### ISSUE TITLE
Cache metadata source files needs to store windows path for windows.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#1008]
Cache metadata for serialized source file paths should store the Windows-style path for Windows since the drive letter could be different and storing in Unix-style would not capture the difference.

From https://github.com/GoogleContainerTools/jib/pull/995#discussion_r218589436

**Comment by coollog** [comment]
Irrelevant now that the new cache mechanism is in place.

**Comment by chanseokoh** [comment]
Maybe we should remove `LayerEntry.getAbsoluteSourceFileString()` and have `LayerEntriesSelector.LayerEntryTemplate` just call `layerEntry.getSourcePath()` below? `getAbsoluteSourceFileString()` strips out the drive letter, so I feel like we shouldn't use or need it.

```java
    @VisibleForTesting
    LayerEntryTemplate(LayerEntry layerEntry) {
      sourceFile = layerEntry.getAbsoluteSourceFileString();
      extractionPath = layerEntry.getAbsoluteExtractionPathString();
    }
```

**Comment by coollog** [comment]
@chanseokoh That's true - we should probably change `getAbsoluteSourceFileString` to return `sourceFile.toAbsolutePath().toString()` directly then since we still do want the absolute path rather than a relative path.
