### ISSUE TITLE
Docker error output is not being captured

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1013]
> The error message is saying Jib failed to run "docker load" which loads the built image into your local docker daemon. The `IOException` is supposed to include the error output of "docker load", but I see it's empty. That said, I wonder why. What is clear is that, running the "docker load" command from Jib failed.

_Originally posted by @chanseokoh in https://github.com/GoogleContainerTools/jib/issues/991#issuecomment-422077844_

**Comment by chanseokoh** [comment]
Reopening. There is still a case an error is not being captured when using Maven 0.9.13:

https://github.com/GoogleContainerTools/jib/issues/330#issuecomment-434603230

**Comment by chanseokoh** [comment]
Oh, seems like Maven 0.9.13 doesn't have the fix #1064 in it.

**Comment by TadCordle** [comment]
Yeah, 0.9.12 and 0.9.13 were branched straight from the 0.9.11 tag with specific patches. So this is already fixed for 0.10.0.
