### ISSUE TITLE
Keep track of local dependencies in files task/goal

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1027]
E.g. in our simple test project, there is a libs/dependency-1.0.0.jar file that is not a snapshot/project dependency, but should still be watched by skaffold since its contents/name may change without anyone changing the build file.

We should check if this is possible in Maven as well.

Related to #1021

**Comment by loosebazooka** [comment]
It's actually pretty annoying and complicated to do this in Maven, but pretty easy in Gradle, so we might need to support it for gradle. Having said that, I think we should hold off doing this. Large projects can usually be combined using maven-artifacts or project artifacts.

**Comment by loosebazooka** [comment]
Someone can open a new issue for this if they want to. I don't think there's a reason to support this at the moment, it's an obscure way of building.
