### ISSUE TITLE
Cannot acccess 'image'

### ISSUE THREAD

**Issue by juergenzimmermann** [GoogleContainerTools/jib#1060]
After upgrading to 0.9.11 I get this error message for build.gradle.kts:
`Cannot acccess 'image': It is public in <anonymous>`

![grafik](https://user-images.githubusercontent.com/734334/46186726-5471b100-c2e0-11e8-935f-9b6b60718cd7.png)

**Comment by loosebazooka** [comment]
That's weird, I mean if it's public, shouldn't it be accessible? Does moving back to 0.9.10 make the error go away?

**Comment by coollog** [comment]
Hi @juergenzimmermann , we have just released `v0.9.12` with the fix for this issue.

**Comment by breandan** [comment]
Thanks! This also fixes the issue I am having. The Gradle Kotlin DSL syntax for collections is still a little bit unpleasant. It requires writing something like `jib.container.jvmFlags = listOf(...)`. It would be nice if this were just `jib.container.jvmFlags(...)`, where the method took vararg parameters.

**Comment by coollog** [comment]
@breandan Thanks for letting us know! We'll take a look into improving this.
