### ISSUE TITLE
Allow using variables in app arguments

### ISSUE THREAD

**Issue by ST-DDT** [GoogleContainerTools/jib#1082]
**Description of the issue**:

Sometimes it is not possible to specify the all/best choice of parameters at compile/packaging time.
Namely the `-Xmx?G` option may only be known at runtime.
If I run it locally I might only need 500MiBs for testing purposes, but during production I might need 10GiB to serve/cache enough requests.

Thats why I tried to inject a variable into the jvmArgs 

````xml
<jvmFlags>
    <jvmFlag>$ADDITIONAL_OPTIONS</jvmFlag>
</jvmFlags>
````

However this value was sent straight to the runner without getting resolved.

`Main class "$ADDITIONAL_OPTIONS" not found`

**Expected behavior**:

If `ADDITIONAL_OPTIONS` is not set (as env variable) it should be replaced by nothing.
If `ADDITIONAL_OPTIONS` is set (as env variable) it should be replaced by that value.

The behavior should be similar to calling this from the command line:

````bash
export ADDITIONAL_OPTIONS=-Xmx1G
java -Dfoo=bar $ADDITIONAL_OPTIONS -cp ...
````

**Environment**: 

* Java 8
* Maven 3.5
* Spring 5

**Comment by coollog** [comment]
Hi @ST-DDT , I believe your issue can be solved using `JAVA_TOOL_OPTIONS`: https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-set-parameters-for-my-image-at-runtime Feel free to re-open if this is solution does not work for you.
