### ISSUE TITLE
If no version is specified, the tag should default to "latest" instead of "unspecified"

### ISSUE THREAD

**Issue by sschuberth** [GoogleContainerTools/jib#1096]
**Description of the issue**:

When running `./gradlew jibDockerBuild` the Docke rimage is always also tagged with "unspecified" even if a tag is specified via `jib.to.tags`.

**Expected behavior**:

Only the tags specified via `jib.to.tags` are used to tag the Docker image.

**Steps to reproduce**:

Run `./gradlew jibDockerBuild` with the configuration as mentioned below. See https://github.com/heremaps/oss-review-toolkit/blob/jib/cli/build.gradle to reproduce.

**Environment**:

Ubuntu 18.04

**`jib-gradle-plugin` Configuration**: 
```groovy
plugins {
    id 'com.google.cloud.tools.jib' version '0.9.11'
}

jib.to.tags = ['latest']
```

**Log output**:

```
Parallel execution with configuration on demand is an incubating feature.
Tagging image with generated image reference cli:unspecified. If you'd like to specify a different tag, you can set the jib.to.image parameter in your build.gradle, or use the --image=<MY IMAGE> commandline flag.
warning: Base image 'gcr.io/distroless/java' does not use a specific image digest - build may not be reproducible

Containerizing application to Docker daemon as cli:unspecified, cli...

Getting base image gcr.io/distroless/java...
Building dependencies layer...
Building classes layer...
Finalizing...
Loading to Docker daemon...

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.here.ort.Main]

Built image to Docker daemon as cli:unspecified, cli

BUILD SUCCESSFUL in 9s
68 actionable tasks: 1 executed, 67 up-to-date
```

**Comment by chanseokoh** [comment]
Hi @sschuberth,

Try `jib.to.image = 'cli:latest'` and remove `jib.to.tags`. `jib.to.tags` is for _additional_ tags you want to create on top of your default image (which is `cli:unspecified` in this case). Will that work?

**Comment by coollog** [comment]
The `unspecified` comes from the fact that the project does not have a version specified, as Jib uses the project version as the default tag if `jib.to.image` is not configured.

**Comment by sschuberth** [comment]
@chanseokoh, yes using `jib.to.image = 'cli:latest'` or simply `jib.to.image = 'cli'` works as expected. I have to say I find the current behavior a bit unintuitive. Wouldn't it make more sense to use just `latest` as the default version?

**Comment by chanseokoh** [comment]
Makes sense, especially when considering that `jib.to.image = 'cli'` gives you `cli:latest` instead of `cli:unspecified`.

**Comment by coollog** [comment]
Yea, I think we can change the behavior to not include a default tag if the version is `unspecified`.
