### ISSUE TITLE
Gradle: Running jibDockerBuild task only on subproject results in strange error

### ISSUE THREAD

**Issue by sschuberth** [GoogleContainerTools/jib#1104]
**Description of the issue**:

Usually, if a Gradle plugin is only applied in a subproject of a multi-project, tasks provided by that plugin are only available for that subproject. This does not seem to be the case for the `jib-gradle-plugin`, however, and the resulting behavior is a bit confusing.

I have a `cli` java application project that depends on a `lib` java-library project in the same multi-project. The `jib-gradle-plugin` is only applied in the `cli` project.

**Expected behavior**:

I'd expect `./gradlew cli:jibDockerBuild` to work. Instead it gives

```
> Configure project :analyzer
Project evaluation failed including an error in afterEvaluate {}. Run with --stacktrace for details of the afterEvaluate {} error.

FAILURE: Build failed with an exception.

* Where:
Build file './analyzer/build.gradle' line: 2

* What went wrong:
A problem occurred evaluating project ':analyzer'.
> Failed to apply plugin [id 'org.gradle.java-library']
   > Cannot change dependencies of configuration ':analyzer:api' after it has been included in dependency resolution.

```

Note that running `./gradlew jibDockerBuild` (without `cli:`) works.

**Steps to reproduce**:

Check out https://github.com/heremaps/oss-review-toolkit/tree/jib and run `./gradlew cli:jibDockerBuild`.

**Environment**:

Ubuntu 18.04

**`jib-gradle-plugin` Configuration**: 
```groovy
plugins {
    id 'com.google.cloud.tools.jib' version '0.9.11'
}

jib.to.image = 'ort:latest'
```

**Comment by coollog** [comment]
Hi @sschuberth , I tried running your build as mentioned and it seemed to have worked:

```
$ ./gradlew cli:jibDockerBuild
Parallel execution with configuration on demand is an incubating feature.

> Task :utils-test:dokka
No source directories found: skipping dokka generation

> Task :utils-test:dokkaJavadoc
No source directories found: skipping dokka generation
warning: Base image 'gcr.io/distroless/java' does not use a specific image digest - build may not be reproducible

Containerizing application to Docker daemon as ort...

Getting base image gcr.io/distroless/java...
Building dependencies layer...
Building classes layer...
Finalizing...
Loading to Docker daemon...

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.here.ort.Main]

Built image to Docker daemon as ort

BUILD SUCCESSFUL in 5s
68 actionable tasks: 6 executed, 62 up-to-date
```

**Comment by sschuberth** [comment]
Interesting, thanks for trying. I wonder what's different in our setups then... thanks to using the Gradle wrapper everything Gradle-related should be the same...

**Comment by chanseokoh** [comment]
I think the messages "an error in afterEvaluate" and "Cannot change dependencies of configuration ... after it has been included in dependency resolution" are giving some clue. Maybe the error behavior depends on the order of task execution?

**Comment by sschuberth** [comment]
That's basically a good idea, but I now also tried with

    ./gradlew -Porg.gradle.configureondemand=false -Porg.gradle.parallel=false cli:jibDockerBuild

to rule out any non-deterministic task execution, and it still fails for me 😢

**Comment by loosebazooka** [comment]
@sschuberth sorry for delaying the followup. Have you figured this out? I cannot access your test project.

**Comment by sschuberth** [comment]
@loosebazooka, no, sorry, I've switched to using https://github.com/bmuschko/gradle-docker-plugin by now.

**Comment by loosebazooka** [comment]
Ah okay @sschuberth, I'd love to take a look at the issue again if you have a commit I can check out but I'll close this for now.
