### ISSUE TITLE
Is there a way to add a volume in image ?

### ISSUE THREAD

**Issue by laurentleseigneur** [GoogleContainerTools/jib#1121]
**Image don't allows to have a volume**:

my project is a CLI that uses a folder as arg to run. I would like to run produced docker image with a volume to bind to some host folder

**Expected behavior**:

add some *volume* parameter when configuring maven/gradle plugin

**Comment by coollog** [comment]
Hi @laurentleseigneur , thanks for your suggestions! Currently we do not provide configuration for setting the volume, but we'll look into this as a potential feature.

**Comment by GuustavoPaiva** [comment]
Hey @coollog wanna some help with these? This seems cool.

**Comment by coollog** [comment]
Hey @GuustavoPaiva , we’d be glad to have your help on this! Let us know if you have any questions. One thing is that this is probably better done as multiple PRs, like one for the `jib-core` changes, one for the `jib-maven-plugin` changes, and one for the `jib-gradle-plugin` changes.

**Comment by coollog** [comment]
@GuustavoPaiva , let us know if you'd like to handle the `jib-maven-plugin`/`jib-gradle-plugin` changes as well!

**Comment by GuustavoPaiva** [comment]
Hey @coollog I plan to do this by the end of this week, is it fine?

**Comment by chanseokoh** [comment]
@GuustavoPaiva sure, we welcome your help.

**Comment by chanseokoh** [comment]
Fixed by #1278. @GuustavoPaiva thanks again for your help!

**Comment by laurentleseigneur** [comment]
thanks you all for adding this feature in Jib!
