### ISSUE TITLE
Custom registry using X-AUTH HTTP header for auth

### ISSUE THREAD

**Issue by zy475459736** [GoogleContainerTools/jib#1135]
I have been using the spotify's maven plugin(customized to a CI servie) to build a docker image ,then  push it to a registry of my company.
I do not know the specific implement of our registry along with the auth system.What I do know is after building the image, I push/post it to a http url instead of https.like http://registry.com/app/ciservice:0.0.1 .
And used a specific header like X-AUTH: ${TOKEN} for auth.

I consider jib's ability to build image without docker daemon is quite fancinating and can be quite useful.But when I run 
> mvn jib:build 

I have no idea how I can push the image to our customized dockerregistry and customized auth system.As I have mentioned , a post request to http url along with a specific header.

So, how can I achieve my purpose ? If customizing the jib-maven-plugin is unavoidable, which part of the code should I start with.

**Comment by briandealwis** [comment]
Jib supports building to a tar with the `jib:buildTar` goal, with the resulting tar placed in `target/jib-image.tar`.  What format does your registry accept?

**Comment by chanseokoh** [comment]
Hi @zy475459736,

I see there is currently no way to set the `X-Auth` header for auth.

We set the `Authorization` header (using the basic access authentication scheme), which we set by calling `Reqeust.setAuthorization()`. The places where we set the header are

- [`RegistryAuthenticator.authenticate()`](https://github.com/GoogleContainerTools/jib/blob/v0.9.11-maven/jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryAuthenticator.java#L272)
- [`RegistryEndpointCaller.call()`](https://github.com/GoogleContainerTools/jib/blob/v0.9.11-maven/jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java#L226)

And it looks like your registry doesn't support HTTPS, so you will need to set `allowInsecureRegistries` and `-DsendCredentialsOverHttp`, but you should know the danger and security risks of using them.

**Comment by chanseokoh** [comment]
And I got curious: how do you set the `X-Auth` with the Spotify plugin? Did you customize it yourself or does it come with the feature to configure it?

**Comment by briandealwis** [comment]
@zy475459736 How are you pushing/posting your image?  With `docker push`?  Or some other means?

**Comment by chanseokoh** [comment]
Oh, forgot to say this: if you have other means to push an image from your local Docker daemon to your company registry, note that `mvn jib:dockerBuild` will push an image to your local daemon instead of a remote registry. You may be able to use this workaround too.

**Comment by zy475459736** [comment]
@briandealwis Thanks for your remind of command mvn jib:buildTar.I had a try and I think it does satisfy the purpose for I can get the same image from the tars. 
But as you have mentioned, although I got the tars, I still need the docker daemon to obtain the images and push them to the registry.It seems there is no other way left for me to reach my goal( image stored in registry) directly .
 I will check with my colleague about the details of the registry next week, to see whether the transition from tars to images can be done by the registry or some other way.

**Comment by zy475459736** [comment]
@chanseokoh the Spotify maven plugin supports pushing  the images generated to registry.
I have done some digging on the plugin and find out that the both the build and push goal of Spotify's plugin are ultimately done by docker daemon.It is more like a Client/Server ,the plugin acting as a client.

**Comment by zy475459736** [comment]
@chanseokoh Thanks for your warning about the risk HTTP has. But the registry can only be accessed inside the company, and the colleague who maintains the registry is busy with some other projects so...But thanks anyway.
My boss just wants to **have the image without docker daemon** so we can have more convenience when we design the CI/CD and some other infrastructure.
I will do some digging on the jib code and try to get my X-Auth-header added next week.

**Comment by briandealwis** [comment]
@zy475459736 out of curiosity, were you able to make this work?

**Comment by zy475459736** [comment]
@briandealwis Somehow, I do achieve my goal.
We have devloped an OAuth and ContainerRegistry of our own running inside the company.

The reason why I raised this issue is that the CI-service I devloped before relyed on the Spotify's maven-plugin to transfer the code to Docker Image and to push it to the ContainerRegistry if necessary.
> The goods to use this plugin ,as have been mentioned in the [video ](https://www.youtube.com/watch?v=H6gR_Cv4yWI),there will be no need for Java devlopers to write the Dockerfile which is kind of like a script,not to mention the size of the image also depends on how you write the Dockerfile. 
> The Spotify's maven-plugin use the info you offer(the orgin version of the plugin is on the pom.xml, I did some work here so the devloper can edit the info on the webUI... And also some other functions) to arrange a Dockerfile and then connects to Docker Daemon to do the **docker build** & **docker push** .

I did some customization on the Spotify's plugin so it can be compatible with the OAuth and the ContainerRegistry I mentioned before: **in short, add the token I get from OAuth-WebUI (which is long-term effective for now because the whole system is not public anyway) to the plugin, it will use the token as a header to push it to a url (which is a HTTP for now).**

**Comment by zy475459736** [comment]
@briandealwis  com.google.cloud.tools.jib.builder.BuildSteps.forBuildToDockerRegistry()
```
public static BuildSteps forBuildToDockerRegistry(BuildConfiguration buildConfiguration) {
    return new BuildSteps(
        DESCRIPTION_FOR_DOCKER_REGISTRY,
        buildConfiguration,
        stepsRunner ->//steps:
            stepsRunner
                .runRetrieveTargetRegistryCredentialsStep()//retrieve the credential you arrange,like username&password
                .runAuthenticatePushStep()//the OAuth system has a api ,so I can use username&password to exchange for an access token for pushing.
                .runPullBaseImageStep()
                .runPullAndCacheBaseImageLayersStep()
                .runPushBaseImageLayersStep()
                .runBuildAndCacheApplicationLayerSteps()
                .runBuildImageStep()
                .runPushContainerConfigurationStep()
                .runPushApplicationLayersStep()
                .runFinalizingPushStep()
                .runPushImageStep()
                .waitOnPushImageStep());
  }
```
And thanks for the suggestion @chanseokoh offered, I set ```allowInsecureRegistries``` and ```-DsendCredentialsOverHttp``` so I can push the image to HTTP url.
I can do some more customization to make jib more suitable for use inside my company. Anyway, it does satisfy the requirement (build and push a image without DockerDaemon and I can pull it from the ContainerRegistry).

**Comment by zy475459736** [comment]
[Reference about container registry auth. ](https://docs.docker.com/registry/spec/auth/token/) In case someone might need it.

**Comment by coollog** [comment]
@zy475459736 Thanks for providing all these details! Glad this all works for you now.

**Comment by chanseokoh** [comment]
@zy475459736 I see. So your requirement was not that you need to set a different header (i.e., `X-Auth-Token:` instead of `Authroization:`), but rather you mistakenly thought Jib could not push to your registry without knowing Jib by default doesn't pass auth to HTTP (although it sounds like you still needed some customization to Jib to retrieve the auth info from your Web UI and make Jib to pick it up).
