### ISSUE TITLE
Support extra classpath folders at runtime

### ISSUE THREAD

**Issue by victornoel** [GoogleContainerTools/jib#1157]
Currently, it is possible to:
- add files to the image both within the classpath (via resources folder) or the filesystem (via the jib folder).
- add files to the container via the use of volumes
- add files to the resources directory via volumes mounted inside `/app/resources`.

But it is not possible to add folders to the classpath directly.

For example, I have an image built with jib and a folder named `config` on the host containing a `logback.xml` file, there is no way to add the whole `config` directory as a classpath entry, I have to mount each file one by one into `/app/resources`.

I'm not sure how to solve this though…

**Comment by chanseokoh** [comment]
Hi @victornoel,

I wonder if you can use the following workaround. Say the config folder is `$CONFIG` (your path to the `config` folder).

Copy `$CONFIG/*` into `<project root>/src/main/jib/app/resources`. That is, if you have `$CONFIG/logback.xml`, you'll placed it at `<project root>/src/main/jib/app/resources/logback.xml`. (If you need to copy files during/after the build process, [this FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-need-to-add-files-generated-during-the-build-process-to-a-custom-directory-on-the-image) may help.)

Then, the files will be placed under `/app/resources` in the image (e.g., `/app/resources/logback.xml`). You may even do this with `/app/classes`.

**Comment by victornoel** [comment]
@chanseokoh yes I do, it is to specify some configurations file that can change when the application is deployed. `logback.xml` is an example, but there are more (and that's why I need the whole directory to be mounted as a classpath folder).

**Comment by chanseokoh** [comment]
I see. How about this workaround?

You'll see the what entrypoint your image will have during building, e.g.,

```
Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, example.HelloWorld]
```

Then you customize the entrypoint (using the `container.entrypoint` parameter) so that it becomes

`java -cp /app/resources:/app/classes:/app/libs/*:/your/mounted/config/folder example.HelloWorld`

**Comment by victornoel** [comment]
@chanseokoh indeed that's seems to be a valid workaround, thanks for the idea :)

**Comment by victornoel** [comment]
@chanseokoh in the end, it's not great, because it doesn't play well with the other options such as `jvmFlags` (which are used only when the entrypoint is not overridden).

Any way to get a new configuration feature for this? :)

**Comment by chanseokoh** [comment]
When you are not customizing the default entrypoint (i.e., when not defining `container.entrypoint`), Jib just adds the `container.jvmFlags` values to the default entrypoint. That's why `container.jvmFlags` and `conatiner.mainClass` are ignored when you define your own entrypoint. So, you can just directly embed the JVM flags in `container.entrypoint`. Do you think this will work?

Another potential option (based on which base image you use) could be to use another environment variable: https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#jvm-flags

**Comment by victornoel** [comment]
@chanseokoh yes, you are right, this makes sense, I didn't think about it enough :P

**Comment by TadCordle** [comment]
Closing since it sounds like there's a valid workaround.

**Comment by victornoel** [comment]
@TadCordle honestly it's more of a hack than a acceptable workaround, not very maintainable: it is relevant to think that one wants to inherit from the command line built by jib while adding some extra directories to the classpath.

Personally, I abandoned the idea of changing the classpath and had to modify my application in the end…

**Comment by TadCordle** [comment]
Ok, in that case I will reopen. The way the thread ended made it sound like everything was acceptable.

**Comment by victornoel** [comment]
@TadCordle no problem, thanks :)

**Comment by chanseokoh** [comment]
Related #894

**Comment by briandealwis** [comment]
Fixed by #1642

**Comment by victornoel** [comment]
@briandealwis thanks :)

**Comment by TadCordle** [comment]
@victornoel @kurczynski @tellisnz-shift version 1.2.0 has been released with the `<container><extraClasspath>` / `jib.container.extraClasspath` configuration parameter!
