### ISSUE TITLE
Add login tasks.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#116]
Example:

```commandline
mvn jib:login -Djib.username=oauth2accesstoken -Djib.password=secret -Djib.registry=gcr.io
mvn jib:login -Du=_json_key -Dp="$(cat keyfile.json)" -Dregistry=https://gcr.io
```

Mimics the API of [`docker login`](https://docs.docker.com/engine/reference/commandline/login/)
Jib stores the credentials.

**Comment by chanseokoh** [comment]
This seems to add more options for auth, which I feel may be good and bad. For example, as of now Jib can read auth info from multiple places, e.g., `~/.m2/settings.xml` or `~/.docker/config` (which can be updated with `docker login` and other various `docker-credential-*` helpers, I suppose?). It's not clear which wins when there are multiple settings competing. Adding one more place could increase the complexity, and it might complicate the task to diagnose customer auth issues.

**Comment by chanseokoh** [comment]
Will revisit this if needed.
