### ISSUE TITLE
Create a Permissions class

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1165]
To make #1156 less of a mess, create a `Permissions` class to allow for
- Type safety - can be parsed from a `String` instead of an `int` to avoid octal vs. decimal confusion
- Compactness - internal representation can still be an `int`
- Ease of use - relevant methods on this class instead of using a helper and doing multiple back-and-forth conversions
- Extendability - should be easy to add operations if/as we need them

Right now we only really need two methods:
```
/* Parse/validate an octal String (e.g. "755"). */
static Permissions fromString(String octalString);

/* Set the permissions on a TarArchiveEntry. */
void setOnTarArchiveEntry(TarArchiveEntry entry);
```

but we can decide to add stuff depending on how people want to use the library.
```
static Permissions fromSet(Set<PosixFilePermission> octalString);

Permissions addPermission(PosixFilePermission permission);

Set<PosixFilePermission> getPermissionSet();

int getPermissionBits();

// etc.
```

**Comment by coollog** [comment]
Looks good! 

I think we can add just the `static Permissions fromSet(...)` (probably `fromPosixFilePermissions`?) for library users who wish to use the JDK class. 

Some other naming suggestions: 

- probably `FilePermissions` to be more specific?
- `setOnTarArchiveEntry`, which usually would mean setting a field `onTarArchiveEntry` - perhaps change to `applyToTarArchiveEntryMode`?
- could name the static factories all just `from`, but might not be good if we want to support other string formats in the future

**Comment by TadCordle** [comment]
>but might not be good if we want to support other string formats in the future

In that case, maybe `fromString` isn't a good name either. `fromOctalString`?

**Comment by chanseokoh** [comment]
One thing I'm not so thrilled about is that it has a dependency on some particular external library (Apache Commons Compress). May not matter much if this is exclusively for internal usage.

And I agree the argument type should be `Set`, not `ImmutableSet`. There is no need to force callers to convert a set to `ImmutableSet`. And for return values, `Set` still makes sense, since it's not like the class maintains a reference to them.

We also need to make it clear that this class only cares about the right-most 9 permission bits for all operations.

`fromOctalString` sounds good.

**Comment by TadCordle** [comment]
>One thing I'm not so thrilled about is that it has a dependency on some particular external library (Apache Commons Compress). May not matter much if this is exclusively for internal usage.

That's true. I don't think this class is going to be exclusively for internal usage. It might be worth it to just leave out `applyToTarArchiveEntryMode` and use `getPermissionBits`.

**Comment by coollog** [comment]
Yea, this class will be user-facing, so `getPermissionBits` sounds good instead of requiring `TarArchiveEntry`.
