### ISSUE TITLE
upgrade to maven-surefire-plugin 2.22.1 

### ISSUE THREAD

**Issue by sullis** [GoogleContainerTools/jib#1175]
**Description of the issue**:

upgrade to maven-surefire-plugin 2.22.1 

**Expected behavior**:

upgrade to maven-surefire-plugin 2.22.1 

**Steps to reproduce**: 

n/a

**Environment**: 

n/a

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by TadCordle** [comment]
Fixed by #1174
