### ISSUE TITLE
Add layer description to history

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#1179]
Feedback from @anthonydahanne after code one talk. Take #840 further.

Instead of generic entries, add description of what the layer is holding. "Dependencies", "Snapshot Dependencies", "Classes", "Resources"

**Comment by anthonydahanne** [comment]
thanks for adding this issue to the backlog !

**Comment by coollog** [comment]
@anthonydahanne Thanks for suggesting this!

**Comment by TadCordle** [comment]
Fixed with #1198
