### ISSUE TITLE
Sometimes Travis build times out; increase the timeout or look into test

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1181]
I think `PackageGoalsMojoTest` often takes a long time. Travis seems to be slow, so we may need to increase the timeout.

Or, if it is not Travis being slow but `PackageGoalsMojoTest` consistently taking an unreasonably long time, we may need to look into why it's slow.
```
[INFO] Running com.google.cloud.tools.jib.maven.skaffold.PackageGoalsMojoTest

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by briandealwis** [comment]
How often are you seeing this @chanseokoh?

When I run the tests locally, PackageGoalsMojoTest takes 12 seconds:
```
[INFO] Running com.google.cloud.tools.jib.maven.skaffold.PackageGoalsMojoTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.988 s - in com.google.cloud.tools.jib.maven.skaffold.PackageGoalsMojoTest
```

Travis seems to periodically lose the plot — we sometimes get similar errors on CT4E. Indeed we went through a period in February where we had lots of timeouts (https://github.com/GoogleCloudPlatform/google-cloud-eclipse/issues/2803).

**Comment by chanseokoh** [comment]
I see. I guess then Travis is sometimes very slow or just stalls. I saw this timeout twice today on two different PRs, but it might have been a temporary problem today. I think we can close this and reopen if necessary.

**Comment by chanseokoh** [comment]
Reopening. Just saw this now. At `PackageGoalsMojoTest` again.

```
INFO] Running com.google.cloud.tools.jib.maven.skaffold.PackageGoalsMojoTest
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by chanseokoh** [comment]
Happened twice actually. Links will show the same error (unless someone restarts the failed Travis builds):

https://travis-ci.org/GoogleContainerTools/jib/builds/445719679?utm_source=github_status&utm_medium=notification
https://travis-ci.org/GoogleContainerTools/jib/builds/445719484?utm_source=github_status&utm_medium=notification

**Comment by chanseokoh** [comment]
Third time: https://travis-ci.org/GoogleContainerTools/jib/builds/445734098?utm_source=github_status&utm_medium=notification

It's always `PackageGoalsMojoTest`, so I think there's something special about that. At least it's true that these file list tests take some time. From a success log:

```
[INFO] Running com.google.cloud.tools.jib.plugins.common.TimerEventHandlerTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.009 s - in com.google.cloud.tools.jib.plugins.common.TimerEventHandlerTest
[INFO] Running com.google.cloud.tools.jib.plugins.common.MainClassResolverTest
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.346 s - in com.google.cloud.tools.jib.plugins.common.MainClassResolverTest
[INFO] Running com.google.cloud.tools.jib.plugins.common.ConfigurationPropertyValidatorTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.211 s - in com.google.cloud.tools.jib.plugins.common.ConfigurationPropertyValidatorTest
[INFO] Running com.google.cloud.tools.jib.maven.skaffold.PackageGoalsMojoTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 37.238 s - in com.google.cloud.tools.jib.maven.skaffold.PackageGoalsMojoTest
[INFO] Running com.google.cloud.tools.jib.maven.skaffold.FilesMojoTest
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.058 s - in com.google.cloud.tools.jib.maven.skaffold.FilesMojoTest
[INFO] Running com.google.cloud.tools.jib.maven.MavenLayerConfigurationsTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.175 s - in com.google.cloud.tools.jib.maven.MavenLayerConfigurationsTest
```

**Comment by briandealwis** [comment]
Another: https://api.travis-ci.org/v3/job/446357609/log.txt

**Comment by loosebazooka** [comment]
I wonder if it has something to do with it downloading a snapshot dependency

**Comment by chanseokoh** [comment]
Haven't seen this for a long time.
