### ISSUE TITLE
Jib Maven plugin unable to resolve gitlab environment variables CI_REGISTRY_USER and CI_REGISTRY_PASSWORD

### ISSUE THREAD

**Issue by raininglotus** [GoogleContainerTools/jib#1191]
**Description of the issue**: I am using jib-maven plugin to build , create a docker image and push the same to gitlab container registry. While pushing I use the following
```xml
<to>
<auth>
<username>$CI_REGISTRY_USER</username>
<password>$CI_REGISTRY_PASSWORD</password>
</auth>
</to>
```

But when the gitlab-ci executes this plugin, these environment variables are not resolved to actual values and hence authentication to gitlab container registry fails. 

Also tried and did not work.
```xml
<to>
  <image>whatever</image>
  <auth>
    <username>${env.CI_REGISTRY_USER}</username>
    <password>${env.CI_REGISTRY_PASSWORD}</password>
  </auth>
</to>
```

I also tried to pass in these values as mvn properties and that did not work either. 

WORKAROUND:

I am currently using a custom .m2/settings.xml and .m2/settings-security.xml to add the gitlab user , password (token) ..encrypt the same and the master password(encrypted ) is in the settings-security.xml. I pass these custom settings files as mvn options

**Expected behavior**:
Authentication in <to> should work. 
**Steps to reproduce**: 

**Environment**: 

**`jib-maven-plugin` Configuration**: 
```xml
	<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>0.9.13</version>
				<configuration>
					<from>
						<image>someimage</image>
					</from>
					<to>
						<image>imagename:imagetag</image>
					</to>
					<!--<extraDirectory>target</extraDirectory>-->
					<container>
						<jvmFlags>
							<jvmFlag>-Dspring.profiles.active=${app.deploy.env}</jvmFlag>
			
						</jvmFlags>
						<mainClass>mainclass</mainClass>
						<ports>
							<port>8080</port>
						</ports>
						<format>Docker</format>
						<useCurrentTimestamp>true</useCurrentTimestamp>
					</container>
					<allowInsecureRegistries>true</allowInsecureRegistries>
				</configuration>
				<executions>
					<execution>
						<id>default</id>
						<phase>install</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```
**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @raininglotus,

First of all, AFAIK, the syntax `<username>$CI_REGISTRY_USER</username>` won't work. It should be `<username>${env.CI_REGISTRY_USER}</username>`.

And it sounded like (correct me if I'm wrong) you can build and push an image locally (i.e., from your computer) with `<username>${env.CI_REGISTRY_USER}</username>`. So, one possibility I'm thinking is that, locally, `$CI_REGISTRY_USER` and `$CI_REGISTRY_PASSWORD` are not defined, effectively resulting empty username and password settings (i.e., `<username></username><password></password>`). And perhaps you have set up some other means for auth, which makes a push work.

And I genuinely think the environment variables are not set in the CI environment, as with Jib 0.9.13, the I've double checked that `<username>` and `<password>` certainly work. To see if some environment variables are actually defined in the CI, you can do `mvn help:system`. Try that on both your computer and the CI env.
