### ISSUE TITLE
jib-maven-plugin randomly fails on the docker authentication

### ISSUE THREAD

**Issue by strangeman** [GoogleContainerTools/jib#1192]
jib-maven-plugin version: 0.9.13

I use credentials from `~/.docker/config.json` and sometimes build fails with:
```
[INFO] --- jib-maven-plugin:0.9.13:build @ application ---
[INFO] 
[INFO] Containerizing application to private_registry/application:1.7.1-SNAPSHOT...
[INFO] 
[INFO] Retrieving registry credentials for private_registry...
[INFO] Getting base image private_registry/oracle-jdk...
[INFO] Building snapshot dependencies layer...
[INFO] Building resources layer...
[INFO] Building dependencies layer...
[INFO] Building classes layer...
[INFO] The base image requires auth. Trying again for private_registry/oracle-jdk...
[INFO] Retrieving registry credentials for private_registry...
[ERROR] Failed to retrieve authentication challenge for registry that required token authentication
```

But when I restart the build (without any changes) - it runs successfully. How can I debug this behavior? I use Nexus OSS as registry if it matters.

Plugin configuration:
```
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>0.9.13</version>
                <configuration>
                 <to>
                    <image>${dockerregistry.url}/${project.artifactId}:${project.version}</image>
                </to>
                <from>
                    <image>private_registry/oracle-jdk:1.0.0</image>
                </from>
                <container>
                    <jvmFlags>
                        <jvmFlag>-XX:OnOutOfMemoryError=kill -9 %p</jvmFlag>
                        <jvmFlag>-XX:+HeapDumpOnOutOfMemoryError</jvmFlag>
                    </jvmFlags>
                </container>
                </configuration>
                <executions>
                    <execution>
                        <id>build-image</id>
                        <phase>install</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by chanseokoh** [comment]
Are you literally using "private_registry/oracle-jdk:1.0.0" as the base image and "private_registry/application:1.7.1-SNAPSHOT" as the target image? I believe this kind of image reference form points to the Docker Hub registry.

**Comment by strangeman** [comment]
@chanseokoh `private_registry` = `registry.ourdomain.com`, it referenced to our registry address. :)

**Comment by chanseokoh** [comment]
That's what I suspected. One possibility I'm thinking of is that there are multiple distributed registry servers accessible through the `registry.ourdomain.com` address, and you are routed to different servers during the build, which sometimes causes this inconsistent results. Is it possible to fix a server (for example, by putting `registry.ourdomain.com` entry in `/etc/hosts` if using a fixed IP can serve the purpose) and see if that clears the problem?

**Comment by strangeman** [comment]
Nope, we have only one DNS record for our registry. `native` docker pull/push (and io.fabric8.docker-maven plugin) works without any problems.

**Comment by strangeman** [comment]
Hmmm. Can't reproduce. Possibly this was been network issues. I'll try again tomorrow and will close the issue if all will works as expected. Sorry for bothering. :)

**Comment by strangeman** [comment]
Looks like it was the network issues. Can't reproduce now.
