### ISSUE TITLE
Main class was not found error with basic usage

### ISSUE THREAD

**Issue by arun-gupta** [GoogleContainerTools/jib#1194]
Trying this plugin on an existing Maven project:

```
mvn compile http://com.google.cloud.tools :jib-maven-plugin:0.9.11:build -Dimage=foo
```

This is giving the error:

```
Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin
```

Was expecting the project to build the image and figure out the dependencies.

The sample project is at https://github.com/arun-gupta/java-k8s/tree/master/app.

**Comment by arun-gupta** [comment]
Added a maven profile to invoke the plugin from within `pom.xml`:

https://github.com/arun-gupta/java-k8s/blob/master/app/pom.xml#L71-L110

`mvn clean package -Pjib` is still giving the same error:

```
[INFO] --- jib-maven-plugin:0.9.11:build (default) @ app ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.741 s
[INFO] Finished at: 2018-10-25T06:23:38+02:00
[INFO] Final Memory: 33M/330M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.11:build (default) on project app: Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin -> [Help 1]
```

Seems like something basic is missing. Two questions:

- How do I tell jib to include the generated JAR file in the image?
- How do I specify `CMD` equivalent in the plugin?

**Comment by arun-gupta** [comment]
The sample application is at https://github.com/arun-gupta/java-k8s/tree/master/app

It is a [Thorntail](https://github.com/thorntail/thorntail) application which is a fat JAR. The manifest contains the information about main class.

**Comment by patflynn** [comment]
I suspect Jib will be a real pain to use for this kind of project.  Thorntail both builds a war and uses a custom jar entrypoint that's not in your project source to run it. At the moment this is not a usecase that works well (or at all) with Jib which is designed to support flat classpath style simple jar based applications.

We are adding [war support](https://github.com/GoogleContainerTools/jib/issues/431) which perhaps you could run your app on by configuring it with a wildfly base image.

**Comment by arun-gupta** [comment]
I changed the project to be a Spring Boot application. This is the most common use case for a Java app developer. Does it work with that configuration?

**Comment by patflynn** [comment]
Yes it should!

**Comment by arun-gupta** [comment]
Works with https://github.com/arun-gupta/java-k8s/pull/21

**Comment by kameshsampath** [comment]
Same thing happens with a Vert.x based application, though the generated JAR manifest has `Main-Class` attribute in it.

**Comment by chanseokoh** [comment]
@kameshsampath our repo has a Vert.x example (from an external contributor), and perhaps you can add the `main()` method like this: https://github.com/GoogleContainerTools/jib/blob/v1.0.0-rc2-gradle/examples/vertx/src/main/java/example/vertx/MainVerticle.java#L14

**Comment by briandealwis** [comment]
@kameshsampath could you please open a [new issue](https://github.com/GoogleContainerTools/jib/issues/new) and describe your project layout?  Are you using Maven with the jar plugin, and specifying your own MANIFEST.MF?

**Comment by kameshsampath** [comment]
@briandealwis opened a new issue https://github.com/GoogleContainerTools/jib/issues/1470
