### ISSUE TITLE
SNI Support

### ISSUE THREAD

**Issue by Justinmad** [GoogleContainerTools/jib#1199]
**Description of the issue**:
I have a single server configured hosting 2 domains, A.com, docker-registry.B.com,all with their own SSL certificates, when i run 'mvn clean compile jib:build' 

[ERROR] Failed to execute goal com.mistong:jib-maven-plugin:0.9.11:build (default-cli) on project helloworld: Build image failed: hostname in certificate didn't match: <docker-mirror.B.com> != <*.A.com> OR <*.A.com> OR <A.com> -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Steps to reproduce**: 
I think this problem is caused by google-http-client:1.25.0, it uses some deprecated api,
The problem is similar to this one https://marc.info/?l=httpclient-users&m=136880409227976&w=2
**Environment**: 
windows7, maven 3.3.9, jdk8, jib:0.9.11

**Comment by briandealwis** [comment]
@Justinmad What was the image name that you're trying to build to?

As a workaround, you should be able to use the [`allowInsecureRegistries`](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-diagnose-problems-pulling-or-pushing-from-remote-registries) flag to connect.

**Comment by briandealwis** [comment]
@Justinmad it would also be worth [examining the network traffic](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-examine-network-traffic) to see exactly what requests are being made.

**Comment by briandealwis** [comment]
Issue caused by an older JRE (1.8.0_131).  Problem disappeared after switching to the latest JRE (1.8.0_191).
