### ISSUE TITLE
skaffold dev with Jib on Gradle: failure from not being able to create subprocesses

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1206]
We observed that, when running `skaffold dev` with Jib on Gradle for a long time, Jib builds may start to fail  at some point, as it cannot create any more sub-processes. More specifically, the point it can fail is when trying to run a cred helper (e.g., `docker-credential-gcr`). It's also observed that restarting the Gradle daemon clears the problem. This leads us to think there's resource leak or some exhaustion (e.g., running out of available process IDs, the Gradle daemon opening to many file handles without closing it, etc.).

It's not clear who's at fault (Skaffold, Jib, Gradle, etc), or if it is a bug or someone is doing something not correctly.

**Comment by briandealwis** [comment]
Does this happen when making changes, so that rebuilds are done, or does it happen when just watching?

**Comment by TadCordle** [comment]
Fixed by https://github.com/GoogleContainerTools/skaffold/pull/1744
