### ISSUE TITLE
`mvn jib:_skaffold-files` is computationally expensive

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1209]
Running `skaffold dev` with a Maven project (such as https://github.com/GoogleContainerTools/skaffold/tree/master/examples/jib) causes my fans to spin up.

What's odd is that the gradle equivalent is fine.

As a workaround, Running skaffold with `--watch-poll-interval 5000` seems ok.

**Comment by coollog** [comment]
I think it's mostly because running Maven is a lot heavier than Gradle since Gradle sends tasks to the Gradle daemon to execute, whereas Maven is a standalone run every time.

**Comment by loosebazooka** [comment]
I wonder if we could set that as the default on the maven builds?

**Comment by briandealwis** [comment]
What if we reworked the Skaffold/Jib watcher interface to reduce the need to call out to maven/gradle?  If `_skaffold-files`/`_jibSkaffoldFiles` returned a list of (i) locations to monitor and (ii) locations to ignore, then Skaffold could only refresh the list when a new location appeared that didn't match either list?

**Comment by loosebazooka** [comment]
Ah from the project directory? That's interesting. I wonder how we could make that work with the snapshot dependencies?

**Comment by briandealwis** [comment]
Perhaps worth further extending this Skaffold/builder interaction to provide a list of definition files (e.g., `pom.xml` — and parent `pom.xml`s too if local — for `jibMaven`; `build.gradle`, `gradle.properties` for `jibGradle`).
