### ISSUE TITLE
Resolve ENV variables in default entrypoint

### ISSUE THREAD

**Issue by strangeman** [GoogleContainerTools/jib#1213]
`jib-maven-plugin 0.9.13`

Hello. I have problems with ENV variables. I want to pass some Spring parameters to the main class and define them via environment variables. I set `args` to the `$JAR_OPTS`:
```
                <container>
                    <args>
                        <arg>$JAR_OPTS</arg>
                    </args>
                </container>
```
and run container with command like:
```
docker run --rm --name myapp -e 'JAVA_TOOL_OPTIONS=-Xmx1024m' -e 'JAR_OPTS=--spring.config.location=classpath:/application.yml' myapp_image:0.0.1
```
Unfortunately, `JAR_OPTS` not resolve, parameter not work and in process list I see:
```
13351 ?        Ssl    0:15 java -cp /app/resources:/app/classes:/app/libs/* org.example.myapp.MyApplication $JAR_OPTS
```
How can I set `args` via env variables without entrypoint overriding (because I want dynamic detection of main class)?

**Comment by coollog** [comment]
Hi @strangeman , `$JAR_OPTS` won't resolve because the entrypoint is executed without a shell to actually resolve environment variables. One solution is to use a base image that has a shell (like `openjdk:8-jre-alpine`) and set the entrypoint to run in shell form, or invoke your docker command like:

```
docker run --rm --name myapp -e 'JAVA_TOOL_OPTIONS=-Xmx1024m' myapp_image:0.0.1 --spring.config.location=classpath:/application.yml
```

**Comment by briandealwis** [comment]
Another alternative is to retrieve the value inside your `main()` rather than pass in the value on the command-line.

**Comment by strangeman** [comment]
@coollog this solution not ideal but better than nothing, thank you. The main reason for using env variables is backward compatibility with our old images, which built with io.fabric8.docker-maven-plugin

**Comment by coollog** [comment]
@strangeman Does using a base image with a shell work for you?
