### ISSUE TITLE
Add `latest` tag by default

### ISSUE THREAD

**Issue by giampaolotrapasso** [GoogleContainerTools/jib#1226]
Add by default the `latest` tag when creating the image. At the moment is possibile to add latest in tags section like this:

```
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>jib-maven-plugin</artifactId>
    <version>0.9.11</version>
    <configuration>
        <to>
            <image>owner/${project.name}:${project.version}</image>
            <tags>
                <tag>latest</tag>
            </tags>
        </to>
    </configuration>
</plugin>
```

However, to give a better "user experience" and to remain minimalist, I think it's better to add this tag by default (like other docker-maven plugins do) and give an option to eventually disable the default.

**Comment by stefanocke** [comment]
If I create a hotfix release (accorging to gitflow, for example), I don't want it to be "latest", since "latest" is my most recent development snapshot.
Unfortunately, jib seem already to have the behavior you request. At least, I always see a "latest" in my repository.  (But maybe this comes from Artifactory, which we use as Docker Registry)

**Comment by giampaolotrapasso** [comment]
@stefanocke you are right, having latest tag may break things with gitflow. But what about having something like `mvn jib:dockerBuild -latest`?  This way I'm not forced to manage latest within the pom for the most recent version and I'm not putting latest into branches/hotfixes.

**Comment by TadCordle** [comment]
>But what about having something like mvn jib:dockerBuild -latest

It's a bit more to type, but I think you could do basically the same thing using the existing `jib.to.image.tags` system property.

`$ mvn jib:dockerBuild -Djib.to.image.tags=latest`

**Comment by giampaolotrapasso** [comment]
Ok, given this indications, I'm going to close it. Thanks for the interest.
