### ISSUE TITLE
Maven: ./scripts/prepare_release.sh should probably not run tests

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1229]
I just tried it, and it runs the whole integration tests. It fails because I don't define the `JIB_INTEGRATION_TESTING_PROJECT` project.

**Comment by coollog** [comment]
This is just as a safeguard measure against potentially releasing something that is not passing integration tests.

**Comment by chanseokoh** [comment]
Makes sense. Not a big deal to run the tests.
