### ISSUE TITLE
COPY command ignores appRoot parameter

### ISSUE THREAD

**Issue by angladem** [GoogleContainerTools/jib#1241]
**Description of the issue**: Using the 0.10.0 release, no matter how appRoot is valued, COPY commands within the generated Dockerfile always copy to /. If no appRoot is specified the entrypoint arguments are indeed valued to /app/<folder> still the COPY commands are COPY <folder> /. 

**Steps to reproduce**: specify an appRoot value within the configuration, launch a mvn jib:exportDockerContext command, check the generated Dockerfile. 

**Environment**: Ubuntu, maven 3.5.2. 

**`jib-maven-plugin` Configuration**: 
```
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>jib-maven-plugin</artifactId>
    <version>0.10.0</version>
    <configuration>
            <from>
                    <image>openjdk:8-jre-alpine</image>
            </from>
            <to>
                    <image>${docker.registry.url}/${project.groupId}.${project.artifactId}:${project.version}</image>
                    <tags>
                            <tag>${project.version}</tag>
                            <tag>latest</tag>
                    </tags>
            </to>
            <allowInsecureRegistries>true</allowInsecureRegistries>
            <container> 
                    <appRoot>test</appRoot>
                    <jvmFlags>
                            <jvmFlag>-XX:+UseCGroupMemoryLimitForHeap</jvmFlag>
                            <jvmFlag>-XX:+HeapDumpOnOutOfMemoryError</jvmFlag>
                            <jvmFlag>-Dspring.main.banner-mode=log</jvmFlag>
                            <jvmFlag>-Dspring.profiles.active=${ENV_NAME}</jvmFlag>
                            <jvmFlag>-Dspring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,/config/</jvmFlag>
                    </jvmFlags>
            </container>
            <extraDirectory>${project.basedir}/src/main/resources/jib</extraDirectory>
    </configuration>
    <executions>
            <execution>
                    <phase>package</phase>
                    <goals>
                            <goal>build</goal>
                    </goals>
            </execution>
    </executions>
</plugin>
```

**Comment by chanseokoh** [comment]
It is the change introduced in 0.10.0 and WAI. Even though it is copying to `/`, directories and files in the source directories are placed in correct directory structures, so the `Dockerfile` should work fine.

**Comment by briandealwis** [comment]
@chanseokoh the classes and resources are put in `/app` and not the configured appRoot.

In the following example, I used `<appRoot>/a/root</appRoot>`:
```
$ mvn compile jib:dockerBuild jib:exportDockerContext
[...]
[INFO] Container entrypoint set to [java, -cp, /a/root/resources:/a/root/classes:/a/root/libs/*, ca.mt.jibexamples.first.Main]
[INFO] Loading to Docker daemon...
[INFO] 
[INFO] Built image to Docker daemon as briandealwis/first:0.0.1-SNAPSHOT
[INFO] 
[INFO] 
[INFO] --- jib-maven-plugin:0.10.0:exportDockerContext (default-cli) @ first ---
[INFO] Created Docker context at /Users/bsd/Manumitting/Projects/GooglePluginEclipse/jibplayground/maven/appRoot/target/jib-docker-context
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.867 s
[INFO] Finished at: 2018-11-12T08:58:21-05:00
[INFO] ------------------------------------------------------------------------
$ 
$ find target/jib-docker-context -type f -print 
target/jib-docker-context/classes/app/classes/ca/mt/jibexamples/first/Main.class
target/jib-docker-context/Dockerfile
target/jib-docker-context/libs/app/libs/guava-21.0.jar
$ 
$ cat target/jib-docker-context/Dockerfile 
FROM gcr.io/distroless/java

COPY libs /
COPY resources /
COPY classes /

ENTRYPOINT ["java","-cp","/app/resources:/app/classes:/app/libs/*","ca.mt.jibexamples.first.Main"]
```

We've removed the `/a/root`.

**Comment by briandealwis** [comment]
@angladem we're considering removing the `exportDockerContext` goal.  Could you please comment on #1219 about how you use the resulting Dockerfile?

**Comment by chanseokoh** [comment]
Huh, it is a regression to ignore the `appRoot` config.

**Comment by angladem** [comment]
For now I used it for checking purposes only. What we are trying to obtain is an image that is generated by JIB but that properly define a user, group and directory ownership. Along the way while trying to check what directories were used, I noticed the appRoot being ignored. 
When the resulting image will be as we expect we won't need the export goal anymore.

**Comment by briandealwis** [comment]
@angladem the Dockerfile generation is generated by a separate code path and so may not actually reflect the reality of the image (as you found!).  If you're looking to check the image set up then you are better to use tools like [container-structure-test](https://github.com/GoogleContainerTools/container-structure-test) or [Dive](https://github.com/wagoodman/dive).
