### ISSUE TITLE
Jib Gradle Plugin - Artifactory Docker Registry

### ISSUE THREAD

**Issue by kittugit** [GoogleContainerTools/jib#1249]
**Description of the issue**: Gradle Jib task fails with "Tried to retrieve authentication method for artifactory.example.com:8080 but failed because: unknown: Unsupported docker v2 repository request for 'artifactory' 

**Expected behavior**:  Gradle Jib task push image to artifactory

**Steps to reproduce**: 
- add the configuration
- run gradle clean jib 

**Environment**: 
Windows, Gradle 4.8.1, Artifactory 6.4.1

**`jib-gradle-plugin` Configuration**: 
```groovy
jib {  
  to {
    image = 'artifactory.example.net:8081/artifactory/test-docker-registry/test-app'
    allowInsecureRegistries = true
    auth {
        username = 'testuser'
        password = 'testpassword'
    }
    
    
  }
}
```

**Log output**: 

17:13:08.577 [DEBUG] [org.gradle.api.Task] TIMING	Pulling base image layer sha256:43b4357066b05434ccb60a247bc8e6b9a67b1cd972a6cb64ed1b02025beae736
17:13:08.577 [INFO] [org.gradle.api.Task] RUNNING	Pulling base image layer sha256:43b4357066b05434ccb60a247bc8e6b9a67b1cd972a6cb64ed1b02025beae736
17:13:08.580 [DEBUG] [org.gradle.api.Task] TIMED	Building and pushing image : 4552.8 ms
17:13:08.580 [INFO] [org.gradle.api.Task] Building and pushing image : 4552.8 ms
17:13:08.581 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 460: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
17:13:05.928 [LIFECYCLE] [org.gradle.internal.operations.DefaultBuildOperationExecutor] 
17:13:05.928 [LIFECYCLE] [org.gradle.internal.operations.DefaultBuildOperationExecutor] > Task :jib FAILED
17:13:08.580 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Execute buildImage for :jib'
17:13:08.582 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Execute buildImage for :jib' completed
17:13:08.582 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
17:13:08.582 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':jib'
17:13:08.582 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Task :jib'
17:13:08.583 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 460: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
17:13:08.585 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Task :jib' completed
17:13:08.585 [INFO] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] :jib (Thread[Daemon worker Thread 13,5,main]) completed. Took 4.719 secs.
17:13:08.586 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 13: released lock on :
17:13:08.586 [DEBUG] [org.gradle.internal.work.DefaultWorkerLeaseService] Worker lease root.1.13 completed (1 worker(s) in use)
17:13:08.586 [DEBUG] [org.gradle.internal.resources.AbstractTrackedResourceLock] Daemon worker Thread 13: released lock on root.1.13
17:13:08.586 [DEBUG] [org.gradle.execution.taskgraph.DefaultTaskPlanExecutor] Task worker [Thread[Daemon worker Thread 13,5,main]] finished, busy: 19.459 secs, idle: 43.601 secs
17:13:08.586 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
17:13:08.587 [DEBUG] [org.gradle.launcher.daemon.server.SynchronizedDispatchConnection] thread 460: dispatching class org.gradle.launcher.daemon.protocol.BuildEvent
17:13:08.588 [DEBUG] [org.gradle.internal.operations.DefaultBuildOperationExecutor] Build operation 'Run tasks' completed
17:13:08.589 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
17:13:08.589 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
17:13:08.589 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
17:13:08.589 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
17:13:08.589 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':jib'.
17:13:08.590 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Tried to retrieve authentication method for artifactory-host.example.net:8081 but failed because: unknown: Unsupported docker v2 repository request for 'artifacoty-host' | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new

**Additional Information**: 
it looks like the issue has been fixed in maven-plugin https://www.jfrog.com/jira/browse/RTFACT-17134

**Comment by briandealwis** [comment]
Hi @kittugit.  Could you please attach [a network trace](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-examine-network-traffic)?

**Comment by kittugit** [comment]
[network_trace.txt](https://github.com/GoogleContainerTools/jib/files/2587771/network_trace.txt)

@briandealwis  thanks for your reply..  It seems, jib is trying to download some files which are blocked  by our corp proxy server.  is there any option to fetch the dependencies through artifactory server?  if not, if we allow the url 'https://gcr.io/v2/distroless/java/" in the proxy, will it be fixed?  Thanks for looking into this.

**Comment by briandealwis** [comment]
@kittugit you can set the base image using the [`from.image`](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#from-closure) to reference an image hosted on your Artifactory registry.  So you can either push the image to Artifactory, or you might be able to configure Artifactory to act as a proxy.

**Comment by TadCordle** [comment]
Closing, feel free to reopen if the problem persists.
