### ISSUE TITLE
Pushing to Nexus

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/jib#1250]
Someone mentioned that Jib fails to push to Nexus (when it’s used as a docker registry). Jib seems to receive xml instead of json, or something along those lines.

I don’t have any more details but it might be worth trying.

**Comment by TadCordle** [comment]
I haven't used Nexus, but I did a quick search and it looks like it's possible to configure Nexus to respond with either xml or json. It's possible they just need to configure something on their repository to get it working.

https://stackoverflow.com/questions/26365371/how-to-get-results-from-sonatype-nexus-rest-api-in-json-format

**Comment by TadCordle** [comment]
We've had [Nexus issues in the past](https://github.com/GoogleContainerTools/jib/search?q=nexus&type=Issues) as well, but they were all authentication issues that we ended up fixing. So I think I'm going to close this. Feel free to reopen if the problem comes up again!

**Comment by briandealwis** [comment]
I just verified that I was able to push to a local nexus registry with no issue.  They're likely trying to push to the Nexus web interface (usually port 8081) rather than the configured registry port.  Here's what I see when I do that:

```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.12-SNAPSHOT:build (default-cli) on project first: Build image failed: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
[ERROR]  at [Source: (String)"
[ERROR] <!DOCTYPE html>
[ERROR] <html lang="en">
[ERROR] <head>
[ERROR]   <title>404 - Nexus Repository Manager</title>
[ERROR]   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
[ERROR] 
[ERROR] 
[ERROR]   <!--[if lt IE 9]>
[ERROR]   <script>(new Image).src="http://localhost:6081/favicon.ico?3.14.0-04"</script>
[ERROR]   <![endif]-->
[ERROR]   <link rel="icon" type="image/png" href="http://localhost:6081/favicon-32x32.png?3.14.0-04" sizes="32x32">
[ERROR]   <link rel="mask-icon" href="http://localhost:6081/safari-pinned-tab.svg?3.14.0-04" color="#5bbad5">
[ERROR]   <link rel="[truncated 1371 chars]; line: 2, column: 2]
[ERROR] -> [Help 1]
```
