### ISSUE TITLE
Proposal: simple non java image

### ISSUE THREAD

**Issue by trecloux** [GoogleContainerTools/jib#1253]
Hi All, 

I have a use case where a git monorepo includes some microservices, some java frontends and some single page applications (Vue.Js).
We are using maven to build all java and non java images.
We moved to jib for java based images and are very happy with it.

But we still need a docker based plugin to build single page applications images. These images are very simple and we just need to add some HTML/JS/CSS files to a static web server base image (Apache httpd/nginx/...).

That mean that we do not need to add java layers and we do not need to overwrite the entrypoint.
I had a look to jib-core and I think that all primitives are ready for this use case.

At the end, the `<extraDirectory>` support is already there, as a first step we just need to skip the java layers and java entrypoint specific stuff.

I'm ready to implement something, do you want it to be integrated into jib ? if yes, in existing maven goals or in a new one ?

I'd be very happy to receive your feedback on this proposal.

**Comment by briandealwis** [comment]
Before creating a new plugin, is there any way to accomplish what you're looking to do with Jib as-is?  For example, the following configuration mimics the `nginx` image setup providing you share put your content under `src/main/jib/usr/share/nginx/html/`.

        <configuration>
          <from><image>nginx</image></from>
          <to><image>static-website</image></to>
          <container>
            
            <entrypoint>
              <command>nginx</command>
              <arg>-g</arg>
              <arg>daemon off;</arg>
            </entrypoint>
          </container>

An alternative might be to put content in `src/main/resources` and overwrite the nginx config in  `src/main/jib/etc/nginx/conf.d/default.conf` to set the server root to `/app/resources`.

**Comment by trecloux** [comment]
Hi Brian,

Before creating this issue, I tried something close to your proposal. It was failing because `target/classes` folder did not exist.
I created `src/main/resources/.placeholder`and it fixed my issue.
Thanks !

**Comment by coollog** [comment]
@trecloux Although we most likely will not add additional goals to build non-java images in Jib, we do welcome anyone to build their own Maven/Gradle plugins or other tools with Jib Core to perform their own custom image builds :)

**Comment by sanyarnd** [comment]
If anyone is interested in complete snippet:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-antrun-plugin</artifactId>
    <version>1.8</version>
    <executions>
        <execution>
            <id>copy-artifacts-for-jib</id>
            <phase>prepare-package</phase>
            <goals>
                <goal>run</goal>
            </goals>
            <configuration>
                <skip>${jib.skip}</skip>
                <target name="Copy build artifacts to JIB Root">
                    <mkdir dir="${project.basedir}/target/jib_root/var/www/app/dist"/>
                    <copy todir="${project.basedir}/target/jib_root/...">
                        <fileset dir="${basedir}/..."/>
                    </copy>
                    <copy todir="${project.basedir}/target/jib_root/etc/nginx/">
                        <fileset dir="${basedir}/..." includes="..."/>
                    </copy>

                    <!-- workaround, see https://github.com/GoogleContainerTools/jib/issues/1253 -->
                    <mkdir dir="${basedir}/target/classes/"/>
                </target>
            </configuration>
        </execution>
    </executions>
</plugin>
```

Then add to jib configuration:
```xml
<extraDirectories>
    <paths>
        <path>${project.basedir}/target/jib_root/</path>
    </paths>
</extraDirectories>
```
