### ISSUE TITLE
Build Image without Application

### ISSUE THREAD

**Issue by Victoria2202** [GoogleContainerTools/jib#1261]
Hello,

is it possible to use the Jib-Maven-Plugin to Build an Image which contains Folders and Script Files? I have only a Dockerfile which I want to get build with jib. 

Thank you
Victoria

**Comment by chanseokoh** [comment]
It is actually possible, but with some tricks (defining `<entrypoint>` to prevent Jib from trying to infer Java main() class, and putting some bogus file to create `target/classes`). See #1253 for the ideas.

**Comment by loosebazooka** [comment]
Hi @Victoria2202, the current jib-maven-plugin does not build non java images. However we have released a general purpose [jib-core library](https://github.com/GoogleContainerTools/jib/tree/master/jib-core) that lets you build arbitrary files programmatically with Java. Perhaps you can use that to do it.

If someone is interested in building a CLI using jib-core that reads a dockerfile (with limitations), it's possible this can solve your problems too.

**Comment by chanseokoh** [comment]
Ah, yeah, if your intention is to use `Dockerfile`, Jib won't really work, since Jib does not have any support related to `Dockerfile`.

**Comment by Victoria2202** [comment]
Hello,

i was thinking to adjust the dockerfile for the jib Maven-Plugin.

My Dockerfile looks like this:







*FROM ubuntu:16.04COPY  project/* /home/project/WORKDIR /home/project/ RUN
chmod +x /home/project/*.shCMD ["sh", "-c", "./test-script.sh"]*


In the pom.xml looks at the moment like this:

    <build>
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>0.10.0</version>
                <configuration>
                    <from>
                        <image>ubuntu:16.04</image>
                    </from>
                    <to>

<image>${project.artifactId}:${project.version}</image>
                    </to>
                    <allowInsecureRegistries>true</allowInsecureRegistries>
                      

<extraDirectory>${project.basedir}/src/main/resources</extraDirectory>
                </configuration>
                <executions>
                    <execution>
                        <id>default</id>
                        <phase>install</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

Is it possible to get the dockerfile in pom.xml to use for the build the
pom.xml?

Thank a lot.

Chanseok Oh <notifications@github.com> schrieb am Di. 20. Nov. 2018 um
00:48:

**Comment by chanseokoh** [comment]
If you put `test-script.sh` at `${project.basedir}/src/main/jib/home/project/test-script.sh` (which will place the script at `/home/project/test-script.sh` in the container image), something like below may work. If you have other files to copy, you'll place them under `src/main/jib` with the directory structure you want. Don't put the files under `src/main/resources`, since files under that directory will be unnecessarily copied into `/app/classes/`.

```xml
<configuration>
  <from><image>ubuntu:16.04</image></from>
  ...
  <container>
    <entrypoint>
      <arg>sh</arg>
      <arg>-c</arg>
      <arg>/home/project/test-script.sh</arg>
    </entrypoint>
  </container>
  <extraDirectory>
    <permissions>
      <permission>
        <file>/home/project/test-script.sh</file><mode>755</mode>
      </permission>
    </permissions>
  </extraDirectory>
</configuration>
```

**Comment by Victoria2202** [comment]
Hello,

thank you. But I get the following error:

[ERROR] Failed to execute goal
com.google.cloud.tools:jib-maven-plugin:0.10.0:build (default) on project
project: Obtaining project build output files failed; make sure you have
compiled your project before trying to build the image. (Did you
accidentally run "mvn clean jib:build" instead of "mvn clean compile
jib:build"?): C:\Projects\test-jib-project\target\classes is not a
directory -> [Help 1]

I tried to change the maven command a few times, but I get the same error.

Am Di., 20. Nov. 2018 um 17:47 Uhr schrieb Chanseok Oh <
notifications@github.com>:

**Comment by chanseokoh** [comment]
That's because `target/classes` is empty. One trick in #1253 is to put an empty file such as `src/main/resources/empty`.

**Comment by Victoria2202** [comment]
Thank you very much it worked. :)

Is it poosilble that the arg looks similiar like this?

<arg>/home/project/test-script.sh && /home/project/test-script-run.sh</arg>


Am Mi., 21. Nov. 2018 um 18:14 Uhr schrieb Chanseok Oh <
notifications@github.com>:

**Comment by chanseokoh** [comment]
> <arg>/home/project/test-script.sh && /home/project/test-script-run.sh</arg>

This won't work. With a single `<arg>`, the entire value will be assumed to be a single executable file.

In your case, I suggest you create another script, e.g., `/home/project/entrypoint.sh` that executes both `test-script.sh` and `test-script-run.sh` inside it.

**Comment by Victoria2202** [comment]
I got still one Problem.

Whe I start the container I got the following error:

/home/project/test-script.sh: line 1: /home/ project/test-script. sh:
Permission denied

Am Mi., 21. Nov. 2018 um 19:55 Uhr schrieb Chanseok Oh <
notifications@github.com>:

**Comment by loosebazooka** [comment]
Could be that you need to also set it to be executable in the extraDirectory configuration?

**Comment by chanseokoh** [comment]
Yeah, please check https://github.com/GoogleContainerTools/jib/issues/1261#issuecomment-440343575 for an example to set the executable permission. I tried a small sample on my own, and things should work end to end.

**Comment by Victoria2202** [comment]
Thanks a lot. It works now Perfect. :)

Chanseok Oh <notifications@github.com> schrieb am Mi. 21. Nov. 2018 um
21:49:
