### ISSUE TITLE
[gradle] Concurrency issue with many simultaneous builds

### ISSUE THREAD

**Issue by anuraaga** [GoogleContainerTools/jib#1273]
**Description of the issue**: In a project that can run dozens of jib build tasks concurrently, an exception was thrown when working with the cache

```
Step #3 - "curio-generated-build-all": Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 133 more
Step #3 - "curio-generated-build-all": Caused by: java.nio.file.FileSystemException: /root/.cache/google-cloud-tools-java/jib/tmp/10954747174794241924 -> /root/.cache/google-cloud-tools-java/jib/layers/096ebeedeeb6534eadf6d1ae8173145e8f43aedf29f5ae179f8b2e899f84f344: Directory not empty
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.moveIfDoesNotExist(DefaultCacheStorageWriter.java:75)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.write(DefaultCacheStorageWriter.java:154)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorage.write(DefaultCacheStorage.java:74)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Cache.writeCompressedLayer(Cache.java:68)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:81)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:36)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
Step #3 - "curio-generated-build-all": 
```

**Expected behavior**: The build succeeds

**Steps to reproduce**:  This only happens sometimes, and on a build with dozens of projects. I suspect it will be hard to reproduce with a small build.

**Environment**: Linux, Gradle 5.0-rc-4, Java 11, gradle-jib-plugin 0.10.0

**`jib-gradle-plugin` Configuration**: 

Standard configuration, just lots of subprojects

**Log output**:

```
Step #3 - "curio-generated-build-all": Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 133 more
Step #3 - "curio-generated-build-all": Caused by: java.nio.file.FileSystemException: /root/.cache/google-cloud-tools-java/jib/tmp/10954747174794241924 -> /root/.cache/google-cloud-tools-java/jib/layers/096ebeedeeb6534eadf6d1ae8173145e8f43aedf29f5ae179f8b2e899f84f344: Directory not empty
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.moveIfDoesNotExist(DefaultCacheStorageWriter.java:75)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.write(DefaultCacheStorageWriter.java:154)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorage.write(DefaultCacheStorage.java:74)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Cache.writeCompressedLayer(Cache.java:68)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:81)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:36)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
Step #3 - "curio-generated-build-all": 
```

**Additional Information**: 

The OS is Linux (more specifically Google's Cloud Build VM with a build image based on debian), so I think atomic moves should work and would not expect #1044 to be related.

**Comment by anuraaga** [comment]
Also to clarify, `/root/.cache` is not saved across builds so it isn't related to having an old cache leftover (am looking forward to save the cache though after #1238 :) )

**Comment by anuraaga** [comment]
Looking at the javadocs, it seems like it is implementation specific whether existing files cause an exception or not when doing `ATOMIC_MOVE`. In my experience, `ATOMIC_MOVE` on Linux does indeed try to replace the existing file and `FileAlreadyExistsExeception` will never be thrown.

**Comment by briandealwis** [comment]
Your stack trace seems really odd: why is `FileSystemException` being thrown, and how is it being thrown from `DefaultCacheStorageWriter.moveIfDoesNotExist()` rather than the `Files.move()`?  After all, `Files.move()` is not a native function.

Can you describe your setup a bit more, @anuraaga?  I ran 20 different builds multiple times in parallel using copies of the same project, and didn't manage to trigger this.  I'm feeling a bit jealous :-)

**Comment by briandealwis** [comment]
This code in `DefaultCacheStorageWriter.moveIfDoesNotExist()` needs to catch and handle the general `FileSystemException`.  When a native function errors, `UnixException#translateToIOException()` handles a few specific errnos and otherwise throws a general `FileSystemException`, including `ENOTEMPTY`.

But in examining the underlying implementations of `Files.move()` I think our `moveIfDoesNotExist()` can be greatly simplified.  In `UnixCopyFile#move()`, which handles the bulk of the move implementation for Linux and MacOS, first calls out to `rename(2)`; `ATOMIC_MOVE` only means that it stops there, otherwise it continues on to try copying-into-place.

We know that `moveIfDoesNotExist()` is only for moving a formed cache layer into place: if a directory by that name exists, then its contents should be exactly the same.

So I think we could just do:
```java
  private static void moveIfDoesNotExist(Path source, Path destination) throws IOException {
    if (Files.exists(destination)) {
      return;
    }

    try {
      Files.move(source, destination, StandardCopyOption.ATOMIC_MOVE);

    } catch (FileSystemException ex) {
      if (!Files.exists(destination)) {
        throw ex;
      }
    }
  }
```

We could be conservative in the destination-exists case and ensure our content matched.  But we don't do any such validation in the already-exists case.

**Comment by chanseokoh** [comment]
You mean not giving the `ATOMIC_MOVE` in the simpified code, right? I am not confident if it is a good idea to make our code depend on the specific platform implementation.

**Comment by anuraaga** [comment]
@briandealwis Thanks for the digging! As for our setup, some other info is

- All base images are openjdk:11-slim (base images is quite larger than distroless so may trigger more?)

- We are using a highcpu-32 build machine on Cloud Build. Lots and lots of cores available.

Other than that, just simple Java builds getting built by jib, nothing special

**Comment by briandealwis** [comment]
@chanseokoh you're right, I meant to *not* include the `ATOMIC_MOVE`.  The standard implementation does try to do an atomic-move and then copies and moves otherwise, similar to what we're doing.

**Comment by anuraaga** [comment]
Hello - just wondering, does it make sense to make a PR with the change from https://github.com/GoogleContainerTools/jib/issues/1273#issuecomment-441086981 ? Then I can try reenabling parallel builds again :D

**Comment by briandealwis** [comment]
@anuraaga I pushed up a branch at

https://github.com/GoogleContainerTools/jib/tree/i1273

Is it possible for you to build it locally and see if you can reproduce the issue?

**Comment by anuraaga** [comment]
Hmm - we use this build to push alpha servers from the master branch in our CI, which is a much more powerful machine than my workstation. So I'm not confident I could repro this with a local build. I was sort of hoping the stacktrace would be definitive enough even if it's hard to repro.

Does jib have snapshot builds on sonatype or similar? It'd be hard to try a local build on our CI but I would be able to try a published snapshot without too much difficulty.

**Comment by briandealwis** [comment]
You can use the build from jitpack.io:

https://jitpack.io/#GoogleContainerTools/jib/i1273-SNAPSHOT

**Comment by briandealwis** [comment]
I managed to coax a build from JitPack but the Maven deems the plugin as invalid as the JitPack coordinates don't match the plugin descriptor's coordinates:
```
[ERROR] Invalid plugin descriptor for com.github.GoogleContainerTools.jib:jib-maven-plugin:i1273-SNAPSHOT (/Users/bsd/.m2/repository/com/github/GoogleContainerTools/jib/jib-maven-plugin/i1273-fdf8a19181-1/jib-maven-plugin-i1273-fdf8a19181-1.jar), Plugin's descriptor contains the wrong group ID: com.google.cloud.tools, Plugin's descriptor contains the wrong version: 0.10.2-SNAPSHOT -> [Help 1]
```
and there [doesn't seem to be any way to ignore this validation](https://github.com/apache/maven/blob/master/maven-core/src/main/java/org/apache/maven/plugin/internal/DefaultMavenPluginManager.java#L250).

**Comment by anuraaga** [comment]
That link looks like it's about maven - as my PR title shows I'm using Gradle :) Gradle didn't seem to complain when I tried this locally and I'm going to try on our master build tomorrow.

**Comment by briandealwis** [comment]
Thanks for testing @anuraaga!
