### ISSUE TITLE
How to specify container MAINTAINER property?

### ISSUE THREAD

**Issue by axiopisty** [GoogleContainerTools/jib#1275]
**Description of the issue**:

Docker allows specifying the MAINTAINER property which indicates who maintains the container. I tried adding this to the container configuration as follows:

```xml
<container>
    <maintainer><![CDATA[My Name <my@email.com>]</maintainer>
</container>
```

**Expected behavior**:

The produced container, when inspected with `docker inspect` should show the specified maintainer

**Comment by briandealwis** [comment]
That would map to the `author` field, I think ([docker image spec](https://github.com/moby/moby/blob/master/image/spec/v1.md#image-json-field-descriptions), [oci image spec](https://github.com/opencontainers/image-spec/blob/master/config.md#properties)).

**Comment by briandealwis** [comment]
Note that Docker has now [deprecated the _MAINTAINER_ instruction](https://docs.docker.com/engine/reference/builder/#maintainer-deprecated) and recommends using a _maintainer_ label instead.  You can set labels in the Jib container configuration using a construct like:
```xml
<configuration>
  <container>
    <labels>
      <maintainer>my@email.com</maintainer>
    </labels>
  </container>
</configuration>
```

I'll close this issue given that the _MAINTAINER_ instruction is deprecated and there is a recommended alternative that is already supported by Jib.
