### ISSUE TITLE
[gradle] (flaky?) Jackson-related error when building image

### ISSUE THREAD

**Issue by anuraaga** [GoogleContainerTools/jib#1277]
**Description of the issue**: Got a random jackson exception when building with `jib`.

Exception when building image. Retrying the same build worked.

`404 not found` seems to be the root cause, which I'm assuming is flakiness when accessing `gcr.io`. I want to just get the log out here, but there might not be anything to do here. It's why I'm keeping this issue lightweight.

```
Step #3 - "curio-generated-build-all": Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 50 more
Step #3 - "curio-generated-build-all": Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.google.cloud.tools.jib.registry.json.ErrorResponseTemplate` (although at least one Creator exists): no int/Int-argument constructor/factory method to deserialize from Number value (404)
Step #3 - "curio-generated-build-all": at [Source: (String)"404 page not found
Step #3 - "curio-generated-build-all": "; line: 1, column: 1]
Step #3 - "curio-generated-build-all": at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
Step #3 - "curio-generated-build-all": at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1343)
Step #3 - "curio-generated-build-all": at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1032)
Step #3 - "curio-generated-build-all": at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromInt(ValueInstantiator.java:262)
Step #3 - "curio-generated-build-all": at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromInt(StdValueInstantiator.java:356)
Step #3 - "curio-generated-build-all": at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromNumber(BeanDeserializerBase.java:1324)
Step #3 - "curio-generated-build-all": at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:173)
Step #3 - "curio-generated-build-all": at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:161)
Step #3 - "curio-generated-build-all": at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
Step #3 - "curio-generated-build-all": at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3004)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.json.JsonTemplateMapper.readJson(JsonTemplateMapper.java:101)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:248)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.callWithAllowInsecureRegistryHandling(RegistryEndpointCaller.java:152)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.registry.RegistryEndpointCaller.call(RegistryEndpointCaller.java:142)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.registry.RegistryClient.callRegistryEndpoint(RegistryClient.java:339)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:200)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.registry.RegistryClient.pullManifest(RegistryClient.java:208)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.pullBaseImage(PullBaseImageStep.java:197)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:168)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullBaseImageStep.call(PullBaseImageStep.java:56)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
```

**Expected behavior**:

Retries so the build doesn't fail? Or possibly provides a clearer exception message

**Steps to reproduce**: 

Running a jib build

**Environment**: Linux, Gradle 5.0-rc-4, Java 11

**`jib-gradle-plugin` Configuration**: 

A relatively standard configuration that pushes to Google Container Registry

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Yeah, looks like `gcr.io` was not responding correctly once.

On our side, it may be worth catching `JsonParseException` and `JsonMappingException` and report that the registry is not behaving.

**Comment by anuraaga** [comment]
Providing a clearer exception sounds great. Though I would suggest that it's probably good to do that on a non-200 response from the registry rather than the json exceptions for better precision - Json decoding doesn't seem related to 404 errors.

**Comment by skunkiferous** [comment]
Hi. I'm also getting this error with Maven. As a "first time user" of JIB, I wasted lots of time trying to understand the problem; totally inscrutable error message. A better error message would be good.

**Comment by chanseokoh** [comment]
Hi @skunkiferous,

Just to understand the symptom and the cause of your issue correctly, here is what I assume happened to you:
- The registry you were trying to use was not behaving correctly or not conforming to the Docker registry protocol standards; this caused Jib unable to parse the registry response and throw a JSON parsing exception.
- You fixed the registry, have someone fix the registry, or the registry became acting normally now, so the problem is gone.

First of all, I'd like to know what was the registry (gcr.io, Nexus, Artifactory, etc) so that we clearly understand why, how, and when the registry can malfunction for which reasons. If you already know the root cause of the registry malfunctioning, please let us know in details. After understanding that, we would able to think what would be the best way to surface such an error to the user.

**Comment by chanseokoh** [comment]
Also, if there is a way to set up some registry to reproduce this consistently and if you know how to do so, please let us know.

**Comment by skunkiferous** [comment]
Hi.

In the mean time, with help of my colleagues, we have resolved the
issue. (Un?)fortunately, it was a "user error", and not a registry
error, so it doesn't really belong in this issue.

To put it shortly, I simply used the wrong image name, and the
registry was trying to tell me that with "page not found", which might
be obvious in hindsight, but wasn't obvious when I first got it.

If it still matters, the registry was VMWare Harbor. Once we figured
out what was wrong, I haven't tried to "reproduce" the error, but I
guess it is 100% reproducible.

If you would like me to open a new issue, regarding the behaviour of
jib when entering a wrong image name, just say so.

**Comment by chanseokoh** [comment]
Thanks for the update. I can now get what really happened.

However, for the "page not found" error, I think the registry should have returned the correct HTTP response code (404), which Jib will recognize and handle properly. It may still be the case that Harbor isn't conforming to the registry communication protocol in this regard.

Do you still have the whole error logs and the exception stack trace? We can think about what we can improve when dealing with non-conforming registries.

**Comment by skunkiferous** [comment]
Hi. I haven't got the logs, but I can reproduce the error any time.
I'll try to reproduce it tomorrow (I'm at home now), and send you all
I can get in output.

**Comment by anuraaga** [comment]
Looking through the caller

https://github.com/GoogleContainerTools/jib/blob/211efee9d244fb4f79488d382bc28fbeec0fdc15/jib-core/src/main/java/com/google/cloud/tools/jib/registry/RegistryEndpointCaller.java

It seems like it parses the JSON even for error status codes. This probably makes sense for well behaved registries but it seems too optimistic as a user error (wrong registry URL) or transient server error (I can only assume the flakiness I saw with gcr.io has something to do with the routing of the load balancer not hitting a  backend) won't have JSON and the error message is very cryptic when that happens.

Isn't it good to add exception handling to the JSON parsing and provide a clearer error message?
