### ISSUE TITLE
Jib mven plugin , How to change tar file name?

### ISSUE THREAD

**Issue by saujanya123** [GoogleContainerTools/jib#1282]
I can  build and save project  image to disk as a tarball with below mvn command:
mvn  jib:BuildTar
This builds and saves project image to target/jib-image.tar

Can i change the name of jib-image.tar to some other name?

**Comment by chanseokoh** [comment]
Hi @saujanya123,

Jib does not have allow renaming, but there should be various other ways to achieve your goal. For example, you could google "Maven copy file after build". One way that comes to my mind is to use the `maven-resources-plugin`, for example like [this](https://stackoverflow.com/questions/41654314/maven-how-to-copy-files). You may bind the plugin execution to the phase you want, e.g., `post-compile`, or trigger the copy using profiles or execution IDs, or manually on the command line, etc.

**Comment by TadCordle** [comment]
As @chanseokoh said, you can probably accomplish this using other plugins. You may be able to use the [`copy-rename-maven-plugin`](https://coderplus.github.io/copy-rename-maven-plugin/rename-mojo.html) to rename the tar after the build.
