### ISSUE TITLE
How to pass _JAVA_OPTIONS to the container 

### ISSUE THREAD

**Issue by pratapagiri** [GoogleContainerTools/jib#1296]
**Description of the issue**:
 With Docker entryfile, previously I was specifying _JAVA_OPTIONS as given below:
       #!/bin/sh
       java $JAVA_OPTIONS -jar $MY_MS_APP $@

 With jib, how do I specify the __JAVA_OPTIONS? Is it in pom.xml?

**Expected behavior**:
  pom.xml should provide example/option to specify __JAVA_OPTIONS

**Steps to reproduce**: 
   NA

**Environment**: 
   Windows 10, Maven 3.6.0

**`jib-maven-plugin` Configuration**: 
```xml
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>0.9.13</version>
				<configuration>
				    <allowInsecureRegistries>true</allowInsecureRegistries>
					<to>
						<image>springboot-jib:${project.version}</image>
					</to>
					<container>
						<ports>
							<port>8080</port>
						</ports>
					</container>
				</configuration>
			</plugin>
```

Thanks for help.

**Comment by briandealwis** [comment]
Hi @pratapagiri. If you're wanting to set fixed JVM arguments, you can set them using [the `<jvmFlags>` block](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage).

If you want to be able to provide alternative values at run time (e.g., `docker run -e JAVA_OPTIONS=xxx`), then you have two choices:
  1. You can put your script in `src/main/jib` and ensure you build from an image that has a shell.  The default image, `gcr.io/distroless/java`, does not have a shell.  You would then specify a custom `<entrypoint>`.
  2. You can use one of the [supported environment variables](https://stackoverflow.com/questions/28327620/difference-between-java-options-java-tool-options-and-java-opts) to pass along additional JVM arguments at run time.

**Comment by Alykoff** [comment]
For my case I change `JVM_OPTS` to `JAVA_TOOL_OPTIONS` and it is worked for me.
