### ISSUE TITLE
Deprecate useOnlyProjectCache from plugin configuration and only set via system property

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1308]
[Original comment](https://github.com/GoogleContainerTools/jib/pull/1306#issuecomment-444664799)

>We might want to consider deprecating useOnlyProjectCache to remove that from the plugin configuration and have that settable via the new system property. It didn't make sense to define the cache location via the plugin configuration anyways.

**Comment by chanseokoh** [comment]
I remember our test projects use this configuration, so they should be migrated too.
