### ISSUE TITLE
jib-core: shut down executor service to allow JVM termination

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1310]
Was testing jib-core.

```java
  public static void main(String[] args) throws Exception {
    Containerizer containerizer = Containerizer.to(DockerDaemonImage.named("francium25/test"));
    Jib.from("francium25/base").containerize(containerizer);
  }
```

The code does not terminate after the image is built, because we are not shutting down `StepsRunner.listeningExecutorService`. One potential-but-not-really-right way to handle it would be to shut it down in `waitOn...Step()`, which is the last step of the `Steps` we chain.

From the perspective of the above simple code, it makes sense to shut it down. However, it's possible to accept an executor service from the user via `Containerizer.setExecutorService()`, and we shouldn't shut their service down on our discretion at the end. But we could accept another parameter for `setExecutorService()` to tell us if we will shut it down or not.

Also, another consequence of shutting down the service is that, in the usual case where people don't provide their executor service, they cannot reuse `JibContainerBuilder`.
```java
    JibContainerBuilder cb = Jib.from(...);
    cb.containerize(...);
    cb.containerize(...); // exception because the executor service is shut down.
```
This is because `BuildConfiguration` is owned by `JibContainerBuilder`, hence the two `containerize()` calls share `executorService`, which `BuildConfiguration` owns. And `executorService` is a mutable object.

And the problem is that, as long as we allow reusing `JibContainerBuilder`, it is impossible to know when it is OK to shut it down.

**Comment by briandealwis** [comment]
I think it makes sense to treat the executor service like any other disposable: if the user provided it, then they destroy it; if we create it, then we dispose of it.

My suggestion is to allow `BuildConfiguration.executionService` to be `@Nullable` and move the creation of the execution service from `BuildConfiguration.Builder.build()` into the `StepsRunner`, and add a `StepsRunner.cleanUp()` method that is called as a final step.

**Comment by chanseokoh** [comment]
> I think it makes sense to treat the executor service like any other disposable: if the user provided it, then they destroy it; if we create it, then we dispose of it.

+1

**Comment by loosebazooka** [comment]
Yeah I mean that's what I [used](https://github.com/loosebazooka/jib-dockerfile/blob/master/src/main/java/com/loosebazooka/jib/dockerfile/JibDockerfile.java#L48-L53) to kill it fast.

Is it weird to ask the user to define the executor lifecycle? (probably)
```
.setExecutorPolicy(Supplier<ExecutorSerivce> supplier, Function<ExecutorService> cleanup)
```
