### ISSUE TITLE
can not pull image from harbor

### ISSUE THREAD

**Issue by qiankunli** [GoogleContainerTools/jib#1311]
I used jib command to build the image `harbor.test.ximalaya.com/test/community-vote-service:20181206-103704`

```
mvn clean install -DskipTests -Dmaven.javadoc.skip=true -Ptest -f=community-vote-service/pom.xml && mvn com.google.cloud.tools:jib-maven-plugin:0.10.1:build -Djib.from.image=harbor.test.ximalaya.com/common/runit-jdk8-tomcat8 -Djib.from.auth.username=barge -Djib.from.auth.password=Barge.Xmly.2018 -Djib.to.image=harbor.test.ximalaya.com/test/community-vote-service:20181206-103704 -Djib.to.auth.username=barge -Djib.to.auth.password=Barge.Xmly.2018 -f=community-vote-service/pom.xml -Djib.container.appRoot=/usr/local/tomcat/webapps/community-vote-service 
```
but can not pull image with docker command 

```
docker pull harbor.test.ximalaya.com/test/community-vote-service:20181206-103704
...
Unexpected EOF 
```

and then , I deleted the repository(`harbor.xxx/test/community-vote-service`) in harbor ui. build image with jib successfully, but now 

```
docker pull harbor.test.ximalaya.com/test/community-vote2:20181206-111607
Error response from daemon: manifest for harbor.test.ximalaya.com/test/community-vote-service:20181206-111607 not found
```

our harbor version is 1.4.0,  I guess that garbage collection cause the lose of some layer.

**Comment by qiankunli** [comment]
when I used `-Djib.useOnlyProjectCache=true`, the `Unexpected EOF` solved in another maven project. is there more detail about `-Djib.useOnlyProjectCache=true`?

**Comment by briandealwis** [comment]
`useOnlyProjectCache=true` forces Jib to not use the per-user cache that caches base images and layers.  The base images and layers are instead maintained within the per-project cache (`target/jib-cache`).  I'm puzzled as to how it could have an effect here.

Reading through your description, it would seem to me that Harbor should be failing during the Jib's image push.  I see that Harbor 1.6.2 is the latest release, and 1.7 is on the horizon.  Is it possible to confirm with the latest?

**Comment by chanseokoh** [comment]
Regarding this error

```
docker pull harbor.test.ximalaya.com/test/community-vote2:20181206-111607
Error response from daemon: manifest for harbor.test.ximalaya.com/test/community-vote-service:20181206-111607 not found
```

when I try to pull a non-existing-repo in my existing Docker Hub account, I get the exact same error, so I think you should double-check that the image is actually available from the registry and you specified the correct tag name. (BTW, I also remember Harbor was a bit slow to show uploaded images in the web UI.)

```
$ docker pull francium25/non-existing-repo
Using default tag: latest
Error response from daemon: manifest for francium25/non-existing-repo:latest not found
```

--

Regarding `-Djib.useOnlyProjectCache=true`, first, as @briandealwis said, try the latest Harbor. If it still gives you `Unexpected EOF`, I'd like to know if you can consistently reproduce that
1. `mvn clean install ... ...:jib-maven-plugin:0.10.1:build ...` always ends up `Unexpected EOF`.double
1. `mvn clean install ... ...:jib-maven-plugin:0.10.1:build -DuseOnlyProjectCache=true ...` always works?

(BTW, always double-check if you're specifying the correct tag on the command line.)

If you can consistently reproduce these, I wonder if clearing the user-level image cache will resolve this. On Linux, the cache directory is `$HOME/.cache/google-cloud-tools-java/jib`. Try renaming that directory and rebuilding:

```
mv $HOME/.cache/google-cloud-tools-java/jib \
   $HOME/.cache/google-cloud-tools-java/jib-cache-backup-for-later-diagnosis
```

**Comment by qiankunli** [comment]
@briandealwis @chanseokoh I am sorry for that `useOnlyProjectCache=true` is a coincidence. 

we implement the "online gc" in harbor  

```
// The two most recent versions are kept and delete others
do
    curl --insecure -X DELETE --header 'Accept: text/plain' "https://192.168.60.8/api/repositories/$line/tags/$deltags"
done
// start gc
docker run  --name gc --rm --volumes-from registry vmware/registry-photon:v2.6.2-v1.4.0 garbage-collect  /etc/registry/config.yml
```
the "online gc" cause that we can get deleted layer information (whose http status is 200) with registry api, but the real size of the deleted layer is 0. 

I guess that the jib may not verify the size of deleted layer, so that jib think that the layer is exist and  do not push the layer again, so that `Unexpected EOF ` happen

**Comment by briandealwis** [comment]
Oh that's interesting!  We do a `HEAD`request against each layer and skip if the registry reports that it's available:

```
Dec 07, 2018 11:30:14 AM com.google.api.client.http.HttpResponse <init>
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: max-age=31536000
Content-Length: 7768687
Content-Type: application/octet-stream
Docker-Content-Digest: sha256:d455ccc1cea9edcc50a50e0ee33a9f90c1f45486bacf8cb59e13203d7ee3be66
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:d455ccc1cea9edcc50a50e0ee33a9f90c1f45486bacf8cb59e13203d7ee3be66"
X-Content-Type-Options: nosniff
Date: Fri, 07 Dec 2018 16:30:14 GMT

```

Could you please dump the full response headers for these deleted layers?

**Comment by qiankunli** [comment]
@briandealwis  

request is

```
HEAD /v2/test/xxm-subscribe/blobs/sha256:f14ad73052287ffa32abf3613f9f758b8d8e1a1783c667db21c5e3a1b9afafcb HTTP/1.1
Host: harbor.test.xx.com
User-Agent: Go-http-client/1.1
Authorization: xxx
```

response is

```
HTTP/1.1 200 OK
Server: nginx
Date: Sun, 09 Dec 2018 10:13:45 GMT
Content-Type: application/octet-stream
Content-Length: 11984
Accept-Ranges: bytes
Cache-Control: max-age=31536000
Docker-Content-Digest: sha256:f14ad73052287ffa32abf3613f9f758b8d8e1a1783c667db21c5e3a1b9afafcb
Docker-Distribution-Api-Version: registry/2.0
Etag: "sha256:f14ad73052287ffa32abf3613f9f758b8d8e1a1783c667db21c5e3a1b9afafcb"
Set-Cookie: beegosessionID=15fbe5e6088b2ca776c6ad18793e796f; Path=/; HttpOnly
Connection: keep-alive
```

**Comment by chanseokoh** [comment]
Yeah, if that is really the layer causing the problem, it genuinely looks like the fault of Harbor not returning correct info. If you believe it is the layer that got deleted from Harbor, you should file a bug against Harbor with the relevant info.

**Comment by qiankunli** [comment]
@briandealwis @chanseokoh ok, I think it may be the bug of harbor（1.4.0）
