### ISSUE TITLE
Progress feedback cleanup: make ProgressEventDispatcher API clearer

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#1357]
Originally from #1297 

Make `ProgressEventDispatcher` API clearer (https://github.com/GoogleContainerTools/jib/pull/1330#discussion_r240724667)

**Comment by chanseokoh** [comment]
This is too general, and it's not clear what the action items are. I'll close this. If we have a tangible proposal, we can create a new issue later.
