### ISSUE TITLE
Generated things in classpath does not get copied

### ISSUE THREAD

**Issue by smil2k** [GoogleContainerTools/jib#1370]
**Description of the issue**:

I have dependency plugin unpacking the webui we would like to display into target/classes/public. This directory is picked up by spring-boot later and displayed.

I just noticed, that JIB does not pick this directory though.

**Expected behavior**:

Jib should put **everything** available under classes into the container.

**Steps to reproduce**: 

1) add plugin:
```xml
<plugin>
          <groupId>com.google.cloud.tools</groupId>
          <artifactId>jib-maven-plugin</artifactId>
          <version>1.0.0-rc1</version>
          <configuration>
            <container>
              <ports>8080</ports>
            </container>
            <to>
              <tags>
                <t>latest</t>
                <t>${project.version}</t>
              </tags>
              <image>xxx/backend</image>
            </to>
          </configuration>
        </plugin>
```
2) create some files under /classes (eg test.js)

3) run jib:buildTar

The resulting container won't contain the .js file.

**Environment**: 

maven 3.6

**Comment by chanseokoh** [comment]
Have you checked `/app/resources/public`?

**Comment by smil2k** [comment]
Sorry, my fault.
