### ISSUE TITLE
Use JavaContainerBuilder in plugins

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1373]
Followup to #1347

**Comment by chanseokoh** [comment]
Hmm... if we really want to do this, I think we will need more changes to `JavaContianerBuilder`? For example, we cannot create an extra files layer with it.

**Comment by TadCordle** [comment]
We can call `toContainerBuilder()` and addLayers to that, can't we?

**Comment by chanseokoh** [comment]
Ah, it returns `JibContainerBuilder`. I missed that.
