### ISSUE TITLE
Not able to set Spring Boot active profiles

### ISSUE THREAD

**Issue by OscarSpruit** [GoogleContainerTools/jib#1375]
**Description of the issue**:
I am trying to set the active profile for a Spring Boot application with this command `./gradlew jib -PspringActiveProfiles=prd` and the configuration below, but that doesn't work. The container that was built will start with the profile I have defined in my application.yml. 

I have also tried to define the profile in the `jvmFlags` property of the `container` closure like this: `jvmFlags = ['-Dspring.profiles.active=prd']`. That also didn't work.

Does someone know how to do this? If it isn't possible right now it would be a nice to have feature.

**Expected behavior**:
The container will start with the profile you provide with the jib command.

**Environment**: jib-gradle-plugin: 0.10.1, Gradle: 4.8, OS: macOS 10.14.2

**`jib-gradle-plugin` Configuration**: 
```groovy
jib {
    String profiles = project.properties.get("springActiveProfiles")
    if (profiles != null) {
        System.setProperty("spring.profiles.active", profiles)
    }

    from {
        image = 'openjdk:8'
    }
    to {
        image = 'gcr.io/test/test-application'
    }
    container {
        ports = ['8080']
    }
}
```

**Comment by chanseokoh** [comment]
Hi @OscarSpruit,

> ... `jvmFlags` property of the `container` closure like this: `jvmFlags = ['-Dspring.profiles.active=prd'].` That also didn't work.

It works for me. Here is a sample app: https://github.com/chanseokoh/spring-boot-test.git

My app has `application.properties` which makes `jason` an active profile:
```properties
spring.profiles.active=jason
```
With the default `jason` profile, running `gradle clean bootRun` and `curl localhost:8080` gives you "Hello, Chanseok".

OTOH, running `SPRING_PROFILES_ACTIVE=peter gradle bootRun` gives you "Greetings, Chanseok".

Now, in `build.gradle`, I set
```
jib.container.jvmFlags = ['-Dspring.profiles.active=peter']
```
to use the non-default `peter` profile. `gradle jibDockerBuild` will show that the JVM flag is set when running the application:
```
Container entrypoint set to [java, -Dspring.profiles.active=peter, -cp, /app/resources:/app/classes:/app/libs/*, com.example.MyApplication]
```
Running `docker run --rm -p8080:8080 spring-boot-test:1` and accessing `localhost:8080` will give you "Greetings, Chanseok".

**Comment by chanseokoh** [comment]
Feel free to re-open if you still have problems or questions.

**Comment by OscarSpruit** [comment]
@chanseokoh Thanks for the help! It works now! Probably did something wrong when I tried it before...

**Comment by TheShubham-K** [comment]
thanks alot this worked for me. would like to recommend it for future reference.

**Comment by TheShubham-K** [comment]
> Hi @OscarSpruit,
> 
> > ... `jvmFlags` property of the `container` closure like this: `jvmFlags = ['-Dspring.profiles.active=prd'].` That also didn't work.
> 
> It works for me. Here is a sample app: https://github.com/chanseokoh/spring-boot-test.git
> 
> My app has `application.properties` which makes `jason` an active profile:
> 
> ```ini
> spring.profiles.active=jason
> ```
> 
> With the default `jason` profile, running `gradle clean bootRun` and `curl localhost:8080` gives you "Hello, Chanseok".
> 
> OTOH, running `SPRING_PROFILES_ACTIVE=peter gradle bootRun` gives you "Greetings, Chanseok".
> 
> Now, in `build.gradle`, I set
> 
> ```
> jib.container.jvmFlags = ['-Dspring.profiles.active=peter']
> ```
> 
> to use the non-default `peter` profile. `gradle jibDockerBuild` will show that the JVM flag is set when running the application:
> 
> ```
> Container entrypoint set to [java, -Dspring.profiles.active=peter, -cp, /app/resources:/app/classes:/app/libs/*, com.example.MyApplication]
> ```
> 
> Running `docker run --rm -p8080:8080 spring-boot-test:1` and accessing `localhost:8080` will give you "Greetings, Chanseok".

thanks alot this worked for me. would like to recommend it for future reference.
