### ISSUE TITLE
[core] open up visibility of build steps

### ISSUE THREAD

**Issue by rmannibucau** [GoogleContainerTools/jib#1388]
**Description of the issue**:

Jib-core has all the internals to introspect an image (check its "dockerfile" or equivalent - typically grab it entrypoint and layers) but it is not public and jib enforces to create a tar - and loose some of these info - or another image - and then use docker to get the info instead of jib.

Concretely exposing Image<Layer> would benefit the library IMHO.

**Expected behavior**:

Build steps should be usable outside the builder API of jib - or a new (introspect/fetch) builder api enabling to use steps more precisely.

**Comment by mpeddada1** [comment]
Closing as part of cleanup. Please re-open if it's still relevant.

**Comment by rmannibucau** [comment]
@mpeddada1 was it fixed? If not it is worth keeping it open I guess.

**Comment by mpeddada1** [comment]
@rmannibucau thanks for the question. Changed the status to "Close as not planned"  given the availability of a workaround (https://github.com/GoogleContainerTools/jib/issues/2045) and as we don't plan on implementing this any time soon. We're happy to re-open this issue as we gain more interest from the community.

**Comment by rmannibucau** [comment]
Well workaround is to use reflection and request mainly changing the scope of some classes, would a PR help so solve that or is the feature unwanted in upstream codebase?

**Comment by elefeint** [comment]
@rmannibucau Relaxing visibility on these APIs would enable usecases for Jib codebase that we don't want to support. Every new public API removes our ability to refactor the codebase, since people end up depending on those.

You are welcome to use Jib codebase for inspiration, but as a team, we are intentionally restricting open surfaces to make Jib both fit for purpose and easier to maintain.

**Comment by rmannibucau** [comment]
Ok, then if this particular issue is not desired, the linked one should be reopened since use case is not handled (whatever tech solution is used).

**Comment by elefeint** [comment]
We are not planning to support the repackaging usecase with Jib, sorry.
