### ISSUE TITLE
Support registry-mirrors

### ISSUE THREAD

**Issue by lxg1208** [GoogleContainerTools/jib#1396]
Because of the network problems in some countries, the basic image cannot be pulled when build image with Jib. Whether the Jib can support a configuration like "registry-mirrors"?

**Comment by loosebazooka** [comment]
Can you explain your usecase.

You can always explicitly set the base image to something that is accessible in your country?

**Comment by lxg1208** [comment]
I can't pull images from Docker Hub with Jib most of the time.

**Comment by coollog** [comment]
Hi @lxg1208 , you can use `jib.from.image` to specify your own custom image from your desired registry mirror.

**Comment by chanseokoh** [comment]
> you can use `jib.from.image` to specify your own custom image from your desired registry mirror.

You can't set `jib.from.image` to a pull-through mirror. For example, the `mirror.gcr.io` mirror (the public Google mirror on `gcr.io` for Docker Hub) doc says

> Pulling cached images does not count against Docker Hub rate limits. However, there is no guarantee that a particular image will remain cached for an extended period of time. Only obtain cached images on `mirror.gcr.io` by [configuring the Docker daemon](https://cloud.google.com/container-registry/docs/pulling-cached-images#configure). A request to pull directly from `mirror.gcr.io` will fail if a cached copy of the image does not exist.

This type of mirrors must be supported internally by Jib, as how `--registry-mirror` of Docker works.

**Comment by chanseokoh** [comment]
For future reference regarding mirror auth:
- https://stackoverflow.com/a/42758287/1701388
- https://github.com/moby/moby/issues/30880

**Comment by chanseokoh** [comment]
For Jib Maven/Gradle plugins and Jib Core, this is fixed by #3011 and #2999. (Only public mirrors such as `mirror.gcr.io` are supported.) The mirror support will be useful when hitting Docker Hub rate limits.

I'll create a separate issue for Jib CLI.

**Comment by chanseokoh** [comment]
@lxg1208 Jib build plugins 2.8.0 is live with the feature to configure registry mirrors. It should be useful to avoid hitting the Docker Hub rate limiting. Check out this [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-hitting-docker-hub-rate-limits-how-can-i-configure-registry-mirrors) to learn how to configure it.
