### ISSUE TITLE
See what labels are set in popular Java base images

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#1402]
This is a task for someone to complete, but do a survey of existing java base images and inspect what labels they are using.

**Comment by briandealwis** [comment]
So I looked at a variety of images and the answer is: there are no labels set except for the `fabric8/java-centos-openjdk8-jre` and `fabric8/java-centos-openjdk7-jre` images, and those labels come from the `centos` base image:

```
    "org.label-schema.build-date": "20181204"
    "org.label-schema.license": "GPLv2"
    "org.label-schema.name": "CentOS Base Image"
    "org.label-schema.schema-version": "1.0"
    "org.label-schema.vendor": "CentOS""
```

<details>
Examined:
- openjdk:11
- openjdk:11-jre
- openjdk:11-jre-alpine
- openjdk:11-jre-slim
- openjdk:10
- openjdk:10-jre
- openjdk:10-jre-alpine
- openjdk:10-jre-slim
- openjdk:9
- openjdk:9-jre
- openjdk:8
- openjdk:8-jre
- openjdk:8-jre-alpine
- openjdk:8-jre-slim
- openjdk:7
- openjdk:7-jre
- openjdk:7-jre-alpine
- openjdk:7-jre-slim
- adoptopenjdk/openjdk11
- adoptopenjdk/openjdk11:alpine
- adoptopenjdk/openjdk11:slim
- adoptopenjdk/openjdk11:alpine-slim
- adoptopenjdk/openjdk11-openj9
- adoptopenjdk/openjdk11-openj9:slim
- adoptopenjdk/openjdk11-openj9:alpine
- adoptopenjdk/openjdk11-openj9:alpine-slim
- adoptopenjdk/openjdk10
- adoptopenjdk/openjdk10:alpine
- adoptopenjdk/openjdk10:slim
- adoptopenjdk/openjdk10:alpine-slim
- adoptopenjdk/openjdk9
- adoptopenjdk/openjdk9:alpine
- adoptopenjdk/openjdk9:slim
- adoptopenjdk/openjdk9:alpine-slim
- adoptopenjdk/openjdk8
- adoptopenjdk/openjdk8:alpine
- adoptopenjdk/openjdk8:slim
- adoptopenjdk/openjdk8:alpine-slim
- azul/zulu-openjdk:11
- azul/zulu-openjdk-alpine:11
- azul/zulu-openjdk-debian:11
- azul/zulu-openjdk:8
- azul/zulu-openjdk-alpine:8
- azul/zulu-openjdk-debian:8
- azul/zulu-openjdk:7
- azul/zulu-openjdk-alpine:7
- azul/zulu-openjdk-debian:7
- mcr.microsoft.com/java/jre-headless:11u2-zulu-alpine
- mcr.microsoft.com/java/jre-headless:8u192-zulu-alpine
- mcr.microsoft.com/java/jre-headless:7u201-zulu-alpine
- amazoncorretto:8
- fabric8/java-centos-openjdk8-jre
- fabric8/java-centos-openjdk7-jre
- fabric8/java-alpine-openjdk8-jre
- fabric8/java-alpine-openjdk7-jre
</details>

**Comment by patflynn** [comment]
Thanks for doing that Brian!!

**Comment by briandealwis** [comment]
The [`label-schema.org`](http://label-schema.org/) initiative defines a small set of labels that are oriented to build information.  It might make sense for Jib to automatically populate some of these.

**Comment by patflynn** [comment]
+1

**Comment by briandealwis** [comment]
Oh.  [OCI have their own annotations](https://github.com/opencontainers/image-spec/blob/master/annotations.md) and claim they supersede those defined by label-schema.org.

**Comment by patflynn** [comment]
@jonjohnsonjr may have some knowledge about this.

**Comment by briandealwis** [comment]
Found [a blog post with the list of top 100 labels used in public images on Docker Hub], though it dates back to October 2016.

**Comment by briandealwis** [comment]
Closing: details are in the details on https://github.com/GoogleContainerTools/jib/issues/1402#issuecomment-459488535
