### ISSUE TITLE
Release jib-core 1.xxxx

### ISSUE THREAD

**Issue by rmannibucau** [GoogleContainerTools/jib#1419]
Hello,

can you release the jib-core version corresponding (or more recent) to the last maven release (1.0.0-rc1) please? Currently I'm using the maven plugin as dependency as a workaround but i'd like to clean that up.

Thanks a lot for the good work,
Romain

**Comment by coollog** [comment]
@rmannibucau Yep! We will do a release for `v0.1.1` of `jib-core` soon.

**Comment by TadCordle** [comment]
jib-core v0.1.1 has been released.
