### ISSUE TITLE
Add Java version and application size labels

### ISSUE THREAD

**Issue by liyinan926** [GoogleContainerTools/jib#1423]
**Description of the issue**:

Xref: https://github.com/GoogleContainerTools/distroless/issues/276

Additionally to the labels proposed in the above issue, the following label is expected to be added through Jib:

`app.java.bytes`: Application size in bytes, which is a sum of sizes of all application image layers.

@coollog

**Comment by loosebazooka** [comment]
This is obsolete. @liyinan926 if we still need this for the operator, please re-open
