### ISSUE TITLE
Finalize initial GA-worthy public API surface for jib-core

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1428]
`JibContainerBuilder` has methods that require use of objects outside of `com.google.cloud.tools.jib.api`, which complicates turning Jib Core into a JPMS module as we cannot just export `com.google.cloud.tools.jib.api`.  For example (not exhaustive):

    com.google.cloud.tools.jib.configuration.LayerConfiguration 
      - addLayerConfiguration
    com.google.cloud.tools.jib.configuration.Port
       - addExposedPort
    com.google.cloud.tools.jib.filesystem.AbsoluteUnixPath
       - addLayer
       - addVolume*
       - setWorkingDirectory

There are other helper classes that are very useful too:

    com.google.cloud.tools.jib.image.ImageReference
       - for parsing
    com.google.cloud.tools.jib.frontend.CredentialRetrieverFactory
       - at a minimum for inferCredentialHelper() and dockerConfig()

**Comment by loosebazooka** [comment]
do we still need the `api` package if we're defining what's internal and what's external via JPMS?

**Comment by briandealwis** [comment]
JPMS defines what's internal and external by packages.  So _yes_, unless we create internal packages (e.g., `.internal`).

**Comment by chanseokoh** [comment]
We believe the public API is in a reasonably good shape. Closing.
