### ISSUE TITLE
Progress bar should not show up when using jibGradle with Skaffold.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#1430]
`jibGradle` with Skaffold does shows the progress bar.

**Comment by briandealwis** [comment]
The progress is disabled as `MavenProjectProperties#isProgressFooterEnabled()` returns `false` as `System.console() == null`:
https://github.com/GoogleContainerTools/jib/blob/cbfef69e7025f0183aceb2b76870149e7b20d219/jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java#L137-L151

The progress is shown in `GradleProjectProperties#isProgressFooterEnabled()` as it doesn't do an equivalent check of `System.console()`.  It should as a `gradlew :jib > log.txt` has all sorts of escaped text:
```
Base image 'gcr.io/distroless/java' does not use a specific image digest - build may not be reproducible¬
^[[1mExecuting tasks:^[[0m
^[[1m[                              ] 0.0% complete^[[0m
^[[1m> building image to tar file^[[0m
^[[1m^[[0m
^[[1A^[[1A^[[1A^[[1A^[[0J
^[[1A^[[1mExecuting tasks:^[[0m
^[[1m[                              ] 0.0% complete^[[0m
```

**Comment by briandealwis** [comment]
Should builds happen in parallel on Skaffold then we could have interleaved log output, which will be confusing.  We'll instead disable the ANSI logging on Gradle when there is no console.

**Comment by briandealwis** [comment]
🤦‍♂️ the gradle plugin is typically executed from the gradle daemon, so there is no console.

**Comment by TadCordle** [comment]
Can we just pass `-Djib.console=plain` into the skaffold gradle command?

**Comment by briandealwis** [comment]
Yep, I think that's the only real solution.  And we should invoke Maven as a batch build too.

**Comment by chanseokoh** [comment]
Another option is `./gradlew --console=plain`. I see it disables colors and the Jib progress (although Jib persists to display colored image names). Running Maven in the batch mode should be the equivalent counterpart. However, it's a bit sad to not see colored output.

**Comment by briandealwis** [comment]
I agree.  I'm going to use `-Djib.console=plain`; users can use the new `args` option to configure `--batch-mode` or `--console=plain` if they wish.

**Comment by TadCordle** [comment]
Fixed with https://github.com/GoogleContainerTools/skaffold/pull/1895
