### ISSUE TITLE
Guava Beta-Checker to error prone checks

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#1435]
Add guava beta checker to error prone checks.

1. Add [beta checker](https://github.com/google/guava-beta-checker) to error prone checks
2. ~~(low-pri) At @netdpb advice, try to use guava-android in libraries.~~

**Comment by chanseokoh** [comment]
We have multiple places where we use classes and methods not present in guava-android, so this might require some migration effort.

**Comment by chanseokoh** [comment]
But really, why the guava-android? I think Jib is well over to the status where Java 8 is required. At this point, it's almost impossible to make our plugins and jib-core work on Java 8.

**Comment by loosebazooka** [comment]
I think it's because guava-jre is a superset of guava-android. It mitigates the possibility of a dependency conflict affecting us. However since we're not included as part of application code, that part of this issue might be less relevant.

**Comment by elharo** [comment]
If you're not a library, by all means go ahead and use guava-jre. No reason not to.

If jib is a library, then guava-android would be more compatible with a lot of other GCP orbit libraries that do support Java 7.

**Comment by loosebazooka** [comment]
This might need to be on jib-core GA milestone, we use A LOT of beta stuff it turns out.
