### ISSUE TITLE
Output SHA hash of built image

### ISSUE THREAD

**Issue by birdayz** [GoogleContainerTools/jib#1443]
**Description of the issue**:
After pushing an image, it would be great to get the SHA hash of the image to be outputted (stdout). i "pin" the docker image when deploying to k8s, with the "@sha<HASH>" suffix after the image name and tag. however, unlike docker build and other tools, jib doesn't output the SHA hash of the image when building/pushing. so i have to pull by tag to get the sha.
so, would it be possible to output the SHA hash of the image built?

**Expected behavior**:
-
**Steps to reproduce**: 
-
**Environment**: 

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by coollog** [comment]
Hi @birdayz , Jib outputs the SHA hash of the image as a file in the build output directory. For Maven, this would usually be [`target/jib-image.digest`](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#additional-build-artifacts), and for Gradle, this would usually be [`build/jib-image.digest`](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#additional-build-artifacts).

**Comment by birdayz** [comment]
thank you! :)
