### ISSUE TITLE
Configuring a base image built earlier in the Gradle build

### ISSUE THREAD

**Issue by marshallpierce** [GoogleContainerTools/jib#1446]
I'd like to use a base image for Jib that was built (via a normal `Dockerfile`) earlier in the Gradle build. (This lets me use a base OS and JDK of my choosing with project-specific other things that aren't easily done by simply copying files from the project via jib's `extraDirectory`.)

The image is built like this using https://bmuschko.github.io/gradle-docker-plugin/:

```
task buildBaseDockerImg(type: DockerBuildImage) {
    inputDir = file("$rootProject.projectDir/docker")
}
```

I can get the `sha256:...` string for the image with another task:

```
task inspect(type: DockerInspectImage) {
    dependsOn buildBaseDockerImg

    targetImageId buildBaseDockerImg.imageId

    onNext { image ->
        // the sha256:.. is at `image.config.image`
    }
}
```

However, in the `onNext` closure seems to be too late to configure the `jib` extension to use the `sha256:...`. Is there a way to do this?

Note: even when I configure the `jib` extension with something like

```
jib {
    from {
        image = 'sha256:...'
    }
```

it still seems to be trying to pull that from a repository, which of course doesn't work since I didn't push it anywhere. Does jib only know how to use base images that it pulls from a repo?

**Comment by chanseokoh** [comment]
Hi @marshallpierce,

Yes, Jib can only get the base image from a registry repo. There is no other way of supplying a base image than pulling it from a registry, unfortunately. The only workaround I can think of is to push the image built by the Gradle Docker Plugin to some registry (could be a private local registry).

Out of curiosity, where exactly does the Gradle Docker Plugin save the built image in which format? A `.tar` file in a build directory? Or, does it push directly into a local Docker daemon?

**Comment by marshallpierce** [comment]
Thanks for the clarification. Suppose I alter my gradle tasks so that instead of just building it, it pushes it to a registry. That still leaves the question of how to just-in-time configure jib to know the `sha256:...` of the image (which is now available in a registry), right?

AFAIK, the plugin simply is a wrapper around the docker remote API, so it would simply do its work via the  docker daemon.

**Comment by chanseokoh** [comment]
> That still leaves the question of how to just-in-time configure jib to know the `sha256:...` of the image (which is now available in a registry), right?

I think so. Not sure what would be the best way to achieve this, since you can do all sorts of crazy things with Gradle. As long as you set the `jib.from.image` correctly to get the right base image, it should work.

**Comment by marshallpierce** [comment]
Interesting. When I tried setting it from inside `onNext` it didn't work; maybe scoping issues got in the way. What about configuring tasks manually? Any thoughts on replicating what the `jib` extension is doing?

**Comment by chanseokoh** [comment]
```
jib {
    from {
        image = 'sha256:...'
    }
```
I suspect you may not be providing the correct value to `jib.from.image`. The value should be an image reference, e.g., that you would use with `docker pull/push` and such. That is, on the command line, `docker pull sha256:whatever` should work as well. I don't think it will.

> What about configuring tasks manually? Any thoughts on replicating what the jib extension is doing?

Sorry, not sure what you're talking about.

**Comment by marshallpierce** [comment]
Configuring tasks manually means doing whatever the plugin does to the task graph, except by hand in the gradle file.

I'll look into generating a tag. https://github.com/GoogleContainerTools/jib/issues/1360 led me to belieave that `sha256:...` should work, but maybe it doesn't...?

**Comment by chanseokoh** [comment]
> `sha256:...` should work, but maybe it doesn't...?

In #1360, it's `openjdk@sha256:...`. That is, `docker pull openjdk@sha256:...` will work, whereas `docker pull sha256...` won't. Do you see the difference in the image reference?

I think setting a tag as @loosebazooka said may work.

**Comment by marshallpierce** [comment]
Yeah, noted -- I misunderstood the problem #1360 had.

**Comment by loosebazooka** [comment]
@marshallpierce to clarify, what I mean is doing something like this in your build.gradle and using that `uuidTag` everywhere
```
def uuidTag = UUID.randomUUID().toString()
println uuidTag
```

**Comment by loosebazooka** [comment]
Just curious if you're planning on building the base image every time? It would seem sub-optimal to mix docker and jib like this in *most* cases. However, I'm not sure about your workflow: does it not make sense in your case to do the base image build on a separate isolated project?

**Comment by marshallpierce** [comment]
Most times the base image will not need to be rebuilt, but the setup it does is project specific. It's possible to do it in another project but then it's just another thing to maintain and version. It would be more convenient to have a Dockerfile that does OS-level or other environmental setup and a Jib build all integrated into the same project.

**Comment by loosebazooka** [comment]
Gotcha. I'll go ahead and close this for now. Please open a new bug if you're having trouble further optimizing your build with jib.
