### ISSUE TITLE
jib-maven-plugin with version 1.0.0 : Giving <user> context to plugin not working

### ISSUE THREAD

**Issue by nrvmodi** [GoogleContainerTools/jib#1447]
jib-maven-plugin with version 1.0.0 has an issue in giving user context to plugin not working. Container must be run with given user.

Provide username into `<user>ray</user>`. 

Ubuntu 18, mvn 3.5.2, Java version: 1.8.0_181, jib-mave-plugin: 1.0.0: 

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${jib-maven-plugin.version}</version>
                <configuration>
                    <from>
                        <image>openjdk:8-jre-alpine</image>
                    </from>
                    <to>
                        <image>nrvmodi/${project.artifactId}:${project.version}</image>
                    </to>
                    <container>
                        <entrypoint>
                            <shell>sh</shell>
                            <option>-c</option>
                            <arg>chmod +x /entrypoint.sh &amp;&amp; sync &amp;&amp; /entrypoint.sh</arg>
                        </entrypoint>
                        <ports>
                            <port>38099</port>
                        </ports>
                        <environment>
                            <SPRING_OUTPUT_ANSI_ENABLED>ALWAYS</SPRING_OUTPUT_ANSI_ENABLED>
                            <JHIPSTER_SLEEP>0</JHIPSTER_SLEEP>
                        </environment>
                        <useCurrentTimestamp>true</useCurrentTimestamp>
                        <user>niravmodi</user>
                    </container>
                </configuration>
            </plugin>
```

**Log output**: 

ERROR: for 1288bb956df9_ray-hub-service  Cannot start service test-service: b'linux spec user: unable to find user niravmodi: no matching entries in passwd file'

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @nrvmodi,

The OS in your base image doesn't have the user `niravmodi`; you have to add the user to the OS yourself. On Linux, you would normally use `useradd` and `groupadd`(e.g., like [this](https://github.com/GoogleContainerTools/jib/issues/1029#issuecomment-424511638)). You could do the same, upload the base image with the user to a registry, and have Jib use that custom image.

Alternatively, I believe all you need is to have the right entry in `/etc/passwd` (and `/etc/group` if applicable), so I guess you can [supply a custom `passwd` file](https://github.com/GoogleContainerTools/jib/issues/1029#issuecomment-428625154). Then, you can place the file at `src/main/jib/etc/passwd`, which Jib will pick up and put it at `/etc/passwd` in the image.

**Comment by chanseokoh** [comment]
But if it is fine to use a uid (i.e., number) and you don't have to use a name (like `niravmodi`), you don't necessarily have to add a user, for example, if all you want is to run your application inside the container as a non-root.

**Comment by chanseokoh** [comment]
I believe now you understand the nature of the problem. Feel free to re-open if you still have suggestions or feedback about this.
