### ISSUE TITLE
jib:build fails on push with odd "auths" in .docker/config.json" but docker-push succeeds

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1460]
@chees hit an issue where he had a `.docker/config.json` with an `auths` section like the following (the email was literally `not@val.id`, but the `xxx-random-token-xxx` was a long base64 token that I replaced):

```
  "credHelpers": {
    "gcr.io": "gcloud", 
    "us.gcr.io": "gcloud", 
    "eu.gcr.io": "gcloud", 
    "asia.gcr.io": "gcloud", 
    "staging-k8s.gcr.io": "gcloud", 
    "marketplace.gcr.io": "gcloud"
  }, 
  "auths": {
    "https://gcr.io": {
      "email": "not@val.id",
      "auth": "xxx-random-token-xxx"
    }
  }
```
There were identical "auths" entries for `eu.gcr.io`, `marketplace.gcr.io`, etc.  With this config.json, pushes from jib failed but `docker push` succeeded.  Removing these `auths` let jib:build succeed.  It seems that `docker push` either has a different order of evaluation or it tries several approaches before failing.

**Comment by briandealwis** [comment]
I found [references to similar auths](https://github.com/docker/docker-py/issues/1930) from using the now-deprecated `gcloud docker login`.  The `"auth"` token looks like it could be an access token.

**Comment by chanseokoh** [comment]
This is essentially a dup of #1819. I'll update the issue description in #1819 and close this.
