### ISSUE TITLE
how can i add Docker's CMD or RUN instruction 

### ISSUE THREAD

**Issue by cg837718548** [GoogleContainerTools/jib#1477]
how can i add Docker's CMD or RUN instruction ?

**Comment by TadCordle** [comment]
RUN is not supported in Jib for speed/reproducibility reasons. If you need to use RUN, you can try making a custom base image using Docker and then pointing to that base image in Jib; see the [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-need-to-run-commands-like-apt-get) for details.

For CMD, you can actually use the `container.args` parameter, if you set a custom `container.entrypoint`. Normally `args` are used for appending Java main class arguments to the entrypoint, but Jib's `args` parameter actually corresponds directly to `CMD` in the container config, so you may be able to use it for your purposes. See [jib-gradle-plugin](https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/README.md#container-closure) or [jib-maven-plugin](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/README.md#container-object) README for more details. There's also an example in the [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-would-a-dockerfile-for-a-jib-built-image-look-like) that shows what a corresponding Dockerfile would look like, which may make it a bit clearer.
