### ISSUE TITLE
Unable to create a container for a war project using a dependency

### ISSUE THREAD

**Issue by susp248** [GoogleContainerTools/jib#1482]
I need to build a war container at a later stage *outside* of the actual maven project that builds the war.

Is there a way to achieve this?

**Environment**:  Maven

**Comment by briandealwis** [comment]
Could you please provide a bit more detail?  What do you mean by _a later stage_?  Are you looking to generate a war after your Maven build has finished?

**Comment by susp248** [comment]
Sure, sorry for the brevity.

Basically I like to consume the war-artifact in dedicated module of a Maven multi module project.

We already do this to build an installer artifact in one module. So it would be natural to encapsulate the container generation in a specialized module as well.

Looking at the current implementation I am missing this option.

I hope this is clearer now, please let me know if I can add information.

**Comment by chanseokoh** [comment]
I'd like to see a bit more details about how you actually pull in and consume the WAR-artifact built by another module. If possible, can you describe simplified root and sub-module `pom.xml` files? Depending on how they are set up, there might be a hack to make it work although I'm not so optimistic.

**Comment by susp248** [comment]
A basic directory structure would look like the following (leaving out non-relevant modules):
```
root
   war
   installer
   docker
```
root/pom.xml likewise lists the dependent modules:

```
  <modules>
    <module>war</module>
    <module>installer</module>
    <module>docker</module>
  <modules>
```

root/installer/pom.xml pulls in the artifact from the war module via maven-dependencies plugin and processes it further to build an installer (left out for brevity):

```
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy web archive</id>
            <phase>compile</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <artifactId>war</artifactId>
                  <groupId>myproject</groupId>
                  <version>${project.version}</version>
                  <type>war</type>
                </artifactItem>
              </artifactItems>
              <stripVersion>true</stripVersion>
              <outputDirectory>${project.build.directory}/installer/</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

So far this is pretty basic stuff. Of course it would also be possible to unpack the war artifact here via a different goal.

What I am missing is the option to do the same in the docker module. I can also copy/unpack the war artifact here but I am unable to tell the jib-plugin that it should process the (unpacked) artifact as it would do with the war module.

Does this make sense? I gladly add more information if required.

**Comment by briandealwis** [comment]
Sorry @susp248 but I'm not clear what you mean by this "processing unpackaged artifacts" or what your "installer" does.

Jib's war support **may** be able to drop your `docker` step: Jib creates a runnable container image from your war with no other steps.  It uses Jetty to directly run your war using the [Jetty distroless container image](https://github.com/GoogleContainerTools/distroless/).

If your processing is more involved, then Jib is unlikely to help.  But you can create your own plugin using [Jib-Core](https://github.com/GoogleContainerTools/jib/tree/master/jib-core#jib-core---java-library-for-building-containers), our Java library for building container images that underpins the Jib Maven and Gradle plugins.

**Comment by chanseokoh** [comment]
I think I get what @susp248 is talking about. The `war/` module is a normal WAR-building project, and you want the `docker/` module which will pick up (or copy/unpack) a WAR built by `war/` (similarly how the existing `installer/` module does using `maven-dependency-plugin`) and configure Jib there to build a container with the WAR. I do get your desire to make things look consistent by separating the WAR-building project and projects to post-process the WAR (such as `installer/` which creates a custom installer for the WAR).

It might be possible to hack around to make Jib work in the `docker/` module, but I think it would be too hacky. Even the hacky way worked, it may break in the long run, as it is not Jib's design to pick up and containerize an arbitrary WAR. And honestly, I don't see a practical difference between having a `docker/` module you want and having an additional profile set up in the `war/` module that will invoke `jib:build` at a later stage.

**Comment by susp248** [comment]
@briandealwis:

'installer' is building installer artifacts (executables) for various os-platforms intended to be distributed for download of the product. It includes the war archive as well as application-server ready to be deployed by a human user.

Likewise I want to integrate a build step for a docker artifact to either run it directly as a test instance during development (basically what you describe above) or build a tar to distribute it to a repository for release.

To follow a seperation of concerns I want to decouple the war creation step from the docker/jib related activities and encapsulate this in a different maven module. The most important part for me is to do this without relying on an external docker instance to be present.

with 'processing unpackaged artifacts' I was referrring to what I guess that the jib-maven-plugin is expecting in a maven war project (I assume that this is either the build artifact/war-archive or the target-folder directory containing the war-content).

I want to use a tomcat image as a base and I might need to add some files to the application server for this to work, but I think this is already supported here.

Hope this helps clearing this up

**Comment by briandealwis** [comment]
Thanks @susp248, I  get the picture now.

Jib is designed to efficiently package a _war project_ into a container image for faster redeploys on changes.  The first thing an app server does when seeing a war is to extract it (or "explode").  Jib doesn't actually use the packaged `.war`, but instead copies the war contents into place.  Placing the exploded war content into different layers enables faster container redeploys, as only changed layers need to be pushed, and also enables faster container startup, since the app server doesn't have to extract the .war.  This matters for container-centric development, like with Kubernetes.

You could use Jib to create a tarball of your container.  We don't currently attach the tarball as a build artifact, but you could use an ant-task or something to copy it out somewhere.

**Comment by susp248** [comment]
Thank you @chanseokoh and @briandealwis for your comments and explanations.

Maybe it helps to add another example of what is needed to make this work, as I do not think that any kind of hack is really needed here.

To summarize I like to specify the following in an arbitrary maven project:

```
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <version>1.0.0</version>
  <executions>
    <execution>
      <goals>
        <goal>buildTar</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <webAppDirectory>${project.build.directory}/mywebappdirectory/</webAppDirectory>
    <from>
      ...
    </from>
    <to>
      ...
    </to>
  </configuration>
</plugin>

```
${project.build.directory}/mywebappdirectory/ contains the exploded war archive content which I like to process with jib. As shown in #1487, this parameter should be supported anyway, as the war content can live in another directory even if the project is bound to a war-artifact.

Both the creation of the ${project.build.directory}/mywebappdirectory/ folder as well as the further handling of the generated tar archive would be out of scope of the jib-maven-plugin here.

Please note that the buildTar goal is just one example and the behavior should not be limited to this goal. I would expect this to work for the other jib goals as well.

So the only thing left to change would be to override the auto-detection of the project artifact in this case. The trigger for this could be bound to the <webAppDirectory> configuration or any other mechanism.

Does this make sense as an acceptable solution or am I missing something here?

**Comment by chanseokoh** [comment]
> As shown in #1487, this parameter should be supported anyway, as the war content can live in another directory even if the project is bound to a war-artifact.

I've updated #1487. Basically, I don't think it's a good idea to have this parameter supported in Jib. Jib can just read the configuration of `maven-war-plugin`.

**Comment by chanseokoh** [comment]
> It might be possible to hack around to make Jib work in the `docker/` module, but I think it would be too hacky.

I still think having a profile or bind Jib to a different Maven lifecycle phase will work better in your case, but if you absolutely want a separate module for running Jib, I can think of the following untested hack (which I am not thrilled for):

1. Create an empty module, e.g., `docker/` and add Jib.
1. Set `<packaging>war</packaging>`. Whether or not the `maven-war-plugin` breaks doesn't matter here; you would not run `mvn package` in this module. This is only for signaling to Jib that it should read the exploded WAR from `docker/target/final-name`. You may unbind `maven-war-plugin` from the `package` phase, if needed.
1. Copy the WAR from another module into `docker/target/final-name`. I'm sure there are various ways to achieve this. Using the [`copy-resources` goal](https://maven.apache.org/plugins/maven-resources-plugin/examples/copy-resources.html) might work.
1. Do `mvn jib:build` inside the empty module.

**Comment by susp248** [comment]
> I still think having a profile or bind Jib to a different Maven lifecycle phase will work better in your case, but if you absolutely want a separate module for running Jib, I can think of the following untested hack (which I am not thrilled for):

I tried this, the solution is of course terrifying and disgusting but works great otherwise, so thanks a lot for the idea!

The following pom.xml snippet illustrates the needed steps:
```
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <executions>
          <execution>
            <id>copy web archive</id>
            <phase>compile</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>mygroup</groupId>
                  <artifactId>mywar</artifactId>
                  <version>${project.version}</version>
                  <type>war</type>
                </artifactItem>
              </artifactItems>
              <stripVersion>false</stripVersion>
              <outputDirectory>${project.build.directory}/${project.artifactId}-${project.version}</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>jib-maven-plugin</artifactId>
        <version>1.0.0</version>
        <executions>
          <execution>
            <id>build docker image</id>
            <goals>
              <goal>buildTar</goal>
            </goals>
            <phase>compile</phase>
            <configuration>
              <from>
                <image>tomcat:8.5-jre8-alpine</image>
              </from>
            </configuration>
          </execution>
        </executions>
      </plugin>
      
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <descriptors>
            <descriptor>src/assemble/distribution.xml</descriptor>
          </descriptors>
          <appendAssemblyId>true</appendAssemblyId>
        </configuration>
      </plugin>

    </plugins>
  </build>

```
To honor the hardcoded value in #1487 the outputDirectory for maven-dependencies-plugin  is required to be `${project.build.directory}/${project.artifactId}-${project.version}`. Do not forget to add a dummy web.xml in `src/main/webapp/WEB-INF` to satisfy the maven-war-plugin.

`src/assemble/distribution.xml` looks as follows:

<?xml version='1.0' encoding='UTF-8'?>
```
<assembly xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.2
                      http://maven.apache.org/xsd/assembly-1.1.2.xsd">
  <id>dist</id>
  <formats>
    <format>zip</format>
  </formats>
  <includeBaseDirectory>false</includeBaseDirectory>
  <fileSets>
    <fileSet>
      <directory>${project.build.directory}</directory>
      <includes>
        <include>jib-image.*</include>
      </includes>
      <outputDirectory></outputDirectory>
    </fileSet>
  </fileSets>
</assembly>

```
This setup allows me to install and deploy the generated docker tar as an additional artifact to our repository  for release builds. There will also be a dummy war artifact created and deployed alongside which is somewhat tolerable.

I added this detailed answer to help others who might be interested in a similar solution.

Again, thanks for your support!

**Comment by chanseokoh** [comment]
Thanks for the update. Good to confirm it works. (But I should say I don't recommend this type of hack.) I'll close this issue, as we don't think we will support containerizing an arbitrary WAR coming from the outside of a project.

Also remember that, as noted in #1487, Jib may eventually unpack a WAR instead of looking into the exploded WAR directory. When that happens, you'll need to copy a WAR instead of unpacking it.

* Some minor notes:

`${project.build.directory}/${project.artifactId}-${project.version}`

Maybe `${project.build.directory}/${project.build.finalName}` is more accurate. This is the [default value of `<webappDirectory>` of `maven-war-plugin`](https://maven.apache.org/plugins/maven-war-plugin/war-mojo.html). and Jib does
```java
project.getBuild().getDirectory()).resolve(project.getBuild().getFinalName())
```
to match that. I think it is possible that `${project.artifactId}-${project.version}` is different from `${project.build.finalName}` when not using default values.
