### ISSUE TITLE
Missing libjpeg.so java 11

### ISSUE THREAD

**Issue by RobMaskell** [GoogleContainerTools/jib#1486]
**Description of the issue**: The docker images build ok, but I get an exception thrown when the container runs. The application is a spring boot 2.1.x app that runs ok in the IDE against java 11.

I'm not sure if this is a Jib issue or distroless one, I thought I'd start here.

**Expected behavior**: No exception

**Steps to reproduce**: Jib a spring boot 2.1.x app that uses image handling parts of java 11 and attempt to run the container on your local docker.

**Environment**: Elementary Linux / Java 11 / Gradle / Spring boot 2.1.x

**`jib-gradle-plugin` Configuration**: 
```groovy
sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

bootRun {
  systemProperties = System.properties // needed for intellij
  systemProperties.remove("java.endorsed.dirs")
}

	jib {
		from.image 'gcr.io/distroless/java:11'
		to.image project.getParent().getName() + "/" + bootJar.getBaseName()
		container({
			useCurrentTimestamp = true
			ports = ['80']
			jvmFlags = ['-Djava.security.egd=file:/dev/./urandom', '-XX:+UseG1GC']
		})
		
	}
```

**Log output**: 

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataLoader': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-openjdk-amd64/lib/libjavajpeg.so: libjpeg.so.62: cannot open shared object file: No such file or directory`

`Caused by: java.lang.UnsatisfiedLinkError: /usr/lib/jvm/java-11-openjdk-amd64/lib/libjavajpeg.so: libjpeg.so.62: cannot open shared object file: No such file or directory`

**Comment by chanseokoh** [comment]
Looks like Distroless is missing the shared library and needs the `libjpeg62` Debian package installed.

**Comment by RobMaskell** [comment]
Am I better off raising it against that project?

**Comment by RobMaskell** [comment]
Raised against distroless instead https://github.com/GoogleContainerTools/distroless/issues/300
