### ISSUE TITLE
jib-maven-plugin is hardcoding the webappDirectory path for war plugins

### ISSUE THREAD

**Issue by susp248** [GoogleContainerTools/jib#1487]
**Description of the issue**:
The current implementation is assuming that  the web app is always residing in ${project.build.directory}/${project.build.finalName} which is only the default value.

This path is actually configurable per <webappDirectory> configuration parameter so jib should not rely on this.

**Steps to reproduce**:
Specify a <webappDirectory> configuration parameter in the maven-war-plugin.

**Expected behavior**:

The  <webappDirectory> should be made configurable in the jib-configuration.

**Environment**: Maven

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @susp248,

Thanks for opening the issue. We're aware that the WAR (and the exploded WAR) path is configurable with `maven-war-plugin` and have left the comment in the code.

```
    // TODO explode the WAR file rather than using this directory. The contents of the final WAR may
    // be different from this directory (it's possible to include or exclude files when packaging a
    // WAR). Also the exploded WAR directory is configurable with <webappDirectory> and may not be
    // at build.getFinalName().
```

> The should be made configurable in the jib-configuration.

However, I don't think this should be made configurable in Jib. Jib can get the value from `maven-war-plugin`, so no need to make it configuration on the Jib side.

**Comment by chanseokoh** [comment]
When we unpack the WAR, for the final WAR file location, maybe we should read `<outputDirectory>` (which defaults to `target/`) instead of `<webappDirectory>`.

**Comment by ldetmer** [comment]
Please note our updated [contributing policy](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md).
We are primarily focused on critical bug fixes and platform evolution to ensure it continues to work for its supported use cases. Closing as out of scope.
