### ISSUE TITLE
Running a fat jar

### ISSUE THREAD

**Issue by j75** [GoogleContainerTools/jib#1489]
**Description of the issue**: Would it be possible to skip copying the **/app/libs**/ , **/app/resources/** and **/app/classes/** in case of running a fat jar ?

**Expected behavior**: just copy the target/my-fat.jar to **appRoot**

**Additional Information**: 
This is not actually an *issue*, it is mostly a suggestion/request for information. I already found a way to run my jar but this plugin copies unnecessary files, wasting space & time.

**Comment by briandealwis** [comment]
Duplicate of #530
