### ISSUE TITLE
Distroless update broke integration tests

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1491]
Several integration tests check for JVM flags, and it looks like https://github.com/GoogleContainerTools/distroless/pull/295 added some, which is making the tests fail.

Example output of one:

```
[ERROR] testExecute_noToImageAndInvalidProjectName(com.google.cloud.tools.jib.maven.BuildDockerMojoIntegrationTest)  Time elapsed: 10.016 s  <<< FAILURE!
org.junit.ComparisonFailure: 
expected:<Hello, world. 
[]> but was:<Hello, world. 
[-XX:+UnlockExperimentalVMOptions
-XX:+UseCGroupMemoryLimitForHeap
]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.google.cloud.tools.jib.maven.BuildDockerMojoIntegrationTest.testExecute_noToImageAndInvalidProjectName(BuildDockerMojoIntegrationTest.java:187)
...
```

**Comment by chanseokoh** [comment]
Don't work on it just yet. We reverted https://github.com/GoogleContainerTools/distroless/pull/295 in https://github.com/GoogleContainerTools/distroless/pull/305.

**Comment by TadCordle** [comment]
Will setting the JVM flags in the entrypoint instead of using _JAVA_OPTIONS make a difference? The test projects that our integration tests use print the JVM flags.

**Comment by briandealwis** [comment]
Jib overwrites the entrypoint. We should probably teach jib to  (somehow) copy it the JVM flags if none are specified.

It's unfortunate that the JVM output about `JAVA_TOOL_OPTIONS` and  `_JAVA_OPTIONS` can't be suppressed as `_JAVA_OPTIONS` is perfect for these types of flags.
