### ISSUE TITLE
Support script plugins in files task

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1494]
https://github.com/GoogleContainerTools/jib/pull/1492#discussion_r258646217

>we may also need to deal with script plugins here (https://docs.gradle.org/current/userguide/plugins.html#sec:script_plugins)
I think there's a way to query it, but I'm not sure.

**Comment by loosebazooka** [comment]
While this can technically occur, I think we can close this for now and deal with it as it comes up. Use of `apply from:` seems to be pretty rare and we haven't run into yet.
