### ISSUE TITLE
Micronaut  Example Main class was not found, perhaps you should add a `mainClass` configuration to jib

### ISSUE THREAD

**Issue by grailsweb** [GoogleContainerTools/jib#1495]
**Description of the issue**:
Micronaut example not compiling

**Expected behavior**:
create docker image

**Steps to reproduce**:  

./gradlew jibDockerBuild

**Environment**: 

Linux, gralde, JDK 11

 
**`jib-gradle-plugin` Configuration**: 
```groovy
plugins {
    id 'application'
    id 'groovy'
    id 'io.spring.dependency-management' version '1.0.6.RELEASE'
    id 'net.ltgt.apt-idea' version '0.18'
    id 'com.google.cloud.tools.jib' version '1.0.0'
}

version '0.1'
group 'example.micronaut-jib'
sourceCompatibility = 1.8

repositories {
    mavenCentral()
    maven { url 'https://jcenter.bintray.com' }
}

dependencyManagement {
    imports {
        mavenBom 'io.micronaut:micronaut-bom:1.0.3'
    }
}

dependencies {
    annotationProcessor 'io.micronaut:micronaut-inject-java'
    compile 'io.micronaut:micronaut-http-client'
    compile 'io.micronaut:micronaut-http-server-netty'
    compile 'io.micronaut:micronaut-runtime-groovy'
    compile 'io.micronaut:micronaut-inject'
    compile 'io.micronaut:micronaut-runtime'
    compileOnly 'io.micronaut:micronaut-inject-groovy'
    compileOnly 'io.micronaut:micronaut-inject-java'
    runtime 'ch.qos.logback:logback-classic:1.2.3'
    testCompile 'io.micronaut:micronaut-inject-groovy'
    testCompile('org.spockframework:spock-core:1.2-groovy-2.5') {
        exclude group: 'org.codehaus.groovy', module: 'groovy-all'
    }
    testCompile 'io.micronaut:micronaut-inject-java'
}

compileJava.options.compilerArgs += '-parameters'
compileTestJava.options.compilerArgs += '-parameters'
run.main = 'example.micronaut.Application'


```

**Log output**: 

./gradlew jibDockerBuild  --image=test
> Task :jibDockerBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jibDockerBuild'.
> com.google.cloud.tools.jib.plugins.common.MainClassInferenceException: Main class was not found, perhaps you should add a `mainClass` configuration to jib

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Additional Information**:

**Comment by briandealwis** [comment]
Hmm this seems to be deeper than jib:
```sh
$ ./gradlew build
> Task :startScripts FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':startScripts'.
> No value has been specified for property 'mainClassName'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
4 actionable tasks: 1 executed, 3 up-to-date
```

**Comment by grailsweb** [comment]
I have to added below section in my build.gradle file
`jib {
    container.mainClass = "webapp.Application"
}`

still registry authentication fails, but image build works.

**Comment by chanseokoh** [comment]
But l think the bigger problem is that the application itself does not build, even before attempting Jib.

**Comment by coollog** [comment]
Hi @grailsweb, we fixed an issue with finding the main class for a Groovy application in version `1.0.1` - if you update the version of Jib, I believe the build should work.

**Comment by grailsweb** [comment]
Yes, it complies now. Thanks

**Comment by chanseokoh** [comment]
Reopnenning since there is a build and run problem in the application itself.
