### ISSUE TITLE
Make integration tests run examples

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#1507]
TODO

**Comment by Belair34** [comment]
Can anyone provide some more details on this issue? Or is this issue irrelevant at this point?

**Comment by elefeint** [comment]
We do have integration tests for examples in Spring Cloud GCP, and it's valuable to automatically test, let's say, Spring Boot major version upgrades. However, Jib has an extensive suite of integration tests, so the value would be marginal given the available resources.

I am going to close the issue as not planned.

@Belair34 if you are a college student, I recommend looking for issues [labeled "good first issue"](https://github.com/search?q=label%3Agood-first-issue&type=issues)
