### ISSUE TITLE
Jib should propagate JVM flags from base image

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1508]
Some base images run the JVM with specific flags, such as [distroless/java](https://github.com/GoogleContainerTools/distroless/pull/305) to enable container-friendly settings.  Flags could be used to define system properties (`-D...`) or to configure agents (`-agentlib`).

Jib currently constructs a custom entrypoint for an image unless instructed with [the `inherit` flag](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage). But these entrypoints may not be suitable for `inherit`: distroless/java, for example, assumes that it is provided a jar and specifies `java -X... -jar`, whereas Jib needs to specify a class path.

There are a couple of possibilities:
  - Jib could examine the base image's entrypoint and copy out flags when constructing an entrypoint.  Perhaps it should only copy out a subset of known flags?
  - Jib `inherit` could strip `-jar` if found as the last parameter

The latter would be easiest.

**Comment by chanseokoh** [comment]
I think we can close this. The container-friendly flags was the main target, but we don't need them anymore. It is also not common that Java base images set certain JVM flags, but even before, it is rarely that base images have `java -jar` as an entrypoint. More importantly, people usually don't expect automatically inheriting arbitrary flags, as this doesn't happen in `Dockerfile`. And I think if they want to set certain flags in their final image, they should be better doing it explicitly. We wanted to make sure the user gets the container-friendly flags, but this is no longer an issue.
