### ISSUE TITLE
Rename Credential.basic(username, password)

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1526]
After the support of OAuth2 in #1511, we now have an OAuth2 flow in addition to the basic auth flow. (FTR, in OAuth2 case, a `Credential` instance holds the fixed constant `<token>` as a username and the OAuth2 refresh token as a password.) The name `Credential.basic()` does not fit well with the OAuth2 flow.

Maybe just `Credential.of(username, password)`? Or, we could turn `Credential` from a simple holder to a more high-level abstraction for both basic auth and OAuth. But since there's no need to directly instantiate an OAuth2 `Credential` instance (the Docker spec returns the explicit username `<token>` and that's how we instantiate the simple holder in practice), so I'm leaning toward the current simple holder.

**Comment by andxu** [comment]
Credential.from?
