### ISSUE TITLE
Configuration settings for development environment

### ISSUE THREAD

**Issue by karthiks** [GoogleContainerTools/jib#1527]
**Description of the issue**:
In development environment (esp, in cases like mine where I use Spring Boot), I wouldn't' want to deploy my container to see the code changes. I would rather prefer hot-deploy, with the volume in the container pointing to my development directory to skip deployment step and boost developer productivity.

**Expected behavior**:
There doesn't seem to be scope for it in Jib or am I missing something, here in the docs?

**Steps to reproduce**: 
Not Applicable

**Environment**: 
Irrelevant

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @karthiks,

Could you detail your setup and use-case? Particularly, how have you been achieving your normal workflow of the "hot-deploy, with the volume in container to my development directory" prior to Jib (e.g., using a Dockerfile)? Are you creating a Docker image that does not actually have an app in it, and you link in an app later through volume mount? Is that same image also used in production?

**Comment by karthiks** [comment]
Hi @chanseokoh,

Here is a [reference blog post](https://hackernoon.com/efficient-development-with-docker-and-docker-compose-e354b4d24831) that details how hot deploy can be achieved with `docker` and `docker-compose` using a Python app. In my case I do this for my SpringBoot Java app.

Because Jib gives me the convenience to escape hand-crafting a Dockerfile, I'm looking forward to see how I can have a similar setting in Jib.

Think of it, why would you want a developer to build an image and deploy it for verifying the validity of his every code change. He is much more productive with simple hot deploy, right?

**Comment by chanseokoh** [comment]
Just read the blog post. I think you can just follow what the post says and it will work, because it just overrides the entrypoint to a completely new one:
```
sh -c 'find src/ | entr mvn clean compile exec:java --batch-mode --quiet'
```
That is, it ignores everything about the image you built, and it just runs that command against your source directory, which will fire up a Servlet engine inside the image to run your Spring Boot app re-built from your source directory. So, do note that this trick is merely replacing what the actual image is supposed to do with something completely unrelated. That is, the trick in the blog post is to ignore everything in the production image and just do `mvn clean compile exec:java` just for the sake of running something completely unrelated inside a container. For this reason, even if you are using docker-compose, you are not testing the image itself. Honestly, I'd rather do `mvn clean compile exec:java` locally on the command line outside an image (with `entr`, of course), since the only different is whether you run that command inside or outside some arbitrary image. This seems like a matter of how close you want your dev/test env to the prod env. The purpose of docker-compose may be to have a closer local dev env, but overriding what the image is supposed to do seems like defeating its purpose to some degree.

**Comment by karthiks** [comment]
:-) I gave a reference blog to answer your question of what a development set-up looks like. The use-case is the development setup itself for productive development. That blog post was not meant to highlight the hack and showcase it to me as the solution :-/

We are in agreement on what the hack is and why it isn't great. Here is the deal, irrespective of the tech-stack, mounting the development directory as readable volume of the container should ideally be a doable thing or so do I wish. It brings the productivity of a developer in orders of magnitude.

I'd like to know if there is a way I can mount my dev directory as volume that the app in the container looks at? This is not a business case specific requirement. It is a developer productivity-centric requirement.

Please do let me know your thoughts.

**Comment by chanseokoh** [comment]
> mounting the development directory as readable volume of the container should ideally be a doable thing

This is doable, of course. Nothing prevents you from mounting any directory to an arbitrary location inside an image. However, mounting your source repo won't magically make your image recompile your source repo. Even if you mount directories containing `.class` files that are somehow recompiled outside the image, doing so won't magically make the already running JVM pick up the new `.class` files and replace previous classes already loaded in the JVM. Therefore, the point of the hackery in that blog was to blatantly override the entrypoint of an image and instead run `entr` for the sake of watching file changes of a source repo to trigger a full rebuild (`mvn clean compile`) and run the recompiled app (`mvn java:exec`) whenever `entr` detects file changes. To emphasize again, for the idea of directly mounting a source repo to work as you wish, you must override the entrypoint of an image anyway, not to mention that you have to watch file changes, re-trigger full builds, and re-launch another JVM each time, ignoring what the image is designed to do.

But I can tell you there exists a far much better (and simple) way to achieve what you really want: Java remote debugging. You are probably aware that when you launch a simple debug session in an IDE, whenever you change your source code in the IDE, the changes become effective instantly on the running app in the debug session. Essentially, you'll do the same thing in your case. Whether your app is running inside an image or not is irrelevant; as long as you connect your IDE debugger to the running app, you'll instantly have the same degree of productivity from instant class reloading. Not only this approach is much more superior than the file-change-watch-and-full-rebuild-and-JVM-relaunch hackery in terms of productivity, it will result in working with the same prod image on your dev environment. If you haven't known, it is easy to set up this remote debug. You pass some argument to your JVM, and make your debugger connect to it through the configured port. Take a look our [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-enable-debugging) and articles like https://jaxenter.com/remote-debugging-java-applications-151466.html. (You may find better articles when googling "java remote debug".)

**Comment by karthiks** [comment]
Doable? Please tell me how do you do that with jib using maven and/or gradle plugin. 
What did I miss in the doc to achieve this?
Thanks in advance!

**Comment by chanseokoh** [comment]
One simple way to do it at runtime is to do `docker run -v /some/dir/in/host:/some/dir/in/image`. This works for any image, whether built by Jib or not. Inside the image, the contents of `/some/dir/in/host` will be accessible at `/some/dir/in/image`. The blog post you linked is doing the same thing, making your `<current directory>/java` directory on the host accessible at `/usr/src/app` inside the image.
```yaml
    volumes:
      - ./java/:/usr/src/app
```
I find this [StackOverflow answer](https://stackoverflow.com/a/34810191/1701388) informative. And also note that you can declare the Dockerfile-[`VOLUME`](https://docs.docker.com/engine/reference/builder/#volume)-equivalent with Jib: https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage (See the `volume` parameter.)

**Comment by karthiks** [comment]
Jib's selling point is not using/managing Dockerfile, IMHO. And so I was looking for ways to achieve it in declarative configuration in maven/gradle. Is that possible?

Are you recommending me the `extraDirectory` attribute in the Jib doc as its equivalent?

**Comment by chanseokoh** [comment]
Sorry, I did not mean using `Dockefile`. You don't need this. Here, mounting a volume is a runtime thing, and it is just that various runtimes (the Docker engine, Kubernetes, etc) provide ways to mount volumes at runtime. When creating/building an image, you don't want to fixate how exactly volumes will be mounted at runtime. The example `docker run -v` above is an example when the runtime to run your image is the Docker engine.

> Are you recommending me the `extraDirectory` attribute in the Jib doc as its equivalent?

I'm talking about the `volumes` attribute. Scroll down the doc more, and you'll see that. It'll look like [this](https://github.com/GoogleContainerTools/jib/issues/1121#issuecomment-434852883). (When I was saying `Dockerfile-VOLUME-equivalent`, I was saying this attribute will create the same image metadata as what the Dockerfile VOLUME directive will create.) But AFAIK, in this use case, I believe things like `docker run -v` will work without configuring `volumes`.

**Comment by chanseokoh** [comment]
Just saw your thumbs-up. I think you've got the answers you need. I'll close the issue.

Consider using the Java remote debugging. It'll enable all the goodies like instant class reloading, breakpoints, stepping through code, etc.
