### ISSUE TITLE
jib should warn when docker-credential-gcloud is not found for gcr.io

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1529]
@etanshaul hit a situation where he was unable to push to a repository on `gcr.io`. Although he had configured docker to authenticate using `gcloud auth configure-docker` (such that his `~/.docker/config.json` had credhelpers registered to `gcloud`), his `PATH` was wrong and `docker-credential-gcloud` was not found by Jib.  Jib silently moved on, and his push failed with an `UNAUTHORIZED`.  Jib should instead warn when a configured credential helper in the `config.js` cannot be found.

As an aside, Jib does warn if `docker-credential-gcr` is not found, regardless of whether it was configured as a credential helper.

**Comment by TadCordle** [comment]
It looks like we do log about missing inferred/configured credential helpers at the info level already, but we don't do anything when there are errors with credHelpers in the docker config. So I guess this is just a matter of adding a couple more log statements.
