### ISSUE TITLE
Update documentation on java agent

### ISSUE THREAD

**Issue by CauchyPeano** [GoogleContainerTools/jib#1537]
Hi! Want to do small addition to documentation about how to add java agent into the image.

**Comment by chanseokoh** [comment]
Thanks! What kind of agent are you specifically thinking of? Or some general instructions for loading native agent libraries or Java agents?

BTW, we have an [FAQ on configuring JDWP debugging](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-enable-debugging), if that's relevant here.

**Comment by CauchyPeano** [comment]
@chanseokoh Its similar, yes. But I've thought it's still worth to have it that it will save some time for others.
Please check my draft PR https://github.com/GoogleContainerTools/jib/pull/1540

**Comment by chanseokoh** [comment]
Closed by #1540.
