### ISSUE TITLE
Attempt to retrieve base images from local docker daemon

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1542]
**Description of the issue**:

@saturnism suggested that Jib should first check if an image is available from the [local Docker Daemon](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-socket-option), if it's available, (via the [image export API](https://docs.docker.com/engine/api/v1.39/#operation/ImageGet)?) before hitting the network.  This could make a big difference when on a slow wifi connection.

**Comment by chanseokoh** [comment]
This I think is a duplicate of #1468. I really like this idea actually. There are already interesting discussions in #1468.
