### ISSUE TITLE
There is no app folder under / directory

### ISSUE THREAD

**Issue by kant111** [GoogleContainerTools/jib#1543]
I have multi project build setup. so my directory structure looks like this 

```
| - MyRepo
         | - myapp
           -  build.gradle
   -build.gralde 
   -settings.gradle

```

MyRepo `build.gradle` looks like this 

```
plugins {
    id 'com.palantir.git-version' version '0.12.0-rc2'
    id 'com.google.cloud.tools.jib' version '1.0.2'
}

allprojects {

    apply plugin: 'java'
    apply plugin: 'maven-publish'
    apply plugin: 'idea'
    sourceCompatibility = 1.8
    targetCompatibility = 1.8

  

    gradle.projectsEvaluated {
        tasks.withType(JavaCompile) {
            options.compilerArgs << "-Xlint:deprecation"
            options.compilerArgs << "-Xlint:unchecked"
        }
    }
}

subprojects {

    repositories {
        mavenLocal()
        mavenCentral()
        maven {
            url 'http://conjars.org/repo'
        }
    }

    ext {
        gitDetails = versionDetails()
    }

    tasks.withType(Jar) {
        destinationDirectory = file("$System.env.WORKSPACE/bin")
    }
}
```

myapp `build.gradle` looks like this 

```
dependencies {
    // This dependency is exported to consumers, that is to say found on their compile classpath.
    compile group: 'org.slf4j', name: 'slf4j-api', version: '1.7.25'
    compile group: 'org.slf4j', name: 'slf4j-log4j12', version: '1.7.25'
    compile 'com.orbitz.consul:consul-client:0.16.3'
    compile group: 'com.google.guava', name: 'guava', version: '21.0'
    compile 'commons-codec:commons-codec:1.11'
    // required if you want to use Mockito for unit tests
    testCompile 'org.mockito:mockito-core:2.7.22'
    testCompile group: 'junit', name: 'junit', version: '4.11'
}

jar {
    from { configurations.compile.collect { it.isDirectory() ? it : zipTree(it) } }
    exclude 'META-INF/.RSA', 'META-INF/.SF','META-INF/*.DSA'
}

jib {
    from {
        image = 'openjdk:alpine'
    }
    to {
        image = "localhost:5000/myapp"
        tags = ["latest"]
        extraDirectory = file('$System.env.SPARK_HOME'.toString())
        allowInsecureRegistries = true
    }
    container {
        entrypoint = ['java', '-cp', 'app/libs/*:app/resources:app/classes:$WORSPACE_HOME/jars/*', 'com.hello.app.MyApp']
        args = ['host=0.0.0.0', 'port=9100']
        ports = ['9100']
        format = 'OCI'
    }
}
```

when I do `gradle jib` under `MyRepo` it gets successfully pushed into my `localhost:5000/myapp` repo but then when i run `docker run -it --entrypoint /bin/sh localhost:5000/myapp` and do `ls` I dont see `app` folder at all under `/`.

Any ideas?

**Comment by chanseokoh** [comment]
FTR:

Conversation has been on the Gitter. The OP could see `/app` after running `gradle jib` on the subdirectory.

**Comment by kant111** [comment]
@chanseokoh I have both `jar` and `jib` task on some of the sub-projects. The goal here is when I do `gradle jib` I want the jib tasks that are defined in the subprojects to be executed. This is the default behavior for `jar` task so I was thinking `gradle jib` would do the same. I am not very familiar with gradle so any help is appreciated!

**Comment by kant111** [comment]
I added the `task jibAll(dependsOn: [subprojects.build, ":myapp:jib"]) {}` under MyRepo `build.gradle`. And I can invoke `gradle jibAll` from MyRepo and it seems to work but not sure if it is the best way.

**Comment by chanseokoh** [comment]
@loosebazooka will have better insights.

**Comment by loosebazooka** [comment]
`gradle jib` should run jib on all projects, that is the behavior of *gradle*. `gradle :jib` is the command one would use to only run it on the root project. However since `jib` isn't fully configured on the root, I don't think it can even run on the root (no `to.image` defined?)

Can you provide us with the output of `gradle jib --console==plain` so we can see what's really going on?

**Comment by kant111** [comment]
Output of `gradle jib --console=plain`

```
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :jib FAILED
No classes files were found - did you compile your project?

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jib'.
> Missing target image parameter, perhaps you should add a 'jib.to.image' configuration parameter to your build.gradle or set the parameter via the commandline (e.g. 'gradle jib --image <your image name>').

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
1 actionable task: 1 executed```

**Comment by kant111** [comment]
yes `to.image` is not defined on the root since I have `jib` defined in every sub project. when I run `gradle jib` I expected it would run all the `jib` tasks defined in the sub projects this is how for example `jar` tasks works in gradle.

**Comment by loosebazooka** [comment]
Since you're applying the plugin on the root, gradle expects to be able to run it on the root. What you can do to avoid having jib on the root is [only apply the plugin on subprojects](https://docs.gradle.org/current/userguide/plugins.html#sec:subprojects_plugins_dsl):

1. don't auto apply the plugin from the plugins block (apply false) this just lets you define the plugin and it's version without applying it on the base projects:
```gradle
plugins {
    ...
    id 'com.google.cloud.tools.jib' version '1.0.2' apply false
}
```

2. only apply the plugin in subprojects (or directly in the subproject's build.gradle)
```
subprojects {
    ...
    apply plugin 'com.google.cloud.tools.jib'
    ...
}
```

I believe then running `gradle jib` will only run on projects with that task defined.

**Comment by kant111** [comment]
Doesn't seem to quite work. `gradle jib` fails on subprojects where `jib` task is not defined. I just `gradle jib` to run all subprojects wherever it is defined but not throw an error if a subproject has no jib task defined.

**Comment by loosebazooka** [comment]
Yeah that makes sense. So maybe just apply the jib plugin directly on the
projects that use it (in the subproject build.gradle) instead of in the
parent build file. Best practices in gradle is to isolate the plugin to the
actual projects that use it.

**Comment by kant111** [comment]
@loosebazooka Got it! That seems to work.
