### ISSUE TITLE
Inherit OS/Architecture from base image

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1547]
We set [OS to "amd64" and Architecture "linux"](https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/image/json/ContainerConfigurationTemplate.java#L87-L91), but we should probably inherit them from the base image. I expect this will enable, for example, creating an ARM image.

A lot of official Docker Hub images support multiple architectures. [OpenJDK](https://hub.docker.com/_/openjdk) for example have the following images.

> **Supported architectures: (more info)**
> amd64, arm32v5, arm32v6, arm32v7, arm64v8, i386, ppc64le, s390x, windows-amd64

If you have to, you can force referencing/pulling architecture-specific images by, e.g., [`amd64/openjdk`](https://hub.docker.com/r/amd64/openjdk/) or [`arm64v8/openjdk`](https://hub.docker.com/r/arm64v8/openjdk/). However, `docker pull openjdk` will just pull the matching architecture on all supported platforms, and it should work.

**Comment by chanseokoh** [comment]
I wonder what needs to be done with the "scratch" image: #1471 #1550

**Comment by briandealwis** [comment]
"Scratch" doesn't actually exist.  So it's universal.

But your point stands: how do we set the os/arch and should we allow changing the os/arch?  I think given images like [balenalib/armv7hf-debian-openjdk](https://hub.docker.com/r/balenalib/armv7hf-debian-openjdk), which is labelled as an `amd64` image but is really an `armXX` image, we should allow changing the os/arch.

**Comment by loosebazooka** [comment]
so does `balenalib/armv7hf-debian-openjdk` even work? or is arch just metadata for human consumption that is ignored by the container runtime?

**Comment by briandealwis** [comment]
I haven't actually tried launching anything on arm but trying to run `java` on an `amd64` fails with invalid sys calls.  But the `/usr/lib/jvm/java-11-openjdk-armhf/bin/java` seems to be an ARM binary:
```sh
$ docker run --name arm balenalib/armv7hf-debian-openjdk:11-sid
'No CMD command was set in Dockerfile! Details about CMD command could be found in Dockerfile Guide section in our Docs. Here's the link: https://balena.io/docs
$ docker cp arm:/usr/lib/jvm/java-11-openjdk-armhf/bin/java .
$ file java
java: ELF 32-bit LSB pie executable ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=5ac7118e428a5f9a237cb68fd8a7ddaa341f2f9f, stripped
```

**Comment by briandealwis** [comment]
os and architecture are now inherited from the base image in Jib 1.1.0. Note that to use arch-specific Official Docker Hub Images, you will need to use an [architecture-specific organization](https://github.com/docker-library/official-images#architectures-other-than-amd64) like [`arm64v8/openjdk`](https://hub.docker.com/r/arm64v8/openjdk).

**Comment by chanseokoh** [comment]
> Note that to use arch-specific Official Docker Hub Images, you will need to use an [architecture-specific organization](https://github.com/docker-library/official-images#architectures-other-than-amd64) like [`arm64v8/openjdk`](https://hub.docker.com/r/arm64v8/openjdk).

Turns out this doesn't really work and you may need to use a specific digest: #2148

**Comment by chanseokoh** [comment]
> > Note that to use arch-specific Official Docker Hub Images, you will need to use an [architecture-specific organization](https://github.com/docker-library/official-images#architectures-other-than-amd64) like [`arm64v8/openjdk`](https://hub.docker.com/r/arm64v8/openjdk).
> 
> Turns out this doesn't really work and you may need to use a specific digest: #2148

No more using a specific digest. See https://github.com/GoogleContainerTools/jib/issues/2148#issuecomment-672129017
