### ISSUE TITLE
Jib should read the Docker environment variables and daemon.json

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1551]
Jib should seed itself with Docker configuration when available.

## Environment

The docker-provided [`inspectDockerImage` tool supports the following environment variables](https://docs.docker.com/docker-hub/publish/certify-images/):
  - `DOCKER_REGISTRY_AUTH_ENDPOINT`, defaults to `https://registry-1.docker.io`
  - `DOCKER_REGISTRY_API_ENDPOINT`, defaults to `https://auth.docker.io`

## `daemon.json`

The Docker `daemon.json` file configures:
  - [`insecure-registries`](https://docs.docker.com/registry/insecure/) a set of registries allowed to be HTTP-only
  - [`registry-mirrors`](
https://docs.docker.com/registry/recipes/#configure-the-docker-daemon): a set of mirrors to consult, sometimes used to reference country-level mirrors like [Docker's China Mirror](https://docs.docker.com/registry/recipes/#use-case-the-china-registry-mirror).

The daemon.json file lives at:
  - `/etc/docker/daemon.json` [on Linux](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file)
  - `%ProgramData%\docker\config\daemon.json` [on Windows](https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file)
  - `~/.docker/daemon.json` on macOS (not documented, but it's there)

**Comment by Eveneko** [comment]
@briandealwis 
I look for the milestones [v2.3.0](https://github.com/GoogleContainerTools/jib/milestone/46) and find it. 
Is the issue still valid? Or can you recommend an entry-level issue please? 🙏

**Comment by chanseokoh** [comment]
@Eveneko how about #2450 starting with Maven first? I think it's not difficult to fix it. For a non-WAR project, we identify project dependencies in [`MavenProjectProperties.classifyDependencies()`](addProjectDependencies) and put them into the project dependency layer by calling [`javaContainerBuilder.addProjectDependencies()`](https://github.com/GoogleContainerTools/jib/blob/v2.2.0-maven/jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java#L281-L282). However, for a WAR project, we go through [`JavaContainerBuilderHelper.fromExplodedWar()`](https://github.com/GoogleContainerTools/jib/blob/v2.2.0-maven/jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java#L244), and the helper method doesn't call [`addProjectDependencies()`](https://github.com/GoogleContainerTools/jib/blob/v2.2.0-maven/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JavaContainerBuilderHelper.java#L124-L133). I think we can match project dependencies by checking the filename of the dependency JARs in `webInfLib`.

**Comment by PavelGloba** [comment]
Since dockerhub introduced the pull limits, [this](https://github.com/GoogleContainerTools/jib/issues/1396) closed issue is now relevant.
It should be covered by reading daemon.json, but the milestone for it is constantly changing. It would be great if registry-mirror feature could be prioritized.

**Comment by chanseokoh** [comment]
@PavelGloba as mentioned in https://github.com/GoogleContainerTools/jib/issues/1396#issuecomment-452794530, you can simply point your base image to your registry mirror. Hence we don't see `registry-mirrors` as a high priority feature but basically something cool to have. Mind to explain to us why you'd like to have Jib follow the same workflow that the Docker daemon goes through regarding `registry-mirrors`?

**Comment by PavelGloba** [comment]
@chanseokoh Well, the reason is the same as why registry-mirrors exists in daemon.json
You can set it once in one place instead of pointing every image that you use to your mirror. That's not an issue if you have one project with one base image, but on a large scale it's becoming a problem.
Also, you can set up multiple mirrors there for fail over.

**Comment by chanseokoh** [comment]
Reopened #1396 about the `registry-mirror` support.

**Comment by chanseokoh** [comment]
@PavelGloba to better support the users hitting the Docker Hub rate limiting, we implemented the registry mirror feature, which is now live with the Jib 2.8.0 release. Check out this [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-hitting-docker-hub-rate-limits-how-can-i-configure-registry-mirrors) to learn how to configure it.

**Comment by mpeddada1** [comment]
Closing issue as `registry-mirror` support is now available in the plugins and Jib CLI (see [README](https://github.com/GoogleContainerTools/jib/tree/master/jib-cli#global-jib-configuration)).
