### ISSUE TITLE
Add configuration option for filename used by buildTar goal of maven plugin

### ISSUE THREAD

**Issue by jrivard** [GoogleContainerTools/jib#1561]
The current (as of 1.0.2) maven plugin has the very useful goal of buildTar which creates a docker tar image named "jib-maven.tar".  It would be very convenient for their to be a configuration option to control the filename for situations when the version or other data needs to be placed into the filename.

Issue #1282 suggests using a separate plugin to accomplish this, but this is awkward at best.  So in this issue I'm requesting specifically that an option be added to allow setting the filename directly by the jib-maven-plugin.

**Comment by blagerweij** [comment]
I would like the same feature for the Gradle plugin!

**Comment by chanseokoh** [comment]
@hoppermann @codeseedr FYI, we are actively working on this based on #2024.

**Comment by TadCordle** [comment]
@jrivard @tishun @oers @codeseedr @blagerweij We've released 1.7.0, which adds a `jib.outputPaths` (gradle) / `<outputPaths>` (maven) configuration block, which lets you specify the `tar`, `digest`, and `imageId` file paths.
