### ISSUE TITLE
Support referencing base images from a manifest list

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1567]
Follow-on to #1547 (and #1360), users should be able to identify a platform for base image from a manifest list.  [Manifest lists](https://docs.docker.com/registry/spec/manifest-v2-2/#manifest-list) are a mechanism for aggregating and serving platform-specific images from a registry.  The list specifies manifests with a set of annotations for `os`, `architecture`, `os.version`, `os.features`, `variant` (cpu), and `features` (cpu).

There's [a nice article describing use of manifest lists](https://medium.com/@mauridb/docker-multi-architecture-images-365a44c26be6).  [The Docker CLI support an experimental `--platform` argument](https://docs.docker.com/engine/reference/commandline/build/) for specifying os/arch/variant combinations.

A related question is support for creating and pushing manifest lists — including perhaps being able to reference images built by jib within the reactor.

- [X] when fixing this bug, remember to ~~remove~~/update the [FAQ entry](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image)

**Comment by chanseokoh** [comment]
There's something I am still not getting it. For example, `openjdk:latest` or `openjdk:11` seems like a manifest list, and we know Jib has been working well. But #1360 suggests, perhaps when reference through a digest, using a manifest list doesn't work. Hence the questions to clear:

1. Is it certain that `openjdk:11` is a manifest list? (Probably.) If so, how has Jib been able to cope with a manifest list? Or, is the registry that returns amd/linux by default in this situation?
1. But pulling a manifest list by a digest doesn't work. Is it the use of a digest that makes this difference? That is, unlike using a tag, a registry doesn't assume amd/linux by default?

**Comment by briandealwis** [comment]
Jib doesn't use manifest lists: to do so requires that we request `application/vnd.docker.distribution.manifest.list.v2`, but [we don't](https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/registry/ManifestPuller.java#L73).  A manifest list is just a map of platforms to a sha1, which is why referencing a specific digest works.

`openjdk` does provide a manifest list:
```sh
$ docker manifest inspect openjdk
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2208,
         "digest": "sha256:08620da8ca7a66f433de9bf14bdcdd390292436f049a7a407a49eabad67d0827",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2207,
         "digest": "sha256:c5830875c4e5341dbc70996f33a58f7eed38f9d68d084c2ca183326fd14d14a7",
         "platform": {
            "architecture": "arm",
            "os": "linux",
            "variant": "v5"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 2207,
         "digest": "sha256:79a149aef2e344ad38924e0999442a62ed93f8cab9eb35c39ae4414899bfccd9",
         "platform": {
...

# Inspect manifest for ARM image
$ docker manifest inspect openjdk@sha256:c5830875c4e5341dbc70996f33a58f7eed38f9d68d084c2ca183326fd14d14a7
{
	"schemaVersion": 2,
	"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
	"config": {
		"mediaType": "application/vnd.docker.container.image.v1+json",
		"size": 5597,
		"digest": "sha256:ae097c632fbe620b26d0df6fd32a831d98e90666f3a88feb69ba8011cd235928"
	},
```

And I can confirm that building against `openjdk@sha256:c5830875c4e5341dbc70996f33a58f7eed38f9d68d084c2ca183326fd14d14a7` succeeds and is `arm/linux`.

**Comment by chanseokoh** [comment]
Based on this [comment](https://github.com/docker/distribution/blob/v2.7.1/registry/handlers/manifests.go#L179-L181), I guess it is the intention that a digest for a manifest list (e.g., the reference in #1360) won't work as it does when using a tag (e.g., `openjdk:latest`).

**Comment by briandealwis** [comment]
Bumping to P1 as it's actually not that easy to find the right digest for a manifest-list.

**Comment by briandealwis** [comment]
NB: OCI supports a similar concept called an [_image index_](https://github.com/opencontainers/image-spec/blob/28462ef6944123de00cf27e812309cbf5d82da71/image-index.md).

**Comment by loosebazooka** [comment]
Okay started on this: tracking progress here:
- [ ] add support for v2.2 manifest list
- [ ] and more!

**Comment by chanseokoh** [comment]
Newer Jib versions now have an _incubating feature_ to select a base image matching a user-configured platform from a manifest list. For usage, refer to the FAQ ["How do I specify a platform in the manifest list (or OCI index) of a base image?"](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image).

As an incubating feature, there are limitations. For example, pushing a manifest list (in other words, selecting multiple base images) is not supported and being tracked by #2523.

Closing.
