### ISSUE TITLE
can the jvmFlags support environment variables?

### ISSUE THREAD

**Issue by onethin** [GoogleContainerTools/jib#1592]
just like <jvmFlag>${xxxxx}</jvmFlag>
or add a new config like <javaOpts>%{JAVA_OPTS}</javaOpts>
so that we can set the jvm parameters in running time，not  in image

**Comment by onethin** [comment]
sorry
add a new config like  ${JAVA_OPTS}

**Comment by chanseokoh** [comment]
Hi @onethin,

Does this [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#jvm-flags) help in your case?

**Comment by onethin** [comment]
@chanseokoh it does,thanks
