### ISSUE TITLE
Spring Boot link is broken in Example section

### ISSUE THREAD

**Issue by isaacasensio** [GoogleContainerTools/jib#1598]
**Description of the issue**:
Spring-boot example in 

**Expected behavior**:

**Steps to reproduce**: 
- Go to project main page.
- Go to Examples section.
- Click on Spring Boot link

**Environment**: 
N/A

**Log output**: 

Github 404 page

**Additional Information**: 
N/A

**Comment by TadCordle** [comment]
Whoops, forgot to update that readme. Thanks for pointing this out so quickly.

**Comment by isaacasensio** [comment]
@TadCordle I pushed a PR with the change just in case you want to merge it.

**Comment by TadCordle** [comment]
Fixed by #1599
