### ISSUE TITLE
Allow configuring container creation timestamp in plugins

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1609]
instead of just whether or not to use current timestamp. We could change the `useCurrentTimestamp` parameter to take either a boolean, or an integer number of milliseconds since epoch, or rename the parameter to just `timestamp` and take a string to determine whether to use current timestamp or a specific timestamp.

**Comment by ST-DDT** [comment]
I would like to set the docker image timestamp to the time of the git commit that was used to build the underlying java classes. IIRC the docker image list has a created date, that shows the age of the image. Falsifying this image date results in a loss of useful information especially if "old images" should be garbage collected.

For plugins it might be useful to provide a timestamp + a format string to allow optimal flexibility when choosing the timestamp source.

**Comment by chanseokoh** [comment]
1.5.0 released with the feature to configure the container creation time. See the `jib.container.creationTime` doc for [Maven](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage)/[Gradle](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#extended-usage).

@ST-DDT
