### ISSUE TITLE
Is there any way to write docker-compose within build script

### ISSUE THREAD

**Issue by saurabh4studies** [GoogleContainerTools/jib#1615]
**Description of the issue**:

I need to have running MSSQL DB, Elasticsearch in order to make my application fully functional. So far i am able to create docker image as per below gradle script. 

Is there any way to write docker-compose equivalent in build.gradle ?

**Environment**: 
OS: Window 7
JDK: Open JDK 8
Gradle: 5.2.1

**`jib-gradle-plugin` Configuration**: 
```groovy
plugins {
    id 'com.google.cloud.tools.jib' version '1.0.2'
    id 'war'
}

jib {
    from {
        image = 'tomcat:8.5'
    }
    container {
        appRoot = '/usr/local/tomcat/webapps/eVA'
        ports = ['8080/tcp']
    }
    to {
        image = 'ecw-assistant:tomcat8.5'
    }
}

tasks.build.dependsOn { tasks.jibDockerBuild }
```

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @saurabh4studies,

The Jib Gradle plugin is intended to containerize a single Java application (a Gradle project built by `build.gradle`), so if you were to build, say, three Java applications, normally you wound create three Gradle projects for each application and its image.

That said, the plugin is specialized in containerizing Java applications. It isn't a general tool to containerize arbitrary images. Although you might be able to tweak Jib configurations to containerize arbitrary contents and set various metadata (for example, you create an empty Gradle project for MSSQL, put every file you want to have in the final MSSQL image under `src/main/jib`,  set custom entrypoint using `<entrypoint>`), I don't feel using Jib is the right way to containerize images like MSSQL or Elasticsearch. I think you should be preparing these non-Java images in other ways. You could use `Dockerfile` for these, but you could also try [jib-core](https://github.com/GoogleContainerTools/jib/tree/master/jib-core), our Java library . See https://github.com/GoogleContainerTools/jib/issues/1452#issuecomment-458588470 and https://github.com/GoogleContainerTools/jib/issues/1452#issuecomment-458598641 if you are interested.

Also note that `docker-compose` (whose primary use case is for development and testing AFAICT) is just one type of many orthogonal technologies to run multiple images in orchestration. There are other ways you can run multiple images, and Jib doesn't intend venture into this another massive area of container orchestration.

**Comment by chanseokoh** [comment]
Closing per above.

**Comment by guai** [comment]
One may want to build the same app on top of several base images. Dev/prod e.g.
