### ISSUE TITLE
RegistryAuthenticatorTest.testUserAgent is flaky

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1621]
See https://github.com/GoogleContainerTools/jib/pull/1620#issuecomment-482668179

The test was added in #1610. I'll get to this not too late, but I suggest to add `@Ignore` for now.

**Comment by loosebazooka** [comment]
Should we ignore for now but still mandate we fix as part of the next milestone?

**Comment by chanseokoh** [comment]
Sounds good.

**Comment by loosebazooka** [comment]
I'll put in the ignore, but leave it up to you to fix :smile:

**Comment by TadCordle** [comment]
This appears to fail on ubuntu and macos sometimes as well.
