### ISSUE TITLE
Problems build images for ARM8

### ISSUE THREAD

**Issue by dementiacs** [GoogleContainerTools/jib#1628]
When building an image on an ARM8/AARCH64 platform using

./gradlew jibDockerBuild --image ...

the image seems to build ok but attempting to run it then I get the error...

standard_init_linux.go:207: exec user process caused "exec format error"

On inspection (docker image inspect) I see that the architecture is "amd64" when it should be "arm64".

Is there any way to force it to create an arm64 architecture image?

I see there is an issue reported about using the base image architecture and that it claims to be fixed (and merged) but I'm not seeing it and I'm using the latest release at this time (1.0.2).

**Comment by chanseokoh** [comment]
Hi @dementiacs,

#1547 is not in 1.0.2. We are going to make a 1.1.0 lease this week, so stay tuned. 1.1.0 will inherit the OS/Arch specified in the base image.

**Comment by chanseokoh** [comment]
We will update here once 1.1.0 is released.

**Comment by briandealwis** [comment]
@dementiacs 1.1.0 has been released. Note that to use arch-specific Official Docker Hub Images, you will need to use [an arch-specific organization](https://github.com/docker-library/official-images#architectures-other-than-amd64) like `arm64v8/openjdk`.

If you're still having problems, please describe the image that you're trying to use.

**Comment by chanseokoh** [comment]
> Note that to use arch-specific Official Docker Hub Images, you will need to use [an arch-specific organization](https://github.com/docker-library/official-images#architectures-other-than-amd64) like `arm64v8/openjdk`.

This doesn't seem to really work, and you may need to use a specific digest: #2148

**Comment by chanseokoh** [comment]
> > Note that to use arch-specific Official Docker Hub Images, you will need to use [an arch-specific organization](https://github.com/docker-library/official-images#architectures-other-than-amd64) like `arm64v8/openjdk`.
> 
> This doesn't seem to really work, and you may need to use a specific digest: #2148

No need to use a specific digest. See https://github.com/GoogleContainerTools/jib/issues/2148#issuecomment-672129017
