### ISSUE TITLE
Unique out of order directory entries should be respected

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#1650]
```java
ReproducibleLayerBuilder(
       LayerEntry("a/b.txt"),
       LayerEntry("a", someCustomPermissions)
)
```
should produce a layer with custom permissions on `a`, current behavior doesn't do this, since `a` is prepopulated into the entries by `a/b.txt`

**Comment by chanseokoh** [comment]
#1270 is slightly related in that #1270 is due to the current solution of adding all the parent directories.

**Comment by loosebazooka** [comment]
I think this can just be considered a duplicate of #1270
