### ISSUE TITLE
while deployment in k8s always failed error as : failed to open log file "/var/log/pods/105c52b6-6396-11e9-b608-00163e10ea14/bs/0.log"

### ISSUE THREAD

**Issue by ZhengKexue** [GoogleContainerTools/jib#1654]
**Description of the issue**:
failed to open log file "/var/log/pods/105c52b6-6396-11e9-b608-00163e10ea14/bs/0.log": open /var/log/pods/105c52b6-6396-11e9-b608-00163e10ea14/bs/0.log: no such file or directory

**Expected behavior**:
Pod start success 
**Steps to reproduce**: 
1.  kubectl run bs --image=xxx --port=8080 --restart=Never --namespace=test
2.  kubectl get pods --namespace=test
     then find the pod can't start success as below:
     bs                                            0/1       ContainerCannotRun   0          12s
3. kubectl logs xxxxx --namespace=test
   check error logs as below: 
  failed to open log file "/var/log/pods/105c52b6-6396-11e9-b608-00163e10ea14/bs/0.log": open /var/log/pods/105c52b6-6396-11e9-b608-00163e10ea14/bs/0.log: no such file or directory

**Environment**: 
gradle 4.6
Mac OS 10.13.3

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
 plugins {
	id 'com.google.cloud.tools.jib' version '1.1.1'
}
jib{
	container{
		mainClass = "com.test.BackendApplication"
	}
}
```

**Log output**: 

**Additional Information**: 
 build command as below ,the application is normal springboot application . build already success and image already push to remoter repository.

```java
gradle jib    -Djib.from.image=openjdk:alpine     -Djib.to.image=xxx     -Djib.to.auth.username=xxx    -Djib.to.auth.password=xxx     -Djib.to.environment=LOCAL_ENV="test"     -Djib.to.ports=8080     -Djib.container.useCurrentTimestamp=true     -Djib.container.workingDirectory=/home/admin     -Djib.container.user=admin
```

**Comment by ZhengKexue** [comment]
> **Description of the issue**:
> failed to open log file "/var/log/pods/105c52b6-6396-11e9-b608-00163e10ea14/bs/0.log": open /var/log/pods/105c52b6-6396-11e9-b608-00163e10ea14/bs/0.log: no such file or directory
> 
> **Expected behavior**:
> Pod start success
> **Steps to reproduce**:
> 
> 1. kubectl run bs --image=xxx --port=8080 --restart=Never --namespace=test
> 2. kubectl get pods --namespace=test
>    then find the pod can't start success as below:
>    bs                                            0/1       ContainerCannotRun   0          12s
> 3. kubectl logs xxxxx --namespace=test
>    check error logs as below:
>    failed to open log file "/var/log/pods/105c52b6-6396-11e9-b608-00163e10ea14/bs/0.log": open /var/log/pods/105c52b6-6396-11e9-b608-00163e10ea14/bs/0.log: no such file or directory
> 
> **Environment**: 
> gradle 4.6
> Mac OS 10.13.3
> 
> **`jib-maven-plugin` Configuration**:
> 
> ```
> PASTE YOUR pom.xml CONFIGURATION HERE
> ```
> 
> **`jib-gradle-plugin` Configuration**:
> 
> ```groovy
>  plugins {
> 	id 'com.google.cloud.tools.jib' version '1.1.1'
> }
> jib{
> 	container{
> 		mainClass = "com.test.BackendApplication"
> 	}
> }
> ```
> 
> **Log output**:
> 
> **Additional Information**: 
> build command as below ,the application is normal springboot application . build already success and image already push to remoter repository.
> 
> ```java
> gradle jib    -Djib.from.image=openjdk:alpine     -Djib.to.image=xxx     -Djib.to.auth.username=xxx    -Djib.to.auth.password=xxx     -Djib.to.environment=LOCAL_ENV="test"     -Djib.to.ports=8080     -Djib.container.useCurrentTimestamp=true     -Djib.container.workingDirectory=/home/admin     -Djib.container.user=admin
> ```

**Comment by loosebazooka** [comment]
It's hard for us to reproduce this issue. Can you confirm whether or not you see the same problem when building your application with docker?

Maybe it has something to do with this `admin` user.
