### ISSUE TITLE
FilesMojoV2 should resolve and use absolute paths for extra directories

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1660]
`FilesMojo` resolves/prints the absolute paths of the extra directories, but `FilesMojoV2` does not. Is this intended?

**Comment by chanseokoh** [comment]
Looking at the docs and samples, the plugin usage of `<extraDirectories>` is to set absolute paths, so I think in practice this shouldn't matter.

I'd say we remove `File::getAbsoluteFile()` from V1 to be consistent with V2 and `RawConfiguration`s, and add validation somewhere that the paths should end up absolute.

**Comment by TadCordle** [comment]
Good point. I also checked `FilesTask` and `FilesTaskV2`, and it seems neither of those uses explicit absolute paths. `FilesMojo` is the odd one out at the moment.

**Comment by chanseokoh** [comment]
Hmm... actually, I tested specifying a non-absolute path (such as `src/main/java/example`) for normal Jib build (not the skaffold-files goal) in both Maven and Gradle, and they all work.

**Comment by chanseokoh** [comment]
Project-relative path works with the properties too. Since they have been working fine, perhaps we should make `FileMojo` and `FileMojoV2` handle project-relative paths correctly.
