### ISSUE TITLE
Unify build tasks by supporting Skopeo URL schemes

### ISSUE THREAD

**Issue by hendrikhalkow** [GoogleContainerTools/jib#1664]
I'd like to propose an alternative approach on how to specify what the jib-gradle-plugin and the jib-maven-plugin output during build. Instead of having three different tasks, `jib`, `jibDockerBuild` and `jibBuildTar`, Jib could use the URL scheme that is currently being used at [Skopeo](https://github.com/containers/skopeo), [Podman](https://github.com/containers/libpod/blob/master/docs/podman-pull.1.md) and [Buildah](https://github.com/containers/buildah/blob/master/docs/buildah-push.md).

Instead of using different tasks, the build target would be specified within the `build.gradle` or `pom.xml` file. Builds would be always executed via `gradle jib` or the corresponding Maven command.

To build to a remote registry, you would use `jib.to.image="docker://docker.io/foo/bar:latest"`, for a Docker archive it would be like `jib.to.image="docker-archive:myimage.tar"`, for Docker Daemon builds it would be `jib.to.image="docker-daemon:foo/bar:latest"`.

To specify the another target, you could provide the target via command line:

```zsh
gradle jib -Pjib.to.image=oci-archive:myimage.tar
```

Pro:
- Just one task instead of three
- Use the same tasks, `jib`, regardless whether you build to a registry, file or daemon
- Unification with other container-related build tools
- More flexibility – you can do things you couldn't do before. How about `jib.from.image="oci-archive:baseimage.tar"`?

Con:
- Would cause a breaking change as this is incompatible with the current scheme
- Addressing isn't [standardized](https://github.com/opencontainers) yet

What do you think about this?

**Comment by sluongng** [comment]
This is an awesome proposal as I too am looking at options on how to make JIB works with a podman (no docker) machine locally (no registry)

Hope it gets more attention.

**Comment by lfarkas** [comment]
+1

**Comment by OneCricketeer** [comment]
> Addressing isn't standardized yet

https://github.com/opencontainers/image-spec

**Comment by JoeWang1127** [comment]
close as not planned
