### ISSUE TITLE
Documentation for the image to use same name/ ip address as the hostname/ip address

### ISSUE THREAD

**Issue by ucancprem** [GoogleContainerTools/jib#1672]
**Description of the issue**:
Is there documentation for creating the image to use the same hostname/ip address as the the instance it is running on?
Is this possible with JIB?

I'm looking to do this with `jib-gradle-plugin`

**Comment by briandealwis** [comment]
Hi @ucancprem.  That's not something that is set in the container, but is instead configured by the container runtime.  For example, you can tell Docker to expose a container port with a `-p` argument.
