### ISSUE TITLE
Skip downloading and caching base image layers (BLOb) if target registry already has them

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1673]
For registry push (`jib:build`), I wonder if we can entirely skip downloading the base image (layer tarballs) by checking ahead if the target registry has all the layers. I think in most cases, the target registry will have the base image. Even if it doesn't, it will have them available as soon as Jib or anyone pushes the base image or any images based on it. (I assume a layer in a registry is shared registry-wide across all repositories/users.) Java base images are often very large, and I think this will particularly helpful on CI/CD environment.

Similarly, we may also be able to skip downloading the base image for Docker daemon push, if we could check if the daemon has some layer, but I think this is less valuable.

**Comment by loosebazooka** [comment]
We gotta be careful when implementing this to make sure this message still makes sense: https://github.com/GoogleContainerTools/jib/pull/1687/files#diff-455581b85be6f9470c42604cc1dcdb3dR89

**Comment by hybnew** [comment]
According to this issue title, does `jib` in fact always download the base image from registry?
But when i run jib demo, it happens that
 ```
[INFO]  TIMED   Pulling base image manifest : 14578.0 ms
[INFO]  TIMING  Setting up base image caching
[INFO]  TIMING  Pulling base image layer sha256:221d80d00ae9675aad24913aacbadfac1ce8b7084f9765a6c0813486082c5c69
[INFO]  TIMING  Pulling base image layer sha256:4250b3117dca5e14edc32ebf1366cd54e4cda91f17610b76c504a86917ff8b95
[INFO]  TIMED   Pulling base image layer sha256:221d80d00ae9675aad24913aacbadfac1ce8b7084f9765a6c0813486082c5c69 : 1.0 ms
[INFO]  TIMED   Pulling base image layer sha256:4250b3117dca5e14edc32ebf1366cd54e4cda91f17610b76c504a86917ff8b95 : 2.0 ms
[INFO]  TIMING  Pulling base image layer sha256:c5e155d5a1d130a7f8a3e24cee0d9e1349bff13f90ec6a941478e558fde53c14
[INFO]  TIMING  Pulling base image layer sha256:3b7ca19181b24b87e24423c01b490633bc1e47d2fcdc1987bf2e37949d6789b5
[INFO]  TIMING  Pulling base image layer sha256:acd9a038f588d8e2b2e3f146ed7adb7b6f8e373516efc24c78c8208f8812ad14
[INFO]  TIMED   Pulling base image layer sha256:c5e155d5a1d130a7f8a3e24cee0d9e1349bff13f90ec6a941478e558fde53c14 : 0.0 ms
[INFO]  TIMED   Pulling base image layer sha256:acd9a038f588d8e2b2e3f146ed7adb7b6f8e373516efc24c78c8208f8812ad14 : 0.0 ms
[INFO]  TIMING  Pulling base image layer sha256:2aa7bd7991994877c85197911e3de5a0f6eecce76c0684b9d5eaf095aba2671a
[INFO]  TIMED   Setting up base image caching : 4.0 ms
[INFO]  TIMED   Pulling base image layer sha256:3b7ca19181b24b87e24423c01b490633bc1e47d2fcdc1987bf2e37949d6789b5 : 0.0 ms
[INFO]  TIMED   Pulling base image layer sha256:2aa7bd7991994877c85197911e3de5a0f6eecce76c0684b9d5eaf095aba2671a : 0.0 ms
[INFO]  TIMING  Pulling base image layer sha256:47ce9f19f5673fe0e0749218052da4940d0c647485f1759ad8c5d3e79b3f7cf9
[INFO]  TIMED   Pulling base image layer sha256:47ce9f19f5673fe0e0749218052da4940d0c647485f1759ad8c5d3e79b3f7cf9 : 0.0 ms
[INFO]  TIMING  Building container configuration
```

so i just want to know does `jib` caching base image or not ?
thanks  advance.

**Comment by chanseokoh** [comment]
@hybnew Jib does cache base images. This issue is about potentially skipping downloading the base image entirely if Jib can be certain that the destination repository/registry already has the base image.

**Comment by hybnew** [comment]
Ok then, I got what you say.

well i have another questions that i want to figure out now if you'd like to .  I did test the time elapse when build my project with `jib` and with `docker`, it  turns out that `docker build` is much faster than `jib` ,  does this what `jib` actually perform or it's  something  my  environment disturb?

the second, as above you mentioned, `jib` is capable of building image without base image locally ,OMG, is that true?

**Comment by chanseokoh** [comment]
> it turns out that docker build is much faster than jib , 

```
[INFO]  TIMED   Pulling base image manifest : 14578.0 ms
```

Looking at your timed log, this seems like a network issue in your environment. It should usually take a fraction of a second to download the base image manifest. I bet the Docker build does not initiate network calls.

However, when pushing your built image to the local Docker daemon (that is, when doing `jib:dockerBuild`), you can make Jib not download the base image manifest but instead let it use the cached manifest by giving the `--offline` flag in Maven/Gradle, as long as you have made Jib download and cache the base image manifest (in addition to the base image layers) once online.

> the second, as above you mentioned, jib is capable of building image without base image locally ,OMG, is that true?

This is not yet supported. This issue is about adding the support in the future and hence still open.

**Comment by hybnew** [comment]
>  you can make Jib not download the base image manifest but instead let it use the cached manifest by giving the --offline flag in Maven/Gradle

finally get what `--offline` do. it would be nice if  the sentence be added to the `Quick Start` doc.

> This is not yet supported

of course ,what a nice feature!

**Comment by chanseokoh** [comment]
1.5.0 released with the feature to skip downloading base images that exist in a target registry. This will particularly helpful on CI/CD environment, where people don't persist the Jib base image cache.

@hybnew
