### ISSUE TITLE
BaseImage configuration propagation only works with Manifest SchemaVersion 2

### ISSUE THREAD

**Issue by menostos** [GoogleContainerTools/jib#1679]
**Description of the issue**:
I was wondering why my BaseImage was not propagating any Environment Variables into my built image. Turns out, that configuration propagation only works with Manifest Schema 2 Versions. I can reproduce this behaviour with different registries serving different Schema Versions and the same pom-configuration.

**Expected behavior**:
I would have expected, that this should not be related to the schema version. I'm not sure if this should be fixed, but it should be documented or log a warning during build, that the base image configuration will be lost.

**Steps to reproduce**:
Using a docker registry which serves manifest schema v1.

**Comment by chanseokoh** [comment]
Thanks for the feedback. We've already fixed this (#1641), and the next Jib release will work as expected. We plan to release it soon.

**Comment by TadCordle** [comment]
@menostos v1.2.0 has been released with this fix!
