### ISSUE TITLE
Remove skaffold-files v1 task/goal

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1681]
We should keep these around for a while in case people use newer versions of Jib with older versions of Skaffold, but after a certain point we should remove support for the v1 goals.

**Comment by loosebazooka** [comment]
Yeah I would mark them deprecated in the code and we can remove them in v2.0.0

**Comment by loosebazooka** [comment]
We can't deprecate these with messaging because it will interfere with their functioning. We'll just have to remove them from 2.0.0.
