### ISSUE TITLE
Have cross-repo mount automatically put source repository for base image in same registry.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#169]
If the base image and the target image are both in the same registry, we can add a `&from=` when pushing a blob to use the base image repository to find the blob to mount.

We might also want to rearrange the build steps to:

1) Pull base image manifest
2) Begin upload of base image layers (get upload location) with mount, if on same registry.
3) Pull base image layers and finish upload if not on same registry, or mount failed.

**Comment by coollog** [comment]
Fixed via #731

**Comment by briandealwis** [comment]
`mount`/`from` broke pushes to Docker Hub as we need to authorize against both the base and target images (#808).  I believe [we can do this by](
https://github.com/GoogleContainerTools/jib/issues/808#issuecomment-412190216):
> Aha, I think we could just adjust `AuthenticatePushStep` to initiate `RegistryAuthenticator` with both the base and target repositories if on the same registry. This requires cascading support for multiple repositories throughout `RegistryAuthenticator`.

**Comment by chanseokoh** [comment]
Closed #819. We can revisit it for reference later if needed.
