### ISSUE TITLE
Add exposed port automatically

### ISSUE THREAD

**Issue by ChenWenBrian** [GoogleContainerTools/jib#1706]
**Description of the issue**: jib won't expose server.port in docker manifest file automatically, unless we write it in maven/gradle configuration file.  If i change server.port in my application.properties file, I need to update my maven POM file too. I don't want to maintain a server port in both places.  

**Expected behavior**: Jib is smart, it can find the MainClass as the ENTRYPOINT, I hope jib can be smart inferences server.port and expose it too.
 
**Steps to reproduce**: 
If I don't write container.ports.port to 8888 in POM file,  there will be no exposed port in docker image manifest file. 
Sometimes even if i set it in POM file, it's still missing in the manifest file.

**Environment**: 
Maven
**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>jib-maven-plugin</artifactId>
    <version>1.1.2</version>
    <configuration>
        <from>
            <image>openjdk:8-jre-alpine</image>
        </from>
        <to>
            <image>${docker.image.prefix}/${project.artifactId}</image>
        </to>
    </configuration>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>dockerBuild</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

**docker manifest config part without ExposedPorts**: 
```json
{
"Config": {
        "Hostname": "",
        "Domainname": "",
        "User": "",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin",
            "JAVA_HOME=/usr/lib/jvm/java-1.8-openjdk/jre",
            "JAVA_VERSION=8u212",
            "JAVA_ALPINE_VERSION=8.212.04-r0",
            "LANG=C.UTF-8"
        ],
        "Cmd": null,
        "Image": "",
        "Volumes": {},
        "WorkingDir": "",
        "Entrypoint": [
            "java",
            "-cp",
            "/app/resources:/app/classes:/app/libs/*",
            "com.example.helloservice.HelloServiceApplication"
        ],
        "OnBuild": null,
        "Labels": {}
    }
}
```
this part is what i want to be included in **Config** or  **ContainerConfig** section
```json
"ExposedPorts": {
            "8888/tcp": {}
        }
```

**Comment by briandealwis** [comment]
I'm guessing you're using Spring Boot?  Maybe we can provide a way to support framework-specific configurator plugins.

**Comment by loosebazooka** [comment]
We're not really in the business of doing framework specific integrations directly in Jib. However it looks like you can configure this yourself using https://www.mojohaus.org/properties-maven-plugin/.

Let maven initialize the properties from your application.properties into the build, you can then inject them into your jib config in your pom.xml? So if it changes in one place, it'll change in all places?

**Comment by ChenWenBrian** [comment]
thanks guys, 

> I'm guessing you're using Spring Boot? Maybe we can provide a way to support framework-specific configurator plugins.

yes, we're using spring boot

**Comment by ChenWenBrian** [comment]
> We're not really in the business of doing framework specific integrations directly in Jib. However it looks like you can configure this yourself using https://www.mojohaus.org/properties-maven-plugin/.
> 
> Let maven initialize the properties from your application.properties into the build, you can then inject them into your jib config in your pom.xml? So if it changes in one place, it'll change in all places?
> 
> Here's a possible example: https://stackoverflow.com/a/1231594

thanks for your suggestion. however, spring boot has a default port(8080) setting if server port is not specified in application.properies. And Spring Boot also support YAML as it's configuration file.  I'm afraid
properties-maven-plugin can't cover the above two cases.

**Comment by briandealwis** [comment]
Maybe the [`yaml-properties-maven-plugin`](https://github.com/ozimov/yaml-properties-maven-plugin) might work then?

**Comment by ChenWenBrian** [comment]
thanks for your reply, but i'm afraid this plugin could not cover all of our cases.
As i explained previously, our team have 3 cases:
1. SpringBoot applications with default tomcat port, that means there's no perperties or yaml settings;
    **this case we still need to add a port setting in jib configuration.**
2. SpringBoot applications with custom tomcat port which is set in application.perperties;
    this case we can use `properties-maven-plugin`.
3. SpringBoot applications with custom tomcat port which is set in application.yaml;
    this case we can use `yaml-properties-maven-plugin`.

the first case is still not covered. and besides that, I hope if there's a solution to smart inferences server.port and expose it in docker images, not solutions case by case. 

thanks.

**Comment by loosebazooka** [comment]
It's really hard for us to infer defaults from other systems, so I doubt we will have a solution for *1*. If you know a way to pro grammatically and correctly infer this, I'd be curious to see what the solution is and see if we could incorporate it. Otherwise, you're going to have the use the configuration setting in pom.xml or explicitly configure the default in a properties/yaml file and configure the properties reader plugin.

**Comment by ChenWenBrian** [comment]
@loosebazooka thanks for your explanation. 
I'm wondering if JIB can provide a `dry-run` mode before image building, like [spring-boot-thin-launcher](https://github.com/spring-projects-experimental/spring-boot-thin-launcher). During `dry-run` mode, application will be started and some network ports would be open, then JIB can find these ports and set them as exposed ports when building image. If `dry-run` mode is not set, then everything will be the same as current release.

**Comment by linkavich14** [comment]
I am using spring boot as well and I set the port in container.ports.port to 42048 but I have never seen it in the docker manifest config. 

This is how I currently have it in my pom:

`<plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>1.3.0</version>
                <configuration>
                    <to>
                        <image>devsdt.water.rubicon.com.au:9445/${project.artifactId}:latest</image>
                    </to>
                    <allowInsecureRegistries>true</allowInsecureRegistries>
                    <container>
                        <mainClass>${app.entrypoint}</mainClass>
                        <ports>
                        	<port>42048</port>
                        </ports>
                        <args>
                          <arg>appId=${project.artifactId}</arg>
                        </args>                    
                        <jvmFlags>
                          <jvmFlag>-Drubicon.debug.file=${project.artifactId}_${project.version}</jvmFlag>
                          <jvmFlag>-Drubicon.app.home=/tmp/rubicon</jvmFlag>        
                        </jvmFlags>                            
                        <environment>
                            <WMS_HOME>/tmp/rubicon</WMS_HOME>
                        </environment>
                        <useCurrentTimestamp>true</useCurrentTimestamp>
                    </container>
                </configuration>                
            </plugin>`

The image runs fine if I used from docker compose, but I am having communication problems when I use it in AWS ECS Fargate and my front end never finds the backend even that they are running in the same task.

**Comment by chanseokoh** [comment]
@linkavich14 when I set the port (Jib 1.2.0), I see that the built image has it in the container configuration of the image.

```
$ mvn clean compile jib:dockerBuild
...
[INFO] Built image to Docker daemon as francium25/test
...
[INFO] BUILD SUCCESS
...
$ docker inspect francium25/test | grep -A 2 Port
            "ExposedPorts": {
                "42048/tcp": {}
            },
```

**Comment by ChenWenBrian** [comment]
@linkavich14 sometimes the port configuration is not working, then I cleaned the entire build environment, and it worked again. I'm afraid this is caused by building cache.

**Comment by linkavich14** [comment]
@chanseokoh @ChenWenBrian After I deleted the target folder and move the plugin from the parent, it worked and the port is displaying now thank you

**Comment by loosebazooka** [comment]
I think I'm going to close this for now. Any automatic port configuration can be handled by a new Jib Extension?
