### ISSUE TITLE
Main Class not found when it is in a sub-project.

### ISSUE THREAD

**Issue by thaneeshshanand** [GoogleContainerTools/jib#1722]
**Description of the issue**:
I have a Gradle project with a sub-project which is a Spring-boot app. JibDockerBuild works fine.  But when running the docker container it is not able to find the Main class.

**Expected behavior**:
Setting the Main class path for sub-projects should work.

**Steps to reproduce**: 
git clone git@github.com:thaneeshshanand/JibTest.git
cd JibTest
./gradlew clean build
./gradlew jibDockerBuild
docker run -p 8080:8080/tcp thaneesh/jibtest

**Environment**:
MacOS

**`jib-gradle-plugin` Configuration**:
Main Project:
```groovy
plugins {
	id 'com.google.cloud.tools.jib' version '1.2.0'
}
apply plugin: 'java'
subprojects {
	apply plugin: 'java'
	jib {
		from {
			image = 'openjdk:11'
		}
		to {
			image = 'thaneesh/jibtest'
		}
		container {
			jvmFlags = ['-Xms512m', '-Xdebug']
			mainClass = 'com.example.JibTest.JibTestApplication'
			args = []
			ports = ['8080/tcp']
		}
	}
	sourceCompatibility = '11'
	repositories {
		jcenter()
		mavenCentral()
	}
}
```
Sub-project:
```
plugins {
	id 'org.springframework.boot' version '2.1.4.RELEASE'
	id 'java'
}

apply plugin: 'io.spring.dependency-management'

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-jersey'
	implementation "org.glassfish.jersey.media:jersey-media-multipart:2.28"
}

```

**Log output**:
Container output:
```
$ docker run -p 8080:8080/tcp thaneesh/jibtest
Error: Could not find or load main class com.example.JibTest.JibTestApplication
Caused by: java.lang.ClassNotFoundException: com.example.JibTest.JibTestApplication
```

**Comment by briandealwis** [comment]
I'm not a gradle expert, but I believe your main project still needs to express a dependency on the subproject.

(Note: Jib doesn't validate that the specific main class can be found.)

**Comment by briandealwis** [comment]
More to the point, when you execute `gradlew jibDockerBuild`, it's applying jib to your top-level project, not to the subproject.  That's why you'll see a warning about no classifies something like the following:
```
$ ./gradlew --console=plain jibDockerBuild
> Task :compileJava NO-SOURCE
> Task :processResources NO-SOURCE
> Task :classes UP-TO-DATE

> Task :jibDockerBuild
No classes files were found - did you compile your project?
...
```

**Comment by loosebazooka** [comment]
A things here.
1. `gradlew jibDockerBuild` will run the task on ALL projects that have jib, but if you use a `:` to specify a project, you can run it only on the root project, `gradlew :jibDockerBuild`, and if you only want to run it on the subproject you can use, `gradlew :subproject:jibDockerBuild`
2. But what it really looks like is that you want to run it on the subproject, so why not just put all your config it the subproject's build.gradle file? That isolates the configuration to the build that is actually going to use it.
3. If for some reason you really really want to keep config in the root project, but not build from it, then disable applying the plugin at the root level
   ```
   plugins {
     id 'com.google.cloud.tools.jib' version '1.2.0' apply false
   }
   ```
   and only apply it in the project that needs it
   ```
   subprojects {
        apply plugin: 'com.google.cloud.tools.jib'
        ...
   }
   ```

**Comment by chanseokoh** [comment]
I believe the issue can be resolved with @loosebazooka's guidance. I'll close this, but feel free to re-open if you still face problems.
