### ISSUE TITLE
gradle jibDockerBuild tries to connect to registry, fails

### ISSUE THREAD

**Issue by taylorsmithgg** [GoogleContainerTools/jib#1732]
**Description of the issue**:
When attempting to run `jibDockerBuild`, jib attempts to connect to the registry, and fails if the required permissions are not set.

This is an issue for local development, as it does not make sense to attempt to connect to the registry for the local build.

**Expected behavior**:
`jibDockerBuild` should allow a local build without a requirement for the `to` repository to exist or correct permissions to exist on it.

**Steps to reproduce**: 
```
gradle jibDockerBuild
```

**Environment**: 
gradle

**`jib-gradle-plugin` Configuration**: 
```groovy
subprojects {
    jib {
        from {
            image = 'company/java10:latest'
            auth {
                username = DOCKER_USERNAME
                password = DOCKER_PASSWORD
            }
        }

        to {
            image = "registry.hub.docker.com/company/${project.name.toLowerCase()}"
            auth {
                username = DOCKER_USERNAME
                password = DOCKER_PASSWORD
            }
            tags = [project.version, gitHash()]
        }

        container {
            entrypoint = 'INHERIT'
            ports = ['8080']
            format = 'DOCKER'
        }
    }
}
```

**Log output**: 
```
15:19:02.082 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':app:jibDockerBuild'.
15:19:02.082 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build to Docker daemon failed, perhaps you should make sure your credentials for 'registry-1.docker.io' are set up correctly. See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized for help
```

**Additional Information**: 
Please note that the `from` base image is also from the registry, but works as intended.
I understand that this is necessary for pulling the `from` image.

I am simply asking why jib is attempting to contact the registry in regard to the local daemon and the `to` image.

**Comment by TadCordle** [comment]
I might be misunderstanding, but Jib needs to be able to download the base image to proceed with the build, regardless of whether or not the target is local. If the base image registry needs credentials and they aren't configured correctly, then the build will fail. I don't think this has anything to do with the configured `to` image, but maybe you can share your `build.gradle` just to be sure? (with sensitive material redacted of course)

At some point we are hoping to improve offline mode so that you can retrieve the base image from docker's cache, but I'm not sure what the timeline is on that. https://github.com/GoogleContainerTools/jib/issues/1468

**Comment by taylorsmithgg** [comment]
The base image works correctly.

I have added the `build.gradle` to the issue.

**Comment by chanseokoh** [comment]
@taylorsmithgg the latest Jib supports the offline mode (See #718), with which `jib:dockerBuild` won't connect to the base image registry provided that you ran `jib:dockerBuild` in the online mode at least once (i.e., provided that Jib has cached the base image.) Note that the Jib cache is irrelevant of the local Docker cache; Jib is designed to work without Docker installed. And as @TadCordle said, we hope to enhance Jib to utilize the Docker cache as well (#1468).

**Comment by taylorsmithgg** [comment]
I will retest with offline mode, but in this case it doesn't seem like it should be necessary to pass the offline flag for the build to work.

Furthermore, our base image is online, so passing offline would break the build as well.

It seems redundant to have to run it both in online and offline mode just for the build to succeed locally.

I am not concerned about using the docker cache.

I feel it would be ideal to not bother connecting to the registry of the `to` image at all during `jib:dockerBuild` execution since it is intended to be a build for the local machine.

**Comment by chanseokoh** [comment]
Are you sure it is the `to` configuration that is causing a problem with `jib:dockerBuild`? `jib:dockerBuild` doesn't connect to `to` at all. Setting it to an arbitrary (syntactically valid) value should work.

**Comment by taylorsmithgg** [comment]
@chanseokoh 

Yes, review the jib config and log above and the error presented.

In this case, the developer that experienced the issue was able to run `jib:dockerBuild` on one of the submodules which he had valid repo permissions on, but not the other.

**Comment by taylorsmithgg** [comment]
If you would like to recreate the scenario for testing, you just need to create two private repositories in dockerhub and allow permissions on one submodule, but not the other.

**Comment by chanseokoh** [comment]
I see. In my testing, setting `to` to something like

```xml
          <to>
            <image>there/is/no/such/repo</image>
          </to>
```

```
$ mvn -U --file=pom-test.xml jib:dockerBuild
...
[INFO] Scanning for projects...
[INFO] 
[INFO] Built image to Docker daemon as there/is/no/such/repo
[INFO] Executing tasks:
[INFO] [==============================] 100.0% complete
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

just works. I wonder if this is related to submodules in your project setup. @TadCordle could you follow up? @taylorsmithgg in the mean time, try changing your `to` to `there/is/no/such/repo` and see what's happening.

**Comment by chanseokoh** [comment]
Actually, `there/is/..` is not a good choice, since it refers to Docker Hub. Try something like `there.is.no/repo` or `not.a.host`.

**Comment by taylorsmithgg** [comment]
Swapping out the dockerhub URL works fine with any value for me.

I'll confirm with the developer that was affected and see if we can't figure out the source of the failure.

**Comment by taylorsmithgg** [comment]
Retracting this issue.

It appears the developer had a local issue.

Thank you.
