### ISSUE TITLE
no war file transferred to image

### ISSUE THREAD

**Issue by meier297** [GoogleContainerTools/jib#1734]
**Description of the issue**:

I want to build an image via `mvn package jib:dockerBuild` with \<packaging>war\</packaging> defined in pom.xml.  But it seems that war file is not copied to image. No war file can be found in '/jetty/webapps/ROOT' or via `find -name '*.war'`. The location '/jetty/webapps/ROOT' contains only two folders (META-INF, WEB-INF).

**Expected behavior**:

According the instructions there should to be a war file in the image at /jetty/webapps/ROOT
META-INF  WEB-INF

**Steps to reproduce**: 

- Create a java project with pom and a StartUp.java class like
- run `mvn package jib:dockerBuild`
- run `docker run -d -p 9080:9080 mini-server`
- run `docker exec -it <container-id> bash`
- run `find -name '*.war'`

```
@Startup
@Singleton
public class StartUpManager {

  private static final Logger LOGGER = LogManager.getLogger(StartUpManager.class);

  @PostConstruct
  public void startUp() {
    LOGGER.info("start up...");
  }
```

**Environment**: 

`mvn -v`
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: C:\DeveloperTools\apache-maven-3.6.1\bin\..
Java version: 1.8.0_212, vendor: AdoptOpenJDK, runtime: C:\Program Files\Java\jdk8u212-b03\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

`docker -v`
Docker version 18.09.2, build 6247962

**`jib-maven-plugin` Configuration**: 
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.example</groupId>
	<artifactId>mini-server</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<m2eclipse.wtp.contextRoot>/</m2eclipse.wtp.contextRoot>
		<jib-maven-plugin.version>1.2.0</jib-maven-plugin.version>
		<maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>com.google.cloud.tools</groupId>
			<artifactId>jib-maven-plugin</artifactId>
			<version>1.2.0</version>
		</dependency>
		<!-- Java EE -->
		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<version>8.0</version>
			<scope>provided</scope>
		</dependency>

		<!-- Logging -->
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-api</artifactId>
			<version>2.2</version>
		</dependency>
		<dependency>
			<groupId>org.apache.logging.log4j</groupId>
			<artifactId>log4j-core</artifactId>
			<version>2.2</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler-plugin.version}</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-war-plugin</artifactId>
				<version>3.2.2</version>
				<configuration>
					<failOnMissingWebXml>false</failOnMissingWebXml>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>${jib-maven-plugin.version}</version>
				<configuration>
					<from>
						<image>open-liberty:webProfile8</image>
					</from>
					<to>
						<image>mini-server</image>
					</to>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

**Log output**: 

[INFO] --- maven-war-plugin:3.2.2:war (default-war) @ mini-server ---
[INFO] Packaging webapp
[INFO] Assembling webapp [mini-server] in [C:\test\mini-server\target\mini-server-0.0.1-SNAPSHOT]
[INFO] Processing war project
[INFO] Copying webapp resources [C:\test\mini-server\src\main\webapp]
[INFO] Webapp assembled in [862 msecs]
[INFO] Building war: C:\test\mini-server\target\mini-server-0.0.1-SNAPSHOT.war
[INFO]
[INFO] --- jib-maven-plugin:1.1.2:dockerBuild (default-cli) @ mini-server ---
[INFO]
[INFO] Containerizing application to Docker daemon as mini-server...
[INFO] The base image requires auth. Trying again for open-liberty:webProfile8...
[INFO]
[INFO] Container entrypoint set to [/opt/ol/helpers/runtime/docker-server.sh] (inherited from base image)
[INFO] Container program arguments set to [/opt/ol/wlp/bin/server, run, defaultServer] (inherited from base image)
[INFO]
[INFO] Built image to Docker daemon as mini-server
[INFO] Executing tasks:
[INFO] [==============================] 100.0% complete
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------

**Comment by chanseokoh** [comment]
Hi @meier297,

`find -name '*.war'` will return nothing because Jib doesn't put a WAR file; instead, it places exploded contents of the WAR under `/jetty/webapps/ROOT`.

**Comment by briandealwis** [comment]
> According the instructions there should to be a war file in the image at /jetty/webapps/ROOT
META-INF WEB-INF

Could you please point out where the docs day this? We should correct it.

Basically an app server takes a war and explodes it before use.we skip that step  and explode it into place.

**Comment by meier297** [comment]
Thank you for the explanation. The documentation says 

> If the Maven project uses the war-packaging type, Jib will by default use the distroless Jetty as a base image **to deploy** the project WAR.

I thought that a WAR will will be transferred and available. But the documentation says also: 

> The WAR will be exploded into.

I misunderstood it. Sorry,it is my first time with Jib =)
