### ISSUE TITLE
how to use <from> tag

### ISSUE THREAD

**Issue by Dineshseervi** [GoogleContainerTools/jib#1740]
Getting issue when using Base Image 

error -->
`The base image requires auth. Trying again for tomcat:8.5-jre8-alpine...`

i am using <from> tag 
```
<from>
	<image>tomcat:8.5-jre8-alpine</image>
</from>
```

```
<from>
            <image>openjdk:8-jre-alpine</image>
</from>
```

For me `<to>` tag is working fine.

**Comment by briandealwis** [comment]
Hi @Dineshseervi.  You haven't provided enough information here for us to help.  Please take a look at the [Jib FAQ on Authorization](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized).

**Comment by briandealwis** [comment]
Hi @Dineshseervi.  The message from Jib isn't an error message _per se_. Although the images you're referencing are all public images on Docker Hub, Docker Hub does require that Jib first obtain an authentication token.  Jib will obtain such a token and then continue on with its image building.

I'll close this for now.  If you are encountering an error trying to fetch these images, please try obtaining a [network trace](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-examine-network-traffic) and post back here.
