### ISSUE TITLE
Allow customer filter for dependencies in JavaContainerBuilder

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#1755]
Currently dependencies are filtered by a single filtering mechanism.
```
if (dependency.name.endsWith("SNAPSHOT"))
  // it's a snapshot
else
  // it's not a snapshot
```

Consider one of the following:
1. A single dependency filter for categorizing the dependencies with a default that works like it does now. (<--- this idea is a little too bonkers for me)
    ```
    setDependencyFilter(Function<Path, String> filter)
    ```
2. Accept a layer name when adding dependenices
   ```
   addDependencies(String category, List<Path> dependencies)
   ```

This will allow more customization of the dependency layers from the client (rather than categorizing in jib-core), for doing this like maven sub-module dependencies and gradle sub-project and *changing* dependencies.

**Comment by loosebazooka** [comment]
@GoogleContainerTools/java-tools-build wdyt?

**Comment by chanseokoh** [comment]
I guess you are trying to tackle #1724. Migrate this to #1724?

According to the option 2 in #1724, looks like we will have three layers for dependencies. Then here, are you trying to open up the possibility to add any number of dependency layers through `JavaContainerBuilder`? The API in `JavaContainerBuilder` is pretty curated, and `addDependencies(String category, ...)` sounds like it actually becomes a very general `addLayer(category, ...)` to add any arbitrary layer.

**Comment by loosebazooka** [comment]
Yeah maybe it can just be add static dependencies, add changing dependencies, add project dependencies?

**Comment by briandealwis** [comment]
The nice thing about the second approach is that I can add the same dependency to multiple layers (should I have such a need).  That's impossible with the functional filter.

**Comment by chanseokoh** [comment]
> I can add the same dependency to multiple layers (should I have such a need)

For containerizing a Java application, I can't really think of a reason to add the same JAR to different "dependency" layers for different file locations and have classpath set up for the both. Perhaps they should add it to a different layer. And if they need such customization, they should probably go with the more flexible `JibContainerBuilder`?

**Comment by loosebazooka** [comment]
dup: #1724

**Comment by MaitreDede** [comment]
Hi,
I have a case where I may need a dependencies filter.
I have a project that builds a custom auth plugin for a Apache Guacamole server. All the Guacamole libs and dependencies are included in a docker image, so I have only to pur my jar into the image.

I build a self-contained jar with the shadow plugin.

My jar has Guacamole as dependencies, but since they are also inside classpath of docker image, I have to filter them (https://imperceptiblethoughts.com/shadow/configuration/filtering/) or else it does not work.

I would like if there is a way to remove some dependencies when build image...

Thanks.

**Comment by loosebazooka** [comment]
Jib only packages what's included in the final computed runtime classpath. You can use `compileOnly` so that dependencies aren't included in your runtime classpath: https://blog.gradle.org/introducing-compile-only-dependencies
