### ISSUE TITLE
Broken up-to-date checking for BuildTarTask

### ISSUE THREAD

**Issue by remmeier** [GoogleContainerTools/jib#1757]
The code defines:

```
  @InputFiles
  public FileCollection getInputFiles() {
    return GradleProjectProperties.getInputFiles(
        Preconditions.checkNotNull(jibExtension).getExtraDirectory().getPath().toFile(),
        getProject());
  }

  @OutputFile
  public String getOutputFile() {
    return getTargetPath().toString();
  }
```

whereas `getInputFiles` leads to:

`[...\build\classes\java\main, ...\build\resources\main, ...\build\extraFiles]`

but to build an image, third-party and project dependencies must be accounted for as well.

**Comment by chanseokoh** [comment]
Thanks for the bug report. We happened to notice this recently too, and I think #1754 fixes it.

**Comment by remmeier** [comment]
oh thx, i did not notice that PR

**Comment by chanseokoh** [comment]
@remmeier v1.3.0 is released with the fix.

**Comment by remmeier** [comment]
thx!
