### ISSUE TITLE
JibDockerBuild fails on download image (manifest) which is only locally available

### ISSUE THREAD

**Issue by lostiniceland** [GoogleContainerTools/jib#1761]
**Description of the issue**:
Using a from-clause with an base-image only available in the local Docker daemon cache, jib still tries to download the image from dockerhub. This, of course, fails

**Expected behavior**:
jibDockerBuild is able to use the image from the local cache and does not fail on missing metadata from dockerhub.

**Steps to reproduce**:
- create local base image
- use base-image in jib-from

**Environment**: 
OpenSuse Leap 15.1
Gradle 5.4.1

**`jib-gradle-plugin` Configuration**: Kotlin-DSL
```groovy
jib {
	from.image = "open-liberty:webProfile8-java12" // not yet available on dockerhub. locally forked
	to.image = "test/mystuff:openliberty"
	container {
		appRoot = "/opt/ol/wlp/usr/servers/defaultServer/apps/some.war"
		ports = mutableListOf("8080")
	}
	extraDirectories {
		setPaths(mutableListOf(Paths.get(libertyDockerFolder)))
	}
}
```

**Log output**: 
```
Execution failed for task ':jibDockerBuild'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Tried to pull image manifest for registry-1.docker.io/library/open-liberty:webProfile8-java12 but failed because: manifest unknown | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new
```

**Comment by loosebazooka** [comment]
This is not supported in jib right now, but we expect to support it eventually.

**Comment by chanseokoh** [comment]
Closing as a dup of #1468.

@lostiniceland you can use the offline mode (`--offline`) with `JibDockerBuild`, which will not attempt downloading the manifest of the base image. The offline mode will work provided you ran `jibDockerBuild` online at least once. However, note that this still won't make use of the Docker cache, so this may not cover your case if the image is only available in your local Docker cache.
