### ISSUE TITLE
Question about push to internal registry

### ISSUE THREAD

**Issue by raizoor** [GoogleContainerTools/jib#1772]
-->

**Description of the issue**:
Hi Team,

I have a question: when I deploy my application with Jib, the pull of my base image (on internal registry - Jfrog Artifactory) works fine and all build too, same as my container. 
But about push: have it should work automatically??
I don't have any error about that.

**Expected behavior**:
Know about push images to private registry.

**Steps to reproduce**:

Only compile API with buildDocker, with From e To tags. 

**Environment**: 
Linux mint
Maven 3.5.2
Java OpenJdk 11

**`jib-maven-plugin` Configuration**: 
`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>12</source>
                    <target>12</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>1.2.0</version>
                <configuration>
                    <allowInsecureRegistries>true</allowInsecureRegistries>
                    <to>
                        <image>hub.docker.local.net/ummagumma/teste:1.0.0</image>
                    </to>
                    <from>
                        <image>hub.docker.local.net/openjdk:12-minimal</image>
                        <auth>
                            <username>michel_moraes</username>
                            <password>xxxxxx</password>
                        </auth>
                    </from>
                </configuration>
            </plugin>`

Thanks !!

**Comment by loosebazooka** [comment]
I'm not sure I understand your question? Are you receiving an error?

Perhaps this will clarify?
- `jib:buildDocker` builds to a local docker daemon
- `jib:build` will do what I think you want - build to a registry

**Comment by raizoor** [comment]
Man,

that's it !!!!!
Thanks for your help !!

**Comment by loosebazooka** [comment]
Nice to see that jib can work for you. I will close this for now
