### ISSUE TITLE
jibs war support doesn't play well with the spring boot gradle plugin

### ISSUE THREAD

**Issue by larsgrefer** [GoogleContainerTools/jib#1786]
When the `war` and `org.springframework.boot` plugins are both applied to a gradle project, the latter disables the `war` task and registers a `bootWar` task instead.

jib should therefore use the `bootWar` task in this case.

**Comment by TadCordle** [comment]
@larsgrefer Thanks for the contribution, v1.4.0 has been released with the fix!
