### ISSUE TITLE
Allow configuring scratch base image in maven/gradle

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#1794]
Allow configuring
- maven
    ```
    <from><image>scratch</image></from>
    ```
- gradle
    ```
    jib.from.image = "scratch"
    ```

**Comment by chanseokoh** [comment]
NOTE: `scratch` starts with empty, meaning no JVM, no bare-minimum Linux system, etc., so not for practical use for Java applications.
