### ISSUE TITLE
unable to add specific image tag using jib instead of latest

### ISSUE THREAD

**Issue by murali474** [GoogleContainerTools/jib#1801]
**Description of the issue**: 
when i am using jib maven plugin to push my app to ECR repo , its adding the image in ECR as below.
`<awsid>.dkr.ecr.us-east-2.amazonaws.com/test/testrepo:latest`
But  i want to attach my application name and specific version to the image. is there any way i can achieve this. is it a bug in jib?

i am getting error while attaching the app name and version to image :
The repository with name 'test/testrepo/myapp' does not exist in the registry 

i am using below configurations in pom.xml

<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>1.3.0</version>

				<configuration>

					<from>
						<image>openjdk:8u212-b04-jre-slim</image>
					</from>
					<container>
						<mainclass>test</mainclass>

					</container>

					<to>
						<image><awsid>.dkr.ecr.us-east-2.amazonaws.com/test/testrepo</image>
						
					</to>

				</configuration>

				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

**Expected behavior**:
i want my application image should be pushed as `<awsid>.dkr.ecr.us-east-2.amazonaws.com/test/testrepo/myapp:<version>`
**Steps to reproduce**:

**Environment**: 

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @murali474,

This should work.

```
The repository with name 'test/testrepo/myapp' does not exist in the registry
```

The error message above might be true. Since you said you can push `test/testrepo:latest`, why don't you try `test/testrepo:sometag` instead of `test/testrepo/myapp:sometag`?

**Comment by murali474** [comment]
test/testrepo:sometag this way its working

**Comment by chanseokoh** [comment]
Yeah, then I think the error message is right, and I think `test/testrepo/myapp:latest` will fail too. I don't think the tag string is the issue here. Maybe you should create the new repository `test/testrepo/myapp` somehow first? (I don't know ECR much.)

**Comment by murali474** [comment]
I understood that i need to create ECR repo as namespace/app then it will work

**Comment by murali474** [comment]
> 
> 
> Yeah, then I think the error message is right, and I think `test/testrepo/myapp:latest` will fail too. I don't think the tag string is the issue here. Maybe you should create the new repository `test/testrepo/myapp` somehow first? (I don't know ECR much.)

**Comment by chanseokoh** [comment]
Ah, I see. So, in the case of `test/testrepo/myapp`, looks like ECR either
1. doesn't support the format `test/testrepo/myapp` with 2+ slashes; or
1. `test/testrepo` as a whole (i.e., including the first slash) will be considered a namespace.

I will close the issue, as this is resolved. Feel free to re-open if you have more feedback on this issue.
