### ISSUE TITLE
Is this plugin unfriendly to Windows7 support?

### ISSUE THREAD

**Issue by ZhangErling** [GoogleContainerTools/jib#1820]
**Description of the issue**:This plug-in is used in IDEA, and the creation of Docker images is very slow.My colleague's creative speed is several times faster than mine.The address of Docker image is aliyun. We work under the same project. My operating system is Windows7, while his is Windows10

**Expected behavior**:It can be done in 30 seconds

**Steps to reproduce**:Install the project using Maven

**Environment**: 
OS:Windows7
IDEA: ultimate 2019.1
    Build #IU-191.6707.61,built on April 16,2019
    JRE：11.0.2+9-b159.44amd64
    JVM:OpenJDK 64-Bit Server VM by jetBrains s.r.o
JDK:1.8.0_181
Maven:3.2.2
**`jib-maven-plugin` Configuration**: 
```xml
           <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>1.2.0</version>
                <configuration>
                    <from>
                        <image>registry.cn-beijing.aliyuncs.com/</image>
                        <auth>
                            <username>...</username>
                            <password>...</password>
                        </auth>
                    </from>
                    <to>
                        
                        <image>registry.cn-beijing.aliyuncs.com</image>
                        <auth>
                            <username>...</username>
                            <password>...</password>
                        </auth>
                    </to>
                    <allowInsecureRegistries>true</allowInsecureRegistries>
                    <container>
                        <mainClass>...</mainClass>
                        <environment>
                            <spring.profiles.active>prod</spring.profiles.active>
                        </environment>
                    </container>
                </configuration>
               
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Log output**: 
![image](https://user-images.githubusercontent.com/45256786/60592135-903b2900-9dd2-11e9-9ebf-1bd8332231c2.png)
![image](https://user-images.githubusercontent.com/45256786/60592576-82d26e80-9dd3-11e9-9e03-2abd76fb845f.png)

There was no deliberate speed limit

**Additional Information**: 
Create an image when the file is not changed. It only takes 30 seconds
![image](https://user-images.githubusercontent.com/45256786/60592693-c2995600-9dd3-11e9-8184-b838bc27a39f.png)

**Comment by chanseokoh** [comment]
Hi @ZhangErling,

If you give `mvn -X -Djib.console=plain ...`, it will output detailed timing information like below. Can you capture the output and upload here ([just drag-and-drop](https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests)) for both Windows 7 and Windows 10?

```
[DEBUG] TIMING  Pushing BLOB digest: sha256:1f593e7f826cb9f73439be33b9796cdc54d57e2127843ceed5f0b4845c7220a7, size: 42455393
[DEBUG] TIMING  Pushing container configuration
[DEBUG] TIMING  Pushing BLOB digest: sha256:795c3f5cb48d0803262865fa8d7cd44c26d9fee02acf87bd1afa8144025edfa7, size: 1792
[DEBUG] TIMING  pushBlob
[DEBUG]         TIMING  pushBlob POST sha256:9694866d56194cd60f7ccb4f848a6384595d43cba9abd645107c8f678484429a
[DEBUG] TIMING  pushBlob
[DEBUG]         TIMING  pushBlob POST sha256:795c3f5cb48d0803262865fa8d7cd44c26d9fee02acf87bd1afa8144025edfa7
```

**Comment by chanseokoh** [comment]
However, looking at the screenshots and judging from the progress bar completion, the progress message, and the short build time on no change, I bet this is probably because pushing data from your Windows 7 machine to `registry.cn-beijing.aliyuncs.com` is taking the most of the time and slowing you down. That is, some kind of network issue for whatever reason.

**Comment by ZhangErling** [comment]
Hi  @chanseokoh 
I think you are right. This is the result of running `mvn -X -Djib.console=plain`  at home,Obviously faster than I can run in the company. Only three and a half minutes! But I only have Windows7 log, my colleague has his task. I will post the full log at the bottom. Thank you very much!!!
But I have one more question, My project is API, which relies on common. My project API has changed files, but common has files not. The project packaging time is only 30 seconds. If common has file changes, the packaging time increases. Interestingly, when common was unchanged,The amount of time I spend packing projects at work is similar to the amount of time I spend packing projects at home. If common has file changes,The time difference between the two is huge.

`[DEBUG] TIMING	Building and pushing image
[INFO] Retrieving registry credentials for registry.cn-beijing.aliyuncs.com...
[DEBUG] TIMING	Retrieving registry credentials for registry.cn-beijing.aliyuncs.com
[DEBUG] Using <to><auth> for registry.cn-beijing.aliyuncs.com
[DEBUG] TIMED	Retrieving registry credentials for registry.cn-beijing.aliyuncs.com : 0.0 ms
[DEBUG] TIMING	Authenticating with push to registry.cn-beijing.aliyuncs.com
[INFO] Getting base image registry.cn-beijing.aliyuncs.com/hadyang/oracle-java-8-alpine...
[DEBUG] TIMING	Pulling base image manifest
[DEBUG] TIMING	Building application layers
[INFO] Building dependencies layer...
[DEBUG] TIMING	Building dependencies layer
[DEBUG] TIMED	Building application layers : 1.0 ms
[INFO] Building classes layer...
[DEBUG] TIMING	Building classes layer
[INFO] Building resources layer...
[DEBUG] TIMING	Building resources layer
[DEBUG] TIMING	Setting up to push layers
[DEBUG] TIMED	Setting up to push layers : 1.0 ms
[DEBUG] TIMED	Building classes layer : 513.0 ms
[DEBUG] TIMED	Building resources layer : 509.0 ms
[INFO] The base image requires auth. Trying again for registry.cn-beijing.aliyuncs.com/hadyang/oracle-java-8-alpine...
[INFO] Retrieving registry credentials for registry.cn-beijing.aliyuncs.com...
[DEBUG] TIMING	Retrieving registry credentials for registry.cn-beijing.aliyuncs.com
[DEBUG] Using <from><auth> for registry.cn-beijing.aliyuncs.com
[DEBUG] TIMED	Retrieving registry credentials for registry.cn-beijing.aliyuncs.com : 0.0 ms
[DEBUG] TIMED	Authenticating with push to registry.cn-beijing.aliyuncs.com : 1617.0 ms
[DEBUG] TIMING	Pushing BLOB digest: sha256:e4b2ee3b308b0bb987e62cc2fd16f48bada177bd7ecd90bd91cafad36fdabb1b, size: 750500
[DEBUG] TIMING	Pushing BLOB digest: sha256:bb36df5345abf6d928bf2b9d2a345c38da5f14e65897caf62d755bd2e89e6f64, size: 84841
[DEBUG] BLOB : digest: sha256:e4b2ee3b308b0bb987e62cc2fd16f48bada177bd7ecd90bd91cafad36fdabb1b, size: 750500 already exists on registry
[DEBUG] TIMED	Pushing BLOB digest: sha256:e4b2ee3b308b0bb987e62cc2fd16f48bada177bd7ecd90bd91cafad36fdabb1b, size: 750500 : 176.0 ms
[DEBUG] BLOB : digest: sha256:bb36df5345abf6d928bf2b9d2a345c38da5f14e65897caf62d755bd2e89e6f64, size: 84841 already exists on registry
[DEBUG] TIMED	Pushing BLOB digest: sha256:bb36df5345abf6d928bf2b9d2a345c38da5f14e65897caf62d755bd2e89e6f64, size: 84841 : 192.0 ms
[DEBUG] TIMED	Pulling base image manifest : 2153.0 ms
[DEBUG] TIMING	Setting up base image caching
[DEBUG] TIMING	Pulling base image layer sha256:4723172fad744a38c0f213cb7dbaa6310c21e56b2b4859b18ebbeac446f1dfc3
[DEBUG] TIMING	Pulling base image layer sha256:6c40cc604d8e4c121adcb6b0bfe8bb038815c350980090e74aa5a6423f8f82c0
[DEBUG] TIMING	Pulling base image layer sha256:7fdf9ef0673ac09dd21cff2f73eb52cf95d0661b5f338d1fcb78769972a5be8f
[DEBUG] TIMED	Setting up base image caching : 2.0 ms
[DEBUG] TIMING	Pulling base image layer sha256:49c94ee93a07e1782961a3280fcbf0b21992ab6c3571a21202c680088b54cc45
[DEBUG] TIMING	Pulling base image layer sha256:74ed4504331965fcc2b3569f8eec7fa5a94faacd4bafa6f73d5180da1b231cbf
[DEBUG] TIMING	Setting up to push layers
[DEBUG] TIMED	Setting up to push layers : 1.0 ms
[DEBUG] TIMED	Pulling base image layer sha256:4723172fad744a38c0f213cb7dbaa6310c21e56b2b4859b18ebbeac446f1dfc3 : 6.0 ms
[DEBUG] TIMING	Pushing BLOB digest: sha256:4723172fad744a38c0f213cb7dbaa6310c21e56b2b4859b18ebbeac446f1dfc3, size: 3173136
[DEBUG] TIMED	Pulling base image layer sha256:49c94ee93a07e1782961a3280fcbf0b21992ab6c3571a21202c680088b54cc45 : 6.0 ms
[DEBUG] TIMING	Pushing BLOB digest: sha256:49c94ee93a07e1782961a3280fcbf0b21992ab6c3571a21202c680088b54cc45, size: 2347743
[DEBUG] TIMED	Pulling base image layer sha256:7fdf9ef0673ac09dd21cff2f73eb52cf95d0661b5f338d1fcb78769972a5be8f : 10.0 ms
[DEBUG] TIMING	Pushing BLOB digest: sha256:7fdf9ef0673ac09dd21cff2f73eb52cf95d0661b5f338d1fcb78769972a5be8f, size: 200
[DEBUG] TIMED	Pulling base image layer sha256:74ed4504331965fcc2b3569f8eec7fa5a94faacd4bafa6f73d5180da1b231cbf : 8.0 ms
[DEBUG] TIMING	Pushing BLOB digest: sha256:74ed4504331965fcc2b3569f8eec7fa5a94faacd4bafa6f73d5180da1b231cbf, size: 192971128
[DEBUG] TIMING	Pulling base image layer sha256:15a5726c181cd5855b603891f16b845a3534cbe95df2c4af7c705494919e15dd
[DEBUG] TIMED	Pulling base image layer sha256:6c40cc604d8e4c121adcb6b0bfe8bb038815c350980090e74aa5a6423f8f82c0 : 24.0 ms
[DEBUG] TIMING	Pushing BLOB digest: sha256:6c40cc604d8e4c121adcb6b0bfe8bb038815c350980090e74aa5a6423f8f82c0, size: 2754728
[DEBUG] TIMED	Pulling base image layer sha256:15a5726c181cd5855b603891f16b845a3534cbe95df2c4af7c705494919e15dd : 1.0 ms
[DEBUG] TIMING	Pushing BLOB digest: sha256:15a5726c181cd5855b603891f16b845a3534cbe95df2c4af7c705494919e15dd, size: 411355
[DEBUG] BLOB : digest: sha256:49c94ee93a07e1782961a3280fcbf0b21992ab6c3571a21202c680088b54cc45, size: 2347743 already exists on registry
[DEBUG] TIMED	Pushing BLOB digest: sha256:49c94ee93a07e1782961a3280fcbf0b21992ab6c3571a21202c680088b54cc45, size: 2347743 : 186.0 ms
[DEBUG] BLOB : digest: sha256:15a5726c181cd5855b603891f16b845a3534cbe95df2c4af7c705494919e15dd, size: 411355 already exists on registry
[DEBUG] TIMED	Pushing BLOB digest: sha256:15a5726c181cd5855b603891f16b845a3534cbe95df2c4af7c705494919e15dd, size: 411355 : 211.0 ms
[DEBUG] BLOB : digest: sha256:74ed4504331965fcc2b3569f8eec7fa5a94faacd4bafa6f73d5180da1b231cbf, size: 192971128 already exists on registry
[DEBUG] TIMED	Pushing BLOB digest: sha256:74ed4504331965fcc2b3569f8eec7fa5a94faacd4bafa6f73d5180da1b231cbf, size: 192971128 : 227.0 ms
[DEBUG] BLOB : digest: sha256:7fdf9ef0673ac09dd21cff2f73eb52cf95d0661b5f338d1fcb78769972a5be8f, size: 200 already exists on registry
[DEBUG] TIMED	Pushing BLOB digest: sha256:7fdf9ef0673ac09dd21cff2f73eb52cf95d0661b5f338d1fcb78769972a5be8f, size: 200 : 229.0 ms
[DEBUG] BLOB : digest: sha256:4723172fad744a38c0f213cb7dbaa6310c21e56b2b4859b18ebbeac446f1dfc3, size: 3173136 already exists on registry
[DEBUG] TIMED	Pushing BLOB digest: sha256:4723172fad744a38c0f213cb7dbaa6310c21e56b2b4859b18ebbeac446f1dfc3, size: 3173136 : 232.0 ms
[DEBUG] BLOB : digest: sha256:6c40cc604d8e4c121adcb6b0bfe8bb038815c350980090e74aa5a6423f8f82c0, size: 2754728 already exists on registry
[DEBUG] TIMED	Pushing BLOB digest: sha256:6c40cc604d8e4c121adcb6b0bfe8bb038815c350980090e74aa5a6423f8f82c0, size: 2754728 : 215.0 ms
[DEBUG] Building dependencies layer built sha256:8934df58ef04f44e6eb6ec06503bebf2a225df98935a1e3c0e980c9134bc53a7
[DEBUG] TIMED	Building dependencies layer : 7789.0 ms
[DEBUG] TIMING	Building container configuration
[DEBUG] TIMING	Pushing BLOB digest: sha256:8934df58ef04f44e6eb6ec06503bebf2a225df98935a1e3c0e980c9134bc53a7, size: 99306468
[INFO] 
[INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.platform.PlatformApiApplication]
[DEBUG] TIMED	Building container configuration : 1.0 ms
[DEBUG] TIMING	Pushing container configuration
[DEBUG] TIMED	Pushing container configuration : 35.0 ms
[DEBUG] TIMING	Pushing BLOB digest: sha256:e233cac7d91d7d2595d46c157e6fb5e9ac9c4259d02487ff9f6baed84f9a738e, size: 5432
[DEBUG] TIMING	pushBlob
[DEBUG] 	TIMING	pushBlob POST sha256:8934df58ef04f44e6eb6ec06503bebf2a225df98935a1e3c0e980c9134bc53a7
[DEBUG] TIMING	pushBlob
[DEBUG] 	TIMING	pushBlob POST sha256:e233cac7d91d7d2595d46c157e6fb5e9ac9c4259d02487ff9f6baed84f9a738e
[DEBUG] 	TIMED	pushBlob PATCH sha256:8934df58ef04f44e6eb6ec06503bebf2a225df98935a1e3c0e980c9134bc53a7 : 148.0 ms
[DEBUG] 	TIMED	pushBlob PATCH sha256:e233cac7d91d7d2595d46c157e6fb5e9ac9c4259d02487ff9f6baed84f9a738e : 159.0 ms
[DEBUG] 	TIMED	pushBlob PUT sha256:e233cac7d91d7d2595d46c157e6fb5e9ac9c4259d02487ff9f6baed84f9a738e : 254.0 ms
[DEBUG] 	TIMED	pushBlob POST sha256:e233cac7d91d7d2595d46c157e6fb5e9ac9c4259d02487ff9f6baed84f9a738e : 464.0 ms
[DEBUG] TIMED	pushBlob : 877.0 ms
[DEBUG] TIMED	Pushing BLOB digest: sha256:e233cac7d91d7d2595d46c157e6fb5e9ac9c4259d02487ff9f6baed84f9a738e, size: 5432 : 999.0 ms
[DEBUG] 	TIMED	pushBlob PUT sha256:8934df58ef04f44e6eb6ec06503bebf2a225df98935a1e3c0e980c9134bc53a7 : 175484.0 ms
[DEBUG] 	TIMED	pushBlob POST sha256:8934df58ef04f44e6eb6ec06503bebf2a225df98935a1e3c0e980c9134bc53a7 : 3158.0 ms
[DEBUG] TIMED	pushBlob : 178790.0 ms
[DEBUG] TIMED	Pushing BLOB digest: sha256:8934df58ef04f44e6eb6ec06503bebf2a225df98935a1e3c0e980c9134bc53a7, size: 99306468 : 178919.0 ms
[DEBUG] TIMING	Pushing new image
[DEBUG] Tagging with latest...
[DEBUG] TIMED	Pushing new image : 525.0 ms
[DEBUG] TIMED	Building and pushing image : 187283.0 ms
[INFO] 
[INFO] Built and pushed image as registry.cn-beijing.aliyuncs.com/aikeyi_docker/platform-api
[INFO] 
[INFO] 
[INFO] --- wagon-maven-plugin:2.0.0:sshexec (upload-deploy) @ platform-api ---`

[log.txt](https://github.com/GoogleContainerTools/jib/files/3364569/log.txt)

**Comment by ZhangErling** [comment]
I deleted the packaged test class today, and modified some of the code. The packaging time for coding was restored to three and a half minutes, and I think I could get the same result in the company. 
This plugin is fun!When I use it, and something interesting happens, I'll continue to append what happened to me under this question

**Comment by chanseokoh** [comment]
Closing as this is a network issue on the user side. Does not seem like Jib is doing wrong on Windows 7. However, feel free to reopen or create a new issue if something's not working.
