### ISSUE TITLE
Jib proxy config inconsistency

### ISSUE THREAD

**Issue by arykov** [GoogleContainerTools/jib#1826]
When using proxy to access Docker repository jib works differently than maven. Jib uses protocol portion of proxy configuration to set <protocol>.proxyHost, <protocol>.proxyPort, etc(see [source](https://github.com/GoogleContainerTools/jib/blob/d3b1e8c19b36427c84c5a7c6cc034e3e6d87a2d6/jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsProxyProvider.java)). This means that protocol indicates whether repository uses http or https.
At the same time [maven documentation](https://maven.apache.org/settings.html#Proxies) and behavior seem to indicate that protocol applies to proxy itself and not repository.
As a result if our docker repo and maven repo both have ssl enabled, we need to have two proxy configurations. 
For maven
```
<proxy>
      <id>myproxy</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>proxy.somewhere.com</host>
      <port>8080</port>
 </proxy>
```
And for jib:
```
<proxy>
      <id>myproxy1</id>
      <active>true</active>
      <protocol>https</protocol>
      <host>proxy.somewhere.com</host>
      <port>8080</port>
</proxy>
```

**Comment by chanseokoh** [comment]
Hi @arykov,

I had the same question around `<protocol>` and had a chance to get to the bottom of it (we had to, as we were implementing the proxy support in Jib.) From reading many sources that claim conflicting arguments about `<protocol>` and my own experiment, I am convinced that the Maven doc is wrong:

https://github.com/GoogleContainerTools/jib/pull/1337#issuecomment-447102059
https://github.com/GoogleContainerTools/jib/pull/1337#issuecomment-447052026

Evidence:
1. Maven does pick the proxy destination with `<protocol>https` for HTTPS-targeting requests, even if the config is defined after another proxy config with `<protocol>http`. That is, `<protocol>` determines the target protocol of requests to proxy.
2. Even after specifying `<protocol>https` and a proxy listens on port 443, Maven does not speak HTTPS when communicating with the proxy.

What do you think?

**Comment by arykov** [comment]
Yup. You are right. It seems like protocol makes no difference at least for mvn 3.5.2 I was using. So basically jib requirements need to be driving protocol section the way it currently works. I suppose if we were sure mvn ignored protocol so could jib, but realistically it is too insignificant to worry about anyways.
