### ISSUE TITLE
Docker Size

### ISSUE THREAD

**Issue by sathishkumar64** [GoogleContainerTools/jib#1836]
Hi,
I have tried different approach for reducing docker image sizes for using Jib and with Docker. I got different sizes for using those approach but i have seen good result for customizing my docker file.. 

Please see the following approach with result.

1) With Docker and standard approach.

   Docker File:
    FROM openjdk:alpine  
  VOLUME /tmp
  EXPOSE 9098 9099
 ADD ./target/schoolservice-0.0.1-SNAPSHOT.jar schoolservice-0.0.1-SNAPSHOT.jar
 RUN sh -c 'touch /schoolservice-0.0.1-SNAPSHOT.jar'
 ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","schoolservice-0.0.1-SNAPSHOT.jar"]

    Result:
   /schoolservice  19fb63bf8256        39 minutes ago       **201MB**

2) Jib  with Maven (version 1.3.0)
    Result:
    /schoolservice     4b63e5159c01        49 years ago         **174MB**

3) With Docker Customizing my docker file.
   Docker File.
   FROM openjdk:8-jre-alpine
VOLUME /tmp
EXPOSE 9098 9099
ARG DEPENDENCY=target/dependency
COPY ${DEPENDENCY}/BOOT-INF/lib /app/lib
COPY ${DEPENDENCY}/META-INF /app/META-INF
COPY ${DEPENDENCY}/BOOT-INF/classes /app
ENTRYPOINT ["java","-cp","app:app/lib/*","com.schoolservice.SchoolServiceApplication"]

   Result:
 /schoolservice     4add7390347d        About a minute ago   **152MB**

For this case, how can simplify docker size for using JIB? So better i can use approach 3 ? 

Please guide me right solution.

Regards,
Sathish Vasu.

**Comment by chanseokoh** [comment]
Hi @sathishkumar64,

I'd start by looking into the images built from 2) and 3) and examining which files exist in 2) but not in 3). Identify what are those files and where they are coming from. Perhaps you could use some tools like  [dive](https://github.com/wagoodman/dive) or [container-diff](https://github.com/GoogleContainerTools/container-diff).

**Comment by loosebazooka** [comment]
I believe the Alpine image using musl libc is also smaller. Since distroless (default base image when using jib) does make that particular optimization to size, it might be a little bigger.

**Comment by sathishkumar64** [comment]
> Hi @sathishkumar64,
> 
> I'd start by looking into the images built from 2) and 3) and examining which files exist in 2) but not in 3). Identify what are those files and where they are coming from. Perhaps you could use some tools like [dive](https://github.com/wagoodman/dive) or [container-diff](https://github.com/GoogleContainerTools/container-diff).

Hi @chanseokoh 

Thanks for your reply... I have used container-diff but i'm not getting expected result,which means it is giving size only, because these are spring boot applications.

Regards,
Sathish Vasu.

**Comment by sathishkumar64** [comment]
> I believe the Alpine image using musl libc is also smaller. Since distroless (default base image when using jib) doesn't make that particular optimization to size, it might be a little bigger.

Hi @loosebazooka 
Thanks for your reply.

**Comment by chanseokoh** [comment]
Ah, you weren't asking why the sizes are different even when using the same base image. I believe you now know the reason here that you are using the alpine JRE for the Docker build. Use the same small base image for Jib too. The base image is configurable with `jib.from.image` (Gradle) or `<from><image>`.
