### ISSUE TITLE
Maven: provide easy way to switch between default and debug base image

### ISSUE THREAD

**Issue by reitzig** [GoogleContainerTools/jib#1850]
For debugging purposes such as checking files in the container, the [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#where-is-bash) recommends to change the base image to the `:debug` variant provided by distroless. That works, but requires changing back and forth when using Jib through Maven.

Please expose the debug variant more clearly, e.g. by providing additional tasks that use the `:debug` base image, or by adding options to the existing tasks.

**Comment by loosebazooka** [comment]
Fortunately maven provides an easy way to make these customizations yourself using profiles: https://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Comment by chanseokoh** [comment]
Also, you can use either the system property `jib.from.image` or the [Maven property](https://maven.apache.org/pom.html#Properties) `jib.from.image`. For example, on the command line

`$ mvn -Djib.from.image=... jib:build`

For the Maven property, you could utilize `${env.SOME_VAR}`.

But as @loosebazooka mentioned, profiles work nicely too.

**Comment by reitzig** [comment]
Thanks guys, that's helpful. Know your tools, I guess. :'D

Does it make sense to keep the ticket? Imho, it might make sense for Jib to control how the debug image is constructed; switching the base layer (alone) may not be enough (or ideal) in every scenario.

**Comment by loosebazooka** [comment]
I think we can close this... Any other customization can also happen in the profile you have set up for debug
