### ISSUE TITLE
Way to exclude dependencies in the image or have right support for various forms of fat/shaded JARs

### ISSUE THREAD

**Issue by maxbrunet** [GoogleContainerTools/jib#1852]
Hi again,

When building with `containerizingMode = 'packaged'`, our dependencies are built into the jar archive. Is it possible to not add the dependencies to `<appRoot>/libs` for a smaller image?

**Comment by chanseokoh** [comment]
I replied to #1851 and just saw your [comment](https://github.com/GoogleContainerTools/jib/issues/1851#issuecomment-512006402). The [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-want-to-containerize-an-executable-jar) explains the current limitation of `containerizingMode = 'packaged'`, and currently fat JARs or alternatively excluding dependencies are not supported yet. Supporting fat JARs created in various ways including by Spring Boot is something on our radar, but we are not sure when we will get to it.

I think I'll open this issue, which asks for either having
- proper support for fat JARs created in various ways; or
- just some means to exclude dependency JARs

**Comment by chanseokoh** [comment]
It is best to avoid putting a fat JAR if possible, because it nullifies all the benefits of fine-grained layering by Jib that brings in fast iterations and caching. It'd be ideal if Jib could just use the original (non-fat) JAR. And because Spring Boot leaves the original JAR in the build directory, it seems not difficult for Jib to automatically detect Spring Boot and use the original JAR.

We may still introduce an option to not copy dependency JARs if we should really copy a fat JAR, but for now, it's worth implementing this auto-detection for Spring Boot.

**Comment by chanseokoh** [comment]
Just for the record here, in the next Jib release, Spring Boot projects with `containerizingMode='package'` should work seamlessly for both Gradle and Maven out of the box.

Anyways, I don't think we'll need to provide a general way to exclude adding dependencies into the image for the sake of being able to put a fat JAR (with `<containerizingMode>packaged`). Now I think almost all the time, we can just put a normal, non-fat JAR (as long as a project generates the normal JAR and we can locate it) regardless of whether maven-shade-plugin, maven-assembly-plugin, or Gradle shadowJar plugin is applied to create a fat JAR.

**Comment by chanseokoh** [comment]
> However, for a potential feature for generalized fined-grained dependency control, see #1962 (comment)

The [Jib Extension Framework](https://github.com/GoogleContainerTools/jib-extensions) is now available with the latest Jib versions. You can easily extend and tailor the Jib plugins behavior to your liking.

We've written a general-purpose layer-filter extension that enables fine-grained layer control, including deleting files and moving files into new layers

- [Maven Layer-Filter Extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-maven)
- [Gradle Layer-Filter Extension]( https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-gradle)

For general information about using and writing extensions, take a look at the [Jib Extensions repo](https://github.com/GoogleContainerTools/jib-extensions).
