### ISSUE TITLE
Angular Storybook's 'Centered' stories are broken.

### ISSUE THREAD

**Issue by qgfey0i2** [GoogleContainerTools/jib#1858]
Describe the bug
Console shows issue with styles.

To Reproduce
[买澳洲大学毕业证文凭/代办墨尔本毕业证 WX：jywenping购买墨尔本大学毕业证成绩单\墨尔本大学学历认证\墨尔本大学使馆认证\国外文凭办理→国外学历学位认证](www.diplomaclub.net)

**Comment by chanseokoh** [comment]
Looks like a spam bot.
