### ISSUE TITLE
Jib a pre-packaged JAR/WAR

### ISSUE THREAD

**Issue by saturnism** [GoogleContainerTools/jib#1859]
**Description of the issue**:
Create a container image from a given executable Fat JAR or WAR.
E.g., `jib app.jar --image=gcr.io/my-registry/app`

Potentially having a plugin option that simply operate on the final artifact.

**Comment by chanseokoh** [comment]
The command line tools is a great.

FTR, Jib 1.4.0 plugins now have `<containerizingMode>packaged` that simply picks up the final JAR, which addressed a number of issues when not using a JAR. However, using the packaged mode with a fat/shaded JAR is [not well supported and should be avoided.](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-want-to-containerize-a-jar) The support for fat/shaded JAR/WAR are being tracked in #1857.

**Comment by chanseokoh** [comment]
FTR:

We have the [Jib Core library](https://github.com/GoogleContainerTools/jib/tree/master/jib-core) upon which our Jib build plugins were built. The example there shows how easily you can write a program to do custom containerization.

And actually there's a non-official command-line tool called [Cram](https://github.com/briandealwis/cram) based on Jib Core that can cover this scenario with relative ease ([example](https://github.com/briandealwis/cram#java-app)).

**Comment by briandealwis** [comment]
Huh, I didn't remember that.  Nice find 😄

**Comment by zhumin8** [comment]
As updated in https://github.com/GoogleContainerTools/jib/issues/1859#issuecomment-528526823, this is already implemented in Jib CLI now. Closing this issue.
