### ISSUE TITLE
Update README for 1.5.0

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1864]
For #1818, #1840, and #1888.

#1818 and #1840 also applies to jib-core.

README should be merged after plugins are released.

- [x] `container.filesModificationTime`
- [x] `container.creationTime`
- [x] remove `container.useCurrentTimestamp`
- [x] skipping base image cache

**Comment by TadCordle** [comment]
Will need to update with `container.creationTime` as well.
