### ISSUE TITLE
Possibly change 'credHelpers' to 'credentialHelpers'.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#187]
For better readability.

**Comment by lukago** [comment]
What about credsStore and credHelper?

**Comment by coollog** [comment]
Hi Łukasz,

By `credHelper`, do you mean an additional configuration parameter for just configuring a single credential helper (instead of `<credHelpers><credHelper>thecredhelper</credHelper></credHelpers>`)?

For `credsStore`, would this be just a different mechanism for retrieving credentials or just an alias for `credHelper`?

Thanks for your feedback!

**Comment by lukago** [comment]
I meant `credHelper` in `com.google.cloud.tools.jib.gradle.ImageConfiguration` but I maven tags are qualifying for my question as well. 
What I asked is if we want to rename any occurence of _cred*_ to _credential_ to keep it consistent? 
So `credsStore` in `com.google.cloud.tools.jib.registry.credentials.json.DockerConfigTemplate` would be changed to credentialsStore, similarly credHelper and maven tags, plus comments and documentation.

**Comment by coollog** [comment]
Ah okay, that makes sense. I should have been clearer in the issue description. Your suggestion sounds good if we do go with renaming, since it fits more of our style of generally no abbreviations.

**Comment by TadCordle** [comment]
If you're stuck with `credStore` maybe it'd just be best to stay with `credHelpers` for consistency.

**Comment by coollog** [comment]
This is superceded by https://github.com/GoogleContainerTools/jib/pull/251
