### ISSUE TITLE
Give access to image repository or full image references built or pushed

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1875]
It was a popular demand to be able to know the image digest/ID of the built image (#933, #1204), and we decided to expose this metadata in the file `jib-image.digest` and `jib-image.id` as clear-text.

Recently there was a request to expose the image repository name similarly, and this seems like a sane feature request. Some tools may just do `jib:build` on user-supplied source and want to know the image name. Also `<to><image>` is optional for `jib:dockerBuild` and Jib will decide the name.

However, the particular request was to get the image repository name that does not include tags. (Note that Jib can push the same image with multiple tags.)

In that light, we may expose both the repository name (without the tag part) and the full image references built or pushed (will be a list).

Knowing that we would expose multiple metadata, we should decide how. For the digest, we create `jib-image.digest`/`jib-image.id` containing the digest/ID, but while we are at it, we may very well create a new structured JSON file containing all data (and potentially more in the future).

**Comment by briandealwis** [comment]
We also expose the `jib-image.digest` too.

**Comment by TadCordle** [comment]
I think we can call this fixed by #2227

**Comment by chanseokoh** [comment]
@Alos we now write a metadata JSON file containing the image repository name, if this still helps.
