### ISSUE TITLE
How can I COPY a file to docker image's directory '/usr/local/bin/'?

### ISSUE THREAD

**Issue by andyzhaozhao** [GoogleContainerTools/jib#1876]
In Dockerfile,I can do this by "COPY xxx.sh /usr/local/bin/". How do it in Jib?

**Comment by briandealwis** [comment]
See the `extraDirectories` item ([Maven](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extradirectories-object), [Gradle](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#extradirectories-closure)).

**Comment by andyzhaozhao** [comment]
extraDirectories can‘t solve my problem. @briandealwis .I need copy a file into a folder of docker i mage. I didn't  found a way of extraDirectories to solve it. extraDirectories:
```
<configuration>
  <!-- Copies files from 'src/main/custom-extra-dir' and '/home/user/jib-extras' instead of 'src/main/jib' -->
  <extraDirectories>
    <paths>
      <path>src/main/custom-extra-dir</path>
      <path>/home/user/jib-extras</path>
    </paths>
  </extraDirectories>
</configuration>
```
But I wan't to do this.
in Dockerfile:
```
...
COPY  wait-for-it.sh   /usr/local/wait-for-it.sh
...
```
copy the the file wait-for-it.sh into docker images's /usr/local/wait-for-it.sh.

**Comment by chanseokoh** [comment]
@andyzhaozhao you can place the `wait-for-it.sh` file at `<project root>/src/main/jib/usr/local/wait-for-it.sh`. No configuration is needed in this case (when using the default extra files directory `src/main/jib`). Then Jib will put the file at `/usr/local/wait-for-it.sh` in the image.

**Comment by andyzhaozhao** [comment]
@briandealwis @chanseokoh Thank you. But I don't wan't to change my src codes. So high coupling of it. The 'ops' codes invade into the 'dev' codes. I think this‘s not
 a good way to copy the wait-for-it.sh file to my src directory. I want separate the Dev and Ops.Are there any other way to solve my problem? May be I need use the Dockerfile directly instead of Jib?

**Comment by chanseokoh** [comment]
Then, how about making a custom base image that has `wait-for-it.sh` pre-installed and have Jib base on it? Or, maybe the other direction: for example, you could run Jib without the script, and the later ops step could put the script using a Dockerfile, if that is the loose coupling you are talking about?

**Comment by andyzhaozhao** [comment]
Will Jib Support COPY in the pom.xml now？

**Comment by chanseokoh** [comment]
I'd say that is basically what `<extraDirectories>` does. You can configure the source path and control the destination.

**Comment by andyzhaozhao** [comment]
@chanseokoh thank you as same. But ,either preparing a docker image which contains the wait-for-it.sh or putting script in other ops step is not a simple way to solve my problem.

**Comment by andyzhaozhao** [comment]
How can I control the destination by _extraDirectories_ ? @chanseokoh

**Comment by chanseokoh** [comment]
For now, you have to layout the file structure as you would want to see in the image. For example, let's say locally you have `/tmp/foo/bar/baz.txt` in your laptop. Then if you specify `/tmp` as `<extraDirectories><path>`, the `baz.txt` will be placed under `/foo/bar/` in the image. This is how you control the destination.

**Comment by andyzhaozhao** [comment]
@chanseokoh Can extraDirectories support "../" ?  

> "Note that Jib does not follow symbolic links. If a symbolic link is present, it will be removed prior to placing the files and directories." 

The follow config is wrong:
```
<!--将外部文件打包到镜像的配置-->
					<extraDirectories>
						<paths>
							<path>../docker/wait-for-it</path>
						</paths>
					</extraDirectories>
```

**Comment by ayhanap** [comment]
Is there a way to not override the entire destination folder but just copy the files?

Currently below configuration overrides the destination folder. So if existing files in the base image under `/lib64` deleted and replaced with `src/main/custom-extra-dir/lib64`.

```
<path>
  <from>src/main/custom-extra-dir/lib64</from>
  <into>/lib64</into>
</path>
```

**Comment by ayhanap** [comment]
@chanseokoh Yeah seems it is pointing to `lib64 -> usr/lib64`. Thanks a lot for the clarification. 

Can confirm if I use `usr/lib64` which is not a symlink but a directory it copies the files without overriding the destination directory.
