### ISSUE TITLE
Jib should report the base image digest that is used

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#1884]
Jib should report the image digest used for the base image to simplify configuring a fixed digest, and also for traceability.

**Comment by tejaskasetty** [comment]
Hi! Can I take this up?

**Comment by chanseokoh** [comment]
Sure, thanks!

**Comment by chanseokoh** [comment]
Presumably we could just read the [`Docker-Content-Digest` HTTP header](https://docs.docker.com/registry/spec/api/#pulling-an-image) in `ManifestPuller` and let the puller return the SHA along with the JSON manifest.

Alternatively we could compute the SHA on the fly inside `ManifestPuller` (with SHA256 for now).

However, @jonjohnsonjr sent us some links and proceed with caution with the header approach, as registries have implemented this so differently. Generally it's questionable to trust the header value.
- https://github.com/docker/distribution/issues/2395
- https://github.com/GoogleContainerTools/kaniko/issues/298 (Huawie registry doesn't prepend `sha256:` in the header value)
- https://github.com/knative/serving/issues/3997 / https://github.com/knative/serving/pull/3998

**Comment by tejaskasetty** [comment]
So I shall work on getting the manifest from the registry first. This should resolve #2034 as well.

**Comment by chanseokoh** [comment]
Thanks. Check my comments I made on your repo, although I am sure you already did. To fix #2034, maybe you have to change the return type of `ManifestPuller`. If that involves too many changes, I am OK with just printing the digest inside `ManifestPuller` as the first step.

**Comment by tejaskasetty** [comment]
@chanseokoh There is one problem with computing the digest form the response directly. Manfiest has a signatures. And we compute the digest from the manifest without the signatures. And you had suggested to compute the digest directly from the inputStream.

**Comment by jonjohnsonjr** [comment]
Only schema 1 images have signatures, which jib doesn't support (I believe).

**Comment by chanseokoh** [comment]
@jonjohnsonjr Jib doesn't support pushing schema 1 images, but it supports pulling schema 1 base images.

@tejaskasetty I think we can ignore schema 1 manifests. They will be gone sooner or later. We are checking if the schema is 1 or 2 in `ManifestPuller` (I believe), so perhaps we should report the digest only when it is 2. And the digest of the schema 2 manifests will exactly be the SHA256 checksum of the blob content.

**Comment by chanseokoh** [comment]
@tejaskasetty I merged #2052. Do you plan to continue on this?

**Comment by tejaskasetty** [comment]
Yes.

**Comment by chanseokoh** [comment]
Fixed by #2063.

**Comment by TadCordle** [comment]
@dev-gaur @tejaskasetty We've released 1.7.0 with this issue fixed!
