### ISSUE TITLE
allow using saved images (tar balls) as base images

### ISSUE THREAD

**Issue by aespinosa** [GoogleContainerTools/jib#1905]
**Environment**:

- *Jib version:* 1.4.0
- *Build tool:* maven 3.6.1
- *OS:* macOS

**Description of the issue**:

The use case might have similarities to #1807 in a way.  But in this case, I'm using a custom base image only for my java app (like adding kerberos packages to upstream java images).

And since i'm only using it for my project, it would make sense to not publish this intermediary base image and just publish the final image at the end of the build:

**Expected behavior**:

```
docker build -t my-custom-image .
docker save my-custom-image -o base.tar
# maybe it will be something like this??
mvn jib:loadBaseCache -Dfrom=base.tar
mvn jib:build
```

** pom.xml **

```
<!---  ... --->
<from>
   <image>./base.tar</image> 
</from>
<!--- ... --->
```

**Comment by raizoor** [comment]
@aespinosa 

Do you want to use a local image instead of a base image of a registry?
If yes, see the changelog to new release:
```
When building to a registry, Jib now skips downloading and caching base image layers that already exist in the target registry. This feature will be particularly useful in CI/CD environments. However, if you want to force caching base image layers locally, set the system property -Djib.alwaysCacheBaseImage=true (#1840)
```

**Comment by TadCordle** [comment]
Hi @aespinosa,

This is actually being worked on, alongside support for using the local Docker cache for base images (#1468). The tentative plan is to allow configuring different types of base images using a URL scheme like the following:

registry:
```
<from>
  <image>gcr.io/project/image</image>
</from>

<from>
  <image>registry://gcr.io/project/image</image>
</from>
```

docker daemon:
```
<from>
  <image>docker://docker-daemon/image</image>
</from>
```

tar:
```
<from>
  <image>tar:///path/to/tarball.tar</image>
</from>
```

I'll leave this open to track the tar half, since the other issue is focused mostly on docker daemon base images.

**Comment by aespinosa** [comment]
thanks @TadCordle .  that URL scheme looks neat!

**Comment by TadCordle** [comment]
@aespinosa @raizoor v1.6.0 has been released with this feature. You can configure Jib's source image to tar on the filesystem the `tar://` prefix:

Gradle: `jib.from.image = 'tar:///path/to/saved.tar'`
Maven: `<from><image>tar:///path/to/saved.tar</image></from>`
