### ISSUE TITLE
Optimize local base image support: more efficient layer processing

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1913]
Following up #1906.

- [x] Multi-threaded layer compression
  - [x] First pass (#2022)
  - [x] Separate build steps to allow pushing layers immediately after compressing (#2144)

Old ideas that we don't want to do anymore:
- When extracting the tar, process each entry without writing them to disk (conflicts with caching mechanism)
- Instead of computing the layer digest and then pushing to a registry, push base image layers while compressing on-the-fly (https://github.com/GoogleContainerTools/jib/pull/1906#discussion_r314796323) (conflicts with caching mechanism)
- Untar `docker save` output directly instead of writing to disk first (i.e. `docker save | tar -xf -`) (Doesn't seem to save time, and hurts code readability)
- Use `BEST_SPEED` while gzipping instead of the default compression method (faster compression, but slows down push steps since blobs are larger)

**Comment by TadCordle** [comment]
For the record, I tried "Untar docker save output directly instead of writing to disk first", and it doesn't seem to save much time, if any. It makes the code harder to read as well, since `DockerClient`, `TarExtractor`, and `LocalBaseImageSteps` need to be more tightly connected, so I think we can skip this one.

**Comment by TadCordle** [comment]
I also just tried using `BEST_SPEED` for layer compression. The results are sort of what I expected; the layer compression executes faster, so stuff like `jibDockerBuild` and `jibBuildTar` seems to be slightly faster overall. But the faster compression also results in larger blobs, which means pushing to a registry is slower. In that case this seems like it's not worth it since it will actually cause a slowdown for pushing to registries, especially for users with weaker connections.

**Comment by loosebazooka** [comment]
Should we make it configurable?

**Comment by TadCordle** [comment]
I don't think it's worth adding an extra configuration for it. The speed difference is pretty small anyway, and it's only noticeable when the image hasn't been cached yet.
