### ISSUE TITLE
I was wondering if you can provide a choice, that I can choose one of sub module to build the docker image?

### ISSUE THREAD

**Issue by playingjoker** [GoogleContainerTools/jib#1916]
**MVN 3.5.2**:

- *Jib version: 1.12.0*
- *Build tool:* Maven 3.5.2
- *MAC OS:*

**Description of the issue**:
This is not an issue...

**Expected behavior**:
For example, I have three modules in a maven project. I make the configuration at the parent pom.xml. It'll affect in every sub module and all of them will be built in to a docker image.
I just want to build only one of them, but I want make the config at the parent pom.xml.
Just like this:
trade
  -- trade-api
  -- trade-server
  -- trade-biz

I want to build a docker image just happen in `trade-server` build phase.

**Comment by briandealwis** [comment]
Hi @playingjoker.  I can think of a few ways to accomplish this:
  - put your Jib plugin configuration for each module within separately-named profile (`mvn -Pjib-build-api ...`)
  - use the [`jib.skip` property](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage) with a separate value for each module (`mvn -Djib-build-api=true ...`).

There's also an internal property `jib.containerize` which is the dual of `jib.skip` — it specifies the coordinates or locations of the Maven modules to build (`mvn -Djib.containerize=trade-biz ...`).  Note that it's internal and may change without notice.

**Comment by loosebazooka** [comment]
Also, if you're not familiar with profiles, this gives a good overview on how you might implement what @briandealwis described in their first suggestion: https://maven.apache.org/guides/introduction/introduction-to-profiles.html

**Comment by chanseokoh** [comment]
I think this answers your question. Feel free to give us feedback.
