### ISSUE TITLE
Convert allowInsecureRegistries to list of registries instead of binary true/false 

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1923]
I think this is a nice enhancement and useful for multi-module projects. It ensures only those registries are insecure, preventing an issue like https://github.com/GoogleContainerTools/skaffold/pull/2674#issuecomment-523497039.

Potentially it can accept a glob pattern. Or, maybe just a suffix for simplicity.

We also need to think about aliases.

**Comment by briandealwis** [comment]
And since registries would be explicitly identified then we could automatically apply `sendCredentialsOverHttp` for those registries.

**Comment by chanseokoh** [comment]
Or perhaps automatically set `sendCredentialsOverHttp` only for loopback addresses (localhost). AFAIK, OS by-passes a network stack entirely for loopback as optimization, so it's pretty safe.

**Comment by JoeWang1127** [comment]
Closing as part of cleanup. Please re-open if it's still relevant
