### ISSUE TITLE
How to disable automatically generating WAR

### ISSUE THREAD

**Issue by falcon-europe** [GoogleContainerTools/jib#1929]
I have WAR plugin in my gradle project. When I run jib it automatically generates WAR archive. Is it possible to disable it without removing WAR plugin from the project? Thank you in advance for response.

**Comment by briandealwis** [comment]
Do you want to prevent jib being invoked in that project?  You can set the `jib.skip` property in that project to `true`.

**Comment by falcon-europe** [comment]
I want jib to generate only jar (spring boot project). Currently it creates image from war (without manifest file) and I cannot run it.

**Comment by chanseokoh** [comment]
Currently there is no way to disable WAR containerization unless you don't apply the WAR plugin. If you are not going to use the WAR, why do you apply it? Depending on your intention, maybe you could conditionally apply the WAR plugin using a project property?

**Comment by chanseokoh** [comment]
I believe your question is answered. I'm closing this, but if you have further feedback, feel free to re-open. For now, we think the current Jib behavior is reasonable, but we haven't heard back from you for a while, so it may just be that we don't fully understood your use case.
