### ISSUE TITLE
jib-maven-plugin should show warnings if packaging war is used and mainClass is specified

### ISSUE THREAD

**Issue by ST-DDT** [GoogleContainerTools/jib#1939]
**Environment**:

- *Jib version:* 1.5.1 (and also 1.4.0 I haven't checked older ones)
- *Build tool:* jib-maven-plugin
- *OS:* Windows 10

**Description of the issue**:

I tried to build a docker image from my war project, but strangely the entry point always defaulted to the base image's.

**Expected behavior**:

There should be a warning that the mainClass property is ignored similar to when the entry point parameter is specified.

**Steps to reproduce**:

  1. Add jib-plugin config to the pom
  2. Change packaging to war
  3. build the docker image
  4. The entry-point is not set

**Log output**: 

````txt
[INFO] --- jib-maven-plugin:1.5.1:build (default-cli) @ war-gui-server ---
[WARNING] Setting image creation time to current time; your image may not be reproducible.
[INFO]
[INFO] Containerizing application to registry/war-gui:3.0.0...
[INFO] Container program arguments set to [/bin/sh] (inherited from base image)
[INFO]
[INFO] Built and pushed image as registry/war-gui:3.0.0
[INFO] Executing tasks:
[INFO] [==============================] 100,0% complete
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  20.712 s
[INFO] Finished at: 2019-08-28T14:41:25+02:00
[INFO] ------------------------------------------------------------------------
````

@lexuna

**Comment by ST-DDT** [comment]
If ypu change the container mode to packaged instead of exploded you will getva warning if you use certain params. However you dont get a warning when using war packaging. IMO not having the warning consistently causes confusion. Well at least for me.

**Comment by chanseokoh** [comment]
Yeah, if `<mainClass>` and `<jvmFlags>` are ignored when inheriting an entrypoint in the WAR case, we should show warnings if they are explicitly configured.

**Comment by rahul0755** [comment]
I'm facing same issue 
mainClass, extraClasspath, jvmFlags, and expandClasspathDependencies are ignored when entrypoint is specified

how to fix it  ?
