### ISSUE TITLE
If a legacy jar application without source code(pom file) been provided can we create a docker image with jib plugin?

### ISSUE THREAD

**Issue by fnukrishnramesh** [GoogleContainerTools/jib#1940]
**Environment**:

- *Jib version:*
- *Build tool:* 
- *OS:*

**Description of the issue**:

**Expected behavior**:

**Steps to reproduce**:

  1. 
  2. 
  3. 

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @fnukrishnramesh,

Jib Maven/Gradle plugins are build plugins, so I think they are not a fit in this case. However, we have the [Jib Core library](https://github.com/GoogleContainerTools/jib/tree/master/jib-core) upon which our Jib build plugins were built. The example there shows how easily you can write a program to do custom containerization. And actually there's a non-official command-line tool called [Cram](https://github.com/briandealwis/cram) based on Jib Core that I think may work decently in your case.

**Comment by chanseokoh** [comment]
Come to think of it, this sounds like a dup of #1859.
