### ISSUE TITLE
Submodule dependencies may not be built reproducibly without user intervention

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#1945]
for a project A that has a dependecy on project Lib, if lib.jar is not built reproducibly, then the layer lib.jar is built into will also not be.

This currently can only be solved with user intervention. Perhaps in gradle using the techniques described here: https://purpledevcat.com/2018/02/14/reproducible-builds-in-java.html
and in maven using some sort of custom packager.

**Comment by loosebazooka** [comment]
Perhaps we should expand and rewrite these jars and erase the required data. And we should expect user intervention when we make guarantees. I think we can, for project dependencies, do the following transformations (as described [here](https://zlika.github.io/reproducible-build-maven-plugin))

- sorts ZIP entries by name
- replaces file timestamps in ZIP entries with a fixed value
- removes timestamps, user names and tool versions in MANIFEST.MF

**Comment by chanseokoh** [comment]
I have realized that, even for a single module project, we may have the same problem when using the "packaged" containering mode.

Also, since we are exploding WAR and `MANIFEST.MF` goes into the resources directory, this may also be the case for WAR.

**Comment by loosebazooka** [comment]
Done in documentation... still hard for users to discover.
