### ISSUE TITLE
Regression: jib.httpTimeout does not work with >= 1.5.0

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1954]
This is due to [a bug in Google HTTP Client](https://github.com/googleapis/google-http-java-client/issues/799). Upgrade to a newer version once it becomes available [here](https://search.maven.org/search?q=google-http-client-apache-v2) and verify it works.

**Comment by TadCordle** [comment]
Looks like 1.32.0 is out.

**Comment by chanseokoh** [comment]
I confirm the timeout works (although I noticed a slight problem in the Apache HTTP Client library).

I also confirm the new version fixes the underlying issue in #1914, so we don't have to pin down to an older Apache HTTP Client once we upgrade to 1.32.0.

We should upgrade it for the 1.6.0 release.

**Comment by chanseokoh** [comment]
> although I noticed a slight problem in the Apache HTTP Client library

Filed [HTTPCLIENT-2015](https://issues.apache.org/jira/projects/HTTPCLIENT/issues/HTTPCLIENT-2015?filter=allissues). This might not be a regression.

**Comment by chanseokoh** [comment]
We should put a hold on it. We may have to revert the library upgrade that was done before 1.5.0 due to #1970.

**Comment by chanseokoh** [comment]
This issue is actually fixed in 1.6.0 that went live, so I'll close it.
