### ISSUE TITLE
Consider configuring permissions and owners for files not covered in <extraDirectories>

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#1955]
Permissions ~~and owners~~ are configurable for files added from `<extraDirectories>`. For other files put by Jib, they are fixed (755 for directories and 644 for files, owned by root).

I think it is possible to modify permissions and owners for existing *directories* in an base image but not really possible for existing *files* unless we can somehow extract and duplicate the files in our layers? (Correct me if I'm wrong.) Knowing that, how would we know if a configured path is a directory or a file? Perhaps this configuration should apply only to the files put by Jib. Most of the time people won't know the details of which files Jib puts where, but at least people using `<appRoot>` in WAR deployment may find this useful. This WAR case is actually #1257.

That said, #1257 is a subset of this issue. The frowned workaround in #1257 actually tweaks `<extraDirectories>` to modify directory permissions.

**Comment by chanseokoh** [comment]
Forgot to update here that the ownership is configurable through an extension. From https://github.com/GoogleContainerTools/jib/issues/1257#issuecomment-642889893:

---

The [Jib Extension Framework](https://github.com/GoogleContainerTools/jib-extensions) is available with the latest Jib versions. You can easily extend and tailor the Jib plugins behavior to your liking.

Since there's a very compelling reason to allow the container to be mutable at runtime by changing file ownership (e.g., running Skaffold to update class files on Kubernetes during development), we've decided to support this use case through an extension. However, changing ownership is still discouraged unless absolutely needed.
- [Maven Ownership Extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-ownership-extension-maven)
- [Gradle Ownership Extension]( https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-ownership-extension-gradle)

For general information about using and writing extensions, take a look at the [Jib Extensions repo](https://github.com/GoogleContainerTools/jib-extensions).

**Comment by chanseokoh** [comment]
I don't remember what was the motivation for changing permissions for files put by Jib but not coming from `<extraDirectories>`. But I cannot really think of a good reason or a use case to support it at the moment, especially give than the user can now change ownership using the extension.

I am closing this issue, but if you want this feature for an interesting use case, please leave feedback.

**Comment by rmannibucau** [comment]
+1, it is impossible today to chown a folder so if an app (coming from the "FROM" container) does some mkdir in a folder we add some extra files then jib changes the owner of the parent directories and we are kind of not able to use the built image (ex: wso2 which backups its config in `/home/wso2carbon/wso2am-4.1.0/` and if you want to add a jdbc driver you do it in `/home/wso2carbon/wso2am-4.1.0/repository/components/lib`).
