### ISSUE TITLE
Different projects on same registry using invalid credentials from Docker config

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#196]
Original comment: "Another thing I saw was if for example, the user does not define a credHelper, but Jib tried to use the Docker config for credentials, but the credentials in there were for a different GCP project than the project you want to push to, the build fails with no suggestions. We might want to explore providing better feedback in these cases where we have the same registry but the credentials retrieved are not correct."

**Comment by coollog** [comment]
Will be taken care of with credential diagnosing options.
