### ISSUE TITLE
How to separate 3rd party dependency layer from in-house jar dependencies ?

### ISSUE THREAD

**Issue by mzagar** [GoogleContainerTools/jib#1962]
Hi,

Is there a way to tell jib to put some jar dependencies into an 'extra' layer or to put all dependency jars into spearate layers: 1 jar - 1 layer ?

Here's my use case:
- my application depends on 3rd party jars (such as spring, gson, etc...) but also on other in-company jars. 
- those in-company jar dependencies change much often than 3rd party jars and new releases are pushed on daily basis.
- when I push my app image and the pull it during deployment then whole 3rd party jars layer gets pulled even if it only had 1 jar dependency changed.

If I could somehow tell jib to put those 'fast changing' in-company jar dependencies into a layer separate from 3rd party jars then I would get much less overhead when pushing/pulling images in case some of in-company jar dependency version changes because 3rd party jars layer would not be touched and instead of pulling 70MB image change I would pull only a 5MB layer (with all in-company jars inside, those changed aswell as those not changed). 

In my mind this layer would function the same way 'SNAPSHOT' layer does, only I could specify which jar releases go to this layer, something like:
- 3rd party dependencies layer
- **extra dependencies layer**
- project deps layer
- snapshot layer
- resources layer
- class layer
- files layer

Coming back to my original question - instead of this complicated extra layer jar selection maybe it would make sense to have an option to put every dependency jar to a separate layer - that way whichever jar changes, only those layers/jars would get pulled.

**Comment by mzagar** [comment]
I wrote a quick-and-dirty implementation (maven only) which works well for my usecase:
https://github.com/GoogleContainerTools/jib/compare/master...mzagar:project-dependencies-selector

With this option, I can easily select which dependencies I want to put in project dependency layer by matching them using a regex specified in `projectDependenciesSelector` field.

For example, I can force all dependencies starting with `infobip-` to end up in project dependency layer and get it separated from other 3rd party and snapshot dependencies:
```
                    <plugin>
                        <groupId>com.google.cloud.tools</groupId>
                        <artifactId>jib-maven-plugin</artifactId>
                        <configuration>
                            <projectDependenciesSelector>^infobip-.*</projectDependenciesSelector>
                        </configuration>
```

I am ready to polish my pull request if you would consider accepting it.
If not, could you please suggest some alternatives?

Thanks

**Comment by chanseokoh** [comment]
Hi @mzagar

That's a very interesting use case that makes us to think we should have a way to support. For a long time, we've had a lot discussions around layering various sorts of dependencies, and looks like we still need to think about this more.

> maybe it would make sense to have an option to put every dependency jar to a separate layer

I think you should avoid this. There used to have a very small limit (of 42) as to how many layers you can have, which I believe has been mostly lifted on modern kernels, but I think many still may face another limit (of 127, for example): https://github.com/docker/docker.github.io/issues/8230

**Comment by hendrikhalkow** [comment]
https://github.com/GoogleContainerTools/jib/issues/1724 does exactly what you want.

**Comment by cricket007** [comment]
Should this be closed?

**Comment by mzagar** [comment]
Hi @cricket007, for me this is still an issue so I would not close it.

Unfortunately #1724 does not solve my problem.

**Here's a structure of infobip-hello maven project I am building:**
- resulting docker image is built inside `infobip-hello-service` maven submodule
- ![image](https://user-images.githubusercontent.com/896701/76704845-1e92d900-66dc-11ea-8a75-e71a9cd4ae4c.png)

**After `mvn jib:dockerBuild` following jib layers are created in `infobip-hello-service` docker image :**
- ![image](https://user-images.githubusercontent.com/896701/76704947-ba244980-66dc-11ea-8519-3dafa3797f63.png)
 
**After diving into docker image built with jib 2.1.0 here's the content of jib layers :**
#### 1. dependencyJars layer 
- all 3rd party dependencies are store at this layer (commons, grps, hibernate, ...)
- in-house dependencies - which are same as 3rd party dependencies from perspective of this module are highlighted (infobip-*)  

- ![image](https://user-images.githubusercontent.com/896701/76704760-7e3cb480-66db-11ea-8163-fe0f3b832afb.png)

#### 2. snapshotDependencyJars layer

- infobip-hello-service module picked up infobip-hello-connector submodule dependency as expected
- ![image](https://user-images.githubusercontent.com/896701/76704816-db386a80-66db-11ea-832e-a69f175e38c7.png)
 
#### 3.   projectDependencyJars
- not present (probably since it is empty)

#### 4. app resources layer
- as expected contains src/main/resources content
- ![image](https://user-images.githubusercontent.com/896701/76704998-02436c00-66dd-11ea-987a-0d49ab87c1cc.png)

#### 5. app class layer
- as expected
- ![image](https://user-images.githubusercontent.com/896701/76705012-1f783a80-66dd-11ea-9183-7508c4f3e924.png)

#### 6. jib extra directory
- as expected, contains files added explicitly
- ![image](https://user-images.githubusercontent.com/896701/76705034-4e8eac00-66dd-11ea-8908-2f585188ec8a.png)

My challenge is that in dependencyJars layer (1) in-house (infobip-*) dependencies are present and I would like:
- for those inhouse deps to be present in separate layer because they change more often than 3rd party deps
- to be able to control which dependencies I put in this 'separate layer'

If I am doing something wrong  in using jib and I can accomplish this easily please help :)
If not, I still am in favor of my suggestion to introduce this 'separate layer' where user could control with a regex which dependencies should be stored in this layer.

Any suggestion how to go about this is greatly appreciated.

Thanks,
Mario

**Comment by chanseokoh** [comment]
@mzagar we're not going to close this. For now, I don't see an immediate workaround in your situation to have this level of fine-grained control.

As we are getting numerous feature requests to Jib (many of which are often very specific to certain use-cases, don't align well with Jib's model or intentions, are too complex to support without polluting our codebase or configuration with special code, etc.), we decided to introduce an extension framework to Jib rather than trying to implement all of them one way or another. With the extension system, anyone will be able to extend and/or modify Jib's behavior relatively easily and have a fine-grained control over most of the aspects of image building. I think that will cover most of such issues and FRs, including this one.

**Comment by mzagar** [comment]
sounds great, thanks!

any eta or a task I could follow the progress of the extension framework?

**Comment by chanseokoh** [comment]
We are working on it, but I think it's going to take a while. We aim to complete this at least in the second quarter.

**Comment by chanseokoh** [comment]
@mzagar @hendrikhalkow @OneCricketeer

The [Jib Extension Framework](https://github.com/GoogleContainerTools/jib-extensions) is now available with the latest Jib versions. You can easily extend and tailor the Jib plugins behavior to your liking.

We've written a general-purpose layer-filter extension that enables fine-grained layer control, including deleting files and moving files into new layers. The extension will cover your use-case to create a separate layer for in-hours jar dependencies (or any new layer for any files).

- [Maven Layer-Filter Extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-maven)
- [Gradle Layer-Filter Extension]( https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-gradle)

For general information about using and writing extensions, take a look at the [Jib Extensions repo](https://github.com/GoogleContainerTools/jib-extensions).

**Comment by mzagar** [comment]
@chanseokoh just wanted to say the layer-filter extension works just the way we need, thanks!
