### ISSUE TITLE
Log output gets overwritten

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#1963]
Jib output used to say:
```
Containerizing application to Docker daemon as test...

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, Hello]

Built image to Docker daemon as test
Executing tasks:
[==============================] 100.0% complete
```

but now the first two messages get overwritten shortly after printing them, and the final output becomes:

```




Built image to Docker daemon as test
Executing tasks:
[==============================] 100.0% complete
```

**Comment by TadCordle** [comment]
Tested on gradle, haven't tried with maven.

**Comment by chanseokoh** [comment]
Drat, this must be by #1953. I'll look into it.

**Comment by chanseokoh** [comment]
Seems like this has something to do with Gradle's own progress bar updating.

```
<==========---> 80% EXECUTING [0s]
```

For example, if I prepend an arbitrary string of length 12 like

```java
            lifecycleConsumer.accept(
                "1234567789012" + String.format(CURSOR_UP_SEQUENCE_TEMPLATE, 2));
```

most of the time (not always) Gradle doesn't overwrite previous output, with some quirks to show a few more lines. So I think it is not safe to make a two-cursor-up jump at once in Gradle.
