### ISSUE TITLE
change jibSerialize -> jib.serialize

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#1967]
`jib.serialize` is more consistent with our other properties.

`jibSerialize` should also be marked for deprecation and removal in 2.0

**Comment by TadCordle** [comment]
It's pretty inconsistent across the board. I can't remember what the first two are for (maybe something skaffold related, so we shouldn't touch them?) but maybe `sendCredentialsOverHttp` should change too.

```
_JIB_UPSTREAM_CLIENT
_JIB_DISABLE_USER_AGENT
jib.httpTimeout
jib.blobMounts
jib.alwaysCacheBaseImage
sendCredentialsOverHttp
jibSerialize
```

**Comment by chanseokoh** [comment]
We should not forget our READMEs and FAQ.

**Comment by loosebazooka** [comment]
So is there a single entrypoint into the code where we can check for deprecations like this? `JibSystemProperties` doesn't really have access to a logger, so we're going to have to kind of process our checks on use of deprecated things somewhere else?

**Comment by TadCordle** [comment]
Maybe it could be in `JibContainerBuilder#containzerize`?
