### ISSUE TITLE
Seeking Guidance on Leveraging Gradle's distZip Task

### ISSUE THREAD

**Issue by neilchaudhuri** [GoogleContainerTools/jib#1977]
**Environment**:

- *Jib version:* 0.10.1
- *Build tool:* Gradle 5.4.1
- *OS:* Windows 10

**Description of the issue**:

I am attempting to containerize a Spring Boot application using Jib Core in a custom Gradle task as environment constraints prevent use of the Jib Gradle plugin. As you know, Gradle's Distribution Plugin can generate compressed artifacts like a zip file containing the executable jar and a script that can run it.

My questions are the following:
- Is this advisable from a "best practices" perspective given the larger image size and additional layers it takes to accomplish unzipping and removing the zip file? On the bright side, it does make running it easier.
- If it is advisable, which `Containerizer` API calls allow me to unzip the compressed file and run the script? It isn't obvious to me from the JavaDocs.

**Expected behavior**:

N/A

**Steps to reproduce**:

N/A

**`jib-gradle-plugin` Configuration**: 
```groovy
task(buildImage, dependsOn: build) {
  doLast {
    Jib
      .from("my-repo.com:5000/redhat-openjdk-18/openjdk18-openshift:1.6")
      .setEntrypoint("unzip", "/my-boot-1.0-SNAPSHOT.zip")
      .addExposedPort(Port.tcp(8080))
      .containerize(Containerizer
          .to(DockerDaemonImage.named("hello-from-jib"))
          .addEventHandler(LogEvent.class, { logEvent -> println(logEvent.getLevel() + ": " + logEvent.getMessage()) })
       )
  }
}
```

**Log output**:  N/A

**Comment by chanseokoh** [comment]
```java
.setEntrypoint("unzip", "/my-boot-1.0-SNAPSHOT.zip")
```

This doesn't make much sense to me, as the image will just unzip the archive and stop when instructed to run. It should normally be like `.setEntrypoint("java", "-jar", "/my-boot-runnable.jar")`. I guess a runnable JAR (whether a single fat-JAR, a collection or JAR, or some kick-off script) swill be inside `/my-boot-1.0-SNAPSHOT.zip`. In any case, you certainly don't want to do the unzip at runtime.

I know it is easy to unpack various archives in Gradle.

```gradle
task unzip(type: Copy) {
  from zipTree('src/dist/dist.zip’)
  into 'ib'
}
```

See https://mrhaki.blogspot.com/2012/06/gradle-goodness-unpacking-archive.html for more.

With jib-core, you can have total control of how many layers you want and which files go into which layer. At one end of the spectrum, you can have a single application layer containing one runnable fat JAR where you would just do `java -jar fat.jar`. The downside is that whenever you update your Java source file, the entire fat JAR hence the layer should be rebuild and pushed repeatedly, even though other things like resources, dependency libraries, extra files don't change. The Jib plugins optimizes layers in this regard.

Hope this helps.

**Comment by neilchaudhuri** [comment]
This is helpful guidance. Thanks.
