### ISSUE TITLE
Module-to-module dependencies in a multi-module maven file are not copied into the container

### ISSUE THREAD

**Issue by DavyLandman** [GoogleContainerTools/jib#2042]
**Environment**:

- *Jib version:* 1.6.1
- *Build tool:* 3.6.0 (jdk 1.8.0_222)
- *OS:* Windows 10

**Description of the issue**:
In a multi module pom, the intermodule dependencies are not copied into the container when using the exposed mode and not running package. 

Based on the [multi-module example](https://github.com/GoogleContainerTools/jib/tree/master/examples/multi-module) you run `mvn compile jib:build` but that doesn't work, as the dependencies are not packaged, and jib wants to have all dependencies as jar.

As I see it, this is either this is an issue with the example, or the exposed mode should also copy the class files of the intermodule dependencies.

**Expected behavior**:

Either:
1. warning that intermodule dependencies are not included when running compile, so run with `mvn package`
2. copy class files of intermodule depedencies just like the class files of the module. That would fit better with the exposed mode of operation.

**Steps to reproduce**:

  1. clone: https://github.com/SWAT-engineering/jib-test
  2. run: `mvn clean compile jib:dockerBuild`
  3. `docker run --rm test-app/app`:
```
Exception in thread "main" java.lang.NoClassDefFoundError: common/A
        at app.B.main(B.java:7)
Caused by: java.lang.ClassNotFoundException: common.A
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
```
  4. run `mvn clean package jib:dockerBuild`
  3. `docker run --rm test-app/app`:
```
1764
```

Anyway, thanks for the great tool, I have a workaround for now, but just thought to post it here, it might be a nice extension to the documentation or else a new feature.

**Comment by loosebazooka** [comment]
You're right package is a necessity for multimodule builds. Since maven doesn't surface the dependency through the reactor system unless it is packaged.

The problem with that sample is that there are no inter-module dependencies... we should update that example.

**Comment by chanseokoh** [comment]
@DavyLandman just so you know, in your case, simply do `mvn package jib:dockerBuild` without `<containerizingMode>packaged`. The library JAR will not be duplicated, and you're good to go.

**Comment by DavyLandman** [comment]
@loosebazooka ah, indeed, I read a bit more about the reactor, and the exec plugin also suffers from this, so that might not be possible. 

Indeed, extend the example with inter-module dependency, or at the least, change the `mvn compile` to `mvn package`, so that when you do start there, you won't be confused.

@chanseokoh yes, my step 4 does that. But looking inside the container (using dive) I see the common module as a jar, instead of the class files. Would be nice to also just have the classes there, but maybe the reactor of maven is limiting us to much there.

**Comment by loosebazooka** [comment]
Perhaps there is some way we can check for multimodule builds with intermodule dependencies that package is indeed being called?

**Comment by loosebazooka** [comment]
Hey @DavyLandman sorry for the delay, we've updated the multi-module sample and README, appreciate any feedback you might have.

**Comment by abelsromero** [comment]
All examples use `compile` and while I understand it's acurate it may cause some hussle with quickstarts.

**Comment by loosebazooka** [comment]
@abelsromero I'm not sure what you mean? Are you talking about this section? https://github.com/GoogleContainerTools/jib/tree/master/examples/multi-module#how-to-run ?

**Comment by abelsromero** [comment]
That was quick, no time to correct :smile: 
I wanted to say that I stumbled with the same issue and took me some time to find it cause I was looking at the main plugin README. Maybe it'd be ncie to add a note there too about multimodules projects.

**Comment by loosebazooka** [comment]
right, I added a section a few days ago: https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin in PR: https://github.com/GoogleContainerTools/jib/pull/2303

Do you think we could do a little more here (serious question)? I'm open to ideas on how to improve the discoverability of the multi-module docs.

**Comment by abelsromero** [comment]
That definetly helps, but I was thinking more on a small note* below the quickstart first example.
Something in the line *For muti module projects use `package` goal instead `. To know more see [multimodule example link]*.

* if you've seen AsciiDoc adminitions, you know what I mean

**Comment by loosebazooka** [comment]
So yeah that's a good idea in the quickstart section, I'll see what we can do there, but I also think multimodule is more complicated than just swapping the package goal, no? you need `-am` and `-pl` flags to ensure you do the right thing.

**Comment by abelsromero** [comment]
You are right, and you also need to enable skip on some submodules. My goal with this suggestion is avoiding issues with the quickstart for those that skim through docs, copy-paste commands and then rant "*h*% not even the simple example works!".
Based on that, maybe the approach should be just stating that multumodules wont' work with that command and point to the example?
