### ISSUE TITLE
Enable to use jib-core to extract a file from a layer

### ISSUE THREAD

**Issue by rmannibucau** [GoogleContainerTools/jib#2045]
Hi,

I have the need to grab a docker image, extract a file to modify it (concatenation) and recreate a docker image.
Jib would be quite fancy except today I have to extract a tar first.
Is it possible to expose StepsRunner to let custom code reuse the steps easily?
Basically it would 1. pull the base image 2. load the layer 3. custom handling of the entries of the layers.

Hope it makes sense.

If it helps, here is the current workaround using reflection:

    final StepsRunner steps = StepsRunner.begin(BuildConfiguration.builder()
            .setBaseImageConfiguration(ImageConfiguration.builder(ImageReference.parse(from)).build())
            .setTargetFormat(ImageFormat.OCI)
            .setTargetImageConfiguration(ImageConfiguration.builder(ImageReference.parse(toConnectorsImage)).build())
            .setToolName("MyTool")
            .setExecutorService(executor)
            .setBaseImageLayersCacheDirectory(baseCache)
            .setApplicationLayersCacheDirectory(appCache)
            .build());
    final String description = "Demo";
    final Field rootProgressDescription = asAccessible(StepsRunner.class.getDeclaredField("rootProgressDescription"));
    rootProgressDescription.set(steps, description);
    final List<Runnable> stepsInstance = (List<Runnable>)
            asAccessible(StepsRunner.class.getDeclaredField("stepsToRun")).get(steps);
    stepsInstance.add(() -> {
        try {
            asAccessible(StepsRunner.class.getDeclaredMethod("pullBaseImage")).invoke(steps);
        } catch (final IllegalAccessException | NoSuchMethodException e) {
            throw new IllegalStateException(e);
        } catch (final InvocationTargetException e) {
            throw new IllegalStateException(e.getTargetException());
        }
    });
    stepsInstance.add(() -> {
        try {
            asAccessible(StepsRunner.class.getDeclaredMethod("obtainBaseImageLayers", boolean.class)).invoke(steps, true);
        } catch (final IllegalAccessException | NoSuchMethodException e) {
            throw new IllegalStateException(e);
        } catch (final InvocationTargetException e) {
            throw new IllegalStateException(e.getTargetException());
        }
    });
    Stream.of("buildAndCacheApplicationLayers", "buildImage").forEach(method -> {
        stepsInstance.add(() -> {
            try {
                asAccessible(StepsRunner.class.getDeclaredMethod(method)).invoke(steps);
            } catch (final IllegalAccessException | NoSuchMethodException e) {
                throw new IllegalStateException(e);
            } catch (final InvocationTargetException e) {
                throw new IllegalStateException(e.getTargetException());
            }
        });
    });
    try (final ProgressEventDispatcher progressEventDispatcher =
                 ProgressEventDispatcher.newRoot(EventHandlers.builder()
                         .build(), description, stepsInstance.size())) {
        asAccessible(StepsRunner.class.getDeclaredField("rootProgressDispatcher")).set(steps, progressEventDispatcher);
        stepsInstance.forEach(Runnable::run);
    }
    final Object stepResult = asAccessible(StepsRunner.class.getDeclaredField("results")).get(steps);
    final Image image = ((Future<Image>) asAccessible(stepResult.getClass().getDeclaredField("builtImage")).get(stepResult)).get();

**Comment by loosebazooka** [comment]
Marking as dup of #1388 for now. Thanks for the extra detail.
