### ISSUE TITLE
Can't push to remote registry

### ISSUE THREAD

**Issue by iocanel** [GoogleContainerTools/jib#2046]
**Environment**:

- *Jib version:* 1.6.1
- *Build tool:* maven 3.5.4
- *OS:* Linux

**Description of the issue**:

I am trying to push to the default registry, but pushing fails after 10+ minutes (and a lot of read timeouts) with HTTP 401 error.

**Expected behavior**:

- I would expect to fail fast if there is an authentication issue.
- I would expect not have timeout errors.
- I would expect some short of feedback and which credential source was used (config.json, settings.xml, etc).

**Steps to reproduce**:

     spring init -g org.acme -a hello-world -v 0.1-SNAPSHOT -dweb hello-world
     cd hello-world
     mvn compile com.google.cloud.tools:jib-maven-plugin:1.6.1:build -Dimage=iocanel/hello-world

also tried with:

    mvn compile com.google.cloud.tools:jib-maven-plugin:1.6.1:build -Dimage=iocanel/hello-world -Dto.auth.username=iocanel -Dto.auth.password=xxxxx

without luck.

Note: I have a valid .docker/config.json, and also entries in my settings.xml for `docker.io` and `registry-1.docker.io`.

**Log output**: 
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< org.acme:hello-world >------------------------
[INFO] Building demo 0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ hello-world ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ hello-world ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- jib-maven-plugin:1.6.1:build (default-cli) @ hello-world ---
[INFO] 
[INFO] Containerizing application to iocanel/hello-world...
[INFO] 
[INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, org.acme.helloworld.DemoApplication]
[INFO] Executing tasks:
[INFO] [=========================     ] 82.5% complete
[INFO] > launching layer pushers
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:07 min
[INFO] Finished at: 2019-10-08T08:28:12Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.6.1:build (default-cli) on project hello-world: Build image failed, perhaps you should make sure your credentials for 'registry-1.docker.io/iocanel/hello-world' are set up correctly. See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized for help: Unauthorized for registry-1.docker.io/iocanel/hello-world: 401 Unauthorized
[ERROR] {"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":[{"Type":"repository","Class":"","Name":"iocanel/hello-world","Action":"pull"},{"Type":"repository","Class":"","Name":"iocanel/hello-world","Action":"push"}]}]}
[ERROR] -> [Help 1]

**Comment by raizoor** [comment]
@iocanel 
Is this an private registry? Http or Https?
Try to use 1.4.0

**Comment by iocanel** [comment]
@raizoor: It's docker.io actually.

Trying 1.4.0 right now.

**Comment by chanseokoh** [comment]
Hi @iocanel,

I suspect #691, given what you said. That is, a credential token retrieved from Docker Hub expiring. There are a few workarounds in #691. Once an image is pushed to the target repository by any means, subsequent builds will be fast enough to trigger the problem.

That said, is it normal in your environment that talking to Docker Hub is slow? Is `docker push` slow too or it is only Jib? (`docker push` retries a few times if there are failures, so `docker push` will eventually succeed. That is the difference with Jib.)

Last, it's `-Djib.to.auth.{username|password}`, not `-Dto.auth...`, although this doesn't help.

**Comment by iocanel** [comment]
Usually, `docker push` is quite fast. 
To be honest, I haven't tried today, but I will as soon as my current attempt is complete (still trying with 1.4.0).

**Comment by chanseokoh** [comment]
Yeah, so I think this is a dup of #691. Docker will eventually succeed, because they retry a few more times when there are failures. That really makes sense for a CLI. We also have a similar issue open to retry when there are failures.

But I think it is a good idea for Jib to inform where it retrieved base and target credentials.

**Comment by raizoor** [comment]
25 min ? wow, it's so much time...
It's a good ideia @chanseokoh . I think at least one warning that this problem may occur in certain situations ... Something that indicates to the user that it could also be a problem with your network, you know?

**Comment by chanseokoh** [comment]
Will close this as a dup of #1693. I've created a new issue (#2056) for logging a credential source.

**Comment by chanseokoh** [comment]
Sorry, #691, not #1693.
