### ISSUE TITLE
Allow to pull, modify and push using the same RegistryImage

### ISSUE THREAD

**Issue by reclaro** [GoogleContainerTools/jib#2047]
**Environment**:

- *Jib version:* jib-core 0.11.0
- *Build tool:* maven 3.6.2
- *OS:* macos

**Description of the issue**:
At the moment it is not possible to use the same RegistryImage to pull, modify and push the modified image to a registry.  If I try that I get this error:
```Multiple entries with same key: <image/imagename>=pull and <image/imagename>=pull,push```

**Expected behavior**:
It would be very useful to be able to specify the same RegistryImage in `Jib.from` and in `Containerizer.to`

**Steps to reproduce**:
Write a method which does something like:
```
JibContainerBuilder jibContainerBuilder = Jib.from("<myRegistryImage>");
jibContainerBuilder.addLayer(Arrays.asList(Paths.get("random.txt")),  AbsoluteUnixPath.get("/")); 
jibContainerBuilder.containerize(Containerizer.to("<myRegistryImage>"));

```
**Log output**: 
```
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Multiple entries with same key: <myRegistryImage>=pull and <myRegistryImage>=pull,push                
```

**Comment by loosebazooka** [comment]
@reclaro I'm curious how you would use something like this.

**Comment by reclaro** [comment]
@loosebazooka I am writing a  function which exercises a registry, the function pull an image, modify it and push it back to the registry. I could use 2 different function but what I am interested in my test is just to do pull -modify (so as next time I'll force a pull without using the cache) and push back.
