### ISSUE TITLE
Clarify log message when Jib skips downloading base image

### ISSUE THREAD

**Issue by raizoor** [GoogleContainerTools/jib#2053]
**Environment**:

- *Jib version: 1.6.1*
- *Build tool:* Maven 3.6.0
- *OS:* Linux Centos

**Doubt**

Hi team,

I see the log bellow on my build and it strange to me:
```
[INFO] 
[INFO] --- jib-maven-plugin:1.6.1:build (default-cli) @ gesresrf-conector-api ---
[INFO] 
[INFO] Containerizing application to harbor.myregistry.net/gesresrf/gesresrf-conector-api:1.5.2...
[INFO] Retrieving registry credentials for harbor.myregistry.net...
** [INFO] Getting base image harbor.myregistry.net/openjdk/openjdk:11-minimal...**
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
```

That log "Getting base image" it's correct? My base image already exists on target registry. Maybe i can have a problem in this function or "Getting base image" is only verify if the image already exists there, like get the manifest?

**Comment by TadCordle** [comment]
Will leave this open to track the logging change.
