### ISSUE TITLE
Display if credentials were successfully retrieved and from which source

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2056]
From #2046.

Auth has the most friction, and it will help a lot to report if Jib picked up some credentials and where if so. It will help cases like #2050 too.

**Comment by loosebazooka** [comment]
There's some other work we can do here too, like try all credential sources if possible...

```
Trying dockerConfig... FAILED (although failed seems a little bit aggressive here)
Trying mavenConfig... AUTHORIZED
```

**Comment by fgakk** [comment]
Someone working on this issue? If not, I would like to tackle this.

**Comment by chanseokoh** [comment]
Hi @fgakk, no one's working on this. Thanks for considering giving us some help! This will be a very nice feature. If you need help, just feel free to ask early.

**Comment by fgakk** [comment]
OK, I looked it up and saw in CredentialRetrieverFactory.java there is already a log statement for retrieving credentials from Docker config.

```CredentialRetriever dockerConfig(
      DockerConfigCredentialRetriever dockerConfigCredentialRetriever) {
    return () -> {
      try {
        Optional<Credential> credentials = dockerConfigCredentialRetriever.retrieve(logger);
        if (credentials.isPresent()) {
          logGotCredentialsFrom("credentials from Docker config");
          return credentials;
        }

      } catch (IOException ex) {
        logger.accept(LogEvent.info("Unable to parse Docker config"));
      }
      return Optional.empty();
    };
  }

```

Are they any other CredentialRetriever functions deriving from a source and what are they? And RetrieveRegistryCredentialsStep.java is the place I found, where each CredentialRetrievers are called. Am I on the right track?

**Comment by chanseokoh** [comment]
If so, then for `CredentialRetrieverFactory`, it could just be a matter of increasing the log level in `logGotCredentialsFrom`. That is, from `LogEvent.info()` to `LogEvent.lifecycle()`. INFO is only visible with the debug level log.

And the complete list of credential retrievers that Jib plugins will try is defined in `DefaultCredentialRetrievers.asList()`. Note that method just creates a list of retrievers. Depending how you plan to actually log an auth source and where, you may not have to increase the log level in `CredentialRetrieverFactory`. But no idea at this point.

As far as I can remember, Jib will go over the retriever list and stops at the first retriever that succeeds. So for example, if `setKnownCredential()` is ever called, that will be used and other retrievers will not be ever tried, but I could be wrong about this.
