### ISSUE TITLE
Doubt about snapshot layer

### ISSUE THREAD

**Issue by raizoor** [GoogleContainerTools/jib#2061]
-->

**Environment**:

- *Jib version: 1.6.1* 
- *Build tool: Maven 3.6* 
- *OS: Centos 7*

**Description of the issue**:

Team,

I was inspecting an project today and I have presenced the below log:

```
[INFO] Building dependencies layer...
--> [INFO] Building snapshot dependencies layer... <--
[INFO] Building resources layer...
[INFO] Building classes layer...
```
What exactly is that snapshot? When occurs it?
Inspecting my gitlab runner, I could saw 4 layers in cache too.

**Comment by loosebazooka** [comment]
includes dependencies that are versioned as SNAPSHOTS

like `my.group:package:1.0.0-SNAPSHOT`, the assumption is that these libraries might change frequently and we wouldn't want to rebuild the whole dependencies layer because of it.

**Comment by raizoor** [comment]
Thanks @loosebazooka !
I think these characteristic could be in the readme, don't you think?

**Comment by TadCordle** [comment]
>I think these characteristic could be in the readme, don't you think?

Or maybe the FAQ, as we tend to treat layering as an implementation detail rather than something users need to worry about. We do already have an example of a [similar dockerfile](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-would-a-dockerfile-for-a-jib-built-image-look-like) in the FAQ which includes the snapshot dependencies layer, but I suppose it doesn't indicate the layering as clearly as we could be.

**Comment by raizoor** [comment]
`but I suppose it doesn't indicate the layering as clearly as we could be.`
That's the point to me @TadCordle .. I think you can present more JIB funcionalities. Today you have been explicity a few things, only the most important on readme. I'm not a Java Developer and it's hard to me understand clearly your codes. I think all JIB features must be exists an any place, I don't know if FAQ is the better place, but anywhere that indicates that.

**Comment by loosebazooka** [comment]
yeah there's isn't much documentation around this. We can mark this as a doc bug. We also have a project-dependencies layer for dependencies coming from other sub-projects
