### ISSUE TITLE
Issues with Gradle 6.0-rc-1

### ISSUE THREAD

**Issue by juergenzimmermann** [GoogleContainerTools/jib#2086]
**Environment**:

- *Jib version:* 1.7.0
- *Build tool:* Gradle 6.0-rc-1
- *OS:* Windows 10 Enterprise

**Description of the issue**:
When I invoke `gradle jib` I get these deprecation warnings:

```
> Task :jib
Property 'jib.allowInsecureRegistries' @Input properties with primitive type 'boolean' cannot be @Optional. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'jib.container.useCurrentTimestamp' @Input properties with primitive type 'boolean' cannot be @Optional. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
```

**Expected behavior**:
No deprecation warning

**Steps to reproduce**:
see above

**Log output**: 
see abouve

**Comment by glefloch** [comment]
I opened a PR which aim to fix those two warning. Should the the `@Optional` be removed from every other input ?

**Comment by chanseokoh** [comment]
Thanks. I thought it is just those two warning with the primitive `boolean`? If you did see other warnings, could you post the output here so that we can see? Otherwise, I guess it's just those two.

**Comment by chanseokoh** [comment]
@juergenzimmermann the warning should be gone with Jib 1.8.0. Thanks for fixing this @glefloch!
