### ISSUE TITLE
Jib images do not show up in Portus

### ISSUE THREAD

**Issue by markusheiden** [GoogleContainerTools/jib#2087]
**Environment**:

- *Jib version:* 1.7.0
- *Build tool:* Maven 3.6.2
- *OS:* macOS

**Description of the issue**:
Images pushed by Jib do not show up (main tag and additional tags) in our self hosted Portus (http://port.us.org/). Pulling those images from our self hosted registry is possible though.

**Expected behavior**:
Images show up in the Portus frontend.

**Steps to reproduce**:

  1. jib:build with pushing the image to a registry with a Portus frontend
  2. The image won't appear in Portus

**`jib-maven-plugin` Configuration**: 
```xml
                  <configuration>
                     <from>
                        <image>${docker.java.image}</image>
                     </from>
                     <container>
                        <jvmFlags>...</jvmFlags>
                        <args>.../args>
                        <ports>
                           <port>1160</port>
                           <port>8080</port>
                        </ports>
                     </container>
                     <to>
                        <image>${docker.hub}/${docker.hub.path}/${project.artifactId}:${docker.image.version}</image>
                        <auth>
                           <username>${docker.username}</username>
                           <password>${docker.password}</password>
                        </auth>
                     </to>
                  </configuration>
```

**Log output**:
Built and pushed image as ...

**Comment by raizoor** [comment]
@markusheiden 

If do you run jib:dockerBuild, the image exists locally?

**Comment by chanseokoh** [comment]
Never heard of Portus, but a brief search on it gives me that it is not technically a registry but like a frontend UI thing for some Docker registry behind it. And judging from what you said ("pulling those images from our self hosted registry is possible though"), I suspect the image is built and pushed successfully to the registry but there exists some issue with Portus integration and it's simply that the Portus frondend UI fails to show it. Seems like you need to file a bug against Portus too? BTW, what is the actual registry implementation behind Portus? Harbor?

**Comment by chanseokoh** [comment]
Hmm... I don't really think there's a problem with the order Jib is communicating with a registry when pushing. Although I think Portus should perhaps fix this, but can you identify how the order is different and why it breaks something?

**Comment by markusheiden** [comment]
No, sorry, the analysis has been some time ago. There has been no analysis why Portus can't handle the different event order. I will create an issue for Portus the and close this issue.
