### ISSUE TITLE
Implement close() or shutDown() on TlsFailoverHttpClient

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2111]
`TlsFailoverHttpClient` generates closeable `Response` instances. It can implement `close()` or `shutDown()` to close all `Response`s it generated.

**Comment by loosebazooka** [comment]
Is the expectation that the consumer of the response close it normally?

**Comment by chanseokoh** [comment]
Yeah, `Response` is a `Closeable` object, and the consumers are encouraged to close them as soon as they don't need it. In that sense, this is an added safety and convenience, but it also calls `HttpTransport.shutdown()`, which is a entirely new thing to Jib, so in that sense, it's a little bit more than that.

**Comment by chanseokoh** [comment]
*are encouraged to --> should
