### ISSUE TITLE
jibBuildTar create wrong OCI format tarbal

### ISSUE THREAD

**Issue by lfarkas** [GoogleContainerTools/jib#2124]
When run the jibBuildTar gradle target and the container.format='OCI' set the resulted jib-image.tar still not contains index.json. 

Per the OCI image spec, there must be an index.json file present in OCI format images: https://github.com/opencontainers/image-spec/blob/master/image-layout.md

**Comment by loosebazooka** [comment]
I don't think we've looked at this code path for a while. Is everything else okay when generating the tar? Is just the `index.json` missing?

**Comment by lfarkas** [comment]
I don't know. actually I'd like to docker/podman pull the image into my local images to be able to run locally with have to push to a registry and then found this bug (since currently that's the only way AFAIK). 
Anyway I'm also vote for this issue #1664 since than it solve all of such problems.

**Comment by chanseokoh** [comment]
I'd like to understand this a bit more.

> I don't know. actually I'd like to docker/podman pull the image into my local images to be able to run locally with have to push to a registry and then found this bug (since currently that's the only way AFAIK).

It makes sense for `jibBuildTar` to produce a tarball with the OCI format image layer, but are you aware that Docker CLI and daemon don't yet support loading (or saving) a tar, zip, or unpacked contents of the OCI image layout anyways? That is, if `jibBuildTar` created a tarball with the OCI image layout, you can no longer load it into the local Docker. I don't know about podman though.

And if you haven't noticed, `jibDockerBuild` will work fine with `container.format='OCI'`. The truth is, when it comes to the local Docker, it is neither OCI nor Docker Registry V2 manifest, so `container.format` doesn't play any role with `jibDockerBuild`. The local Docker just uses it's own legacy format.

> Anyway I'm also vote for this issue #1664 since than it solve all of such problems.

And to be clear, fixing #1664 won't address this issue. It's an independent issue concerning only the configuration syntax.

**Comment by lfarkas** [comment]
> I'd like to understand this a bit more.
> 
> > I don't know. actually I'd like to docker/podman pull the image into my local images to be able to run locally with have to push to a registry and then found this bug (since currently that's the only way AFAIK).
> 
> It makes sense for `jibBuildTar` to produce a tarball with the OCI format image layer, but are you aware that Docker CLI and daemon don't yet support loading (or saving) a tar, zip, or unpacked contents of the OCI image layout anyways? That is, if `jibBuildTar` created a tarball with the OCI image layout, you can no longer load it into the local Docker. I don't know about podman though.

I tried it with podman. what's more report it to podman and they point me to the standard. and after this i looked into the tarball which is in a wrong format.

> And if you haven't noticed, `jibDockerBuild` will work fine with `container.format='OCI'`. The truth is, when it comes to the local Docker, it is neither OCI nor Docker Registry V2 manifest, so `container.format` doesn't play any role with `jibDockerBuild`. The local Docker just uses it's own legacy format.

yes but in this case you can write a jibPodmanBuild which can work.

> > Anyway I'm also vote for this issue #1664 since than it solve all of such problems.
> 
> And to be clear, fixing #1664 won't address this issue. It's an independent issue concerning only the configuration syntax.

yes it's true, but in that case the user of this plugin can more easy usage and configuration eg: as you write oci-archive:// you shouldn't have to handle container.format='docker' etc...

**Comment by TadCordle** [comment]
Would you mind giving more details on how to reproduce the bug you're seeing? When I run `./gradlew jibBuildTar -Djib.container.format="OCI"`, then `podman load < build/jib-image.tar`, the image still loads and runs fine with `podman run`, most likely because it's still a valid docker tar. Is there a way to force podman into expecting an OCI tar?

**Comment by lfarkas** [comment]
try:
podman pull oci-archive:....../jib-image.tar

**Comment by lfarkas** [comment]
seems to working
