### ISSUE TITLE
Maven settings.xml auth matching

### ISSUE THREAD

**Issue by lionelfleury** [GoogleContainerTools/jib#2135]
**Environment**:

- *Jib version:* 1.7.0
- *Build tool:* maven 3.6.2
- *OS:* macOS and gitlab CI

**Description of the issue**:
Docker image tagging: `registry:port/image:version`
Maven expects `<server><id>` and `<repositories><repository><id>` to match.
https://maven.apache.org/settings.html
Problem is that jib expects to match exactly these with `repository:port` part of the docker image tagging.
Maven doesn't like the `:port` - `:` part - at all.

**Expected behavior**:
Matching the previous mentioned settings.xml file entry/key without `:port` part.
Not produce maven to output warning regarding special character... (see log output below)

**Steps to reproduce**:

  1. edit your ~/.m2/settings.xml file with desired and preferred registry `host:port` key. For server.id and registries.registry.id keys.
  2. run `mvn jib:build` or `mvn {any_goal}`
  3. 

**Log output**: 

```
[WARNING] Some problems were encountered while building the effective model for common:jar:HEAD-SNAPSHOT
[WARNING] 'repositories.repository.id' must not contain any of these characters \/:"<>|?* but found :
```

**Additional Information**: 

I suggest to relax the auth retrieval with maven to not use the `:port` part of the docker image tagging.
This can let the user chose whatever port the registry he/she wants to open.
Otherwise you have to put a double entry for server.id part only to please jib... meaning with the `:port` included.

**Comment by chanseokoh** [comment]
Thanks for filing this!

**Comment by lionelfleury** [comment]
Sure! ;)

**Comment by TadCordle** [comment]
@lionelfleury 2.0.0 has been released with a fix for this issue!
