### ISSUE TITLE
Base image 'openjdk:11-slim' does not use a specific image digest - build may not be reproducible

### ISSUE THREAD

**Issue by yerzhant** [GoogleContainerTools/jib#2143]
**Environment**:

- *Jib version:* 1.7.0
- *Build tool:* Gradle 5.6.2
- *OS:* Linux 5.0.0-32-generic amd64

**Description of the issue**:
Base image 'openjdk:11-slim' does not use a specific image digest - build may not be reproducible

**Expected behavior**:
No such message

**Steps to reproduce**:
  1. Add plugin:
`
id 'com.google.cloud.tools.jib' version '1.7.0'
`
  2. Add from image:
`
jib {
    from {
        image = 'openjdk:11-slim'
    }
...
`
  3. Run:
`
./gradlew jib
`

**Log output**:
```
./gradlew jib

> Task :jib

Containerizing application to yerzhant/nurbus-back, yerzhant/nurbus-back:1.6.0...
Base image 'openjdk:11-slim' does not use a specific image digest - build may not be reproducible
The base image requires auth. Trying again for openjdk:11-slim...
Using base image with digest: sha256:fb54ed3516242995d86c53346463a3509f9baf74a9178c066bdbcc5c1bdafc66

Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.nurbus.back.BackApplication]

Built and pushed image as yerzhant/nurbus-back, yerzhant/nurbus-back:1.6.0
Executing tasks:
[===========================   ] 90,0% complete
> launching layer pushers


BUILD SUCCESSFUL in 11s
3 actionable tasks: 1 executed, 2 up-to-date
```

**Comment by TadCordle** [comment]
This message shows up because the image at `openjdk:11-slim` may change between builds, leading to potentially different results using the same configuration. To get rid of the warning and ensure reproducible builds, you can specify a digest for the base image (which is reported in Jib's output).

```
jib {
  from {
    image = 'openjdk@sha256:fb54ed3516242995d86c53346463a3509f9baf74a9178c066bdbcc5c1bdafc66'
  }
}
```
