### ISSUE TITLE
Error if base image registry uses V2 Schema1

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2147]
A user in [gitter.im/google/jib](https://gitter.im/google/jib) reported

```
Caused by: com.google.cloud.tools.jib.image.LayerPropertyNotFoundException: Diff ID not available for digest-only layer
    at com.google.cloud.tools.jib.image.DigestOnlyLayer.getDiffId (DigestOnlyLayer.java:50)
    at com.google.cloud.tools.jib.builder.steps.PreparedLayer.getDiffId (PreparedLayer.java:93)
    at com.google.cloud.tools.jib.image.json.ImageToJsonTranslator.getContainerConfiguration (ImageToJsonTranslator.java:142)
    at com.google.cloud.tools.jib.builder.steps.PushContainerConfigurationStep.call (PushContainerConfigurationStep.java:63)
    at com.google.cloud.tools.jib.builder.steps.StepsRunner.lambda$pushContainerConfiguration$9 (StepsRunner.java:359)
    at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly (TrustedListenableFutureTask.java:125)
    at com.google.common.util.concurrent.InterruptibleTask.run (InterruptibleTask.java:69)
    at com.google.common.util.concurrent.TrustedListenableFutureTask.run (TrustedListenableFutureTask.java:78)
    at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:628)
    at java.lang.Thread.run (Thread.java:834)
```

The only place where `DigestOnlyLayer` is created is `ImageToJsonTranslator.toImage(V21ManifestTemplate)`, meaning it happens only when the registry returns (or returned once in the past if Jib uses a cached manifest) the legacy V2 Schema 1 manifest. Then the `toImage(V21ManifestTemplate)` is called only in `PullBaseImageStep`. (There are two call sites in it.)

The obvious workaround is to make the registry return V2.2 manifest or use a different registry that supports V2.2. (But if you have ever used `--offline` or referenced a base image with a digest (e.g., `sha256:xxx`, Jib may have cached V2.1 manifests locally at `$HOME/.cache/google-cloud-tools-java/jib/images` (on Linux), so you may have to delete the folder to clear cached V.2.1 manifests first.)

Note, V2 Schema1 manifest is deprecated in Docker: https://docs.docker.com/engine/release-notes/#19030
> Deprecate image manifest v2 schema1 in favor of v2 schema2. Future version of Docker will remove support for v2 schema1 althogether. moby/moby#39365

**Comment by chanseokoh** [comment]
But I cannot reproduce this. I've been testing this with `quay.io/tremolosecurity/myvirtualdirectory-base` (example from #1634), which still returns the old V2.1 manifest. I have no problem building using the base image, with or without `--offline`, whether the manifest is cached or not.

I think there's something more to this that triggers this error execution path.

**Comment by chanseokoh** [comment]
Actually, I can reproduce this. It always happens when pushing to a remote registry. (Previously, I was pushing to a local Docker daemon.)

Another workaround besides upgrading the registry to return a V2.2 manifest is to use the flag `-Djib.alwaysCacheBaseImage=true`. For example,

```
mvn -Djib.alwaysCacheBaseImage=true compile (or package if necessary) jib:build
```

However, this flag will always make Jib download the base image even if it doesn't have to, so this isn't ideal (particularly on CI/CD environment where Jib has to download the base image for every run).

**Comment by bjornmagnusson** [comment]
Apparently docker registry (docker distribution, registry:2) being used is only defaulting to v2.1 but supports v2.2 as well.

Using `docker manifest inspect` with recent Docker CLI a v2.2 manifest is returned.

However when using the REST API to query the manifest, a v2.1 manifest is returned unless the header `Accept: application/vnd.docker.distribution.manifest.v2+json` is sent.

Without Accept header
```
curl -sSL <docker-registry>/v2/REDACTED/manifests/REDACTED | jq .schemaVersion
1
```
With header
```
curl -sSL -H "Accept: application/vnd.docker.distribution.manifest.v2+json" <docker-registry>/v2/REDACTED/manifests/REDACTED | jq .schemaVersion
2
```

**Comment by chanseokoh** [comment]
> However when using the REST API to query the manifest, a v2.1 manifest is returned unless the header `Accept: application/vnd.docker.distribution.manifest.v2+json` is sent.

Yes, you should set the `Accept` header to let the registry know what you can handle. You may also consider accepting an OCI manifest (`application/vnd.oci.image.manifest.v1+json`), Docker manifest list (`application/vnd.docker.distribution.manifest.list.v2+json`), or an OCI index (`application/vnd.oci.image.index.v1+json`).

And given that Docker currently displays a conspicuous deprecate notice for v2.1, we probably won't work on this issue. I guess you have no problem using v2.2?

```
# quay.io still defaults to v2.1
$ docker push quay.io/...
The push refers to repository [quay.io/...]
...
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
```

**Comment by bjornmagnusson** [comment]
I still consider this an issue in Jib, as we do not have any issues like this when using Docker CLI to pull or push.
The issue with quay is a bit different issue, as we can easily push v2.2 manifests.

Is there (or will there be) a way in jib to enforce the use of v.2.2?

From initial investigations (from https://docs.docker.com/registry/configuration/) there are no way to configure Docker Distribution to default to return v2.2 manifest.

**Comment by chanseokoh** [comment]
There's something missing here. Jib always pushes v2.2. It also explicitly requests v2.2 for pulling a base image. And the "Docker Distribution" (if you are talking about `docker run -p 5000:5000 registry:2`) does return v2.2 for the base image when Jib requests. It has been working fine for years.

```
$ cd /tmp
$ docker pull openjdk:11-jre-slim
$ docker tag openjdk:11-jre-slim localhost:5000/openjdk
$ docker run -d -p5000:5000 registry:2
8df9394f86736edf6300933c78fe9ac97a11f699d4dd85e5857849e07481da46

$ docker push localhost:5000/openjdk
The push refers to repository [localhost:5000/openjdk]
...
$ git clone https://github.com/GoogleContainerTools/jib.git
$ cd jib/examples/helloworld/

$ mvn compile -Djib.from.image=localhost:5000/openjdk -Djib.to.image=localhost:5000/test -Djib.allowInsecureRegistries=true jib:build
...
[INFO] Built and pushed image as localhost:5000/test
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...

# Subsequent runs succeed as well.
$ mvn compile -Djib.from.image=localhost:5000/openjdk -Djib.to.image=localhost:5000/test -Djib.allowInsecureRegistries=true jib:build
```

What are the exact steps you are doing, what is the problem, and what log are you seeing?

**Comment by zalym** [comment]
I am seeing the same issue when running from bitbucket pipelines.  I do not have any issues running it from my local machine, and am able to push it to AWS ECR.  But from bitbucket, I get this error.

Registry may not support pushing OCI Manifest or Docker Image Manifest Version 2, Schema 2 

This is my bitbucket pipeline

`image: openjdk:11.0.7-slim
pipelines:
  default:
    - step:
        name: Get AWS Token
        image: python:3.6-alpine
        script:
          - pip install awscli
          - >-
            mkdir -p ~/.aws/ 
            && echo "[default]" > ~/.aws/credentials
            && echo -n "aws_access_key_id = " >> ~/.aws/credentials
            && echo $AWS_ACCESS_KEY_ID >> ~/.aws/credentials
            && echo -n "aws_secret_access_key = " >> ~/.aws/credentials
            && echo $AWS_SECRET_ACCESS_KEY >> ~/.aws/credentials 
            && cat ~/.aws/credentials
          - echo "export AWS_TOKEN=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)" > set_env.sh
        artifacts:
          - set_env.sh
    - step:
        name: Build n Deploy Project
        caches:
          - gradle
        script:
          - cat set_env.sh 
          - source set_env.sh
          - echo $AWS_TOKEN
          - bash ./gradlew clean build -x test
          - bash ./gradlew  -PawsEcrToken="$AWS_TOKEN" jib --image=$AWS_ECR_ROOT_URL`

**Comment by chanseokoh** [comment]
Hi @zalym,

Your issue is a different one. Could you open a new issue with more details with `./gradlew --debug`? I believe you'll also see the JSON response body from the server following the error message.

**Comment by zalym** [comment]
I changed my pipeline and hence didnt pursue this.  But the above yaml is good enough to recreate it

**Comment by chanseokoh** [comment]
@zalym the last time I checked, I didn't have any problem pushing to AWS ECR. Not to mention there are a lot of users using AWS. I think something particular about your environment or setup is causing a failure.

In any case, your issue is different from this issue, so if you would like us to investigate, please open a new issue and help us get more information.

**Comment by chanseokoh** [comment]
V2 Schema 1 was already dead when the issue was opened. It's now 2021, and it's certain that we won't do any work related to V2 Schema 1. And as explained in https://github.com/GoogleContainerTools/jib/issues/2147#issuecomment-558216506, there's no issue with Jib.
