### ISSUE TITLE
How can I change the UID

### ISSUE THREAD

**Issue by tobias-neubert** [GoogleContainerTools/jib#2159]
I want to execute my docker container as a non root user and set the UID to 1001. But now, whatever I put into the container.user field, the container will run as user 1001. I am not able to change that Id anymore. Are there some layers cached and not refreshed? Or is this intended behaviour? My pom.xml looks like this:

```
<plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>jib-maven-plugin</artifactId>
        <version>1.8.0</version>
        <configuration>
          <from>
            <image>docker.tobias.io/lab/openjdk:11.0.5</image>
            <auth>
              <username>${artifactory.username}</username>
              <password>${artifactory.password}</password>
            </auth>
          </from>
          <to>
            <image>docker.tobias.io/lab/${project.name}:${version.number}</image>
            <auth>
              <username>${artifactory.username}</username>
              <password>${artifactory.password}</password>
            </auth>
          </to>
          <container>
            <user>1002</user>
          </container>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
</plugin>
```

**Comment by tobias-neubert** [comment]
By the way: I made a mvn clean to delete the local jib cache folder in the target folder and a docker system prune -a to remove everything from my docker installation. But that does not help either.

**Comment by briandealwis** [comment]
Hi @tobias-neubert.  We have number of tests around this functionality.  And I just tried setting a user on a simple project and it is executed on the specified user

My guess is that you are not running the actual image that you built.  If you are building to a registry  (`jib:build`) then you can ensure you're running your built image by running something like:
```
docker run <your image>@$(cat target/jib-image.digest)
```

Docker will pull the image if it is not cached locally.

Once you've pulled down that built image, you can use `docker` and `jq` to determine the default user configured for an image that will be used for execution:
```
docker inspect $(cat target/jib-image.id) | jq '.[].Config.User'
```

**Comment by chanseokoh** [comment]
Looks like this is working, and I am pretty sure it is. If it's not for whatever reason, please re-open the issue with some more details. You may not be running an actual image or the runtime may be overriding the configured user.

**Comment by tobias-neubert** [comment]
Oh damn, you were absolutely right: It was in the docker-compose.yml :-)
