### ISSUE TITLE
Images are not listed in Repo when pushed with jib

### ISSUE THREAD

**Issue by Bean900** [GoogleContainerTools/jib#2161]
**Environment**:

- *Jib version:* 1.8.0
- *Build tool:* Maven
- *OS:* Win10

**Description of the issue**:
When the `mvn clean compile jib:build` is executed in the current project, a dockerfile is built and pushed into AWS ECR successfully.
When executing `docker images <repo>`, the pushed image is not listet!
However, if I run `docker run <repo>:<tag>` on the pushed image, it can be downloaded and started. If I load the, already locally built image, over `docker push` with a different tag in ecr, it appears when i execute `docker images <repo>`

**Expected behavior**:
The image that was pushed to ecr using jib should appear when `docker images <repo>` is executed and should not be invisible.

**Steps to reproduce**:

Execute `mvn clean compile jib:build` in project dir
Run `docker images <ID>.dkr.ecr.eu-west-1.amazonaws.com/<IMAGE>`
The pushed image with the corresponding tag should not be listed
Run `docker run <ID>.dkr.ecr.eu-west-1.amazonaws.com/<IMAGE>:<SET_TAG>`
See that the image is in the repo and can be downloaded

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.7.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>accessing-data-mysql</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>accessing-data-mysql</name>
    <description>Demo project for Spring Boot</description>

    <properties>
        <java.version>1.8</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>1.8.0</version>
                <configuration>
                    <to>
                        <image>DELETED.dkr.ecr.eu-west-1.amazonaws.com/DELETED
                        </image>
                        <tags>
                            <tag>test2</tag>
                            <tag>latest</tag>
                        </tags>
                    </to>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>

```

**Log output**: 
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------< com.example:accessing-data-mysql >------------------
[INFO] Building accessing-data-mysql 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:3.1.0:clean (default-clean) @ accessing-data-mysql ---
[INFO] Deleting <DELETED>\workspace\helloworld\target
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ accessing-data-mysql ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ accessing-data-mysql ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 4 source files to <DELETED>\workspace\helloworld\target\classes
[INFO]
[INFO] --- jib-maven-plugin:1.8.0:build (default-cli) @ accessing-data-mysql ---
[INFO]
[INFO] Containerizing application to <DELETED>.dkr.ecr.eu-west-1.amazonaws.com/<DELETED>, <DELETED>.dkr.ecr.eu-west-1.amazonaws.com/<DELETED>:test2, <DELETED>.dkr.ecr.eu-west-1.amazonaws.com
/<DELETED>...
[WARNING] Base image 'gcr.io/distroless/java:8' does not use a specific image digest - build may not be reproducible
[INFO] Using base image with digest: sha256:<DELETED>
[INFO]
[INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.example.accessingdatamysql.AccessingDataMysqlApplication]
[INFO]
[INFO] Built and pushed image as <DELETED>.dkr.ecr.eu-west-1.amazonaws.com/<DELETED>, <DELETED>.dkr.ecr.eu-west-1.amazonaws.com/<DELETED>:test2, <DELETED>.dkr.ecr.eu-west-1.amazonaws.com/<DELETED>
[INFO] Executing tasks:
[INFO] [===========================   ] 90,0% complete
[INFO] > launching layer pushers
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.388 s
[INFO] Finished at: 2019-11-19T11:33:28+01:00
[INFO] ------------------------------------------------------------------------

**Comment by loosebazooka** [comment]
If you want to build to a local docker daemon, try using `jib:dockerBuild`

**Comment by Bean900** [comment]
In my Use Case I want, that the application is built without docker on a Jenkins and then loaded into the Amazon Elastic Container Registry (ecr).
By playing around I have now found out that the images are listed when they are pushed from jib to ecr. But only if they have already been started once.

**Comment by briandealwis** [comment]
Docker pulls images from a remote registry into a local cache.  You can see the list of images cached by your daemon with `docker images`.

`docker images <repo>` reports on the images in your cache that were pulled from that repository.  It doesn't actually list the images *on* the remote repository.

`docker run <image>` will pull the image *if* it doesn't already exist locally.

**Comment by chanseokoh** [comment]
> When executing `docker images <repo>`, the pushed image is not listet!

Yes, this is expected and how Docker works. The `docker images` command only lists the images cached locally in the Docker daemon. (And the locally cached image are often out of sync with the images on a remote registry.)

**Comment by Bean900** [comment]
Thanks, I did not know that.
