### ISSUE TITLE
unable to push to enterprise quay registry

### ISSUE THREAD

**Issue by aditya86c** [GoogleContainerTools/jib#2163]
**Environment**:

- *Jib version:*1.8.0
- *Build tool:* 
- *OS:* windows 10

**Description of the issue**:
Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.0.0:build (default-cli) on project dna-routeplan-execution: Tried to push image manifest for registry.ford.com/abhagava/dna-service-routeplan-executor:0.0.1 but failed because: Registry may no
t support Image Manifest Version 2, Schema 2 | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new: 415 UNSUPPORTED MEDIA TYPE
[ERROR] {"errors":[{"code":"MANIFEST_INVALID","detail":{"message":"manifest schema version not supported"},"message":"manifest invalid"}]}

**Expected behavior**:

**Steps to reproduce**:

  1. 
  2. 
  3. 

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @aditya86c, please see https://github.com/GoogleContainerTools/jib/issues/500#issuecomment-520077378. Note that Docker deprecated Manifest V2 Schema 1. For a private Quay repo, there may be a way to configure Quay to use V2 Scheme 2 by default. For a public Quay repo, you can ask Red hat to whitelist your namespace to start using V2.2.
