### ISSUE TITLE
Use specific 'gcr.io/distroless/java' image digest.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#217]
To ensure reproducibility at the plugin version level, each plugin version should be tied to a specific release of the default `gcr.io/distroless/java` image.

For example, the current latest digest is [`@sha256:6af3b801e2beef75307d1eb683e2da792357cacb675a60c10ede16481d2cea741`](https://pantheon.corp.google.com/gcr/images/distroless/GLOBAL/java@sha256:6af3b801e2beef75307d1eb683e2da792357cacb675a60c10ede16481d2cea74/details/info).

**Comment by patflynn** [comment]
Hmm, is that what Bazel rule does?  I'm thinking that most of the time people want the latest updates.  It might make sense to add a digest field to the config and make it required if reproducible builds is enabled..

The way I can imagine this working for people is that their master or dev branch is also at head in terms of the latest up-to-date distroless image, while their release branches are set to reproducible with the digest explicitly specified in the config.

**Comment by coollog** [comment]
Yea, the Bazel rules_docker [defines specific digests to use for each image](https://github.com/bazelbuild/rules_docker/blob/3caddbe7f75fde6afb2e2c63654b5bbeeeedf2ac/java/java.bzl). The image doesn't seem to actually change much, since this digest that is being used is from back in January and there has been [6 new `gcr.io/distroless/java` images](gcr.io/distroless/java) since then.

The digest field is currently part of the `from` field. It might be confusing if they specified a `from` image with a specific tag and then a separate `digest` field replaces that tag with a digest. It does make sense to have release branches use reproducible with a specific digest that is independent of the plugin version though.
