### ISSUE TITLE
How to push image to private registry

### ISSUE THREAD

**Issue by HsiangSun** [GoogleContainerTools/jib#2179]
> I have pushed an image to docker.io successfully，but I want to know how to push the image to my private registry？. I have searched for a lot of answers on the internet, but not work. Thank you for reply！

**Comment by raizoor** [comment]
@HsiangSun 

What exactly is your problem? 
What error have you get?
What private registry have you using?

It isn't cleary what do you want to know =/

Thanks...

**Comment by cricket007** [comment]
You can tag the image with your repo  `my.registry/image:tag`, then have that be the image that is pushed.

**Comment by chanseokoh** [comment]
Hi @HsiangSun,

Say you have a local registry running at `localhost:5000`, `my.private.registry:6000`, or `some.secure.server:443`. Then you'd name your image like `localhost:5000/some/repo/name:some-tag`, `my.private.registry:6000/some/name:tag`, `some.secure.server/repo`, etc. Then `mvn jib:build` will push the image to the registry.
