### ISSUE TITLE
Add FAQ entry for configuring SOURCE_DATE_EPOCH

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#2197]
This can maybe configured by the user with timestamp settings.

we might need to provide support for milliseconds.

https://reproducible-builds.org/specs/source-date-epoch/

**Comment by chanseokoh** [comment]
Reading this again, it's not clear what we intended. Is it an FAQ explaining how to make Maven or other tools to generate files with a desired timestamp without changing the local machine time? Or is it that Jib should also honor `SOURCE_DATE_EPOCH`? If so, for the image creation time or files in an image?

**Comment by alicejli** [comment]
Closing as there has not been any feedback on this request for several years and it's unclear what the desired outcome is.

**Comment by christf** [comment]
The intent is to achieve a situation where 2 different builds that happen at a different time will result in docker Images having the identical hash. For this to work, the mtime of each file in the image must be set to SOURCE_DATE_EPOCH
