### ISSUE TITLE
Local docker daemon support for .dockerignore when using jibDockerBuild 

### ISSUE THREAD

**Issue by reevesm** [GoogleContainerTools/jib#2198]
**Environment**:

- *Jib version:* 1.8.0
- *Build tool:* Gradle 5.6.2
- *OS:* macOS Mojave

**Description of the issue**:

Docker CLI behavior excluding files and directories in .dockerignore:

> Before the docker CLI sends the context to the docker daemon, it looks for a file named .dockerignore in the root directory of the context. If this file exists, the CLI modifies the context to exclude files and directories that match patterns in it. This helps to avoid unnecessarily sending large or sensitive files and directories to the daemon and potentially adding them to images using ADD or COPY.

The FAQ suggests using jibDockerBuild to build directly to local Docker daemon

> jibDockerBuild for Gradle to build directly to your local Docker daemon.

**Expected behavior**:
Expecting files in the .dockerignore file (located at the root folder of the project) to not be included in the docker image. 

Alternatively, it would be nice to offer an option for excluding files when configuring jib.

**Steps to reproduce**:

  1.  Set up build.gradle
  2.  create somefile.text in root project folder
  2. create .dockerignore
```
somefile.txt
```
  3.  Run `gradle jibDockerBuild`

**`jib-gradle-plugin` Configuration**: 
```groovy
jib.to.image = "test-image"
jib.from.image = 'gcr.io/distroless/java:11'
```

**Additional Information**: 
Using dive to inspect the image includes files which should have been ignored.

**Comment by loosebazooka** [comment]
Can you provide an example of what kind of file you're trying to ignore? `.dockerignore` makes sense in the docker context because it sends *everything* in the working directory over to the daemon. But during a jib build, jib only adds specific files to the final image based on configuration. Perhaps there is something you can add to your configuration to achieve the same result

**Comment by reevesm** [comment]
Sure. Good points. I lost some context trying to simplify the steps to reproduce.  

I specifically want to ignore a properties file in the resources folder of a kotlin application.

**Comment by loosebazooka** [comment]
Is there a reason why ignoring it at the gradle level is not sufficient?

```
sourceSets {
    main {
        resources {
            exclude 'path/to/my/properties.properties'
        }
    }
}
```

**Comment by reevesm** [comment]
That works for me.  Thanks for the help.

**Comment by Ale94** [comment]
@loosebazooka regarding exclude from main or processResources (when I want to exclude application.properties) this will make other gradle tasks impossible to run: e.g bootRun. 
Is there any way of excluding a file only in the jib task?

**Comment by chanseokoh** [comment]
@gataela one option is to use the [layer-filter extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-gradle).

**Comment by gataela** [comment]
@chanseokoh life saver, thank you!  :)
