### ISSUE TITLE
Generate a dockerFile for projects using jib build

### ISSUE THREAD

**Issue by luvtk** [GoogleContainerTools/jib#2199]
**Environment**:

- *Jib version:*  1.0.2
- *Build tool:* Maven 3.3.9
- *OS:*  Windows 10

**Description of the issue**: Is there any possibilities that **Jib** could generate a **dockerFile**  after *Jib build*? For I wanna make my own dockerFile or even make some customized stuff,

**Expected behavior**: to generate a dockerFile for those using jib

**Comment by loosebazooka** [comment]
Jib no longer has a feature to create a docker file. But you can do this on your own, see https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-would-a-dockerfile-for-a-jib-built-image-look-like

**Comment by loosebazooka** [comment]
It might be helpful to describe the kind of customizations you want, perhaps we can do those in jib without resorting to docker files.

**Comment by luvtk** [comment]
> It might be helpful to describe the kind of customizations you want, perhaps we can do those in jib without resorting to docker files.

At least there are something not clear using **Jib**, for I wanna know clearly what it actually did after *Jib build*, and yes, **Jib** is a great tool to make my app into a image and push to some registries if  configured well, I would still focus on **Jib** as well, thank you for your reply

**Comment by loosebazooka** [comment]
@luvtk there are some things that might be helpful for you:
- There are tools that help you inspect the container image, like dive: https://github.com/wagoodman/dive
-  Understanding the container image format is extremely helpful as well: https://containers.gitbook.io/build-containers-the-hard-way/

**Comment by luvtk** [comment]
> @luvtk there are some things that might be helpful for you:
> 
> * There are tools that help you inspect the container image, like dive: https://github.com/wagoodman/dive
> * Understanding the container image format is extremely helpful as well: https://containers.gitbook.io/build-containers-the-hard-way/

Thank you! That's very nice of you, I am new on **devops** but old on Java web development
