### ISSUE TITLE
Unrecognized option: -Xmy:flag=jib-rules Error: Could not create the Java Virtual Machine. Error: A fatal exception has occurred. Program will exit.

### ISSUE THREAD

**Issue by hhofchina** [GoogleContainerTools/jib#2205]
**Environment**:
<jvmFlag>-Xmy:flag=jib-rules</jvmFlag>
- *Jib version:* 
- *Build tool:* 
- *OS:* 

**Description of the issue**:

**Expected behavior**:

**Steps to reproduce**:

  1. 
  2. 
  3. 

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Do not pass `-Xmy:flag=jib-rules` to JVM. It's an invalid flag.

```
chanseok@chanseok3:~$ java -Xmy:flag=jib-rules
Unrecognized option: -Xmy:flag=jib-rules
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
chanseok@chanseok3:~$ java -invalid-flag
Unrecognized option: -invalid-flag
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
chanseok@chanseok3:~$ 
```

**Comment by crimsonvspurple** [comment]
Hi @chanseokoh . I recommend renaming that flag to something _more_ obvious that it is an example flag. I'm new to Jib (amazing stuff 🙇 ) and I thought it is some custom jib related `rules`. 😳

**Comment by chanseokoh** [comment]
Will update the example.
