### ISSUE TITLE
Change cache location on Mac/Windows

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#2216]
Currently, the base image cache is located at:
* Mac: `$HOME/Library/Application Support/google-cloud-tools-java/jib/`
* Win: `%LOCALAPPDATA/google-cloud-tools-java/jib/`

It may be a good idea to change these to:
* Mac: `$HOME/Library/Caches/Google/Jib/`
* Win: `%LOCALAPPDATA/Google/Jib/Cache/`

We may need to come up with a migration strategy so we don't break users who rely heavily on the cache (e.g. offline users).

Checklist:
- [x] Code (#2218)
- [x] Docs (#2231)

**Comment by briandealwis** [comment]
The Win cache should be in `%LOCALAPPDATA%/Google/Jib/Cache` just to be clear that it can be removed without affecting other possible configuration files.

**Comment by chanseokoh** [comment]
> We may need to come up with a migration strategy so we don't break users who rely heavily on the cache (e.g. offline users).

I'm leaning toward documentation rather than adding code to do automatic migration for a number of reasons.

**Comment by TadCordle** [comment]
Gonna reopen this until the documentation is updated

**Comment by chanseokoh** [comment]
Alos, does it make sense to update CHANGELOG to describe the changes to the base image cache directory on some platforms by #2218?

**Comment by TadCordle** [comment]
Oh right, was gonna do that but forgot.
