### ISSUE TITLE
The extraDirectories copied the file in the wrong place for image

### ISSUE THREAD

**Issue by TuringZhai** [GoogleContainerTools/jib#2221]
**Environment**:

- *Jib version: 1.8.0* 
- *Build tool: Maven* 
- *OS:  linux aarch64* 

**Description of the issue**:

copy *.so file to image's '/usr/lib/aarch64-linux-gnu/' directory, but always in the directory '/'
![image](https://user-images.githubusercontent.com/11326721/71945991-4e68c080-3203-11ea-8d57-8378df6a95c4.png)

**Expected behavior**:

**Steps to reproduce**:

  1. 
  2. 
  3. 

**`jib-maven-plugin` Configuration**: 
```

  <extraDirectories>
                        <paths>
                            <path>src/main/resources/lib/arm64_tf1.10_so</path>
                            <path>/usr/lib/aarch64-linux-gnu/</path>
                        </paths>
 </extraDirectories>


```

**Log output**: 

**Additional Information**:

**Comment by TuringZhai** [comment]
![image](https://user-images.githubusercontent.com/11326721/71945991-4e68c080-3203-11ea-8d57-8378df6a95c4.png)

**Comment by chanseokoh** [comment]
Hi,

This is working as designed. It's just that your usage is not correct. You are specifying *two* extra directories, one of which is `/usr/lib/aarch64-linux-gnu/`. That is, you are copying your *local* files under `/usr/lib/aarch64-linux-gnu/` into the root directory in the image; `/usr/lib/aarch64-linux-gnu/` is not a destination directory but an additional extra directory. The destination directory in the image is always `/`.

So for now, you have to prepare the right directory hierarchy in the configured extra directories. Please see https://stackoverflow.com/a/58661938/1701388 and #1581 to understand how the extra directories feature work.
