### ISSUE TITLE
Project using war plugin always deploys as war for spring boot application instead embedded server.

### ISSUE THREAD

**Issue by bs-git** [GoogleContainerTools/jib#2229]
**Description of the issue**:
This is not a bug report, but a improvement request:

It seems there is no way to favor/configure jib to prefer "plain" Spring Boot with embedded server as soon the War plugin is applied to the project.  On my project the war plugin is needed for a separate tomcat deployment, but it also influences the jib and there is no way to deploy as plain spring boot application any more.

**Expected behavior**:
I would like to configure jib to deploy a standard (spring boot) application instead of a war even if the war plugin is applied for the project. The "magic" applied by jib once the war plugin is present can not be influenced, even if is not wanted and needed for a spring boot application. 

jib {
   deploymentType='web'|'standalone'  -> using web server or plain main
...

**Comment by chanseokoh** [comment]
How about applying the WAR plugin only when needed? https://stackoverflow.com/a/49739351/1701388

I also tried the following, and it works.
```gradle
if (project.hasProperty('tomcatDeploy')) {
      apply plugin: 'war'
}
```

**Comment by loosebazooka** [comment]
It looks like what you want is two separate build profiles.
1. a `tomcat` build that applies the war plugin.
1. a `jib` build that does not.

so maybe your build needs to be something like:
build.gradle
```
if (project.hasProperty('doWar')) {
  apply plugin: 'war'
}
```
to conditionally apply war when you want it:
```
$ ./gradlew -PdoWar build
```
and when you don't
```
$ ./gradlew jib
```

or something like that

**Comment by loosebazooka** [comment]
ooh oops, race condition...

**Comment by bs-git** [comment]
Thank you for your suggestion, I ended up removing the war plugin completely and using a custom jar task. The plugin is quiet "demanding" how a project is structured or plugins are applied automatically - but this is something I am happy to work around in exchange for what this powerful features this plugin provides! If you like feedback from your users, I would hope for a separate task type from which I could create custom jib tasks - but with a litte adjustments on my project your plugin is great as it is.
