### ISSUE TITLE
latest tag should not be pushed automatically if user specify the jib.to.tags property

### ISSUE THREAD

**Issue by ylvmw** [GoogleContainerTools/jib#2237]
**Environment**:

- *Jib version:* 1.8.0
- *Build tool:* Maven 3.5.4
- *OS:* MacOS

**Description of the issue**:
Jib will always push the "latest" tag automatically even if the user specify the "jib.to.tags" property

**Expected behavior**:
a. If the "jib.to.tags" property is specified, Jib only push the tags in the "jib.to.tags" list
b. if the "jib.to.tags" not specified, Jib push the "latest" tag

**Steps to reproduce**:

  1. Configure the project jib plulgin as below
  2. Run "mvn clean compile jib:build -Djib.to.tags=test" under the project
  3. Check the docker registry to see if only the "test tag" is pushed

**`jib-maven-plugin` Configuration**: 
```xml
<build>
    <plugins>
        <plugin>
            <groupId>com.google.cloud.tools</groupId>
            <artifactId>jib-maven-plugin</artifactId>
            <version>1.8.0</version>
            <configuration>
                <to>
                    <image>my_repo/my_image</image>
                </to>
            </configuration>
        </plugin>
    </plugins>
</build>
```

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @ylvmw,

Don't use `to.tags`. Instead, have `<to><image>my-repo/my-image:test</image></to>`. If you don't specify a tag in the image reference, `latest` is assumed like what Docker does.

**Comment by voznenkoD** [comment]
The problem I think is different, and still persists. Because latest tag is still created even if no tag is passed, which is annoying and stops from branch/main approach of tagging.

**Comment by chanseokoh** [comment]
@voznenkoD but Jib is following the industry convention. If you do `docker push example.com/your-image`, the registry will have it as `example.com/your-image:latest`. And in all `docker` commands, if you don't specify a tag, `:latest` is implied.

**Comment by chanseokoh** [comment]
> Because latest tag is still created even if ~no~tag is passed

Oh, just realized you edited your comment. Our `to.tags` config actually means additional tags. (Yeah, bad naming, and we regret this naming choice, since a lot of people hit this issue.) So, if you want to push an image with a tag but without `:latest`, you should set the tag in the `<to><image>` like `<to><image>my-repo/my-image:my-tag</image></to>`.
