### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by iocanel** [GoogleContainerTools/jib#2238]
Now, that master is using `google-http-client` which does contain an important fix for us, would it be too much to ask for a new release?

Thanks in advance!

**Comment by TadCordle** [comment]
Thanks for being patient. We're working on finishing up a couple features that we want to get into the next release, so we're aiming to release this week when those are ready.

**Comment by TadCordle** [comment]
Going to close this, will be sure to leave an update here once there's a new release :)

**Comment by timpeeters** [comment]
New release available. :dancer:

**Comment by iocanel** [comment]
Thank you very much!
