### ISSUE TITLE
Improve Checkstyle

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#2272]
Upgrade checkstyle to 8.29

Also fix all these checkstyle violations (currently suppressed in `config/checkstyle/checkstyle-suppressions.xml`)

- [ ] VariableDeclarationUsageDistance
- [x] MissingJavadocMethod
- [x] SummaryJavadoc
- [x] MemberName
- [x] ~~OverloadMethodsDeclarationOrder~~ Moved to ignore (#2293)
- [x] JavadocParagraph
- [x] AbbreviationAsWordInName
- [x] EmptyBlock
- [x] WhitespaceAround
- [x] EmptyLineSeparator
- [x] EmptyCatchBlock
- [x] MultipleVariableDeclarations
- [x] AtclauseOrder
- [x] ArrayTypeStyle
- [x] MissingSwitchDefault
- [x] NonEmptyAtclauseDescription
- [x] MethodName

**Comment by mpeddada1** [comment]
@appu can this be closed?

**Comment by loosebazooka** [comment]
Yeah sure. I think we did our job for now
