### ISSUE TITLE
Do not override jar task's classifier if bootJar task does not interfere in Gradle

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2278]
In [#2178](https://github.com/GoogleContainerTools/jib/commit/a692b8b0cde1f982f6e28309dd08ca80460950e2#diff-aef8bf567c91df6622aa0ea29ed0c682R192), we overrode the `archiveClassifier` (`classifier` is deprecated) of the `jar` task, because by default both the `jar` and `bootJar` tasks write their respective JAR to the same location (`build/<name>.jar`). However, if `bootJar` is configured to write its fat JAR to a different location, there's no need to rename the original JAR generated by the `jar` task.

@ewirch

**Comment by ewirch** [comment]
> Basically, if the classifier or archiveClassifier of bootJar is set, then make Jib not set the classifier of the jar task.

That would do the trick.

But, wouldn't it be cleaner to create a new 'jar' task, exclusively for jib? Then you wouldn't need to mess with the default 'jar' task.

**Comment by chanseokoh** [comment]
> create a new 'jar' task, exclusively for jib

Looks like it's not easy to clone the `jar` task that guarantees to create the exact same jar file as the `jar` task will produce.

That said, I have refined the logic to be more conservative like this:

- If both `bootJar` and jar` are enabled and their jar locations conflict, throw an error. This is really like a misconfiguration that the user needs to address.
- Set the classifier of `jar` to `original` only when all the followings are true.
  1. `jar` is *disabled*.
  2. `bootJar` is *enabled*.
  3. Their jar locations conflict.

**Comment by chanseokoh** [comment]
@ewirch we've release Jib 2.1.0 with this change. You may want to take a spin.
