### ISSUE TITLE
Warning from empty global Jib config

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2294]
I first observed this in this [log](https://github.com/GoogleContainerTools/jib/pull/2264#issuecomment-583288030).

I also hit this on Windows:
```
[WARNING] Failed to read global Jib config: No content to map due to end-of-input
 at [Source: (sun.nio.ch.ChannelInputStream); line: 1, column: 0]; you may need to fix or delete C:\Users\chanseok\AppData\Local\Google\Jib\Config\config.json;
```
The code for this is in [`UpdateChcker.java`](https://github.com/GoogleContainerTools/jib/blob/master/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/UpdateChecker.java#L116).

In my case, the config file (`config.json`) is empty (0-byte). I think it's easy to generate an empty file.

First, we need to understand when and why we may create an empty file. ~~And if it seems not possible to prevent that, we should find a way to suppress this warning.~~ Turns out, we never intended to create an empty file and doing so is a bug that wipes out the values set by the user. We should never let this happen.

**Comment by loosebazooka** [comment]
consider swapping the error message around to make the location of the config file more prominent

**Comment by chanseokoh** [comment]
I realized just opening an `OutputStream` creates an empty file. The following code creates an empty `/tmp/foo` by the time the control reaches line 2:
```java
    1: OutputStream os = Files.newOutputStream(Paths.get("/tmp/foo"));
    2: Thread.sleep(30000);
    3: os.toString();
```

So we can actually simulate this issue with
```java
        try (OutputStream outputStream = Files.newOutputStream(configFile)) {
          if (true) while (true) try { Thread.sleep(30000); } catch (InterruptedException e) {}
          JsonTemplateMapper.writeTo(config, outputStream);
```

**Comment by briandealwis** [comment]
Oh!  I wonder if something odd could happen if you ran two jib instances simultaneously?

**Comment by chanseokoh** [comment]
We've seen this at least two times. Maybe we should create a `config.json.tmp` file in the same directory and rename to avoid accidental truncating.

**Comment by alkoclick** [comment]
We have recently started observing this exception and I think it's because we use parallel gradle building

> Oh! I wonder if something odd could happen if you ran two jib instances simultaneously?

Well... :laughing:

**Comment by loosebazooka** [comment]
@alkoclick Is this happening on a CI?

**Comment by loosebazooka** [comment]
Also, are you using `--parallel`

**Comment by chanseokoh** [comment]
This is a [real possibility](https://github.com/GoogleContainerTools/jib/issues/2294#issuecomment-586014889), and we've observed this issue multiple times. We should fix this.

**Comment by alkoclick** [comment]
Indeed using `--parallel`, this is on CircleCI

**Comment by loosebazooka** [comment]
@alkoclick just FYI the error message is harmless, and wont even surface on 2.1.0 (because of #2295), but we're still fixing the underlying file creation issue.

**Comment by alkoclick** [comment]
Well, we're getting failing builds in gradle when this shows up :/ Correlation, causation and all that jazz. We actually have the bump to 2.1.0 scheduled for later in the week (with minimal impact), do you want us to update and test there, or stay and test on 2.0?

**Comment by loosebazooka** [comment]
Oh maybe we're using the wrong log level?

**Comment by loosebazooka** [comment]
I would move to 2.1 at least to get some build stability. We already know the issue :) but thanks for offering.
