### ISSUE TITLE
jib.to.image push to multiple repositories

### ISSUE THREAD

**Issue by Bwvolleyball** [GoogleContainerTools/jib#2299]
**Environment**:

- *Jib version:* 1.1.2
- *Build tool:* Gradle v1.1.2
- *OS:* MacOS

**Description of the issue**:

Seeking a way to push the _same_ image to multiple image repositories.  We have a need  where we need to host our images in both DockerHub and ECR, the documentation doesn't make any reference to if this is possible.
If it is in-fact possible, if someone can explain it here, I'd be happy to help update the documentation for the gradle plugin as needed.

**Expected behavior**:

Allow a means to specify multiple `jib.to.image` values, such as via a comma separated list, with the expectation that each image provided will be pushed to the correct docker respository.

**Steps to reproduce**:

  1. Create a container repo on dockerhub and ECR
  2. Try to push one docker container to both repo's in one build.

**`jib-gradle-plugin` Configuration**: 
```groovy
jib {
	to {
		tags ['latest', 'develop']
		// one possibility:
                image "organization/repo, id.dkr.ecr.us-west-2.amazonaws.com/repo"
		// second possibility:
		image ['organization/repo', 'id.dkr.ecr.us-west-2.amazonaws.com/repo']
    }
}       
```

**Log output**:

```Caused by: com.google.cloud.tools.jib.image.InvalidImageReferenceException: Invalid image reference: org/repo,id.dkr.ecr.us-east-1.amazonaws.com/repo```

--- OR ---

* What went wrong:
Script compilation errors:

```
  Line 133:         image=listOf("org/repo","id.dkr.ecr.us-east-1.amazonaws.com/repo")
                          ^ Type mismatch: inferred type is List<String> but String? was expected
```

My log output is from a kotlin gradle buildscript, but I think the concepts apply no matter the buildscript language - there does not appear to be a way to specify 2 image locations to be able to push an image to 2 image repos via one build.

There is a workaround [specified here](https://github.com/GoogleContainerTools/jib/issues/802#issuecomment-415491924) but it feels somewhat un-natural and so I wonder if this tool should support this use case?

**Comment by chanseokoh** [comment]
Hi @Bwvolleyball,

As you noticed, this is not supported, and implementing this is not an easy task this than you can imagine for a few technical and non-technical reasons.

First of all, Jib provides a lot of ways and configuration options to provide credentials to both the base image repository and the target repository. (For example, you can pass `-Djib.to.auth.username=myaccount` on the command line.) Allowing multiple target repositories mean we need to sort out a new compatible design for specifying registry credentials. This is doable, but configurations will become more complex, and a lot of code handling these configuration options should change as well. And of course, coming up with a good configuration design should be the first step and needs careful thoughts too.

And there are other things that need to think about, which may determine the scope of the work needed. For example, what to do if authentication works for one target registry but does not for another registry? Should Jib fail right away, or upload only a subset of images and fail later? What about general registry error handling? Yeah, we will be able implement this, but this requires a lot of effort.

All these boil down to how much value we can add considering that there is a reasonable workaround: you can parameterize `jib.to.image`. There are many ways you can parameterize various Jib configurations in Maven and Gradle. And running two Jib commands as as workaround shouldn't be bad. Everything is cached, and it will not be slower than when this feature is directly supported in Jib.

One day, we may eventually implement this feature. However, unfortunately, I don't think that will happen anytime soon.

Lastly,
```
		tags ['latest', 'develop']
```
No need to have `latest` in `tags`. `latest` is already implied in `image` (i.e., `id.dkr.ecr.us-west-2.amazonaws.com/repo:latest`.

**Comment by cricket007** [comment]
Why not loop and push in a fashion similar to this?

````
buildCmd -Djib.to.image=foo
buildCmd -Djib.to.image=bar
```

**Comment by charneykaye** [comment]
I'm going with the @OneCricketeer method, for now, _but_ am disappointed by my build time in CI _doubling_. I'm considering a vector where we build once with jib to a local image, and then do the shipping to repository manually.

**Comment by chanseokoh** [comment]
I wouldn't worry too much about running Jib multiple times. Everything built for an image is cached and reused (thanks to the strong reproducibility of Jib), so subsequent runs will be no-op regarding building something.

**Comment by charneykaye** [comment]
I agree, @chanseokoh based on our experience so far. Subsequent jib runs are very fast.

**Comment by jaw111** [comment]
I have a similar requirement to push an image to different ECR repositories depending on the branch being built.

For now I use an approach based on what is described here: https://github.com/GoogleContainerTools/jib/issues/802#issuecomment-415041916

What would really help though is if I could separate the registry name and path, so I could easily vary the registry that is pushed to using something like `-Djib.to.registry`.
