### ISSUE TITLE
Enable separate container build and push

### ISSUE THREAD

**Issue by konfri** [GoogleContainerTools/jib#2305]
**Environment**:

- *Jib version:* 
2.0.0
- *Build tool:* 
gradle

Hey, 
thanks for jib, it's a nice tool that makes container creation easy! 👍

At present, our team uses gitlab and docker to build containers. We would like to use jib but I have troubles to do a separate container creation and push to our container registry from gitlab. Just to explain my use case, I list our pipeline steps:

- build 
- unit tests / integration tests
- container build & push
- deployment

At present, we keep the created jar from _build_ step and pass it to _container build & push_ step to speed up the process. If the previous steps were successful, the jar is reused to build and push a container to our registry. So instead of passing around the jar, we can pass the container as tar (using _gradle jibBuildTar_). This works fine and the only thing that is missing, is pushing the container to our registry without using docker. So do you support a separate container push? Thanks :)

**Comment by chanseokoh** [comment]
Hi @konfri,

How about using [`skopeo`](https://github.com/containers/skopeo)? It's a CLI tool with many useful features for dealing with containers. For example, I was able to push a tar to Docker Hub like this:
```
$ skopeo docker-archive:build/jib-image.tar docker://francium25/test
```

(I actually needed to do `skopeo --insecure-policy copy ...`.)

And I don't think we will implement this feature in Jib.

**Comment by chanseokoh** [comment]
Sorry, the correct command is `skopeo copy docker-archive:build/jib-image.tar docker://francium25/test`. I omitted the `copy` command by mistake.

**Comment by loosebazooka** [comment]
We also have a product [`crane`](https://github.com/google/go-containerregistry#crane) that might work here. @jonjohnsonjr ?

**Comment by chanseokoh** [comment]
@konfri actually, I recommend our [`crane`](https://github.com/google/go-containerregistry#crane) for this. (I just didn't realize I can push a tar archive with `crane`.)

```
$ crane push build/jib-image.tar francium25/test
```

I'm going to close this issue. As I said, I don't think we will implement this in Jib. However, anyone feel free to update or re-open if there's any feedback.

**Comment by konfri** [comment]
Thanks for the feedback, I will try crane :)
