### ISSUE TITLE
How to use remote docker daemon?

### ISSUE THREAD

**Issue by jiangyongbing24** [GoogleContainerTools/jib#2313]
**Environment**:

- *Jib version:* 1.4.13
- *Build tool:* Maven
- *OS:* `maven app`: win10,`remote docker daemon`: centos7

**Description of the issue**:
I want to use the remote docker daemon to pull and upload images. The `dockerclient` Property in the document is configured as a daemon into the local path. If I want to use a remote one, how do I configure it?

**Comment by chanseokoh** [comment]
Hi @jiangyongbing24

You should be able to pass Docker-specific environment variables like `DOCKER_HOST`. See https://github.com/GoogleContainerTools/jib/issues/1956#issuecomment-530548273

I have no experience using a remote Docker engine. I wonder if this will help: https://gist.github.com/kekru/4e6d49b4290a4eebc7b597c07eaf61f2#set-env-var-linux-mac-windows I'm curious if this actually works well. Could you update here after trying it?

**Comment by chanseokoh** [comment]
For Maven, it should be like

```xml
<dockerClient>
    <environment>
        <DOCKER_HOST>...</DOCKER_HOST>
    </environment>
</dockerClient>
```

See https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#dockerclient-object

**Comment by chanseokoh** [comment]
This actually works.

1. Run a Docker daemon in Docker; API exposed via port 2375
   ```
   $ docker run --rm -p2375:2375 --privileged -e DOCKER_TLS_CERTDIR= docker:19.03.3-dind
   ```
1. Set `DOCKER_HOST` to `localhost:2375`.
   ```xml
   <dockerClient>
       <environment>
           <DOCKER_HOST>localhost:2375</DOCKER_HOST>
       </environment>
   </dockerClient>
   ```
1. Build and push an image with Jib.
   ```
   $ mvn jib:dockerBuild
   ...
   [INFO] Built image to Docker daemon as francium25/test
   ...
   [INFO] BUILD SUCCESS
   ```
1. Check the image.
   ```
   $ docker inspect francium25/test
   []
   Error: No such object: francium25/test
   $ DOCKER_HOST=localhost:2375 docker inspect francium25/test
   [                                                                                                                                                                                                    
       {                                                                                                                                                                                                
           "Id": "sha256:f174a058dbd3cc99a8996f7a6b654c7bbb0928e44d33ae0d6b027120a6e92e4b",                                                                                                             
    ```

**Comment by chanseokoh** [comment]
@swang-harbin unfortunately for now, Jib requires executing a Docker client (the `docker` CLI) to communicate to a Docker engine (whether remote or local): #1997

I believe you are already aware of this, but you just need to [download and unzip](https://docs.docker.com/engine/install/binaries/#install-static-binaries) a Docker client (`docker`); no need for a Docker engine (`dockerd`). For the spotify and fabric8io plugins, I guess they are using some Docker client Java library instead of running `docker`.
