### ISSUE TITLE
time parser should handle all time zone designators

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#2319]
https://en.wikipedia.org/wiki/ISO_8601#Time_zone_designators

https://stackoverflow.com/questions/46487403/java-8-date-and-time-parse-iso-8601-string-without-colon-in-offset

**Comment by chanseokoh** [comment]
> A formatter with optional sections like the above is good for parsing, but not for formatting. When formatting, it'll print all the optional sections, which means it'll print the offset many times. So, to format the date, just use another formatter

Also the answer has something important to keep in mind.
