### ISSUE TITLE
jib packages spring boot devtools

### ISSUE THREAD

**Issue by saturnism** [GoogleContainerTools/jib#2336]
**Environment**:

- *Jib version:* 2.1.0
- *Build tool:* maven
- *OS:* macos

**Description of the issue**:
I created a Spring Boot app w/ devtools dependency:

```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-devtools</artifactId>
  <scope>runtime</scope>
  <optional>true</optional>
</dependency>
```

In the resulting image,  devtool is actually activated. The dependency is in the image's `/app/libs` directory.

**Expected behavior**:
Optional dependency ignored? Spring Boot's plugin excludes devtool by default.
https://docs.spring.io/spring-boot/docs/2.2.5.RELEASE/maven-plugin/repackage-mojo.html

**Steps to reproduce**:

  1. Create a new spring boot app w/ devtool
  2. Package w/ Jib
  3. See that Jib includes Devtool 

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <version>2.1.0</version>
  <configuration>
    <from><image>openjdk:8u222-slim</image></from>
    <to><image>gcr.io/wise-coyote-827/jib-demo</image></to>
    <container><user>nobody:nogroup</user></container></configuration>
</plugin>
```

**Log output**: 

**Additional Information**:

**Comment by loosebazooka** [comment]
Yeah that makes sense, our logic considers it a runtime dependency. We're not checking for optional. How would this work in a container environment? Someone would inject the dependency at runtime?

**Comment by chanseokoh** [comment]
Someone asked this before: https://github.com/GoogleContainerTools/jib/issues/1254#issuecomment-439478139

**Comment by loosebazooka** [comment]
Oh this is more about development vs deployment.
I feel like the springboot team should've used profiles in their example, not optional.

Anyway, it still seems within the scope of optional use as an exclusionary mechanism for packaging.
See: **Why use optional dependencies?** at https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by saturnism** [comment]
how can we resolve this? thinking of..

* explicit exclusions by groupId:artifactId
* or, simply ignore optionals
* or, simply jib the produced JAR, which is something i've been advocating :) since the JAR is what user expects to turn into container.

**Comment by hjannasch** [comment]
As a workaround use this solution https://blog.frankel.ch/spring-devtools-jib-intellij-idea/

**Comment by loosebazooka** [comment]
Yeah, profiles should be the way to go.

**Comment by chanseokoh** [comment]
We have published a Jib extension for Spring Boot ([Maven](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-quarkus-extension-maven) and [Gradle](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-spring-boot-extension-gradle)) that covers this issue. You can apply the extension on recent Jib versions.

## Details

As discussed in this thread and #1254, Jib is working as intended to package `spring-boot-devtools` in the image, and the user should properly configure the dependency if they do not want it at runtime. However, we decided to create the extension to help people avoid the chore of manually setting up profiles in their projects.

**Comment by beku8** [comment]
For future reference, I solved the issue with maven profile & scope.

I have two profiles local (active by default for local development) & cloud in my ```pom.xml```.
```
<profiles>
  <profile>
    <id>local</id>
    <activation>
      <activeByDefault>true</activeByDefault>
    </activation>
    <properties>
      <dev-tools.scope>compile</dev-tools.scope>
    </properties>
  </profile>
  <profile>
    <id>cloud</id>
    <properties>
      <dev-tools.scope>provided</dev-tools.scope>
    </properties>
  </profile>
</profiles>
```
When scope is ```provided``` jib won't include it in the ```apps/lib``` folder
```
<dependency>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-devtools</artifactId>
  <scope>${dev-tools.scope}</scope>
</dependency>
```
Then build my docker image with ```-P cloud``` like 
```
mvn package myproject -P cloud jib:build -Dimage=myproject```

**Comment by ChristianCiach** [comment]
For future reference: When using the Gradle plugin `org.springframework.boot`, you can configure Jib to use a configuration called `productionRuntimeClasspath` that doesn't include the devtools (and possibly other dependencies of the `developmentOnly` configuration).

Example in build.gradle:
```
jib {
    configurationName = org.springframework.boot.gradle.plugin.SpringBootPlugin.PRODUCTION_RUNTIME_CLASSPATH_NAME
    from {
        image = 'amazoncorretto:16'
    }
    to {
        image = 'myimage'
    }
```
The references constant is not public, which is why I've created an issue at the spring boot project: https://github.com/spring-projects/spring-boot/issues/26686

Instead of referencing the constant, you may just as well just use the string `"productionRuntimeClasspath"`.

**Comment by goto1134** [comment]
update: use [jib-spring-boot-extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-spring-boot-extension-maven) to exclude spring-boot-devtools

**Comment by markusheiden** [comment]
Doesn't do 
```gradle
jib {
  container {
    configurationName = 'productionRuntimeClasspath'
  }
}
``` 
the trick too?

**Comment by StringKe** [comment]
In the latest version `configurationName` is defined by `val` it is not modifiable, how do I set `configurationName`?

**Comment by artemptushkin** [comment]
This is not only about `devtools` but [docker-compose](https://docs.spring.io/spring-boot/reference/features/dev-services.html#features.dev-services.docker-compose) too, I assume you use `runtimeclasspath`? I will open a dedicated issue
