### ISSUE TITLE
could I use the google jib to build the spring boot with https?

### ISSUE THREAD

**Issue by darapenhchet** [GoogleContainerTools/jib#2340]
could I use the google jib to build the spring boot with https?

**Comment by loosebazooka** [comment]
Can you explain a little more what you want to do?

**Comment by cricket007** [comment]
@darapenhchet 👋 https://github.com/GoogleContainerTools/jib/tree/master/examples/spring-boot#dockerize-a-spring-boot-application-using-jib

**Comment by darapenhchet** [comment]
I want to build the springboot applications with https. But right now it works. Thanks you
