### ISSUE TITLE
PyGradle?

### ISSUE THREAD

**Issue by cricket007** [GoogleContainerTools/jib#2342]
**Environment**: Python developer

- *Build tool:* Gradle

**Description of the issue**:
Use Jib to package Python containers via [pygradle](https://github.com/linkedin/pygradle)

**Expected behavior**:
A layered container that separates out `site-packages` from the source-code like `lib/*.class` is done separately in Java applications.

**Comment by loosebazooka** [comment]
Should be possible with jib core right now?

**Comment by cricket007** [comment]
Should be, yes, although it'd be a rather manual process to get the layers to be as I described

**Comment by loosebazooka** [comment]
I think this is out of scope for us at the moment. If you would like to propose something more concrete, perhaps a new proposal in https://github.com/GoogleContainerTools/jib/tree/master/proposals that we can work on together.

**Comment by cricket007** [comment]
Make sense. Thanks!
