### ISSUE TITLE
[jib-cli] Pass auth creds through parameters

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/jib#2361]
**Copied from https://github.com/briandealwis/cram/issues/5**: @student-06 asked
> It would be great if we can supply auth creds for registry using parameters since it removes the dependency on credential helpers.
> 
> My exact use case is: We are setting up a CI system for UI projects, where we need to push docker images (without daemon) to a local registry which has auth.

**Comment by Eveneko** [comment]
@briandealwis 
I'm happy to fix this issue, but a bit confused due to my initial exposure to this project. :-)
In this issue scenario, you don't want to use or can't use credential helpers?
Can I understand this issue in this way: we need an explicit login operation?

**Comment by chanseokoh** [comment]
jib-cli can already use credentials helpers, and it's the recommend way to provide credentials. This issue is proposing to have an additional way of providing registry username/password on the command line.

**Comment by Eveneko** [comment]
OK, I'll work on it.

**Comment by chanseokoh** [comment]
Thanks! Note this issue is specifically about jib-cli. You only need to look into the [`jib-cli` folder](https://github.com/GoogleContainerTools/jib/tree/master/jib-cli).

**Comment by loosebazooka** [comment]
@Eveneko unless this is a problem that is specifically affecting you right now, I would hold off, we are currently working through formalizing the design of the jib-cli. 

If you are looking for a way to contribute to jib and are not blocked by the current implementation, please take a look at our issues and find one and we can help you there.

**Comment by Eveneko** [comment]
OK👌, I'll look for other issues.

**Comment by ishan008** [comment]
can't we pass the registry username and password as parameters in JIB-CLI ?

**Comment by everflux** [comment]
I tested it with
```
jib build
--to-username sampleuser --to-password samplepass --target=registry.example.com/trion/demo:latest
```
and it worked like a charm. I think this issue can be closed.
