### ISSUE TITLE
Unable to give command line parameters during build

### ISSUE THREAD

**Issue by tamizharasanr** [GoogleContainerTools/jib#2384]
**Environment**: Local

- *Jib version: 2.1.0
- *Build tool:*  Gradle 5.4.1
- *OS:* Windows

**Description of the issue**: 
I am having conditional based build to make normal spring boot jar with Netflix stack and application jar with Kubernetes stack. 

**Expected behavior**:
When I use the Gradle build with -Dk8s=true then the application jar will consist of Kubernetes stack. If the parameters not used while building then normal Netflix stack will be in the application jar

**Steps to reproduce**:

  1. Add the following command to build.gradle
```
if (System.getProperty("k8s") == "true") {
  dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-kubernetes', version: '1.0.3.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-context', version: '2.1.1.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-kubernetes-config', version: '1.0.3.RELEASE'
  }
  configurations {
    compile.exclude group: "org.springframework.cloud", module: "spring-cloud-netflix-core"
  }
}
```
  2. Do the docker image build with `./gradlew jibDockerBuild -Dk8s=true`
  3. Run the image in docker it should use the Kubernetes stack and not the Netflix stack

**Log output**: 

**Additional Information**:

**Comment by loosebazooka** [comment]
This is not really a jib configuration problem, it appears to be an issue with how you're confusing gradle. 

What does the rest of your build file look like?

**Comment by tamizharasanr** [comment]
@loosebazooka  I cannot able to give the complete Gradle file. Because most of the plugins and libraries are built internally in my organization. So you won't able to build with that. 

But whenever I run the Gradle build like `./gradlew build -Dk8s=true` it adds and removes the libraries as per the condition inside the block.

But do I have an option to give the build command while executing `./gradlew jibDockerBuild `?

**Comment by loosebazooka** [comment]
jib uses `runtimeClasspath` from gradle to determine which libraries to include in the final build. So as long as you're populating that correctly, jib should work as expected -- including anything that is determined by command line parameters (like -Dk8s)

It's not clear to me exactly what you're seeing to determine that jib isn't working though, and that would help debug. Have you inspected both the final artifact from `build` and `jibDockerBuild` and seen some discrepancies? 

Perhaps you can provide a minimal project without any references to your companies proprietary libraries.

**Comment by tamizharasanr** [comment]
@loosebazooka  To give you context what i am trying to do. Let's say I am building a spring boot application with Netflix oss package like in the following build.gradle
```
dependencies {
    compile("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client")
    compile('org.springframework.cloud:spring-cloud-starter-openfeign')
    compile('org.springframework.cloud:spring-cloud-starter-netflix-hystrix')
    compile('org.springframework.cloud:spring-cloud-starter-netflix-ribbon')
    compile('org.springframework.boot:spring-boot-starter-web')
    compile('org.springframework.boot:spring-boot-starter-actuator')
    compile('org.springframework.boot:spring-boot-starter-validation')
    compile('org.springframework.boot:spring-boot-starter-aop')
    compile('org.springframework.retry:spring-retry')
    compile('org.springframework.cloud:spring-cloud-starter-config')
    compile('org.springframework.cloud:spring-cloud-starter-bus-amqp')
    compile('org.springframework.cloud:spring-cloud-starter-zipkin')
    compile('de.codecentric:spring-boot-admin-starter-client:2.0.1')
    compile('org.springframework.boot:spring-boot-starter-security')
    compile('io.springfox:springfox-swagger2:2.6.1')
    testCompile('org.springframework.boot:spring-boot-starter-test')
}
```
Once I built the jar and run it will run with those dependency jars.

But I want to run the same code with some modified dependency list by adding some and removing some for only running in kubernetes. So I have modified build.gradle as follows

```
dependencies {
    compile("org.springframework.cloud:spring-cloud-starter-netflix-eureka-client")
    compile('org.springframework.cloud:spring-cloud-starter-openfeign')
    compile('org.springframework.cloud:spring-cloud-starter-netflix-hystrix')
    compile('org.springframework.cloud:spring-cloud-starter-netflix-ribbon')
    compile('org.springframework.boot:spring-boot-starter-web')
    compile('org.springframework.boot:spring-boot-starter-actuator')
    compile('org.springframework.boot:spring-boot-starter-validation')
    compile('org.springframework.boot:spring-boot-starter-aop')
    compile('org.springframework.retry:spring-retry')
    compile('org.springframework.cloud:spring-cloud-starter-config')
    compile('org.springframework.cloud:spring-cloud-starter-bus-amqp')
    compile('org.springframework.cloud:spring-cloud-starter-zipkin')
    compile('de.codecentric:spring-boot-admin-starter-client:2.0.1')
    compile('org.springframework.boot:spring-boot-starter-security')
    compile('io.springfox:springfox-swagger2:2.6.1')
    testCompile('org.springframework.boot:spring-boot-starter-test')
}
if (System.getProperty("k8s") == "true") {
  dependencies {
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-kubernetes', version: '1.0.3.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-context', version: '2.1.1.RELEASE'
    compile group: 'org.springframework.cloud', name: 'spring-cloud-starter-kubernetes-config', version: '1.0.3.RELEASE'
  }
  configurations {
    compile.exclude group: "org.springframework.cloud", module: "spring-cloud-netflix-core"
  }
}
```
By this, I can run both normal build and Kubernetes build with just some configuration parameters like `k8s=true`. When I am running a build with `k8s=true` it will exclude the `spring-cloud-netflix-core` dependency from the application jar and add the `spring-cloud-starter-kubernetes` and remaining two.

But when I build the image with jib I won't be able to give that build parameter to Gradle so I couldn't add or remove dependency basically I am not able to build the jar for Kubernetes. 

And thank you for your quick responses.

**Comment by loosebazooka** [comment]
> But when I build the image with jib I won't be able to give that build parameter to Gradle

That's not really how this works, jib is just a plugin in Gradle, it doesn't control anything that gradle does. 

Jib and Gradle *should* both be doing the right thing here.

Let me try inspecting the build to see if something is really going on, but you can also inspect the build output using an image inspection tool like [dive](https://github.com/wagoodman/dive)

**Comment by loosebazooka** [comment]
@tamizharasanr In order to test this, I need a completely working build.gradle. It appears the code snippet you provided us with is missing bom references and other versioning. Please provide more info to help us proceed.

**Comment by tamizharasanr** [comment]
@loosebazooka Thanks for your guidance. The dive tool helped me a lot to figure out what went wrong. I missed JVM flag `-Dspring.profiles.active=k8s` for spring profile in the build.gradle file. Now it's working fine as expected.
