### ISSUE TITLE
Image is not pushing to ECR after the build got successful

### ISSUE THREAD

**Issue by tamizharasanr** [GoogleContainerTools/jib#2385]
**Environment**: Local

- *Jib version:* 2.1.0
- *Build tool:*  Gradle - 5.4
- *OS:* Windows

**Description of the issue**:
I could able to build the image locally by using the command `jibDockerBuild` but the image is not pushed to the repository.

**Expected behavior**:
I have logged in to my ECR repo manually to my local docker. I could able to push the images manually by running `docker push`. I have set the `jib.to.image` to my ECR repo. The expected behavior is after the successful build the image should be pushed to the ECR repo which is not happening

**Steps to reproduce**:

  1. I have added the following to my build.gradle file.
```
plugins { 
  id 'com.google.cloud.tools.jib' version '2.1.0'  // <-- ADD ME
}
jib {
  to {
    image = "my ecr repo"
  }
  container {
    // Set JVM options.
    jvmFlags = ['-Dspring.profiles.active=k8s']
    // Add labels.
    args = ['-Dk8s=true']
  }
}
```
  2.  I ran the following command to build the image  `./gradlew jibDockerBuild`
  3. The build is successful and I could run the image locally. But after the successful build it is not pushing the image to ECR repo

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @tamizharasanr,

The `jibDockerBuild` task doesn't push to a remote registry. Use the `jib` task instead. It will directly push an image to ECR (as long as you set up auth correctly and use the right ECR repo name).

**Comment by chanseokoh** [comment]
Just in case, you don't need to run `jibDockerBuild` before `jib`. Jib works without Docker installed.
