### ISSUE TITLE
IllegalArgumentException from ASM library

### ISSUE THREAD

**Issue by Jojoooo1** [GoogleContainerTools/jib#2389]
**Environment**:

- *Jib version:* 2.1.0
- *Build tool:* 3.0.0-M1
- *OS:* Ubuntu

**Description of the issue**:
Can not build Docker daemon using command ` mvn compile com.google.cloud.tools:jib-maven-plugin:2.1.0:dockerBuild `

**Steps to reproduce**:

  1. download project  https://github.com/Jojoooo1/spring-boot-base
  2. `mvn compile com.google.cloud.tools:jib-maven-plugin:2.1.0:dockerBuild`

**Log output**: 
` Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.1.0:dockerBuild (default-cli) on project carros: Execution default-cli of goal com.google.cloud.tools:jib-maven-plugin:2.1.0:dockerBuild failed.: IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.1.0:dockerBuild (default-cli) on project carros: Execution default-cli of goal com.google.cloud.tools:jib-maven-plugin:2.1.0:dockerBuild failed.`

**Comment by chanseokoh** [comment]
Thanks for reporting this, @Jojoooo1.

For now you can work around this by explicitly setting the `mainClass`, e.g.,

```
mvn compile com.google.cloud.tools:jib-maven-plugin:2.1.0:dockerBuild \
    -Djib.container.mainClass=com.carros.CarrosApplication
```

You can also configure `<mainClass>` in `pom.xml`.

---

It is coming from the ASM library.
```
Caused by: java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:258)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:162)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:283)
        at com.google.cloud.tools.jib.api.MainClassFinder.find(MainClassFinder.java:165)
```

**Comment by chanseokoh** [comment]
@Jojoooo1 your project looks strange. Why do you have `.class` files under `src/main/resources`? For example, 
```
./src/main/resources/classes/classes/com/carros/api/IndexController.class
./src/main/resources/classes/com/carros/api/IndexController.class
```

If I remove those `.class` files, the error goes away. I think they are not meant to be checked into the source repo?

**Comment by Jojoooo1** [comment]
Yes thanks you very much ! Those files had nothing to do overthere, it was problably coming from an unexpected copy. It is now working perfectly.
