### ISSUE TITLE
Revisit ImageReference tags

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#2390]
As a follow-up to #2381, we should figure out how default tags should work now that digests can be specified at the same time.

- `isDefaultTag` / `usesDefaultTag`
- `withTag` <-- should we preserve a digest?

**Comment by chanseokoh** [comment]
Don't forget `toString()` needs to be changed so that it doesn't print the default tag `latest` when a digest is given but not a tag.
