### ISSUE TITLE
How to set contextPath in embedded Jetty?

### ISSUE THREAD

**Issue by wicadmin** [GoogleContainerTools/jib#2391]
Hi,
Referring to [this](https://www.eclipse.org/jetty/documentation/current/configuring-contexts.html#setting-context-path), how does one use jib to set the contextpath of the embedded Jetty server for a webapp (without modifying the webapp)?

My build is simple:

```
git clone https://e1dabe...edbf9@github.com/foo/bar.git .

mvn package com.google.cloud.tools:jib-maven-plugin:2.1.0:build -Dimage=registry.gitlab.com/foo/bar \
    -Djib.to.auth.username=joe -Djib.to.auth.password=-xxxxxxgizy -Djib.container.creationTime=USE_CURRENT_TIMESTAMP

```

**Comment by chanseokoh** [comment]
Hi @wicadmin,

You can configure `<appRoot>` to change where your app will be placed in the image. The default value for a WAR project is `/jetty/webapps/ROOT`. Therefore, for Jetty, you can do this:

```xml
        <configuration>
          <container>
            <appRoot>/jetty/webapps/foo</appRoot>
          </container>
        </configuration>
```

Then your app will be served at, for example, `localhost:8080/foo/`. (Mind the trailing slash.) You can set this on the command line with `-Djib.container.appRoot=/jetty/webapps/foo`.

**Comment by wicadmin** [comment]
Yep, thank you for this.

It is that trailing slash I was originally trying to avoid ;-)

**Comment by chanseokoh** [comment]
I think the trailing slash is important for a Servlet engine to distinguish between the `foo` resource in the ROOT context and the `foo` context.

**Comment by wicadmin** [comment]
OK, I'll see if I can have my HAProxy look for it and add it if missing. Let me try this.
