### ISSUE TITLE
InsecureRegistryException

### ISSUE THREAD

**Issue by 2020testuser** [GoogleContainerTools/jib#2422]
I'm not sure this is an issue or I'm missing something. Please direct me to the solution link if this is not an issue as I'm new to Jib. Appreciate any help to get this issue resolved.
==============
I'm using Jib Gradle for building Sprint Boot Java application.
I'm getting the below exxception.
Caused by: java.io.IOException: com.google.cloud.tools.jib.api.InsecureRegistryException: Failed to verify the server at https://gcr.io/v2/distroless/java/blobs/sha256:e263a579c008a7b3f2d1fce55152ec4e7f800f915f6c58fc245ec6a6d19316a6 because only secure connections are allowed.
11:31:17.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.cloud.tools.jib.registry.RegistryClient.lambda$pullBlob$3(RegistryClient.java:353)
11:31:17.435 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.google.cloud.tools.jib.hash.Digests.computeDigest(Digests.java:102)

**Environment**:
Mac OS
Docker installed and tested successfully
Included docker and docker config file in the PATH
Sprint Boot Java 
Gradle 4.6
Gradle Wrapper 4.6
Jib Plugin 1.4.0

- *Jib version: 1.4.0*
- *Build tool: Gradle 4.6*
- *OS: MAC* 

**Description of the issue**:
I'm getting an exception. My build.gradle is below. I also pulled the image successfully.
plugins {
	id 'com.google.cloud.tools.jib'  version '1.4.0' 	
}
	dependencies {
	compile(project(":base-framework"))
	}
/** CHANGE THIS TO THE IMAGE YOU WANT TO PUSH TO */
jib.from.image = 'gcr.io/distroless/java:debug'
jib.to.image = '<org docker repo/image name>:jib'
apply plugin: "com.google.cloud.tools.jib"

**Expected behavior**:
Successful build with no errors or exceptions.

**Steps to reproduce**:

  1.  Configure build.gradle to use the jib plugin.
  2.  Build the spring boot application using the below command.
./gradlew build --stacktrace --debug --no-build-cache --scan  --rerun-tasks -S -x test jibDockerBuild 
  3. 

**`

plugins {
	id 'com.google.cloud.tools.jib'  version '1.4.0' 
}
	dependencies {
	compile(project(":common-code"))
	}
/** CHANGE THIS TO THE IMAGE YOU WANT TO PUSH TO */
jib.from.image = 'gcr.io/distroless/java:debug'
 jib.to.image = 'docker.repo1.uhc.com/is360art/is360api-search-ms:jib'
	apply plugin: "com.google.cloud.tools.jib"
'-->

**Log output**: 

**Additional Information**:

**Comment by loosebazooka** [comment]
Can you upgrade to jib 2.2.0 and try again?
This is very strange, it could just be that you don't have the right certificates on your machine to verify the connection to gcr.io?

**Comment by 2020testuser** [comment]
Unfortunately, I'm unable to upgrade the jib as if I upgrade, I get other errors even before it reaches this step. Also, I'm using Gradle 4.6 and so, using the matching jib version for it to avoid compatibility issues. To resolve this error, I'm using a different base image which I pushed to my local docker repo and using it.

Will need to revisit this later. 

Thanks for your help!

**Comment by chanseokoh** [comment]
Something is still off, but I think the most probable cause is that your JVM has trouble verifying the server `https://gcr.io`. Maybe try with a different JVM or on a different machine. MacOS might be related as well.

**Comment by manuelarte** [comment]
I'm having the same issue with Jib id 'com.google.cloud.tools.jib' version '2.6.0' and this:

```
jib {
    from {
        image = 'openjdk:13'
    }
    to {
        image = "gcr.io/${myproject}/$name:${getDockerTag()}"
    }
    container {
        creationTime = 'USE_CURRENT_TIMESTAMP'
    }
}
```

It works locally, but not when building it in circleci. I get the following error:

```
* What went wrong:
Execution failed for task ':jib'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: com.google.cloud.tools.jib.api.InsecureRegistryException: Failed to verify the server at https://registry-1.docker.io/v2/library/openjdk/blobs/sha256:ff31919fd91c62f64a0815e18cade1bb567
```

**Comment by mpeddada1** [comment]
@manuelarte Thanks for reaching out. This kind of an issue has been associated with the JDK version in the past ([#1216] (https://github.com/GoogleContainerTools/jib/issues/1216). Hm are you using the same jdk version locally as well?

**Comment by manuelarte** [comment]
Yes I am

**Comment by chanseokoh** [comment]
@manuelarte according to your report in Gitter, seems like you got past the `InsecureRegistryException`? What was the issue and how did it get resolved?

**Comment by manuelarte** [comment]
Hi @chanseokoh , I updated the gitter message with the stacktrace. It is not solved (I also updated jib version to 2.7.0)

**Comment by chanseokoh** [comment]
Re: https://github.com/GoogleContainerTools/jib/issues/2422#issuecomment-737058101, another user said was hitting the [same problem on CircleCI](undefined). They managed to resolve the issue and shared their experience:

> We have managed to resolve the issue by using a machine executor and not a docker executor on circleci. The issue does not seem to be jib related.

**Comment by manuelarte** [comment]
> Re: [#2422 (comment)](https://github.com/GoogleContainerTools/jib/issues/2422#issuecomment-737058101), another user said was hitting the [same problem on CircleCI](undefined). They managed to resolve the issue and shared their experience:
> 
> > We have managed to resolve the issue by using a machine executor and not a docker executor on circleci. The issue does not seem to be jib related.

Nice, unfortunately I clicked on your link and I don't see the reply

**Comment by chanseokoh** [comment]
Sorry, updated the link. But nothing more specific than what you see.
