### ISSUE TITLE
Jib Gradle - adding jar 

### ISSUE THREAD

**Issue by 2020testuser** [GoogleContainerTools/jib#2423]
**Environment**:
Gradle 4.6 
- *Jib version: 1.4.0* 
- *Build tool:* 
- *OS: Mac OS* 

**Description of the issue**:
Could anyone please let me know how I can make jib to use the dependent jar created during the build time to use as Dockerfile ENTRYPOINT jar? Looking for the equivalent command to be added in the jib container {}. 
Converting the existing gradle build springboot application to gradle jib. 
I'm able to build and deploy in the application in Kubernetes. However, the application is not giving any response back.
**Expected behavior**:
On using gradle jib for build and docker image push to registry, the application must be launched successfully.

**Steps to reproduce**:

  1.  Migrate the existing SpringBoot application's gradle build to gradle jib for build. No change made in application. Just modified the build.gradle and gradle.properties file.
  2. The JibDockerBuild created the image successfully.
  3. When pushed the image to Kubernetes and launched the application, getting an error. The application doesn't open successfully in the browser and no errors in the log.

**`jib-gradle-plugin` Configuration**: 
```gradle
plugins {
	id 'com.google.cloud.tools.jib'  version '1.4.0' 
}	
dependencies {
	compile(project(":common-framework"))
}
jib {
    from {
        image = 'openjdk:alpine'
    }
    to {
        image = '<my org docker repo/appname>:dev'

    }
    container {
        jvmFlags = ['-Xms512m', '-Xmx1024m']
        args = ['coretest-app.jar']
        ports = ['8204']
        format = 'OCI'
    }
}
apply plugin: "com.google.cloud.tools.jib"
```
**Log output**: 
No errors seen when ran the command - kubectl logs services/ <sn>
**Additional Information**: 
Below is my Docker file that was generated by Gradle earlier when plain Gradle (without Jib was used for build).
```Dockerfile
FROM openjdk:alpine
ARG JAR_NAME
WORKDIR /app
ADD $JAR_NAME coretest-app.jar
RUN touch coretest-app.jar
EXPOSE $PORT
ENV PORT=$PORT
ENV JAVA_OPTS=$JAVA_OPTS
ENTRYPOINT [ "sh", "-c", "java  -jar coretest-app.jar" ]
```

**Comment by chanseokoh** [comment]
By default, Jib doesn't need a JAR. Remove `args` below, and it should work (at least on recent Jib versions.)
```diff
     container {
         jvmFlags = ['-Xms512m', '-Xmx1024m']
-        args = ['coretest-app.jar']
         ports = ['8204']
         format = 'OCI'
     }
```

**Comment by chanseokoh** [comment]
And regarding [your Gradle 4.6 requirement](https://github.com/GoogleContainerTools/jib/issues/2422#issuecomment-618010428), can't you use a Gradle wrapper instead?

**Comment by chanseokoh** [comment]
Oh, and since you are using `plugins { id 'com.google.cloud.tools.jib'  version '1.4.0' }`, it's unnecessary to do `apply plugin: "com.google.cloud.tools.jib"`. You should remove the legacy `apply plugin`.

**Comment by 2020testuser** [comment]
Thanks for inputs! After removing the above, having the same problem. "Safari can't open the page". Is there any way to get more info. when the application url is launched in the browser as the checking the application log using kubectl doesn't show any error message.
Sorry. I'm using Gradle 4.6 .
Below is my command to create the docker image. 
 ./gradlew build --stacktrace --debug --no-build-cache  --rerun-tasks  -x test jibDockerBuild

Am I missing anything in the command? Thanks!

**Comment by chanseokoh** [comment]
Nothing seems wrong. Take a look at this [Spring Boot+Kubernetes example](https://github.com/GoogleContainerTools/jib/tree/master/examples/spring-boot). Or this [Spring Boot+Jib+Kubernetes Wokrshop](https://hackmd.io/@ryanjbaxter/spring-on-k8s-workshop) material. 

And before deploying an image to Kubernetes, can't you test and verify the image works locally with Docker? And I understand you'll stick to Gradle 4.6 on prod, at least you could test Jib 2.2.0 locally with a recent Gradle just for the sake of checking if 1.4.0 is broken.

But if you could share your application (or at least a stripped-down sample project), I should be able to make it work in no time.

**Comment by 2020testuser** [comment]
Thanks!
I finally got it working by passing parameters for port, security, docker etc. 
It works now. 
Not sure what got the issue resolved. Thanks again.
