### ISSUE TITLE
Gradle plugin 2.2.0 is not available on maven central

### ISSUE THREAD

**Issue by celcius112** [GoogleContainerTools/jib#2424]
The Gradle plugin 2.2.0 does not seem to be published on [maven central](https://mvnrepository.com/artifact/gradle.plugin.com.google.cloud.tools/jib-gradle-plugin), while the maven plugin is.

**Comment by loosebazooka** [comment]
This bug is non-actionable so closing for now.

**Comment by celcius112** [comment]
hello @loosebazooka and thank you the fast answer.

The link I sent is indeed not the "real" maven central, but it does show that the plugin is not available as a maven artifact. This means that I can't import the plugin as a normal dependency, as such: 
```kotlin
dependency {
   implementation("gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:2.2.0")
}
```
which is possible until version 2.1.0.

Importing the artifact as a plugin does work, but my use-case is to import it as a maven dependency in order to extend the task in a custom plugin.

**Comment by celcius112** [comment]
It might also be a synchronization issue between the Gradle plugin portal and maven central

**Comment by celcius112** [comment]
Hello @loosebazooka and thank you for the fast answer.

The link I sent is indeed not the "real" maven central per se, but it does show that the artifact is not available as a maven dependency, such as:
```
dependency {
  implementation("gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:2.2.0")
}
```

In the Gradle plugin portal we can compare this way and see that there seem to be missing some information:
- 2.1.0: https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/2.1.0/
- 2.2.0: https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/2.2.0/
I'm no expert, but this might cause maven central to not understand this new version.

**Comment by loosebazooka** [comment]
Yeah, so gradle has its own way of defining plugins. Perhaps something changed since we last

**Comment by loosebazooka** [comment]
Actually you know what, this is a re-appearance of: https://discuss.gradle.org/t/debug-an-issue-in-publish-plugin-gradle-plugin-not-being-prepended-to-groupid/32720

I think I messed up the release a little with a bug I already knew about :facepalm: 

I'll have to fix this (and maybe re-release 2.2.0) :\

**Comment by loosebazooka** [comment]
so, we probably wont do a re-issue of 2.2.0, maybe a 2.2.1 and this should fix your issue. There is a workaround, but I don't want to recommend it as it would be very temporary.

**Comment by chanseokoh** [comment]
FTR,

- https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/
- https://plugins.gradle.org/m2/com/google/cloud/tools/jib/com.google.cloud.tools.jib.gradle.plugin/

Group ID different between 2.1.0 and 2.2.0:
- https://plugins.gradle.org/m2/com/google/cloud/tools/jib/com.google.cloud.tools.jib.gradle.plugin/2.1.0/com.google.cloud.tools.jib.gradle.plugin-2.1.0.pom
- https://plugins.gradle.org/m2/com/google/cloud/tools/jib/com.google.cloud.tools.jib.gradle.plugin/2.2.0/com.google.cloud.tools.jib.gradle.plugin-2.2.0.pom

**Comment by loosebazooka** [comment]
Right, this is only for `2.2.0`, any future release will have the `gradle.plugin` prefix again

**Comment by celcius112** [comment]
Nice, thanks a bunch

**Comment by chanseokoh** [comment]
@celcius112 Jib 2.3.0 is released. You'll no longer see this issue.
