### ISSUE TITLE
dockerBuild throws a Docker daemon failed Error

### ISSUE THREAD

**Issue by mayhs19** [GoogleContainerTools/jib#2429]
**Environment**: Local Machine

- *Jib version:*  2.2.0
- *Build tool:* Maven
- *OS:* Mac OS Mojave

**Description of the issue**:
`jib dockerBuild` on `MacOS` gives the below error, though I know that docker is installed and I can run docker build commands from my username without any special permissions

```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.2.0:dockerBuild (default) on project distroless-service: Build to Docker daemon failed, perhaps you should make sure Docker is installed and you have correct privileges to run it -> [Help 1]
```

**Expected behavior**:
`jib dockerBuild` should connect to the local docker daemon and create a docker image

**Steps to reproduce**:

  1. Add jib-maven-plugin to pom.xml
  2. Add dockerBuild to execution Steps
  3. run maven with jib:dockerBuild Command

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>2.2.0</version>
                <configuration>
                    <to>
                        <image>${image.path}</image>                        
                    </to>
                </configuration>
                <executions>
				    <execution>
				      <phase>install</phase>
				      <goals>
				        <goal>dockerBuild</goal>
				      </goals>
				    </execution>
  				</executions>
            </plugin>
```

**Log output**: 
```
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.2.0:dockerBuild (default) on project distroless-service: Build to Docker daemon failed, perhaps you should make sure Docker is installed and you have correct privileges to run it -> [Help 1]
```

**Additional Information**: None

**Comment by chanseokoh** [comment]
Hi @mayhs19,

Can you run `$ docker images && mvn jib:dockerBuild -X` and report back what they show?

**Comment by mayhs19** [comment]
Hi @chanseokoh 
Sure, I can do that on a terminal on my mac but I am using the `Spring STS` IDE where I would like to use the `maven build` run configuration to use JIB. Any clues on how I can get what you are looking for, with still using Spring/Eclipse IDE , instead of in a terminal window ?

**Comment by chanseokoh** [comment]
Aha, that makes sense. You just need to launch your IDE from the environment where `PATH` has a directory that contains the `docker` binary. For example, launch your terminal (which seems to have the right `PATH`) and from that terminal, launch your IDE. There are certainly many other ways, like set the system `PATH` that globally affects all apps on your machine. Or, I don't know much about MacOS, but there should be a way to set environment variables for the probably you launch from a shortcut icon. 

If all fails, any IDE should have a way to set environment variables when launching `mvn` from within the IDE.

**Comment by mayhs19** [comment]
Hi @chanseokoh Ok, I guess I could not convey my idea effectively, so I may have to rephrase my earlier comment a bit.
I am able to do a `docker images` from both the Terminal and on the IDE using the `Docker Tooling` perspective provided by the IDE. So, there is no issue with docker being "identified" from within the IDE.
The only issue is that JIB does not identify the running docker daemon automatically during the `jib:dockerBuild` phase and throws the below error :

```[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.2.0:dockerBuild (default) on project distroless-service: Build to Docker daemon failed, perhaps you should make sure Docker is installed and you have correct privileges to run it -> [Help 1]```

I hope that clarifies my line of thought a bit more effective than before :)

**Comment by chanseokoh** [comment]
Note that Jib literally [executes the `docker` binary](https://github.com/GoogleContainerTools/jib/blob/e4b291f9dd9fe4de666935d568306a8fde13b38b/jib-core/src/main/java/com/google/cloud/tools/jib/docker/DockerClient.java#L119); therefore, what is certain is that the environment you are running the `mvn` process doesn't have `docker` in `PATH`.

If you have trouble figuring out how to set the environment for the `mvn` process launching from within your IDE, then the last resort I can propose is to explicitly tell Jib where to find the `docker` binary.

```
mvn -Djib.dockerClient.executable=/your/path/to/docker ... jib:dockerBuild
```

You can configure [`<dockerClient><executable>`](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage) in `pom.xml`, if you like.

However, as I said, you won't need this if you can set up correct `PATH` for the environment where the `mvn` process is launched from your IDE.

**Comment by chanseokoh** [comment]
> If all fails, any IDE should have a way to set environment variables when launching `mvn` from within the IDE.

> I am using the `Spring STS` IDE where I would like to use the `maven build` run configuration to use JIB. Any clues on how I can get what you are looking for, with still using Spring/Eclipse IDE , instead of in a terminal window ?

Just realized you are using Eclipse and running Maven through a _Maven Build Run Configuration_. You can set up the environment for launching Maven in the _Environment_ tab of the _Run Configuration_.

![run_configuration](https://user-images.githubusercontent.com/10523105/80408753-b49e4f80-8895-11ea-85ba-a86945e25692.png)

**Comment by mayhs19** [comment]
Hi @chanseokoh 
Thanks for the support. I will check the above steps out.
