### ISSUE TITLE
Tarball manifest.json has incorrect key capitalization

### ISSUE THREAD

**Issue by ctimmins** [GoogleContainerTools/jib#2430]
**Environment**:

- *Jib version:* v2.x
- *Build tool:* Gradle 5.2.1
- *OS:* MacOS 10.15

**Description of the issue**:
manifest.json inside jib image tarball has incorrect capitalization

**Expected behavior**:
manifest.json should contain key "RepoTags".  instead it contains "repoTags".  
Technically it is expected to be "repoTags" according to [this test](https://github.com/GoogleContainerTools/jib/blob/v2.2.0-gradle/jib-core/src/test/java/com/google/cloud/tools/jib/docker/json/DockerManifestEntryTemplateTest.java#L39) but I have always seen "RepoTags" in manifest

**Steps to reproduce**:

  1. `./gradlew jibBuildTar`
  2. `cd <buildDir> && tar -xvf jib-image.tar`
  3. manifest.json will have a key *repoTags*

**Notes**
[source pojo](https://github.com/GoogleContainerTools/jib/blob/v2.2.0-gradle/jib-core/src/main/java/com/google/cloud/tools/jib/docker/json/DockerManifestEntryTemplate.java#L51)

I think adding `@JsonProperty("RepoTags")` could fix the issue

**Comment by chanseokoh** [comment]
Thanks for reporting. Not just `RepoTags` but `Config` and `Labels`, I think.

**Comment by chanseokoh** [comment]
@ctimmins Jib 2.3.0 is released with this fix!
