### ISSUE TITLE
Maven plugin : improve the doc for container entrypoint INHERIT configuration 

### ISSUE THREAD

**Issue by bcopy** [GoogleContainerTools/jib#2433]
**Environment**:

- *Jib version:* 2.2.0
- *Build tool:* maven 3.2.5
- *OS:* Linux

**Description of the issue**:

**Expected behavior**:

**Steps to reproduce**:

  1. Create a pom.xml with the given plugin configuration (see below)
  2. When building, the following error is shown (see below)
 

**`jib-maven-plugin` Configuration**: 
```xml
        <configuration>
          <container>
            <entrypoint>INHERIT</entrypoint>
          </container>
        </configuration>
```

**Log output**: 
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.2.0:build (build-dockerhub) on project img-mq: Unable to parse configuration of mojo com.google.cloud.tools:jib-maven-plugin:2.2.0:build for parameter entrypoint: Cannot assign configuration entry 'entrypoint' with value 'INHERIT' of type java.lang.String to property of type java.util.List -> [Help 1]
[ERROR]

**Additional Information**: This is expected behaviour. The workaround is to add a dummy element to turn the string into a list :
```xml
<entrypoint><entry>INHERIT</entry></entrypoint>
```

**Comment by chanseokoh** [comment]
Thanks for reporting. I confirmed that Maven 3.2.5 (released in 2014) is too old and cannot handle this. I'll just add a note to the current doc.
