### ISSUE TITLE
Project dependencies in a separate layer for WAR projects

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2450]
We put project dependencies into a separate layer for JAR projects (https://github.com/GoogleContainerTools/jib/issues/1436#issuecomment-504534542 and https://github.com/GoogleContainerTools/jib/issues/403#issuecomment-504549115), but this isn't supported for WAR projects.

---

Note there are other related feature requests for generalized dependency control (such as excluding certain dependencies from a list and fine-controlled dependency layering):

https://github.com/GoogleContainerTools/jib/issues/1962#issuecomment-529161358
https://github.com/GoogleContainerTools/jib/issues/403#issuecomment-404461239
https://github.com/GoogleContainerTools/jib/issues/403#issuecomment-405028122
https://github.com/GoogleContainerTools/jib/issues/403#issuecomment-405051107
https://github.com/GoogleContainerTools/jib/issues/403#issuecomment-405099150
https://github.com/GoogleContainerTools/jib/issues/1436#issuecomment-486772623
https://github.com/GoogleContainerTools/jib/issues/1852

Note we expect to support the generalized fined-grained dependency control through the Jib extension framework: https://github.com/GoogleContainerTools/jib/issues/1962#issuecomment-599235543

**Comment by ST-DDT** [comment]
I use jib-maven-plugin 2.2.0 and I have a separate layer for the dependencies.

````json
		}, {
			"created": "2020-05-13T13:36:58.743844200Z",
			"author": "Jib",
			"created_by": "jib-maven-plugin:2.2.0",
			"comment": "dependencies"
		}, {
			"created": "2020-05-13T13:36:58.743844200Z",
			"author": "Jib",
			"created_by": "jib-maven-plugin:2.2.0",
			"comment": "snapshot dependencies"
		}, {
````
Or I'm I mistaken?

**Comment by chanseokoh** [comment]
I was talking about "[project dependencies](https://github.com/GoogleContainerTools/jib/issues/1436#issuecomment-504534542)", i.e., JAR from a sibling module/sub-project within the same project.

**Comment by Eveneko** [comment]
OK, I'll work on it. ;-)

**Comment by chanseokoh** [comment]
@Eveneko thank you very much! If you need any help, let us know.

**Comment by Eveneko** [comment]
@chanseokoh 
Hi, I noticed that project dependencies are obtained by the following code in method `createJibContainerBuilder` in `MavenProjectProperties.java`:

```java
session
    .getProjects()
    .stream()
    .map(MavenProject::getArtifact)
    .collect(Collectors.toSet())
```

I am not clear about MavenSession (try to find documents but failed )
I wonder if this is the same for war project to get project dependencies using MavenSession?

**Comment by chanseokoh** [comment]
@Eveneko
Hi! Yeah, What happens is that, `session.getProjects()` gives us all the (sub-)projects involved in an entire Maven build session, and calling `getArtifact()` on each (sub-)project tells us the output artifact (e.g., a JAR file) associated with the project. For example, if a multi-module setup looks like this,
```
my-project/
  +-- library-foo-module: getArtifact() returns "library-foo.jar" (basically)
  +-- library-bar-module: getArtifact() returns "library-bar.jar"
  `-- main-module: (getArtifact() returns something, but we won't care)
```
then in `classifyDependencies()`, it goes through all the dependencies of `main-module` to check whether they are either `library-foo.jar` or `library-foo.jar`; if so, they are classified as a project dependency.

So the same story still applies to the WAR case, basically. The difference, however, would be that you may need to check actual filenames in `WEB-INF/lib/*.jar` to determine if a JAR file there is from a sub-module.

**Comment by WuYff** [comment]
Hi @chanseokoh, thank you for your guide. We created a pr and hope that you can review it. Working with @Eveneko.

**Comment by chanseokoh** [comment]
> Note we expect to support the generalized fined-grained dependency control through the Jib extension framework: #1962 (comment)

The [Jib Extension Framework](https://github.com/GoogleContainerTools/jib-extensions) is now available with the latest Jib versions. You can easily extend and tailor the Jib plugins behavior to your liking.

We've written a general-purpose layer-filter extension that enables fine-grained layer control, including deleting files and moving files into new layers

- [Maven Layer-Filter Extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-maven)
- [Gradle Layer-Filter Extension]( https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-gradle)

For general information about using and writing extensions, take a look at the [Jib Extensions repo](https://github.com/GoogleContainerTools/jib-extensions).
