### ISSUE TITLE
Jib infers wrong main class if multiple main classes exist

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2456]
We got a report that Jib uses the string `${start-class)` when there are multiple `public static void main()` defined. I was able to reproduce this on a Spring Boot project. I think the string `${start-class)` comes from Spring Boot.
```
$ cd examples/spring-boot
$ mvn help:effective-pom | grep start-class
                <mainClass>${start-class}</mainClass>
            <mainClass>${start-class}</mainClass>
                <mainClass>${start-class}</mainClass>
                    <mainClass>${start-class}</mainClass>
                <mainClass>${start-class}</mainClass>
            <mainClass>${start-class}</mainClass>
                  <mainClass>${start-class}</mainClass>
              <mainClass>${start-class}</mainClass>
```
We are [supposed to fail and show an error](https://github.com/GoogleContainerTools/jib/blob/eafbb96b59d05b153d943631be50733baf98754c/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java#L126-L131) if there are multiple main classes, but seems like this isn't working.

A workaround is to explicitly set the main class with `<container><mainClass>`.

UPDATE: found a related issue #170

@reechar-goog @saturnism

**Comment by chanseokoh** [comment]
```
[WARNING] 'mainClass' is not a valid Java class : ${start-class}
...
[INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, ${start-class}]
```

**Comment by chanseokoh** [comment]
I don't know how exactly Spring Boot determines a main class, but having a single `@SpringBootApplication` does help. If there is no `@SpringBootApplication` or multiple `@SpringBootApplication` annotations, then Spring Boot shows an error:

```
[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.6.RELEASE:run (default-cli) on project spring-boot-k8s-example: Execution default-cli of goal org.springframework.boot:spring-boot-maven-plugin:2.1.6.RELEASE:run failed: Unable to find a single main class from the following candidates [hello.Foo, hello.Application] -> [Help 1]
```

And there seem [many other ways](https://stackoverflow.com/questions/23217002/how-do-i-tell-spring-boot-which-main-class-to-use-for-the-executable-jar/31040641) Spring Boot determines the main class.

For now, I think we should fix this bug and show an error that multiple main classes are detected.

**Comment by chanseokoh** [comment]
@reechar-goog @saturnism Jib 2.3.0 is released with the fix.

**Comment by saturnism** [comment]
Neat. Thank you!
