### ISSUE TITLE
Failed to verify the server at error

### ISSUE THREAD

**Issue by Arnold1** [GoogleContainerTools/jib#2458]
Hi,

I run into the following issue. can someone please tell me what is wrong?

**Environment**:

- *Jib version:*  ```id 'com.google.cloud.tools.jib' version '2.2.0'```
- *Build tool:*  ```Gradle 5.3```
- *OS:* ```OSX 10.14.6```

**Description of the issue**:
```
$ ./gradlew jib

Containerizing application to docker.blabla.com/intelligence/cbr-endpoint...
Base image 'gcr.io/distroless/java:8' does not use a specific image digest - build may not be reproducible
Using credentials from Docker config (/Users/arnold1/.docker/config.json) for docker.blabla.com/intelligence/cbr-endpoint
Using base image with digest: sha256:f59b26c5ecc735514a38afbf845214383c4e2ba1fdd15a76225339b8ab7da8ef
I/O error for image [gcr.io/distroless/java]:
    javax.net.ssl.SSLHandshakeException
    sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
Executing tasks:
[========                      ] 27.8% complete
> pulling base image manifest
> pushing blob sha256:94fb8dcb2723fa67aff65a829...

> Task :jib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jib'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: com.google.cloud.tools.jib.api.InsecureRegistryException: Failed to verify the server at https://gcr.io/v2/distroless/java/blobs/sha256:63318ff0cff7b0a3d925cd239ee03b9f970aff6bd8bc6edf29313ff1f8a3f90b because only secure connections are allowed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
12 actionable tasks: 1 executed, 11 up-to-date
```

**Expected behavior**:
```
no error
```

**Steps to reproduce**:
```
./gradlew jib
```
**`jib-gradle-plugin` Configuration**: 
```groovy
plugins {
    id 'java'
    id 'application'
    id 'idea'
    id "com.google.protobuf" version "0.8.8"
    id 'com.google.cloud.tools.jib' version '2.2.0'
}

group 'com.blabla.bve'
version '1.0-SNAPSHOT'

jib.to.image = "docker.blabla.com/intelligence/cbr-endpoint"
tasks.jib.dependsOn tasks.test

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

application {
    mainClassName 'com.blabla.bve.Endpoint'
}

dependencies {
    compile (
        "com.sparkjava:spark-core:2.7.2",
        "com.typesafe:config:1.3.2",
        'com.google.protobuf:protobuf-java:3.6.1',
        'com.google.protobuf:protobuf-java-util:3.6.1',
        'com.google.code.gson:gson:2.8.5',
        'ch.qos.logback:logback-core:1.2.3',
        'ch.qos.logback:logback-classic:1.2.3',
        'com.sumologic.plugins.logback:sumologic-logback-appender:1.2',
        'ch.qos.logback.contrib:logback-jackson:0.1.5',
        'com.fasterxml.jackson.core:jackson-databind:2.9.8',
        'ch.qos.logback.contrib:logback-json-classic:0.1.5'
    )
    testCompile (
        "org.junit.jupiter:junit-jupiter-engine:5.4.0",
        "org.assertj:assertj-core:3.9.1",
        "commons-beanutils:commons-beanutils:1.9.3",
        "org.apache.httpcomponents:httpclient:4.5.7"
    )
    testImplementation('org.junit.jupiter:junit-jupiter:5.4.1')
}

protobuf {
    protoc {
        // Download from repositories
        artifact = 'com.google.protobuf:protoc:3.6.1'
    }
}

test {
    useJUnitPlatform()
    testLogging {
        events "passed", "skipped", "failed"
    }
    include '**/*Properties.class'
    include '**/*Test.class'
    include '**/*Tests.class'
}
```

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @Arnold1,

This is indeed a very rare and unexpected error that your Java (JVM) installation cannot verify a Google's server (`https://gcr.io`). (Almost certainly, this has nothing to do with Jib.) It would not really be rare or unexpected If it were not a Google server. However, since this is a Google server, this only says that your JVM has a fundamental issue verifying servers. Is this your local environment? Most likely your JVM doesn't have a Root CA installed. As such, if you compile and run the following code, it will fail with the same error *when using the same JVM your Gradle and application use*:

```java
public class OpenStream {
  public static void main(String[] args) throws Exception {
    new java.net.URL("https://gcr.io").openStream().close();
    System.out.println("The line above will throw an exception.");
  }
}
```

Also can you try different JVMs and on different machines?

If only `gcr.io` is the problem, you can try a different base image (for example, an image on Docker Hub) by setting `jib.from.image`.

**Comment by chanseokoh** [comment]
But maybe, this is an intermittent problem and the `OpenStream` sample above may fail only on some occasions. The URL `https://gcr.io/v2/distroless/java/blobs/sha256:63318ff0cff7b0a3d925cd239ee03b9f970aff6bd8bc6edf29313ff1f8a3f90b` in the error suggests that your JVM was actually able to verify `gcr.io` before, because accessing that URL should be sometime after you interacted with `gcr.io`. So, this is very very strange. In any case, I still believe it is the problem in your JVM.

```
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: com.google.cloud.tools.jib.api.InsecureRegistryException: Failed to verify the server at https://gcr.io/v2/distroless/java/blobs/sha256:63318ff0cff7b0a3d925cd239ee03b9f970aff6bd8bc6edf29313ff1f8a3f90b because only secure connections are allowed.
```

**Comment by chanseokoh** [comment]
If this is indeed an occasional PKIX verification failure, another wild speculation is that some proxy, firewall, router, or software sits between your JVM and `gcr.io` that sporadically and wrongly interferes networking.

In any case, this will definitely work on a sane JVM on a different network and machine.

**Comment by Arnold1** [comment]
I found the issue - my machine has netscape installed - which causes that error...

**Comment by chanseokoh** [comment]
Huh, Netscope. Very interesting. Thank you very much for the information. I was really curious. Will close this issue.

**Comment by andreasf** [comment]
In case anyone else comes across this issue while using the Maven plugin and a custom truststore, make sure to get the order of arguments to Maven right:

This will not work the first time it's run in a fresh container:
```
./mvnw compile jib:build -Djavax.net.ssl.trustStore=cacerts
```

But this always works:
```
./mvnw -Djavax.net.ssl.trustStore=cacerts compile jib:build
```
