### ISSUE TITLE
Allow specifing creation/modification date on libraries

### ISSUE THREAD

**Issue by ST-DDT** [GoogleContainerTools/jib#2462]
**Environment**:

- *Jib version:*  2.2.0
- *Build tool:* 3.6.2
- *OS:* Windows 10

**Description of the issue**:

I have to use `<filesModificationTime>${git.commit.time}</filesModificationTime>` in order for spring to properly detect the last changed date for static resources. However this also affects the `dependencies` layer. So every commits effectively generates a new `dependencies` layer, but those only change very rarely.

**Expected behavior**:

The dependencies layer should only change when the dependencies change themselves.

**Steps to reproduce**:

  1. Add a dependency to your project
  2. Set filesModificationTime to a fixed value
  3. Build-Tar
  4. Search for the dependency image layer name
  5. Alter filesModificationTime
  6. Build-Tar
  7. Search for and compare the dependency image layer name

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>jib-maven-plugin</artifactId>
	<executions>
		<execution>
			<id>docker-build-tar</id>
			<phase>package</phase>
			<goals>
				<goal>buildTar</goal>
			</goals>
		</execution>
	</executions>
	<configuration>
		<from>
			<image>adoptopenjdk/openjdk11:alpine-jre</image>
		</from>
		<to>
			<image>test:${project.version}</image>
		</to>
		<container>
			<creationTime>USE_CURRENT_TIMESTAMP</creationTime>
			<filesModificationTime>${git.commit.time}</filesModificationTime>
		</container>
	</configuration>
</plugin>
```

**Additional Information**:

I'm not sure whether the `creationTime` has an impact on the layer re-usability, so I don't know whether we need to duplicate that property as well, but we definitely need a new property for `filesModificationTime` for `dependencies`. Maybe something like `dependenciesModificationTime`.

Is there a reliable way to get the "release/upload-date for a maven/gradle dependency?
If there is not, then I will probably use the epoch constant property.

I'm not sure whether `snapshot-dependencies` need an extra property or should be treated as either dependencies or "files".

**Note**

This might again cause issues with static resources in dependencies, as the timestamp is collected from the jar containing that resource. But that can be adjusted by the user as they can see fit.

**Possibly related issues:**

* https://github.com/GoogleContainerTools/jib/issues/2317
* https://github.com/GoogleContainerTools/jib/issues/2021
* https://github.com/GoogleContainerTools/jib/issues/1608

**Comment by ST-DDT** [comment]
On a second thought this alternative might be more powerful:

Allow specifying a `class` name, that can map the files to a timestamp.

**Example:**

`<filesModificationTime>com.example.jib.TimeMapper</filesModificationTime>`

````java
public class TimeMapper implements FileModificationTimeSelector {

    private static final long LAST_GIT_COMMIT = System.getProperty("git.commit.time");

    public long getLastModified(String layer, File file) {
        if (file.endsWith(".jar")) {
            return jar.readManifest().getOrDefault("Build-Time", LAST_GIT_COMMIT);
        } else {
            return LAST_GIT_COMMIT;
        }
    }

}
````

**Comment by chanseokoh** [comment]
As of now, you can create a [new Jib extension](https://github.com/GoogleContainerTools/jib-extensions), e.g., to set timestamps of only those file you want.
