### ISSUE TITLE
Use daemon-free Buildah instead of Docker to generate OCI containers

### ISSUE THREAD

**Issue by loxal** [GoogleContainerTools/jib#2465]
The only reason for me to switch from the classic container pipeline to this dependency would be if it would offer an optional Buildah backend option. Currently I would need to install Docker just to use this plugin.

Currently I switched to podman which uses Buildah underneath to build OCI containers.

**Comment by chanseokoh** [comment]
Hi @loxal,

> Currently I would need to install Docker just to use this plugin.

Note Jib doesn't use Docker for _building_ containers. You can still use Jib without Docker if you push an image directly to a registry.

For now, a workaround is use `jib:buildTar` and then load the tarball to Buildah yourself. That said, what's the exact Buildah command to load and save an OCI/Docker image tarball?

**Comment by loxal** [comment]
If it does not depend on Docker nor Buildah, it might be even more appealing. I'll take a closer look as I want to get rid of Docker & its daemon altogether. 

Can't help you with your question though.

**Comment by chanseokoh** [comment]
Closing as a non-issue. Jib doesn't depend on Docker.
