### ISSUE TITLE
Why is default charset is US-ASCII and not UTF-8

### ISSUE THREAD

**Issue by NaitYoussef** [GoogleContainerTools/jib#2475]
**Environment**:

- *Jib version:* 2.2.0
- *Build tool:* Maven 3.6.3
- *OS:* UBUNTU-20

**Description of the issue**:

Hello, I've been using lately the jib maven plugin to build my docker Java application images and I noticed that the default **charset encoding** used in my Java application is US-ASCII. 
Wouldn't it be more convient if UTF-8 was the default instead ? 
I have added the -Dfile.encoding=UTF-8 jvm flag to set UTF-8 as default for file encoding.

**Steps to reproduce**:

  1. print the Charset.defaultCharset()

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>jib-maven-plugin</artifactId>
    <version>2.2.0</version>
    <executions>
        <execution>
            <phase>install</phase>
            <goals>
                <goal>dockerBuild</goal>
            </goals>
        </execution>
    </executions>
    <configuration>
        <container>
            <mainClass>MyClass</mainClass>
            <creationTime>USE_CURRENT_TIMESTAMP</creationTime>
            <ports>8080</ports>
        </container>
    </configuration>
</plugin>
```

**Comment by chanseokoh** [comment]
Hi @NaitYoussef,

This is an issue in the base image ([gcr.io/distroless/java](https://gcr.io/distroless/java)) that Jib uses by default: https://github.com/GoogleContainerTools/distroless/issues/253

I will seek to fix this in the base image. I am closing this as a duplicate, but feel free to update here with more information or feedback as needed.

**Comment by chanseokoh** [comment]
FYI, another workaround is to use a different JDK base image with `<configuration><from><image>`.

**Comment by chanseokoh** [comment]
This is [fixed](https://github.com/GoogleContainerTools/distroless/pull/551) in the upstream Distroless Java images.
