### ISSUE TITLE
Want to build only when "mvn install" and both build and push when "mvn deploy"

### ISSUE THREAD

**Issue by stevengibbszions** [GoogleContainerTools/jib#2480]
**Environment**:

- *Jib version:* 2.2.0
- *Build tool:* Maven 3.5+
- *OS:* Linux

**Description of the issue**:
The below maven configuration results in docker build happening twice on a "mvn deploy", once during "dockerBuild" goal and once during "build" goal.

**Expected behavior**:
Would like to **build** (and then push) only once during a maven deploy, and only build (not push) the image on mvn install (or package).

**`jib-maven-plugin` Configuration**: 
```xml
				<plugin>
					<groupId>com.google.cloud.tools</groupId>
					<artifactId>jib-maven-plugin</artifactId>
					<version>${jib-maven-plugin.version}</version>
					<configuration>
						<container>
							<user>1000:1000</user>
						</container>
						<from>
							<image>somebase:image</image>
						</from>
						<to>
							<image>some:iamgetag</image>
						</to>
					</configuration>
					<executions>
						<execution>
							<id>dockerBuild</id>
							<goals>
								<goal>dockerBuild</goal>
							</goals>
							<phase>package</phase>
						</execution>
						<execution>
							<id>build</id>
							<goals>
								<goal>build</goal>
							</goals>
							<phase>deploy</phase>
						</execution>
					</executions>
				</plugin>
```

**Log output**: 
During **package** phase

> 2020-05-19T23:25:26.0262037Z [INFO] **Built** image to Docker daemon as someimage:tag

During **deploy** phase

> 2020-05-19T23:26:13.2744645Z [INFO] **Built and pushed** image as someimage:tag

**Additional Information**: 
I don't think the build should happen twice, any ideas how I can achieve this? TIA

**Comment by chanseokoh** [comment]
Hi there!

In your case, I think the closest workaround is to bind the `jib:buildTar` goal instead of `jib:dockerBuild` to the `package` phase: https://stackoverflow.com/a/60869500/1701388 It will unnecessarily assemble an image tarball though; Jib doesn't have a "prepare-layers-and-warm-cache" goal, which can sometimes be inefficient compared to the combined build and push with `jib:build`.

Also take a look at #2305 and #1756.

I will close this as a dup of #1756 (or #2305), but feel free to reopen or update if you think your case is different.

**Comment by chanseokoh** [comment]
Just in case: to be clear, although the messages you see (`Built image` and `Built and pushed`) sound like Jib is building an image again, the second `deploy` with `jib:build` doesn't actually rebuild an image. Everything is cached, so any consecutive Jib runs will be very fast. In your case, the `deploy` phase will only do what's really necessary (i.e., pushing the already-built layers to a registry).
