### ISSUE TITLE
cache mount paths

### ISSUE THREAD

**Issue by 2020testuser** [GoogleContainerTools/jib#2481]
@chanseokoh - Could you please confirm on the below?
I'm using a PVC  ( in Kubernetes) to store my application source (pulled from git).
In my gradle command below (in my Tekton Pipeline), I'm passing --gradle-user-home=/workspace/.gradle as you recommended (to resolve permission issues) since I'm using gradle image which runs as user-gradle by default.

`gradle build testapp:jib --gradle-user-home=workspace/.gradle --build-cache  
-Duser.home=/workspace `

I believe I don't need the below volume mounts as my /.gradle is under /workspace/.gradle. I had to change the mountpaths to /workspace/.gradle below. Is that correct? Also, since, /workspace is in PVC, caching these in PVC, would improve my build performance.
Since, I used the tekton catalog's jib, these volumemounts are in  my pipeline. Thanks in advance!

  `volumeMounts:
    - name: $(params.cache)
      mountPath: /tekton/home/.gradle/caches
      subPath: gradle-caches
    - name: $(params.cache)
      mountPath: /tekton/home/.gradle/wrapper
      subPath: gradle-wrapper
    - name: $(params.cache)
      mountPath: /tekton/home/.m2
      subPath: m2-cache
    - name: $(params.cache)
      mountPath: /tekton/home/.cache
      subPath: jib-cache `

_Originally posted by @2020testuser in https://github.com/GoogleContainerTools/jib/issues/2437#issuecomment-631140644_
/kind/question

**Comment by chanseokoh** [comment]
Closing as a dup of https://github.com/GoogleContainerTools/jib/issues/2437#issuecomment-631140644.
