### ISSUE TITLE
Can't docker run java project image which used jlink tool: Permission denied, unknown error

### ISSUE THREAD

**Issue by ceyhunn** [GoogleContainerTools/jib#2506]
**Environment**:

- *Jib version:* jib core version 0.14.0
- *Build tool: I can't find anything to use scratch base image with gradle plugin
- *OS:* Manjaro Arch based linux

**Description of the issue**:
I can't docker run java project image which used jlink tool. `Permission denied, unknown` error gives when run executable file.

**Expected behavior**:

**Steps to reproduce**:

  1. Add the gradle dependency to [this example](https://github.com/ceyhunn/demo)
`compile group: 'com.google.cloud.tools', name: 'jib-core', version: '0.14.0'`
  2. Run following task
```
task dojib {
        def builder = Jib.fromScratch()
        builder.setEntrypoint("/bin/demo")
        builder.setCreationTime(Instant.now())

        builder.addFileEntriesLayer(FileEntriesLayer.builder().addEntryRecursive(Path.of("$buildDir/image/cp"), AbsoluteUnixPath.get('/cp')).build())
        builder.addFileEntriesLayer(FileEntriesLayer.builder().addEntryRecursive(Path.of("$buildDir/image/bin"), AbsoluteUnixPath.get('/bin')).build())
        builder.addFileEntriesLayer(FileEntriesLayer.builder().addEntryRecursive(Path.of("$buildDir/image/conf"), AbsoluteUnixPath.get('/conf')).build())
        builder.addFileEntriesLayer(FileEntriesLayer.builder().addEntryRecursive(Path.of("$buildDir/image/legal"), AbsoluteUnixPath.get('/legal')).build())
        builder.addFileEntriesLayer(FileEntriesLayer.builder().addEntryRecursive(Path.of("$buildDir/image/lib"), AbsoluteUnixPath.get('/lib')).build())

        builder.containerize(Containerizer.to(DockerDaemonImage.named("example")))
}
```
  3. Run the docker image which named "example" and see the error.  

**Log output**: 
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/bin/demo\": permission denied": unknown.
ERRO[0000] error waiting for container: context canceled
```

**Comment by chanseokoh** [comment]
Hi @ceyhunn,

I didn't look into the sample repo, but I think at least you should set executable bits when adding `$buildDir/image/bin`? 
```groovy
builder.addEntryRecursive(Path.of("$buildDir/image/bin"), AbsoluteUnixPath.get('/bin'),
                          (source, target) -> FilePermissions.fromOctalString('755'))
```

**Comment by chanseokoh** [comment]
BTW, I just realized an unrelated issue when adding the jib-core dependency: #2507.

**Comment by ceyhunn** [comment]
Hi @chanseokoh , thank you very much, it worked. However jib became useless for me, because jlink launcher depends on glibc, zlib, stdc++ libraries. Jib doesn't support custom run command, I need to use dockerfile.

**Comment by chanseokoh** [comment]
Thanks for the update. Just FYI and for future documentation:

Jib Core is a general tool to build a container image, so I am certain you can create a working image as long as you supply the right runtime libraries or use the right base image that already contains the libraries from the right OS/architecture. Even with the Jib Maven plugin (not Jib Core), I was able to build a working jlink application with some tweak and tricks.

**Comment by chanseokoh** [comment]
Also note it'll be really arduous to create any working image from "scratch", much like the ["scratch image"](https://hub.docker.com/_/scratch) in `Dockerfile`. Most like you'll start from some base image.

```groovy
def builder = Jib.fromScratch()
```
