### ISSUE TITLE
jib-buildplan dependency should be in scope compiler for jib-core

### ISSUE THREAD

**Issue by rmannibucau** [GoogleContainerTools/jib#2524]
Hi,

Using jib-core 1.4.0, buildplan module is not imported transitively (it is scope runtime) so if you code/script against jib-core you can't create properly images.

Can you move the scope to compile?

Thanks,
Romain

**Comment by chanseokoh** [comment]
This is a dup of #2507 and fixed. We will release 1.4.1 today.

**Comment by chanseokoh** [comment]
@rmannibucau jib-core 1.15.0 released and live.

**Comment by rmannibucau** [comment]
Updated with success thanks!
