### ISSUE TITLE
Skipping containerization because packaging is 'pom'.

### ISSUE THREAD

**Issue by xavipen** [GoogleContainerTools/jib#2533]
Hi,

I have the following use case for jib:

There is an application that have different distributions. Each distribution is defined by a set of spring configuration files and a set of additional dependencies. The actual application code is the same in each distribution.

For this use case it would be great to be able to define, for each distribution, a maven project with packaging pom that defines only the additional dependencies and contains the configuration resources. This way it will be easy to handle the different distribution.

I understand that jib was not design in principle for this type of use case. Normally, the application is directly package as a container and that gives you a lot of nice features and testing capabilities for your application in addition to the containerization.

It would be great, if jib could also support this other "use case" for containerization of "distributions"

As a work around, I guess that instead of using the packaging pom i could use packaging jar and create a proxy main that starts the application in each distribution but it would be great if no hack where needed to get jib to work in this case.

**Comment by loosebazooka** [comment]
It seems like you could use maven profiles for this? or maven executions?

It's not really clear what you are trying to do without an example.

**Comment by xavipen** [comment]
Thanks for the quick response. I will try to be more precise. Although it is difficult to explain.

I have a maven project "processingApp". This app is a pretty dummy main file, that will load most of the actual processing based on a Spring configuration.

When the "processingApp" is going to be deployed in a site for processing "apples" it has to be delivered with and additional dependency to an "apple-processor". The "processingApp.jar" + the additional dependency "apple-processor.jar" and the spring config to load an implementation of the appleProcessor.class. All this elements together is what I called before a distribution. In this particular example it would be called the apples distribution.

In another site instead of "apples" they will process  "oranges" and in that case it should have an additional dependency to "orange-processor" and a new distribution should be created for the orange processing.

The processingApp is totally decoupled from the libraries/jars/dependencies that provide the processing implementation. The spring configuration defines which is the actual processing to be done.

This means that I do not know which dependencies may be needed in the "processingApp" maven project, so I can not use maven profiles or maven executions for this in the "processingApp" maven project

Currently I use maven-assembly-plugin and also and rpm plugin to package each distribution.

For that I would create a specific maven project per distribution with packaging pom that gathers all the dependencies and spring configuration and generates the assemblies.zip and rpm files for each one.

Now I would like to also be able to deliver each distribution also as a docker image and I am struggling to see how to use jib for this without using a workaround that looks a lot like a hack.

I hope, this clarifies a bit more what I meant earlier

**Comment by loosebazooka** [comment]
I think we need to understand your current process, it currently seems like to me that you're trying to get jib to do something it's not designed to do (but maybe I'm wrong), so a few more questions:
1. You're using packaging pom, because no other packaging makes sense in maven? But you're not actually using the POM itself here?
1. How do you plan on using the assemblies.zip and rpm in a docker image?
    1. What exactly does a dockerfile look like in this case? That would help us define what a jib build could (if possible) look like.
1. What can't this just be done with multiple modules, each module creating a new distribution:
```
- common-module : used by both apples/oranges, but no container created
- apples -> produces a container
- oranges -> produces a container
```

**Comment by xavipen** [comment]
1. That is correct. In the pom I define the dependencies and the project only contains some configuration files.

2. I am not trying to use assemblies or rpms together with jib. Sorry, if that was misleading. I am trying to use jib to generate a container like I am using maven-assembly-plugin to package the distribution as an assembly. 

3. I thing I see what you mean but I am afraid the would not fit the this case. In my previous example I had simplified the dependencies to just one but it actually could be more than one dependency. I will try to expand my previous example with a more detail description and comments:

Application code is in one maven project
 - processingApp: maven project containing the class with the Main

Processing implementation dependencies for apple distribution are somewhere else

 - apple-processor1: first dependency needed for apple distribution
 - apple-processor2: second dependency needed for apple distribution

Then maven projects to create/package distributions automatically are defined as needed and are totally decouple from the previous maven projects. This way the distributions can be delivered in many different ways depending on the needs:

- apple-dist-config1.jib: would generate a docker image using processingApp, apple-processor1 and apple-processor2 as dependencies and include as external files some specific configuration files in the project. The entry point would be to run a class in the processingApp that contains the main. All of this in a maven project with packaging pom because no other packaging makes sense so to say.

-apple-dist-config2.jib: like the previous one but with a different configuration.

-apple-golden-dist-config1.jib: Provides a distribution specific to golden apples that needs an additional golden-apple-verifier dependency.

**Comment by chanseokoh** [comment]
I think this is what you can do as a workaround.

- apple-dist-config1 setup
```
$ mkdir apple-dist-config1 && cd apple-dist-config1
$ # Jib resists to run if there are no `.class` files, so create a bogus source.
$ mkdir -p src/main/java/com/example
$ cat > src/main/java/com/example/Bogus.java <<<'package com.example; public class Bogus {}'
```
- `pom.xml`:
```xml
<!-- Doesn't matter. Jib doesn't use JAR anyway -->
<packaging>jar</packaging> <!-- Or just omit it, because jar is the default. -->

<dependencies>
  <dependency>
    ...
    <artifactId>processingApp</artifactId>
  </dependency>
  <dependency>
    ...
    <artifactId>apple-processor1</artifactId>
  </dependency>
</dependencies>

    <!-- Jib configuration -->
    <configuration>
      <container>
       <mainClass>main.class.in.processing.app.Main</mainClass>
      </container>
    </configuration>
```

Then `$ mvn compile jib:build` (or `jib:dockerBuild`) should work and running the container should run the main class from "processingApp". Jib will place both `processingApp.jar` and `apple-processor1` (along with all transitive dependencies from them) into `/app/libs` in the image.

It's harmless to have `Bogus.class` in the built image, but if you don't like putting it, then you can possibly remove it using the [Jib Layer Filter Extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-maven).

**Comment by xavipen** [comment]
I have been playing around a bit and the final workaround I will be using is to use the packaging jar and then put the configuration files that should not be persistent in the src/main/resources. This way maven does not complain, jib can build the image and no bogus files need to be created. 

The persistent configurations are added using the extraDirectories configuration.

With this everything works like a charm, although it would be nice to be able to use packaging pom instead of jar. Even better would be to have a specific packaging for jib, like other other maven plugins do (i.e. tycho, or maven-bundle-plugin).

In any case, it works great as it is, once you get your head around it. :) The comments I made are just nice to have things.

**Comment by xavipen** [comment]
I would like to add a couple of configs that I have added that keep things cleaner on the maven side.

Just in case it may be useful for some other people:

    
    <plugin>
        <groupId>org.apache.maven.plugins</groupId>
	    <artifactId>maven-jar-plugin</artifactId>
	    <executions>
	        <execution>
			<id>default-jar</id>
			<phase>none</phase>
		</execution>
	    </executions>
    </plugin> 

    
    <plugin>
	  <groupId>org.apache.maven.plugins</groupId>
	  <artifactId>maven-install-plugin</artifactId>
	  <configuration>
		<skip>true</skip>
	  </configuration>
    </plugin>

    
    <plugin>
	  <groupId>org.apache.maven.plugins</groupId>
	  <artifactId>maven-deploy-plugin</artifactId>
	  <configuration>
		<skip>true</skip>
	  </configuration>
    </plugin>

**Comment by chanseokoh** [comment]
Thanks for the update and the tips!

**Comment by chanseokoh** [comment]
> no bogus files need to be created.

Oh, and you were right. I realized Jib just requires the directory `target/classes` to exist, so it is enough to have an empty directory `src/main/resources`.

**Comment by chanseokoh** [comment]
I will close this issue. This is not really the use case for which Jib is designed, and we don't think we will support this scenario unless more people asks for this. However, it's good to have a potential workaround and tips documented, so @xavipen thanks for bring this up!
