### ISSUE TITLE
Package a different jar when using containerizingMode packaged

### ISSUE THREAD

**Issue by sbaier1** [GoogleContainerTools/jib#2541]
**Environment**:

- *Jib version:* 2.4.0
- *Build tool:* Gradle, 5.5
- *OS:* macOS 10.15.5

**Description of the issue**:

It seems that it is currently not possible to manually specify a source jar within the build folder that jib should package. It always uses the jar-task's output, regardless of how it is parameterized (setting a classifier in jar-task leads to that classifier-named jar still being used by jib).

For example when running intermediate processors like proguard on the jar output which should then be packaged, it seems impossible to have the output jar of that task to be used directly by jib. 

It is possible to work around this by creating another intermediate gradle task that moves around the jar files but it's pretty inconvenient.

**Expected behavior**:

It should be possible to configure jib such that it containerizes my processed jar instead of directly using the `jar`-task output.

**Steps to reproduce**:

  1. Run any gradle plugin that creates another (processed) jar file, like proguard
  2. Configure jib build with containerizingMode packaged
  3. Try to get it to package the thin-jar from proguard

**Comment by loosebazooka** [comment]
I think you can do this with module indirection right now, create an empty module and use the proguard jar as a dependency. 

Or, if you're interested, write an extension to do it: github.com/GoogleContainerTools/jib-extensions.

We're also working on a cli to just package anything you want: github.com/GoogleContainerTools/jib/jib-cli
- the cli work is **in progress**, and there's no guarantee right now that we don't change things.

**Comment by chanseokoh** [comment]
Just an idea: another hack would be to add a manual step in Gradle to rename (move) the proguard jar to the jar name of jar-task before running the Jib task, but perhaps this is not a good practice.

**Comment by chanseokoh** [comment]
But an extension seems like a good idea that can really benefit other Jib users too. A configurable extension where you can specify a location of a JAR to replace the jar-task one, or even a very general extension where you can put any files into new layers. (Right now, existing files and/or layers can be removed using the [Jib Layer-Filter Extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-gradle).)

Given that we can use [Jib Layer-Filter Extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-gradle), another hack is to copy the proguard jar to an empty directory, set `jib.extraDirectories` to make Jib put the file into the image, configure `jib.container.extraClasspath` to put the proguard jar in the runtime Java classpath, and use the layer-filter extension to remove the original jar layer.

**Comment by sbaier1** [comment]
> Just an idea: another hack would be to add a manual step in Gradle to rename (move) the proguard jar to the jar name of jar-task before running the Jib task, but perhaps this is not a good practice.

i implemented this and while it works, it honestly feels a bit wrong and prone to errors

> Or, if you're interested, write an extension to do it: https://github.com/GoogleContainerTools/jib-extensions.

This looks like the more correct way to do it for now; i'll take a look and submit an extension if i do build one, thanks.

**Comment by time4tea** [comment]
@sbaier1 - Are you able to share the configuration that you used to get jib to package a proguarded application. it would be incredibly useful. Thank you!
