### ISSUE TITLE
Obtaining project build output files failed when using finalName

### ISSUE THREAD

**Issue by tomikmar** [GoogleContainerTools/jib#2565]
**Environment**:

- *Jib version:* 2.4.0
- *Build tool:* maven:3.6.3-amazoncorretto-11
- *OS:* Amazon Linux 2

**Description of the issue**:
When spring-boot-maven-plugin finalName is used jib cannot find project build output file.

**Steps to reproduce**:

    mvn package jib:build ...

**`jib-maven-plugin` Configuration**: 
```xml
    <plugin>
         <groupId>org.springframework.boot</groupId>
         <artifactId>spring-boot-maven-plugin</artifactId>
         <configuration>
             <finalName>${project.artifactId}</finalName>
          </configuration>
    </plugin>

    <plugin>
           <groupId>com.google.cloud.tools</groupId>
           <artifactId>jib-maven-plugin</artifactId>
           <version>2.4.0</version>
           <configuration>
                 ....
                 <containerizingMode>packaged</containerizingMode>
            </configuration>
    </plugin>
```

**Log output**:

[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.4.0:build (default-cli) on project registry: Obtaining project build output files failed; make sure you have packaged your project before trying to build the image. (Did you accidentally run "mvn clean jib:build" instead of "mvn clean package jib:build"?): /home/builder/src/myapp/target/myapp-3.0.2-SNAPSHOT.jar.original -> [Help 1]

**Comment by chanseokoh** [comment]
Jib uses the JAR generated by `maven-jar-plugin`. Jib neither depends on `spring-boot-maven-plugin` nor uses a Spring Boot-specific JAR that the plugin repackages intentionally.

FYI, one should really avoid containerizing a fat/uber JAR, which is the case with Spring Boot repackaging.

**Comment by chanseokoh** [comment]
However, I think this is a bug in Jib. We will look into it next week.

**Comment by chanseokoh** [comment]
@tomikmar Jib 2.5.0 is released with the fix!

**Comment by tomikmar** [comment]
Thank you !!!
