### ISSUE TITLE
How to build image directly from an existed Dockerfile with jib.

### ISSUE THREAD

**Issue by liuhuagui** [GoogleContainerTools/jib#2576]
I already have a complex Dockerfile, but there is no docker daemon in my development environment. Converting Dockerfile to xml configuration is difficult work, but I also hope to use Dockerfile build image with jib without docker daemon.

**Comment by loosebazooka** [comment]
It's hard to say without knowing what's in your dockerfile. Perhaps we will be able to help if you provide us with more information.

Jib does not build using dockerfile. It is a different build mechanism that produces container images.

**Comment by liuhuagui** [comment]
Thanks, I don't know if there is a corresponding tool to directly convert the Dockerfile to jib configuration

**Comment by loosebazooka** [comment]
There is not. Again, we cannot help you without more information.

**Comment by liuhuagui** [comment]
I understand, thank you, I will try it myself
