### ISSUE TITLE
Gradle plugin outputs progress to Jenkins console

### ISSUE THREAD

**Issue by sergeykad** [GoogleContainerTools/jib#2601]
**Environment**:

- *Jib version:* 2.4.0
- *Build tool:* Gradle 6.4
- *OS:* Linux

**Description of the issue**:
Jib prints progress to Jenkins console. Gradle option `--console=plain` is also ignored.
After some additional digging I fount that there is a separate `jib.console` option, but having such configuration on a plugin level seems controversial.
 
```
Executing tasks:
[======                        ] 19.5% complete
> pulling base image manifest
> building dependencies layer
> pushing blob sha256:93e7881491435e7cd110b14fb...
> pushing blob sha256:ae7d1ea461238896bc30fc58d...
> pushing blob sha256:0ac309b3bb44fd5a03eafdf66...


Executing tasks:
[======                        ] 20.0% complete
> pulling base image manifest
> building dependencies layer
> pushing blob sha256:93e7881491435e7cd110b14fb...
> pushing blob sha256:ae7d1ea461238896bc30fc58d...
> pushing blob sha256:0ac309b3bb44fd5a03eafdf66...


Executing tasks:
[=======                       ] 22.8% complete
> pulling base image manifest
> building dependencies layer
> pushing blob sha256:ae7d1ea461238896bc30fc58d...
> pushing blob sha256:0ac309b3bb44fd5a03eafdf66...
```

**Expected behavior**:
Jib will not print progress while running in Jenkins.

**Steps to reproduce**:

  1. Run Gradle Jib task from Jenkins

**Log output**: See output above

**Comment by loosebazooka** [comment]
see jib config for `jib.console`: https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#system-properties

**Comment by chanseokoh** [comment]
> Gradle option `--console=plain` is also ignored.

Jib [does observe `--console=plain`](https://github.com/GoogleContainerTools/jib/blob/f575c81188438f64deebb00a8f25e57df8fa9dc7/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java#L137-L139) and it has always worked correctly. I just tried Jib 2.4.0 + Gradle 6.4 and verify it worked; you can easily verify this by running Jib locally too. If it doesn't work on Jenkins, the only reason I can think of is the switch is overridden on Jenkins at a different level.

FYI, `jib.console` doesn't affect how the Gradle console works but only affects the Jib output. If `jib.console` resolves your issue, it can be a workaround.

**Comment by chanseokoh** [comment]
I am certain that Jib works disables the rich progress reporting when `--console=plain`. I'm closing this, as there has been no response. Feel free to update if the problem still exists.
