### ISSUE TITLE
make our dependency version stuff more friendly to dependabot

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#2602]
Right now in `build.gradle` we use [dependency versions](https://github.com/GoogleContainerTools/jib/blob/master/build.gradle#L51-L81).
If we use full dependency data, maybe the dependabot would work better.

```
project.ext.dependencyVersions = [
  GOOGLE_HTTP_CLIENT: '1.34.0',
  ...
```

could maybe be 

```
project.ext.dependencyStrings = [
  GOOGLE_HTTPS_CLIENT: "com.google.http-client:google-http-client:1.34.0"
  ...
]
```

We would probably need a splitter on `:` to make sure [`ensureTransitiveDependencyOverrides`](https://github.com/GoogleContainerTools/jib/blob/master/build.gradle#L85-L102) still works.

**Comment by mpeddada1** [comment]
Fixed with #2602
