### ISSUE TITLE
AWS ECR with jib.to.auth.username does not work

### ISSUE THREAD

**Issue by jomach** [GoogleContainerTools/jib#2627]
**Environment**:

- *Jib version: 2.4.0* 
- *Build tool: maven 3.6.3*
- *OS: MacOs* 

**Description of the issue**:

Running the command: 
`mvn compile com.google.cloud.tools:jib-maven-plugin:2.4.0:build Djib.to.auth.username=${AWS_ECR_KEY_USER} -Djib.to.auth.password=${AWS_ECR_SECRET} -Dimage=<MY IMAGE>` does not work and I get a 401 from the ECR registry 

**Expected behavior**: Should build

**Steps to reproduce**:
Create a mvn project with : 

```
<build>
<plugins>
    <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>jib-maven-plugin</artifactId>
        <version>${jib.version}</version>
        <executions>
            <execution>
                <phase>package</phase>
                <goals>
                    <goal>build</goal>
                </goals>
            </execution>
        </executions>
        <configuration>
            <from>
                <image>gcr.io/distroless/java:8</image>
            </from>
            <to>
                <image>
                    imageURI:/${project.artifactId}:${project.version}
                </image>
                <tags>latest</tags>
            </to>
        </configuration>
    </plugin>
</plugins>
</build>
```

**Log output**: are set up correctly. See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized for help: Unauthorized forimageURI: 401 Unauthorized -> [Help 1]

AWS_ECR_KEY_USER and AWS_ECR_SECRET are my aws credentials this seems not to work. If I don't pass the -Djib.to.auth.username it will grab it from amazon-ecr-credential-helper which in my case works and the credentials are the same. That's why I think this is a bug.

**Comment by jomach** [comment]
I tracked it down to : 

```
  private T call(URL url) throws IOException, RegistryException {
    String serverUrl = registryEndpointRequestProperties.getServerUrl();
    String imageName = registryEndpointRequestProperties.getImageName();

    Request.Builder requestBuilder =
        Request.builder()
            .setUserAgent(userAgent)
            .setHttpTimeout(JibSystemProperties.getHttpTimeout())
            .setAccept(registryEndpointProvider.getAccept())
            .setBody(registryEndpointProvider.getContent())
            .setAuthorization(authorization);
```
on the class RegistryEndpointCaller

**Comment by chanseokoh** [comment]
Hi @jomach,

I can vouch that `-Djib.to.auth.username/password` works with ECR or any registry.

From my limited experience with amazon-ecr-credential-helper, I remember it returns short-lived credentials and the username is always `AWS`. Can you check the output of `docker-credential-ecr-login get <<<your.ecr.registry.host`? For example with GCR,

```
$ docker-credential-ecr-login list
{"https://<redacted>.dkr.ecr.us-east-1.amazonaws.com":"AWS"}

$ docker-credential-ecr-login get <<< https://<redacted>.dkr.ecr.us-east-1.amazonaws.com
{"ServerURL":"https://<redacted>.dkr.ecr.us-east-1.amazonaws.com","Username":"AWS","Secret":"eyJw..."}
```

Therefore, probably it should be`-Djib.to.auth.username=AWS`. And I remember the secret (password) expires eventually, but I am pretty sure it will work if you pass the returned "Username" and "Secret" for `-Djib.to.auth.username/password`.

Lastly, I believe it's just a typo you made while writing a comment, but just in case, you missed `-` in `-Djib.to...`.
```diff
-mvn compile ... Djib.to.auth.username=...
+mvn compile ... -Djib.to.auth.username=...
```

**Comment by jomach** [comment]
Hello @chanseokoh  I think this is actually a bug that is kind of duplicate of https://github.com/GoogleContainerTools/jib/issues/1554 which was not resolved and the work around is to use this extra command line tool I see an issue there because: 

* if we are building on git actions we would nee to install all this binaries 
* imho we should be able to pass an aws key and secret and the plugin should do the rest :) 
* At least we should adjust the docs so that others do not have the same issue. I will come up with a pr.  the suggestion on  1554 works good

**Comment by chanseokoh** [comment]
> if we are building on git actions we would nee to install all this binaries

For GitHub Actions, previously I've successfully used [`aws-actions/amazon-ecr-login`](https://github.com/aws-actions/amazon-ecr-login).

> imho we should be able to pass an aws key and secret and the plugin should do the rest :)

I think you misunderstood here. Jib simply passes through the given username/password combination, whether Jib got it from a credential helper or on the command-line. There's no special processing at all. If the ECR server rejects the username/password combination that you think should work, it is their decision (which I can understand from my experience with other registry servers). As in #1554, the user [mistakenly thought they could use their "user credentials"](https://github.com/GoogleContainerTools/jib/issues/1554#issuecomment-473103876). There nothing really is anything Jib can do. All you need to do is to provide the username/password that the server can accept.

Generally speaking, the recommendation is to use a credential helper for any registries or environments.

**Comment by jomach** [comment]
Then let's close this.

**Comment by chanseokoh** [comment]
For those coming to this thread, see https://serverfault.com/questions/1004915/what-is-the-proper-way-to-log-in-to-ecr to and #2628 to understand the issue. However, we recommend using a credential helper instead of `jib.to.auth`.
