### ISSUE TITLE
Warning "'mainClass' configured in 'maven-jar-plugin' is not a valid Java class" appearing since jib 2.3

### ISSUE THREAD

**Issue by whut** [GoogleContainerTools/jib#2637]
**Environment**:

- *Jib version:* 2.4
- *Build tool:* Maven 3.6.3
- *OS:* Windows

**Description of the issue**:

Since jib 2.3 the build prints below warning when I use it with Spring Boot application:

```raw
[WARNING] 'mainClass' configured in 'maven-jar-plugin' is not a valid Java class: ${start-class}
```

Still later entry point is correctly inferred which is visible in log:

```raw
[INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.example.ExampleApplication]
```

**Expected behavior**:

The warning should not be printed, like before jib 2.3.

**Additional Information**: 

I believe this issue was introduced in pr #2457. Looks like it introduced some additional logging, which in this scenario creates odd experience: jib logs warnings about invalid mainClass, but is still able to set it correctly.

It can be seen as Spring Boot issue, as the Spring Boot sets `mainClass` in maven-jar-plugin to `${start-class}`. Still, even though the root cause is in Spring Boot, if maven-jar-plugin does not issue such warning, why should jib do it on its behalf. Better yet, (but I do not know anything about Maven internals), jib could try to resolve value of `${start-class}`, which I believe is empty, and issue warning only when that resolved value is invalid.

**Comment by loosebazooka** [comment]
Yeah, so we only print this warning because it can potentially cause misconfiguration. I understand that it may not apply to do, but we must consider the cost of failure vs the cost of inconvenience. Is the warning breaking your build?

**Comment by chanseokoh** [comment]
At least, you can manually set `<container><mainClass>` which will prevent Jib from trying to infer a main class by looking into various places including `maven-jar-plugin`.

**Comment by whut** [comment]
>Yeah, so we only print this warning because it can potentially cause misconfiguration. I understand that it may not apply to do, but we must consider the cost of failure vs the cost of inconvenience. Is the warning breaking your build?

If there is some issue with maven-jar-plugin configuration, it should report it, not jib. No, it is not breaking the build as it is just a warning.

> At least, you can manually set <container><mainClass> which will prevent Jib from trying to infer a main class by looking into various places including maven-jar-plugin.

I would like to avoid setting manually mainClass in each and every module I have, automatic detection is nice.

**Comment by chanseokoh** [comment]
Back in July and also today, I mulled over multiple options and pondered ensuing user experiences around them. For example, lowering the log level from WARN to INFO or DEBUG, printing the warning only when Jib fails to infer a main class in the end, etc.

> If there is some issue with maven-jar-plugin configuration, it should report it, not jib.

I get what you are saying, but I have a slightly different perspective. The `maven-jar-plugin` may not have an issue in itself, but when considering interactions with a different plugin, it can become an issue from the viewpoint of the other plugin. As a hypothetical example, a user may set a perfectly valid compiler arguments for `maven-compiler-plugin` that work just fine; clearly, it's not a misconfiguration in itself. However, another plugin doing some particular task may find it troublesome if the project is compiled with such arguments, and the plugin may show a warning to remove those arguments.

> No, it is not breaking the build as it is just a warning.

So, this is a warning and not causing any issue even in your case. Spring Boot is a major player for us, and a lot of people have tripped over the issue from `maven-jar-plugin` having `${start-class}` and filed issues on our Jib repo. These and considering other factors, I think showing the warning whenever this happens really helps minimizing frictions in Jib user experience and makes the user's lives easier. I hope you'll understand.

I'll close the issue, but feel free to update feedback. We can definitely revisit this if there are many more people having trouble with seeing the warning.

**Comment by listaction** [comment]
How _do_ you set a mainClass so that you can detect it correctly? It is not clear how to remove the warning.

**Comment by loosebazooka** [comment]
@listaction this bug is closed, please open a new one if you would like to troubleshoot an issue. In that new issue, include a detailed description of your problem and what you would like to achieve.

**Comment by moondowner** [comment]
@loosebazooka @listaction you've probably resolved this by now, but I'll add this comment for future people that may end up on this ticket while browsing for a solution:

Here's an example:

```            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.1.1</version>
                <configuration>
                    <container>
                        <mainClass>com.test.ServerApplication</mainClass>
                    </container>
                </configuration>
            </plugin>
```

**Comment by robert-gdv** [comment]
@chanseokoh : I think you should decide: Either you provide the automatic class detection as a reasonable working default or you require a definition.

The world currently tends to work with reasonable defaults. In this case, if the main class is wrong, it will surely come up in an integration test.
If every reasonably default comes with a warning "Hey we assumed this setting. But it is probably wrong.", I would disable warnings.

So either it works in the end, then don't warn. Or it doesn't work. Then break the build.

**Comment by listaction** [comment]
yes - all good. thanks !
