### ISSUE TITLE
How to add exsting .jar file to docker image using Jib maven plugin

### ISSUE THREAD

**Issue by vayila** [GoogleContainerTools/jib#2690]
I want to download .jar file and containerize the same .

How can i provide same jar name in jib maven plugin configuration.

**Comment by vayila** [comment]
> If you are talking about adding an extra JAR file (or just any arbitrary files) in addition to your main Java application built by your Maven setup, use the [`<extraDirectories>` feature](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#adding-arbitrary-files-to-the-image).
> 
> If you are talking about containerizing an application already packaged as a JAR by someone else (i.e., the application is independent of your Maven setup), then I think this is a dup of #1859. There are certainly a few ways to make this work using jib-maven-plugin (which I am not going to list), but this isn't the primary use case of jib-maven-plugin, as the plugin is for containerizing a Java application set up to built by Maven. Rather, as mentioned in #1859, this should be covered by Jib CLI that we are actively working on to revamp it. We are working on unpacking such a JAR and create a highly optimized image with multiple layers.

Can get code snippet for mentioning jar name and path for containerizingMode>packaged

**Comment by chanseokoh** [comment]
For `<containerizingMode>packaged`, changing a JAR name or path different than the JAR that Maven builds is specially not allowed. Jib Maven is intended to use the application built by Maven. It is not the intention of the plugin to allow people take an arbitrary JAR; that's a very abusive use of Jib Maven, I'd say. I think your use case really needs Jib CLI.

**Comment by vayila** [comment]
> For `<containerizingMode>packaged`, changing a JAR name or path to a different one than the JAR that Maven builds is specifically not allowed. Jib Maven is intended to use the application built by Maven. It is not the intention of the plugin to allow people take an arbitrary JAR; that's a very abusive use of Jib Maven, I'd say. I think your use case really needs Jib CLI.

I will use the jar built by maven only as part of build and how can i provide jar name to Jib plugin.
How it will look for jar file in packaged mode.

**Comment by chanseokoh** [comment]
Jib Maven takes the JAR built by maven-jar-plugin. Applying Jib should just work, and you shouldn't think about implementation details. Is your JAR you want to use is not built by maven-jar-plugin but by something else?

**Comment by vayila** [comment]
> Jib Maven takes the JAR built by maven-jar-plugin. Applying Jib should just work, and you shouldn't think about implementation details. Is your JAR you want to use is not built by maven-jar-plugin but by something else?

Built by maven-jar-plugin only and it is generated under /target folder

**Comment by chanseokoh** [comment]
If so, `<containerizingMode>packaged` and running `mvn package jib:build` (or `mvn package jib:dockerBuild`) should just work. Jib will use, e.g., `<project root>/target/helloworld-0.1.0.jar` and use it. If it isn't working, please provide us with more details and error logs and what's not working.

**Comment by vayila** [comment]
> If so, `<containerizingMode>packaged` and running `mvn package jib:build` (or `mvn package jib:dockerBuild` or `mvn package jib:buildTar` as necessary) should just work. Jib will take, e.g., `<project root>/target/helloworld-0.1.0.jar` and use it. If it isn't working, please provide us with more details and error logs and what's not working.

Getting Below error while running build.

[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.9:build (default-cli) on project interestservice: Execution default-cli of goal com.google.cloud.tools:jib-maven-plugin:0.9.9:build failed: Parameter 'to' is invalid: Invalid image reference: http://nexus-lms2020.isvapps02.netmagicsolutions.com/repository/lms2020/Venu:latest -> [Help 1]

Docker repo is empty and this is first image push

**Comment by chanseokoh** [comment]
The image reference specified in `<to><image>` is syntactically invalid. Remove the `http://` prefix from `<to><image>http://nexus-lms2020...`, so that it looks like `<to><image>nexus-lms2020...`.

For example, if you try to add `http://` using Docker, you'll get the same error:
```
docker tag \
    gcr.io/distroless/java \
    http://gcr.io/distroless/java
Error parsing reference: "http://gcr.io/distroless/java" is not a valid repository/tag: invalid reference format
```

Also, I see that your image reference container an uppercase letter ("V" in "Venu"), which isn't allowed. For example, if you try to use uppercase letter using Docker, you'll get an error:
```
$ docker tag \
    gcr.io/distroless/java \
    gcr.io/distroless/JAVA
Error parsing reference: "gcr.io/distroless/JAVA" is not a valid repository/tag: invalid reference format: repository name must be lowercase
```

And Jib 0.9.9 is really old. Use 2.5.2 is the latest as of now. Using 2.5.2 will give you a better error message when your image reference is syntactically wrong.

**Comment by vayila** [comment]
> The image reference specified in `<to><image>` is syntactically invalid. Remove the `http://` prefix from `<to><image>http://nexus-lms2020...`, so that it looks like `<to><image>nexus-lms2020...`.
> 
> For example, if you try to add `http://` using Docker, you'll get the same error:
> 
> ```
> $ docker tag \
>     gcr.io/distroless/java \
>     http://gcr.io/distroless/java
> Error parsing reference: "http://gcr.io/distroless/java" is not a valid repository/tag: invalid reference format
> ```
> 
> Also, I see that your image reference contains an uppercase letter ("V" in "Venu"), which isn't allowed. For example, if you try to use uppercase letters using Docker, you'll get an error:
> 
> ```
> $ docker tag \
>     gcr.io/distroless/java \
>     gcr.io/distroless/JAVA
> Error parsing reference: "gcr.io/distroless/JAVA" is not a valid repository/tag: invalid reference format: repository name must be lowercase
> ```
> 
> And Jib 0.9.9 is really old. 2.5.2 is the latest as of now. Using 2.5.2 will give you a better error message when your image reference is syntactically wrong.

[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.5.2:build (default-cli) on project interestservice: 503 Service Unavailable
[ERROR] <html>
[ERROR]   <head>
[ERROR]     <meta name="viewport" content="width=device-width, initial-scale=1">
[ERROR] 
[ERROR]   <style type="text/css">
[ERROR]   /*!
[ERROR]    * Bootstrap v3.3.5 (http://getbootstrap.com)
[ERROR]    * Copyright 2011-2015 Twitter, Inc.
[ERROR]    * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
[ERROR]    */
[ERROR]   /*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */
[ERROR]   html {
[ERROR]     font-family: sans-serif;
[ERROR]     -ms-text-size-adjust: 100%;
[ERROR]     -webkit-text-size-adjust: 100%;
[ERROR]   }
[ERROR]   body {
[ERROR]     margin: 0;
[ERROR]   }
[ERROR]   h1 {
[ERROR]     font-size: 1.7em;
[ERROR]     font-weight: 400;
[ERROR]     line-height: 1.3;
[ERROR]     margin: 0.68em 0;
[ERROR]   }
[ERROR]   * {
[ERROR]     -webkit-box-sizing: border-box;
[ERROR]     -moz-box-sizing: border-box;
[ERROR]     box-sizing: border-box;
[ERROR]   }
[ERROR]   *:before,
[ERROR]   *:after {
[ERROR]     -webkit-box-sizing: border-box;
[ERROR]     -moz-box-sizing: border-box;
[ERROR]     box-sizing: border-box;
[ERROR]   }
[ERROR]   html {
[ERROR]     -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
[ERROR]   }
[ERROR]   body {
[ERROR]     font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
[ERROR]     line-height: 1.66666667;
[ERROR]     font-size: 13px;
[ERROR]     color: #333333;
[ERROR]     background-color: #ffffff;
[ERROR]     margin: 2em 1em;
[ERROR]   }
[ERROR]   p {
[ERROR]     margin: 0 0 10px;
[ERROR]     font-size: 13px;
[ERROR]   }
[ERROR]   .alert.alert-info {
[ERROR]     padding: 15px;
[ERROR]     margin-bottom: 20px;
[ERROR]     border: 1px solid transparent;
[ERROR]     background-color: #f5f5f5;
[ERROR]     border-color: #8b8d8f;
[ERROR]     color: #363636;
[ERROR]     margin-top: 30px;
[ERROR]   }
[ERROR]   .alert p {
[ERROR]     padding-left: 35px;
[ERROR]   }
[ERROR]   a {
[ERROR]     color: #0088ce;
[ERROR]   }
[ERROR] 
[ERROR]   ul {
[ERROR]     position: relative;
[ERROR]     padding-left: 51px;
[ERROR]   }
[ERROR]   p.info {
[ERROR]     position: relative;
[ERROR]     font-size: 15px;
[ERROR]     margin-bottom: 10px;
[ERROR]   }
[ERROR]   p.info:before, p.info:after {
[ERROR]     content: "";
[ERROR]     position: absolute;
[ERROR]     top: 9%;
[ERROR]     left: 0;
[ERROR]   }
[ERROR]   p.info:before {
[ERROR]     content: "i";
[ERROR]     left: 3px;
[ERROR]     width: 20px;
[ERROR]     height: 20px;
[ERROR]     font-family: serif;
[ERROR]     font-size: 15px;
[ERROR]     font-weight: bold;
[ERROR]     line-height: 21px;
[ERROR]     text-align: center;
[ERROR]     color: #fff;
[ERROR]     background: #4d5258;
[ERROR]     border-radius: 16px;
[ERROR]   }
[ERROR] 
[ERROR]   @media (min-width: 768px) {
[ERROR]     body {
[ERROR]       margin: 4em 3em;
[ERROR]     }
[ERROR]     h1 {
[ERROR]       font-size: 2.15em;}
[ERROR]   }
[ERROR] 
[ERROR]   </style>
[ERROR]   </head>
[ERROR]   <body>
[ERROR]     <div>
[ERROR]       <h1>Application is not available</h1>
[ERROR]       <p>The application is currently not serving requests at this endpoint. It may not have been started or is still starting.</p>
[ERROR] 
[ERROR]       <div class="alert alert-info">
[ERROR]         <p class="info">
[ERROR]           Possible reasons you are seeing this page:
[ERROR]         </p>
[ERROR]         <ul>
[ERROR]           <li>
[ERROR]             <strong>The host doesn't exist.</strong>
[ERROR]             Make sure the hostname was typed correctly and that a route matching this hostname exists.
[ERROR]           </li>
[ERROR]           <li>
[ERROR]             <strong>The host exists, but doesn't have a matching path.</strong>
[ERROR]             Check if the URL path was typed correctly and that the route was created using the desired path.
[ERROR]           </li>
[ERROR]           <li>
[ERROR]             <strong>Route and path matches, but all pods are down.</strong>
[ERROR]             Make sure that the resources exposed by this route (pods, services, deployment configs, etc) have at least one pod running.
[ERROR]           </li>
[ERROR]         </ul>
[ERROR]       </div>
[ERROR]     </div>
[ERROR]   </body>
[ERROR] </html>
[ERROR] 
[ERROR] -> [Help 1]

**Comment by chanseokoh** [comment]
This typically means you typed a wrong image reference (though syntactically correct) in `<to><image>` and thus resulting in not hitting a Docker registry endpoint.

To give you a simple analogy, it is very much like you typed a wrong web server URL in the address bar of your web browser and thus the web server returned ”404 page not found". (For example, you typed `www.test.com/not-right.html` instead of `www.test.com/correct/page.html`.) That is, you just hit a wrong web server endpoint.

I think the quickest way to resolve this in your case is to contact your Docker registry administrator and get some direct help. Ask them what is the exact URL of the Docker registry endpoint and what exactly you should type as an image reference in order to successfully push an image. Take note of things like hostname, port, protocol (http:// or https://), image repository name convention, etc. Just ask what image reference you should use, and check if running `$ docker push <image reference they tell you to use>` works first.
