### ISSUE TITLE
Incorrect application jar in /app/classpath/ (packaged mode)

### ISSUE THREAD

**Issue by tomikmar** [GoogleContainerTools/jib#2692]
**Environment**:

- *Jib version:* 2.5.1
- *Build tool:* maven:3.6.3-amazoncorretto-11
- *OS:* Amazon Linux 2

**Description of the issue**:
After upgrading from 2.4.0 to 2.5.1 incorrect file is put in /app/classpath/ in packaged mode. It looks like Spring Boot output file (with dependencies). As the result dependencies are duplicated and main class if different (Spring Boot one). See jar size below:

2.5.1

> docker run -it --entrypoint "" dockerreg.abc.com/def/backend/my-service bash
> $ cd app
> $ ls -lh classpath/
> total 90M
> **-rw-r--r-- 1 root root 90M Jan  1  1970 my-service-2.1.1.6.jar**
> $ ls -lh libs/
> total 89M
> -rw-r--r-- 1 root root 121K Jan  1  1970 HdrHistogram-2.1.11.jar
> -rw-r--r-- 1 root root  30K Jan  1  1970 LatencyUtils-2.0.3.jar
> -rw-r--r-- 1 root root  30K Jan  1  1970 accessors-smart-1.2.jar
> ...
> 

2.4.0

> docker run -it --entrypoint "" dockerreg.abc.com/def/backend/my-service bash
> $ cd app/
> $ ls -lh classpath/
> total 144K
> **-rw-r--r-- 1 root root 142K Jan  1  1970 my-service-2.1.1.5.original.jar**
> $ ls -lh libs/
> total 89M
> -rw-r--r-- 1 root root 121K Jan  1  1970 HdrHistogram-2.1.11.jar
> -rw-r--r-- 1 root root  30K Jan  1  1970 LatencyUtils-2.0.3.jar
> -rw-r--r-- 1 root root  30K Jan  1  1970 accessors-smart-1.2.jar
> ...
> 

**Steps to reproduce**:
mvn -B --also-make --projects my-service clean package jib:build

**`jib-maven-plugin` Configuration**: 
pom.xml
```xml
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>2.5.1</version>
                    <configuration>
                        <from>
                            <image>dockerreg.abc.com/def/build/my-app-base-image:latest</image>
                        </from>
                        <to>
                            <image>dockerreg.abc.com/def/backend/my-${project.artifactId}</image>
                        </to>
                        <containerizingMode>packaged</containerizingMode>
                        <skip>true</skip>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
```

my-service/pom.xml
```
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <configuration>
                    <skip>false</skip>
                    <container>
                        <entrypoint>/wrapper.sh, com.abc.my.service.MyApplication</entrypoint>
                    </container>
                </configuration>
            </plugin>
        </plugins>
    </build>
```

**Comment by chanseokoh** [comment]
This is embarrassing. I think the NPE fix (#2688) added in 2.5.1 wasn't a correct fix; it only avoided NPE and wrongly assumed that Spring Boot isn't configured. I expect that 2.5.1 will use the thin JAR if you add an empty `<configuration>` block to `spring-boot-maven-plugin` (the workaround you suggested in #2687).

**Comment by chanseokoh** [comment]
>  I expect that 2.5.1 will use the thin JAR if you add an empty `<configuration/>` block to spring-boot-maven-plugin (the workaround you suggested in #2687).

I can confirm this. I was able to reproduce both #2688 with 2.5.0 (the NPE issue) and this issue with 2.5.1 using [your sample](https://github.com/GoogleContainerTools/jib/issues/2687#issuecomment-671922147). (Thanks for sharing a test sample!) So the workaround for both #2688 and this is to have an empty `<configuration/>`, but since this is a fairly significant issue, we'll fix it as soon as possible.

**Comment by chanseokoh** [comment]
@tomikmar 2.5.2 is released with the correct fix.
