### ISSUE TITLE
Convert Gradle config parameters (such as jib.to.image and jib.to.tags) to use Property type

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2727]
I tried using `gradle-git-properties` Gradle plugin to set a git commit as an image tag. Following their [plugin doc](https://github.com/n0mer/gradle-git-properties),
```gradle
plugins {
    id 'com.gorylenko.gradle-git-properties' version '2.2.3'
    id 'com.google.cloud.tools.jib' version '2.5.0'
    id 'java'
}

gitProperties {
      extProperty = 'gitProps' // git properties will be put in a map at project.ext.gitProps
}
// make sure the generateGitProperties task always executes (even when git.properties is not changed)
generateGitProperties.outputs.upToDateWhen { false }

// make sure generateGitProperties task to execute before accessing generated properties
task printGitProperties(dependsOn: 'generateGitProperties') {
    doLast {
        println "git.commit.id.abbrev=" + project.ext.gitProps['git.commit.id.abbrev']
    }
}
```
Running `./gradlew printGitProperties` works as documented.

The doc also shows an example using Groovy GString lazy evaluation.
```gradle
jar {
  manifest {
    attributes(
      // Use GString lazy evaluation to delay until git properties are populated
      'Build-Revision': "${-> project.ext.gitProps['git.commit.id.abbrev']}"

      // OTOH, the following code fails with "Cannot get property 'gitProps' on extra properties extension as it does not exist"
      //'Build-Revision': project.ext.gitProps['git.commit.id.abbrev']
    )
  }
}
```
I confirm `./gradlew jar` works and the `MANIFEST.MF` in the JAR contains the `Build-Revision` attribute.

However, we still can't use GString lazy evaluation with most of the Jib properties. It fails with "Cannot get property 'gitProps' on extra properties extension as it does not exist."

I think it makes sense to convert `jib.to.image` and `jib.to.tags` to `Property<String>` and `SetProperty<String>`. `Property<String>` has a two `.set()` methods, one with signature `.set(String)` and the other with `.set(Provider<String>)`, which I think will allow configuring these values lazily.

**Comment by loosebazooka** [comment]
Yeah I don't think you can use GString lazy eval, but you can use `Provider<String>` to basically do the same thing?

**Comment by chanseokoh** [comment]
> convert jib.to.image and `jib.to.tags` to `Property<String>` and `SetProperty<String>`.

Much like we currently use `Property<String>` for `jib.containerizingMode`. (On hindsight, I think I just used `Property<String>` instead of `String` for it without thinking much only after seeing there existed `Property<Boolean>`.) https://github.com/GoogleContainerTools/jib/blob/9a39d8f6bd640064d6ff3460a313c99a3a9fc190/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibExtension.java#L96

**Comment by loosebazooka** [comment]
once this is released, we should also update the answer here: https://stackoverflow.com/questions/59588495/jib-plugin-not-able-to-access-project-version-as-updated-by-another-gradle-plugi/59631660#59631660
