### ISSUE TITLE
<platform> configuration should be configurable with system properties

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2742]
For example, `-Djib.from.platforms=... list of platforms ...`.

Note that `architecture` and `os` are required sub-properties. Need to think about the format. Also consider #2471.

**Comment by LeaTaka** [comment]
Any progress on this? 

I like to decouple the choice of platform from my app.
So for example this would be handy -->
-Djib.from.image=arm32v7/adoptopenjdk:11-jre-hotspot
-Djib.from.platforms.platform.architecture=arm
-Djib.from.platforms.platform.os=linux

**Comment by chanseokoh** [comment]
If your main goal is to decouple the platform settings, then for now, you can easily [parameterize](https://stackoverflow.com/questions/7513319/passing-command-line-arguments-from-maven-as-properties-in-pom-xml) them through Maven properties with default values.

**Comment by LeaTaka** [comment]
Hey, thanks for your reply! 

I use parameterization for most settings, however for the deeply nested platform settings like 'architecture' and 'os', I can't get it to work. In my example below I'll show you what works and what doesn't.

POM settings that work well:
  <from>
    <image>arm32v7/adoptopenjdk:11-jre-hotspot</image>
    <platforms>
      <platform>
        <architecture>arm</architecture>
        <os>linux</os>
      </platform>
    </platforms>
  </from>

Above settings replaced by parameters in mvn command:
-Djib.from.image=arm32v7/adoptopenjdk:11-jre-hotspot (THIS WORKS)
-Djib.from.platforms.platform.architecture=arm (DOESN'T GET PICKED UP)
-Djib.from.platforms.platform.os=linux (DOESN'T GET PICKED UP)

Maybe I got the explanation in the docs wrong --> (i.e. -Djib.parameterName[.nestedParameter.[...]]=value), any ideas?

**Comment by chanseokoh** [comment]
So what I was talking about was to use standard Maven features to accomplish the same effect of using built-in Jib system and Maven properties. For the built-in Jib properties, our code reads system and Maven properties like [this](https://github.com/GoogleContainerTools/jib/blob/4cd234ad796329dd8b98cfd225f93ce08fb98ecf/jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/JibPluginConfiguration.java#L533), but as you observed, this isn't defined for the `<platform>` configurations yet. So, what you can do with standard Maven features is like:

```xml
<properties>
  <!-- Define Maven properties. These are arbitrary Maven properties, so you can name them however you want. -->
  <jib.platform-arch>amd64</jib.platform-arch> <!-- most likely the default value you want to use -->
  <jib.platform-os>linux</jib.platform-os>
</properties>

...

   <!-- Jib configuration -->
   <from>
     <image>arm32v7/adoptopenjdk:11-jre-hotspot</image>
     <platforms>
       <platform>
         <architecture>${jib.platform-arch}</architecture>
         <os>${jib.platform-os}</os>
       </platform>
     </platforms>
   </from>
```
Then, when you run Jib, by default the platform will be `linux/amd64`. If you want to override the Maven properties, you'd do, e.g.,
```
$ ./mvnw -Djib.platform-arch=arm jib:build
```

**Comment by StringKe** [comment]
How to set up multiple platforms?
```
-Djib.from.platforms[0].os=linux -Djib.from.platforms[0].architecture=amd64 -Djib.from.platforms[1].os=linux -Djib.from.platforms[1].architecture=arm64

or

-Djib.from.platforms.os=linux -Djib.from.platforms.architecture=amd64 -Djib.from.platforms.os=linux -Djib.from.platforms.architecture=arm64
```

**Comment by chanseokoh** [comment]
@StringKe it's a list property. For example, `-Djib.from.platforms=linux/amd64,linux/arm64`.

https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/CHANGELOG.md#added-2
