### ISSUE TITLE
Enable accepting OCI image index for multi-platform image building

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2749]
However, I think this is low priority, as I speculate in practice registries will convert OCI manifest lists to Docker format when a client reports it only accepts Docker manifest lists. But if there are cases where a registry doesn't do it, we can revisit this.

Note this is different from #2748, which is for pushing an OCI image index.

**Comment by bogdanbrindusan** [comment]
This is blocking me from using Docker images hosted in icr.io - IBM's Container Registry.
I'm not looking to build multi-platform, just to get the base image from there.

The error I'm getting is:
```
Execution failed for task ':jibDockerBuild'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Tried to pull image manifest for icr.io/appcafe/ibm-semeru-runtimes:certified-17-jdk-ubi-minimal but failed because: OCI index found, but accept header does not support OCI indexes
```

I'd really appreciate any effort in releasing this sooner, rather than later.

**Comment by chanseokoh** [comment]
See https://github.com/GoogleContainerTools/jib/issues/3700#issuecomment-1168790728

**Comment by mpeddada1** [comment]
thank you for your contribution @rquinio! `jib-gradle-plugin` and `jib-maven-plugin` 3.3.0 have been released with this feature.
