### ISSUE TITLE
 Could not find or load main class org.springframework.boot.loader.PropertiesLauncher

### ISSUE THREAD

**Issue by SamPeng87** [GoogleContainerTools/jib#2762]
I have use jib in gradle plugin,version is 2.5.0

I can success build docker image.But can't running when run it with docker command.

```
Error: Could not find or load main class org.springframework.boot.loader.PropertiesLauncher
Caused by: java.lang.ClassNotFoundException: org.springframework.boot.loader.PropertiesLauncher
```
I think i not use any special setting

```
    jib {
        from {
            auth {
                username = "${ArtifactoryUsername}"
                password = "${ArtifactoryPassword}"
            }
        }
        to {
            image = imageName
            tags = tagsList
            auth {
                username = "${ArtifactoryUsername}"
                password = "${ArtifactoryPassword}"
            }
        }
        container {
            mainClass = 'org.springframework.boot.loader.PropertiesLauncher'
        }
    
```

I have run in container

```
java -cp /app/libs/*:/app/classpath/ org.springframework.boot.loader.PropertiesLauncher
```

have any idea to resolve  this problem?

**Comment by chanseokoh** [comment]
I think this is because Spring Boot packages additional classes (including `PropertiesLauncher`) to its fat JAR in addition to your application classes and has its proprietary way of launching an application. Do you have to use Spring Boot's `PropertiesLauncher`? Can't you directly `container.mainClass` to your application main class?

**Comment by SamPeng87** [comment]
@chanseokoh thank your reply,because we wan't not change any other build config。I did not reply for a long time so I researched it myself, PropertiesLauncher is gradle repackage action add some depend in fat jar。now，I use main clas ，it is good work  now。
