### ISSUE TITLE
Disable cyan coloring in build output when `--console=plain` is used.

### ISSUE THREAD

**Issue by mpeddada1** [GoogleContainerTools/jib#2764]

**Comment by chanseokoh** [comment]
Affects both Maven and Gradle. Doesn't matter if it's `--console=plain` (Gradle), `--batch-mode` (`-B`) (Maven), or `-Djib.console=plain`.

We should also clean up [code](https://github.com/GoogleContainerTools/jib/pull/2739/files#diff-96ad525f118ecaed9517fc980ce1f07cR381) that we introduced in `JibPluginTest` to remove color sequence from a string.

```java
String cleanOutput = output.replace("\u001B[36m", "").replace("\u001B[0m", "");
```

Details: https://github.com/GoogleContainerTools/jib/pull/2739#discussion_r488110919

There may be more places where we color output.

**Comment by dinvlad** [comment]
Any updates here? Thanks

**Comment by chanseokoh** [comment]
It's a low priority although I think it's an easy fix. We're pretty overloaded, and we'd appreciate contributions. :smile:

**Comment by dinvlad** [comment]
Thanks for the update! In the meantime, I was able to work around it using
```
./gradlew jib --console=plain | perl -pe 's/\x1b\[[0-9;]*[mG]//g'
```

**Comment by vinod-tahelyani** [comment]
@chanseokoh I would like to take this.
One simple solution that I have is to replace `"\u001B[36m"` and `"\u001B[0m"` with `""`, here
https://github.com/GoogleContainerTools/jib/blob/9f4c93cf6b66cc67b674ff8f574892c1bf148c7a/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java#L339

or if there is any way to access ConsoleOutput from https://github.com/GoogleContainerTools/jib/blob/9f4c93cf6b66cc67b674ff8f574892c1bf148c7a/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/JibBuildRunner.java#L76
??

**Comment by mpeddada1** [comment]
Hey @vinod-tahelyani, thanks for looking into this! We were thinking that this change could be even more effective if there was a way to filter out any color (not just cyan) in this [the PlainConsoleLogger](https://github.com/GoogleContainerTools/jib/blob/ab0bc65a06d8f1cc6e4ab56d987bbc765b054326/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/logging/PlainConsoleLogger.java#L46)? This would allow us to touch all parts of the code that use the plain console output. Looking at this [stackoverflow link](https://stackoverflow.com/questions/5762491/how-to-print-color-in-console-using-system-out-println, it seems like most colors follow a similar regex pattern.

**Comment by chanseokoh** [comment]
Reopening to track the cleanup task: https://github.com/GoogleContainerTools/jib/issues/2764#issuecomment-693512019
