### ISSUE TITLE
Feature Request: Allow setting Architecture and OS when an image is built from scratch.

### ISSUE THREAD

**Issue by mpeddada1** [GoogleContainerTools/jib#2765]
The user may want to set their own architecture and os rather than use the default values (`amd64` and `linux`) when building an image from scratch. This is currently not supported in Jib.

**Comment by chanseokoh** [comment]
Fixed by #2778.

**Comment by loosebazooka** [comment]
For `jib-core` users this is fixed in `0.16.0`
