### ISSUE TITLE
Use of outdated Debian 9 images - update to Debian 10

### ISSUE THREAD

**Issue by mayrstefan** [GoogleContainerTools/jib#2775]
**Description of the issue**:
Jib still uses Distroless Images based on Debian 9 (stretch, oldstable currently). Debian 9 has already reached its regular end of life two months ago and might not get all security updates. E.g. Java 11 like mentioned in  https://github.com/GoogleContainerTools/distroless/issues/524

**Expected behavior**:
Jib should be updated to use the more up-to-date  *-debian10 images.
Also examples like in [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#where-is-bash) or [Jib CLI](https://github.com/GoogleContainerTools/jib/blob/master/jib-cli/README.md) should be updated to avoid insecure images.

**Comment by chanseokoh** [comment]
@mayrstefan @gredler @Saljack we released Jib build plugins 3.0 that switched the base image from Distroless to `adoptopenjdk` (and `jetty` for WAR).

For the details about the breaking change, see [this](https://github.com/GoogleContainerTools/jib/blob/master/docs/default_base_image.md).
