### ISSUE TITLE
jib-gradle-plugin fails when the platform/architecture is not amd64.

### ISSUE THREAD

**Issue by jtgasper3** [GoogleContainerTools/jib#2781]
**Environment**:

- *Jib version: 2.5.0 
- *Build tool: Gradle
- *OS: OS X

**Description of the issue**: The jib-gradle-plugin is not replacing the given platform config but adding to an existing collection[1]. Jib-core requires exactly one in the collection[2].

Side note: I realize multi-platform builds are not supported yet. I'm just trying to do a single non-amd64 build.

BTW, Thanks for the great tool!

[1] https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/PlatformParametersSpec.java#L45
[2] https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/api/JibContainerBuilder.java#L597

**Expected behavior**:
Jib should download the arm64-based base image and build.

**Steps to reproduce**:

  1. Setup the jib config provided below.
  2. `./gradlew bootJar jibDockerBuild`
  3. Fail

**`jib-gradle-plugin` Configuration**: 
```groovy
jib {
    from {
        image = "amazoncorretto:11"
        platforms {
            platform {
                architecture = 'arm64'
                os = 'linux'
            }
        }
    }
}
```

**Log output**: 
```
> multi-platform image building is not yet supported
```

**Additional Information**: 
The platforms collection has 2 items even though I'm only specifying 1 in the config. I'm not a gradle internals dev, but I'm assuming this gets invoked regardless of if I try to override it in the config or not: https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/BaseImageParameters.java#L48

**Comment by chanseokoh** [comment]
Working on fixing this. The current workaround is to use the digest of the arm64/linux image. In your case, based on the `amazoncorretto:11` manifest list,
```
$ docker manifest inspect amazoncorretto:11
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
   "manifests": [
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 742,
         "digest": "sha256:f7a7126645e48c54535e36bcae9a7fbeba6fd5fc7dbb0071ce4534cad101616a",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
         "size": 742,
         "digest": "sha256:e8214c624c083bd6e62079474645c3d6228cacee4583f070f14b8919fa076125",
         "platform": {
            "architecture": "arm64",
            "os": "linux",
            "variant": "v8"
         }
      }
   ]
}
```
it will be
```
from.image = 'amazoncorretto:11@sha256:e8214c624c083bd6e62079474645c3d6228cacee4583f070f14b8919fa076125'
```

**Comment by jtgasper3** [comment]
Thanks for the suggestion, @chanseokoh. That's what I did before I reached out on Gitter to ensure I was not completely crazy.

I noticed you already have a fix in the works. I appreciate the effort!

**Comment by loosebazooka** [comment]
Hi @jtgasper3 this should be fixed in the latest jib gradle bugfix release (2.5.1)
