### ISSUE TITLE
Upgrading Jib results in creating a different image due to Jib version written in container config

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#2810]
The root cause of the recent integration failure in #2809.

```
  "history": [
    {
      "created": "2020-07-27T23:41:26.054263591Z",
      "created_by": "/bin/sh -c #(nop) ADD file:b30c8ba7ffe694c4cd200cdcfc75a57a099c28f5cc97c74b6e5c0cf2bfcc5962 in / "
    },
    {
      "created": "2020-07-27T23:41:26.640971697Z",
      "created_by": "/bin/sh -c #(nop)  CMD [\"sh\"]",
      "empty_layer": true
    },
    {
      "created": "1970-01-01T00:00:00Z",
      "author": "Jib",
      "created_by": "jib-maven-plugin:2.6.1-SNAPSHOT",
      "comment": "dependencies"
    },
```

Need to verify, but it's likely that this has been like this since the beginning. Not sure if we should take out the version info. Up for discussion.

**Comment by loosebazooka** [comment]
I'm trying to remember, but I think the last time we talked about this, we said we can only remain reproducible for the same version of jib. Putting the version info in the history actually helps users recreate an image -- as we cannot make strong guarantees across versions of jib for build output.

**Comment by chanseokoh** [comment]
That makes a lot of sense. Closing.
