### ISSUE TITLE
Set environment variables for credHelper

### ISSUE THREAD

**Issue by EugenDueck** [GoogleContainerTools/jib#2814]
I want to use the "ecr-login" credHelper for both `from` and `to`, but I need to use different environment variables (`AWS_PROFILE` in my case), because the IAM is different in each case. If it is possible somehow, I would like to know, and if not, I would like to request this feature (just like e.g. `environment` can be set for `dockerClient`).

As a workaround, I will now try to run the credHelper manually and pass in username/password values via system properties (`-Djib.to.auth.username=...`)

**Comment by chanseokoh** [comment]
This is an interesting use case.

As another coarse workaround, you can write two wrapper scripts `ecr-login-foo` and `ecr-login-bar` (probably OK to have a `.sh` suffix) that just sets `AWS_PROFILE` and delegates to `ecr-login`. For example,
```sh
#!/bin/sh

AWS_PROFILE=profile-foo
exec ecr-login $*  # "exec" is not really required; I just do it to replace the sh process.
```
Then having `jib.{from|to}.credHelper='ecr-login-foo'` will probably work. Still ugly. Just an idea.

**Comment by EugenDueck** [comment]
@chanseokoh Thanks for the idea - I actually had the same idea, but ended up being able to push the base image into the same ecr registry as the output image. So problem solved for me, but by working around it. But I think this is a valid, if not that common, use case, so I would like to leave this as a feature request.

**Comment by vinod-tahelyani** [comment]
@chanseokoh I would like to help in this. I have researched a bit and found that, we can get credentials specific to AWS_PROFILE by setting AWS_PROFILE=profile-foo, before calling start in https://github.com/GoogleContainerTools/jib/blob/9f4c93cf6b66cc67b674ff8f574892c1bf148c7a/jib-core/src/main/java/com/google/cloud/tools/jib/registry/credentials/DockerCredentialHelper.java#L134

something like
```
ProcessBuilder processBuilder = processBuilderFactory.apply(credentialHelperCommand);
processBuilder.environment().put("AWS_PROFILE", awsProfile);
Process process = processBuilder.start();
```
But I have few questions

1. How do we set aws profiile in from and to, Is the below config ok?
```
jib {
  from {
    image = '0123456789.dkr.ecr.us-east-1.amazonaws.com/my-base-image:latest'
    credHelper = 'ecr-login'
    awsProfile = 'ecr-user1'
  }
  to {
    image = '0123456789.dkr.ecr.us-east-1.amazonaws.com/my-target-image:latest'
    credHelper = 'ecr-login'
    awsProfile = 'ecr-user2'
  }
}
```

2. How do we get awsProfile in DockerCredentialHelper.java?

**Comment by chanseokoh** [comment]
@vinod-tahelyani thanks for your interest on this.

What we want is a general way to provide any environment variables when running a credential helper. Maybe something like
```
jib.from.credHelper {
  helper = 'ecr-login'
  // map property
  environment = [
    AWS_PROFILE: 'ecr-user2',
    FOO: 'bar'
  ]
}
```
while still maintaining backward compatibility with the current usage: `jib.from.credHelper = 'ecr-login'`.

**Comment by vinod-tahelyani** [comment]
@chanseokoh I have linked a PR, which is solution for gradle. Pls look into, if it looks ok then I'll add solution for maven and corresponding test as well.
Thanks

**Comment by chanseokoh** [comment]
Haven't heard back from @vinod-tahelyani about their PR (#3093) for months. Will close the PR due to inactivity. This issue is again up for a *"good first issue"*, welcoming contributions.

**Comment by tobiade** [comment]
Hey @chanseokoh I'm happy to pick this up. Will get a PR out soon!

**Comment by tobiade** [comment]
@chanseokoh I've raised #3575 to fix this - please have a look when you can. Thanks!

**Comment by elefeint** [comment]
[jib-maven-plugin v3.2.1](https://github.com/GoogleContainerTools/jib/releases/tag/v3.2.1-maven) released.

**Comment by alexanderankin** [comment]
so i'm using this the exact way it is referred to in this issue (i just tried to supply what the CredHelperParameters class looked like it wanted):

```
jib.from.credHelper {
  helper = 'ecr-login'
  // map property
  environment = [
    AWS_PROFILE: 'ecr-user2',
    FOO: 'bar'
  ]
}
```

but it doesn't seem like it works - is there a working example? Is this working and I just have to keep trying things until it works fro me too?

**Comment by chanseokoh** [comment]
@alexanderankin does your credential helper correctly return your username and the password?
```
$ export AWS_PROFILE=<your profile>
$ echo <your.registry.com> | docker-credential-helper-ecr-login get
```

**Comment by alexanderankin** [comment]
sure does.

```
toor@z14-3:~$ echo '$account.dkr.ecr.us-east-1.amazonaws.com/repo' -n | docker-credential-ecr-login get
credentials not found in native keychain
toor@z14-3:~$ echo '$account.dkr.ecr.us-east-1.amazonaws.com/repo' -n | AWS_PROFILE=tpp docker-credential-ecr-login get
{"ServerURL":"$account.dkr.ecr.us-east-1.amazonaws.com/repo -n","Username":"AWS","Secret":"eyJwYXlsb2FkIjoiRXYvc2tscWgrelI1
```

**Comment by alexanderankin** [comment]
I'll try to put together a complete example with terraform to define the ecr and everything, id have to redact a lot otherwise.

**Comment by chanseokoh** [comment]
Just saw your Gradle output. Jib worked fine. It's just that you ran jib on another sub-project (`:libs:test-lib`) where you don't want it to run. Do `gradle :app:jib` instead of `gradle jib`.

```
> Task :app:jib
...
Built and pushed image as $account.dkr.ecr.us-east-1.amazonaws.com/$repo:test
...
> Task :libs:test-lib:jib FAILED
...
> Missing target image parameter, perhaps you should add a 'jib.to.image' configuration parameter ...
```

I strongly recommend set up your multi-module project in this [way](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-seeing-method-not-found-or-class-not-found-errors-when-building). That is, declare plugins in the root without applying them, and selectively apply them in sub-projects. Otherwise, it's somewhat easy to run into `Method Not Found` or `Class Not Found` issues in the future.

**Comment by alexanderankin** [comment]
@chanseokoh thank you! yes thats exactly what was happening.
