### ISSUE TITLE
[jib-cli] Correctly create parent directories on filter files

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#2843]
https://github.com/GoogleContainerTools/jib/pull/2700#discussion_r471560251

currently for filter files, the parent directory is ignored by nature of the filter. Because of this, the filtered files are not added with their parents populated. This could lead to an issue where the directory permissions are not as expected.

for a directory structure like:
```
dir1/dir2/
  - file1
  - file2
  - ignore1
```
and a file filter like `**/file*`, the layer parser only adds
```
dir1/dir2/file1
dir1/dir2/file2
```

What it should add is:
```
dir1
dir1/dir2
dir1/dir2/file1
dir1/dir2/file2
```
so that it correctly adds the permissions of `dir1` and `dir2` based on the spec from the build file for directories

**Comment by chanseokoh** [comment]
Reading the linked comment and the TODO comment again, I lost what this means. Can you elaborate on what's the issue and what needs to be done?

**Comment by loosebazooka** [comment]
updated description.
