### ISSUE TITLE
Does this library have apis that deletes the image of registry?

### ISSUE THREAD

**Issue by Bryce-huang** [GoogleContainerTools/jib#2857]
**Environment**:

- *Jib version:* 
- *Build tool:* 
- *OS:* 

**Description of the issue**:

Does this library have apis that deletes the image of registry?
**Expected behavior**:

**Steps to reproduce**:

  1. 
  2. 
  3. 

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by chanseokoh** [comment]
Hi @Bryce-huang,

I'll assume you're talking about the [Jib Core](https://github.com/GoogleContainerTools/jib/tree/master/jib-core) library, which is a general-purpose container-building library for Java. It's not just a Java library for the container registry API, and it doesn't have the functionality to delete an image (manifest and blobs) on a container registry. Hope this answers your question.

**Comment by loosebazooka** [comment]
Perhaps crane from ggcr could work?
https://github.com/google/go-containerregistry

**Comment by Bryce-huang** [comment]
Hi @chanseokoh @loosebazooka 
Thank you very much for your answers, but I am looking for a docker registry library implemented by java
