### ISSUE TITLE
Don't log a warning when setting image creation time to current timestamp

### ISSUE THREAD

**Issue by rmannibucau** [GoogleContainerTools/jib#2860]
What I don't want to see:

> [WARNING] Setting image creation time to current time; your image may not be reproducible.

Factually, JIB does not check the build is reproducible, it just enables to make it reproducible and it is today hard to have a full reproducible build (requires a lot of hacks in maven/gradle and it is rarely the case) so I think this could be an INFO.

Moreover, there is a case it should not even be logged: when user explicitly set the current time to the build time in the configuration. In such a case, the action was intentionnal so the warnning is just bothering.

Hope it makes sense.

Romain

**Comment by rmannibucau** [comment]
up? this sounds like a fairly easy feature making builds more relevant (it is actually often needed to have the timestamp for static resources)

**Comment by mpeddada1** [comment]
Hi @rmannibucau, thank you for filing the feature request! We've discussed this internally and think that it is okay to remove the warning when the creation time is explicitly set. Please feel free to put a PR.

**Comment by rmannibucau** [comment]
https://github.com/GoogleContainerTools/jib/pull/3520
