### ISSUE TITLE
Unrecognized VM option 'UseShenandoahGC'

### ISSUE THREAD

**Issue by fragaLY** [GoogleContainerTools/jib#2863]
**Environment**:

- *Jib version:*  2.6.0
- *Build tool:* Gradle 6.7
- *OS:* Win10 or MacOS

**Description of the issue**:
The base image for java 11 ("gcr.io/distroless/java:11") doesn't support ShenandoahGC.

**Expected behavior**:
The application runs correctly on the created JVM.

**Steps to reproduce**:
  1. Setup a gradle build;
  2. Build it;
  3. Run it.

**`jib-gradle-plugin` Configuration**: 
```kotlin
jib {
  from {
    image = DockerProps.BASE_IMAGE
  }
  container {
    jvmFlags = parseSpaceSeparatedArgs("-noverify -XX:+UseShenandoahGC -Xss${JVMProps.XSS} -Xmx${JVMProps.XMX} -Xms${JVMProps.XMS} -XX:MaxMetaspaceSize=${JVMProps.MAX_METASPACE_SIZE} -XX:MaxDirectMemorySize=${JVMProps.MAX_DIRECT_MEMORY_SIZE} -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${JVMProps.HEAPDUMP_PATH} -Dspring.profiles.active=dev")
    ports = listOf(DockerProps.APP_PORT)
    labels = mapOf("app-name" to application.applicationName, "service-version" to version.toString())
  }
}

// DockerProps.BASE_IMAGE = "gcr.io/distroless/java:11"
```

**Log output**:
Unrecognized VM option 'UseShenandoahGC'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by chanseokoh** [comment]
Hi @fragaLY,

AFAIK, Java 11 [doesn't have Shenandoah](https://developers.redhat.com/blog/2019/04/19/not-all-openjdk-12-builds-include-shenandoah-heres-why/). Perhaps just set `jib.from.image` to use any base image that has the feature. I don't have a specific JDK recommendation.

**Comment by fragaLY** [comment]
@chanseokoh 
https://wiki.openjdk.java.net/display/shenandoah/Main

JDK 11 has a Shenandoah.

**Comment by chanseokoh** [comment]
Thanks for the reference.

> In mainline OpenJDK 11u builds since 11.0.9.

The version of the OpenJDK 11 build by Debian in `gcr.io/distroless/java:11` is currently 11.0.6. Actually, the image is based on the Debian 9 oldstable, which Debian does not usually provide updates to packages. You may want to use the Debian 10-based `gcr.io/distroless/java-debian10:11`. Note that `gcr.io/distroless/java-debian10:11` was using 11.0.8 until now, and 11.0.9 was published **_today_**, so make sure to rebuild your image online to use 11.0.9. Looks like the OpenJDK 11.0.9 Debian build does accept `-XX:+UseShenandoahGC`.

**Comment by fragaLY** [comment]
@chanseokoh thanks a lot.

**Comment by fragaLY** [comment]
@chanseokoh, 

Hello,

Unfortunately, 
```
api_1       | Unrecognized VM option 'UseShenandoahGC'
api_1       | Error: Could not create the Java Virtual Machine.
api_1       | Error: A fatal exception has occurred. Program will exit.
```
It was built on gcr.io/distroless/java-debian10:11

**Comment by chanseokoh** [comment]
@fragaLY yeah, looks like it. Please use a OpenJDK build that supports the option. I don't have a specific recommendation.

**Comment by chanseokoh** [comment]
Your previous link lists some builds:

> ### Releases
>
> Known sources for Shenandoah-enabled OpenJDK:
>
> OpenJDK 12+ builds normally include Shenandoah by default; some vendors (notably Oracle) choose to exclude it
> Fedora 24+ OpenJDK 8+ builds include Shenandoah
> RHEL 7.4+ ships with OpenJDK 8+ that includes Shenandoah as Technology Preview
> RHEL/Fedora-based distros or other distros that use packages from them may also have Shenandoah enabled. Notably, > CentOS, Oracle Linux, and Amazon Linux are known to ship it.
> Gentoo ebuilds for IcedTea have Shenandoah USE flag
> Red Hat OpenJDK 8u builds for Windows include Shenandoah
