### ISSUE TITLE
[jib-cli-jar] Enable caching for jib cli jar 

### ISSUE THREAD

**Issue by mpeddada1** [GoogleContainerTools/jib#2879]
This is would require creating a build artifacts directory for the command so that the jar file wouldn't need to be unzipped every time it is used.

**Comment by chanseokoh** [comment]
We are specially talking about the application cache. (The base image cache will work fine.)

Javadoc of `LayerEntriesSelector`:

```
 * Generates a selector based on {@link FileEntry}s for a layer. Selectors are secondary references
 * for a cache entries.
 *
 * <p>The selector is the SHA256 hash of the list of layer entries serialized in the following form:
 *
 * <pre>{@code
 * [
 *   {
 *     "sourceFile": "source/file/for/layer/entry/1",
 *     "extractionPath": "/extraction/path/for/layer/entry/1"
 *     "sourceModificationTime": "2018-10-03T15:48:32.416152Z"
 *     "targetModificationTime": "1970-01-01T00:00:01Z",
 *     "permissions": "777",
 *     "ownership": "0:0"
 *   },
 *   {
 *     "sourceFile": "source/file/for/layer/entry/2",
 *     "extractionPath": "/extraction/path/for/layer/entry/2"
 *     "sourceModificationTime": "2018-10-03T15:48:32.416152Z"
 *     "targetModificationTime": "1970-01-01T00:00:01Z",
 *     "permissions": "777",
 *     "ownership": "alice:1234"
 *   }
 * ]
 * }</pre>
```

The way we compute a "selector" for cached layer tarballs is by looking at the properties above, which includes `sourceFile`. Therefore, if we unzip a jar to a new temp location each time we run `jib jar`, passing `--application-cache` will have no effect.

And actually, I think the Jib build plugins for WAR projects has the same issue. They [unzip `.war` files into temporary directories](https://github.com/GoogleContainerTools/jib/blob/f0123a83be9560b8980690f86ffdbdfdcbc67439/jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenProjectProperties.java#L258-L259).
