### ISSUE TITLE
Maven `jib:dockerBuild` re-uploads layers that have already been pushed

### ISSUE THREAD

**Issue by spmason** [GoogleContainerTools/jib#2883]
**Environment**:

- *Jib version:* 2.6.0
- *Build tool:* Maven
- *OS:* MacOS Mojave

**Description of the issue**:

In my build, the `jib:dockerBuild` target takes the majority of the time to run, even if the layers have already been loaded previously

ie if I run two back-to-back builds (with no code changes between) the "Loading to Docker daemon" step still takes ten seconds or so

My image is quite large, mostly due to a 400Mb "dependencies" layer - as the dependencies hardly ever change I'd expect a big speed up if that layer wasn't being uploaded to the docker daemon every time

**Expected behavior**:

`jib` skips uploading layers to the docker daemon that have already been uploaded

**Steps to reproduce**:

  1. Download this example repo: https://github.com/spmason/jib-image-caching-example
  2. `mvn clean package jib:dockerBuild -X -B | grep TIMED`
  3. Note down the built sha from `docker images | grep jib-cache-repro`
  4. Run `mvn clean package jib:dockerBuild -X -B | grep TIMED` a second time
  3. Observe that the "Loading to Docker daemon" step took just as long as the first time, and the image sha output from `docker images | grep jib-cache-repro` hasn't changed

**Log output**:

Output of running `mvn clean package jib:dockerBuild -X | grep TIMED` on that second run:

```
[DEBUG] TIMED	Preparing application layer builders : 2.407 ms
[DEBUG] TIMED	Building classes layer : 75.097 ms
[DEBUG] TIMED	Pulling base image manifest : 1295.003 ms
[DEBUG] TIMED	Preparing base image layer pullers : 0.118 ms
[DEBUG] TIMED	Pulling base image layer sha256:febab311d432377a68e537dfd16a83a185e9fc214e9b509afea0d5e9e8154053 : 0.445 ms
[DEBUG] TIMED	Pulling base image layer sha256:71f0443d2e95e6191e67896551f8a67f4c17989f71683a4458b43aa2b06d8e47 : 0.573 ms
[DEBUG] TIMED	Pulling base image layer sha256:e708be98c58f6bb27bf2b7839d7e63ad5be667b1585c6142af4d3dbbe80a7330 : 0.731 ms
[DEBUG] TIMED	Pulling base image layer sha256:31eb28996804beb46ae686d865721ff610e2a89dc13d3dcb7c4622377447f11d : 0.916 ms
[DEBUG] TIMED	Pulling base image layer sha256:e59bd8947ac7af2c8f4403b183326986ab554bbc262739cf5d9d596c7c7a3aca : 0.242 ms
[DEBUG] TIMED	Building dependencies layer : 3506.639 ms
[DEBUG] TIMED	Building container configuration : 0.851 ms
[DEBUG] TIMED	Loading to Docker daemon : 4217.32 ms
[DEBUG] TIMED	Building image to Docker daemon : 7775.815 ms
```

**Additional Information**:

This Moby issue seems to be related here: https://github.com/moby/moby/issues/20380 - it seem to say that uploading layers separately instead of as one tar would make dockers caching kick in, but I don't know enough about what jib is doing to say whether it's already doing that or not

**Comment by mpeddada1** [comment]
Hello @spmason, thanks for asking! Unfortunately, due to certain limitations of the Docker Engine API, Jib doesn’t have a way to check if certain layers are already stored in a Docker Engine so Jib has to stream the entire image when `jibDockerBuild` is called. 

If you have good network bandwidth, one workaround could be to push to and pull from a local/remote registry with `mvn jib:build && docker pull <image name>`. This may be more efficient than pushing directly to your local Docker engine (daemon).

**Comment by chanseokoh** [comment]
> Docker Engine API, Jib doesn’t have a way to check if certain layers are already stored in a Docker Engine

Also the API doesn't provide a way to send only some part of an image.

Hope you got the answer you were seeking. We feel this is very unfortunate, but we are not aware of any solution. Will close the issue. Feel free to update any feedback.
