### ISSUE TITLE
Using jib.extraDirectories with Maven at CLİ

### ISSUE THREAD

**Issue by uguruysal0** [GoogleContainerTools/jib#2884]
For some reason, I need to use extra directories for creating an image.

 ./mvnw compile jib:dockerBuild -Dimage=X -Djib.container.args="--spring.profiles.active=test" \ -Djib.extraDirectories="WHAT_TO_WRİTE_HERE"

I could not figure out how to pass extraDirectories from CLI. For some reason I can not put to pom.xml.

Using:
apache-maven-3.5.4

Can I get a little help here?

**Comment by chanseokoh** [comment]
Good question.

```
-Djib.extraDirectories.paths=/some/extra/dir,/another/extra/dir
```

> For some reason I can not put to pom.xml.

Here are some [examples](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#adding-arbitrary-files-to-the-image).
