### ISSUE TITLE
Consider exposing a task/mojo for just pushing an existing image

### ISSUE THREAD

**Issue by alvarosanchez** [GoogleContainerTools/jib#2897]
It would be great to be able to run `mvn jib:push` or `gradle jibPush` to push an existing image to the configured registry.

It should allow pushing existing `DockerDaemonImage`s or `TarImage`s, and it would handle all the credential retrievers business.

At Micronaut, we are leveraging Jib in our Maven Plugin, but [had to handle the credential retrievers and credHelpers registration ourselves](https://github.com/micronaut-projects/micronaut-maven-plugin/blob/master/src/main/java/io/micronaut/build/DockerPushMojo.java), since the existing API is not really reusable. For example `DefaultCredentialRetrievers#init()` is package-private.

If `jib:push` existed, we would simply delete ours and delegate to yours.

**Comment by chanseokoh** [comment]
Thanks for the feedback. As you already know, `DefaultCredentialRetrievers` is an internal class and not even in jib-core. So probably not a good idea to use it.

And unfortunately, I think having a standalone goal to just push an existing local Docker image to a registry is basically out of scope of the Jib plugin. And it is not that we have such a task/mojo; at the moment, we don't have separated steps or mojos for building and pushing. Even if we did, jib-core would still directly push an image to a registry without going through Docker. However, we definitely want to have great support for Micronaut and help in whatever way feasible. We will need to discuss this issue further internally, but I think we cannot guarantee anything.

**Comment by alvarosanchez** [comment]
So `jib:build` is `[Build + Push]` and `jib:dockerBuild` is `[Build]`. All I'm saying is to have an additional `jib:push` that does `[Push]`. Out of the existing code, just separated so that it can be reused. I don't see how this is out of scope since it's already part of `jib:build`.

If you want, we can have a call to discuss it with more detail.

Thank you for considering this feedback anyway.

**Comment by chanseokoh** [comment]
By `[Push]`, I assume you're talking about obtaining an image from a Docker daemon and pushing it to a registry. Note that our `jib:build` works even if you don't have Docker, and it doesn't build an image into a Docker daemon. It prepares JSON and layer blobs, stores them in our own base image and application layer cache directories, and directly streams blobs to a registry. In that sense, retrieving an image from Docker and pushing it is a different logic we don't have.

I'll contact you in a different channel anyway.

**Comment by alvarosanchez** [comment]
> By [Push], I assume you're talking about obtaining an image from a Docker daemon and pushing it to a registry

Not exactly, I was referring to `DockerDaemonImage`s or `TarImage`s.

I know how `jib:build` works, however, in Micronaut what we use is `jib:dockerBuild`.

> In that sense, retrieving an image from Docker and pushing it is a different logic we don't have.

`Jib.from(aDockerDaemonImage)` is a public API, which as far as I can tell, it's used in jib-cli and `JavaContainerBuilder`.

> I'll contact you in a different channel anyway.

Sounds good, I'm available in Gitter.

**Comment by mpeddada1** [comment]
@alvarosanchez Closing this issue as the conversation has moved to Gitter. But please feel free to reopen it if you have any further questions or feedback!

**Comment by alvarosanchez** [comment]
That's fine, we're moving away from Jib for pushing anyway: https://github.com/micronaut-projects/micronaut-maven-plugin/issues/72

Thanks for at least considering it!
