### ISSUE TITLE
Sonatype Nexus: not passing authorization header for base image: 400 Bad Request: "[ERROR-400] DOCKER Either Authorization header is missing or invalid"

### ISSUE THREAD

**Issue by zebu** [GoogleContainerTools/jib#2898]
**Environment**:

- *Jib version:* 2.6.0
- *Build tool:* Maven
- *OS:* reproduced on macos and redhat

**Description of the issue**:
I'm using a local repository and seeing 'HTTP/1.1 401 Unauthorized' on the from repository due to JIB not passing the Authorization Header. The logs confirm the maven settings are being selected. I've also tried explicitly setting the credentials in the from/auth and in the docker config. The behavior is consistent, the header is never passed. The 'to' image is working correctly and passing credentials.

If I manually issue the jib curls and add the Authorization Header the requests are successful. 

Full logs below but here are the excerpts of failed calls
> curl -v --compressed -H 'Accept: ' -H 'Accept-Encoding: gzip' -H 'User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)' -- 'https://dockercentral:5100/v2/'
> HTTP/1.1 401 Unauthorized

> curl -v --compressed -H 'Accept: application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json' -H 'Accept-Encoding: gzip' -H 'User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)' -- 'https://dockercentral:5100/v2/com.mydomain.public/anapsix/alpine-java/manifests/8u221b11_jdk'
> HTTP/1.1 400 Bad Request

I also want to note that this has been working for over six months. It just recently broke. No build/code changes. The team that manages the repository claim no changes.

**Expected behavior**:
Authorization Header passed on https://dockercentral:5100/v2/ and 'from' calls.

**Steps to reproduce**:
mvn -s setttings.xml -Djava.util.logging.config.file=logging.properties -Djib.serialize=true -Dimage=dockercentral:5100/com.mydomain/myservice:1.0.268 jib:build

**`jib-maven-plugin` Configuration**: 
```
<plugin>
      <groupId>com.google.cloud.tools</groupId>
      <artifactId>jib-maven-plugin</artifactId>
      <version>2.6.0</version>
      <configuration>
            <from>
                <image>${docker-baseimage}</image>
           </from>
          <to>
              <image>${docker-serviceimage}</image>
          </to>
          <container>
              <creationTime>USE_CURRENT_TIMESTAMP</creationTime>
           </container>
      </configuration>
</plugin>
```
**Log output**: 
```
[INFO] --- jib-maven-plugin:2.6.0:build (default-cli) @ myservice ---
[WARNING] 'mainClass' configured in 'maven-jar-plugin' is not a valid Java class: ${start-class}
[WARNING] Setting image creation time to current time; your image may not be reproducible.
[INFO] 
[INFO] Containerizing application to dockercentral:5100/mydomain/myservice:1.0.268-wc1091...
[WARNING] Base image 'dockercentral:5100/mydomain.public/anapsix/alpine-java:8u221b11_jdk' does not use a specific image digest - build may not be reproducible
[INFO] Using credentials from Maven settings file for dockercentral:5100/mydomain/myservice:1.0.268
[INFO] Executing tasks:
[INFO] [=                             ] 4.2% complete
[INFO] > authenticating push to dockercentral...
Nov 20, 2020 8:45:03 AM com.google.api.client.http.HttpRequest execute
CONFIG: -------------- REQUEST  --------------
GET https://storage.googleapis.com/jib-versions/jib-maven
Accept: */*
Accept-Encoding: gzip
User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)

Nov 20, 2020 8:45:03 AM com.google.api.client.http.HttpRequest execute
CONFIG: -------------- REQUEST  --------------
GET https://dockercentral:5100/v2/
Accept: 
Accept-Encoding: gzip
User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)

Nov 20, 2020 8:45:03 AM com.google.api.client.http.HttpRequest execute
CONFIG: curl -v --compressed -H 'Accept: ' -H 'Accept-Encoding: gzip' -H 'User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)' -- 'https://dockercentral:5100/v2/'
Nov 20, 2020 8:45:03 AM com.google.api.client.http.HttpRequest execute
CONFIG: curl -v --compressed -H 'Accept: */*' -H 'Accept-Encoding: gzip' -H 'User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)' -- 'https://storage.googleapis.com/jib-versions/jib-maven'
Nov 20, 2020 8:45:03 AM com.google.api.client.http.HttpResponse <init>
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 401 Unauthorized
Server: nginx/1.15.8
Date: Fri, 20 Nov 2020 13:45:06 GMT
Content-Type: application/json
Content-Length: 113
Connection: keep-alive
X-Content-Type-Options: nosniff
Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
X-XSS-Protection: 1; mode=block
WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"
Docker-Distribution-Api-Version: registry/2.0
X-Upstream: 135.47.69.226:5100

Nov 20, 2020 8:45:03 AM com.google.api.client.util.LoggingByteArrayOutputStream close
[INFO] Executing tasks:
[INFO] [===                           ] 8.3% complete
[INFO] > pulling base image manifest
Nov 20, 2020 8:45:03 AM com.google.api.client.http.HttpRequest execute
CONFIG: -------------- REQUEST  --------------
GET https://dockercentral:5100/v2/mydomain.public/anapsix/alpine-java/manifests/8u221b11_jdk
Accept: application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json
Accept-Encoding: gzip
User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)

Nov 20, 2020 8:45:03 AM com.google.api.client.http.HttpRequest execute
CONFIG: curl -v --compressed -H 'Accept: application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json' -H 'Accept-Encoding: gzip' -H 'User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)' -- 'https://dockercentral:5100/v2/mydomain.public/anapsix/alpine-java/manifests/8u221b11_jdk'
Nov 20, 2020 8:45:04 AM com.google.api.client.http.HttpResponse <init>
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 400 Bad Request
Server: nginx/1.15.8
Date: Fri, 20 Nov 2020 13:45:06 GMT
Content-Type: application/json;charset=iso-8859-1
Content-Length: 222
Connection: keep-alive
X-Upstream: 135.47.69.226:5100

Nov 20, 2020 8:45:04 AM com.google.api.client.util.LoggingByteArrayOutputStream close
[INFO] Executing tasks:
[INFO] [========                      ] 25.0% complete
[INFO] > pushing blob sha256:ad802fec9f8c711f97571e2cb...
Nov 20, 2020 8:45:04 AM com.google.api.client.http.HttpRequest execute
CONFIG: -------------- REQUEST  --------------
HEAD https://dockercentral:5100/v2/mydomain/myservice/blobs/sha256:ad802fec9f8c711f97571e2cbff1b45d181e07148d4367b3a8d5bca3de204df4
Accept: 
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)

Nov 20, 2020 8:45:04 AM com.google.api.client.http.HttpRequest execute
CONFIG: curl -v --compressed -X HEAD -H 'Accept: ' -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)' -- 'https://dockercentral:5100/v2/mydomain/myservice/blobs/sha256:ad802fec9f8c711f97571e2cbff1b45d181e07148d4367b3a8d5bca3de204df4'
Nov 20, 2020 8:45:04 AM com.google.api.client.http.HttpResponse <init>
CONFIG: -------------- RESPONSE --------------
HTTP/1.1 200 OK
....
.... NOT an issue for 'to' images ...
....
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.317 s
[INFO] Finished at: 2020-11-20T08:45:04-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.6.0:build (default-cli) on project myservice: Tried to pull image manifest for dockercentral:5100/mydomain.public/anapsix/alpine-java:8u221b11_jdk but failed because: registry returned error code 400; possible causes include invalid or wrong reference. Actual error output follows:
[ERROR] &#x7b;&quot;errors&quot;&#x3a;&#x5b;&#x7b;&quot;code&quot;&#x3a;&quot;UNAUTHORIZED&quot;,&quot;message&quot;&#x3a;&quot;&#x5b;ERROR-400&#x5d; DOCKER Either Authorization header is missing or invalid&quot;&#x7d;&#x5d;&#x7d;
[ERROR]  | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new: 400 Bad Request
[ERROR] &#x7b;&quot;errors&quot;&#x3a;&#x5b;&#x7b;&quot;code&quot;&#x3a;&quot;UNAUTHORIZED&quot;,&quot;message&quot;&#x3a;&quot;&#x5b;ERROR-400&#x5d; DOCKER Either Authorization header is missing or invalid&quot;&#x7d;&#x5d;&#x7d;
[ERROR] -> [Help 1]
[ERROR
```

**Comment by chanseokoh** [comment]
Hi @zebu,

Jib has never sent the `Authorization:` header for the very first base image manifest query (in the hope that a public base image repository would just return a manifest without requiring credentials). If the registry returns 401 Unauthorized for the first manifest request without credentials, Jib will prepare a proper form of `Authorization:` based on the auth challenges that the registry asks for. So in this case, the server should normally return 401 with an auth challenge (e.g., the `WWW-Authenticate: BASIC ...` as you can see for the target image repository), and I think it doesn't make much sense that it returns 400 bad request. I don't believe Jib is making a bad request.

What's the output of this? (Update the `mydomain.public` portion if that's not part of a real repository name.)
```
$ curl -v --compressed -H 'Accept: application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json' -H 'Accept-Encoding: gzip' -H 'User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)' -- 'https://dockercentral:5100/v2/mydomain.public/anapsix/alpine-java/manifests/8u221b11_jdk'
```

And are you behind a proxy? For example, do you have any proxy settings in `settings.xml`?

**Comment by zebu** [comment]
Yes, proxy is configured but ignored for this domain. I just tested removing it completely with the same result.

Based on your response, it sounds like something was changed on the repository and it is no longer sending challenges?

```
GAML01WC1091:service bconner$ curl -v --compressed -H 'Accept: application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json' -H 'Accept-Encoding: gzip' -H 'User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)' -- 'https://dockercentral:5100/v2/public/anapsix/alpine-java/manifests/8u221b11_jdk'
* Uses proxy env variable no_proxy == 'olakscluster-dns-.eastus2.azmk8s.io,.att.com,.sbc.com,localhost,127.0.0.1'
*   Trying 135.47.45.237...
* TCP_NODELAY set
* Connected to dockercentral (135.47.45.237) port 5100 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=US; ST=Texas; L=Dallas; O=AT&T Services, Inc.; OU=ACSI; CN=dockercentral
*  start date: Aug 18 00:00:00 2020 GMT
*  expire date: Aug 19 12:00:00 2021 GMT
*  subjectAltName: host "dockercentral" matched cert's "dockercentral"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert Global CA G2
*  SSL certificate verify ok.
> GET /v2/public/anapsix/alpine-java/manifests/8u221b11_jdk HTTP/1.1
> Host: dockercentral:5100
> Accept: application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json
> Accept-Encoding: gzip
> User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)
> 
< HTTP/1.1 400 Bad Request
< Server: nginx/1.15.8
< Date: Fri, 20 Nov 2020 15:28:32 GMT
< Content-Type: application/json;charset=iso-8859-1
< Content-Length: 222
< Connection: keep-alive
< X-Upstream: 135.47.69.226:5100
< 
* Connection #0 to host dockercentral left intact
&#x7b;&quot;errors&quot;&#x3a;&#x5b;&#x7b;&quot;code&quot;&#x3a;&quot;UNAUTHORIZED&quot;,&quot;message&quot;&#x3a;&quot;&#x5b;ERROR-400&#x5d; DOCKER Either Authorization header is missing or invalid&quot;&#x7d;&#x5d;&#x7d;* Closing connection 0
```

**Comment by chanseokoh** [comment]
> Based on your response, it sounds like something was changed on the repository and it is no longer sending challenges?

Basically, yes. I think previously the server sent 401 instead of 400. And it's not just the auth challenge. I think the problem is the code "400 Bad Request", and from our perspective, it is not quite right. (400 will not accompany an auth challenge anyway). The server is Sonatype Nexus, right?

And now I just realized that the server made the following output.
```
&#x7b;&quot;errors&quot;&#x3a;&#x5b;&#x7b;&quot;code&quot;&#x3a;&quot;UNAUTHORIZED&quot;,&quot;message&quot;&#x3a;&quot;&#x5b;ERROR-400&#x5d; DOCKER Either Authorization header is missing or invalid&quot;&#x7d;&#x5d;&#x7d;
```
which when rendered correctly is
```
{"errors":[{"code":"UNAUTHORIZED","message":"[ERROR-400] DOCKER Either Authorization header is missing or invalid"}]}
```
So probably if Jib initiated an auth workflow in a different way than directly trying to access the manifest without credentials as the first attempt (for example, like in the target repository case where Jib started with contacting `GET https://dockercentral:5100/v2/`), it could have worked. However, the error message says `code: UNAUTHORIZED`, so I think it's more appropriate for the server to return "401 Unauthorized" (plus an auth challenge) instead of "400 Bad Request." I'm not sure if Sonatype had a reason to make this breaking change or if it's unintentional, but I think it's worth filing an issue against them. It's possible that this is not a deliberate decision. (If they insist this is an intended breaking change and will return 400 going forward, we really need to think about how we can support Sonatype.) But all other registries (including Sonatype until now) return 401 if it requires authentication when accessing a manifest, and I think it really makes sense.

For now, unfortunately I can't think of any workaround.

**Comment by zebu** [comment]
Thanks for all of your help, I'll see what I can do from the Sonatype end.

**Comment by chanseokoh** [comment]
Please keep us updated.

If you're blocked, you can use a different registry, make the base image repo public, or set `<from><image>docker://...` to use a local Docker daemon image. Using a local Docker image can be slow though.

**Comment by cgasparini** [comment]
Hello,

Was any solution found for this issue?
Provided workaround are not an suitable option for my case.

Regards

**Comment by chanseokoh** [comment]
@zebu have you filed a bug against Sonatype? Any update?

**Comment by chanseokoh** [comment]
@zebu any update on this?

**Comment by cgasparini** [comment]
I think we loose @zebu, but I will like to have this working. @chanseokoh Will this scenario be fixed or closed as per no reaction of zebu?

**Comment by chanseokoh** [comment]
It depends on whether Sonatype Nexus will fix it. I do think it's a bug in Sonatype that they will fix.

**Comment by cgasparini** [comment]
I think the same, they wont do anything about it.

**Comment by chanseokoh** [comment]
Sorry, I think you misunderstood. I *do* think it's their bug.

**Comment by zebu** [comment]
Sorry, this got buried in my email with the holiday break. I don't have full visibility of the details because a separate team handles our nexus. They did knowledge there was an upgrade and it was the root cause. Before our internal ticket was closed, they noted they made a code fix and were working with Sonatype for something more permanent. If interested, I can try and get more information.

**Comment by chanseokoh** [comment]
@zebu thanks for the update. So what did Sonatype say about https://github.com/GoogleContainerTools/jib/issues/2898#issuecomment-731270470? Did they admit that it's their bug to have introduced a breaking change that changed the return code from Unauthorized (401) to Bad Request (400)? Will they fix it? Is Jib working fine right now? It'd be helpful to us if you provide more details.

**Comment by zebu** [comment]
It may take some time to pull this information together. I only know that was posted to our internal ticketing system which doesn't have a lot of details. I'll open a new ticket requesting details.

What I do know:
Nexus 3.23.0. JIB was working fine.
Nexus 3.27.0. JIB started seeing the issue.

An internal patch was made to correct the issue. Sonatype was engaged for a long term fix.

**Comment by zebu** [comment]
I was able to get some more details. The issue started with the Nexus 3.27.0 upgrade. There was a change in the nexus principle which broke how our custom authentication plugin handled anonymous users. A ticket was opened with Sonatype but they would not address the issue from their side. We updated our custom plugin to handle the change in behavior.

**Comment by chanseokoh** [comment]
Thanks. Could you clarify one thing? Which one is true?

1) The issue (that you see the return code Bad Request 400) is because of the presence of your custom auth plugin. Normal Sonatype users won't hit this issue. (Nothing to be done on the Jib side, so we can close this issue.)
2) Sonatype did make this change to return Bad Request in this situation, so all Jib users on Nexus 3.27.0 will hit the issue. The auth plugin is irrelevant. You just implemented your own workaround through the custom auth plugin. (Jib needs to do something to support Nexus.)

**Comment by cgasparini** [comment]
2 is the true.
I'm user from different environment and I'm hitting the same issue

**Comment by chanseokoh** [comment]
Understood. Since Sonatype said they won't fix this, we will work on this as a priority to have special auth path for Sonatype.

**Comment by zebu** [comment]
I can't speak to 1 vs 2 being the root cause of the issue. I did not write the plugin and I don't have access to the code. All I can say if Nexus 3.27.0 broke our custom plugin

**Comment by chanseokoh** [comment]
Thanks for the info.

I set up a local Sonatype Nexus (using [`sonatype/nexus3`](https://hub.docker.com/r/sonatype/nexus3) (3.27.0-03 as of now) and `sonatype/nexus3:3.27.0`) in hopes to reproduce this. For testing, I created both a hosted Docker repository and a proxy repository for Docker Hub. However, Jib was able to push and pull images. Sonatype Nexus correctly returns 401 Unauthorized with the message `access to the requested resource is not authorized`. For example with `curl`,

```
$ curl -k -v --compressed -H 'Accept: application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json' -H 'Accept-Encoding: gzip' -H 'User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)' -- 'https://localhost:5443/v2/mydomain.public/anapsix/alpine-java/manifests/8u221b11_jdk'
...
...
> GET /v2/mydomain.public/anapsix/alpine-java/manifests/8u221b11_jdk HTTP/1.1
> Host: localhost:5443
> Accept: application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.v2+json,application/vnd.docker.distribution.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json
> Accept-Encoding: gzip
> User-Agent: jib 2.6.0 jib-maven-plugin Google-HTTP-Java-Client/1.34.0 (gzip)
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Date: Mon, 25 Jan 2021 20:59:22 GMT
< Strict-Transport-Security: max-age=7776000
< Server: Nexus/3.27.0-03 (OSS)
< X-Content-Type-Options: nosniff
< Content-Security-Policy: sandbox allow-forms allow-modals allow-popups allow-presentation allow-scripts allow-top-navigation
< X-XSS-Protection: 1; mode=block
< WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"
< Docker-Distribution-Api-Version: registry/2.0
< Content-Type: application/json
< Content-Length: 113
< 
* Connection #0 to host localhost left intact
{"errors":[{"code":"UNAUTHORIZED","message":"access to the requested resource is not authorized","detail":null}]}
```

The server identifies itself as `Nexus/3.27.0-03 (OSS)`. I see that in @zebu's case, it's NGINX. AFAIK, Sonatype runs Eclipse Jetty, and it looks like Nexus is secured behind an NGINX reverse proxy. I wonder if it isn't the NGINX proxy sitting in the middle that is intercepting the response and causing an issue. (Or the custom plugin @zebu uses. At least it's certain there are other components involved.) Probably the actually Sonatype repository is behind the proxy at `X-Upstream: 135.47.69.226:5100` as shown in the header. I tried to find who returns the original error message `Either Authorization header is missing or invalid` but searching on the internet effectively shows up nothing. I don't feel strongly that the issue is on Jib or Sonatype.

As Jib and Sonatype seem to work correctly and this seems like an isolated instance in a specific user environment, I'm a bit hesitant to implement a special handling to Jib at the moment. If Jib didn't work with Sonatype outright, we would have received a lot of user reports and have seen the error message in multiple places.

**Comment by chanseokoh** [comment]
As explained above, neither Sonatype nor Jib seems to cause or hit the issue. Both of them are working fine, and I think the issue is from a different component, but there's no more information. Closing the issue.
