### ISSUE TITLE
Maven plugin: Skipped dependency module missing from service image

### ISSUE THREAD

**Issue by reitzig** [GoogleContainerTools/jib#2901]
**Environment**:

- *Jib version:* 2.6.0
- *Build tool:* Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
- *JVM:* 14.0.2, AdoptOpenJDK
- *OS:* Linux 5.4.0-52-generic amd64

**Description of the issue**:
Building images from the root folder of a multi-module project, I don't get functional images: during container startup, the JVM can not find classes from the (skipped) `common` module

**Expected behavior**:

Images are functional, i.e. include all dependencies (even if they were marked to "skip" for Jib).

**Steps to reproduce**:

  1. Maven project with three modules `common`, `serviceA`, `serviceB`; the latter two depend on `common` (via `dependencyManagement` in the root POM).
  2. Configure Jib in the root pom.
  3. Run `mvn compile jib:dockerBuild`

**`jib-maven-plugin` Configuration**: 
Root:
```xml
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>jib-maven-plugin</artifactId>
    <version>${jib.version}</version>
    <configuration>
      <skip>true</skip>
      <from>
        <image>gcr.io/distroless/java:11</image>
      </from>
      <to>
        <image>my-service-${project.artifactId}</image>
      </to>
    </configuration>
</plugin>
```

`serviceA`, `serviceB`:
```xml
      <plugin>
        <groupId>com.google.cloud.tools</groupId>
        <artifactId>jib-maven-plugin</artifactId>
        <configuration>
          <skip>false</skip>
        </configuration>
      </plugin>
```

**Additional Information**: 
Without `<skip>`, building in the root folder fails because `common` doesn't have a "main" class:

> [ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.5.2:build (default-cli) on project commons: Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin

**Comment by chanseokoh** [comment]
Hi @reitzig,

If you run `mvn -am -pl serviceA dependency:copy-dependencies` (and `mvn -am -pl serviceA dependency:copy-dependencies`), do you see `common-....jar` in `serviceA/target/dependency/*.jar` (and `serviceB/target/dependency/*.jar)?

And can you provide us with a sample skeleton project where this is reproducible?

**Comment by chanseokoh** [comment]
> Run `mvn compile jib:dockerBuild`

Oh, actually, I think you should do `mvn package jib:dockerBuild`.

**Comment by reitzig** [comment]
> If you run mvn -am -pl serviceA dependency:copy-dependencies (and mvn -am -pl serviceA dependency:copy-dependencies), do you see common-....jar in serviceA/target/dependency/*.jar (and serviceB/target/dependency/*.jar)?

Nope, it's not in that list.

> And can you provide us with a sample skeleton project where this is reproducible?

Not right now, sorry.

> Oh, actually, I think you should do `mvn package jib:dockerBuild`

Umm ... that works? Why on earth would that make a difference? 

I'm not an expert in how Maven plugins work, but shouldn't `jib:dockerBuild` automatically run all required phases? :thinking:

**Comment by chanseokoh** [comment]
> Nope, it's not in that list.

If that's the case, this could be the root cause. Jib asks Maven what runtime dependencies that `serviceA` requires. If Maven doesn't tell Jib that "common" is part of "serviceA"'s dependencies, Jib won't include it. Perhaps your project is not correctly set up?

> Umm ... that works? Why on earth would that make a difference?
> 
> I'm not an expert in how Maven plugins work, but shouldn't `jib:dockerBuild` automatically run all required phases?

Unfortunately, AFAIK, there is no way a plugin can trigger lifecycle phases (whether it be `mvn deploy`, `mvn install`, or `mvn compile`). For your build to run the `compile` or `package` lifecycle, you must give the command.

For example, if you don't run the `package` phase, Maven will never create `common-....jar` for your "common" module, which if existed Jib would containerize as a dependency of "serviceA". Likewise, if you don't run the `compile` phase, Maven will not create `.class` files, and Jib would miss those compile files. It's not possible for Jib to run `package` or `compile`.

**Comment by reitzig** [comment]
Maybe? We do have this in `serviceA/pom.xml`:

```xml
<dependency>
    <groupId>our.group</groupId>
    <artifactId>commons</artifactId>
</dependency>
```

Does Maven not resolve this to the sibling module? :man_shrugging: 

> Unfortunately, AFAIK, there is no way a plugin can trigger lifecycle phases (whether it be mvn deploy, mvn install, or mvn compile). For your build to run the compile or package lifecycle, you must give the command.
>
>For example, if you don't run the package phase, Maven will never create common-....jar for your "common" module, which if existed Jib would containerize as a dependency of "serviceA". Likewise, if you don't run the compile phase, Maven will not create .class files, and Jib would miss those compile files. It's not possible for Jib to run package or compile.

Thanks.

So, if I were to run `mvn -pl serviceA clean package jib:dockerBuild`, it wouldn't work either because `commons` would silently be forgotten? Ugn... `-pl commons,serviceA` it is, but that's ... sad.

Anyway, it seems that by issue is with Maven, not Jib. Thanks for your help!

**Comment by chanseokoh** [comment]
> Does Maven not resolve this to the sibling module? :man_shrugging:

It should. Not sure what's going on.

> So, if I were to run `mvn -pl serviceA clean package jib:dockerBuild`, it wouldn't work either because `commons` would silently be forgotten?

You need `-am` ([`--also-make`](https://maven.apache.org/guides/mini/guide-multiple-modules.html#command-line-options)) too. That is, `mvn -am -pl serviceA clean package jib:dockerBuild`.

> `--also-make` - build the specified projects, and any of their dependencies in the reactor

We have a [multi-module example](https://github.com/GoogleContainerTools/jib/tree/master/examples/multi-module), which I think is configured a little bit different than yours. Worth taking a look.

Let us know if you have any questions. If you have a reproducible sample, we can take a look too.
