### ISSUE TITLE
Don't transform the object passed to extraDirectories.paths.path.from immediately

### ISSUE THREAD

**Issue by bric3** [GoogleContainerTools/jib#2902]
**Environment**:

- *Jib version:* 2.6.0
- *Build tool:*Gradle 6.7.1
- *OS:* macOS

**Description of the issue**:

I'd like to configure extraDirectories with the output from another task, however during the gradle configuration the task didn't run yet, the files dod not exist yet

```gradle
jib {
    extraDirectories {
        paths {
            path {
                from = {
                    unpackLibsodium.outputs
                            .files
                            .asFileTree
                            .matching { include "**/*.so" }
                            .singleFile
                            .parentFile
                }
// ...
}

tasks.jibBuildTar.dependsOn unpackLibsodium
tasks.jibDockerBuild.dependsOn unpackLibsodium
tasks.jib.dependsOn unpackLibsodium

```

This leads to the following error 

```
* What went wrong:
A problem occurred evaluating project ':password-encryption-cli'.
> Expected task 'unpackLibsodium' output files to contain exactly one file, however, it contains no files.
```

And it is likely caused by the `setFrom` method that immediately pass the object to `project.file`, thus immediately executing the closure, however as the task has been executed it fails because there's no output yet.

https://github.com/GoogleContainerTools/jib/blob/8d34a28a156894867c6fdd8416a9f03cdf04d863/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ExtraDirectoryParameters.java#L57

The only option is to use a string constant.

**Expected behavior**:

It would be nice if jib called the closure at execution time. In other word moving the `project.files(from).toPath()` outside the setter, at the place it is really needed. Maybe in the `getFrom()` method ?

**Comment by mpeddada1** [comment]
Hey @bric3, 
If I’m not wrong, you are asking for some sort of late evaluation of the value passed to `extraDirectories.paths.path.from`? If this is what you’re looking for, we are still in the process of figuring out expanding late evaluation for parameters. Jib 2.6.0 currently supports late evaluation of jib.to.images and jib.to.tags by using gradle providers but we hope to extend it for others as well. But for the time being, have you tried using `[afterEvaluate](https://docs.gradle.org/current/javadoc/org/gradle/api/Project.html#afterEvaluate-groovy.lang.Closure-)` and  putting the unpackLibsodium code into a `project.afterEvaluate` block like this:
```
Jib {
  extraDirectories {
   …
        from =  project.afterEvaluate { // this will be evaluated after it has been set. 
                       unpackLibsodium.outputs
                            .files
                            .asFileTree
                            .matching { include "**/*.so" }
                            .singleFile
                            .parentFile
	}
```
Note: I haven’t been able to test this out locally but sharing your full `build.gradle` (if it is not too complex) would be of great help if the proposed soln doesn’t work.

**Comment by bric3** [comment]
Hi @mpeddada1 thank you for the feedback, I'm not sure it will work since the value in the output is already defined, it's just that the file don't exists yet tasks have yet to run. Also afterEvaluate returns `void`, should the `from =` be included in the closure.

And anyway I'll try to export the relevant bit to have a reproducible case.

**Comment by chanseokoh** [comment]
Just in case if you are blocked, at least I think there's an easy workaround: set `extraDirectories.paths` to a temporary directory (e.g., `extraDirectories.paths = 'build/my-libs-dir`), set up a [`Copy` task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html) to copy `.so` files into `my-libs.dir`, and have Jib depend on the Copy task. A bit of unnecessary copying here, but I think it will work. However, I'm not versed in Gradle at all, and I'm not sure if there's a better workaround or even this makes sense.

And we still want to go deeper into this issue to figure out what can be done generally, so it'll be helpful for us to have a reproducible case.

**Comment by loosebazooka** [comment]
Just curious how your unpack lib sodium task works?

If you're using a gradle Copy task to do it, maybe you can inject all this logic in there?
```groovy

def libsodiumOut = "${buildDir}/libsodium"

task unpack(type: Copy) {
  from {
    tarTree(resources.gzip("libsodium.tar.gz")).matching({include "**/*.so"}).singleFile
    //or for .zips -- zipTree("libsodium.zip").matching({include "**/*.so"}).singleFile
  }
  into(libsodiumOut)
}
```
and then just use `libsodiumOut` in extraDirectories

**Comment by bric3** [comment]
@loosebazooka Sorry, I missed this message, I have reworked the unpacking task for another reason.

Before when it didn't work, the unpacking task was

```gradle
task unpackLibsodium(dependsOn: downloadLibsodiumDeb) {
    inputs.property('libFilename', 'libsodium.so.23.3.0')
    inputs.property('debFile', downloadLibsodiumDeb.dest)
    outputs.file("${buildDir}/libsodium/linux/libsodium.so").withPropertyName('linuxLibraryFile')
    //...
}
```

This approach don't work well as the task outputs (`unpackLibsodium.outputs`) are not present if the task didn't run, also referring to `unpackLibsodium.linuxLibraryFile` don't work (https://github.com/gradle/gradle/issues/15284).

After my refactoring the unpack task looks like this

```gradle
task unpackLibsodium(dependsOn: downloadLibsodiumDeb) {
    description "Extract Libsodium Debian package file into $buildDir/libsodium directory"
    ext {
        debFile = downloadLibsodiumDeb.dest
        libFilename = 'libsodium.so.23.3.0'
        outDir = "${buildDir}/libsodium/linux"
        outFilename = 'libsodium.so'
        unpackedLibraryFile = "${outDir}/${outFilename}"
    }

    inputs.file(debFile)
    outputs.dir(outDir)
    outputs.file(unpackedLibraryFile)
    // ...
}
```

With this setup, the `outDir` property is known before the unpack task is run, and as it is declared in the `ext` block of the task, it can be referred to as `unpackLibsodium.outDir` in the jib, which does seem to work.
