### ISSUE TITLE
Can no longer append values dynamically to tags property

### ISSUE THREAD

**Issue by coopstah13** [GoogleContainerTools/jib#2909]
**Environment**:

- *Jib version:* 2.6.0
- *Build tool:* Gradle 6.7
- *OS:* Linux/Mac OS

**Description of the issue**:
Cannot dynamically append to the tags

**Expected behavior**:
Can dynamically append to the tags

**Steps to reproduce**:

  1. Assign value to the tags property
  2. Append a value to the tags property

**`jib-gradle-plugin` Configuration**: 
```groovy
        tags = ["my_tag"]
        tags << "latest"
```

**Log output**: 
```
> java.lang.UnsupportedOperationException (no error message)
```

**Additional Information**: 
This works in 2.5.0. I'm assuming it was broken by #2727.
In our case, when we build our master branch, we conditionally were adding the "latest" tag to that property using the groovy left shift operator. This no longer works since tags is now returned as a SingletonImmutableSet object.

**Comment by loosebazooka** [comment]
Yeah, you're right, the behavior has changed. It's unfortunate that we did not anticipate this usecase but I believe the way forward is to adjust how you do this:

perhaps?
```
tags = tags + ["latest"]
```

**Comment by coopstah13** [comment]
interestingly we found that
```
tags += ["latest"]
```
works, I think because groovy is creating a new list rather than append to the left hand side as it does with `<<`

**Comment by chanseokoh** [comment]
Looks like this isn't going to be an issue to you. I'll close this, but feel free to update.
