### ISSUE TITLE
[jib-cli-jar] Add option to specify base image in jib cli jar command 

### ISSUE THREAD

**Issue by mpeddada1** [GoogleContainerTools/jib#2923]
The jib cli jar subcommand currently only uses the distroless base image (the default) but we should add a `--base-image` parameter to allow users to specify a base image of their choice.

**Comment by chanseokoh** [comment]
The `BuildFileSpec` has it as `from` --> `image`. Maybe `--from-image`?

https://github.com/GoogleContainerTools/jib/blob/master/proposals/buildfile.md#jib-cli-buildfile-specification
