### ISSUE TITLE
Deprecation warning for property jib.container.expandClasspathDependencies

### ISSUE THREAD

**Issue by juergenzimmermann** [GoogleContainerTools/jib#2930]
**Environment**:

- *Jib version:* 2.7.0
- *Build tool:* Gradle 6.8-rc-1
- *OS:* Windows 10 Enterprise 2004

**Description of the issue**:
When I invoke `gradle jibDockerBuild` I get this deprecation warning:
```
Property 'jib.container.expandClasspathDependencies' @Input properties with primitive type 'boolean' cannot be @Optional. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.8-rc-1/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
```

**Expected behavior**:
No warning.

**Steps to reproduce**:
Just a simple gradle project with the config below.

**`jib-gradle-plugin` Configuration**:
```kotlin
jib {
    from {
        image = "gcr.io/distroless/java-debian10:11"
    }
    to {
        image = project.name
    }
}
```

**Log output**: see above

**Comment by loosebazooka** [comment]
this should be fixed

**Comment by chanseokoh** [comment]
@juergenzimmermann 2.7.1 is released with the fix.

**Comment by juergenzimmermann** [comment]
@chanseokoh Thank you!
