### ISSUE TITLE
Consider outputting to a subdirectory under /tmp/ instead of /tmp by default

### ISSUE THREAD

**Issue by nivekuil** [GoogleContainerTools/jib#2939]
It looks like jib dumps a bunch of stuff under `/tmp/` like `/tmp/18205206676401484098/layers/179079355f3e6be0baffff364e59e7f3a3076fbb7c65e10fc5217d9fdca88840`.  It would be more clear that this stuff comes from jib and easier to delete if it used something like `/tmp/jib` by default.

**Comment by chanseokoh** [comment]
Hi @nivekuil,

That's a great suggestion. Are you using jib-core or Jib Maven/Gradle plugin?

**Comment by nivekuil** [comment]
I'm using a build tool (https://github.com/juxt/pack.alpha) that itself uses jib-core.

**Comment by chanseokoh** [comment]
Thanks. I'll close this in favor of #2942.
