### ISSUE TITLE
Provide better defaults for jib application cache

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#2942]
If we create a new directory for application cache each time in jib-core, then we will not be able to re-use the application cache because of directory changes.

Instead of creating a new tmp dir. Just create a fixed named location in tmp.
The only question is whether applications should share a cache or they should be separate:
- `/tmp/jib/<hash of project context>/...`
- `/tmp/jib/...`

**Comment by chanseokoh** [comment]
Fixed by #2938 (jib-cli) and #2945 (jib-core).

For jib-core, the directory is `/tmp/jib-core-application-layers-cache` (typically on Linux), shared by all jib-core apps.

For jib-cli, it's `/tmp/jib-cli-cache/projects/<some sha256 checksum>/application-layers`.
