### ISSUE TITLE
Add internal cacert to /etc/ssl/certs/java/cacerts

### ISSUE THREAD

**Issue by gabrieljones** [GoogleContainerTools/jib#2971]
**Environment**:

- *Jib version:* 2.6.0
- *Build tool:* Gradle 6.7.1
- *OS:* MacOS

**Description of the issue**:
I'd like a way to add my internal `cacert.pem` file to the `/etc/ssl/certs/java/cacerts` file that comes with the base image.

**Expected behavior**:
I specify some directory containing `cacert.pem` files, they all get added to the existing `/etc/ssl/certs/java/cacerts` in the resulting image.

This is distinct from https://github.com/GoogleContainerTools/jib/issues/2240 which merely wants to be able to replace the existing `cacerts` file.  I want to be able append to it.

**Comment by gabrieljones** [comment]
Do different jvm base images have different paradigms/protocols for loading cacerts into the TLS subsystem? If they are all the same this should be relatively simple.

**Comment by gabrieljones** [comment]
This could even be an opinionated default dir within the `src/main` 
Something like `src/main/jibAdditionalCACerts/**.pem`

**Comment by loosebazooka** [comment]
So there is the extradirectories option to add any arbitrary file to the container? But we don't have any configuration built specifically for certs

**Comment by gabrieljones** [comment]
> So there is the extradirectories option to add any arbitrary file to the container? But we don't have any configuration built specifically for certs

How would I extract out the `/etc/ssl/certs/java/cacerts` file from the base image and then add back my modification to it during the build?

**Comment by loosebazooka** [comment]
Yeah that's the problem, we don't offer mutation of files like that because jib doesn't do a build by execution in the container environment. 

Hacky: I wonder if you can just reference that file on your local machine and do the modification all locally and dump it in your container via `extraDirectories`

**Comment by gabrieljones** [comment]
Is the `cacerts` file for a given jvm distro version available via some other maven central dependency channel?

**Comment by loosebazooka** [comment]
I think the most I can do at the moment is acknowledge this is an issue, but also beyond my expertise, looking to see if @saturnism has an insights with specific customer use?

**Comment by jdarmetzki** [comment]
I am currently also looking for a solution for this exact problem. 
For reference, this is what we currently do in our Dockerfiles to import our CA-Certs: 
`RUN $JAVA_HOME/bin/keytool -importkeystore -srckeystore /<our_ca_certs>.jks -srcstorepass <pass> -destkeystore $JAVA_HOME/lib/security/cacerts -deststorepass changeit`

**Comment by chanseokoh** [comment]
For now, I think the best solution is to prepare your own `cacerts` in advance (could be done at build time by Maven or Gradle if desired) and copy the file into the right place into an image at image building time (e.g., using `<extraDirectories>`) as in #2240. As you can imagine, extracting and modifying any file from a base image is a non-trivial task for both Jib and anyone doing it manually. And for this type of files (`cacerts`), another model that may make sense is to provide it at runtime (e.g., mounting it on Kubernetes).

another relevant SO link: https://stackoverflow.com/a/62998403/1701388

**Comment by gabrieljones** [comment]
> For now, I think the best solution is to prepare your own `cacerts`

I'm happy to do this. Is there any kind of "official" list of CA certs published to maven central that I can reference in my build?

I found https://curl.haxx.se/docs/caextract.html

It would be so much nicer if it was published to maven central though. Regarding corporate nexus proxies and such.

**Comment by gabrieljones** [comment]
Related:
https://hg.mozilla.org/mozilla-central/raw-file/tip/security/nss/lib/ckfw/builtins/certdata.txt
https://godoc.org/github.com/agl/extract-nss-root-certs
[https://github.com/grpc/grpc/tree/master/etc](https://github.com/grpc/grpc/tree/b7df39f095417754e99558d3c9b277e30274005f/etc)
https://github.com/AdoptOpenJDK/openjdk-support/issues/13

**Comment by gabrieljones** [comment]
Even more related:
https://github.com/AdoptOpenJDK/openjdk-build/pull/2113

**Comment by gabrieljones** [comment]
https://github.com/AdoptOpenJDK/openjdk-build/tree/master/security

**Comment by jdarmetzki** [comment]
Like @gabrieljones wrote, building a cacerts-file yourself adds the massive overhead of having make sure you have a up-to-date upstream version. This makes the whole process a lot less attractive, as missing an important update has the potential to create strange, unexpected and difficult to find problems.

**Comment by dides82** [comment]
Hi all,
we started adding modified cacerts to our images with the extra-directories option of jib. However, with the increasing number of micro services of our stack, it became rapidly painful to go through all of them.
Since we work with Kubernetes, we decided to expose the cacert through a k8s secret. 
So we only have to modify it at one place and the change is taken into account directly for all pods.
This meets a best practice for java container that is not to contain keystores and to externalize configuration.

**Comment by mpeddada1** [comment]
Thank you sharing your approach! Closing this issue given the availability of potential alternative solutions and the [SO post](https://stackoverflow.com/questions/62991314/adding-ssl-certificate-when-using-google-jib-and-kubernetes/62998403#62998403) that @chanseokoh linked.
