### ISSUE TITLE
Support dependencies inclusion/exclusion into layer

### ISSUE THREAD

**Issue by strowk** [GoogleContainerTools/jib#2986]
This is a feature request. 

Sometimes it's needed to exclude certain dependencies from resulting build. Example - when AspectJ is used to weave certain libraries, it produces result in classes and jar of that dependency should not be included in the build. 

To have exclusions with maven-shade-plugin for example, we are using `excludes`, which are supported by that plugin. With jib same result is possible to receive by using `provided` scope, however that have unintended effect that all transitive dependencies become provided as well and we have to add those dependencies as well and change their scope to runtime. This requires adding sometimes quite a lot of dependencies, which increases pom.xml somewhat.

Suggestion is to support some way of selecting which dependencies should not go in the resulting build. Here's an example of excluding from maven-shade-plugin:
```

                    <artifactSet>
                        <excludes> <!-- Following artifacts are weaved by aspectj and are already in the fat jar -->
                            <exclude>com.typesafe.akka:akka-actor_${scala.tools.version}</exclude>
                            <exclude>io.kamon:kamon-akka-${akka.major.version}_${scala.tools.version}</exclude>
                            <exclude>org.aspectj:aspectjtools</exclude>
                        </excludes>
                    </artifactSet>
```

It's just an example how it could look like. Jib could have a different configuration. There could be inclusion rule as well. Maybe it would be even convenient to define list of layers, each with its own inclusions/exclusions, for situation when user wants to separate dependencies into different layers based on how often they're changed (f.e. if project has a library shared between services, which changes often and framework libs, which do not).

**Comment by chanseokoh** [comment]
Hi @strowk,

We have a [Jib Layer-Filter Extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-maven) that covers these use cases.

BTW, I'm interesting in hearing in more details why you should exclude some dependencies at runtime while declaring it in `pom.xml` as runtime dependencies when using AspectJ. (We have zero knowledge about AspectJ.)

**Comment by strowk** [comment]
Ah, cool extension, seems like it could work, I'll try it later. BTW I was follwing this guide 
https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#quickstart
Maybe it worth mentioning extensions in there

So regarding AspectJ use with Maven. Plugin takes classes from dependency, transforms them (adds some proxying in functions, etc) and puts result as a classes as if they were built from app code (that callsed "weaving"). Then those appear in the "classes" layer of jib. Some of those dependencies are not even specified directly in our pom, but they come transitevely from other libraries and that's ok. Now the problem is that jib includes original classes (as jars) into "dependecies" layer as well.
 
So I managed so far to remove jars from that layer by making them provided, while simultaneously overriding their transitive dependencies as runtime. Say S (service) depends on A, which depends on B, which depends on C. AspectJ "weaves" B, now I want to exclude B without loosing C. So I'm adding dependency from S to B, make it of `provided` scope, but then C also becomes `provided` and is missing in runtime (AspectJ did not "weave" it), so I have to add dependency from S to C as well and override scope to be `runtime`.

But now I see that filter extension should be enough to not do all that black magic..

**Comment by chanseokoh** [comment]
Thanks for all the details!

**Comment by chanseokoh** [comment]
Added documentation in the build plugin `README.md` files.
