### ISSUE TITLE
Multiple valid main classes were found

### ISSUE THREAD

**Issue by majorinche** [GoogleContainerTools/jib#3007]
pom.xml is setting like follow
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>2.4.0</version>
                <configuration>
                    <from>
                        <image>harbor.newbase.com/cicd/jdk.18</image>
                    </from>
                    <to>
                        <image>harbor.newbase.com/cicd/ddd</image>
                        <auth>
                            <username>admin</username>
                            <password>admin</password>
                        </auth>
                    </to>
                </configuration>
            </plugin>

mvn compile -s settings.xml jib:build -DsendCredentialsOverHttp=true
reports this error:
Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.7.1:build (default-cli) on project fateboard: Multiple valid main classes were found: com.webank.ai.fate.board.bootstrap.Bootstrap, com.webank.ai.fate.board.pojo.Job, com.webank.ai.fate.board.utils.GetSystemInfo, perhaps you should add a `mainClass` configuration to jib-maven-plugin

do i need to set 'mainClass' and how to do that?

**Comment by loosebazooka** [comment]
Set the main class in the jib plugin config.
```
<container><mainClass>my.main.class</container></mainClass>
```

**Comment by loosebazooka** [comment]
closing for now, please reopen if you have any followup questions
