### ISSUE TITLE
Vertx example fails with: com.google.cloud.tools.jib.plugins.common.MainClassInferenceException

### ISSUE THREAD

**Issue by javadevmtl** [GoogleContainerTools/jib#3025]
As the title says. The faillure is:

```
com.google.cloud.tools.jib.plugins.common.MainClassInferenceException: Main class was not found, perhaps you should add a `mainClass` configuration to jib
```

Sample gradle.build
```
plugins {
    id 'io.vertx.vertx-plugin' version '1.2.0'
    id 'com.google.cloud.tools.jib' version '2.7.1'
}


group 'com.acme'
version '1.0-SNAPSHOT'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

vertx {
    mainVerticle = 'com.acme.Main'
    vertxVersion = "3.9.5"
}

jib {
    container {
        ports = ['8080']
    }
}
```

**Comment by chanseokoh** [comment]
Hi @javadevmtl,

I just ran `./gradlew jibDockerBuild` as instructed in the [README of the Vert.x example](https://github.com/GoogleContainerTools/jib/tree/master/examples/vertx), and it runs OK. Which example are you referring to? And does it have a `.java` file with `public static void main(String[])` like [this one in the Vert.x example](https://github.com/GoogleContainerTools/jib/blob/bf6199bdcf65d6a58e9375076fb2776ef239a94c/examples/vertx/src/main/java/example/vertx/MainVerticle.java#L14-L16)?

**Comment by javadevmtl** [comment]
Ok nothing to see here then lol My bad I didn't see the static main in the example.
