### ISSUE TITLE
Latest built image - shows 51 years ago in local docker 

### ISSUE THREAD

**Issue by iamsivav** [GoogleContainerTools/jib#3030]
**Environment**: local

- *Jib version:* 2.0.0
- *Build tool:*  Maven 3.5.4
- *OS:*  Mac OS - Big Sur

**Description of the issue**:
 Incorrect Image timestamp published in local docker image registry.

**Expected behavior**:
It should say XX minutes ago.

**Steps to reproduce**:

  1.  I configured the jib-maven-plugin in my springboot application.
  2. Executed "clean package jib:dockerBuild" to publish the image in my local docker.
  3. ran "docker image ls" in Terminal and the Image Timestamp shows "**51 Years Ago**". 

**`jib-maven-plugin` Configuration**: 
```xml
<plugins>
					<plugin>
						<groupId>com.google.cloud.tools</groupId>
						<artifactId>jib-maven-plugin</artifactId>
						<version>2.0.0</version>
						<configuration>
							<to>
								<image>registry.hub.docker.com/{username}/image-built-with-jib</image>
							</to>
						</configuration>
					</plugin>
				</plugins>
```

**Log output**: 
INFO] --- spring-boot-maven-plugin:2.2.5.RELEASE:repackage (repackage) @ spring-boot-feign-learn ---
[INFO] Replacing main artifact with repackaged archive
[INFO] 
[INFO] --- jib-maven-plugin:2.0.0:dockerBuild (default-cli) @ spring-boot-feign-learn ---
[INFO] 
[INFO] Containerizing application to Docker daemon as registry.hub.docker.com/{username}/image-built-with-jib...
[WARNING] Base image 'gcr.io/distroless/java:8' does not use a specific image digest - build may not be reproducible
[INFO] Getting manifest for base image gcr.io/distroless/java:8...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO] Using base image with digest: sha256:fc50011690ad9ea2b8001f1f83f24d15089992fae78d3b731c0e1564ee0a61f3
[INFO] 
[INFO] Container entrypoint set to [java, -cp, /app/resources:/app/classes:/app/libs/*, com.sv27.learn.SpringBootFeignLearnApplication]
[INFO] Loading to Docker daemon...
[INFO] 
[INFO] Built image to Docker daemon as registry.hub.docker.com/{username}/image-built-with-jib

**Additional Information**: 

<img width="1171" alt="Screen Shot 2021-02-03 at 11 09 57 PM" src="https://user-images.githubusercontent.com/34560264/106843904-1f768580-6675-11eb-88b6-cd44821208e3.png">

<img width="1207" alt="Screen Shot 2021-02-03 at 11 12 54 PM" src="https://user-images.githubusercontent.com/34560264/106844000-63698a80-6675-11eb-840f-6a691b68d39e.png">

**Comment by mpeddada1** [comment]
Hey @iamsivav, thanks for the question. Jib sets the creation time of the container image to the unix epoch `(00:00:00, January 1st, 1970 in UTC)` for the purpose of reproducibility. This is why the image is seen as being created 51 years ago. You can also set the timestamp to the build time as shown below but keep in mind that doing so will sacrifice reproducibility. (More info in the [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago))

Setting creation time to the current time:
```
<configuration>
  <container>
    <creationTime>USE_CURRENT_TIMESTAMP</creationTime>
  </container>
</configuration>
```

**Comment by iamsivav** [comment]
@mpeddada1 Thanks for clarifying and responding quickly. This issue can be closed.
