### ISSUE TITLE
Jib should be able to backoff and retry when it receives 429 to many requests

### ISSUE THREAD

**Issue by tjtaill** [GoogleContainerTools/jib#3042]
**Environment**:

- *Jib version: 2.7.1
- *Build tool:* Maven 3.6.3 jib-maven-plugin: 2.7.1
- *OS:* AWS Codebuild 4.0 Ubuntu

**Description of the issue**:

Inside AWS Codebuild I periodically get 429 to many request error

**Expected behavior**:

I expect the Jib to backoff and retry so my CI build doesn't fail be nice if they were configurable parameters
like number of retries and backoff parameters like fixed time, random and exponential

**Steps to reproduce**:

  1. inside an aws codebuild container
  2. run `mvn -q compile jib:dockerBuild -Djib.to.image=$IMAGE_REPO_URL:$TAG -Djib.to.credHelper=ecr-login -Djib.jvmFlags=-Dspring-boot.run.profiles=prod` a couple of times
  3. you will observe the 429 to many requests error 

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <version>2.7.1</version>
  <configuration>
  <from>
	<image>openjdk:11-jre-slim</image>
  </from>
  </configuration>
</plugin>
```

**Log output**: 

Container] 2021/02/08 00:40:08 Running command mvn -q compile jib:dockerBuild -Djib.to.image=$IMAGE_REPO_URL:$TAG -Djib.to.credHelper=ecr-login -Djib.jvmFlags=-Dspring-boot.run.profiles=prod
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.7.1:dockerBuild (default-cli) on project rest-event-box: 429 Too Many Requests
[ERROR] GET https://registry-1.docker.io/v2/library/openjdk/manifests/11-jre-slim
[ERROR] {
[ERROR] "errors": [
[ERROR] {
[ERROR] "code": "TOOMANYREQUESTS",
[ERROR] "message": "You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit"
[ERROR] }
[ERROR] ]
[ERROR] }
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Additional Information**:

**Comment by chanseokoh** [comment]
FTR: https://gitter.im/google/jib?at=60213f4384e66b7f7edd5c90

**Comment by chanseokoh** [comment]
@tjtaill I know you are already using the [`retry` tool](https://github.com/kadwanev/retry), and I think it's an effective way to achieve retrying with increasing back-offs. But to better support the users hitting the Docker Hub rate limit, we implemented the registry mirror feature, which is now live with the Jib 2.8.0 release. Check out this [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-hitting-docker-hub-rate-limits-how-can-i-configure-registry-mirrors) to learn how to configure it.

**Comment by tjtaill** [comment]
Awesome thanks
