### ISSUE TITLE
Files created in user.home although baseImageCache set to different directory

### ISSUE THREAD

**Issue by alexbde** [GoogleContainerTools/jib#3049]
Hi all!

**Environment**:

- *Jib version:* 2.7.1
- *Build tool:* Maven 3.6.3
- *OS:* docker.io/library/maven:3.6.3-openjdk-11

**Description of the issue**:

I set options `baseImageCache` and `applicationCache` because user home (`$HOME`/`~`) is not set in my build setup. But I still can see two files written to user home (Jenkins is replacing `~` with `$WORKSPACE/?` as it is not set). The other files are correctly written to configured caching directories.
 
![image](https://user-images.githubusercontent.com/17784818/107637540-8f38d180-6c6e-11eb-95a4-ca333801d6e3.png)

**Expected behavior**:

All cache files are written to configured caching directories.

**Steps to reproduce**:

  1. Run `mvn com.google.cloud.tools:jib-maven-plugin:2.7.1:dockerBuild -Djib.from.image=x -Djib.to.image=y -Djib.baseImageCache=.buildcache/jib -Djib.applicationCache=.buildcache/jib` via Jenkins declarative Docker pipeline.
  2. Find files `config.json` and `lastUpdateCheck` in `$WORKSPACE/?/.config/google-cloud-tools-java/jib`.

**`jib-maven-plugin` Configuration**: none, command line invocation only

**Comment by chanseokoh** [comment]
Hi @alexbde,

Base image and application layer caches go into a platform-dependent conventional cache directory by default. In your case, it would probably be `$HOME/.cache/...`. Normally it's harmless to clear this cache directory, and applications will continue to function normally.

On the other hand, those `config.json` and `lastUpdateCheck` files are not cache files but configuration files. They go to a conventional config directory by default, which in your case is `$HOME/.config/...`. Applications often store their configuration under this directory, and you don't want to clear this directory.

If for some reason you want to change the config directory for Jib, you can set [`$XDG_CONFIG_HOME`](https://github.com/GoogleContainerTools/jib/pull/3002/files#diff-c29050ce36cf927d96c52c317225d05d41fac12ee634eb8efd6a2c17b670cc0cR319) for the Jib process.

Or, if you don't or have no plan to persist those config files (most likely you will not), don't be bothered with those files. Jib will create `config.json` with the default settings if it doesn't exist.

Hope this helps.

**Comment by alexbde** [comment]
Thank you very much for pointing out difference between cache and configuration files! Makes no difference in my case, just as you pointed out, so I'll set `$XDG_CONFIG_HOME`. Great it makes it to the docs in the next release.

Just as side note: root cause of question mark (`?`) directory is `$HOME` is not set correctly via Maven/JVM (see [this article](https://support.cloudbees.com/hc/en-us/articles/360049463431-Why-do-I-have-directory-named-question-mark-in-my-workspace-)). Passing it explictly to Maven/JVM is also solving the issue: `mvn -Duser.home=$HOME ...` (note you might need to escape `$` if you run this in Jenkins Docker pipeline).
