### ISSUE TITLE
Jib-gradle-plugin jib.httpTimeout not taken into account

### ISSUE THREAD

**Issue by GianniGiglio** [GoogleContainerTools/jib#3054]
**Environment**:

- *Jib version: 2.6.0* 
- *Build tool:* gradle 6.7

**Description of the issue**:

Getting the following error when building:

`15:27:50  Container entrypoint set to [java, -XX:MaxMetaspaceSize=512m, -Djava.security.egd=file:/dev/./urandom, -javaagent:/app/WEB-INF/lib/otel-javaagent.jar, -Dotel.instrumentation.jdbc-datasource.enabled=false, -Dotel.instrumentation.servlet-filter.enabled=true, -Dotel.instrumentation.servlet-service.enabled=true, -cp, /app/resources:/app/classes:/app/libs/*, ...]
15:28:22  [31;1mI/O error for image [docker-staging.repository.collibra.io/arch/dgc-aggregator]:[0m
15:28:22  [31;1m    java.net.SocketTimeoutException[0m
15:28:22  [31;1m    Read timed out[0m`

gradle.properties contain the following property

jib.httpTimeout=0

Never the less from the logs you can see it times out after +-20 seconds.

It seems the property doesn't have any effect.

**Comment by chanseokoh** [comment]
Hi @GianniGiglio, what's the exact command on the command-line you used?

And I don't know if this is relevant in your case, but often there are other layers imposing network timeout, typically a kernel. From https://github.com/GoogleContainerTools/jib/issues/2014#issuecomment-534610778,

> As I said, often you need to lift the timeouts imposed by the kernel. On my machine for example, I found the connection timeout is set to 30 seconds, so setting the timeout over 30 seconds at the JVM level is meaningless.

**Comment by chanseokoh** [comment]
Never mind the command. I see you set it in `gradle.properties`.

**Comment by GianniGiglio** [comment]
> Hi @GianniGiglio,
> 
> I don't know if this is relevant in your case, but often there are other layers imposing network timeout, typically a kernel. From [#2014 (comment)](https://github.com/GoogleContainerTools/jib/issues/2014#issuecomment-534610778),
> 
> > As I said, often you need to lift the timeouts imposed by the kernel. On my machine for example, I found the connection timeout is set to 30 seconds, so setting the timeout over 30 seconds at the JVM level is meaningless.

I'll check that.

**Comment by chanseokoh** [comment]
If you want to set a system property, it should be
```
systemProp.jib.httpTimeout=1
```
https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties

I verified that `jib.httpTimeout` takes effect.

**Comment by chanseokoh** [comment]
And an easy way to verify if it takes effect is to set the timeout to 1 sec. Most of the time, you'll timeout immediately.

**Comment by GianniGiglio** [comment]
Hey,
The jib.httpTimout option works when passing directly to the task but it doesn't work when it's specified in the gradle.properties

**Comment by chanseokoh** [comment]
I did verify that specifying it in `gradle.properties` works in a sample project. (If you need proof, I can provide it.) Are you sure you added the `systemProp.` prefix?

Anyways, I think now this seems like an issue in Gradle configuration or a project setup. Maybe ask on a Gradle forum why system properties can't be set via `gradle.properties`? I'll close the issue as Jib is working correctly and this is not a Jib issue, but feel free to update if you some need help.

**Comment by GianniGiglio** [comment]
I'll have to test it using systemProp. Anyway, I have a workaround for now.

**Comment by chanseokoh** [comment]
> It feels odd that is have to set this as a systemProp in the gradle file

It's [how Gradle works](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties). There are notions of "[Gradle properties](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties)" and JVM-wide "[system properties](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties)."

Also note in the doc that, for the system properties,

> In a multi project build, “`systemProp.`” properties set in any project except the root will be ignored. That is, only the root project’s `gradle.properties` file will be checked for properties that begin with the “`systemProp.`” prefix.

**Comment by GianniGiglio** [comment]
> > It feels odd that is have to set this as a systemProp in the gradle file
> 
> It's [how Gradle works](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties). There are notions of "[Gradle properties](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_configuration_properties)" and JVM-wide "[system properties](https://docs.gradle.org/current/userguide/build_environment.html#sec:gradle_system_properties)."
> 
> Also note in the doc that, for the system properties,
> 
> > In a multi project build, “`systemProp.`” properties set in any project except the root will be ignored. That is, only the root project’s `gradle.properties` file will be checked for properties that begin with the “`systemProp.`” prefix.

Yeah correct, just a bit odd to use jvm properties. The Gradle way would be to use project properties instead that's why am confused :)

**Comment by chanseokoh** [comment]
Oh, I see the confusion. They are [system properties](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#system-properties).
