### ISSUE TITLE
Getting manifest for base image uses Proxy even if it is set in nonProxyHosts

### ISSUE THREAD

**Issue by sforner405** [GoogleContainerTools/jib#3059]
**Environment**:

- *Jib version:* 2.7.1
- *Build tool:* Maven
- *OS:* Ubuntu (Official 3.6.3 Docker Image with openjdk 11) running on Jenkins as agent

**Description of the issue**:

Timeout while Getting manifest for base image. It still uses proxy, but it was set as nonProxyHost in settings.xml and jvm.config  .

**Expected behavior**:

Should honor proxy settings.

**Steps to reproduce**:

  1. Setup System Proxy
  2. Add settings.xml and jvm.config with nonProxyHost
  3. set From Image to a registry in nonProxyHost

**`jib-maven-plugin` Configuration**: 
```xml
<configuration>
          <skip>${docker.image.skip}</skip>
          <from>
            <image>internal.reg.com/openjdk:11-jre-slim-latest</image>
          </from>
          <to>
            <image>${docker.registry}/${docker.image.prefix}/${docker.image.name}</image>
          </to>
          <container>
            <creationTime>USE_CURRENT_TIMESTAMP</creationTime>
            <ports>
              <port>${docker.image.exposedPort}</port>
            </ports>
          </container>
          <pluginExtensions>
            <pluginExtension>
              <implementation>com.google.cloud.tools.jib.maven.extension.springboot.JibSpringBootExtension</implementation>
            </pluginExtension>
          </pluginExtensions>
        </configuration>
```

**Log output**: 

[WARNING] Base image 'internal.reg.com/openjdk:11-jre-slim-latest' does not use a specific image digest - build may not be reproducible
[INFO] Getting manifest for base image internal.reg.com/openjdk:11-jre-slim-latest...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for service 0.0.1-SNAPSHOT:
[INFO] 
[INFO] service ..................................... SUCCESS [  1.847 s]
[INFO] service_api ................................. SUCCESS [  0.307 s]
[INFO] service_app ................................. FAILURE [01:00 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:02 min
[INFO] Finished at: 2021-02-18T12:52:54Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.7.1:dockerBuild (default-cli) on project service_app: 503 Service Unavailable
[ERROR] GET https://internal.reg.com/v2/openjdk/manifests/11-jre-slim-latest

**Additional Information**: 
File can be downloaded without proxy.
Proxy (Squid) provides 503, because he cannot resolve hostname.
```xml
<proxy>
      <id>http-proxy</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>security-proxy.reg.net</host>
      <port>3128</port>
      <nonProxyHosts>localhost|127.0.0.1|*.reg.com|internal.reg.com</nonProxyHosts>
    </proxy>
      <proxy>
      <id>https-proxy</id>
      <active>true</active>
      <protocol>https</protocol>
      <host>security-proxy.reg.net</host>
      <port>3128</port>
      <nonProxyHosts>localhost|127.0.0.1|*.reg.com|internal.reg.com</nonProxyHosts>
    </proxy>
```

```
-Dhttp.nonProxyHosts="localhost|127.0.0.1|*.reg.com|internal.reg.com"
```

**Comment by chanseokoh** [comment]
Hi @sforner405,

It works. You can follow the exact commands below to confirm yourself.
```
$ cd /tmp
$ git clone https://github.com/GoogleContainerTools/jib.git
$ cd jib/examples/helloworld/
$ cat > proxy-settings.xml <<EOF
<settings>
  <proxies>
    <proxy>
      <id>http</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>proxy.test.example.com</host>
      <port>3128</port>
      <nonProxyHosts>*.com|localhost</nonProxyHosts>
    </proxy>
    <proxy>
       <id>https</id>
       <active>true</active>
       <protocol>https</protocol>
       <host>proxy.test.example.com</host>
       <port>3128</port>
       <nonProxyHosts>*.com|localhost</nonProxyHosts>
     </proxy>
   </proxies>
</settings>
EOF
$ # Build fails below, because "docker.io" goes through "proxy.test.example.com".
$ mvn -s proxy-settings.xml -Djib.from.image=alpine -Djib.to.image=test-image compile jib:dockerBuild
...
[ERROR]     java.net.UnknownHostException
[ERROR]     proxy.test.example.com: Name or service not known
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
...
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.7.1:dockerBuild (default-cli) on project helloworld: proxy.test.example.com: Name or service not known: Unknown host proxy.test.example.com: Name or service not known -> [Help 1]
...
$ # Now add "*.io" to <nonProxyHosts>
$ cat > proxy-settings.xml <<EOF
<settings>
  <proxies>
    <proxy>
      <id>http</id>
      <active>true</active>
      <protocol>http</protocol>
      <host>proxy.test.example.com</host>
      <port>3128</port>
      <nonProxyHosts>*.com|*.io|localhost</nonProxyHosts>
    </proxy>
    <proxy>
      <id>https</id>
      <active>true</active>
      <protocol>https</protocol>
      <host>proxy.test.example.com</host>
      <port>3128</port>
      <nonProxyHosts>*.com|*.io|localhost</nonProxyHosts>
    </proxy>
  </proxies>
</settings>
EOF
$ # Works now.
$ mvn -s proxy-settings.xml -Djib.from.image=alpine -Djib.to.image=test-image compile jib:dockerBuild
...
[INFO] Built image to Docker daemon as test-image
[INFO] Executing tasks:
[INFO] [==============================] 100.0% complete
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...
```

One hypothesis why it's not working in your case: the way Jib supports proxy settings defined in `settings.xml` is by reading the values and setting the [JVM-wide standard networking system properties](https://docs.oracle.com/javase/8/docs/api/java/net/doc-files/net-properties.html) (such as `http(s).proxyHost`). That is, [our code skips setting the proxy system properties](https://github.com/GoogleContainerTools/jib/blob/9f4c93cf6b66cc67b674ff8f574892c1bf148c7a/jib-maven-plugin/src/main/java/com/google/cloud/tools/jib/maven/MavenSettingsProxyProvider.java#L49-L51) if any of the proxy-related system properties are already set per protocol.

Therefore, at least configuring all the system properties on the command-line with `-Dhttp(s)....` should work. They will take precedence.

**Comment by sforner405** [comment]
Hi @chanseokoh,
thanks for the answer.
This seems to be one part of the solution, as they show why the settings are not working.
But if I run your example with :

`mvn  -Dhttp.nonProxyHosts="*.io" -Dhttps.proxyHost=proxy.test.example.com -Dhttps.proxyPort=3128 -Djib.from.image=alpine -Djib.to.image=test-image compile jib:dockerBuild`

I get the error. It seems -Dhttp.nonProxyHosts="*.io" does not works here.

**Comment by sforner405** [comment]
Just rechecked.

If I run: 
`mvn -Dhttp.nonProxyHosts="*.io|*.com" -Dhttps.proxyHost=proxy.test.example.com -Dhttps.proxyPort=3128 -Djib.from.image=alpine -Djib.to.image=test-image compile jib:dockerBuild`

It works.
So it should be fine from your side.
Thanks!

**Comment by chanseokoh** [comment]
Thanks for the update. So, is the issue resolved? Have you figured out why it's not working in your environment?

**Comment by sforner405** [comment]
@chanseokoh:
Yes the issue is resolved. Had to set the setting additionally in the MAVEN_OPTS (could have been set in as cli param also), because the system settings had another syntax in the http.nonProxyHosts . This is because of another tool that needs commas instead of | to separate hosts .
So setting all the proxy settings explicitly worked.
