### ISSUE TITLE
jib often fails with "imagestreammappings: the object has been modified"

### ISSUE THREAD

**Issue by dmoebius** [GoogleContainerTools/jib#3101]
**Environment**:

- *Jib version:* 2.7.1
- *Build tool:* Gradle 6.7.1
- *OS:* CentOS

**Description of the issue**:

Very often (around every third build) `gradlew jib` fails with:

```
> Task :productservice:service:jib

Containerizing application to openshiftregistry.scoop-gmbh.de/xxxxx/product-service, openshiftregistry.scoop-gmbh.de/xxxxx/product-service:prod...
Base image 'adoptopenjdk/openjdk15:centos' does not use a specific image digest - build may not be reproducible
Using credentials from to.auth for openshiftregistry.scoop-gmbh.de/xxxxx/product-service
Getting manifest for base image adoptopenjdk/openjdk15:centos...
Building dependencies layer...
Building resources layer...
Building classes layer...
Building project dependencies layer...
The base image requires auth. Trying again for adoptopenjdk/openjdk15:centos...
Using base image with digest: sha256:065a8148eec0bf34dc093da7a8e50828c416e1838cd2f52f3d080564832ee56a

Container entrypoint set to [java, -Dfile.encoding=UTF-8, -XX:-OmitStackTraceInFastThrow, -XX:+HeapDumpOnOutOfMemoryError, -XX:HeapDumpPath=/tmp, -XX:MaxRAMPercentage=90, --enable-preview, -XX:+UseShenandoahGC, -cp, /app/resources:/app/classes:/app/libs/*, de.scoopsoftware.product_service.Main]

> Task :productservice:service:jib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':productservice:service:jib'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: 500 Internal Server Error
  PUT https://openshiftregistry.scoop-gmbh.de/v2/xxxxx/product-service/manifests/prod
  {"errors":[{"code":"UNKNOWN","message":"unknown error","detail":{"ErrStatus":{"metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on imagestreammappings.image.openshift.io \"product-service\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"product-service","group":"image.openshift.io","kind":"imagestreammappings"},"code":409}}}]}
```

**Expected behavior**:

Jib is the only process pushing to our registry, so this shouldn't fail with "the object has been modified".

**`jib-gradle-plugin` Configuration**: 
```groovy
    String now = ISO_OFFSET_DATE_TIME.format(now())
    String buildNumber = ofNullable(getenv("BUILD_NUMBER")).orElse("local")
    String gitCommit = getenv("BUILD_NUMBER") != null ? "git rev-parse HEAD".execute().text.trim() : "unknown"
    jib {
        container {
            mainClass = 'de.scoopsoftware.product_service.Main'
            ports = ['8180', '8181']
            jvmFlags = ['-Dfile.encoding=UTF-8', '-XX:-OmitStackTraceInFastThrow', '-XX:+HeapDumpOnOutOfMemoryError', '-XX:HeapDumpPath=/tmp', '-XX:MaxRAMPercentage=90', '--enable-preview', '-XX:+UseShenandoahGC']
            filesModificationTime = now
            environment = [
                    APP_STORAGE: '/data',
            ]
            labels = [
                    'de.scoopgmbh.proavo.build-date': now,
                    'de.scoopgmbh.proavo.build-number': buildNumber,
                    'de.scoopgmbh.proavo.git-commit': gitCommit,
            ]
        }
        from {
            image = 'adoptopenjdk/openjdk15:centos'
        }
        to {
            image = 'openshiftregistry.scoop-gmbh.de/xxxxx/product-service'
            tags = [getenv('DOCKER_IMAGE_TAG') ?: 'latest']
            auth {
                username = getenv('DOCKER_USERNAME')
                password = getenv('DOCKER_PASSWORD')
            }
        }
    }
```

**Comment by loosebazooka** [comment]
is it possible that your instance of openshift is unable to update an existing image tag?

**Comment by chanseokoh** [comment]
Looks like an internal sever error (bug) on OpenShift. Most likely a concurrency issue, whose nature may be similar to [#2470](https://github.com/GoogleContainerTools/jib/issues/2470) and [this](https://groups.google.com/g/quay-sig/c/7Pp80zhdgzM/m/DA4u8WGkAAAJ). I suggest filing a bug against OpenShift. If they need help or more information from the Jib side, we can help, as we've done in #2470. That said, definitely check out #2470 to see what could be possible workarounds to try.

@josephschorr (a Red Hat dev who fixed similar concurrency issues report by Jib) any ideas?

**Comment by josephschorr** [comment]
@chanseokoh I'm no longer affiliated with Red Hat, so my (wildly uninformed) guess is that the OpenShift Registry (which last I checked was backed by Kubernetes itself) might have tried to update the underlying `Image` Kub object after it had already been changed, which would definitely be a bug in that implementation.

I may be wildly off though :)

**Comment by dmoebius** [comment]
Many thanks for your answers. :smiley:  I'll try the suggested doings at #2470.

I don't think that our openshift registry is generally unable to update an existing image tag, because most of the time it works after the second retry. Like in #2470 it's probably some kind of concurrency issue. Maybe `jib.serialize=true` helps, but before trying this, I'll try to get some more logging output.

**Comment by chanseokoh** [comment]
@dmoebius looks like the error is when concurrently pushing two manifests (corresponds to two tags `latest` and `getenv('DOCKER_IMAGE_TAG')`). As explained [here](https://groups.google.com/g/quay-sig/c/7Pp80zhdgzM/m/DA4u8WGkAAAJ), you can [push the tags sequentially](https://github.com/GoogleContainerTools/jib/issues/2470#issuecomment-631500142), which will be very fast.

But I see that your config looks like
```
            image = 'openshiftregistry.scoop-gmbh.de/xxxxx/product-service'
            tags = [getenv('DOCKER_IMAGE_TAG') ?: 'latest']
```
Note "openshiftregistry.scoop-gmbh.de/xxxxx/product-service" for `jib.to.image` implies "openshiftregistry.scoop-gmbh.de/xxxxx/product-service:**latest**", so you are always creating `:latest` whether or not `DOCKER_IMAGE_TAG` is defined. Should it be like this to avoid confusion?
```
            image = 'openshiftregistry.scoop-gmbh.de/xxxxx/product-service'
            tags = getenv('DOCKER_IMAGE_TAG') ? [getenv('DOCKER_IMAGE_TAG')] : []
```

**Comment by dmoebius** [comment]
omg, you're right! No, it's *not* intended, that ":latest" is implied here. I thought Jib would push to _only_ to the specified tags, which is _either_ `getenv('DOCKER_IMAGE_TAG')` (if `DOCKER_IMAGE_TAG` is defined) _or_ "latest". I wasn't aware that the "tags" property only allows to specify _additional_ tags. (The docs say so; I have overlooked this.) Many thanks for the hint!

So, the correct solution imho is not to specify "tags" at all, but:
```
image = `openshiftregistry.scoop-gmbh.de/xxxxx/product-service:${getenv('DOCKER_IMAGE_TAG') ?: 'latest'}`
```

This also explains why pushing to `latest` never fails; it only fails when `DOCKER_IMAGE_TAG != 'latest'`.

**Comment by dmoebius** [comment]
We tested this for a couple of days now and it works fine. 
When pushing to more than one tag at the same time, ie. when using the `tags` property, we have to use '-Djib.serialize=true` though.
Our problem is solved. Many thanks for your great support!!
