### ISSUE TITLE
Be more flexible on jib-core dependencies and drop useless ones

### ISSUE THREAD

**Issue by rmannibucau** [GoogleContainerTools/jib#3109]
**Description of the issue**:

Not require so much runtime dependencies (details in next part)

**Expected behavior**:

1. Since java 11 becomes mainstream, using its httpclient is expected (instead of apache one)
2. Jackson is not always desired in particular when you have another mapper. Moving to jsonb spec will enable to use jackson or not very easily (or yasson/johnzon). Goal is to align it on the app runtime and stop duplicating libs (and their cve management which is time consuming for nothing IMHO).
3. Asm is only needed to find the main so it should be provided in jib-core and compile/implementation in the gradle/maven plugins (jib core users will import it if needed - note that implementing the find logic with reflection is trivial with maven since you know the module classpath and files so you can just test main method exists in a public class by reflection which enables to drop the dep). Generally integrations set the main explicitly anyway.
4. (More optional) I assume dropping guava and google http client layer is less desired but a quick review makes it not super critical for jib and easy to replace on java 8/11/...

Overall goal is to make jib way easier to include in runtimes without using shades and making it fat-tish.

**Comment by mpeddada1** [comment]
Hi @rmannibucau, we appreciate you bringing this up and agree that being selective about dependencies is beneficial.  However, the team is a little short on resources at the moment so it might be a while before we get to implement this. If you are interested in making a contribution, we will be happy to review it!
