### ISSUE TITLE
Run "package" and "jib:build" separately in a multimodule maven project

### ISSUE THREAD

**Issue by kan-izh** [GoogleContainerTools/jib#3117]
**Environment**:

- *Jib version:* 2.8.0
- *Build tool:* maven 3.6.2
- *OS:* Windows 10

**Description of the issue**:
When I run "mvn package" and "mvn jib:build" as separate commands, it does not work as it tries to download internal dependency from repository, instead of using local one.

11319 [main] [ERROR] Failed to execute goal on project name-service: Could not resolve dependencies for project com.example:name-service:jar:01.0: Could not find artifact com.example:shared-library:jar:0.1.0 in nexus (http://mirror:8081/repository/maven-public/) -> [Help 1]

**Expected behavior**:
jib goal should use local jars.

**Steps to reproduce**:

  1. go to `jib\examples\multi-module` which is a part of this repo
  2. mvn package
  3. mvn jib:build

**Log output**: 
11319 [main] [ERROR] Failed to execute goal on project name-service: Could not resolve dependencies for project com.example:name-service:jar:01.0: Could not find artifact com.example:shared-library:jar:0.1.0 in nexus (http://my-mirror:8081/repository/maven-public/) -> [Help 1]

**Additional Information**:

**Comment by loosebazooka** [comment]
Unforuntately this is how maven works, take a look at the readme README, it clearly explains how to correctly run the project: https://github.com/GoogleContainerTools/jib/tree/master/examples/multi-module#how-to-run
