### ISSUE TITLE
Recover generated images in multi-module project

### ISSUE THREAD

**Issue by sergiopacezup** [GoogleContainerTools/jib#3143]
In a CI/CD pipeline I need to deploy Jib generated images to test environment after the build step. It is a multi-module maven project and not every module generates images.

Is there a way to recover the names/tags of images generated by Jib after the build? Like I can with the image id in target/jib-image.id?

**Comment by chanseokoh** [comment]
Jib generates `target/jib-image.json` (#2227), and I think this is what you want?

**Comment by sergiopacezup** [comment]
Perfect!
