### ISSUE TITLE
Expose jib classpath and mainClass as environment variable

### ISSUE THREAD

**Issue by thomasmey** [GoogleContainerTools/jib#3147]
Hi,

would it be possible to make the jib classpath and mainClass, that is created as ENTRYPOINT (ENTRYPOINT ["java", jib.container.jvmFlags, "-cp", "/app/resources:/app/classes:/app/libs/*", jib.container.mainClass]) available as environment variables in the created container image?

I would like to run a custom shell script before I jump into java. the injected shell script would be a generic script for several different apps/container images.

On the end of the script I would like to jump into java with something like this:

java $CUSTOM_JAVA_OPTS_FROM_SCRIPT -cp $JIB_CLASSPATH $JIB_MAIN_CLASS

or is that already possible somehow?

**Comment by mpeddada1** [comment]
Hey @thomasmey, I think what you're looking for is similar to #894. As described there, this issue had proven to be tricky to support within Jib in the past and we decided that writing a [Jib Extension](https://github.com/GoogleContainerTools/jib-extensions) for it would be the best course of action. If you would like write a small extension to resolve this issue, we would be happy to receive your contribution!

**Comment by chanseokoh** [comment]
@thomasmey thanks again for your awesome contribution.

We just published the extensions. The coordinates are
- [com.google.cloud.tools:jib-ownership-extension-maven:0.1.0](https://repo1.maven.org/maven2/com/google/cloud/tools/jib-classpath-main-class-extension-maven/0.1.0/)
- [com.google.cloud.tools:jib-ownership-extension-gradle:0.1.0](https://repo1.maven.org/maven2/com/google/cloud/tools/jib-classpath-main-class-extension-gradle/0.1.0/)

Can you test this out?

**Comment by chanseokoh** [comment]
And although it's unrelated to the issue, we also released Jib build plugins 3.0, so I suggest upgrading.

**Comment by chanseokoh** [comment]
@thomasmey I just realized a problem with the extension. To identify the classpath and main class, the extension works by parsing the entrypoint already set in the image (i.e., assumes that you didn't set a custom entrypoint). That is, even though you have the environment variables, you cannot set a custom entrypoint based on them (sort of a chick-and-egg problem). What would you say?

So, in order to be usable, maybe the extension should really do keyword substitution as I hinted in https://github.com/GoogleContainerTools/jib-extensions/pull/82#pullrequestreview-617696866?

**Comment by thomasmey** [comment]
Hi,

My use case is to set a custom entrypoint to a shell script, in that script i want to use those variables.

And i didnt find any time yet to test, sorry.
Maybe i find some time next week.

But your description sounds if it cannot work, besides when the custom entry point is set after the plugin did already run, not sure when the plugin is called.

**Comment by chanseokoh** [comment]
@thomasmey as I said in https://github.com/GoogleContainerTools/jib/issues/3147#issuecomment-819065992, I think the extension you wrote has an issue to use in practice.

We just released Jib 3.1.0, which creates two new JVM argument files inside an image, where they hold the computed classpath and the main class respectively. It will be trivial to retrieve these values from a shell. See [the doc](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin/README.md#custom-container-entrypoint) for more details.
