### ISSUE TITLE
Adding mongoDb connection during build in github workflow

### ISSUE THREAD

**Issue by lisamittmann** [GoogleContainerTools/jib#3155]
Hey guys,
I'm an absolute noob and am trying to figure this out on my own but I just don't know enough about docker to figure this out. 

Problem:
I have a spring boot application with a static frontend and mongoDb connection. I set up a test instance of mongo Db atlas. Now I am trying to pass the mongoDb connection Uri to jib as a github workflow secret but I cannot for the life of me figure out how to pass on values for my application.yml.
Any suggesstions? Please I am desperate

**Comment by loosebazooka** [comment]
You need to describe your problem better for us to help you.

**Comment by lisamittmann** [comment]
Hey there,

okay trying to be more specific. 
I have a spring boot application with mongoDb connection. I am trying to set this mongoDb connection during the build process. In Docker you could simply add someting like `-Dspring.data.mongodb.uri=$MONGODB_URI` and the image would include the mongoDb connection you passed on in the variable. 
I tried the exact same with jib:build followed by `-Dspring.data.mongodb.uri=$MONGODB_URI` but the variable is not passed on to the image. 
You can find my pipeline here if this helps: 
https://github.com/lisamittmann/capstone-teddys-corona-diaries/blob/feature/addIacAndPipeline/.github/workflows/deployment.yml

**Comment by chanseokoh** [comment]
> I tried the exact same with jib:build followed by `-Dspring.data.mongodb.uri=$MONGODB_URI`

Probably this doesn't make sense. I think you are supposed to pass `-Dspring.data.mongodb.uri=...` to your app (precisely speaking, the JVM will run your app) that will run inside a container when the container starts? But with `mvn jib:build -D...`, you're passing it to Maven (precisely speaking, the JVM running the Maven build).

> In Docker you could simply add someting like `-Dspring.data.mongodb.uri=$MONGODB_URI`

How do you exactly add this? Can you show us your `Dockerfile` and the entire sequence of commands (or whatever tools you use) to build and run your image?

**Comment by lisamittmann** [comment]
Thx for the explanation, like I said I am absolutely noob and have absolutely no idea about Docker (it's my second day) 

Before I used heroku to create a Dockerfile which include the following: 
`ADD backend/target/github-bingo-master.jar app.jar

CMD ["sh", "-c", "java -Dserver.port=$PORT -Dspring.data.mongodb.uri=$MONGODB_URI -Dsecurity.jwt.secret=$JWT_SECRET -Dgithub.auth.client-id=$GITHUB_CLIENT_ID -Dgithub.auth.client-secret=$GITHUB_CLIENT_SECRET -jar /app.jar"]`

not quite sure if this heroku specific or not 
but how exactly would I pass the parameter to the JVM that will run the app? is there a possibility using jib to achieve something similar?

**Comment by chanseokoh** [comment]
There are different ways to achieve what you want. Most likely this may not be the best way, but if you just want to build the exact same image as you did with `Dockerfile`, just set the `CMD` (["program arguments"](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#container-object) is what Jib configuration names it) in the same way. This assumes you're using the same `FROM` image.

```xml
<configuration> <!-- jib-maven-plugin configuration -->
  <container>
    <args>sh,-c,java -Dserver.port=$PORT -Dspring.data.mongodb.uri=$MONGODB_URI -jar /app.jar</args>
  </container>
</configuration>
```
or alternatively
```xml
    <args>
      <arg>sh<arg>
      <arg>-c</arg>
      <arg>java -Dserver.port=$PORT -Dspring.data.mongodb.uri=$MONGODB_URI -jar /app.jar</arg>
    </args>
```

**Comment by lisamittmann** [comment]
Thx for the reply and clarification on what to use to achieve this outcome, this was very very helpful for me
Will most certainly read up more on Docker and hopefully not have to ask such basic questions again 🤞🏻
