### ISSUE TITLE
Remove all dependencies for JCenter as it is being discontinued 

### ISSUE THREAD

**Issue by cameron-p-m** [GoogleContainerTools/jib#3170]
**Description of the issue**:
https://github.com/GoogleContainerTools/jib/search?q=jcenter

JCenter is being removed, and all plugins and dependencies that have it listed as a dependency will fail fetching when they schedule their brown outs and eventually their blackouts 

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

```
What happens after the sunset of Bintray and JCenter?

On May 1, 2021, the sunset will impact all existing Bintray users. Bintray users will be blocked and will no longer be able to use the Bintray service. This includes existing software distribution, account administrative access, UI access, and the REST API.

After this date JCenter repository will still resolve artifacts, but end users should migrate to the canonical repo (e.g. Java packages should be retrieved from Maven Central). On Feb 1st, 2022 JCenter will only resolve artifacts for Artifactory clients.
```

Gradle migration guide: https://blog.gradle.org/jcenter-shutdown

**Expected behavior**:

Dependency of jcenter is removed to avoid brown outs and a complete shutdown is planned for February 2022

**Steps to reproduce**:

Read articles and attempt to build a project that has Jib Gradle as a dependency during brown-out periods.

**Comment by chanseokoh** [comment]
Interesting. Thanks for the heads-up!

**Comment by cameron-p-m** [comment]
Np. There was a brown out last week that caused our project to fail building :(

**Comment by chanseokoh** [comment]
It's interesting to note it will remain as a reliable read-only repo indefinitely.

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

> UPDATE 4/27/2021: We listened to the community and will keep JCenter as a read-only repository indefinitely. Our customers and the community can continue to rely on JCenter as a reliable mirror for Java packages.
