### ISSUE TITLE
Get image digest from jib cli

### ISSUE THREAD

**Issue by wouterhund** [GoogleContainerTools/jib#3183]
**Environment**:

- *Jib version:* 0.5.0
- *Build tool:* Jib CLI
- *OS:* Linux

**Description of the issue**:

Unable to get built image digest when using jib cli

**Expected behavior**:

The maven and gradle plugins generate a `jib-image.json` file which contains the digest of the built image. The jib cli should have an option to specify the path to write such a file to as well.

**Steps to reproduce**:

  1. Run `jib build --help`
  2. Look for a way to generate a `jib-image.json` or any other way to get built image digest

**Comment by mpeddada1** [comment]
@wouterhund thanks for creating this issue! Jib CLI 0.6.0 has been released with this feature. It introduces an option (`--image-metadata-out`) to let you specify a JSON file that will contain image metadata such as image id, digest and tags.
