### ISSUE TITLE
Environment entries can not be null or empty

### ISSUE THREAD

**Issue by Marty** [GoogleContainerTools/jib#3195]
**Environment**:

- *Jib version:* 2.8.0
- *Build tool:* Maven 3.6.1
- *OS:*  Windows 10

**Description of the issue**:
Setting `environment` entries to an empty string results in the following message:
```
Execution default-cli of goal com.google.cloud.tools:jib-maven-plugin:2.8.0:dockerBuild failed: environment map contains null values 
```` 

**Expected behavior**:
The ENV variables should be set inside the image to an empty string.

**Steps to reproduce**:
Add an `environment` element with an empty value.
```
<value></value>
````

**Log output**: 
```
Execution default-cli of goal com.google.cloud.tools:jib-maven-plugin:2.8.0:dockerBuild failed: environment map contains null values 
```` 

**Additional Information**: 
This is needed since my application has a default value for that parameter that I have to override with an empty string.
I can workaround this by using
```
<CATALINA_OPTS>-Dvalue=</CATALINA_OPTS>
```
that way I can set it to an empty string.

**Comment by chanseokoh** [comment]
Hi @Marty,

I understand the pain, but fortunately, this seems like a limitation of Maven. There just does not seem a way to pass an empty string or even non-empty whitespace.

- [SO answer](https://stackoverflow.com/a/7893288/1701388)
- [mailing list message from 2007](http://mail-archives.apache.org/mod_mbox/maven-users/200708.mbox/%3C5a2cf1f60708090246l216f156esf46cc1e968b37ccd@mail.gmail.com%3E)

I cannot immediately think of an elegant way to support this. Maybe introduce a special keyword like `JIB_EMPTY_STRING`?

**Comment by emmileaf** [comment]
Closing as part of cleanup since known issue is in Maven. Please re-open if needed.
