### ISSUE TITLE
Changing base jetty image for WAR: running image fails

### ISSUE THREAD

**Issue by aanno** [GoogleContainerTools/jib#3204]
**Environment**:

- *Jib version:* 3.0.0
- *Build tool:*  mvn 3.6.3
- *OS:* Linux (Fedora 33)

**Description of the issue**:
Changing base jetty image for WAR: running image fails

**Expected behavior**:
Changing base jetty image for WAR: running image should run WAR on jetty

**Steps to reproduce**:

**`jib-maven-plugin` Configuration**: 
```xml
			<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>3.0.0</version>
				<configuration>
					<from>
						<image>jetty:11.0.2-jre11</image>
					</from>
					<to>
						<image>matching-server-war-jetty</image>
					</to>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>build</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```

When using the maven configuration above:
```bash
$ podman run --rm -p 8080:8080 matching-server-war-jetty:latest 2>&1 | tee log
/docker-entrypoint.sh: 98: /docker-entrypoint.sh: cannot create /var/lib/jetty/jetty.start: Permission denied
```
When using the maven configuration above _without the **from** part_, everything works as expected.

**Comment by chanseokoh** [comment]
Hi @aanno,

I know what's happening. The way we make the default `jetty` image (when you are not specifying `<from>`) works is to set the entrypoint to `java -jar /usr/local/jetty/start.jar`. 

(from #3124)

> For WAR projects, we no longer inherits the entrypoint from the base image. The new default entrypoint is explicitly set to `java -jar /usr/local/jetty/start.jar`. The idea is from https://github.com/GoogleContainerTools/jib/issues/1270#issuecomment-791525157.

So I expect you should be able to resolve the issue by specifying
```xml
<configuration>
  ...
  <container>
    <entrypoint>java,-jar,/usr/local/jetty/start.jar</entrypoint>
  </container>
</configuration>
```

---

Maybe we can help this situation by setting this entrypoint automatically if the base image is from the official `jetty` repo and no entrypoint is given? Or, maybe we can just document how to configure this [here](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#war-projects)?

**Comment by chanseokoh** [comment]
Hmm, I tried setting the entrypoint with `jetty:11.0.2-jre11` but ran into a problem. The jetty server does run, but it fails to start up the WAR context with

```
2021-04-12 15:34:38.970:INFO :oejs.Server:main: jetty-11.0.2; built: 2021-03-26T06:42:38.152Z; git: 14ed9a526425785884b34f59e1153fede0ae3552; jvm 11.0.10+9
2021-04-12 15:34:39.040:INFO :oejdp.ScanningAppProvider:main: Deployment monitor [file:///var/lib/jetty/webapps/]
2021-04-12 15:34:39.768:INFO :oejss.DefaultSessionIdManager:main: Session workerName=node0
2021-04-12 15:34:39.816:WARN :oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@b62d79{ROOT,/,file:///var/lib/jetty/webapps/ROOT/,UNAVAILABLE}{/var/lib/jetty/webapps/ROOT}
java.lang.NoClassDefFoundError: javax/servlet/http/HttpServlet
        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
        at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
```

**Comment by chanseokoh** [comment]
Never mind. The error on my project was because my source was based on old Servlet API. I noticed that `jetty:latest` runs Jetty 9.4. OTOH, Jetty 11 (`jetty:11.0.2-jre11`) seems to require Servlet 5.0. When converted my source to Servlet 5.0, it works. So, yeah, set `<entrypoint>java,-jar,/usr/local/jetty/start.jar</entrypoint>`, and you should be good.

**Comment by chanseokoh** [comment]
So #3205 documented an [example](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#war-projects) to use `jetty` as a base image, in addition to the existing example to use `tomcat`.

I think this issue can be resolved with the documentation. Technically Jib could do more magic to automatically set multiple configurations (`appRoot`, `entrypoint`, etc.) for some well-known base images, but I don't think we want to enter into that territory and open Pandora's box. If the user specifies a custom Servlet engine, then our stance is that basically it's on their own to figure out how to properly use the image. However, we can help documentation and examples.

**Comment by aanno** [comment]
Dear @chanseokoh, thank you very much for prompt support!
