### ISSUE TITLE
Spring environment variable is not recognized

### ISSUE THREAD

**Issue by chtpl** [GoogleContainerTools/jib#3212]
**Environment**:
Local 
- *Jib version:* 3.0.0
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.10, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-70-generic", arch: "amd64", family: "unix"

**Description of the issue**:
When using the following container config:

```xml
<container>
    <environment>
        <PROFILE>dev</PROFILE>
    </environment>
    <jvmFlags>
        <jvmFlag>-Dspring.profiles.active=$PROFILE</jvmFlag>
    </jvmFlags>
</container>
```

and running the image with 
`docker run -d localhost:5000/test:dev`

The logs show:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.2.0.RELEASE)

2021-04-14 16:13:06.969  INFO 1 --- [           main] com.mycompany.MyApp     : The following profiles are active: $PROFILE

```

**Expected behavior**:
Spring starts with profile `dev`

**Steps to reproduce**:
See above 

**`jib-maven-plugin` Configuration**: 
See above

**Comment by mpeddada1** [comment]
Hi @chtp, what happens if you just use static value like this `<jvmFlag>-Dspring.profiles.active=dev<jvmFlag>`?

**Comment by chtpl** [comment]
I'll setup a minimal example when I find the time. Probably not before mid may

**Comment by chanseokoh** [comment]
There's no interpreter evaluation the string literal `$PROFILE` and substitute the string `dev` for it, so you're initial approach doesn't work. Checking [this SO question](https://stackoverflow.com/questions/59357410/jib-how-to-use-environmental-variables-from-base-image/59361658#59361658) may give you some more insights.

**Comment by chtpl** [comment]
Thanks. I used a custom entrypoint now:

```
<container>
    <entrypoint>
        <arg>/bin/sh</arg>
        <arg>-c</arg>
        <arg>echo "PROFILE: $PROFILE"; exec java \
            -Dspring.profiles.active=$PROFILE \
            $JAVA_OPTS -cp /app/resources:/app/classes:/app/libs/* \
            com.company.MyApplicationMainClass
        </arg>
    </entrypoint>
</container>
```
