### ISSUE TITLE
mvn clean compile jib:build not work for war project.

### ISSUE THREAD

**Issue by eisig** [GoogleContainerTools/jib#3214]
**Environment**:

- *Jib version:*  3.0.0
- *Build tool:* maven 3.6.3,Java version: 1.8.0_282,
- *OS:*  ubuntu20.04

**Description of the issue**:
`mvn clean compile jib:build ` not work for war project.
have to package the war project. `mvn clean package jib:build ` 
The documents and the log output do not mention that.

**Expected behavior**:
work as jar project.

**Steps to reproduce**:

  1.  create simple springweb  app in https://start.spring.io/; set the package to war
  2. run `mvn clean compile jib:build ` 

**Log output**: 
```
Obtaining project build output files failed; make sure you have compiled your project before trying to build the image. (Did you accidentally run "mvn clean jib:build" instead of "mvn clean compile jib:build"?)
```

**Comment by chanseokoh** [comment]
Yeah, the message is misleading. (It used to be `mvn clean package jib:build`, but I guess this is a regression.)

BTW, I highly recommend `<packaging>jar` instead of `war` if feasible.

**Comment by Sap1996** [comment]
Hi. I am new to this space, and  would like to pick up this issue.

**Comment by Sap1996** [comment]
Thank you @chanseokoh . I will take a look into it :)

**Comment by JacekDuszenko** [comment]
@chanseokoh @saptaswapal I noticed this task hasn't been worked on for some time now and I'd like to contribute. May I take this over?

**Comment by JacekDuszenko** [comment]
I assumed I can start working on the task and submitted a PR. @chanseokoh, feel free to  review at your free time! #3306
