### ISSUE TITLE
Official Support for Sbt as Part of Approved Jib Plugin

### ISSUE THREAD

**Issue by irvifa** [GoogleContainerTools/jib#3236]
**Kind**:

Feature request

**Description of the issue**:

Since `jib-core` is available and can be used to create a plugin for another JVM builder,
is it possible to officially support `sbt` as official plugin. This is related to issue mentioned on [1].

**Additional Information**: 

[1] [Official Support for Sbt Jib as Part of Approved Builder](https://github.com/GoogleContainerTools/skaffold/issues/5830)

**Comment by chanseokoh** [comment]
Thanks for the feedback, but unfortunately, we have no plan to support sbt. It is unlikely that we will ever work on it.

But at least we know there exists [sbt-jib](https://github.com/schmitch/sbt-jib) created by the community, so maybe check it out.

**Comment by irvifa** [comment]
I see, as for skaffold support for jib other than the one for gradle and maven will that ever be considered?

**Comment by chanseokoh** [comment]
I don't think so, sorry. You may already be aware of this, but at least Skaffold supports a ["custom builder"](https://skaffold.dev/docs/tutorials/custom-builder/). So, I guess it can be made to work with Skaffold using the sbt-jib plugin.

**Comment by irvifa** [comment]
Got it, thanks for explaining it to me, I also got a response about the suggestion on using a custom builder on the Skaffold repository as well. I'll close this issue then. Thanks!
