### ISSUE TITLE
GOOGLE_APPLICATION_CREDENTIALS for Google's Artifact Registry (*-docker.pkg.dev)

### ISSUE THREAD

**Issue by briananderson1222** [GoogleContainerTools/jib#3239]
**Environment**:

- *Jib version:*  3.0.0
- *Build tool:* Maven (3.8.3)
- *OS:* OSX Big Sur

**Description of the issue**:
Images with path gcr.io are correctly able to use GOOGLE_APPLICATION_CREDENTIALS to resolve the ability to upload. `*-docker.pkg.dev` Google Artifact Registry cannot leverage this same technique. 

**Expected behavior**:
I believe Google Artifact Registry should use `*-docker.pkg.dev` to give the same first class treatment of Application Default Credentials

Might just need to add this path here? --
https://github.com/GoogleContainerTools/jib/blob/0ed7dca36864b6b19ff61629fc578018041fa15f/jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java#L243

**Steps to reproduce**:
  1. ADC set via GOOGLE_APPLICATION_CREDENTIALS
  2. Try `gcr.io` image path w/ Success
  3. Try `-docker.pkg.dev` w/ no attempt to resolve via ADC

**`jib-maven-plugin` Configuration**: 
```xml
<configuration>
    <to>
        <!--  <image>gcr.io/my-project/my-image:latest</image>  <!-- SUCCESS -->
        <image>us-central1-docker.pkg.dev/my-project/container-registry/my-image:latest</image>
        <tags>${git.commit.id}</tags>
    </to>
</configuration>
```

**Log output**:  403 Forbidden

**Additional Information**: https://cloud.google.com/artifact-registry/docs/docker/pushing-and-pulling
- GAR by default uses the same credentials resolver as gcr.i

**Comment by chanseokoh** [comment]
Thanks for the feedback! This will be supported in the next release.

**Comment by chanseokoh** [comment]
@briananderson1222 Jib 3.1.0 is released with this fix. Let us know if you still experience an issue.
