### ISSUE TITLE
Pushing Images to same tag with different architectures

### ISSUE THREAD

**Issue by lukeSky3434** [GoogleContainerTools/jib#3269]
Hello,

is it possible to push images to the same tag with different architectures? You have defined in the _from image_ confguration, to define the architecture:

          <from>
            <image>....</image>
            <platforms>
              <platform>
                <architecture>arm/v7</architecture>
                <os>linux</os>
              </platform>
            </platforms>
          </from>

Thats fine, but what if I pull 2 different images (from a different location), and I want to push the first image to a tag, e.g. _1.0.0-slim_ with architecture _amd64_, and the second to the same tag _1.0.0-slim_ with a other architecture _arm/v7_.

Are there any possibilities with the jib maven plugin?

**Comment by meltsufin** [comment]
@lukeSky3434 Can you just define the plugin in two different Maven profiles with different configurations?

**Comment by chanseokoh** [comment]
This is already doable. What you are asking for is to create and push a manifest _list_. You just need to list all the platforms you want., e.g.,

```xml
        <platforms>
          <platform>
            <architecture>amd64</architecture>
            <os>linux</os>
          </platform>
          <platform>
            <architecture>arm/v7</architecture>
            <os>linux</os>
          </platform>
        </platforms>
```
In this scenario, Jib will build two "images" (manifests, to be correct, where are a small JSON file), each based on one of the two amd and arm base images. Then it will create a manifest _list_ (another small JSON file) and push it. The tag `1.0.0-slim` will then point to this manifest list.

See this [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image) for more information.

**Comment by lukeSky3434** [comment]
> This is already doable. What you are asking for is to create and push a manifest _list_. You just need to list all the platforms you want., e.g.,
> 
> ```
>         <platforms>
>           <platform>
>             <architecture>amd64</architecture>
>             <os>linux</os>
>           </platform>
>           <platform>
>             <architecture>arm/v7</architecture>
>             <os>linux</os>
>           </platform>
>         </platforms>
> ```
> 
> In this scenario, Jib will build two "images" (manifests, to be correct, which are a small JSON file), each based on one of the two amd and arm base images. Then it will create a manifest _list_ (another small JSON file) and push it. The tag `1.0.0-slim` will then point to this manifest list.
> 
> See this [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image) for more information.

Thats not what I mean, I know how to create and push a manifest list, and how to define such a thing, but  the question was a different one...

I have to use 2 images from a different location, because the one from distroless do not provide a image for arm/v7 - only for _amd64_, and the other for _arm/v7_ is from a different location, that means, i have two base images...

- <image>registry://gcr.io/distroless/java@sha256:e99eb6cf88ca2df69e99bf853d65f125066730e3e9f7a233bd1b7e3523c144

- <image>arm32v7/openjdk:11-slim</image>

I want to build my project and push each manifest to the same tag _1.0.0-slim_, with a manifest list, one for _amd64_ and one for _arm/v7_ but from a different image location.... I tried it with 2 different maven profiles, but the one which executed last will overwrite the old one, and so there is only one platform available...

**Comment by chanseokoh** [comment]
This is not supported. In fact, supporting different registries (either for pull or push) are trickier than you think (authentication becomes a lot complicated). The close workarounds I can think of:

1. Individual build and push arm and amd images using Jib. Then create a manifest list yourself with the tag `1.0.0-slim` in that registry.

   I don't know what tools are readily available, but I know `docker manifest create` is there. However, I believe this requires having images in your local daemon first. A quick search gives me another tool [`manifest-tool`](https://github.com/estesp/manifest-tool), which emphasizes creating a manifest list was the main motivation:
   > This tool was mainly created for the purpose of viewing, creating, and pushing the new **manifests list** object type in the Docker registry
   Briefly reading their doc, I think it can create a manifest list online with a small YAML file. 

2. Set up a registry for the base images that has a manifest list point to the arm and amd JDK images, and have set it in `<from><image>`.
