### ISSUE TITLE
Entrypoint example with run-java-sh

### ISSUE THREAD

**Issue by OneCricketeer** [GoogleContainerTools/jib#3271]
**Environment**: N/A

- *Jib version:* latest
- *Build tool:* Maven
- *OS:* Mac

**Description of the issue**:

[`run-java-sh`](https://github.com/fabric8io-images/run-java-sh) describes itself as a "_universal startup script for Java applications, especially crafted for being run from within containers_". 

I understand Jib can offer `<entrypoint>` configs, yet would like to see an example of how this can be configured when there are external dependencies that include such scripts.

**Expected behavior**:

Example or documentation how to include external dependencies that include entrypoint scripts. 

**Additional details**:

Mostly interested in the dynamic memory calculation functions

No, haven't tried it 🙂 

Not sure if works for your packaging layout, or requires a JAR - [ref. bash script](https://github.com/fabric8io-images/run-java-sh/blob/master/fish-pepper/run-java-sh/fp-files/run-java.sh#L614-L616)

**Comment by elefeint** [comment]
@OneCricketeer Jib itself generates a runnable Java archive. Out of curiosity, how are you going to use `run-java-sh` -- do you need to spawn multiple Java processes or are you hoping to attach to the one Jib-generated container starts?

If you need to pass arguments to Jib container's JVM startup directly, you can do it with `-Djib.container.jvmFlags`. For example, to do profiling, you could provide `-Djib.container.jvmFlags="-agentpath:/opt/cprof/profiler_java_agent.so=-cprof_service=servicename`.

**Comment by OneCricketeer** [comment]
I'm aware of the jvmFlags build argument, but that doesn't answer the question. 

> Jib itself generates a runnable Java archive

Only if `containerizingMode = 'packaged'`, right? Otherwise, only archives are the layer for 
 /app/lib? 

[This FAQ section more closely matches what I am asking](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-need-to-add-files-generated-during-the-build-process-to-a-custom-directory-on-the-image), however I'm not sure how to address a resource that's pulled from a dependency rather than existing in my own project

> do you need to spawn multiple Java processes

I do not, and I don't think that's the intended purpose of the script

**Comment by elefeint** [comment]
There is a good example of setting a custom entrypoint in [this StackOverflow answer](https://stackoverflow.com/a/59361658/10441462) by @chanseokoh -- essentially, your first argument will be to invoke the shell, which is available in Jib versions after 3.0.

**Comment by OneCricketeer** [comment]
Thanks. Yes, I'm aware of the `<entrypoint>` config, but that answer specifies placing the script under `src/main/jib`


Still unclear on _how to address a resource that's pulled from a dependency_. Would that require `maven-resources-plugin`, for example?

**Comment by elefeint** [comment]
Oh, so your dependency script is not in the final image?

**Comment by OneCricketeer** [comment]
If I just add the dependency, it's pulled to the build path, sure, however I'm not connecting how that can be included in the resulting image... 

Following the [example for the docker-maven-plugin](https://github.com/fabric8io-images/run-java-sh#maven-builds), how does one duplicate `ADD target/docker-extra/run-java/run-java.sh` layer in Jib?

**Comment by mpeddada1** [comment]
Hey @OneCricketeer, using the `extraDirectories` feature as described in the [example mentioned above](https://github.com/GoogleContainerTools/jib/issues/3271#issuecomment-853103813) will add the script to the container image, therefore making it accessible to `<entrypoint>`. Note that `extraDirectories` is a way of doing `ADD` in Jib. You can also find more info about it in the [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#can-i-add-a-custom-directory-to-the-image)

**Comment by OneCricketeer** [comment]
What filesystem locations can `extraDirectories` access? All the examples I see only reference paths under `src/main/jib`, which externally downloaded files _are not_, which is my question.

**Comment by chanseokoh** [comment]
Updated a missing link in the comment above.

**Comment by OneCricketeer** [comment]
> just need to manually download the files

Right, which, based on their example of including the dependency inside of the docker-maven-plugin definition, it should be doing that, and placing the files into `target/docker-extra/run-java/run-java.sh`, apparently, but what's unclear to me is how `docker-extra` path is determined since I cannot find a reference to that anywhere other than the README

> not sure how that will be better than downloading files from the repo

Excluding repeated requests per-build, it'll reduce/eliminate change drift, but, yes, then `wget` download plugin example is the ultimate workaround from the raw github resource

**Comment by nikita2206** [comment]
@OneCricketeer I'm looking into this with my project as well and the way I'm doing it is by baking the run-java.sh script into the docker image and then using that docker image as a base in Jib (via `<from><image>quay.io/org/repo:latest</image></from>`). That's possibly the simplest way to do that without redownloading the script on every build.

**Comment by OneCricketeer** [comment]
>  realized that I'm probably better off without run-java.sh given that most of its benefits are gone with Java 10+

If you're referring to the cgroup memory configurations inside the container, should be similar with Java8u192+ 

e.g.`JAVA_TOOL_OPTIONS='-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2'`

In my case, I'd simply like to pull an entrypoint script from an external dependency. I mainly only asked about `run-java-sh` project because it was a seemingly relatable public example

**Comment by OneCricketeer** [comment]
btw, the script is available in Maven Central, so wouldn't necessary need to download from Github

<https://repo1.maven.org/maven2/io/fabric8/run-java-sh/1.3.8/run-java-sh-1.3.8-sh.sh>

**Comment by chanseokoh** [comment]
Thanks all for the updates and insights. As of now, the only approaches I can think of as viable options are those in https://github.com/GoogleContainerTools/jib/issues/3271#issuecomment-854066423 or baking the file into a base image. This `run-java-sh` dependency behavior seems like fairly special, and we have no plan to natively support this scenario. Hope this issue thread helped.

**Comment by OneCricketeer** [comment]
> we have no plan to natively support this scenario

AFAICT, using an entrypoint script is a regularly asked scenario ( #3147 for example would be useful for exposing the class name to the script ) , not sure if it matters if it is part of the project, the base image, or external. 

My question was asking how that can be done from a dependency, which I know would eventually get pulled into `target/`, so should I be able to reference `<entrypoint>${project.build.directory}/foo/bar/entrypoint.sh</entrypoint>`, assuming _something_ has already placed a file there (for example, the maven-resources-plugin)?

**Comment by chanseokoh** [comment]
> which I know would eventually get pulled into `target/`

If this is the case and as long as the file exists at `target/foo/bar/entrypoint.sh` by the time Jib runs (by whatever means, by `maven-resources-plugin`, whether extracted from a dependency somehow, etc.), you should be able to copy that file into an image (e.g., at `/script/entrypoint.sh`) using `<extraDirectories>`. Just make sure the file gets placed before the Jib plugin runs. And note, then, the entrypoint you should set should be `<entrypiont>/script/entrypoint.sh` (i.e., the path inside the image). Basically, I don't see anything particularly interesting about this scenario; Jib can copy what it can see into an image, and you set the image entrypoint to whatever suits you.
