### ISSUE TITLE
Run commands from pom.xml

### ISSUE THREAD

**Issue by mohan33** [GoogleContainerTools/jib#3278]
Hello Team, 
Using jib can we run commands like we do using DOCKER file. 
**Eg**: RUN apk add --upgrade python3-dev 

@mbruggmann @jponge @suztomo @sullis @glaforge

**Comment by chanseokoh** [comment]
Please see https://github.com/GoogleContainerTools/jib/issues/2383#issuecomment-617251882

However, often there are other approaches to achieve your final goal. For example, I see you want to install some OS package (Python dev runtime in this case), so you could use the base image that already has the required packages (e.g., the official Python Docker Hub image), or prepare your own custom base image in advance, or copy necessary files with Jib using the `<extraDirectories>` feature during builds.

**Comment by chanseokoh** [comment]
Fee free to update if you have more questions.
