### ISSUE TITLE
Can jib-core  be used to creat multi manifest images?

### ISSUE THREAD

**Issue by alpar-t** [GoogleContainerTools/jib#3279]
We are using jib-core to implement our own, opinionated Gradle plugin, that extends beyond the JDK ecosystem.  
We would like to  build two slight different platform specific images and combine them in a multi manifest image. Each image might have a different statically linked executable added for the specific platform, but  they will start out from different platform specific base images.  

e.g.  we build and push `base-linux_aarch64` and `base-linux_x86_64` as distinct docker images (coming from different CI workers) and would like to add a statically linked executable on top which is cross compiled,  e.g. `tool-$os_$architecture` such that we eventually push `final:latest` that has support for both aarch64 and x86_64 such that it will work and will have the right variant of `tool` on both platforms. 

I couldn't find anything in the `api` package, but the tests helped me trace down fragments like `BuildManifestListOrSingleManifestStep`, `V22ManifestTemplate` and `RegistryClient`  and I see that the Gradle plugin has support for this, so I'm thinking it has to be possible, just not sure how to consume it.  I haven't yet tried to trace what the plugin does to implement this. 

Thanks for the help and this great tool!

**Comment by chanseokoh** [comment]
Hey @alpar-t! The answer is yes. For example, call `JibContainerBuilder.setPlatforms()` (or `addPlatforms()`) with multiple platforms. If you are building based on some existing base images, the base image reference should be a manifest list that contains all the platforms you specified. Jib will build and push multiple platform-specific images to the registry (they will not have tags), followed by the final manifest list that point to the platform-specific images.

```java
  /**
   * Sets a desired platform (properties including OS and architecture) list. If the base image
   * reference is a Docker manifest list or an OCI image index, an image builder may select the base
   * images matching the given platforms. If the base image reference is an image manifest, an image
   * builder may ignore the given platforms and use the platform of the base image or may decide to
   * raise on error.
   *
   * <p>Note that a new container builder starts with "amd64/linux" as the default platform.
   *
   * @param platforms list of platforms to select base images in case of a manifest list
   * @return this
   */
  public JibContainerBuilder setPlatforms(Set<Platform> platforms) {
```

**Comment by chanseokoh** [comment]
Also note that you should be able to create and push a manifest list (which is just a small JSON) for existing images (`base-linux_aarch64` and `base-linux_x86_64` in your case) using external tools. For example, see https://github.com/GoogleContainerTools/jib/issues/3269#issuecomment-849928759

**Comment by alpar-t** [comment]
Thanks for the help! 
It seems to me that I would still not be able to customize the images Jib generates based on the platform. 
e.g.  add `tool-arm64` or  `tool-amd64`  to the images generated by Jib (that are pushed without a tag). 
My only option would be to generate separate images with jib and use the manifest tool at the very end.

**Comment by chanseokoh** [comment]
Ah, so you're saying you want to also add individual tags to all of the platform-specific image (in addition to the final manifest list)? That's not supported.
