### ISSUE TITLE
Quickstart doc issues

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#329]
https://github.com/GoogleContainerTools/jib/tree/v0.9.0-update-readme/jib-maven-plugin#quickstart

1. `docker build -t myregistry/myapp my/docker/context/` --> `docker build -t some-name myregistry/...`
1. "Minikube Docker daemon" heading should be at the same level as "Build to Docker daemon" is at. It's font is smaller.

**Comment by coollog** [comment]
1. I'm not sure what the suggestion means. The command example tags your image with `myregistry/myapp` and sends the docker context at `my/docker/context` to the Docker daemon.

2. The "Minikube Docker daemon" example is meant to be a subset of "Build to Docker daemon". Do you think it's confusing to have this in this quickstart section?

**Comment by chanseokoh** [comment]
Oh, I failed to see the first argument was a tag. I wrongly thought you were providing the context path as a single argument.

If you believe the Minikube instructions should be a subset, you can close this issue.

**Comment by coollog** [comment]
Ah okay, I will make that clearer and not use a slash in the image name. Thanks!
