### ISSUE TITLE
Refactor User-Agent injection.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#33]
`User-Agent` is currently passed in to the `RegistryClient` in `BuildImageMojo` with `RegistryClient.setUserAgentSuffix(USER_AGENT_SUFFIX);`.

**Comment by TadCordle** [comment]
For this should we just add a configuration option to `BuildConfiguration` and pass that into the `RegistryClient.Factory` in the appropriate steps?

**Comment by coollog** [comment]
I think we can hold off on this till we have the library API design set, since that will be the main user-facing API we expose.
