### ISSUE TITLE
Main class inference fails on files with external dependencies

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#331]
Tried running jib on https://github.com/spring-guides/gs-spring-boot/blob/master/complete with no explicit main class parameter. Fails with "Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin".

This is caused by a `NoClassDefFoundError` when the class finder is processing `Application.class`. It looks like when it hits the `commandLineRunner` method, it calls `findClass` on `org.springframework.context.ApplicationContext`, but fails to find the corresponding .class file since it's an external dependency.

**Comment by coollog** [comment]
```[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.1.8-SNAPSHOT:buildDocker (default-cli) on project dropwizrd-jib-demo: Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin -> [Help 1]```

Code sample here: https://github.com/patflynn/dropwizard-jib-sample
