### ISSUE TITLE
Disable generating of the latest tag

### ISSUE THREAD

**Issue by igor-dmitriev** [GoogleContainerTools/jib#3346]
**Environment**:
- *Jib version:*
- 3.1.2 
- *Build tool:* 
- Maven
- *OS:* 
any

**Description of the issue**:
I am using Immutable AWS ECR repository and when I run `mvn clean install jib:build`
it fails with an error that the latest tag already exists.

**Expected behavior**:
The latest tag should not be created and pushed

**Steps to reproduce**:

  1. Create an AWS ECR repository
  2. Enable Immutability
  3. run `mvn clean install jib:build`

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.1.2</version>
                <configuration>
                    <to>
                        <image>${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/ecs-play</image>
                        <tags>
                            <tag>${env.IMAGE_TAG}</tag>
                        </tags>
                    </to>
                </configuration>
            </plugin>
```

**Log output**: 

**Additional Information**:

**Comment by zhumin8** [comment]
would use of `-Djib.to.image` property to setup a unique tag name do what you intend?

**Comment by chanseokoh** [comment]
@igor-dmitriev set the tags in `<to><image>`.
```xml
<image>${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/ecs-play:${env.IMAGE_TAG}</image>
```
When you don't specify a tag in an image reference, `:latest` is implied, just like `docker push example.com/image` will push an image with the `:latest` tag. `<to><tags>` actually mean "additional" tags. (We regret the bad naming, sorry.)

Duplicates: #2237 #3330 (and many more)
