### ISSUE TITLE
Consider separating jib into class library and plugins

### ISSUE THREAD

**Issue by elharo** [GoogleContainerTools/jib#337]
This project could be divided into an independent library for building images and pushing them to repos; and the Maven and gradle specific parts. 

Among other uses, this would allow us to adopt jib for building/pushing Docker images from Eclipse and IntelliJ.

**Comment by coollog** [comment]
A quick survey for everyone who thumbs upped this issue - *please comment below with your intended use case*. This will help us think about how we could better structure the features of the library. Thanks!

**Comment by schmitch** [comment]
For a Sbt Plugin: https://github.com/schmitch/sbt-jib

**Comment by rmannibucau** [comment]
To be able to manipulate layers of multiple images and merge them into a single one with some customizations. Can likely end up as a maven/gradle plugin but goal is to aggregate images before a cloud vendor specific deployment.

**Comment by coollog** [comment]
Hi everyone, we have released an initial alpha version of the Jib Core library for building containers in Java. Please see the draft documentation at https://github.com/GoogleContainerTools/jib/tree/master/jib-core and let us know if there's any issues or questions!
