### ISSUE TITLE
Move BuildFiles from jib-cli to jib-core

### ISSUE THREAD

**Issue by szhem** [GoogleContainerTools/jib#3372]
Currently jib-core provides a functionality to create a `JibContainerBuilder` using expression like the following
```java
Jib.from(...)
```
However jib-cli allows a user to create a `JibContainerBuilder` by means of a configuration file using a declarative rather than an imperative style.
```java
BuildFiles. toJibContainerBuilder(...)
```
It will be very convenient 
- to be able to use jib's build files from custom build scripts of non-java projects, but built with java build tools, e.g. gradle
- to have everything that creates `JibContainerBuilder` in a single place

**Comment by chanseokoh** [comment]
Thanks for the feedback. I think I should explain the current situation first.

`BuildFiles` is a higher-level abstraction built on top of jib-core, only relevant and specific to jib-cli. That is, at the moment, jib-core doesn't know or have to know anything about `BuildFiles`. There is a lower-level construct in jib-core called [`ContainerBuildPlan`](https://github.com/GoogleContainerTools/jib/blob/master/jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/ContainerBuildPlan.java) that we introduced at some point, which we intended to migrate the jib-core codebase to be able to build upon it, but right now, even that is working only partially and internally for the sake of making things only work. The migration is not fully sorted out, and as you can imagine, this kind of work has not been our priority. Even before we will be able to look into `BuildFiles` (which may be competing with `ContainerBuildPlan` and will add more complexity if it blindly pull it into jib-core), we need to sort out the `ContainerBuildPlan` integration and its relationship with `BuildFiles`. `BuildFiles` was exclusively and independently developed in the context of jib-cli, so for now, it doesn't make sense for us to put it into jib-core without giving more thoughts. Initially we envisioned that we will convert `BuildFiles` into `ContainerBuildPlan`, but for a quick implementation, we changed our direction to directly construct a `JibContainerBuilder`.

I agree `BuildFiles` can be really useful for jib-core, and if the situation above weren't a concern, I think it could be totally acceptable to move it to jib-core. However, unfortunately, given the situation and also our limited resources, it is unlikely that we will work on this anyway. :(

**Comment by szhem** [comment]
@chanseokoh Thanks a lot for the answer. In that case could you please consider publishing `jib-cli.jar` into maven central repository then?

**Comment by chanseokoh** [comment]
I'll close this issue for now, but anyone is welcome to leave feedback if they really want to see this happen.

For publishing jib-cli.jar to Maven Central, please discuss it in #3373.
