### ISSUE TITLE
Publish jib-cli.jar to maven central

### ISSUE THREAD

**Issue by szhem** [GoogleContainerTools/jib#3373]
It will be very convenient having jib-cli.jar to be published into maven central to be able to download it with maven dependency resolution tools.

**Comment by chanseokoh** [comment]
Currently, we have no plan to publish jib-cli to Maven Central but will this issue open.

**Comment by mpeddada1** [comment]
Thank you for the idea! However, we're focusing on [bug fixes](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md) and platform evolution changes and while it's a good idea, it's not something we can prioritize at this time (unfortunately). Closing as not planned.
