### ISSUE TITLE
Every layer is rebuild even if there is no source code change

### ISSUE THREAD

**Issue by Alexander-Betz** [GoogleContainerTools/jib#3375]
I'm using jib-maven-plugin with version 3.1.2 and have the following added to my pom file:
```
<plugin>
 <groupId>com.google.cloud.tools</groupId>
 <artifactId>jib-maven-plugin</artifactId>
 <version>3.1.2</version>
</plugin>
```
and I use the following command to build and push an image:
```
mvn compile jib:build -Dimage=eu.gcr.io/project_id/image_name -Djib.to.tags=latest,another_tag -Djib.from.image=eu.gcr.io/project_id/image_name
```
in my Github Actions CI/CD pipeline.

But even if I don't have any source code changes all layers are rebuild and the image is pushed:
```
Getting manifest for base image eu.gcr.io/project_id/image_name...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO] Building jvm arg files layer...
```
To my understanding no layer should be rebuild since there was no change and if I only change a dependency then only the dependency layer should be rebuild etc.
I also tried adding a specific image digest for the base image but that didn't help.

Is something wrong with the above command or is it not possible to pull the latest image from Google Container Registry, use it as base image and then have only the layers be rebuild where a change was?

**Comment by chanseokoh** [comment]
@Alexander-Betz if what you said is right, then it will be a critical regression. But note that the `INFO` messages (`Building ... layer`) are general progression messages always printed. It doesn't mean that layer tarball are re-assembled.

Do you have concrete evidence that the same layers are rebuilt or repushed?

**Comment by Alexander-Betz** [comment]
@chanseokoh Okay, good to know. I thought if the messages say "Building ... layer" then it's rebuild from scratch. Then maybe that's not the case for me.

But regarding image push: yes, even if there is no change (I just do a dummy commit) the image is pushed to Google Container Registry and I see the new image there.

**Comment by chanseokoh** [comment]
Can't reproduce this.
```
$ cd /tmp
$ git clone https://github.com/GoogleContainerTools/jib.git
...
$ cd jib/examples/helloworld
$ mvn compile
$ mvn -Djib.to.image=gcr.io/chanseok-playground-new/foo jib:build
...
[INFO] Built and pushed image as gcr.io/chanseok-playground-new/foo                                                                                    
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.378 s
[INFO] Finished at: 2021-08-03T16:43:30-04:00
[INFO] ------------------------------------------------------------------------
```
I can verify that the image is uploaded to GCR 4 minutes ago.
![image](https://user-images.githubusercontent.com/10523105/128084490-192af58d-7146-4037-ac3c-0ac84eb6d347.png)

Now I run Jib a couple more times. Note that it is super fast for these operations. (What is uploaded is only a manifest, which is a tiny JSON file.)
```
$ mvn -Djib.to.image=gcr.io/chanseok-playground-new/foo jib:build
...
[INFO] Built and pushed image as gcr.io/chanseok-playground-new/foo
...
[INFO] BUILD SUCCESS
...
[INFO] Finished at: 2021-08-03T16:46:36-04:00
[INFO] ------------------------------------------------------------------------
$ mvn -Djib.to.image=gcr.io/chanseok-playground-new/foo jib:build
...
[INFO] Built and pushed image as gcr.io/chanseok-playground-new/foo
...
[INFO] Finished at: 2021-08-03T16:46:56-04:00
[INFO] ------------------------------------------------------------------------
```

I see that the image has just been uploaded, but it didn't create a new image. It is the exact same image.

![image](https://user-images.githubusercontent.com/10523105/128084795-1fc5dc06-3175-42bb-9886-c63ea4f44c56.png)

**Comment by chanseokoh** [comment]
BTW, `latest` in `-Djib.to.tags=latest,another_tag` is unnecessary. (We regret that we didn't name the parameter as `jib.to.additionalTags`.) `-Djib.from.image=eu.gcr.io/project_id/image_name` already implies `-Djib.from.image=eu.gcr.io/project_id/image_name:latest`.

**Comment by Alexander-Betz** [comment]
Thank you for the detailed example and information.

I see that you didn't include `-Djib.from.image=gcr.io/<GCP project>/foo` in your command. But in my case this is necessary right?

Because how I understand it is that since I'm running Jib in my Github Actions workflow runs:
- with `-Djib.from.image=eu.gcr.io/project_id/image_name` I'm pulling the latest image from GCR and use it as base image
- with that Jib knows how the latest image looks like
- then Jib rebuilds the image according to the changes in my commit
- if there is no change it should rebuild very fast like in your case and it should upload the same image and not create a new one

Unfortunately that's not what I'm experiencing. Here is how I'm running Jib in my workflow like mentioned in my first comment:
```
mvn compile jib:build -Djib.to.image=eu.gcr.io/project_id/image_name -Djib.from.image=eu.gcr.io/project_id/image_name

```
I just changed `Dimage` now to `Djib.to.image` and removed the tags.

With dummy commits I ran Jib 5 times now in my workflow runs and here is the latest run:
```
[INFO] 
[INFO] Containerizing application to eu.gcr.io/project_id/image_name...
Warning:  Base image 'eu.gcr.io/project_id/image_name' does not use a specific image digest - build may not be reproducible
[INFO] Getting manifest for base image eu.gcr.io/project_id/image_name...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO] Building jvm arg files layer...
[INFO] The base image requires auth. Trying again for eu.gcr.io/project_id/image_name...
[INFO] Using credentials from Docker config (/home/runner/.docker/config.json) for eu.gcr.io/project_id/image_name
[INFO] Using credentials from Docker config (/home/runner/.docker/config.json) for eu.gcr.io/project_id/image_name
[INFO] Using base image with digest: sha256:44d62...
[INFO] 
[INFO] Container entrypoint set to [java, -cp, @/app/jib-classpath-file, path/to/class]
[INFO] 
[INFO] Built and pushed image as eu.gcr.io/project_id/image_name
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.783 s
[INFO] Finished at: 2021-08-04T16:18:13Z
[INFO] ------------------------------------------------------------------------
```

In GCR I see that there is always a new image added/created and for some reason the virtual size increases every time by approx. 50MB
![image](https://user-images.githubusercontent.com/70712913/128219786-5310e879-cb8f-4b86-9676-4ad7518a4921.png)

Do you have an idea why this is happening?

**Comment by chanseokoh** [comment]
You misunderstood what a base image is. It doesn't make sense to set both `jib.from.image` and `jib.to image` to the same image. You build a new image by adding layers of your application (classes, resources, ...) on top of a base image. Then, what you did was to use that new image as a base image and put the same application layers on top of that. That is, now you have duplicate layers. You have been repeating process, and that is why your image size on GCR is progressively increasing.

When you are not specifying a base image, the default Jib uses is `adoptopenjdk:8/11`, but you can choose whatever JDK image that you think works best for you.
