### ISSUE TITLE
It might be nice if our final image didn't say CREATED in 292 years ago.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#341]
We can make each layer reproducible but the final tar can still have a different creation date with the same image-id?

**Comment by patflynn** [comment]
Shouldn't we only be zero-ing this out when the builds are reproducible
with a fixed digest base image?

**Comment by coollog** [comment]
Currently, we aren't actually zero-ing this out for the image, but rather just not setting a creation time (https://github.com/opencontainers/image-spec/blob/master/config.md#properties), which somehow causes Docker to say `292 years ago`. For builds, we don't vary any of our build logic based on what the base image is so all the application layers and container config are reproducible.
