### ISSUE TITLE
Consider publishing Jib CLI to SDKMAN

### ISSUE THREAD

**Issue by vpavic** [GoogleContainerTools/jib#3419]
SDKMAN is a very popular tool for managing various SDKs for the JVM. The list of currently available SDKs can be seen [here](https://sdkman.io/sdks).

Jib CLI seems like a natural fit for the SDKMAN, and I'm pretty sure its presence on the SDKMAN would help increase adoption.

**Comment by suztomo** [comment]
@vpavic I'm new to SDKMAN. It seems that the tool allows users to have different versions of the tools listed there. I want to know more about that. Would you  describe your situation where you encountered issues where you only had one version of Jib CLI?

**Comment by vpavic** [comment]
> Would you describe your situation where you encountered issues where you only had one version of Jib CLI?

I'm not sure if I understand this right.

There are no issues - rather than managing my local Jib CLI installation manually, I'd like to have it managed by SDKMAN, just like I have it with a number of tools listed on [sdkman.io](https://sdkman.io/sdks).

**Comment by suztomo** [comment]
Good. Glad to hear you're not having a problem. Thank you for clarification.

**Comment by suztomo** [comment]
This feature is not currently in our roadmap. If we change the direction, we revisit this issue.

**Comment by mpeddada1** [comment]
This is really cool! Thanks for the update.

**Comment by emmileaf** [comment]
Duplicate of #3667, closing as part of cleanup to centralize the discussion there.
