### ISSUE TITLE
No autosuggestions in intellij for Maven configuration.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#345]
This is probably because we are using nested configuration classes.

This only happens for the nested configuration like `to` and `from`.

**Comment by coollog** [comment]
@etanshaul Hey Etan, did you encounter this no autosuggestions problem in IntelliJ when you were working on the BOM stuff?

**Comment by etanshaul** [comment]
could you elaborate? do you mean that it stopped autocompleting suddenly?

**Comment by coollog** [comment]
@etanshaul I believe it probably never autocompleted for the nested configuration options we added. It works fine for the "normal" configuration like `mainClass` and `jvmFlags`, but not for the nested configuration like `to`:

```xml
  <configuration>
    <to>
      < <- typing the angle bracket here does not show the possible nested configuration parameters
    </to>
  </configuration>
```

This might just be a limitation in the way IntelliJ processes Maven plugin configuration though.

**Comment by etanshaul** [comment]
we don't have anything specific related to this for the BOM work. What we do have is custom inspections and quickfixes, but that's a different thing.

Nested configuration should autocomplete. I just tested this out with a different plugin. But I'm not immediately sure why its not working with jib.

**Comment by etanshaul** [comment]
actually the nested autocomplete I noticed working was for simple List types. it doesn't work for custom types as far as I can tell

**Comment by coollog** [comment]
Okay I'll take a look more into this. Thanks!

**Comment by coollog** [comment]
Not possible

**Comment by patflynn** [comment]
one thing we do in the appengine plugins is add aliases to the nested
fields e.g. `<to.image>` as well as `<to><image>`, which should work with
quick docs and command line flags.

**Comment by coollog** [comment]
@patflynn Filed #382 for adding aliases.
