### ISSUE TITLE
springboot multi-module change harbor

### ISSUE THREAD

**Issue by ustcck** [GoogleContainerTools/jib#3453]
**Environment**:

- *Jib version:* 2.7.1
- *Build tool:* maven 3.6.1
- *OS:* win10

**Description of the issue**:

have two harbor：harbor.lenovo-r.cloud,harbor.ar.thinkhcp.cn. and will change between them

Using the command line, and get some errors. Is that the wrong way to use it?
`mvn clean package -Dmaven.test.skip=true jib:build -Djib.to.tags=2.0.5 -Djib.to.image=harbor.ar.thinkhcp.cn/aa-traini ng/${project.artifactId}`

**Expected behavior**:
can change between two harbors,

**Steps to reproduce**:
  1. springboot multi-module
  2. mvn clean package -Dmaven.test.skip=true jib:build -Djib.to.tags=2.0.5 -Djib.to.image=harbor.ar.thinkhcp.cn/aa-traini ng/${project.artifactId}

**`jib-maven-plugin` Configuration**: 
```xml
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>${jib-maven-plugin.version}</version>
                    <configuration>
                        <from>
                            <image>adoptopenjdk:8-jre-openj9</image>
                        </from>
                        <to>
                            <image>harbor.lenovo-r.cloud/aa-training/${project.artifactId}</image>
                            <auth>
                                <username>***</username>
                                <password>***</password>
                            </auth>
                            <tags>
                                <tag>2.0.0</tag>
                            </tags>
                        </to>
                        <container>
                            <entrypoint>
                                <shell>bash</shell>
                                <option>-c</option>
                                <arg>chmod +x /entrypoint.sh &amp;&amp; sync &amp;&amp; /entrypoint.sh</arg>
                            </entrypoint>
                            <environment>
                                <TZ>Asia/Shanghai</TZ>
                            </environment>
                            <creationTime>USE_CURRENT_TIMESTAMP</creationTime>
                        </container>
                        <allowInsecureRegistries>true</allowInsecureRegistries>
                    </configuration>
                </plugin>
```

**Comment by meltsufin** [comment]
I suspect `${project.artifactId}` is not being substituted when done through command-line. What's the error that you're seeing?

**Comment by ustcck** [comment]
Yeah, not being substituted. Is there a solution?

`[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.7.1:build (default-cli) on project aa-training-gateway: Invalid image reference harbor.ar.thinkhcp.cn/aa-training/${project.artifactId}, perhaps you should check that the reference is formatted correctly according to https://docs.docker.com/engine/reference/commandline/tag/#extended-description
[ERROR] For example, slash-separated name components cannot have uppercase letters: Invalid image reference: harbor.ar.thinkhcp.cn/aa-training/${project.artifactId}
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :aa-training-gateway`

**Comment by meltsufin** [comment]
Maybe try passing a property instead and doing substitution in the `pom.xml`?
```
<image>${harbor.host}/aa-training/${project.artifactId}</image>
```
```
mvn clean package -Dmaven.test.skip=true jib:build -Djib.to.tags=2.0.5 -Dharbor.host=harbor.ar.thinkhcp.cn
```

**Comment by ustcck** [comment]
It worked.  Many thanks.
