### ISSUE TITLE
Support including test scoped dependencies/resources

### ISSUE THREAD

**Issue by omallo** [GoogleContainerTools/jib#3455]
I have a Maven module containing Cucumber tests which can be executed through a Java main class. All the module dependencies and resources are under the scope "test" which is the common practice with Cucumber.

I would like to containerize my Cucumber tests using Jib. This is currently not possible since Jib does not support including test scoped resources. This is why I would like to request support for test scoped resources in Jib.

I have also considered the possibility of implementing such a functionality as a Jib extension but I believe that it is easier and more maintainable to support this directly in Jib. Furthermore, Jib would currently fail on a module which has only test scoped resources since the Jib layers would be empty which lets Jib fail immediately.

Could you please check whether it would be possible to add such a functionality to Jib?

**Comment by elefeint** [comment]
@omallo Thank you for describing your usecase. This may be common practice in Cucumber, but it goes against the intent of Maven test scope. If running tests is the primary goal of the application, then the dependencies required should be included in `compile` scope.

Maven's [documentation](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) is clear that test scope "indicates that the dependency is not required for normal use of the application, and is only available for the test compilation and execution phases".

As such, we will not consider implementing this feature in Jib.

**Comment by chanseokoh** [comment]
Yeah, if you do need those dependencies at runtime, why don't you just declare them with the `runtime` or `compile` scope? If you don't want that to be the default for some reason, at least you can use a profile to change the scope only for Jib builds.
