### ISSUE TITLE
Allow user to set default arguments to main.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#346]
drop wizard requires it

@patflynn 

- [x] Add `Cmd` to `ContainerConfigurationTemplate`
- [x] Add `javaArguments` to `BuildConfiguration`
- [x] Set `Cmd` in `ImageToJsonTranslator`
- [ ] Add parameter `args` to `jib-maven-plugin`
- [x] Add parameter `args` to `jib-gradle-plugin`

**Comment by coollog** [comment]
Should we have the parameter be called `args`, `mainArgs`, or `cmd`?

**Comment by patflynn** [comment]
+1 to `args`

```
~ $ java
Usage: java [-options] class [args...]
           (to execute a class)

```

**Comment by TadCordle** [comment]
+1 `args`

**Comment by coollog** [comment]
Looks like `args` it is
