### ISSUE TITLE
ClassNotFoundException - when building the image & push it to GCR using jib-maven-plugin in BitBucket pipeline

### ISSUE THREAD

**Issue by soumiknow** [GoogleContainerTools/jib#3465]
**Environment**:

- *Jib version:*  3.1.4
- *Build tool:* Maven 3.6.3
- *OS:*  linux-5.4.92-flatcar

**Description of the issue**:

I was able to build the image using jib-maven-plugin from my windows local system and able to deploy it into GCP Cloud Run. 

But when I used the same code to build the image using jib-maven-plugin from BitBucket pipeline, image got pushed to gcr, but unable to deploy to GCP Cloud Run service. It says Error: Could not find or load main class com.demo.sdas.Application Caused by: java.lang.ClassNotFoundException: com.demo.sdas.Application.

What I am not understanding is, if this is working from my local then why it failed to load from BitBucket Pipeline. Everything is same in the code repository and executing the same commands for building the image and deploying it. Is there any bug in jib plugin.

**Expected behavior**: jib-maven-plugin should build the image from BitBucket pipeline in same way it was doing from my local machine

**Steps to reproduce**:

  1. Create a HelloWorld SpingBoot api endpoint in BitBucket Repository.
  2. Push the code image to GCP Container Registry using jib-maven-plugin through BitBucket pipeline.
  3. Try to deploy the image in GCP Cloud Run using gcloud run deploy command.

**`jib-maven-plugin` Configuration**: 
```xml
<build>
        <pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>com.demo.sdas.Application</mainClass>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.1.4</version>
                <configuration>
                    <container>
                        <mainClass>com.demo.sdasApplication</mainClass>
                    </container>
                    <to>
                        <image>eu.gcr.io/sdas-demo-dev/temp-service</image>
                    </to>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        </pluginManagement>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
```

**Comment by dzou** [comment]
I think we need a little bit more information about your bitbucket pipeline to be able to help answer your question.

Could you share the Jib logs when you run it in debug mode and compare it between the local run and the run on bitbucket?
You can use the additional mvn flags `-X` and `-Djib.serialize=true` in your pipeline.
See: https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-view-debug-logs-for-jib

Also is it possible to pull the image that you pushed in step #2 using the bitbucket pipeline, [inspect the files inside](https://stackoverflow.com/questions/43308319/how-can-i-run-bash-in-a-new-container-of-a-docker-image), and confirm that all your class files appear correctly in the image?

**Comment by soumiknow** [comment]
> I think we need a little bit more information about your bitbucket pipeline to be able to help answer your question.
> 
> Could you share the Jib logs when you run it in debug mode and compare it between the local run and the run on bitbucket? You can use the additional mvn flags `-X` and `-Djib.serialize=true` in your command, both locally and in pipeline. See: https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-view-debug-logs-for-jib
> 
> Also is it possible to pull the image that you pushed in step 2 using the bitbucket pipeline, [inspect the files inside](https://stackoverflow.com/questions/43308319/how-can-i-run-bash-in-a-new-container-of-a-docker-image), and confirm that all your class files appear correctly in the image?

I pull the images which build using bitbucket pipeline and found that /app/classes does not contain any of the compiled files of my application. However the /app/resources, /app/libs, /app/jib-main-class-file contain the correct files and information.

**Comment by soumiknow** [comment]
This is the docker image history different between my local and bitbucket pipeline:
--------------------------------------------------------------------------------------------------------------
docker image history local-image
IMAGE               CREATED             CREATED BY               SIZE                COMMENT
113e94d4776b        51 years ago        jib-maven-plugin:2.8.0   116kB               classes
<missing>           51 years ago        jib-maven-plugin:2.8.0   17.1kB              resources
<missing>           51 years ago        jib-maven-plugin:2.8.0   114MB               dependencies
<missing>           51 years ago        bazel build ...          170MB
<missing>           51 years ago        bazel build ...          16.5MB
<missing>           51 years ago        bazel build ...          2.34MB
<missing>           51 years ago        bazel build ...          17.9MB
<missing>           51 years ago        bazel build ...          2.36MB
--------------------------------------------------------------------------------------------------------------
docker image history pipeline-image
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
f9cafe85cfb3        51 years ago        jib-maven-plugin:3.1.4                          8.83kB              jvm arg files
<missing>           51 years ago        jib-maven-plugin:3.1.4                          0B                  classes
<missing>           51 years ago        jib-maven-plugin:3.1.4                          13.3kB              resources
<missing>           51 years ago        jib-maven-plugin:3.1.4                          114MB               dependencies
<missing>           11 hours ago        /bin/sh -c #(nop)  ENV JAVA_HOME=/opt/java/o…   0B
<missing>           11 hours ago        /bin/sh -c set -eux;     ARCH="$(dpkg --prin…   128MB
<missing>           11 hours ago        /bin/sh -c #(nop)  ENV JAVA_VERSION=jdk-11.0…   0B
<missing>           11 hours ago        /bin/sh -c apt-get update     && apt-get ins…   43.2MB
<missing>           11 hours ago        /bin/sh -c #(nop)  ENV LANG=en_US.UTF-8 LANG…   0B
<missing>           12 hours ago        /bin/sh -c #(nop)  CMD ["bash"]                 0B
<missing>           12 hours ago        /bin/sh -c #(nop) ADD file:8d2f4a45a58b3f542…   72.8MB
 --------------------------------------------------------------------------------------------------------------

You can see that the class directory size is 0B in case of bitbucket-image, where it is 116kb size for local-image for the same code base.

**Comment by chanseokoh** [comment]
You're using Jib 2.8.0 on BitBucket. Please use 3.1.4.

**Comment by chanseokoh** [comment]
Oh, I see it's the other way around.

**Comment by chanseokoh** [comment]
I suspect `target/classes` directory is empty on BitBucket. Can you do like `tree -a target/classes` after running Jib to see what's in there?

**Comment by soumiknow** [comment]
> tree -a target/classes

You suspected at the correct point. `target/classes` is missing the application package directory in bitbucket server.

So, why it is doing so different than local.

**Comment by soumiknow** [comment]
Issue sorted now.

Root cause: 

- 'No resources found to compile' - I found this message in the build log. This message remind me something wrong within the application package.
- My system is running on Windows 10 and my application directory starting with 'Java.com.demo.sdas' (J in capital). Since Windows is case in sensitive; it is not causing an issue.
- BitBucket pipeline running on Linux server and it is case sensitive. Thus it is unable to find the application directory starting with 'Java.com.demo.sdas'.

Solution: Renamed the directory as 'java' and then everything is working as expected.
