### ISSUE TITLE
Could be nice to identify top 3-5 frameworks and provide tutorials for how to use Jib with them.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#347]
What should be cool is that we simplify their instructions a lot because they don’t need to setup uberjar.

Possible frameworks:

- [x] Spring boot
- [x] Dropwizard (#1290)
- [x] [ktor](https://github.com/ktorio/ktor) (#1291)
- [x] Vert.x
- [ ] Spark
- [ ] [Play framework](https://www.playframework.com/)
- [x] [micronaut](http://micronaut.io/) - move https://github.com/coollog/micronaut-jib over here? #893

**Comment by coollog** [comment]
Any help would be greatly appreciated!

**Comment by dansiviter** [comment]
Thorntail? Although v2 branch uses uberjar packaging which I believe Jib doesn't support.

**Comment by coollog** [comment]
@dansiviter Are there any special files in the uberjar packaging that is not available prior to packaging? If not, Jib should be able to package the container just like the uberjar packaging packages the jar.

**Comment by dansiviter** [comment]
Yea, Thorntail uses JBoss modules which are resolved when the `thorntail-maven-plugin` runs. The maven dependency graph primarily only has the JEE spec libraries (plus a few other bits) so doesn't have the implementations which mean Jib can't bundle the libraries correctly and fails at runtime. The Thorntail maintainers are flattening the classpath via their v4 branch but that's way off yet.

**Comment by cricket007** [comment]
Any news, or has anyone come across a Dropwizard example recently?

Would like to know if there are any gotchas before we begin.

**Comment by coollog** [comment]
@cricket007 We have a few examples up in the [`examples` folder](https://github.com/GoogleContainerTools/jib/tree/master/examples) (Spring Boot, Micronaut, Vert.x). We don't have a Dropwizard example yet, but we could definitely add one! (We welcome anyone to contribute an example too)

**Comment by chanseokoh** [comment]
We've covered 5 frameworks in the examples. Seems good enough to close this now.

**Comment by ffluk3** [comment]
Hey no need to re-open this issue necessarily, but has anyone encountered an example of leveraging the Play Framework with Jib? I am running into pathing issues trying to get things set up.

**Comment by OneCricketeer** [comment]
I recall seeing someone had posted about Play, or maybe in the playfrmework repo about Jib.

I vaguely recall someone mentioning that they recommended using sbt docker plugin instead
