### ISSUE TITLE
Jib-core: creation date ignored when pushing to repo

### ISSUE THREAD

**Issue by obierlaire** [GoogleContainerTools/jib#3482]
I understand that for [reproducibility reasons ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago) we need to set the creation timestamp to 0 (epoch). But in some cases, we are not rebuilding an image, but simply push it, maybe we could keep the creation date of the image. 

For example, in my project, we use jib-core's `JibContainerBuilder` and I need to build the image and save it, then push the image later (we do that in order to take advantage of the caching system of our CI). In jib-core, the only way to **push** an image is actually to rebuild it from the tar: 

```
Jib.from(<tar>)
  .containerize(
      Containizer.to(
          RegistryImage(... <image ref> ... )
     )
  )
```

In this example it's not a real "rebuild", it's a "push", so the creation date could be read from the tar. But it's not and it's set to zero. 

---
**Proposals:**

- Can we imagine specific values to `setCreationDate()` like:
  - `USE_FROM_TIMESTAMP` where it keeps the creation date from the `from()` image? 
  - Keep the creation date from the `from()` if we are not adding any new layer
  - `USE_CURRENT_TIMESTAMP` like in maven's jib setting the current timestamp
- or even, having an explicit `push(..)` method which will simply push a tar without rebuilding it, keeping the creation date? 

I currently work it around by storing the creation date in a file alongside with the image tar, call the [`setCreationDate()`](https://javadoc.io/static/com.google.cloud.tools/jib-maven-plugin/1.2.0/com/google/cloud/tools/jib/api/JibContainerBuilder.html#setCreationTime-java.time.Instant-) with the content of this file.

**Comment by chanseokoh** [comment]
Thanks for the input.

> * `USE_FROM_TIMESTAMP` where it keeps the creation date from the `from()` image?
> * Keep the creation date from the `from()` if we are not adding any new layer

> In this example it's not a real "rebuild", it's a "push"

Allow me to share our views on this. Jib is a tool to _build_ an image in a declarative manner. When you run Jib, you are always creating a new image, as it is what Jib does. Even if you have nothing after `from()`, you will create a new container configuration and a manifest, which means you will create a different image than the base image. The newly created image will always be different, as these metadata are really different. Jib is not a tool to just move or copy an existing image (whether the image is stored locally as a tar, in a Docker daemon cache, or in a remote registry). For such operations, there are other great tools specifically designed for that.

And the way we want Jib to build images is declaratively and  reproducibly. Image building is then conceptual. If you have the same source code that calls the Jib API interface in the exact same way, then whenever and wherever you check out the code and build an image, it should build the exact same image every time. That is, as soon as you have written a piece of code, it becomes irrelevant whether you have physically created and stored an image somewhere; all that matters is that you have the code that can build an image. But if you make Jib read a timestamp of a local file, then the outcome of running Jib will be different if, for example, you run it on a different machine or OR, or a month layer.

> `USE_CURRENT_TIMESTAMP` like in maven's jib setting the current timestamp

This is very easy to do in Java, so I don't think we really need to change the Jib API. Just get the current time and set it.

**Comment by chanseokoh** [comment]
I am closing the issue, but feel free to update for any feedback. Thanks!
