### ISSUE TITLE
Gradle: Set PathSensitivity for file and directory inputs, or support Gradle CopySpec instead

### ISSUE THREAD

**Issue by nhoughto** [GoogleContainerTools/jib#3488]
The current setup for Gradle tasks configured task inputs via `@InputFile` etc but doesn't set a `@PathSensitivity` of the files, so the current default of ABSOLUTE is used (https://github.com/gradle/gradle/issues/10346). Which means that the absolute path to input files is considered when doing up-to-date or build caching checks, this makes the checks fragile and any caching/reduction in work to be invalidated in any environment where the path can change (CI / different peoples machines). Best practice is to either set path sensitivity, or use the more idiomatic Gradle CopySpec instead of the `from, into, includes, excludes` blocks you currently have which supports configuring PathSensitivity OOTB.

```
gw jibBuildTar -Dorg.gradle.caching.debug=true -i

...
Appending input file fingerprints for 'inputFiles' to build cache key: 8d7a4ab4f25eddbb27b76ce61cab5766 - ABSOLUTE_PATH{...
```

**Comment by suztomo** [comment]
> this makes the checks fragile and any caching/reduction in work to be invalidated in any environment where the path can change (CI / different peoples machines)

Can you elaborate a bit more? I might lack the context of your application but for me, it's natural to have cache invalidated when running a new build in CI or in another people machine.

**Comment by nhoughto** [comment]
Generally it is good practice in Gradle to have as stable inputs as possible (https://docs.gradle.org/current/userguide/build_cache_concepts.html#relocatability) there is no reason they can't be stable here so would be a small win.

Working through how i'm looking to use Jib more, caching is less important than I expected as the tasks are all naturally uncached (packaging tar file, pushing image) not an expensive local operation like compilation. So this is likely just a 'best practice' thing that might save someone some pain in future.

**Comment by chanseokoh** [comment]
Thanks for the feedback.

> idiomatic Gradle CopySpec instead of the `from, into, includes, excludes` blocks

We need to give more thoughts on this to maintain a good balance in the spectrum: from a Gradle-specific and -idiomatic implementation to a common and general model that can consistently apply to other plugins. After all, Gradle is one build tool, and we want to keep consistent behavior and infrastructure across multiple plugins for reasons including maintainability. That said, we have been embracing Gradle-only way already in many areas, and I'm just saying we need to maintain a good balance and give more thoughts. We have established a common configuration processing pipeline shared by both Maven and Gradle, and sometimes, a Gradle-specific idiom can be hard to implement on the existing infrastructure. Also, we see many Gradle folks often strongly advocate that "the Gradle way is correct" or "in Gradle, you should do it in the Gradle way" (don't get me wrong, we listen), but at the same time, we always consider matters from both Maven and Gradle perspectives. In any case, we'll leave this open.

**Comment by ldetmer** [comment]
Please note our updated [code on conduct](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md).  
We are primarily focused on critical bug fixes and platform evolution to ensure it continues to work for its supported use cases.  Closing as out of scope.
