### ISSUE TITLE
How to use command line specify base image?

### ISSUE THREAD

**Issue by ChangJinLong** [GoogleContainerTools/jib#3513]
### **`jib-maven-plugin`**

I don't want specify base image in pom.xml, like this:
```xml
<configuration>
  <from>
    <image>openjdk:alpine</image>
  </from>
   ......
</configuration>
```
I want specify base in command line, like this:
```shell
mvn compile com.google.cloud.tools:jib-maven-plugin:3.1.4:build -Dfrom=<BASE IMAGE>
```
Is there such an command already?
What's it way to use?

**Comment by mpeddada1** [comment]
Hi @ChangJinLong, it is possible to configure the base image through the command line with `-Djib.from.image=<BASE IMAGE>`. Please look into this [section in our documentation](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#system-properties) if you would like more information on how parameters can be configured using system properties. We generally follow this convention: `-Djib.parameterName[.nestedParameter.[...]]=value`
