### ISSUE TITLE
Plugin is tagging images as latest even when only another tag is specified

### ISSUE THREAD

**Issue by wapmesquita** [GoogleContainerTools/jib#3528]
**Environment**:

- *Jib version:* 3.1.4
- *Build tool:* Maven
- *OS:* Linux

**Description of the issue**:
The plugin is creating the latest image even when not specified.

I set up my project like this and:
```
          <to>
            <image>my.registry/my-image</image>
            <tags>
              <tag>test</tag>
            </tags>
          </to>
```

And it generated the images `my.registry/my-image:test` and `my.registry/my-image:latest`

**Expected behavior**:

When the tags is defined generate the images only with the defined tags.

**Steps to reproduce**:

  1. Set up the project as above.
  2. Run `mvn jib:dockerBuild`
  3. Run `docker images`

**Comment by chanseokoh** [comment]
Closing as a dup of #3346.
