### ISSUE TITLE
Issues setting up custom entrypoint for SpringBoot application

### ISSUE THREAD

**Issue by giovanni-nic-kuama** [GoogleContainerTools/jib#3533]
**Environment**:

- Jib version: `3.1.4`

- Build tool: `Maven `
```
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Maven home: /Users/**/.m2/wrapper/dists/apache-maven-3.8.3-bin/5a6n1u8or3307vo2u2jgmkhm0t/apache-maven-3.8.3
Java version: 11.0.12, vendor: Eclipse Foundation, runtime: /Users/*/Library/Java/JavaVirtualMachines/temurin-11.0.12/Contents/Home
Default locale: it_IT, platform encoding: UTF-8
OS name: "mac os x", version: "11.1", arch: "x86_64", family: "mac"
```

- OS: OSX 12.1 Monterey (updated today on my laptop), OSX 11 on my workplace (the issue is the same in both versions)
- Spring Boot 2.6.0 (not sure if it's an useful info)

Description of the issue:
Hi everyone,
I'm not sure if this is really a bug or a configuration issue on my part (I'm a Junior dev, and Java/Spring/Jib is not my only focus).  In my workplace I found the need to dockerize a spring boot app while being able to pass env variables to Spring Boot (such as Db connection parameters, active profiles, context for liquibase, ecc..) through docker-compose so that the built image is not machine dependent. If I understood correctly, this problem can be solved setting up a custom entrypoint that "pass" env variables from the docker compose to the Jvm.

I'm sure that this procedure should be possible because I'm working on a Jhipster project that does exactly the same (even if it use Jib 2.0.0 and SpringBoot 2.*.*) and it's even useful to let the app start with some delay in respect to the DB container to make more likely it is ready when Spring Boot tries to start a connection to it (I've seen this problem a couple of times, especially if the DB container is starting for the first time).

The problem that I've found is that the custom entrypoint.sh script that I made doesn't seem to be executed. 
I've tried to follow these 3 setup suggested by a person who claims to work on Google Cloud  [here](https://stackoverflow.com/questions/59357410/jib-how-to-use-environmental-variables-from-base-image/59361658#59361658)  but none of these has been successful. If I open a shell into the container, I can find my entrypoint.sh file on the root. For now the entrypoint script is a standard one for running a java app, preceded by a simple echo (to confirm the script has been executed). 
A confirmation to the fact that this custom entrypoint is not picked is in the output of the command: `./mvnw clean package jib:dockerBuild`

Output:
```
Using base image with digest: sha256:ad6431b2e2a6f8016aa6d79c3f588783af9fdc06cafe131fd0d3faf560914b13
[INFO] 
[INFO] Container entrypoint set to [java, -cp, @/app/jib-classpath-file, com.gn.springtest.SpringtestApplicationKt]
[INFO] 
[INFO] Built image to Docker daemon as springtest:0.0.1-SNAPSHOT
```

**Expected behavior**:
I would expect to see the echo "Ciao SpringTest" before the spring boot app stats and later, when I got this working, be able to pass variables from the docker compose to spring boot.

**Steps to reproduce**:
I have a very similar open repo that is setup exactly as the project where I found this issue. 
These 2 project has been setup with IntellJ Ultimate through Spring Initialzr. They both uses Kotlin as language.

Even in this repo it seems I cannot make this work. To reproduce, you can clone my repo [here, the branch 'feat/setup-docker-entrypoint' is already selected](https://github.com/giovanni-nic-kuama/springtest/tree/feat/setup-docker-entrypoint)

Run Jib to create the image and push to the loca docker daemon:
`./mvnw clean package jib:dockerBuild`

Here you will already see that the picked entrypoint is the standard one `[java, -cp, @/app/jib-classpath-file, com.gn.springtest.SpringtestApplicationKt]` and not the one I wrote.

Run Docker compose to bring up the Spring App and its Postgres BD:
`docker-compose up -d`

If you look into docker logs you will not see the echo coming from the custom entrypoint.sh before the Spring Boot App starts.

I hope some of you can help me understand why this is not working.
I tried to be as specific as I could. As you can see I'm not really strong with English and I hope you can understand the wall of text that I wrote. If you need additional I try to reply as soon as possible. 
Thank you very much for this project. I really appreciate Jib, and I'm trying to learn how to use it correctly!

PS: Sorry to make you read and clone another sh***y todo app. 

Giovanni.

**Comment by giovanni-nic-kuama** [comment]
While further investigating, I found a solution to my problem while reading an issue on Jhipster-generator repository.
I've commited a fix on the branch I specified on the erlier post so anybody interested can look directly the code.

In short I setup Jib like this on my pom file:

`<plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.1.4</version>
                <executions>
                    <execution>
                        <configuration>
                            <from>
                                <image>adoptopenjdk:11-jre-hotspot</image>
                            </from>
                            <to>
                                <image>springtest</image>
                            </to>
                            <container>
                                <entrypoint>
                                    <shell>sh</shell>
                                    <option>-c</option>
                                    <arg>/entrypoint.sh</arg>
                                </entrypoint>
                                <ports>
                                    <port>8080</port>
                                </ports>
                                <environment>
                                    <SPRING_OUTPUT_ANSI_ENABLED>ALWAYS</SPRING_OUTPUT_ANSI_ENABLED>
                                </environment>
                                <creationTime>USE_CURRENT_TIMESTAMP</creationTime>
                            </container>
                            <extraDirectories>
                                <permissions>
                                  <permission>
                                    <file>/entrypoint.sh</file>
                                    <mode>755</mode>
                                  </permission>
                                </permissions>
                              </extraDirectories>                              
                        </configuration>
                        <phase>package</phase>
                    </execution>
                </executions>
            </plugin>`

Then, instead of building the image with this command `./mvnw clean package jib:dockerBuild`  I run `./mvnw package jib:dockerBuild -Djib.extraDirectories.permissions="/entrypoint.sh"="755"`

and on the docker-compose I defined the property `entrypoint: "entrypoint.sh"` on the service running the built jib image. 

Now, before spring boot starts, I can correctly see my echo. Now I'll try to pass some variables from the docker-compose  file to spring boot.

**Comment by ddixit14** [comment]
Thanks @giovanni-nic-kuama, the fix LGTM. Please let us know if there's anything else we can help with!
