### ISSUE TITLE
extraDirectories property should validate if the supplied path exists

### ISSUE THREAD

**Issue by tommysitu** [GoogleContainerTools/jib#3542]
**Environment**:

- *Jib version:* 3.1.4
- *Build tool:* Maven 3.6.2

**Description of the issue**:
```
<configuration>
    <extraDirectories>
         <paths>
             <path>missing/folder</path>
          </paths>
     </extraDirectories>
</configuration>
```
Using the `extraDirectories` config above to copy additional files doesn't fail the build even the path is invalid or not a folder. This behaviour is not good for catching bugs early if the additional files are crucial for the docker container. 

**Expected behaviour**:
Should be similar to the `docker build` command which would throw the following exception if a `Dockerfile` has a command to copy a non-existent folder: 

```
 => ERROR [stage-1 2/2] COPY missing/folder /app                                                                                                                                     0.0s
------
 > [stage-1 2/2] COPY missing/folder /app:
------
failed to compute cache key: "/missing/folder" not found: not found

```

**Comment by meltsufin** [comment]
Thank you for submitting this enhancement request.

**Comment by chanseokoh** [comment]
The reason we don't check the existence is due to the default implicit directory `src/main/jib`, which doesn't exist often. Perhaps we should fail only for non-default directories.

**Comment by tommysitu** [comment]
Hi @chanseokoh I've raised a PR. Could you approve the build? so that we can see which tests are failing. Thanks!

**Comment by chanseokoh** [comment]
@tommysitu I just approved it.

**Comment by tommysitu** [comment]
Thanks for reviewing the PR @chanseokoh. Shall I close this issue?

**Comment by cebrailinanc** [comment]
i got  error on gradle
Execution failed for task ':jib'.
> extraDirectories.paths contain "from" directory that doesn't exist locally: /aass/test

my command:  `./gradlew jib ... -Djib.extraDirectories.paths=truststore,/aass/test`

**Comment by chanseokoh** [comment]
@cebrailinanc just create the directory before running Gradle, like `mkdir /aass/test`.

**Comment by cebrailinanc** [comment]
I tried but it didn't work. Because we need to open a folder within the image.

**Comment by chanseokoh** [comment]
Oh, I see what you were thinking. It must be that you thought the syntax of the command-line parameter would be
```
-Djib.extraDirectories.paths=<from_1>,<to_1>,<from_2>,<to_2>,...
```
, but the command-line [supports only the basic form](https://github.com/GoogleContainerTools/jib/blob/0df8ed9e0e6990321f1193d214915987127962b9/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ExtraDirectoriesParameters.java#L74-L79) of
```
-Djib.extraDirectories.paths=<form_1>,<from_2>,<from_3>,...
```
. If you want to specify the `to` directories, you have to set it in a Gradle build file.

**Comment by cebrailinanc** [comment]
i think, it's not useful, 
Should we open an issue?

**Comment by chanseokoh** [comment]
Sure, go ahead open a new issue.

**Comment by chanseokoh** [comment]
Anyways, if you are familiar with Gralde, you can always define your own property as a workaround to templatize `to` directiories on the command-line.

**Comment by cebrailinanc** [comment]
I used it by defining it in the `build.gradle`. But it would be usable to add the command line in the future, thank you.

```
jib {
	extraDirectories {
		paths {
			path {
				setFrom("extra")
				into = "/test/native-libs"
			}
		}
	}
}
```
