### ISSUE TITLE
Support local registry without Docker daemon

### ISSUE THREAD

**Issue by Kitanotori** [GoogleContainerTools/jib#3577]
**Environment**:

- *Jib version:* 3.2.0
- *Build tool:* Gradle 7.4
- *OS:* macOS 12.2

**Description of the issue**:

It is not possible to build an image into local registry without Docker daemon. I'm using [lima-vm ](https://github.com/lima-vm/lima) with [containerd](https://github.com/containerd/containerd) as runtime, and manage containers using [nerdctl](https://github.com/containerd/nerdctl) - all installed as part of [Rancher Desktop](https://rancherdesktop.io/).

Industry is moving away from Docker daemon, so this kind of limitation is a blocker in adoption of jib for those who can't or don't want to use Docker.

**Expected behavior**:

Can build OCI image locally without Docker daemon.

**Comment by elefeint** [comment]
There is a similar discussion in #3571. Please comment on the existing issue with additional requirements / preferences, so they can all be addressed consistently.
