### ISSUE TITLE
Publish jib-plugins-common as artifact for code-reuse in third-party projects

### ISSUE THREAD

**Issue by pschichtel** [GoogleContainerTools/jib#3578]
**Description of the issue**:

All official jib plugins use the `jib-plugins-common` module in order to consistently do certain things like for example outputting the `jib-image.{digest,id,json}` files. I build a few scala application which use [sbt-jib](https://github.com/schmitch/sbt-jib) SBT plugin to build containers with jib. [That plugin does not currently generate these files](https://github.com/schmitch/sbt-jib/issues/70).

When contributing the functionality to the plugin I noticed that the code used by the official plugins is not currently published as an artifact usable for projects similar to jib-core. It would be great if other build-tool integration could re-use the same code for consistency.

#3194 is somewhat related as it would also affect third-party users of the code.

**Comment by elefeint** [comment]
@pschichtel Thank you for the request! Would the same functionality be possible through https://github.com/GoogleContainerTools/jib-extensions?

**Comment by pschichtel** [comment]
Not quite sure. The jib-extensions project seems to be for extending the maven and gradle plugin. How would that help here? Or am I missing something?

**Comment by elefeint** [comment]
We've discussed this internally, and currently there are no plans to publish `jib-plugins-common`. As the project is Apache v2.0 licensed, you can copy any useful files with attribution.

**Comment by pschichtel** [comment]
@elefeint well publishing the jib-plugins-common module wasn't really my request. My intent is to reuse the code, not because I cannot write it myself or copy it, but to improve consistency to the official plugins.

Would it be an option to move the logic for these files to another artifact, e.g. jib-core (not sure if that is a fitting place)?

**Comment by elefeint** [comment]
jib-core is for shared logic that's not only for plugins. We specifically don't want to create a public API surface out of the internal plugin implementation details at this time -- having external projects depend on this code would limit our ability to refactor it in the future.

**Comment by elefeint** [comment]
I'm sorry; we are not going to expose this functionality.

**Comment by pschichtel** [comment]
Are their plans for official integrations for build systems other than gradle and maven?

**Comment by elefeint** [comment]
No, no plans.

**Comment by chanseokoh** [comment]
> The files that this code generates already part of the API, you can't easily change them without probably breaking tons of CI pipelines and I think generating these files might also be interesting for the cli and other projects, not just for gradle/maven/sbt. I would even be fine if these APIs would be flagged as unstable or something.

The behavior that the plugins and the CLI generate `jib-image.{digest,id,json}` is stable and will not change. We will not break that. What we are talking about API by "public surface" is making some part of jib-plugins-common code a library so that Java programmers can make use of by calling public Java library API surface. Java code in jib-plugins-common code is internal and we will change it however we want. This doesn't mean we will break Jib behavior.
