### ISSUE TITLE
FYI: Created a new idiomatic gradle plugin around jib-core

### ISSUE THREAD

**Issue by nhoughto** [GoogleContainerTools/jib#3582]
As discussed in a few issues, I've been kicking around ways to solve for some of the constraints i've bumped into using Jib and the OOTB jib gradle plugin, and I ended up rolling them up into a separate gradle plugin that I thought others might find useful.

Plugin here, early days not published to gradle plugin portal yet but the bones are there:
https://github.com/bsycorp/gradle-jib-plugin

The intent of the project is to create an idiomatic Gradle plugin around `jib-core` that follows all the Gradle best practices for the best Gradle experience (build cache, configuration caching, up-to-date checking, `Property<>` usage, locking concurrent base image pulls etc). I know the Jib project has to solve for both Gradle and Maven  (probably others?) and that means its hard or impossible to achieve these Gradle specific things, so I just solved for Gradle =).

If you spot anything that could be improved with the `jib-core` integration or anything in general, happy to hear 👍

**Comment by melix** [comment]
This looks very interesting, @nhoughto . I may be able to give your plugin a try for building containers with Micronaut!

**Comment by elefeint** [comment]
Alternative implementations strengthen the ecosystem. If you prefer to use more of the existing plugin's functionality, you may be interested in creating a Jib Gradle plugin extension (https://github.com/GoogleContainerTools/jib-extensions).

**Comment by ldetmer** [comment]
closing issue, thank you for the contribution!
