### ISSUE TITLE
Release sha256 file is wrong for jib-cli

### ISSUE THREAD

**Issue by vlagorce** [GoogleContainerTools/jib#3584]
**Environment**:

- *Jib version:* v0.9.0

**Description of the issue**:
The file name in the sha256 file is wrong
https://github.com/GoogleContainerTools/jib/releases/download/v0.9.0-cli/jib-jre-0.9.0.zip.sha256

**Expected behavior**:
File name must be jib-jre-0.9.0.zip instead of  jib-0.9.0.zip

**Steps to reproduce**:
```
$ sha256sum -c jib-jre-0.9.0.zip.sha256
sha256sum: jib-0.9.0.zip: No such file or directory
```

**Comment by suztomo** [comment]
I see the two files "jib-jre-0.9.0.zip" and "jib-jre-0.9.0.zip.sha256" in GitHub's release page.

<img width="535" alt="Screen Shot 2022-02-25 at 2 21 31 PM" src="https://user-images.githubusercontent.com/28604/155775384-8b64c8b1-3f7d-4e02-87f3-a8ac0d78924b.png">

Are you referring somewhere different?

**Comment by suztomo** [comment]
Now I understand the problem.

```
suztomo@suztomo:/tmp$ sha256sum -c jib-jre-0.9.0.zip.sha256 
sha256sum: jib-0.9.0.zip: No such file or directory
jib-0.9.0.zip: FAILED open or read
sha256sum: WARNING: 1 listed file could not be read
suztomo@suztomo:/tmp$ cat jib-jre-0.9.0.zip.sha256 
c0f47017f1218a223f51228cc69fe9d7793e600d8a05b11e4dbdba0dee6bfc11  jib-0.9.0.zip
```

```
suztomo@suztomo:/tmp$ sha256sum --help
...
  -c, --check          read SHA256 sums from the FILEs and check them
```

**Comment by mpeddada1** [comment]
@vlagorce thanks for reporting this issue! Jib CLI 0.10.0 with this fix has been released.
