### ISSUE TITLE
Jib throwing an error: [ERROR] Failed to execute goal on project

### ISSUE THREAD

**Issue by EbadMajeed** [GoogleContainerTools/jib#3599]
Hi 

**I am working with a legacy system (SOAP Service which doesn't have any main method in it) and I am trying to containerize this service with Jib. I was successfully able to push a sample HelloWorld image (where I had a main method) but when I try to containerize the actual service it shows an error which I am not able to resolve.**

Here is my POM:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>Link01</groupId>
    <artifactId>ourApp</artifactId>
    <version>4.1-SNAPSHOT</version>

    <packaging>pom</packaging>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.scm.id>ourGitHubCI</project.scm.id>
        <project.scm.url>URL to our GitHub repo</project.scm.url>
    </properties>

    <modules>
        <module>ourApp-ejb</module>
        <module>ourApp-war</module>
    </modules>

    <profiles>
        <profile>
            <id>java8-doclint-disabled</id>
            <activation>
                <jdk>[1.8,)</jdk>
            </activation>
            <properties>
                <javadoc.opts>-Xdoclint:none</javadoc.opts>
            </properties>
        </profile>
    </profiles>

    <build>
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <to>
                        <image>ourRegistry/ourApp</image>
                    </to>
                </configuration>
            </plugin>

            <plugin>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.5.3</version>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.scm</groupId>
                        <artifactId>maven-scm-provider-gitexe</artifactId>
                        <version>1.9.5</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <version>2.9</version>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <additionalparam>${javadoc.opts}</additionalparam>
                            <failOnError>false</failOnError>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <reportPlugins>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-javadoc-plugin</artifactId>
                            <configuration>
                                <additionalparam>${javadoc.opts}</additionalparam>
                                <failOnError>false</failOnError>
                            </configuration>
                        </plugin>
                    </reportPlugins>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-checkstyle-plugin</artifactId>
                <version>2.17</version>
            </plugin>
        </plugins>
    </build>

    
    <scm>
        <connection>scm:git:${project.scm.url}</connection>
        <developerConnection>scm:git:${project.scm.url}</developerConnection>
        <url>${project.scm.url}</url>
        <tag>HEAD</tag>
  </scm>
    <distributionManagement>
        <repository>
            <id>repository.internal</id>
            <url>http://server/factory/libs-release-local/</url>
        </repository>
        <snapshotRepository>
            <id>repository.snapshots</id>
            <url>http://server/factory/libs-snapshot-local/</url>
        </snapshotRepository>
    </distributionManagement>

</project>

**and this is the error I get when I type mvn compile jib:build:**

[ERROR] Failed to execute goal on project ourApp-ejb: Could not resolve dependencies for project Link01:ourApp-ejb:ejb:4.1-SNAPSHOT: Failed to collect dependencies at Link01:settings-reader:jar:1.0: Failed to read artifact descriptor for Link01:settings-reader:jar:1.0: Could not transfer artifact Link01:settings-reader:pom:1.0 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [repository.internal (http://server/factory/libs-release/, default, releases+snapshots), repository.snapshots (http://server/factory/libs-snapshot/, default, releases+snapshots)] -> [Help 1]

Could you please help me with this issue?

**Comment by EbadMajeed** [comment]
Clearing the cache doesn't help. In the project I have different modules:
- ourApp (root)
- ourApp-ejb
- ourApp-war

I can do: "clean test install" fine but when I go to Maven tab, ourApp(root) or ourApp-ejb->plugins->jib and when I click jib:build or jib:buildtar I get an error:

**[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.2.0:build (default-cli) on project ourApp-ejb: Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin -> [Help 1]**

Do you know how can I get rid of this?

**Comment by EbadMajeed** [comment]
> @mpeddada1 Clearing the cache doesn't help. In the project I have different modules:
> 
> * ourApp (root)
> * ourApp-ejb
> * ourApp-war
> 
> I can do: "clean test install" fine but when I go to Maven tab after that, in ourApp(root) or ourApp-ejb->plugins->jib and when I click jib:build or jib:buildtar I get an error:
> 
> **[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.2.0:build (default-cli) on project ourApp-ejb: Main class was not found, perhaps you should add a `mainClass` configuration to jib-maven-plugin -> [Help 1]**
> 
> Do you know how can I get rid of this?

and if I add main class configuration to jib-maven-plugin in POM:
<container><mainClass>ourApp-ejb.src.main.java.service.mainClassServiceBean</mainClass></container>
 then it says this:
**'mainClass' configured in jib-maven-plugin is not a valid Java class: ourApp-ejb.src.main.java.service.mainClassServiceBean, perhaps you should add a `mainClass` configuration to jib-maven-plugin**

**Comment by mpeddada1** [comment]
From your previous message, it looks like you're using a multimodule project? If that is true, I would first recommend following these instructions: https://github.com/GoogleContainerTools/jib/tree/master/examples/multi-module#how-to-run 

As for the `'mainClass' configured in jib-maven-plugin is not a valid Java class` error, the logic below verifies if the Java class name provided is syntactically valid and throws that message if it is not. So you need make sure there are no syntax errors when specifying the class:

https://github.com/GoogleContainerTools/jib/blob/0ed7dca36864b6b19ff61629fc578018041fa15f/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java#L120

It should be the full package name that contains the class + the class name. So if I have `package example.service` at the top of `MyApplication.java`. The mainClass would be `example.service.MyApplication`. Here's an [example](https://github.com/GoogleContainerTools/jib/tree/30301c4cb73b22f40e4cce936bb0e1fa7659104d/jib-maven-plugin#example).

**Comment by EbadMajeed** [comment]
> From your previous message, it looks like you're using a multimodule project? If that is true, I would first recommend following these instructions: https://github.com/GoogleContainerTools/jib/tree/master/examples/multi-module#how-to-run
> 
> As for the `'mainClass' configured in jib-maven-plugin is not a valid Java class` error, the logic below verifies if the Java class name provided is syntactically valid and throws that message if it is not. So you need make sure there are no syntax errors when specifying the class:
> 
> https://github.com/GoogleContainerTools/jib/blob/0ed7dca36864b6b19ff61629fc578018041fa15f/jib-plugins-common/src/main/java/com/google/cloud/tools/jib/plugins/common/MainClassResolver.java#L120
> 
> It should be the full package name that contains the class + the class name. So if I have `package example.service` at the top of `MyApplication.java`. The mainClass would be `example.service.MyApplication`. Here's an [example](https://github.com/GoogleContainerTools/jib/tree/30301c4cb73b22f40e4cce936bb0e1fa7659104d/jib-maven-plugin#example).

Hi @mpeddada1,

Sorry for a late reply. Yes it is a multimodule project and it has war packaging (was trying that) and after mentioning the plugin in war project (pom) and after generating the new war when I go to maven tab -> war project ->plugins -> jib -> jib:build
 
It worked and image was pushed it to ourRegistry but I am facing a new issue now. We use payara server to deploy our applications/services. I have added the base payara image in a the 'form' tag in pom. Payara instance starts but it seems like it is not picking up the service because when I go to local WSDL. It says Not found-404. 

While deploying our services to payara we do provide the context root of our services. Do you think it is unable to pick that up or there is another reason?

**Comment by mpeddada1** [comment]
I don't have much knowledge of payara. But I've seen an example where it did work: https://github.com/GoogleContainerTools/jib/issues/1280#issuecomment-442267845. Perhaps as a debugging technique, you could try a smaller "hello world" app to check if you're able to touch "localhost:8080/"? Additionally, when containerizing WAR projects with Jib, make sure you follow the instructions [here](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/README.md#war-projects). When you use a base image that is not the default, you may need to customize the container entrypoint and the appRoot.
