### ISSUE TITLE
openj9 image pre warm

### ISSUE THREAD

**Issue by company-myther** [GoogleContainerTools/jib#3601]
**Environment**:

- *Jib version:* 3.2.0
- *Build tool:*  maven
- *OS:* Window11

**Description of the issue**:
I am using openj9 jdk. How can I execute a command similar to the following to pre warm the container?
```shell
RUN /bin/bash -c 'java -Xshareclasses -Xscmx20M -jar batch-processor-0.0.1-SNAPSHOT.jar --run_type=short &' ; sleep 15 ; xargs kill -1
```

**Comment by elefeint** [comment]
You can use the [`container.entrypoint` property](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#custom-container-entrypoint) to an arbitrary script that both starts and pre-warms the container. [This StackOverflow answer](https://stackoverflow.com/a/69259214) describes the approach in more detail.

**Comment by company-myther** [comment]
Thank you very much for your help, but this script will not be executed during the packaging process.
