### ISSUE TITLE
Build local docker image

### ISSUE THREAD

**Issue by diory-coulibaly** [GoogleContainerTools/jib#3647]
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.8.0:dockerBuild (default-cli) on project demo: Tried to pull image manifest for registry-1.docker.io/library/openjdk:1.8 but failed because: manifest unknown | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new: 404 Not Found
[ERROR] GET https://registry-1.docker.io/v2/library/openjdk/manifests/1.8
[ERROR] {"errors":[{"code":"MANIFEST_UNKNOWN","message":"manifest unknown","detail":"unknown tag=1.8"}]}
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by emmileaf** [comment]
Closing as resolved, please re-open if needed.
