### ISSUE TITLE
Feature request: Verify Base-Image, Sign created Image

### ISSUE THREAD

**Issue by tb-38** [GoogleContainerTools/jib#3648]
**Description of the issue**:

It would be great if jib could verify a (signed) base image and if jib could signed the created image.

**Expected behavior**:

If we give jib a public key, jib should verify that the base image is signed accordingly. If not, the creation should fail.
If we give jib a private key, jib should sign the created image with the private key.

If this feature is out of scope - what would be best practice to have a secure workflow with e.g. [cosign](https://github.com/SigStore/cosign)? (Especially, how can I be sure, that the image is not modified between verifying by cosign and usage by jib?)

**Comment by zhumin8** [comment]
Thanks for filing this issue, we had some related discussions in #1544. 
As for now, Jib relies on the JRE's CA Certificates for validating registry's SSL certificates, more details [here](https://github.com/GoogleContainerTools/jib/blob/master/docs/self_sign_cert.md).
@mpeddada1 if you have more insights?

**Comment by zhumin8** [comment]
Closing as duplicate. Please use #1544 thread for further discussion.
