### ISSUE TITLE
Why does it default to "tcp" once it doesn't comply with string "udp" (in ignore case mode)?

### ISSUE THREAD

**Issue by slavino** [GoogleContainerTools/jib#3650]
https://github.com/GoogleContainerTools/jib/blob/20ba40a7e04f504cb827377e84542de04187f912/jib-build-plan/src/main/java/com/google/cloud/tools/jib/api/buildplan/Port.java#L58

**Comment by ddixit14** [comment]
Hi @slavino, this is more like a choice. It was an implementation detail to be explicit with the default protocol.
