### ISSUE TITLE
Tried to pull image manifest for registry-1.docker.io/library/adoptopenjdk:17.0.3-jdk but failed because: manifest unknown

### ISSUE THREAD

**Issue by samira-empire** [GoogleContainerTools/jib#3651]
when I'm trying to the jdk 17.0.3, I get this error:
Tried to pull image manifest for registry-1.docker.io/library/openjdk:17.0.3-jdk but failed because: manifest unknown

how can I get this image?
jib {
    from {
        image = "openjdk:17.0.3-jdk"
    }
...
it works for image "openjdk:17.0.2-jdk", but not for "openjdk:17.0.3-jdk"
thanks

**Comment by ddixit14** [comment]
Hi @samira-empire, looks like the image you are looking for does not exist in the docker-hub. 
Please have a look at [this](https://github.com/GoogleContainerTools/jib/issues/3647).
