### ISSUE TITLE
A way to disable IncompatibleBaseImageJavaVersionException

### ISSUE THREAD

**Issue by Vampire** [GoogleContainerTools/jib#3652]
**Environment**:

- *Jib version:* 3.2.1
- *Build tool:* Gradle 7.4.1
- *OS:* Windows / Linux

**Description of the issue**:

I have a project where I build a jlinked runtime and that needs fonts to draw text onto images, so it needs a base image with `fontconfig`.
I tried to use `debian:stable-slim` and `debian:stable` but they both don't have `fontconfig` included.
So I thought I use the smallest of the temuring images `8-jre` as it has fontconfig included and the Java version is irrelevant for the project as it has its own runtime.
But now Jib is yelling at me that it is incompatible.

**Expected behavior**:

A way to disable this warning as it does not apply here.

**Log output**: 

Your project is using Java 17 but the base image is for Java 8, perhaps you should configure a Java 17-compatible base image using the 'jib.from.image' parameter, or set targetCompatibility= 8 or below in your build configuration

**Comment by mpeddada1** [comment]
Hi @Vampire, thanks for the question! As the error message suggests, the base image being used (Java 8 based) is incompatible with your Java 17 project. Please try setting `jib.to.image` to a java 17 compatible image. This suggestion is helpful when troubleshooting the container image setup and avoiding accidentally running into issues like, `Exception in thread "main" java.lang.UnsupportedClassVersionError` when we run the container. Please see [this issue](https://github.com/GoogleContainerTools/jib/issues/1143) for more information on the decision.

**Comment by Vampire** [comment]
@mpeddada1 did you actually read my issue? The Java 8 image **is** compatible with my Java 17 project because I use an own jlinked JRE.

The error message is fine for the usual situation, but I'm asking for a way to disable that check, because I know better than Jib that the image is appropriate and the Java 8 image is much smaller than the Java 17 one.

**Comment by Vampire** [comment]
The only clean solution would be to not use Jib but a Dockerfile because it treats something that should be a warning or at least disableable as hard unconfigurable error.

It is great that Jib tries to prevent people from shooting their own feet, but please not for the price of reduced flexibility.

**Comment by Vampire** [comment]
The only clean solution would be to not use Jib but a Dockerfile because it treats something that should be a warning or at least disableable as hard unconfigurable error.

It is great that Jib tries to prevent people from shooting their own feet, but please not for the price of reduced flexibility.

**Comment by elefeint** [comment]
If fontconfig can't be added as a Java dependency and has to be installed through the system utilities, you may want to consider creating a custom image based on slim distributions and [using it in Jib as a base](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-need-to-run-commands-like-apt-get).

By the way, [here](https://github.com/AdoptOpenJDK/openjdk-docker/pull/224/files) is what adoptopenJDK did to add the fonts to their base images.

**Comment by Vampire** [comment]
Yes, I know, that's what I said.

But if I need a custom base image, where is the benefit of Jib?
I need to build a custom base image, I need to publish this custom base image, I need to manually maintain that custom base image, ...

It would be much easier and faster then to just use a conventional Dockerfile to build the image.
And all that just because a check that does not make sense everywhere but cannot be disabled.

**Comment by Vampire** [comment]
Yes, I know, that's what I said.

But if I need a custom base image, where is the benefit of Jib?
I need to build a custom base image, I need to publish this custom base image, I need to manually maintain that custom base image, ...

It would be much easier and faster then to just use a conventional Dockerfile to build the image.
And all that just because a check that does not make sense everywhere but cannot be disabled.

**Comment by Vampire** [comment]
Not really, still hoping you add this simple configuration option before I have to make that decision with a heavy heart. But it seems Jib is only intended for very narrow standard cases and not for flexibility. I also had to jump some other hoops before.

**Comment by elefeint** [comment]
Jib will not allow overriding of this option.
