### ISSUE TITLE
Container entrypoint set to [java, -cp, @/app/jib-classpath-file spend long time

### ISSUE THREAD

**Issue by jianchengwang** [GoogleContainerTools/jib#3653]
hello guys, I use `jib-maven-plugin` to build my springboot project, it works well, but `Container entrypoint set to [java, -cp, @/app/jib-classpath-file ` will lock and spend a long time, about 10minuter and more. so how to short this time.

**Comment by mpeddada1** [comment]
Hello @jianchengwan, when forming the entrypoint, Jib generates `@/app/jib-classpath-file` to allow for the generation of a deterministic classpath regardless of the host you're running your container on. The computation of the classpath (and presumably the time it takes) can vary from app to app, based on the dependencies they are using. Here is more information on the process if you're interested: [CHANGELOG](https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/CHANGELOG.md#changed-5) and [customer container entrypoint section in README](https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/README.md#custom-container-entrypoint). This is a new observation but we can keep this issue open in case we notice anything similar.

**Comment by zhumin8** [comment]
Closing as part of a clean up. Please reopen if this is still relevant.
