### ISSUE TITLE
Signed Manifest not supported

### ISSUE THREAD

**Issue by rinconjc** [GoogleContainerTools/jib#3657]
**Environment**: 
Any

- *Jib version:*  Latest
- *Build tool:* Gradle
- *OS:*  OSX

**Description of the issue**:

The `RegistryClient.pullManifest()` doesn't retrieve the `Signed Manifest` extra fields (`history`, `signature`)

**Expected behavior**:

The `RegistryClient.pullManifest(...)` should support the media type `application/vnd.docker.distribution.manifest.v1+prettyjws` and return the additional fields: `history` and `signature`

**Steps to reproduce**:

  1. Pull manifest of an image using signed manifest v 2.1 
  2. The retrieved manifest doesn't include the `history` and `signature`
 

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by mpeddada1** [comment]
Hi @rinconjc, thanks for filing this issue. We've had some conversations about this in the past, please take a look at  https://github.com/GoogleContainerTools/jib/issues/1544. Additionally, please check out ["Accessing a private docker registry with self-signed certificate"](https://github.com/GoogleContainerTools/jib/blob/master/docs/self_sign_cert.md#accessing-a-private-docker-registry-with-self-signed-certificate) for more information.

**Comment by zhumin8** [comment]
Closing as duplicate. Please use #1544 thread for further discussion.
