### ISSUE TITLE
Publish jib via SDKMAN!

### ISSUE THREAD

**Issue by helpermethod** [GoogleContainerTools/jib#3667]
**Environment**: MacOS, Windows, Linux

- *Jib version:* 0.10.0
- *Build tool*: Gradle 7.3.3
- *OS:* MacOS

**Description of the issue**:
Distribute jib via SDKMAN!

**Expected behavior**:
The jib CLI ZIP file has the correct structure to be distributed by SDKMAN!

![image](https://user-images.githubusercontent.com/1562019/168275262-5a375a8e-2049-4760-a151-288779562d46.png)

SDKMAN! is a popular tool for managing multiple versions of SDKs and CLI tools. jib would be a welcome addition!

**Additional Information**: 

The distribution can easily be automated using JReleaser (https://jreleaser.org/). This would also open up the possiblity to automatically distribute jib via other channels, like Homebrew and many more.

I wouldn't hesitate to do the PR myself :).

**Comment by elefeint** [comment]
The benefits I see are ease of installation/discoverability, and possibly simpler upgrades. @mpeddada1 What do you think?

**Comment by mpeddada1** [comment]
This sounds a like a really useful idea! I just have one quick question. I'm not too familiar with how SDKMAN manages versions, but would the new version of the CLI be available as soon as it is released on github? Or would it require any manual updates?

**Comment by helpermethod** [comment]
> This sounds like a really useful idea! I just have one quick question. I'm not too familiar with how SDKMAN manages versions, but would the new version of the CLI be available as soon as it is released on github? Or would it require any manual updates?

There are two options: One is performed manually and entirely community driven, i.e. if a new version is available someone has to manually perform a PR against our migrations repo.

The other option is using SDKMAN!s Vendor API. You can basically request a key, and by using the API or through some tools announce a new release on SDKMAN! in your CI pipeline.

**Comment by elefeint** [comment]
We'd be okay with adding the manual step as part of our release process, and seeing how it goes. It can be automated later.

**Comment by mpeddada1** [comment]
Thanks for proposing this! However, we're trying to focus on [bug fixes](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md) and platform evolution changes. After careful consideration, while it is a good idea, it's not something we can prioritize at this time (unfortunately). Closing as not planned.
