### ISSUE TITLE
[Question] Does jib support chunked layer (blob) uploading?

### ISSUE THREAD

**Issue by Rkuro** [GoogleContainerTools/jib#3683]
This is not an issue, just a question.  [In the docker registry HTTP spec they mention that you can do chunked blob uploads](https://docs.docker.com/registry/spec/api/#chunked-upload) in smaller PATCH requests and I'm trying to figure out whether jib supports this. 

Looking at the [BlobPusher](https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/registry/BlobPusher.java) class - it seems like it does use a PATCH request but I don't see any chunking mechanics being implemented inside of it which makes me think that jib does not currently support this.  There's also [this comment](https://github.com/GoogleContainerTools/jib/issues/2014#issuecomment-534154014) which also suggests that this is not a current feature but figured I'd ask in case I missed something.

**Environment**: N/A

- *Jib version:*  0.20.0
- *Build tool:* Gradle
- *OS:* RHEL7

**Comment by chanseokoh** [comment]
No, it's not implemented.

About a year ago, a Jib user (@sineaggi) [implemented and tested this feature](https://gitter.im/google/jib?at=6103096772c37b6f457e9754), which seemed working. However, the user realized that [GitHub doesn't support uploading chunks](https://gitter.im/google/jib?at=610981d2aedfa70f0d74410e) (presumably GitLab as well). The user [filed a bug](https://github.community/t/bug-api-patch-chunk-upload-to-ghcr-io-broken/193471) against them and stopped there. Definitely we didn't ever want to turn this feature on if it's going to break users who use a major registry like ghcr.io. But it sounds like they may fixed this recently.

**Comment by Rkuro** [comment]
I see - this is helpful and answers my question! Thank you @chanseokoh 🙏
