### ISSUE TITLE
Allow to specify multiple complete image names on CLI

### ISSUE THREAD

**Issue by penguineer** [GoogleContainerTools/jib#3685]
**Environment**: Debian Bullseye, GitHub Actions (Ubuntu latest)

- *Jib version:*  latest
- *Build tool:* Maven (3.8)
- *OS:* Linux

**Description of the issue**:

I would like to specify multiple complete image names (e.g. `user/tool:version`) on the command line. 
Currently it is possible to specify multiple tags via `-Djib.to.tags=`. However, tools for integration with GitHub Actions (e.g. [docker/metadata-action](https://github.com/docker/metadata-action)) seem to produce the complete image name, not the bare tags, so integration fails.

**Expected behavior**:

A CLI option such as `-Djib.to.images=user/tool:latest,user/tool:1.4.2` creates an image and tags it with `user/tool:latest`, `user/tool:1.4.2`.

Why not use the tags configuration in JIB? Sometimes the tags depend on the build environment (e.g.: building on main branch, ...) and/or cannot be determined by JIB.

**Comment by mpeddada1** [comment]
Hi @penguineer, is this what you're looking for: https://github.com/GoogleContainerTools/jib/blob/master/jib-maven-plugin/README.md#example? Especially note this particular configuration: 

```
<configuration>
  <from>
    <image>openjdk:alpine</image>
  </from>
  <to>
    <image>localhost:5000/my-image:built-with-jib</image>
    <credHelper>osxkeychain</credHelper>
    <tags>
      <tag>tag2</tag>
      <tag>latest</tag>
    </tags>
  </to>
```
It will push to `localhost:5000/my-image:built-with-jib`, `localhost:5000/my-image:tag2`, and `localhost:5000/my-image:latest`. We will be able to see the same behavior when we use system properties to specify `to.image` along with `to.tags`

**Comment by penguineer** [comment]
Thank you for the suggestion and quick answer!

I am aware of this option. However, this cannot be integrated with my CI workflow:
* I do not want to change the POM for release and tag decisions.
* The [action that decides which tags to create](https://github.com/docker/metadata-action) (based on: are we on the main branch? Is there a PR? Is there a release tag?) creates complete image names (i.e. `localhost:5000/image:tag`) instead of separated tags. 

My problem  is that I have two GitHub actions whose input/output are not compatible.

I have also posted an issue for the other tool: https://github.com/docker/metadata-action/issues/212. My hope is that I can  integrate JIB with my GitHub workflow and overall interoperability improves.

The workflow I tried to build is here: https://github.com/penguineer/CalMixer/blob/main/.github/workflows/docker-publish.yml
(Without the JIB part for now.)

**Comment by penguineer** [comment]
@elefeint The same argument could come from the other project, and they have a good point as they allow to state different image names and outputting tags only might be ambiguous or just wrong.

Is there a reason to keep image names and tags separated in JIB?
Is there a structural property that makes it impossible to input complete image names?

(I understand the convenience in the POM where multiple tag names can be put to an image name and repetitions are avoided, but I do not see why this is kept internally.)

**Comment by elefeint** [comment]
Tags are registry-agnostic. Host/Port ties to you a specific registry instance.

**Comment by elefeint** [comment]
It's only helpful when tags are not available as a separate piece of information, in which case it would serve as a workaround.

This isn't something we will be implementing, as it addresses a narrow scenario for which workarounds are already available.
