### ISSUE TITLE
Is it possible to Build Image for a certain Platform Architecture 

### ISSUE THREAD

**Issue by eldo26** [GoogleContainerTools/jib#3686]
**Environment**:

- *com.google.cloud.tools.jib:*  3.2.1
- Gradle 7.4.2
------------------------------------------------------------
JVM:          18.0.1.1 (Oracle Corporation 18.0.1.1+2-6)
OS:           Mac OS X 12.4 x86_64

**Description of the issue**:
Cant find any method to build image for a certain platform architecture 

**Steps to reproduce**:

**`jib-gradle-plugin` Configuration**: 
```groovy
jib.to {
  image = 'localhost:5000/nginx_new'
  platforms {
    platform {
      architecture = 's390x'
      os = 'linux'
    }
  }  
}
```

**Log output**: 
```
* What went wrong:
A problem occurred evaluating root project
> Could not find method platforms() for arguments [build_e470sv26omxhc01p0di2zc0og$_run_closure3$_closure6@2920b0ff] on object of type com.google.cloud.tools.jib.gradle.TargetImageParameters.
```

Additional info: 

Looking for similar features   with docker buildx 
Example 
```
docker buildx build --push --platform linux/arm/v7,linux/arm64/v8,linux/amd64

**Comment by eldo26** [comment]
@chanseokoh 
by `jib.from` we could select base image architecture. 
like wise, how we could set architecture for target image. (`jib.to`)

**Comment by chanseokoh** [comment]
The base image architecture determines what you build. For example, if you choose a Windows base image, you are building a Windows image. It's not possible that you can create a Linux image that can run on the Linux platform when you choose a Windows base image. If you build a Windows image, it can only run on the Windows platform.

**Comment by eldo26** [comment]
@chanseokoh  

- Docker Buildx  have a feature like,

When we invoke a build using `docker buildx`, we can set the `--platform flag` to specify the `target platform` for the build output, (for example, `linux/amd64`, `linux/arm64`, or `darwin/amd64` etc..).

When the current builder instance is backed by the docker-container driver, you can specify multiple platforms together. In this case, **it builds a manifest list which contains images for all specified architectures. When you use this image in docker run or docker service, Docker picks the correct image based on the node’s platform.**

Does Jib has any similar feature ?

**Comment by chanseokoh** [comment]
Yes. You specify multiple platforms under `jib.from`. It will create and push a manifest list containing all the specified architectures.

**Comment by cxie4** [comment]
Hi, I faced the similar issue here. 
Our java base image only supports `amd64` platform, I did the same thing like [this](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image). However when I built the image, it gave the below warning: 
`the configured platform (arm64/linux) doesn't match the platform (amd64/linux) of the base image. 
`
In this case, the image for `arm64/linux` platform hasn't been created? 
If so, is there any other way for us to build the image for `arm64/linux` platform besides changing the java base image to support the `arm64/linux`?

**Comment by eldo26** [comment]
If I bring in a new platform which is not in the manifest list of the base image, build is throwing an exception. 
```
jenkins/jenkins is a manifest list, but the list does not contain an image for architecture=amd64, os=windows.
```

****So** How we could add a new architecture into target image manifest.**

**Comment by cxie4** [comment]
Thanks for the detailed explanation, will change the base image and try again.

**Comment by eldo26** [comment]
@chanseokoh  
If we specify multiple platforms under  `jib.from`  and assume all of those platforms are available in source image manifest. 

what will be the action done by Jib. 

- It creates multiple images for all the platforms specified under `jib.from` and creates a manifest.
or 
- It only create one image with the architecture of node where jib runs on 
?

**Comment by chanseokoh** [comment]
> It creates multiple images for all the platforms specified under `jib.from` and creates a manifest.

This one. To be precise, it creates a manifest list. This is actually answered explicitly a couple times:

> You specify multiple platforms under `jib.from`. It will create and push a manifest list containing all the specified architectures.

> ... configure both arm64 and amd64, Jib will build both arm64 and amd64 images, create a manifest list pointing to those two built images, and upload the two images as well as the manifest list to the target registry

**Comment by eldo26** [comment]
ThankYou.. !

**Comment by eldo26** [comment]
It worked !! 👍 

@chanseokoh  much appreciate your support and guidelines. 


For reference attaching `build.gradle` and respective results. 

```
plugins {
  id 'java'
  id 'com.google.cloud.tools.jib' version '3.2.1'
}

repositories {
  mavenCentral()
}

jib.container.mainClass = 'nginx'
jib.allowInsecureRegistries = true
jib.from {
  image = 'nginx'
  auth {
    username = 'eldo26'
    password = '**************'
  }
  platforms {
    platform {
      architecture = 'amd64'
      os = 'linux'
    }
    platform {
      architecture = 'arm64'
      os = 'linux'
    }
    platform {
      architecture = 's390x'
      os = 'linux'
    }       
    platform {
      architecture = '386'
      os = 'linux'
    }      
  }
}


jib.container {
  environment = [
    'var1' : 'abc'
  ]
}

jib.to {
  image = 'eldo26/nginx_1:v2'
  auth {
    username = 'eldo26'
    password = '**************'
  }  
}
```

**Output indicates architectures available with the Image we build.** 
```
➜  nginx docker manifest inspect eldo26/nginx_1:v2 |jq '.manifests'
[
  {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 1395,
    "digest": "sha256:e961bf0158231f145599755ebfc619d5ce8546265dfceda78b3ec1236d294b04",
    "platform": {
      "architecture": "amd64",
      "os": "linux"
    }
  },
  {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 1395,
    "digest": "sha256:15570c5379c89eaadd9ee4b5a17bfff75a523097073cc79d5a9ae9a57387fe09",
    "platform": {
      "architecture": "arm64",
      "os": "linux"
    }
  },
  {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 1395,
    "digest": "sha256:c025c9d0185ba6054f2c364295a47ff2162e0b9fc3b99e63bad99caa89380fdc",
    "platform": {
      "architecture": "s390x",
      "os": "linux"
    }
  },
  {
    "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
    "size": 1395,
    "digest": "sha256:de30beba1eefc7780be2728dae88c4024cb9a7dbf485bbaf77cd3512c5394219",
    "platform": {
      "architecture": "386",
      "os": "linux"
    }
  }
]
➜  nginx
```

**Comment by OneCricketeer** [comment]
Wanted to share how I am doing this with the maven plugin in Github Actions

https://github.com/OneCricketeer/apache-kafka-connect-docker/blob/v3.2.3/.github/workflows/maven.yml
