### ISSUE TITLE
jib task throws java.lang.NoSuchMethodError when project has buildSrc module with custom plugin

### ISSUE THREAD

**Issue by MolodoyBoy** [GoogleContainerTools/jib#3702]
Hello, using jib plugin 3.2.1 version faced with next issue:

- Jib version: 3.2.1
- Build tool: Gradle
- OS: ubuntu

**Description of the issue**:
java.lang.NoSuchMethodError: 'java.util.stream.Collector com.google.common.collect.ImmutableList.toImmutableList() exception thrown when project has buildSrc module, after adding implementation "com.google.guava:guava:31.1-jre" to buildSrc/build.gradle problem is fixed, but I would like to know why there is such conflict.

**Steps to reproduce**:
1.Create project with buildSrc module.
2.Add build.gradle file to buildSrc 
apply plugin: "java"

repositories {
    mavenCentral()
}

sourceCompatibility = JavaVersion.VERSION_11
targetCompatibility = JavaVersion.VERSION_11

dependencies {

    implementation "org.testcontainers:postgresql:1.16.0"
    implementation "org.flywaydb:flyway-core:8.0.3"
    implementation "org.jooq:jooq:3.15.4"
    implementation "org.jooq:jooq-codegen-maven:3.15.4"
    implementation "org.postgresql:postgresql:42.2.14"
}

3.Add jib plugin to root build.gradle file.
4.Run jib task

**Comment by elefeint** [comment]
Please see [this FAQ entry](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-seeing-method-not-found-or-class-not-found-errors-when-building) for pointers.

If you are still having issues after this, could you create a minimum reproducible sample, and provide your Gradle version?

**Comment by MolodoyBoy** [comment]
@elefeint thanks for quick reply, i found out that was issue caused by transitive dependencies.

**Comment by elefeint** [comment]
Thanks!
