### ISSUE TITLE
Respect maven platform-based profiles

### ISSUE THREAD

**Issue by sanyarnd** [GoogleContainerTools/jib#3711]
**Environment**:

- *Jib version:*  3.2.1
- *Build tool:* maven
- *OS:* Windows

**Description of the issue**:

During OCI image build `maven-jib-plugin` detects and packs all .jar dependencies to a separate layer.
But for some reason it ignores [this kind of dependencies](https://github.com/hyperxpro/Brotli4j/blob/main/natives/pom.xml#L37-L99=).

This is a content of a final image.
![изображение](https://user-images.githubusercontent.com/6544384/180578258-ff68d3c0-90d9-4471-8827-2c32ce2a27fe.png)

As you can see, there's only an API dependency.

**Expected behavior**:
Both API and native implementation dependency is included.

**Steps to reproduce**:
  1. add brotli4j dependency
  2. build an image
  3. no platform-specific dependency available

**Comment by mpeddada1** [comment]
@sanyarnd to troubleshoot this further, can you try using the `mvn dependency:copy-dependencies` command to verify if a `.jar` file is created by maven for the dependency in question? If a `.jar` is created then jib should be able to use that to containerize it into the dependencies layer. Additionally, can you also try calling `mvn package jibDockerBuil` as described in this [issue comment](https://github.com/GoogleContainerTools/jib/issues/2901#issuecomment-736714473)?

**Comment by sanyarnd** [comment]
I tried to find the problem with the above commands, and indeed the problem is not in the JIB, but in the library.

Sorry for the false report, I'll notify the library author instead.
