### ISSUE TITLE
How do i resolve: jib not having access to dockerd on apple silicon?

### ISSUE THREAD

**Issue by nohallcaesars** [GoogleContainerTools/jib#3712]
everything works on intel, but not on apple silicon

throws
```sh
jibDockerBuild: Build to Docker daemon failed, perhaps you should make sure Docker is installed and you have correct privileges to run it
```

**Comment by elefeint** [comment]
Do you have Docker installed on the silicon machine?

**Comment by nohallcaesars** [comment]
Yes, using docker isnt the issue, its getting to jib to work with it

**Comment by elefeint** [comment]
Can you run `docker save`, `docker inspect` and `docker load` manually, with the same user/permissions that you use for Jib? Our team did not see issues when running Jib on M1 architecture. The most likely explanation is permissions (are you perhaps running docker commands with `sudo` but not jib commands?).

**Comment by emmileaf** [comment]
It could also be worth checking that sufficient permissions are granted to any programmatically or manually created files/folders that you may be using for credentials (`htpasswd` files, for example). 

In the case that permission changes do not resolve the problem, would you have a small code sample you could help provide us with for reproducing this issue?

**Comment by nohallcaesars** [comment]
@elefeint  @emmileaf 

Very likely a permissions issue. thanks for your help
