### ISSUE TITLE
'classes' dependency should be handled after project evaluation

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#374]
Currently if the java plugin is applied after the jib plugin, builds will fail due to error:
```
A problem occurred evaluating root project 'hello-gradle'.
> Failed to apply plugin [id 'com.google.cloud.tools.jib']
   > Task with path 'classes' not found in root project 'hello-gradle'.
```

**Comment by loosebazooka** [comment]
If we absolutely require the java plugin, we can apply in from within our own plugin first?

**Comment by coollog** [comment]
I think we can leave that to the user to apply. I just tried it with the kotlin plugin and it seems to work with the solution in #377.
