### ISSUE TITLE
I'm using JibCore, but how do I set the POD's time zone?

### ISSUE THREAD

**Issue by tiandizhiguai** [GoogleContainerTools/jib#3746]
If is dockerfile, add the following command：
`RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime`
`RUN echo 'Asia/Shanghai' >/etc/timezone`
but with jib core how do this？thx

**Comment by mpeddada1** [comment]
@tiandizhiguai one possibility I can think of is to mount a `/etc/localtime` file with the desired timezone onto the container. Jib-core has an [`addVolume`](https://www.javadoc.io/static/com.google.cloud.tools/jib-core/0.21.0/com/google/cloud/tools/jib/api/JibContainerBuilder.html) option for this purpose. There is also a `TZ` environment variable which can be used to set the timezone which is worth trying? (environment variables can be set through jib-core `addEnvironmentVariable`)

**Comment by tiandizhiguai** [comment]
@mpeddada1 I use addVolume method, like this:
`jibContainerBuilder.addVolume(AbsoluteUnixPath.fromPath(Paths.get("/etc/localtime")))`
the pod time is correct, many thx!

**Comment by KimDoubleB** [comment]
As @mpeddada1 explained above, it can also be set by adding the `TZ` environment variable.

For example, if you use gradle (kotlin dsl), 

```kotlin
from {
    image = "eclipse-temurin:17-jre"
}

to {
   ....
}

container {
    ....
    environment = mapOf(
        "TZ" to "Asia/Seoul"
    )
}
```
