### ISSUE TITLE
Many failing tests on Windows machines

### ISSUE THREAD

**Issue by Belair34** [GoogleContainerTools/jib#3781]
**Environment**:

- *Jib version:* jib-cli v0.11.0
- *Build tool:* Gradle wrapper included
- *OS:* Windows 10

**Description of the issue**:
Multiple failing integration tests seemingly due to running the tests on windows instead of Linux (ex: expecting "\n" but getting "\r\n") among some other types of failures. Using intelliJ Community IDE.

**Expected behavior**:
Integration tests all pass given no changes have been made since cloning the project. 

**Steps to reproduce**:
  1. Clone main branch on Windows 10 machine 
  2. Set up Java (using Temurin 11.0.16) 
  3. Open project in IntelliJ and ensure java version is correct
  4. Set system environment variable JIB_INTEGRATION_TESTING_LOCATION to localhost:9990
  5. run './gradlew clean goJF build integrationTest' in IntelliJ's gradle section

**Additional Information**:
We have been working on solving this issue by using system.lineSeparator() in more places, amending some docker commands, and even messing with our groovy version. Another notable thing is that cloning the repo in WSL can cause discrepancies between System.lineSeparator() and the line separators used in text files when running the tests in Windows.

**Comment by zhumin8** [comment]
Thanks for reporting. I wonder if this could be an IDE issue? For example, for "\n" vs "\r\n", you can configure in Intellij for which style you want ([Intellij configure line separators](https://www.jetbrains.com/help/idea/configuring-line-endings-and-line-separators.html)).
Alternatively, you could try to test without IDE. For context, we do have ci test that runs against Windows VMs regularly with no problem. Please followup is you still see issues this way.

**Comment by Belair34** [comment]
Thanks for the quick response! That seems like a good solution for the last thing I mentioned regarding WSL, however it doesn't seem to solve most of the "\n" vs "\r\n" issues because I believe the"\r\n" comes from something that is generated during the tests. For example, the StringWriter in this test ends up with "\r\n" at the end even though it is expecting "\n"
https://github.com/GoogleContainerTools/jib/blob/aca26b3191990095217ced424b4ca0c7a6acc0d2/jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/JarCommandTest.java#L69-L84
There is also another error: `Cannot run program "./gradlew" (in directory "C:\Users\User\AppData\Local\Temp\junit2372789025395354886\junit15493631909377854876"): CreateProcess error=2, The system cannot find the file specified` when running tests like the following: 
https://github.com/GoogleContainerTools/jib/blob/aca26b3191990095217ced424b4ca0c7a6acc0d2/jib-cli/src/integration-test/java/com/google/cloud/tools/jib/cli/WarCommandTest.java#L81-L105

Note that we don't necessarily want to build windows images with Jib, rather we want to develop and test Jib on windows machines. If it is determined to have any value, we may make a PR/draft of some changes we're coming up with to make this work.

**Comment by elefeint** [comment]
@Belair34 We don't support a development flow on Windows because nobody on the team uses Windows.
In general, development flows on Linux or MacOS (basically also *nix nowadays) are more common and better tested in open source projects.
