### ISSUE TITLE
v3.3.0 missing from https://plugins.gradle.org/m2

### ISSUE THREAD

**Issue by gabrieljones** [GoogleContainerTools/jib#3795]
**Environment**:

- *Jib version:* v3.3.0
- *Build tool:* Gradle 7.5.2
- *OS:* Mac OS

**Description of the issue**:
v3.3.0 missing from https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/

**Expected behavior**:
v3.3.0 is present in https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/

**`jib-gradle-plugin` Configuration**: 
```kts
plugins {
  id("com.google.cloud.tools.jib") version "3.3.0"
}
```

**Log output**: 
```log
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':build-plugins:generateExternalPluginSpecBuilders'.
> Could not resolve all files for configuration ':build-plugins:compileClasspath'.
   > Did not resolve 'gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:3.3.0' which is part of the dependency lock state
   > Could not find gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:3.3.0.
     Searched in the following locations:
       - https://corp-mirror.com/java-proxy/content/repositories/iq-gradle/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/3.3.0/jib-gradle-plugin-3.3.0.pom
     Required by:
         project :build-plugins
   > Could not find gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:3.3.0.
     Searched in the following locations:
       - https://corp-mirror.com/java-proxy/content/repositories/iq-gradle/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/3.3.0/jib-gradle-plugin-3.3.0.pom
     Required by:
         project :build-plugins
```

**Comment by elefeint** [comment]
@gabrieljones The issue is likely due to the "gradle.plugin" prefix seen in the output ` 'gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:3.3.0' ` -- we've upgraded the gradle publish plugin, so the prefix is no longer used.

Do you declare the dependency with the "gradle.plugin" somewhere? See [this thread](https://github.com/GoogleContainerTools/jib/issues/3719#issuecomment-1234595127) for more detail.

**Comment by gabrieljones** [comment]
> Do you declare the dependency with the "gradle.plugin" somewhere? See [this thread](https://github.com/GoogleContainerTools/jib/issues/3719#issuecomment-1234595127) for more detail.

Yes I do. Thanks for helping me fix this.

I had
```
  implementation("gradle.plugin.com.google.cloud.tools:jib-gradle-plugin:latest.release")
```
changing it to
```
  implementation("com.google.cloud.tools:jib-gradle-plugin:latest.release")
```
fixed the issue.

**Comment by elefeint** [comment]
Gradle's latest publish plugin moved the maven repo from `https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/` to to `https://plugins.gradle.org/m2/com/google/cloud/tools/jib-gradle-plugin/`
