### ISSUE TITLE
feature: allow pushing built images to multiple target registries

### ISSUE THREAD

**Issue by tnaroska** [GoogleContainerTools/jib#3808]
**Environment**:
- *Jib version:* jib-cli v0.11.0
- *Build tool:* jib-cli
- *OS:* N/A

**Description of the issue**:

Using jib-cli, we need to push our image build results into multiple docker registries (different cloud providers, etc). Currently jib-cli only takes one target repo URL. To push to multiple repos, we'd need to invoke jib multiple times. 

**Expected behavior**:

Ideally, we would like for jib to support multiple --target parameters. Jib would then build layer data once and push bits to all destinations in parallel.
Internally, Image should be built once and then uploaded to all target repos in parallel to achieve optimal build time.

**Workaround**:
Invoke jib-cli multiple times. Second and following builds of a target should come from cache mostly, which will cut down build times. The downside is that uploading to multiple repos will still be sequential where it could ideally happen in parallel.

**Comment by elefeint** [comment]
Sorry, this isn't something we are planning to support in Jib. Configuring authentication to a single registry already causes a lot of user issues; designing user-friendly support for multiple registry authentication is going to increase support burden disproportionately to the value added.

See #2299 for full discussion and examples of workaround flows others came up with.
