### ISSUE TITLE
why the tomcat-embed-core exception on NoSuchMethodError

### ISSUE THREAD

**Issue by auqf** [GoogleContainerTools/jib#3813]
![image](https://user-images.githubusercontent.com/8895540/196171954-1b6dddb5-5e83-4719-a74c-dc9ef5736e0e.png)

**Comment by elefeint** [comment]
Could you provide a reproducible sample application demonstrating the issue?

**Comment by emmileaf** [comment]
Guessing from what’s in the screenshot, could [this StackOverflow thread](https://stackoverflow.com/questions/54122724/spring-boot-java-lang-nosuchmethoderror-javax-servlet-http-httpservletrequest) be relevant to the error you are observing? If building with gradle, t[his section in Jib’s FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-seeing-method-not-found-or-class-not-found-errors-when-building) on version mismatch issues might also be helpful to look at for troubleshooting.

**Comment by auqf** [comment]
I cannot provide a demo application, And if I not use the  mavn jib to  build the image, directing  build the image by maven docker, and it's run normally. Or you can build a project by the version of my using to test. and the problem is with  the dependencs loading order  ?

**Comment by elefeint** [comment]
If you run the application locally, without containerizing it first, do you get the same error?

**Comment by auqf** [comment]
no, it's ok.

**Comment by elefeint** [comment]
Then the best avenue for investigation for you is @emmileaf 's suggestion of looking into your gradle build path.

**Comment by elefeint** [comment]
Closing this issue; please reopen if you can provide information on how to reproduce the issue.
