### ISSUE TITLE
multi-arch container image build support

### ISSUE THREAD

**Issue by Rajpratik71** [GoogleContainerTools/jib#3815]
Firstly, question is 

- does jib provides multi-arch container image build support ?
- 
- If yes how to enable / achieve it ?
- 
- Can we compose all arch image into single image ?
- 
- Do we need to any other configuration changes for application ?

**Comment by rquinio** [comment]
@Rajpratik71 Have you checked the FAQ entry https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image ?

**Comment by Rajpratik71** [comment]
> @Rajpratik71 Have you checked the FAQ entry https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image ?

thanks @rquinio  let me check and try https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-specify-a-platform-in-the-manifest-list-or-oci-index-of-a-base-image
