### ISSUE TITLE
Add aliases for Maven configuration.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#382]
From https://github.com/GoogleContainerTools/jib/issues/345#issuecomment-394828180

First, confirm if this actually enables IntelliJ quickdocs for nested configuration aliases.

**Comment by coollog** [comment]
Looks like adding aliases on nested configuration doesn't actually provide quickdocs either.

**Comment by patflynn** [comment]
@loosebazooka do you know what's going on here?  It looks like you made it work for the appengine plugins.

![screenshot from 2018-06-06 13-17-41](https://user-images.githubusercontent.com/7862557/41054361-25f2ce0c-698c-11e8-9e91-20d22ddee033.png)

**Comment by loosebazooka** [comment]
Appengine config is not actually nested. For job there's the option of
changing it back to flat if we need to. I was kinda hoping Maven support of
nested arguments would be better :/

**Comment by TadCordle** [comment]
Are we still doing this even though it doesn't fix the original problem? Or can we close this

**Comment by coollog** [comment]
I think we can still do this so that users could write their pom configuration even simpler like in the form of:

```xml
...
<configuration>
  <to.image>myimage</to.image>
</configuration>
...
```

**Comment by chanseokoh** [comment]
FTR, `<to.image>` in `<configuration>` isn't implemented. What works instead is `<jib.to.image>` under `<properties>`.
