### ISSUE TITLE
How to run arbitrary commands like `apt-get update`?

### ISSUE THREAD

**Issue by obarat** [GoogleContainerTools/jib#3820]
Hello, I'm using JIB to build my multi-architecture base image.  I'm following this [instructions](https://github.com/GoogleContainerTools/jib/issues/1261#issuecomment-440343575) and it is working well.  As part of the Dockerfile that I'm converting to JIB - using Maven, it was running the command `apt-get update`.  How can I run the same command with JIB?  Is it possible?

Thanks!

**Comment by zhumin8** [comment]
Hi, glad you found helpful instructions. 
Does this [FAQ section](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-need-to-run-commands-like-apt-get) help in your case?

**Comment by obarat** [comment]
Ah thanks for the link, I didn't see that before (I just searched in issues).  However that doesn't address the issue I have.  I want to use only JIB to build my base image, not a Dockerfile.  Is this not possible?

**Comment by sschuberth** [comment]
Chiming in here, no, this is not possible @obarat (to the best of my knowledge). JIB cannot run arbitrary commands as part of its image build process. Instead, you need to move those commands to a base image that you create otherwise, and make JIB use that base image.
