### ISSUE TITLE
Consider adding configuration for exposing ports.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#383]

**Comment by TadCordle** [comment]
I'm thinking the end-goal would be this for gradle:
```
jib {
  container {
    exposedPorts = ['1000', '2000-2010']
  }
}
```

For maven:
```
<configuration>
  <container>
    <exposedPorts>
      <exposedPort>1000</exposedPort>
      <exposedPort>2000-2003</exposedPort>
    </exposedPorts>
  </container>
</configuration>
```

Would be equivalent to adding this to a Dockerfile:
```
EXPOSE 1000
EXPOSE 2000-2003
```

We could name the parameters something differe ("expose" instead of "exposedPorts?")

**Comment by loosebazooka** [comment]
What's the interaction between this being configured on the container and someone exposing ports in their deployment configuration (kube yaml)?

**Comment by coollog** [comment]
I believe exposing the ports on the container would mean that it would not need to be exposed in the pod container definition in the kube yaml.

**Comment by coollog** [comment]
@TadCordle I think calling it `ports` would be fine since I don't think it will have any other connotation than meaning the ports to expose.
