### ISSUE TITLE
Gradle plugin: allow to build arbitrary images without java plugin

### ISSUE THREAD

**Issue by slamdev** [GoogleContainerTools/jib#3858]
**Description of the issue**:

When running jib tasks on a project without java plugin, tasks are failing with error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':tmp'.
> Could not find any convention object of type JavaPluginConvention.
```

Sample build.gradle:

```gradle
plugins {
    id 'base'
    id 'com.google.cloud.tools.jib'
}

jib {
    container.entrypoint = "/${project.name}"
    from.image = 'registry.hub.docker.com/library/alpine:3.16.2'
    extraDirectories {
        paths {
            path {
                from = 'build/dist'
                into '/'
            }
        }
        permissions = ["/${project.name}": '755']
    }
}
```

**Additional Information**: 

Current workaround is to add java plugin, but that adds a lot of unnecessary garbage to a non-java project.

**Comment by elefeint** [comment]
Well, JIB does stand for "Java Image Builder". It sounds like it might not be a suitable tool for your usecase.

**Comment by slamdev** [comment]
@elefeint true, but there is no better alternative :) 

also [jib-cli doesn't have this limitation](https://github.com/GoogleContainerTools/jib/tree/master/jib-cli#quickstart).

I think it can be a nice feature to offer because ppl are build go\node\etc applications via gradle and they need to containerize them :)

**Comment by elefeint** [comment]
Unfortunately, containerizing non-Java applications is not part of our team's charter -- buildpacks are a better fit for non-Java usecases. I am going to close this request as not planned.
