### ISSUE TITLE
extraDirectories setting is not honored for snapshot jars 

### ISSUE THREAD

**Issue by acappella2017** [GoogleContainerTools/jib#3868]
**Environment**:

- *Jib version:* 3.3.1
- *Build tool:* Maven
- *OS:* centos

**Description of the issue**:
We have extraDirectories in pom.xml to make sure all jar files in  **`opt/product/libs`** are packaged into a single layer. But we found that the SNAPSHOT jars in **`opt/product/libs`** are extracted to a separate layer.

We know that jib build the SNAPSHOT jars into a separate layers by default, but when we also add the extraDirectories, the files in extraDirectories should not be move to the separate layer.

BTW, we found that when jar files in lib folder are builded into 2 different layers,  the application shows significant performance downgrade...

<img width="460" alt="Screen Shot 2022-11-16 at 12 01 38 PM" src="https://user-images.githubusercontent.com/34084871/202080423-41e3d919-023e-4665-b973-96557972a3c9.png">

<img width="470" alt="Screen Shot 2022-11-16 at 12 01 32 PM" src="https://user-images.githubusercontent.com/34084871/202080429-50e70222-7bc3-4129-b9cc-c35eb4413d79.png">

**`jib-maven-plugin` Configuration**: 
```xml
<extraDirectories>
        <paths>
              <path>
                    <from>target/libs</from>
                    <into>/opt/product/libs</into>
             </path>
           </paths>
 </extraDirectories>
```

**Log output**: 

**Additional Information**:

**Comment by JoeWang1127** [comment]
Hi @acappella2017, if you want fine-grained layer control, try [Jib Layer-Filter Extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-maven).
