### ISSUE TITLE
Not reproducible between multiple OS (SHA256 of layer files difference in Windows and MacOS)

### ISSUE THREAD

**Issue by cuong0993** [GoogleContainerTools/jib#3874]
**Environment**:

- *Jib version: 3.3.1
- *Build tool: Gradle
- *OS: Windows and macOS

**Description of the issue**:
I am trying to use jib on both Windows and macOS.

I found that the same cache file has a different SHA256 in macOS from Windows.
For example, 2 attached files have the same content but different SHA256.
[windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz](https://github.com/GoogleContainerTools/jib/files/10076640/windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz)
[macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz](https://github.com/GoogleContainerTools/jib/files/10076646/macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz)

**Expected behavior**:
Have the same cache file digest between multiple OS.
Am  I missing some configurations or jib is not reproducible between multiple OS?

**Steps to reproduce**:

  1. Clone project https://github.com/cuong0993/test.
  2. Run jibBuildTar task.
  3. Check the build/jib-cache/layers folder.

**`jib-gradle-plugin` Configuration**: 
```groovy
    id("com.google.cloud.tools.jib") version "3.3.1"
```

**Log output**: 

**Additional Information**:

**Comment by zhumin8** [comment]
This [thread](https://github.com/GoogleContainerTools/jib/issues/2288#issuecomment-585430974) might be interesting to read, we have seen unexpected behavior on Windows.
But in general, we are not supporting a development workflow on Windows as explained [here](https://github.com/GoogleContainerTools/jib/issues/3781#issuecomment-1249375258). 
Please do let us know in case you are also observing discrepancies between MacOS and Linux.

**Comment by chanseokoh** [comment]
@zhumin8 that's misleading. That thread is about building a Windows image. AFAIK, the majority of Java developers are on Windows. People have been happily using Jib on Windows for years.

That said, generating different SHAs doesn't seem right if that's the case.

**Comment by chanseokoh** [comment]
Java code is portable and should be generating the same tar.gz on any platform. So, one possibility is that the Gradle runtime running Jib picked up a different version of some library on one platform. For example, I remember an [instance](https://github.com/GoogleContainerTools/jib/pull/3342#issuecomment-884538093) where `commons-compress` made a breaking change in that a newer version created a slightly different archive.

In any case, the SHA in the two filenames are the same, which means at least the uncompressed tars are the same:
```
windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz
macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz
```
Indeed, unzipping and diffing shows they are identical. The SHA also matches the filename.
```
$ gunzip macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz
$ gunzip windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz

$ # no output from diff, so looks good.
$ diff macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d

$ sha256sum macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d
af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d  macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d
af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d  windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d
```
OTOH, the compressed files are not idencial:
```
$ diff macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz 
Binary files macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz and windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz differ
 
$ diffoscope windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz 
--- windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz
+++ macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz
├── filetype from file(1)
│ @@ -1 +1 @@
│ -gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT)
│ +gzip compressed data

$ file macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz 
macos-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz: gzip compressed data, original size modulo 2^32 14515200
$ file windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz 
windows-af749e711711b96c75ab389fec9592018f57402d31b58398967d693336022c9d.gz: gzip compressed data, from FAT filesystem (MS-DOS, OS/2, NT), original size modulo 2^32 14515200
```

It may (or may not) just be the file metadata that's different. This is as far as I can get to.

**Comment by cuong0993** [comment]
Thanks guys for explainations.
