### ISSUE TITLE
Ignore Docker credentials when using local resources

### ISSUE THREAD

**Issue by 0x000bff** [GoogleContainerTools/jib#3875]
**Environment**:

- *Jib version:* 3.2.0
- *Build tool:*  Gradle 7.4.2
- *OS:* macOS 12.6

**Description of the issue**:
Jib fails complaining about Docker credentials when using local images.

**Expected behavior**:
I would expect to not need to authenticate to a Docker registry if I'm not pulling or pushing any images to/from a repository.

**Steps to reproduce**:

  1. Do not configure Docker credentials.
  2. Build project locally using jib.

**`jib-gradle-plugin` Configuration**: 
```groovy
...
tasks {
    jib {
        from {
            image = "openjdk:17"
        }
        to {
            image = "reporting-app"
            tags = ["latest-local"]
        }
        container {
            creationTime = 'USE_CURRENT_TIMESTAMP' //otherwise it defaults to 1970
        }
    }
}
...
```

**Log output**: 
```
> Configure project :
[native-image-plugin] Instrumenting task with the native-image-agent: e2e
[native-image-plugin] Instrumenting task with the native-image-agent: test
[native-image-plugin] Instrumenting task with the native-image-agent: e2eNativeImage
[native-image-plugin] Instrumenting task with the native-image-agent: testNativeImage

> Task :_skaffoldFailIfJibOutOfDate
> Task :compileJava UP-TO-DATE

> Task :buildInfo
generating build info properties...

> Task :processResources UP-TO-DATE
> Task :classes UP-TO-DATE

> Task :jib

Containerizing application to reporting-app:latest-local, reporting-app...
Base image 'openjdk:17' does not use a specific image digest - build may not be reproducible
Getting manifest for base image openjdk:17...
Building dependencies layer...
Building resources layer...
Building classes layer...
Building jvm arg files layer...
Using credentials from Docker config (/Users/connor/.docker/config.json) for reporting-app:latest-local
The base image requires auth. Trying again for openjdk:17...
Using credentials from Docker config (/Users/connor/.docker/config.json) for openjdk:17
Using base image with digest: sha256:528707081fdb9562eb819128a9f85ae7fe000e2fbaeaf9f87662e7b3f38cb7d8

> Task :jib FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jib'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed, perhaps you should make sure your credentials for 'registry-1.docker.io/library/reporting-app' are set up correctly. See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized for help

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
5 actionable tasks: 3 executed, 2 up-to-date
```

**Additional Information**: 
I'm running jib from Skaffold, but running jib directly gives the same behavior.

**Comment by emmileaf** [comment]
Could you help me understand what local images refer to in this scenario - would you be looking to build the image to a local container registry, docker daemon, or to disk?  

`jib` requires credentials to push/pull to/from container registries, but local options are available with `jibDockerBuild` ([building to docker daemon](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#build-to-docker-daemon)) or  `jibBuildTar` ([building to image tarball](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#build-an-image-tarball)) if these correspond to your use case.

**Comment by 0x000bff** [comment]
Hey sorry, `jibDockerBuild` works. Thanks!

I didn't realize Skaffold was using the regular `jib` command out of error because it couldn't detect the k8s cluster was local.
For anyone else running into this with Skaffold, my local context was aliased as "local" instead of the [expected](https://skaffold.dev/docs/environment/local-cluster/#auto-detection) "docker-desktop" or "minikube". Switching back to the "docker-desktop" context fixed.
