### ISSUE TITLE
Failing to run `jib-gradle-plugin` with "Unable to find method" "org.apache.commons.compress.compressors.CompressorStreamFactory.getSingleton()"

### ISSUE THREAD

**Issue by will-molloy** [GoogleContainerTools/jib#3883]
**Environment**:

- *Jib version:* 3.3.1
- *Build tool:* Gradle 7.6, Java 19 (also tried Gradle 7.3 with Java 17)
- *OS:* Windows

**Description of the issue**:
Running Jib fails at around ~60% with an error:
```
Unable to find method ''org.apache.commons.compress.compressors.CompressorStreamFactory org.apache.commons.compress.compressors.CompressorStreamFactory.getSingleton()''
'org.apache.commons.compress.compressors.CompressorStreamFactory org.apache.commons.compress.compressors.CompressorStreamFactory.getSingleton()'
```

**Expected behavior**:
Jib runs successfully

**Steps to reproduce**:

  1. Code here: https://github.com/will-molloy/auto-handbrake-encoding/pull/82
  2. Run `./gradlew jibDockerBuild` (or `./gradlew jib`)
  3. Build errors at ~60%

**`jib-gradle-plugin` Configuration**: 
```groovy
plugins {
  id 'com.google.cloud.tools.jib' version '3.3.1'
}

jib {
  to {
    image = "auto-handbrake-cfr:latest"
  }
  container {
    mainClass = 'com.willmolloy.handbrake.cfr.Main'
    args = ["/input", "/output", "/archive"]
    creationTime = "USE_CURRENT_TIMESTAMP"
  }
}
```

**Comment by emmileaf** [comment]
@will-molloy This issue looks similar to the one observed in #3794 - I also noticed the `net.rdrei.android.buildtimetracker` plugin noted in that issue used in your project, and think it might be pulling in an older version of of `org.apache.commons:commons-compress`. [This section in the FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#i-am-seeing-method-not-found-or-class-not-found-errors-when-building) might be of help working around this.

**Comment by will-molloy** [comment]
@emmileaf thank you! That was it.

I swapped `net.rdrei.android.buildtimetracker` with `org.asarkar.gradle:build-time-tracker`
