### ISSUE TITLE
'Val cannot be reassigned' when attempting to set container creationTime

### ISSUE THREAD

**Issue by lewimuchiri** [GoogleContainerTools/jib#3887]
**Environment**:

- *Jib version:* 3.3.1
- *Build tool:* Gradle (Kotlin) v7.6
- *OS:* Windows 11

**Description of the issue**:
Using Gradle Kotlin, I cannot set the value of `container.creationTime` because I get the error "Val cannot be reassigned". Gradle build also fails with the same error. Also, setting "USE_CURRENT_TIMESTAMP" as the value fails with a "Type Mismatch" error. See the two screenshots below

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1880626/206669667-aa2b6f0a-8449-4894-a6fe-5e5b3654adaa.png">

<img width="418" alt="image" src="https://user-images.githubusercontent.com/1880626/206670173-db3bec4b-73d4-4bfd-a012-794734a2a32e.png">

**Expected behavior**:
Successfully set creationTime and Gradle build should be successful

**`jib-gradle-plugin` Configuration**:
```kotlin
plugins {
    java
    id("org.springframework.boot") version "2.7.6"
    id("com.google.cloud.tools.jib") version "3.3.1"
}

jib {
    from {
        image = "eclipse-temurin:17-jre"
        platforms {
            platform {
                architecture = "amd64"
                os = "linux"
            }
            platform {
                architecture = "arm64"
                os = "linux"
            }
        }
    }
    to {
        image = "xxxx"
        tags = setOf(System.getenv("SHORT_SHA")?.toString() ?:"")
    }
    container {
        creationTime = "USE_CURRENT_TIMESTAMP"
        mainClass = "xxx"
        ports = listOf("8081")
        jvmFlags = listOf("-Xms512m", "-Xmx1024m")
    }
}
```

**Comment by mpeddada1** [comment]
@lewimuchiri  You may find this [suggestion](https://github.com/GoogleContainerTools/jib/issues/3791#issuecomment-1256231134) to be helpful since the `creationTime` has been updated to be a Gradle `Property`.

**Comment by lewimuchiri** [comment]
@mpeddada1 thank you. The suggestion works.

`creationTime.set("USE_CURRENT_TIMESTAMP")`
