### ISSUE TITLE
How to configure the timezone of docker image to be built by the jib plugin?

### ISSUE THREAD

**Issue by hittlle** [GoogleContainerTools/jib#3891]
Hi experts,
Could you please tell me how to configure the time zone of a docker image to be generated by the jib plugin? Thanks.

**Comment by JoeWang1127** [comment]
Hi @hittlle, there's a similar issue [here](https://github.com/GoogleContainerTools/jib/issues/3746). Could you check it out?

**Comment by meltsufin** [comment]
Please re-open if you still have this question.
