### ISSUE TITLE
Log info instead of warning when entrypoint is used

### ISSUE THREAD

**Issue by rmannibucau** [GoogleContainerTools/jib#3898]
Not sure why but on 3.3.0 a warning is issued when using entrypoint instead of mainclass (and other java friends):

```
[WARNING] mainClass, extraClasspath, jvmFlags, and expandClasspathDependencies are ignored when entrypoint is specified
```

Is it possible to lower the level (idea being warning -> requires attention, error -> fails). Here it does not require any intention since it is an explicit user action so it is intentional.

**Comment by rmannibucau** [comment]
Hi,
any news on this one? Would a PR help?

**Comment by ddixit14** [comment]
Hi @rmannibucau, feel free to contribute.

**Comment by rmannibucau** [comment]
Here it is https://github.com/GoogleContainerTools/jib/pull/3904 :)
