### ISSUE TITLE
How-Tos

### ISSUE THREAD

**Issue by kancharlamanikumar** [GoogleContainerTools/jib#3901]
<!--
I have 2 questions:

1. I have multi-module maven project, in that 2 folders are there (app-1 and app2) and while pushing the image i want to create image as imagereponame/app1 and imagerepo/app2

3. in app2 i have 2 application.properties and while building the image i want to create 2 images with 1 image with 1 application.properties and another image with another application.properties.

**Comment by ddixit14** [comment]
Looks like an empty issue. Closing this.
