### ISSUE TITLE
Is it possible to build an image with a provided and already packaged war

### ISSUE THREAD

**Issue by CharlelieBouvier** [GoogleContainerTools/jib#3906]
Dear community,

I'm not the owner of the app sources, I pay a license and get 2 already packaged war and one spring boot jar. 
Is JIB the right tool to easy put those apps in a docker image, or should I simply write a Dockerfile?

If JIB is the right tool, do you have any example or insights please?

NOTE : I'd like to use jib gradle plugin

Regards,
Charlélie Bouvier

**Comment by ddixit14** [comment]
Hey, you can refer to the following documentation:
1. [I want to containerize a jar](https://github.com/GoogleContainerTools/jib/blob/9705c58e8dabcd851f9d53340f0771666698e601/docs/faq.md#i-want-to-containerize-a-jar)
2. [How does the war command work](https://github.com/GoogleContainerTools/jib/blob/9705c58e8dabcd851f9d53340f0771666698e601/docs/faq.md#how-does-the-war-command-work)

Let us know if you have any other questions. Thank you.
