### ISSUE TITLE
When adding some files to the image, There're exec permission issues.

### ISSUE THREAD

**Issue by zzerjae** [GoogleContainerTools/jib#3913]
**Environment**:

- *Jib version:*  3.3.1
- *Build tool:*  gradle with Kotlin DSL v7.6
- *OS:*  M1 mac

**Description of the issue**:
I am trying to deploy a grpc service running on Kubernetes via jib. 
Since the version of our k8s cluster is less than [1.24](https://kubernetes.io/blog/2022/05/13/grpc-probes-now-in-beta/), we try a health check using the [grpc_health_probe](https://github.com/grpc-ecosystem/grpc-health-probe) binary.
At this time, exec permission of /bin/grpc_health_probe is required, but this exec is denied.
This is because in 3.3.0 or later, setting permission on extraDirectories directly is no longer possible. I'm trying to use JibOwnershipExtension, but even with the settings below, the healthcheck daemon doesn't seem to get the proper exec permission.

**Expected behavior**:
I hope /bin/grpc_health_probe has permissions set so that anyone can run it.

**`jib-gradle-plugin` Configuration**: 
```kotlin
configure<JibExtension> {

    extraDirectories {
        setPaths(files("../agents"))
    }

    pluginExtensions {
        pluginExtension {
            implementation = "com.google.cloud.tools.jib.gradle.extension.ownership.JibOwnershipExtension"
            configuration(Action<com.google.cloud.tools.jib.gradle.extension.ownership.Configuration> {
                rules {
                    rule {
                        glob = "/bin/grpc_health_probe"
                        ownership = "0"
                    }
                }
            })
        }
    }


    from {
        image = "eclipse-temurin:19.0.1_10-jre-alpine"
    }

...
```

**Log output**: 

**Additional Information**:

**Comment by emmileaf** [comment]
@zzerjae Would the discussion in #3791 on setting `extradirectories.permissions` in Kotlin DSL be helpful for your use case here?

**Comment by zzerjae** [comment]
Hello @emmileaf.
it was worked for me. 
I realize my shortcomings. Kotlin is powerful, but subtle syntax differences with Java can confuse beginners from non-jvm world.
thank you.
