### ISSUE TITLE
jib.skip is ignored with false value 

### ISSUE THREAD

**Issue by foal** [GoogleContainerTools/jib#3917]
**Environment**:

- *Jib version:* 3.3.1
- *Build tool:* Maven 3.8.6
- *OS:* Win/Linux 

**Description of the issue**:
Parent project has set skip parameter to true `<skip>true</skip>`. for legacy projects we need to enable the plugin from command line with `-Djib.skip=false` but the parameter is ignored and module not processed.

**Expected behavior**:
JIB will process the module.

**Steps to reproduce**:

  1. Disable JIB in the parent pom 
  2. No configuration in the module POM
  3. run the jib:build for the module with `mvn jib:build -pl=m1-read -Djib.skip=false -Dimage=quay.lx/dep/m1-read:1.0.0-SNAPSHOT-20230124T194118-9b5f7f7`

**Log output**: 
```
+ mvn jib:build -pl=m1-read -Djib.skip=false -Djib.alwaysCacheBaseImage=true -Dimage=quay.lx/dep/m1-read:1.0.0-SNAPSHOT-20230124T194118-9b5f7f7 -Djib.container.labels=quay.expires-after=10d

[INFO] Scanning for projects...

[INFO] 

[INFO] ----------------< depr:m1-read >-----------------

[INFO] Building m1-read 1.0.0-SNAPSHOT

[INFO] --------------------------------[ jar ]---------------------------------

[INFO] 

[INFO] --- jib-maven-plugin:3.3.1:build (default-cli) @ m1-read ---

[INFO] Skipping containerization because jib-maven-plugin: skip = true

[INFO] ------------------------------------------------------------------------

[INFO] BUILD SUCCESS
```

**Comment by diegomarquezp** [comment]
Hi @foal, thanks for reporting this. Would you mind sharing a minimal version of the parent and child pom producing this issue?
Also, please consider reaching out to our [support hub](https://cloud.google.com/support-hub) if you have a support plan for faster response times

**Comment by slawekjaranowski** [comment]
There is no jib issue.

It is standard Maven way, when you literally configure parameter of plugin  it cannot be overridden by user properties.

So, when you configure plugin like:

```
<plugin>
   <configuration>
     <skip>true</skip>
   </configuration>
</plugin>
```
There is no way to pass new value from user properties, skip has constant value.

you should do it in such way:

```
<properties>
  <!-- default value -->
  <jib.skip>true</jib.skip>
</properties>

...
<plugin>
  <configuration>
   <!-- use property, which can be overrided -->
   <skip>${jib.skip}</skip>
  </configuration>
</plugin>
```


`jib.skip` looks like default property name used by plugin so, you not need to configure such property for plugin any way. 

Only `<properties>...</properties>` with your default value should be enough, can be in root pom of your project.

**Comment by blakeli0** [comment]
Thanks @slawekjaranowski for the response! Closing as completed.
