### ISSUE TITLE
Replace deprecated `set-output` command with environment file

### ISSUE THREAD

**Issue by jongwooo** [GoogleContainerTools/jib#3920]
## Description

In workflow, `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

**Comment by lqiu96** [comment]
Thanks for bringing this to our attention. We'll review your PR.
