### ISSUE TITLE
mainClass and jvmFlags cannot be set lazily on JibExtension in the Gradle plugin

### ISSUE THREAD

**Issue by erdi** [GoogleContainerTools/jib#3927]
While many properties on `JibExtension` utilise [lazy configuration APIs](https://docs.gradle.org/current/userguide/lazy_configuration.html), including some of the more complex ones like `labels`, there are some, including `mainClass` and `jvmFlags`, that do not. This forces users of the plugin to have to resort to using `Project.afterEvaluate()` in certain scenarios.

Would you be willing to accept a PR if I addressed that?

**Comment by lqiu96** [comment]
Hi @erdi. Thanks for bringing this up! We do welcome contributions to jib (https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md) and we'll gladly review any incoming PRs.

@emmileaf FYI as you may have more context regarding this.

**Comment by emmileaf** [comment]
Yes, enabling lazy evaluation for more of jib-gradle-plugin’s properties is something we would welcome help from the community on. @erdi As you’ve mentioned, this was previously done for a number of properties such as `labels` (#3094) and `creationTime` (#3709), feel free to refer to these discussions and follow a similar approach. Thank you!

**Comment by erdi** [comment]
Thanks for the pointers to related issues/PRs, @emmileaf, they will definitely come handy. Let me see what I can do about this.

**Comment by wakingrufus** [comment]
@emmileaf i have opened an additional PR to make entrypoint lazy  https://github.com/GoogleContainerTools/jib/pull/4003

**Comment by emmileaf** [comment]
Hi @wakingrufus, would you mind opening a separate issue to track this feature request and your implementation? I think this issue can be closed with https://github.com/GoogleContainerTools/jib/pull/3936 already merged and released. Thanks!
