### ISSUE TITLE
[Customization][Question] Jib:build forces user to use local docker daemon.

### ISSUE THREAD

**Issue by happyfeetw** [GoogleContainerTools/jib#3934]
I'm using jib:build(v3.2.1) goal to build my project, and now I need to specify a commonly used server as docker daemon instead of using local docker daemon. But it seems that currently jib:build fixed all steps from building images to pushing to registry. And I've got from jib docs that jib:dockerBuild can specify a remote docker daemon, but it won't push the image to registry.

So is there any way to approach my goal?

Thanks!

**Comment by happyfeetw** [comment]
To be specific, my goal is to have a way to let me specify a remote docker daemon in build flow like jib:build and leave other steps just the same. :)

**Comment by chanseokoh** [comment]
Neither jib:build nor jib:dockerBuild uses a Docker daemon to *build* an image. Jib can build an image even if you don't have Docker. It is just that jib: dockerBuild loads a built image to a Docker daemon instead of a registry.

**Comment by happyfeetw** [comment]
> 

Thanks for your answer. Maybe I misunderstood the concept and process of building a docker image. So if it is true that jib only builds an image where jib:build or jib:dockerBuild runs?

**Comment by chanseokoh** [comment]
Not sure if I understand your question. Anyways, the only difference of jib:build and jib:dockerBuild is where a built image ends up living: a container registry (local or remote) or a Docker daemon (local or remote). And Jib can run on any machine where there is Java.

**Comment by happyfeetw** [comment]
> 

Understood. My question is how jib builds an image. Based on [https://cloudplatform.googleblog.com/2018/07/introducing-jib-build-java-docker-images-better.html](url), docker assembles building information in a context and send this context to a docker daemon(remote or local), and that docker daemon actually builds the image; But for jib, this blog doesn't show much about details, which i want to learn more about.

The fact is that my team is working to slim as much as possible to slim our images among plenty of services, and some services use spotify maven docker plugins to manually build their images by layer, and i decided to do it with jib. The problem encountered is when i run jib:build in my local development environment, it builds with a sha string, but when it runs in remote building server, sha changes. And I'm looking forward to find a way to solve it.

That leads me to looking into jib's build steps and its details and see if there's a solution.

**Comment by chanseokoh** [comment]
As to how Jib builds an image, take a look at https://stackoverflow.com/questions/64104769/how-does-the-jib-maven-plugin-build-images-without-using-a-docker-daemon

BTW, the spotify plugin simply runs Docker to build an image.

**Comment by happyfeetw** [comment]
> 

Thanks for your patience. I build my image with the <creationTime> label in pom.xml and the value is set to "USE_CURRENT_TIMESTAMP". Is that the probable reason I got different image SHA result?

**Comment by chanseokoh** [comment]
Yes, that is the reason.

**Comment by happyfeetw** [comment]
> 

Ok, is there any method to avoid this? I mean to save the right timestamp while building the exact same image between multiple builds among different linux servers.

**Comment by chanseokoh** [comment]
No. Please take a look at this [FAQ](https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#why-is-my-image-created-48-years-ago).

**Comment by chanseokoh** [comment]
Some people use a fixed timestamp like a git commit timestamp of a source repo.

**Comment by happyfeetw** [comment]
> stamp of a source repo.

Thank you very much, I'll take a look. :)

**Comment by happyfeetw** [comment]
And one more question, With  `<creationTime>` set to `USE_CURRENT_TIMESTAMP`, will all layers' SHA and image SHA change even if there's no change in code, or only SHAs of layers correspond to changed code and image SHA changes?

**Comment by happyfeetw** [comment]
So basically if I set `<creationTime>` to `USE_CURRENT_TIMESTAMP`, with no changes in my project source code, and no matter which linux server runs jib, only the image SHA will change as a result, right?
And as expected, in this situation ( `<creationTime>` is set to `USE_CURRENT_TIMESTAMP`), when I change some source code, maven dependencies or config files inside project and runs jib several times in different linux servers, it is only the correspond layers' SHA and the whole image's SHA changes.
Is this a correct comprehension?

**Comment by chanseokoh** [comment]
Yes.

**Comment by happyfeetw** [comment]
> Yes.

Thx, and one last question: how on earth did jib build an image without runing docker like spotify plugin? 
Or any blog or docs for details besides source code?

**Comment by chanseokoh** [comment]
I guess you missed my [previous comment](https://github.com/GoogleContainerTools/jib/issues/3934#issuecomment-1439980626)?

**Comment by happyfeetw** [comment]
> I guess you missed my [previous comment](https://github.com/GoogleContainerTools/jib/issues/3934#issuecomment-1439980626)?

Sorry I'll check :)

**Comment by alicejli** [comment]
Closing as this appears to have been resolved.
