### ISSUE TITLE
jib插件使用

### ISSUE THREAD

**Issue by Ycm19970520** [GoogleContainerTools/jib#3937]
您好，JIB插件可以在前端使用吗？

**Comment by mpeddada1** [comment]
From Google Translate: `Can jib plugins be used in the front end?`

@Ycm19970520 Thanks for the question! Please correct me if I'm not interpreting the ask correctly, are you asking if jib can package front end applications? If so then yes, jib can be used with front end applications. However, please note that Jib is mainly used for building Docker and OCI images for Java applications. Jib can be used in several ways (as a maven plugin, gradle plugin, Java library or from the CLI). You may find this page to be helpful in getting started: https://github.com/GoogleContainerTools/jib#what-is-jib

**Comment by alicejli** [comment]
Closing as this has been answered.
