### ISSUE TITLE
Issue setting up profiler with Maven Jib

### ISSUE THREAD

**Issue by thakurmiti** [GoogleContainerTools/jib#3951]
Hello Team,
I'm currently using maven jib in my current project and it's working fine. But now I wanted to implement a profiler to tackle heap memory-related issues. As to the setup profiler, we need to make sure the profiler agent is there in the container image and we just need to add the agent path between the jar command. e.g.  -agentpath:INSTALL_DIR/profiler_java_agent.so=OPTION1,OPTION2,OPTION3.

https://cloud.google.com/profiler/docs/profiling-java#gke

As we are using jib maven, I'm adding the profiler agent in the base jib image but I'm not able to locate the jar file that jib used to create after building the project. I tried adding the agent command via entrypoint and args section but it's not working. I'm unable to find any info related to how jib creates the jar file and how we can add any arguments with it.

It will be really helpful if you can help with this.

**Comment by thakurmiti** [comment]
Update I could see that jib maven add entrypoint as [java, -cp, @/app/jib-classpath-file, javafilename]. But it's still not working if I add agent path in it, in pom file.

**Comment by jingwenyang2023** [comment]
same problem here, would love to see the progress!

**Comment by jingwenyang2023** [comment]
> same problem here, would love to see the progress! the docker image built successfully but when launching container it fails with the following errors...

![image](https://user-images.githubusercontent.com/124350974/224809533-c54b6812-ac26-4992-9779-ba18aa6cb30e.png)
