### ISSUE TITLE
publish jib-core

### ISSUE THREAD

**Issue by schmitch** [GoogleContainerTools/jib#397]
hello I stumbled upon jib and was looking to try build something for sbt on top of jib. Would it be possible to publish `jib-core` to maven central so that people can build plugins for other jvm build tools?

**Comment by schmitch** [comment]
I also created a "demo" plugin of jib, here: https://github.com/schmitch/sbt-jib I use a git submodule to pull jib, however it's a little bit flaky since I need to patch some sources, else zinc/scala compiler is not happy.

**Comment by loosebazooka** [comment]
Hi @schmitch, though we don't have a specific timeline for this, it is in our roadmap for jib.

**Comment by TadCordle** [comment]
Yup, should be happening eventually. I'm going to close this since we already have an issue open for making a jib class library here: https://github.com/GoogleContainerTools/jib/issues/337
