### ISSUE TITLE
Multi-module project has external dependency to jib-build-plan

### ISSUE THREAD

**Issue by rquinio** [GoogleContainerTools/jib#3973]
I initially had trouble to build master locally when doing changes in jib-build-plan and jib-core, and didn't see this mentioned in CONTRIBUTING.md

I had to change the hardcoded version
https://github.com/GoogleContainerTools/jib/blob/d6f10241f7c383ffb764cbbd20ac82f5dd7c97ea/jib-core/build.gradle#L16

into a relative multi-module dependency:

```
api project(':jib-build-plan')
```

and then comment the ```ensureNoProjectDependencies()``` in jib-maven-plugin / jib-gradle-plugin.

I imagine this is linked to the releasing process, but it's surprising the multi-module project doesn't behave like one.

**Comment by blakeli0** [comment]
Thanks @rquinio for reporting this. However, the current build structure is by design and we don't plan to change it any time soon.
