### ISSUE TITLE
Digest calculation wrong for chainguard image base layer

### ISSUE THREAD

**Issue by patrickpichler** [GoogleContainerTools/jib#3982]
**Environment**:

- *Jib version:* 3.3.1
- *Build tool:* Gradle 8.0.2
- *OS:* Linux

**Description of the issue**:
When using chainguard images as base image, the resulting image is not valid. 

**Expected behavior**:
Valid image with chainguard base image.

**Steps to reproduce**:

  1. Use `cgr.dev/chainguard/jre:openjdk-17@sha256:44f2d2c9f26b0f5c6c4c42bfc25ee86f8922cc653134013f03f16e6d77e60278` as base image 
  2. Run `jibDockerBuild` gradle task
 
The command will fail with:
```
Execution failed for task ':jibDockerBuild'.
> com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: 'docker load' command failed with error: invalid diffID for layer 0: expected "sha256:ee8995e709b214acee4a776c152b4dfa67ea682295af300c0b18af2077630583", got "sha256:63216462371853219552197170f73ba4f80c7be34c24192867b845710c630e48"
```

**`jib-gradle-plugin` Configuration**: 
```groovy
jib {
    from {
        image = 'cgr.dev/chainguard/jre:openjdk-17@sha256:44f2d2c9f26b0f5c6c4c42bfc25ee86f8922cc653134013f03f16e6d77e60278'
   }
}
```

**Additional Information**: 
I trace down the issue to be caused by `com.google.cloud.tools.jib.cache.CacheStorageWriter#getDiffIdByDecompressingFile` [1]. 
For whatever reason the `CompressedInputStream` only delivers `1MB` of data and then closes.

I copied the temporary compressed layer created and when I use `cat tmp.layer | gunzip | sha256sum` it produces the correct 
checksum.

[1] https://github.com/GoogleContainerTools/jib/blob/eeefd4fddf6b9a023afbe7f4c54375da075f5b77/jib-core/src/main/java/com/google/cloud/tools/jib/cache/CacheStorageWriter.java#L164

**Comment by emmileaf** [comment]
@patrickpichler Thanks for the investigation and fix!
