### ISSUE TITLE
Gradle: Property "container.labels" does not respect "convention" values

### ISSUE THREAD

**Issue by ChristianCiach** [GoogleContainerTools/jib#3986]
**Environment**:

- *Jib version:* 3.3.1
- *Build tool:* Gradle 8.1
- *OS:* Fedora Workstation 37

**Description of the issue**:

I am trying to set convention-values to the Gradle MapProperty `jib.container.labels` from within my Gradle Init-Script. Unfortunately, this doesn't work, because the MapProperty is explicitly initialized with `.empty()` by the Jib plugin, overriding any convention values of property.

https://github.com/GoogleContainerTools/jib/blob/9f2d0ba16dfb02eece1b40f55c6e2f1c42c7e178/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/ContainerParameters.java#L61

I've prepared a commit to fix this, but the PR-template advises me to create an issue first. My fix: https://github.com/ChristianCiach/jib/commit/7b6f5b5e0e2c6ab54e4c78c6bfad6e31b209d1d3 

**Expected behavior**:

Convention-values should be respected.

**Steps to reproduce**:
  1. Set `jib.container.labels.convention(['a': 'b'])` in your gradle script.
  2. Do not explicitly set `jib.container.labels` to any value.
  3. No labels in generated image :(
 

**`jib-gradle-plugin` Configuration**:
```groovy
jib {
    configurationName = SpringBootPlugin.PRODUCTION_RUNTIME_CLASSPATH_CONFIGURATION_NAME
    from {
        image = 'company-internal-image:latest'
    }
    container {
        mainClass = project.mainClassName
        ports = ['8080']
        creationTime = 'USE_CURRENT_TIMESTAMP'
    }
}

```

Relevant part of my init-script:

```groovy
void configureJib(Project p) {
    p.pluginManager.withPlugin('com.google.cloud.tools.jib') { jibPlugin ->
        def defaultLabels = getConventionContainerLabels()

        // "jib" is the name of the project extension applied by the jib plugin.
        // See: com.google.cloud.tools.jib.gradle.JibPlugin.JIB_EXTENSION_NAME
        p.extensions.configure("jib") { jib ->
            jib.container.labels.convention(defaultLabels)
        }
    }
}
```

**Comment by ChristianCiach** [comment]
I just notice that the class `ContainerParameters` is very inconsistent about its return values. `getLabels()` is the only Method in that class that directly returns the underlying `MapProperty`. The other `@Input` methods do not expose the gradle properties, like `String getMainClass()` and `List<String> getJvmFlags()`. That's a bummer, because I actually do want to set convention-values for `jvmFlags` from within my gradle-init-script, but the getter method does not expose the underlying `ListProperty`, so I cannot call `convention(..)` on it.

**Comment by ChristianCiach** [comment]
Actually, I think Jib should not try to hide the `ListProperty` and `MapProperty` input-variables from the users. `getLabels()` has successfully been converted from `Map` to `MapProperty` in the past. I don't know if this is a breaking change, but I think the other `@Input`-methods should also directly return the underlying `*Property` objects. This is how the Gradle documentation says it should be done.

**Comment by diegomarquezp** [comment]
Hi @ChristianCiach, thanks for bringing this up. Since we are accepting contributions, the best way to determine if your suggestion is non-breaking is by running tests on a PR, so feel free to go ahead with it!

cc'ing @emmileaf and @mpeddada1 - you may have more info on this

**Comment by blakeli0** [comment]
[Convention values ](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/Convention.html)are deprecated in Gradle 8.6, closing as not planned.

**Comment by ChristianCiach** [comment]
@blakeli0 The deprecated Convention interface that you linked has absolutely nothing to do with the `Property.convention(..)` values that this issue is all about. See https://docs.gradle.org/current/javadoc/org/gradle/api/provider/Property.html#convention-T-

These are not deprecated and this issue is still valid.
