### ISSUE TITLE
Maven 3.9.2 - Plugin issues

### ISSUE THREAD

**Issue by slawekjaranowski** [GoogleContainerTools/jib#4019]
**Environment**:

- *Jib version:* 3.3.1 
- *Build tool:* Maven 3.9.2
- *OS:* macOS

**Description of the issue**:

Maven 3.9.2 reports issues in plugin:

```
[WARNING]  * com.google.cloud.tools:jib-maven-plugin:3.3.1
..
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-resolver-provider:3.8.6, org.apache.maven:maven-settings-builder:3.8.6, org.apache.maven:maven-repository-metadata:3.8.6, org.apache.maven:maven-artifact:3.8.6, org.apache.maven:maven-core:3.8.6, org.apache.maven:maven-plugin-api:3.8.6, org.apache.maven:maven-model-builder:3.8.6, org.apache.maven:maven-model:3.8.6, org.apache.maven:maven-builder-support:3.8.6, org.apache.maven:maven-settings:3.8.6]

```

**Expected behavior**:

no reported issues

**Steps to reproduce**:

  1. build project with jib-maven-plugin by Maven 3.9.2

**Comment by HanselCream** [comment]
[WARNING]
[WARNING] Plugin validation issues were detected in 2 plugin(s)
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-compiler-plugin:3.8.1
[WARNING]   Declared at location(s):
[WARNING]    * org.example:POM_Session:1.0-SNAPSHOT (pom.xml) @ line 78
[WARNING]   Used in module(s):
[WARNING]    * org.example:POM_Session:1.0-SNAPSHOT (pom.xml)
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin should declare these Maven artifacts in `provided` scope: [org.apache.maven:maven-settings-builder:3.0, org.apache.maven:maven-repository-metadata:3.0, org.apache.maven:maven-artifact:3.0, org.apache.maven:maven-plugin-api:3.0, org.apache.maven:maven-settings:3.0, org.apache.maven:maven-aether-provider:3.0, org.apache.maven:maven-model:3.0, org.apache.maven:maven-core:3.0, org.apache.maven:maven-model-builder:3.0]
[WARNING]
[WARNING]  * org.apache.maven.plugins:maven-resources-plugin:3.3.0
[WARNING]   Declared at location(s):
[WARNING]    * org.apache.maven:maven-core:3.9.2:default-lifecycle-bindings @ line -1
[WARNING]   Used in module(s):
[WARNING]    * org.example:POM_Session:1.0-SNAPSHOT (pom.xml)
[WARNING]   Mojo issue(s):
[WARNING]    * Mojo resources:resources (org.apache.maven.plugins.resources.ResourcesMojo)
[WARNING]      - Implements `Contextualizable` interface from Plexus Container, which is EOL.
[WARNING]    * Mojo resources:testResources (org.apache.maven.plugins.resources.TestResourcesMojo)
[WARNING]      - Implements `Contextualizable` interface from Plexus Container, which is EOL.
[WARNING]
[WARNING]
[WARNING] Fix reported issues by adjusting plugin configuration or by upgrading above listed plugins. If no upgrade available, please notify plugin maintainers about reported issues.
[WARNING] For more or less details, use 'maven.plugin.validation' property with one of the values (case insensitive): [BRIEF, DEFAULT, VERBOSE]
[WARNING]

**Comment by HanselCream** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>POM_Session</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <testng.version>7.7.1</testng.version>
        <log4j2.version>2.14.1</log4j2.version>
    </properties>

    

    <dependencies>

        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>4.9.0</version>
        </dependency>

        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
        </dependency>

        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>jquery</artifactId>
            <version>3.6.4</version>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>5.2.3</version>
        </dependency>

        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>5.2.3</version>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-api</artifactId>
            <version>2.18.0</version>
        </dependency>
        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.17.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-settings-builder</artifactId>
            <version>3.9.1</version>
        </dependency>

        

    </dependencies>


    <build>
        <pluginManagement>
        <plugins>

            
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>src/main/resources/testrunners/testng_regression.xml</suiteXmlFile>
                    </suiteXmlFiles>
                    <systemPropertyVariables>
                        <browser>chrome</browser>
                    </systemPropertyVariables>
                </configuration>
            </plugin>

            
        </plugins>
        </pluginManagement>
    </build>

</project>

**Comment by slawekjaranowski** [comment]
Close as duplicate of: #4033
