### ISSUE TITLE
entrypoint cannot be set lazily on JibExtension in the Gradle plugin

### ISSUE THREAD

**Issue by wakingrufus** [GoogleContainerTools/jib#4027]
While many properties on JibExtension utilise [lazy configuration APIs](https://docs.gradle.org/current/userguide/lazy_configuration.html), there are some, includingentrypoint, that do not. This forces users of the plugin to have to resort to using Project.afterEvaluate() in certain scenarios.

This issue is similar to #3927 but for entrypoint

**Comment by wakingrufus** [comment]
Thanks again for merging my contribution. Since it was merged, no release of the gradle plugin has gone out. I would greatly appreciate if a current maintainer could cut a release.
Thanks again!

**Comment by mpeddada1** [comment]
@wakingrufus Thank you for your contribution! [ jib-gradle-plugin:3.4.0](https://github.com/GoogleContainerTools/jib/releases/tag/v3.4.0-gradle) which includes this fix has been released. !
