### ISSUE TITLE
How to configure jib.httpTimeout instead of adding it from the command line (which is very cumbersome)

### ISSUE THREAD

**Issue by zxuanhong** [GoogleContainerTools/jib#4028]
**Environment**:

- *Jib version:* 3.3.2
- *Build tool:*  maven
- *OS:* mac

**Description of the issue**:
1. How to configure jib.httpTimeout instead of adding it from the command line (which is very cumbersome)
2. If a project team does run out of time often and can't be fixed. Everyone has to configure command-line arguments, which is particularly cumbersome.
3. Because in some cases Intranet penetration is done, or there are net gates. He's just slow.
4. I really want to configure it directly in the pom instead of the mvn command line

**Comment by chanseokoh** [comment]
You can set it in pom: https://github.com/GoogleContainerTools/jib/issues/2314#issuecomment-602654790

**Comment by zxuanhong** [comment]
@chanseokoh Thank you very much. This method is very effective
