### ISSUE TITLE
privacy.md mentions wrong config property to disable update checks

### ISSUE THREAD

**Issue by ChristianCiach** [GoogleContainerTools/jib#4029]
**Environment**:

- *Jib version:* 3.3.2
- *Build tool:* Gradle 8.1.1
- *OS:* Fedora 37

**Description of the issue**:

According to https://github.com/GoogleContainerTools/jib/blob/master/docs/privacy.md, the update checks of Jib can be disabled by declaring `"disableUpdateChecks": true` in `config.json`. This doesn't work, because the correct property is `disableUpdateCheck` (without the trailing `s`).

**Expected behavior**:

Well, at first I was expecting `"disableUpdateChecks": true` to work as documented and I even prepared a PR to fix the value in `GlobalConfigTemplate.java` instead of just fixing the documentation in `privacy.md`, because, surely, there are people out there already having `"disableUpdateChecks": true` inside their `config.json`, since the `privacy.md` file is mentioned inside the update-information printed by Jib:

```
A new version of jib-gradle-plugin (3.3.2) is available (currently using 3.3.1). Update your build configuration to use the latest features and fixes!
https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/CHANGELOG.md
Please see https://github.com/GoogleContainerTools/jib/blob/master/docs/privacy.md for info on disabling this update check.
```

So, fixing the code to make it consistent to the current `privacy.md` will make it "just work" for existing configurations that follow the `privacy.md`, and it would also make it consistent to the system-property `jib.disableUpdateChecks`. 

"Unfortunately", the README of jib-cli mentions the *correct* config: https://github.com/GoogleContainerTools/jib/tree/master/jib-cli#properties

So, these are our options:

* Fix the `privacy.md` to mention the correct property, (keep) breaking people who blindly believed the `privacy.md`.
* Fix the code (and `jib-cli/README.md`) to make the currently documented config in `privacy.md` work retroactively for people (like me) who blindly followed the information mentioned by the update-information printed by Jib when it finds a new update, also making it consistent to the system-property, but breaking people who followed `jib-cli/README.md`.

**Comment by meltsufin** [comment]
I think we should just fix the typo in `privacy.md`.
