### ISSUE TITLE
Publish JIB Gradle plugin artifact to MavenCentral (Gradle build conventions)

### ISSUE THREAD

**Issue by namero999** [GoogleContainerTools/jib#4038]
Currently the plugin is published to the Gradle plugin portal and is accessible via id such as `id("com.google.cloud.tools.jib") version "3.3.2"`

However, when implementing Gradle's precompiled build conventions scripts, the plugin needs to be accessed as regular Maven dependency.

See [here](https://docs.gradle.org/current/userguide/custom_plugins.html#applying_external_plugins_in_precompiled_script_plugins) and [here](https://docs.gradle.org/current/samples/sample_convention_plugins.html#applying_an_external_plugin_in_precompiled_script_plugin) for documentation.

On MavenCentral, it can only be found the JIB plugin for version 3.0.0 https://mvnrepository.com/artifact/gradle.plugin.com.google.cloud.tools/jib-gradle-plugin

It would be great if each version released on the Gradle pluing portal would be accompanied by a release on MavenCentral, so that Gradle's build conventions can be implemented company-wide.

**Comment by chanseokoh** [comment]
> On MavenCentral, it can only be found the JIB plugin for version 3.0.0 https://mvnrepository.com/artifact/gradle.plugin.com.google.cloud.tools/jib-gradle-plugin

Don't be confused by the name of the site `mvnrepository`. It is not on Maven Central but on some weird repository I've never heard of:

![image](https://github.com/GoogleContainerTools/jib/assets/10523105/769e70f6-a08b-4283-acbe-1a9e1520a129)

No need to publish Jib artifacts to Maven Central. They are available on the Gradle plugin portal. Check these out:

- https://github.com/GoogleContainerTools/jib/issues/3719#issuecomment-1203109125
- https://github.com/GoogleContainerTools/jib/issues/3719#issuecomment-1234595127

**Comment by namero999** [comment]
Excellent, thank you for the clarifications.
Seems like it's working by accessing it via the `gradlePluginPortal()` repository.
