### ISSUE TITLE
[jib-cli] Release lifecycle

### ISSUE THREAD

**Issue by gansheer** [GoogleContainerTools/jib#4041]
Hi Team,

I was looking through the last releases and was surprised to see there was one of jib-core last month and not one for jib-cli. Since jib-cli depends on jib-core I wonder how it's release life cycle works. 

Also the last jib-cli release (v0.12.0) contains in the lib two SNAPSHOT versions : jib-core-0.23.1-SNAPSHOT and jib-plugins-common-0.1.0-SNAPSHOT.

I would be thankful if you could give me more informations on this subject.

Thanks,

**Comment by emmileaf** [comment]
Hi @gansheer! In general Jib releases on an ad-hoc cadence. The changes introduced in the jib-core 0.24.0 release were smaller fixes reported from users of the Maven and Gradle plugins, so we hadn’t prioritized a release of jib-cli at the time, though please let us know in this issue if you are experiencing any blockers (you can also find instructions [here](https://github.com/GoogleContainerTools/jib/tree/master/jib-cli#build-yourself-from-source-for-advanced-users) for building jib-cli from source as well).

On the question about the snapshot jars: jib-cli depends on [jib-core and jib-plugins-common](https://github.com/GoogleContainerTools/jib/blob/master/jib-cli/build.gradle#L34-L35) while being distributed as a standalone CLI tool, and my understanding is that the snapshot jars contained in the distribution are [versions](https://github.com/GoogleContainerTools/jib/blob/v0.12.0-cli/jib-core/gradle.properties) from these modules captured at the time of each Jib CLI release.

**Comment by wakingrufus** [comment]
Hi there @emmileaf , I would like to use the changes to the gradle plugin that I recently contributed. could you please trigger a release for that when you have a chance?

Thanks for all of your work on this project!

**Comment by emmileaf** [comment]
Hi @wakingrufus - I am no longer part of the team that maintains this repo and can't speak for future releases, but would suggest perhaps following-up on https://github.com/GoogleContainerTools/jib/issues/4027 for better visibility of this comment!

**Comment by wakingrufus** [comment]
> Hi @wakingrufus - I am no longer part of the team that maintains this repo and can't speak for future releases, but would suggest perhaps following-up on https://github.com/GoogleContainerTools/jib/issues/4027 for better visibility of this comment!

Ok. Sorry to hear that! Thanks so much for your work.

**Comment by blakeli0** [comment]
The fix is released, see https://github.com/GoogleContainerTools/jib/issues/4027#issuecomment-1733754598 for details.
