### ISSUE TITLE
Writing Metadata to image?

### ISSUE THREAD

**Issue by lkb2k** [GoogleContainerTools/jib#4044]
What is the recommended way to write metadata like git sha into the image in a way the application can read it at runtime? We tag our images with build number and git sha, but I would also want to be able to include those values in the logs the application generates while it is running, so I'm looking for some mechanism to write those values into the image.  Do other people generate a properties file or write environment variables into the image itself somehow?

I found the discussion about using gradle to generate a manifest.mf which can be read if you package your application as a jar file, but if I want to continue to take advantage of the default image layout, what is the best approach?

**Comment by chanseokoh** [comment]
I don't have a strong opinion. You could write a plain text file during building a project and have Jib pick that up to place it wherever you want inside the image. Setting an environment variable sounds like this could be another option. For any options, I think either Maven or Gradle should allow you to do it.

**Comment by burkedavison** [comment]
Closing this issue as answered.
