### ISSUE TITLE
Connect to production.cloudflare.docker.com:443

### ISSUE THREAD

**Issue by Ycm19970520** [GoogleContainerTools/jib#4050]
Run Command mvn clean compile jib:build 

Error reporting：Connect to production.cloudflare.docker.com:443 [production.cloudflare.docker.com/104.18.124.25, production.cloudfla
re.docker.com/104.18.121.25, production.cloudflare.docker.com/104.18.122.25, production.cloudflare.docker.com/104.18.125.25, production.cloudflare.docker.com/104.18.123.25] failed: Connect timed out

**Comment by suztomo** [comment]
It seems the connection from your computer to the Cloudflare docker site was unavailable at that time. Can you retry again, probably from different network?

**Comment by suztomo** [comment]
Duplicate of https://github.com/GoogleContainerTools/jib/issues/4047. If there's network issue, then I'm afraid that Jib cannot resolve that.

**Comment by lexang** [comment]
isThereAnyOtherWayToOpenALadder？
