### ISSUE TITLE
Val cannot be reassigned for creationTime

### ISSUE THREAD

**Issue by neogeogre** [GoogleContainerTools/jib#4079]
**Environment**:

- *Jib version:* 3.3.2
- *Build tool:* Gradle 8.1.1
- *OS:* ubuntu 22.04

**Description of the issue**:

`Val cannot be reassigned` for `creationTime` 

**Expected behavior**:

`creationTime` can be set

**Steps to reproduce**:

  1. use jib 3.3.2
  2. `creationTime = "USE_CURRENT_TIMESTAMP"` cannot be used

But when using:

  1. use jib 3.3.0
  2. `creationTime = "USE_CURRENT_TIMESTAMP"` can be used

**Comment by burkedavison** [comment]
Hello @neogeogre, I haven't been able to replicate your issue. Could you try following the below example and seeing if it works for you?

My steps:
* `examples/helloworld/build.gradle`:
  1. Verified line 3 is `id 'com.google.cloud.tools.jib' version '3.3.2'`
  2. Updated line 17 to `jib.to.image = 'gcr.io/<myproject>/image-built-with-jib'`
* Execute `./gradlew jib`. Result: Container uploaded to gcr.io with creation date Dec 31, 1969
* Modify `examples/helloworld/build.gradle` with new line 18:
  `jib.container.creationTime = "USE_CURRENT_TIMESTAMP"`
* Execute `./gradlew jib`. Result: Container uploaded to gcr.io with creation date <Now>

Final `build.gradle`:
```
plugins {
  id 'java'
  id 'com.google.cloud.tools.jib' version '3.3.2'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
  mavenCentral()
}

dependencies {
  implementation 'com.google.guava:guava:23.6-jre'
}

jib.to.image = 'gcr.io/<myproject>/image-built-with-jib'
jib.container.creationTime = "USE_CURRENT_TIMESTAMP"
```

Screenshot:
![image](https://github.com/GoogleContainerTools/jib/assets/40617934/d2a5edc3-b7cd-4652-8ca9-79f3005be90d)

**Comment by wakingrufus** [comment]
3.3.1 included https://github.com/GoogleContainerTools/jib/commit/3696e6c75551fd8f2da55206e38e264cc499662c which changed creationTime to a Property.
you can set it like:
```
creationTime.set("USE_CURRENT_TIMESTAMP")
```
or by upgrading gradle to [8.2.1](https://docs.gradle.org/8.2.1/release-notes.html#simple-property-assignment-in-kotlin-dsl-enabled-by-default)

or, in [gradle 8.1.1](https://docs.gradle.org/8.1.1/release-notes.html#experimental-simple-property-assignment-in-kotlin-dsl-scripts), setting `systemProp.org.gradle.unsafe.kotlin.assignment=true` in gradle.properties

**Comment by neogeogre** [comment]
Thank you @wakingrufus, this solved the issue, what is difficult to guess is that now properties are not all set in the same way like:

```kotlin
container {
    ports = listOf("8080")
    creationTime.set("USE_CURRENT_TIMESTAMP")
}
```

**Comment by wakingrufus** [comment]
> Thank you @wakingrufus, this solved the issue, what is difficult to guess is that now properties are not all set in the same way like:
> 
> ```kotlin
> container {
>     ports = listOf("8080")
>     creationTime.set("USE_CURRENT_TIMESTAMP")
> }
> ```
> 

Yes its not ideal. But eventually everything should be a property. Also in gradle 8.2+ the `=` syntax works with properties
