### ISSUE TITLE
401 Unauthorized 

### ISSUE THREAD

**Issue by yarporokh** [GoogleContainerTools/jib#4083]
**`jib-maven-plugin` Configuration**: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>microservices-pract</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>car-service</module>
        <module>discovery-server</module>
        <module>api-gateway</module>
        <module>email-service</module>
        <module>notification-service</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <spring.boot.version>3.1.1</spring.boot.version>
        <spring-cloud.version>2022.0.3</spring-cloud.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.28</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-tracing-bridge-brave</artifactId>
        </dependency>
        <dependency>
            <groupId>io.zipkin.reporter2</groupId>
            <artifactId>zipkin-reporter-brave</artifactId>
        </dependency>
    </dependencies>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.1.1</version>
    </parent>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.2.1</version>
                <configuration>
                    <from>
                        <image>eclipse-temurin:17.0.4.1_1-jre</image>
                    </from>
                    <to>
                        <image>microservices-${project.artifactId}</image>
                    </to>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Log output**: [INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] microservices-pract                                                [pom]
[INFO] car-service                                                        [jar]
[INFO] discovery-server                                                   [jar]
[INFO] api-gateway                                                        [jar]
[INFO] email-service                                                      [jar]
[INFO] notification-service                                               [jar]
[INFO] 
[INFO] ------------------< org.example:microservices-pract >-------------------
[INFO] Building microservices-pract 1.0-SNAPSHOT                          [1/6]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.2.0:clean (default-clean) @ microservices-pract ---
[INFO] 
[INFO] --- jib-maven-plugin:3.2.1:build (default-cli) @ microservices-pract ---
[INFO] Skipping containerization because packaging is 'pom'...
[INFO]
[INFO] ----------------------< org.example:car-service >-----------------------
[INFO] Building car-service 1.0-SNAPSHOT                                  [2/6]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.2.0:clean (default-clean) @ car-service ---
[INFO] Deleting D:\javaweb\microservices-pract\car-service\target
[INFO] 
[INFO] --- maven-resources-plugin:3.3.1:resources (default-resources) @ car-service ---
[INFO] Copying 2 resources from src\main\resources to target\classes
[INFO] Copying 0 resource from src\main\resources to target\classes
[INFO]
[INFO] --- maven-compiler-plugin:3.11.0:compile (default-compile) @ car-service ---
[INFO] Changes detected - recompiling the module! :source
[INFO] Compiling 7 source files with javac [debug release 17] to target\classes
[INFO] 
[INFO] --- maven-resources-plugin:3.3.1:testResources (default-testResources) @ car-service ---
[INFO] skip non existing resourceDirectory D:\javaweb\microservices-pract\car-service\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.11.0:testCompile (default-testCompile) @ car-service ---
[INFO] Changes detected - recompiling the module! :dependency
[INFO]
[INFO] --- maven-surefire-plugin:3.0.0:test (default-test) @ car-service ---
[INFO] 
[INFO] --- maven-jar-plugin:3.3.0:jar (default-jar) @ car-service ---
[INFO] Building jar: D:\javaweb\microservices-pract\car-service\target\car-service-1.0-SNAPSHOT.jar
[INFO] 
[INFO] --- jib-maven-plugin:3.2.1:build (default-cli) @ car-service ---
[WARNING] 'mainClass' configured in 'maven-jar-plugin' is not a valid Java class: ${start-class}
[INFO] 
[INFO] Containerizing application to microservices-car-service...
[WARNING] Base image 'eclipse-temurin:17.0.4.1_1-jre' does not use a specific image digest - build may not be reproducible
[INFO] Using credentials from Docker config (C:\Users\Yarik\.docker\config.json) for microservices-car-service
[INFO] The base image requires auth. Trying again for eclipse-temurin:17.0.4.1_1-jre...
[INFO] Using credentials from Docker config (C:\Users\Yarik\.docker\config.json) for eclipse-temurin:17.0.4.1_1-jre
[INFO] Using base image with digest: sha256:7c08b969337bc44101a21a56eddfe65e20560045f558fad804d8d06bb455e778
[INFO] Executing tasks:
[INFO]
[INFO] Executing tasks:
[INFO]
[INFO] Executing tasks:
[INFO] [=======                       ] 22,9% complete
[INFO]
[INFO] Executing tasks:
[INFO] [=======                       ] 22,9% complete
[INFO] > building dependencies layer
[INFO]
[INFO] Executing tasks:                                  
[INFO] [========                      ] 25,0% complete   
[INFO]
[INFO] Executing tasks:
[INFO] [========                      ] 25,0% complete
[INFO] > pushing blob sha256:af65f068fb827aacac728fad3...
[INFO]
[INFO] Executing tasks:                                  
[INFO] [========                      ] 27,1% complete   
[INFO]
[INFO] Executing tasks:                                  
[INFO]
[INFO]
[INFO] Executing tasks:
[INFO] [===============               ] 50,0% complete
[INFO] > scheduling building manifests
[INFO] > launching layer pushers
[INFO] > scheduling pushing container configurations
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for microservices-pract 1.0-SNAPSHOT:
[INFO]
[INFO] microservices-pract ................................ SUCCESS [  0.774 s]
[INFO] car-service ........................................ FAILURE [ 11.307 s]
[INFO] discovery-server ................................... SKIPPED
[INFO] api-gateway ........................................ SKIPPED
[INFO] email-service ...................................... SKIPPED
[INFO] notification-service ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  12.413 s
[INFO] Finished at: 2023-08-05T23:18:58+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:3.2.1:build (default-cli) on project car-service: Build image failed, perhaps you should make sure your credentials for 'registry-1.docker.io/library/microserv
ices-car-service' are set up correctly. See https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized for help: Unauthorized for registry-1.docker.io/library/
microservices-car-service: 401 Unauthorized -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :car-service

**Additional Information**:

**Comment by truonglehcm** [comment]
I solved this issue by follow these steps:
1. Press **Windows + R** > Input **.docker** > Enter
2. Open **config.json** and remove **"credsStore": "desktop"**
3. Rebuild

Hope this help.

**Comment by yarporokh** [comment]
> 

Didn't help.😞

**Comment by yarporokh** [comment]
Didn't help 😢

**Comment by burkedavison** [comment]
Hey @yarporokh , have you tried following the troubleshooting section listed in the error message? (https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#what-should-i-do-when-the-registry-responds-with-unauthorized)

If so, please provide some details on the steps you've taken to ensure the credentials you're providing are correct and are configured according to the instructions.

**Comment by yarporokh** [comment]
@burkedavison @truonglehcm 

Hey guys, I want to share the news, I've solved the problem. In pom.xml->build->plugins->plugin->plugin->configuration->to

I changed the image field from 
<image>microservices-${project.artifactId}</image>
To 
<image>registry.hub.docker.com/{My docker hub username}/microservices-${project.artifactId}</image>
