### ISSUE TITLE
feature request: log the digest of the uploaded image

### ISSUE THREAD

**Issue by dirk-olmes** [GoogleContainerTools/jib#4087]
**Environment**:

- *Jib version:* 3.3.2
- *Build tool:* Maven 3.9.4
- *OS:* Windows

**Description of the issue**:
I'd like jib to print the image digest of the newly uploaded image. It already does the same when configured with a dedicated base image:
```
[INFO] Using base image with digest: sha256:087ebac0c3627a24db347a0a1603aa5cb6d9d51fb11f5a7d18383bc313fc5268
```

**Expected behavior**:
An output similar to the one above, just with the image digest of the newly created image.

**Comment by chanseokoh** [comment]
Does the following help?

https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#additional-build-artifacts

> As part of an image build, Jib also writes out the _image digest_ and the _image ID_. By default, these are written out to `build/jib-image.digest` and `build/jib-image.id` respectively

**Comment by dirk-olmes** [comment]
Yes that helps. I have configured my build to archive the `jib-image.digest` files.
