### ISSUE TITLE
Trying to update java.txt file at /user/share/crypto-policies/DEFAULT/java.txt

### ISSUE THREAD

**Issue by MohitMehta1986** [GoogleContainerTools/jib#4096]
I am trying to update the java.txt file present at /user/share/crypto-policies/DEFAULT/java.txt in the image created through jib plugin
But it always do permission denied 

Any way to update the file?

**Comment by chanseokoh** [comment]
Check out [`extraDirectories` and `extraDirectories.permissons`](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#adding-arbitrary-files-to-the-image).

**Comment by alicejli** [comment]
Please re-open this if the above does not answer your question.
