### ISSUE TITLE
Set creationTime/lastModificationTime only for last layer

### ISSUE THREAD

**Issue by Tristan-WorkGH** [GoogleContainerTools/jib#4108]
**Environment**:
- *Jib version:* 2.8.0
- *Build tool:* Maven 3.9.3
- *OS:* Linux

**Description of the issue**:
I understand that Jib create different layers as a mean to reduce images size by reusing common parts (in the case of my Spring-Boot app: base image, dependencies, resources, then application).  
When I look on Docker Hub and when I do an `docker images`, I can see my image being created "53 years ago". I understand from the FAQ that its for reproducibility, and there is `<creationTime/>` and `<filesModificationTime/>` options if I want to change that.  
But this seems to change files timestamp in the image for all layers.

Would it be possible to change timestamp only for the latest layer to be able to keep dependencies layer common between images while having the container time "correct".  
That way I can keep my image up-to-date with the last/actual commit time using a plugin like [git-commit-id-maven-plugin](https://github.com/git-commit-id/git-commit-id-maven-plugin/).

**Expected behavior**:
To have an option to set `<filesModificationTime/>` only on last layer.

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
	<groupId>pl.project13.maven</groupId>
	<artifactId>git-commit-id-plugin</artifactId>
	<configuration>
		<dateFormat>yyyy-MM-dd'T'HH:mm:ss'Z'</dateFormat>
		<dateFormatTimeZone>UTC</dateFormatTimeZone>
	</configuration>
</plugin>
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>jib-maven-plugin</artifactId>
	<configuration>
		<container>
			<filesModificationTime>${git.commit.time}</filesModificationTime>
		</container>
	</configuration>
</plugin>
```

EDIT:  
I may have not understand how docker images works. From this [comment in issue moby/moby#42417](https://github.com/moby/moby/issues/42417#issuecomment-862545586), I understand that there is a field `Created` that is keep in some metadata of the image.  
Can Jib offer a way to set this field ?

**Comment by mpeddada1** [comment]
Thanks for the question! As @chanseokoh mentioned, there is a [third-party Jib extension available for setting file timestamps ](https://github.com/infobip/jib-layer-with-modification-time-extension-maven). Closing.
