### ISSUE TITLE
`extraDirectories.permissions` is not changing folder permissions

### ISSUE THREAD

**Issue by kristian** [GoogleContainerTools/jib#4125]
**Environment**:

- *Jib version:* 3.3.1
- *Build tool:* Gradle 8.1.1
- *OS:* Windows + MacOS

**Description of the issue**:

Setting `extraDirectories.permissions` does not apply to folders, but to files only.

**Expected behavior**:

If setting a permission with a matching (folder) glob, the permission should be set to files.

**Comment by chanseokoh** [comment]
This used to work: https://stackoverflow.com/a/58661938/1701388

It might be that you are hitting the same issue as in https://github.com/GoogleContainerTools/jib-extensions/issues/163#issuecomment-1761698594.

**Comment by kristian** [comment]
Yes, same root cause essentially, the "root" of the extraDirectories (and any mkdirs that have been "in between" the targeted directory) have not been affected by the permissions. Only when we built the structure into a folder and defined the whole folder as an extraDirectory, the permissions have been set correctly. Thanks for your immediate help @chanseokoh! 👍 Have a nice weekend.
