### ISSUE TITLE
running a bash script in a multi-module project by not placing the script in each module's /src/main/jib

### ISSUE THREAD

**Issue by soyreda** [GoogleContainerTools/jib#4130]
I'm looking forward to customize my entrypoint on a spring boot multi-module project and in order to do that, i did choose to run this bash script from the root of the project (parent), but to make the script executable we should use the "extraDirectories" to add it. the thing is i don't want to add the script in each module /src/main/jib because that's what "extraDirectories" does. 
So how can I try to achieve this from parent without going through each module?

**Comment by chanseokoh** [comment]
You can [configure `extraDirectories.path`](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#adding-arbitrary-files-to-the-image) to your liking.

**Comment by soyreda** [comment]
> You can [configure `extraDirectories.path`](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#adding-arbitrary-files-to-the-image) to your liking.

that's it.
