### ISSUE TITLE
Abililty to override libs folder ( from /libs to /lib)

### ISSUE THREAD

**Issue by RestfulBlue** [GoogleContainerTools/jib#4132]
Currently, we are trying to integrate jib in our builds. In our project we have a lot of custom logic and all that logic assumes all libs are placed in lib folder. But jib places it into libs folder. Is there a way to override it? 
Sorry if if i am just missing it from, but checked it multiple times and didn't find such option :C

**Comment by chanseokoh** [comment]
If you can pre-bake a symlink into the base image, that may be one option?

Writing your own [Jib extension](https://github.com/GoogleContainerTools/jib-extensions/blob/master/README.md#updating-container-build-plan) is another option (the [Jib Layer-Filter extension](https://github.com/GoogleContainerTools/jib-extensions/tree/master/first-party/jib-layer-filter-extension-maven) is an example), but it requires some effort.

**Comment by RestfulBlue** [comment]
ok, thank you for information! <3
