### ISSUE TITLE
Plugin Config shows prefix not found exception 

### ISSUE THREAD

**Issue by skumaravelan** [GoogleContainerTools/jib#4143]
Mvn jib: build is touring an exception
  when I have plugin in Pom with out from and to image configuration.  I am passing these arguments as environment variables.
When I add those entries in Pom , build is successful.
There is no need. When I tried to build using the ci system, build was failing because of the prefix not found exception. jib plugin needs the below config entries.
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>3.4.0</version>
                <configuration>
                    <from>
                        <image>${jib.from.image}</image>
                    </from>
                    <to>
                        <image>${jib.to.image}</image>
                        <auth>
                            <username>${jib.to.auth.username}</username>
                            <password>${jib.to.auth.password}</password>
                        </auth>
                    </to>
                    <skip>false</skip>
                    <containerizingMode>packaged</containerizingMode>
                    <container>
                        <ports>
                            <port>8080</port>
                        </ports>
                    </container>
                </configuration>
            </plugin>

**Comment by rquinio** [comment]
Could you show the exception you're getting and use code blocks using ` ``` ` before and after the XML ?

**Comment by diegomarquezp** [comment]
Hi @skumaravelan, thanks for reporting this. Would you mind sharing the source pom.xml you are using and the exception you are getting as well? +1 to @rquinio's suggestion of using code blocks
I will close this issue in the meantime as we do not have enough information to reproduce it. Please feel free to reopen it when we have more info.
