### ISSUE TITLE
publsish jib-cli as maven artifacts

### ISSUE THREAD

**Issue by maxandersen** [GoogleContainerTools/jib#4148]
currently jib-cli is only distributed as jre bundle which is nice, but tedious and duplicates both the JDK and the jars I already have on my system.

could jib-cli be published to maven central so one could use tool like jbang to run it like: `jbang com.google.cloud.tools:jib-cli:RELEASE` or just do `jbang app install --name jib com.google.cloud.tools:jib-core` and then just use `jib` directly.

**Comment by mpeddada1** [comment]
Thanks for your interest in this! We're focusing on [bug fixes](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md) and platform evolution changes and while it's a good idea, it's not something we can prioritize at this time (unfortunately). Closing as not planned.
