### ISSUE TITLE
Rewrite example Gradle projects in Kotlin

### ISSUE THREAD

**Issue by KengoTODA** [GoogleContainerTools/jib#4149]
**Description of the issue**:

- Currently Gradle projects in the `examples` directory is written in Groovy DSL
- However, [the default buildscript DSL is now Kotlin from this April](https://blog.gradle.org/kotlin-dsl-is-now-the-default-for-new-gradle-builds)
- For users, it would be nice to provide examples written in Kotlin

**Additional Information**: 

- It is also good to bump up Gradle version; v5 is used in these example projects but v8 is the latest release.
- For example, [here is a DIFF](https://github.com/KengoTODA/jib/compare/master...KengoTODA:jib:example-kotlin) that updates the `example/hello-world` project.

**Comment by OneCricketeer** [comment]
> Currently Gradle projects in the examples directory is written in Groovy DSL

The ktor one isn't

**Comment by blakeli0** [comment]
Groovy DSL is still supported, we don't have plan to rewrite our examples at this moment. Please refer to the [examples in ktor folder ](https://github.com/GoogleContainerTools/jib/blob/master/examples/ktor/build.gradle.kts) if you need guidance on using Jib in Gradle projects with Kotlin DSL.
