### ISSUE TITLE
Making RegistryClient a more complete registry client

### ISSUE THREAD

**Issue by flfr-stibosystems-com** [GoogleContainerTools/jib#4158]
This is not so much a bug report or even a feature request, but I'd like to make RegistryClient more complete and useful in its own right.

Specifically I'm using RegistryClient to pull manifests and blobs in my application and I'd like to be able to delete manifests too.

If I create a pull request that adds a deleteManifest method to RegistryClient, would that be appreciated?

**Comment by blakeli0** [comment]
Hi @flfr-stibosystems-com , `RegistryClient` is supposed to be used internally, but not publicly used in your own application. Although this is a good idea, but we don't foresee it to be used for Jib internally at this point. Closing as not planned.
