### ISSUE TITLE
Gradle plugin 3.4.0 version is not available m2 plugin repo

### ISSUE THREAD

**Issue by ashvaniverma18** [GoogleContainerTools/jib#4162]
Latest version (3.4.0) of https://plugins.gradle.org/plugin/com.google.cloud.tools.jib is not availble on gradle plugin repo

https://plugins.gradle.org/m2/gradle/plugin/com/google/cloud/tools/jib-gradle-plugin/

**Comment by chanseokoh** [comment]
It's here: https://plugins.gradle.org/m2/com/google/cloud/tools/jib-gradle-plugin/

See #3795.
