### ISSUE TITLE
Hi, I am trying to call the python script from Spring boot Java application which is containerized with Google Jib. 

### ISSUE THREAD

**Issue by NitinSharma1991** [GoogleContainerTools/jib#4185]
I am trying to call a python script for some business purposes which is containerized with Google Jib.  I would like to know how can I copy python into the jib if it's possible , so that it will allow me to call the script from the application itself.

**Comment by NitinSharma1991** [comment]
This is just to copy the script file.  How about copy python executable to run python script as a process.

**Comment by mpeddada1** [comment]
@NitinSharma1991 similar to what was described above, to make Python binaries available to your Java application within the container, you can use Jib's `extraDirectories` feature to copy them into the desired location.  This [Maven](https://github.com/GoogleContainerTools/jib/blob/8b13f0d1bd4d88d7b3503b570ae065e322daaf47/jib-maven-plugin/README.md#adding-arbitrary-files-to-the-image) and [Gradle](https://github.com/GoogleContainerTools/jib/blob/6df635ee51bc466c961cdeea23d84e84e87ba4b0/jib-gradle-plugin/README.md#adding-arbitrary-files-to-the-image) doc explains how you can add arbitrary files to the jib container (the python binary can be added the same way). By default, the file will be copied onto the `src/main/jib` directory but the destination can be customized as instructed in the links attached.

**Comment by zhumin8** [comment]
Closing as there is no followups from issue reporter.  Feel free to reopen if you still have questions on this topic.
