### ISSUE TITLE
Release jib cli v0.13.0 ?

### ISSUE THREAD

**Issue by alexciouca** [GoogleContainerTools/jib#4242]
**Environment**:

- *Jib CLI version:* 0.12.0
- *Build tool:* jib cli
- *OS:* Win + Unix

**Description of the issue**:

Would it be possible to release a new version of jib cli? It hasn't been released in a while, and the current version contains outdated or libraries with security vulnerabilities.

**Expected behavior**:

A new version of jib cli is released.

**Steps to reproduce**:

NA

**Log output**: 

NA

**Additional Information**: 

NA

**Comment by mpeddada1** [comment]
Thank you @alexciouca! We've also had a couple of bug fixes go in recently so it may be a good time to release the jib-cli. I will assign this to myself.

**Comment by mpeddada1** [comment]
@alexciouca jib-cli:0.13.0 is now available at https://github.com/GoogleContainerTools/jib/releases/tag/v0.13.0-cli.
