### ISSUE TITLE
Cred Helper Environment support: clarification - is com.google.cloud.tools.jib.gradle.CredHelperParameters.getEnvironment used for anything?

### ISSUE THREAD

**Issue by alexanderankin** [GoogleContainerTools/jib#4251]
presumably this is a place to set variables like `AWS_PROFILE` for `credHelper`s like `ecr-login`, but this does not appear to work, at least not trivially.

**Comment by chanseokoh** [comment]
Take a look at #2814.

**Comment by alexanderankin** [comment]
oh great, yeah i will close this as duplicate. i guess it is the same.
