### ISSUE TITLE
v0.27.1-core not building amd64 images on M1+ macs

### ISSUE THREAD

**Issue by Rattenkrieg** [GoogleContainerTools/jib#4279]
**Environment**:

- *Jib version:* v0.27.1-core
- *Build tool:* gradle 8.7 with custom binary plugin using v0.27.1-core
- *OS:* Darwin Kernel Version 23.5.0

**Description of the issue**:
I have my cloud running amd64/linux containers hence I build with `.setPlatforms(setOf(Platform("amd64", "linux")))`. My CI setup is the same arch however sometimes I use to deploy from my M1 Mac (build image + push image + deploy) and since #4249 I'm getting 
> The configured platforms don't match the Docker Engine's OS and architecture (linux/arm64)

I see that there are changes in that PR that examine `docker -info` and my setup obviously reports `Architecture: aarch64` which being treated as an error despite my Mac totally happy to `docker build --platform linux/amd64`.

While this issue being triaged/fixed, maybe someone knows a way to configure docker to pretend it running on amd64 when asked for `docker info ...`?

**Comment by johncook-ch** [comment]
This issue is stopping us to upgrading to the latest version. My team and all onn M1 Macbook Pros but building images for `linux/amd64` to be deployed to AWS EC2

**Comment by mpeddada1** [comment]
jib-core 0.27.2 has been released (https://github.com/GoogleContainerTools/jib/releases/tag/v0.27.2-core) to address https://github.com/GoogleContainerTools/jib/issues/4265 and https://github.com/GoogleContainerTools/jib/issues/4265. Please let us know if you're running into any further issues!
