### ISSUE TITLE
Jib gradle plugin and Java modules?

### ISSUE THREAD

**Issue by hrstoyanov** [GoogleContainerTools/jib#4280]
**Environment**:
- *Jib version:3.4.3*
- *Build tool: Gradle 8.8*
- *OS: MacOS Java 22.0.1* 

**Description of the issue**:
1. How do prevent Jib gradle plugin from using/searching  main class and instead make it use main module?
2. How do I tell Jib gradle plugin to use module path?
3. How do I tell it to stop extracting the content of the jar that has a my main class?

I would like to specify all of these mylsef:

```
java --module my.module/my.package.App. --module-path /app/libs
 ```

I have used the below configuration, but this plugin still tries to infer main class and unzip the jar with the main class. 
```
container{
        entrypoint = [
                "java",
                '--module-path', '/app/libs',
                '--module', 'my.module/my.App'
        ]
    }
```

**Expected behavior**:

I want Jib to stop doing so opinionated and classpath-centric,  and allow me to set up main module path and main module myself.

**Comment by chanseokoh** [comment]
Not ignoring `mainClass` when setting `entrypoint` seems like a regression or a bug, because it's not going to be used anyway.

https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#container-object

> The command to start the container with (similar to Docker's [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/#entrypoint) instruction). If set, then `jvmFlags`, `mainClass`, `extraClasspath`, and `expandClasspathDependencies` are ignored.

**Comment by chanseokoh** [comment]
Actually, it's WAI that Jib searches for a main class even if you set a custom `entrypoint`. Jib still needs to know the main class to generate the `/app/jib-main-class-file` to support the [popular use-case](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#custom-container-entrypoint) where the user wants to know and use the main class that Jib has found in their custom `entrypoint`. But I agree this isn't ideal for the Java module use-case.
