### ISSUE TITLE
JIB Maven Container Labels with Properties from Parent POM

### ISSUE THREAD

**Issue by stefanLeo** [GoogleContainerTools/jib#4295]
**Environment:**

    Jib version: 3.4.3
    Build tool: Maven 3.9.6
    OS: N/A

**Description of the issue:**

I want to use properties of the parent pom as values for labels. However it seems that JIB is not resolving properties of a parent pom for this specific label field correctly (while it works this way for others like the from image). If I put the properties in the "current" pom all works as expected, but if I use a parent pom property, then the value is always null. 

**Expected behavior:**
JIB maven plugin can resolve parent pom properties as well. 

**Steps to reproduce:**

Use an labels map with a properities from a parent pom as value: 
Parent POM: 
 ```
<properties>
       <test.vendor>TESTVENDOR</test.vendor>
</properties>
<modules>
        <module>child</module>
</modules>
```

Child POM: 
```
<parent>
    <groupID>parent</groupID>
   ...
</parent>

JIB... 
<labels>
	 <org.opencontainers.image.vendor>${test.vendor}</org.opencontainers.image.vendor>
</labels>
```

Run jib

**Comment by chanseokoh** [comment]
I think this is a Maven question rather than a Jib one. Jib doesn't do anything special about Maven properties. It's Maven that substitutes properties at some point.
