### ISSUE TITLE
Publish jib-cli on Maven central

### ISSUE THREAD

**Issue by mikaelstaldal** [GoogleContainerTools/jib#4302]
It would be useful if jib-cli was published on Maven central (like jib-core and the Maven and Gradle plugings already are). That would, among other things, enable invoking it from a Maven build easily using [exec-maven-plugin](https://www.mojohaus.org/exec-maven-plugin/java-mojo.html).

**Comment by ldetmer** [comment]
unfortunately, we are not planning on supporting jib-cli on maven.
