### ISSUE TITLE
Support building image from jib.yaml in Maven plugin

### ISSUE THREAD

**Issue by mikaelstaldal** [GoogleContainerTools/jib#4303]
It would be useful if the Maven plugin (and probably also Gradle plugin) supports building an image from a [jib.yaml](https://github.com/GoogleContainerTools/jib/tree/master/jib-cli#fully-annotated-build-file-jibyaml) specification like the CLI's `build` command.

**Comment by ldetmer** [comment]
Unfortunately this project is primarily focused on critical bug fixes and platform evolution to ensure it continues to work for its supported use cases.  We are not accepting feature requests at this time.  Please see [contributing.md](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md)
