### ISSUE TITLE
Documentation for recommended JVM flags for containers

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#436]
Flags such as `-XX:+UseCGroupMemoryLimitForHeap`, `-XX:+UnlockExperimentalVMOptions`, `-Djava.security.egd=file:/dev/./urandom` and tips on setting limits.

**Comment by hoegertn** [comment]
I would also recommend `-XX:+ExitOnOutOfMemoryError`. Would it be an idea to have an option to set these automatically?

**Comment by coollog** [comment]
@hoegertn Thanks for those suggestions! I think having an option to set these automatically is definitely something we can consider - although, we would have to think about the user experience side. We want to provide ones that work for everyone and are transparent enough that users know what flags are being added. This may encompass belong in a separate "image manipulation" plugin/goal/task.

**Comment by cricket007** [comment]
Added some of these to #1291 and #1290

**Comment by chanseokoh** [comment]
`-XX:+UseCGroupMemoryLimitForHeap` and `-XX:+UnlockExperimentalVMOptions` are no longer needed in Java 9+ and recent Java 8u191+. Note Distroless

About `-Djava.security.egd=file:/dev/./urandom`, there are multiple aspects involved and `/dev/./urandom` isn't always the ideal choice. Pivotal has published an [excellent article](https://content.pivotal.io/blog/challenges-with-randomness-in-multi-tenant-linux-container-platforms) about it.

For some others like `-XX:+ExitOnOutOfMemoryError` and `-Djava.awt.headless=true`, this may be case-specific and we don't feel strongly about documenting these recommendations.
