### ISSUE TITLE
Declare gradle plugin in root project, use only in sub-projects

### ISSUE THREAD

**Issue by gintautassulskus** [GoogleContainerTools/jib#447]
**Description of the issue**:

Is it possible to declare jib plugin dependency in a root project and then use the plugin only in sub-projects?

Given the following configuration:
```
//root project
plugins {
    id 'com.google.cloud.tools.jib' version '0.9.0'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'com.google.cloud.tools.jib'
}
```

Command `gradle :root:subproject:jib` yields
```
Caused by: org.gradle.api.UnknownTaskException: Task with path 'classes' not found in project ':services'.Close stacktrace
at org.gradle.api.internal.tasks.DefaultTaskContainer.getByPath(DefaultTaskContainer.java:382)
at com.google.cloud.tools.jib.gradle.JibPlugin.lambda$apply$0(JibPlugin.java:61)
```

**Expected behavior**:
I expected a successful completion.

**Other**:
The plugin works fine if I declare it in the sub-project.
I am not certain whether this is my misuse of Gradle/Plugin or the plugin needs some fine-tuning.

**Environment**: 
Gradle 4.8

**Comment by coollog** [comment]
Thanks for reporting this! I think this is a bug on the way the plugin by default depends on the `classes` task. We'll take a look into this and provide a fix soon.

**Comment by gintautassulskus** [comment]
Hi @coollog, the root project does not contain any sources and therefore does not have the java plugin declared.
I did not realise that the declaration in the `plugins {}` block already activated Jib plugin.
I fixed the issue by applying the `apply false`.

```
//root project
plugins {
    id 'com.google.cloud.tools.jib' version '0.9.0' apply false
}
```
Sorry, false flag.
