### ISSUE TITLE
Micronaut

### ISSUE THREAD

**Issue by Solido** [GoogleContainerTools/jib#457]
**Description of the issue**:

Micronaut service doesn't start on Google Cloud when deployed as Container in Compute Engine.
Container stall in Restarting mode.

http://micronaut.io is a microservice framework by OCI the team behing Grails / Groovy.

**Expected behavior**:

Service should start instantly

**Steps to reproduce**: 

Create a new Micronaut app using the Cli
Add the JIB gradle plugin
Deploy to Container Repo and start a new instance using the Jib deployed container

**Environment**: 

GCE

**Additional Information**: I guess that the generated ENTRYPOINT can't access required 
classes/libs 

Thank you

**Comment by patflynn** [comment]
could this be related to #396 ?

**Comment by patflynn** [comment]
@Solido do you have a sample we could use for testing? Are you using Java, Kotlin, or Groovy?

**Comment by Solido** [comment]
Not sure, Micronaut is using java as the main starter but the rest of the app is impl w/ groovy.

The shortest path to recreate is 

- installing micronaut using SDKMan : https://sdkman.io/ (easier than build from github)
- create a app using the command `mn create-app hello-world --features groovy`
- add JIB to Gradle

The build and the upload of the image is OK

Let me know if it's too complicated I may try to send you a blank project, just not sure about the size of the archive it will generate.

**Comment by patflynn** [comment]
FYI I just tried this without groovy and it worked perfectly.  This may be a generic Groovy related issues similar to #396

**Comment by Solido** [comment]
Good news that java is working, 

#396 can not even compile and he gets log about it.
Looks like all is fine and jib-docker-context contains all the compiled classes and required libs. 
Here's my log from gradle jib with groovy

Retrieving registry credentials for gcr.io...
Retrieving registry credentials for gcr.io...
Building dependencies layer...
Building resources layer...
Building classes layer...
Getting base image gcr.io/distroless/java...
Finalizing...

Container entrypoint set to [java, -Xmx50m, -cp, /app/libs/*:/app/resources/:/app/classes/, awesome.server.Application]

Any idea where to look ?

**Comment by patflynn** [comment]
I just tried running jib with the groovy hello  world and got:
`
Execution failed for task ':jib'.
> Obtaining project build output files failed; make sure you have compiled your project before trying to build the image. (Did you accidentally run "gradle clean jib" instead of "gradle clean compileJava jib"?)
`

**Comment by Solido** [comment]
The app is working well when using a shadow jar and using a basic 
`CMD java -jar awesome-server-0.1-all.jar`

**Comment by patflynn** [comment]
@coollog for the Java sample I didn't even have to run `compileJava`,  does that error message still make sense?

**Comment by coollog** [comment]
Yes, Jib now doesn't require you to run `compileJava` explicitly since it automatically depends on the `classes` task. That error will show up for the cases when using languages that aren't Java itself (no `src/main/java`). We will have to work on adding support for other JVM languages like Kotlin and Groovy by fetching the correct source output files to build into the image. Currently, we only fetch those provided by the `JavaPluginConvention`, which give output files such as `build/classes/java/main`.

**Comment by Solido** [comment]
I think I get something

Parallel execution with configuration on demand is an incubating feature.
:compileJava UP-TO-DATE
:compileGroovy UP-TO-DATE
... all is working well and container deployed.

My project contains the `src/main/java` to awesome.server.Application

BUT jib-docker-context only contains Groovy compiled class not awesome.server.Application

**Comment by Solido** [comment]
I've manually moved the Applications.class to jib-docker-context and redeployed.
Inspection of the generated container show that

`"Entrypoint": [
                "java",
                "-Xmx50m",
                "-cp",
                "/app/libs/*:/app/resources/:/app/classes/",
                "awesome.server.Application"
            ],`

Is now working.

**Comment by patflynn** [comment]
@coollog do we have a tracking bug for adding support for Kotlin and Groovy?  If it's low effort seems like something worth prioritizing.

**Comment by Solido** [comment]
Up & Running 
Thanks @coollog

**Comment by patflynn** [comment]
:+1:
