### ISSUE TITLE
specifying target docker daemon for jibDockerBuild 

### ISSUE THREAD

**Issue by gintautassulskus** [GoogleContainerTools/jib#468]
Section [Build to Docker daemon](https://github.com/GoogleContainerTools/jib/tree/v0.9.1-gradle/jib-gradle-plugin#build-to-docker-daemon) provides an example on how to build and push a docker image to minikube docker daemon:

```
eval $(minikube docker-env)
gradle jibDockerBuild
```

Is there a gradle-native way to configure target docker daemon for the jib plugin?
I have multiple minikube instances running at the same time and must use minikube `--profile` option to retrieve specific minikube's docker-envs.

**Comment by gintautassulskus** [comment]
At first glance, the variable approach seems a bit neater, but the support for environmnt variable ingestion is more future-proof and flexible.
Whatever the decision, the end solution should integrate well with the [minikube plugin](https://github.com/GoogleContainerTools/minikube-build-tools-for-java).

I have opened an [issue](https://github.com/GoogleContainerTools/minikube-build-tools-for-java/issues/141) which I believe is somewaht relevant to this one.

**Comment by coollog** [comment]
Since it might be confusing to have `environment` on the `jib` extension (which configures the entire build), we may have the `jibDockerBuild` task configurable with environment variables, so it would look something like:

```
tasks.jibDockerBuild.environment 'NAME', 'VALUE'
```

Similarly, for Maven, only the `jib:dockerBuild` goal will be configurable with `dockerBuildEnvironment`.

**Comment by gintautassulskus** [comment]
I am thinking of adding `jib.dockerClient` to configure docker executable specific parameters, such as environment and path.

**Comment by gintautassulskus** [comment]
In response to https://github.com/GoogleContainerTools/jib/pull/1173#issuecomment-431891842

We have a number of multi-project gradle builds that require separate development enviromments. Hence the need for Minikube profiles.

If the following PR gets accepted (https://github.com/GoogleContainerTools/minikube-build-tools-for-java/pull/146), then the push of docker images would look something like:

```
    jibDockerBuild {
        doLast {
            dockerExecutable = "/usr/local/bin/docker"
            dockerEnvironment = minikube.getDockerEnv(projectID)
        }
    }
```
Where `minikube.getDockerEnv(profileID)` retrieves docker ENV configuration from the specified minikube instance and configures the `jibDockerBuild` task to deploy the image to the very same minikube instance.

This way developers can work on two projects at a time with fully isolated enviroments. For smaller projects, minikube with 2-4GB of ram is more than enough. Considering modern hardware it is feasible to comfortably run at least two such instances at the same time.

**Comment by chanseokoh** [comment]
Not available for Maven, let's leave this open. I think it's better than creating another issue.
