### ISSUE TITLE
Move plugins specific code to separate module.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#478]
Since `jib-core` will be converted to a standalone Java library for building container images, the plugins-specific code in there (mostly in the `frontend` package) should be moved to a separate module, perhaps called `jib-plugins-common`. This module would have most of the shared code for `jib-maven-plugin` and `jib-gradle-plugin`.

**Comment by patflynn** [comment]
Just a thought: Most of the use-cases that make sense for jib are for
building Java images from some kind of UI (whether build system or IDE),
and conceivably a lot of that package (or as much as I could gather form
looking at the class names :) ) could apply to those clients.

**Comment by coollog** [comment]
Yes, we should definitely think more about which classes we could provide in `jib-core` vs in `jib-plugins-common`. For example, the messages in the suggestions messages class (`HelpfulSuggestions`) mostly only apply to Maven or Gradle and has Maven/Gradle-specific messages and that should only go into `jib-plugins-common`, where `MainClassFinder` should definitely be in `jib-core` since it is core to Jib's simple configuration capability.
