### ISSUE TITLE
OSGI metadata

### ISSUE THREAD

**Issue by elharo** [GoogleContainerTools/jib#498]
jib-core (the library) will eventually need OSGI metadata to be used in Eclipse and other OSGI environments.

**Comment by coollog** [comment]
MANIFEST.MF with OSGi metadata draft:

```properties
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Version: <version>
Bundle-Name: Jib
Bundle-Vendor: Google
Bundle-SymbolicName: com.google.cloud.tools.jib; singleton:=true
Export-Package: com.google.cloud.tools.jib
Bundle-Description: Build containers
```

We will use [the Gradle OSGi plugin](https://docs.gradle.org/current/userguide/osgi_plugin.html) (which uses Bnd) to generate most of these automatically.

**Comment by briandealwis** [comment]
The Gradle-provided [`osgi` plugin](https://docs.gradle.org/current/userguide/osgi_plugin.html) does most of what we need, but the packages are exported with a `.SNAPSHOT` qualifier:
```
Export-Package: com.google.cloud.tools.jib;version="0.1.0.SNAPSHOT";uses:="…",
  com.google.cloud.tools.jib.async;version="0.1.0.SNAPSHOT";uses:="…",
  com.google.cloud.tools.jib.blob;version="0.1.0.SNAPSHOT";uses:="…",
```
Which in OSGi terms meants that these packages sort after `0.1.0`.  What's odd is the `maven-bundle-plugin` also uses bnd under the hood, but strips off the qualifier.

I'm investigating the use of the [bnd plugin](https://github.com/bndtools/bnd/blob/master/biz.aQute.bnd.gradle/README.md#gradle-plugin-for-non-workspace-builds) instead.

**Comment by briandealwis** [comment]
Using the bnd plugin looks to Do The Right Thing.

**Comment by loosebazooka** [comment]
I think it's `Google LLC`: https://github.com/GoogleCloudPlatform/appengine-plugins-core/issues/685
