### ISSUE TITLE
Check using Quay as the registry.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#500]

**Comment by briandealwis** [comment]
Note there are two versions of Quay: the hosted `quay.io` and the on-prem [Quay Enterprise](https://quay.io/plans/?tab=enterprise).  Both are affected by #601.

**Comment by chanseokoh** [comment]
Pushing to Quay fails: #698

**Comment by briandealwis** [comment]
The Quay developers are actively working on Schema 2 support (https://github.com/moby/buildkit/issues/409#issuecomment-394757219).

**Comment by coollog** [comment]
Closing as there hasn't been any requests for using Jib to build to Quay.

**Comment by briandealwis** [comment]
[Quay](https://github.com/moby/buildkit/issues/409#issuecomment-469759226) now supports schema 2 and OCI images.

**Comment by chanseokoh** [comment]
I have difficult following all the history. My understanding is that, since Quay is rolling out support for V2.2 schema, Jib should start being able to push to Quay, and we just need to have someone verify that it works. No work from our side beside that, right?

**Comment by anthonydahanne** [comment]
I've just tried 5 minutes ago and got : 
```
[INFO] --- jib-maven-plugin:1.0.1:build (default-cli) @ demo ---
[WARNING] Setting image creation time to current time; your image may not be reproducible.
[INFO] 
[INFO] Containerizing application to quay.io/anthonydahanne/test1...
[INFO] The base image requires auth. Trying again for openjdk:8-jre-alpine...
[INFO] 
[INFO] Container entrypoint set to [sh, -c, chmod +x /entrypoint.sh && sync && /entrypoint.sh]
[INFO] Executing tasks:
[INFO] [==============================] 100.0% complete
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  04:18 min
[INFO] Finished at: 2019-03-08T11:54:08-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.0.1:build (default-cli) on project demo: Tried to push image manifest for quay.io/anthonydahanne/test1:latest but failed because: Registry may not support Image Manifest Version 2, Schema 2 | If this is a bug, please file an issue at https://github.com/GoogleContainerTools/jib/issues/new: 415 UNSUPPORTED MEDIA TYPE
[ERROR] {"errors":[{"code":"MANIFEST_INVALID","detail":{"message":"manifest schema version not supported"},"message":"manifest invalid"}]}
```

**Comment by chanseokoh** [comment]
The server is clearly responding that the requested manifest schema version is not supported. It may be that their incremental rollout is not complete yet. Looks like you can [contact them for whitelisting](https://github.com/moby/buildkit/issues/409#issuecomment-469759226) if this is the case.

**Comment by chanseokoh** [comment]
@anthonydahanne does Quay work now?

**Comment by anthonydahanne** [comment]
nope, still the same :-(

**Comment by chanseokoh** [comment]
Alright, you should keep nagging the Quay folks.

Quay still doesn't support Manifest V2.2 (returning 415 Unsupported Media Type).
```
$ curl -v -X PUT -H 'Content-Type: application/vnd.docker.distribution.manifest.v2+json' https://quay.io/v2/francium25/test/manifests/add-tag
...
< HTTP/2 415 
...
{"errors":[{"code":"MANIFEST_INVALID","detail":{"message":"manifest schema version not supported"},"message":"manifest invalid"}]}
```
OTOH, Manifest V2.1 works, as it has been.
```
$ curl -v -X PUT -H 'Content-Type: application/vnd.docker.distribution.manifest.v1+json' https://quay.io/v2/francium25/test/manifests/add-tag
...
< HTTP/2 401 
...
{"errors":[{"code":"UNAUTHORIZED","detail":{},"message":"access to the requested resource is not authorized"}]}
```

**Comment by chanseokoh** [comment]
Quay uses Manifest V.2.1 by default, but I've seen many users asking for whitelisting their namespaces to use V2.2 (https://github.com/moby/buildkit/issues/409#issuecomment-469759226). Jib should work with Quay when using V2.2. I'm closing this, but if anyone finds that it doesn't, please re-open.

**Comment by chanseokoh** [comment]
Note Docker deprecated Manifest V2.1: https://docs.docker.com/engine/#19030

> Deprecate image manifest v2 schema1 in favor of v2 schema2. Future version of Docker will remove support for v2 schema1 althogether. [moby/moby#39365](https://github.com/moby/moby/pull/39365)

**Comment by chanseokoh** [comment]
This is the deprecation notice Docker currently prints out.

```
$ docker push quay.io/francium25/test
The push refers to repository [quay.io/francium25/test]
...
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the quay.io registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
```
