### ISSUE TITLE
No credential helper is needed if auth is configured with a JSON key file

### ISSUE THREAD

**Issue by dgageot** [GoogleContainerTools/jib#507]
I'm trying to build and push an image built by `jib` to `gcr.io`.
The sources for the project are [here](https://github.com/dgageot/hello-jib).
Docker is configured to push to `gcr.io` using a JSON key file, as explained in [this guide](https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file).

I expect `mvn compile jib:build` to be able to push the image.
It fails with this message:
```
[INFO] Containerizing application to gcr.io/dga-demo/hello-jib...
[INFO] 
[INFO] Retrieving registry credentials for gcr.io...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Getting base image gcr.io/distroless/java...
[INFO] Building classes layer...
[WARNING] The system does not have docker-credential-gcr CLI
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.985 s
[INFO] Finished at: 2018-07-05T09:07:21Z
[INFO] Final Memory: 97M/243M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.1:build (default-cli) on project hello-spring-boot: Build image failed, perhaps you should set a credential helper name with th
e configuration '<from><credHelper>' or set credentials for 'gcr.io' in your Maven settings: com.google.api.client.http.HttpResponseException: 401 Unauthorized
[ERROR] {"errors":[{"code":"UNAUTHORIZED","message":"You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps
 in: https://cloud.google.com/container-registry/docs/advanced-authentication"}]}
```

It shouldn't require the `docker-credential-gcr` credential helper. The JSON file is enough to push.
As a proof, `docker pull|push gcr.io/dga-demo/hello-jib` both work.

**Comment by dgageot** [comment]
If I install `docker-credential-gcr` it works

**Comment by coollog** [comment]
Hi David, could you provide you Docker config file (without sensitive info)? Usually it's `$HOME/.docker/config.json`.

**Comment by dgageot** [comment]
It looks like that:

```
{
	"auths": {
		"https://gcr.io": {
			"username": "_json_key",
			"password": "[SOME JSON]",
			"auth": "[SOME BASE64 STUFF]",
			"email": "not@val.id"
		}
	}
}
```

I followed [those instructions](https://cloud.google.com/container-registry/docs/advanced-authentication#json_key_file) to set it up.

**Comment by coollog** [comment]
Hmm, okay, it looks like this is in a format we don't process correctly - will take a closer look at this.

**Comment by sankar22222** [comment]
Hi Team i am pusing image from mvn jib i am getting same credential error. i have installed the docker credential gcr as well . Error as follows
Step #1: [ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:1.0.2:build (default-cli) on project demogcp: Build image failed, perhaps you should set a credential helper name with the configuration '<to><credHelper>' or set credentials for 'gcr.io' in your Maven settings: Unauthorized for gcr.io/storageproject-12345/demogcp: 401 Unauthorized
Step #1: [ERROR] {"errors":[{"code":"UNAUTHORIZED","message":"You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication"}]}
Step #1: [ERROR] -> [Help 1]

**Comment by loosebazooka** [comment]
@sankar22222 Please open a new issue. This issue is closed.
