### ISSUE TITLE
Allow user to build image as tar file that can be 'docker load'ed

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#514]
https://github.com/GoogleContainerTools/jib/blob/master/proposals/build_tarball.md

- [x] Add private output path configuration parameter
- [x] Rename `BuildTarballAndLoadDockerStep` to `LoadDockerStep`
- [x] Add `WriteTarFileStep`
- [x] Add `BuildSteps#forBuildToTarball()`
- [x] Add new task to Gradle plugin
- [x] Add new mojo to Maven plugin

**Comment by briandealwis** [comment]
Would it make sense to attach the tarball as an artifact to the project?

Is there any value in supporting a new packaging that would:
  - use `package` to generate the tar ball
  - use `install` to build to docker
  - use `deploy` to push to registry

**Comment by TadCordle** [comment]
I'm not sure we want to do that, since currently when we generate the tarball blob, we never actually write it to disk. Adding the tarball as an actual artifact would add some unnecessary I/O to the other steps.

**Comment by briandealwis** [comment]
Most of the repository managers are adding support for docker images anyways.
