### ISSUE TITLE
The name is very LOW!

### ISSUE THREAD

**Issue by xiasenhai** [GoogleContainerTools/jib#538]
**Description of the issue**:
Imagine this:  

I create a project named `PENIS`. do you english people feel offended?

**Expected behavior**:

jib is treated as penis in chinese pinyin. some of us may feel this is a very low and stupid name.

**Steps to reproduce**: 
step 1: find a chinese man/woman
step 2: say 'jib' to he/she in face
step 3: Just waiting to be slap on face

**Environment**: 

Any Chinese-speaking community

**Additional Information**: 

insult
humiliate

**Comment by li-xunhuan** [comment]
兄die。你怕不是个杠精？？
人家英文单词`jib`在您这儿就成了`ji'ba`了？
恕在下直言，您这行为挺丢人的！！

**Comment by loosebazooka** [comment]
While we appreciate your concerns with our choice of name, it is probably going to remain `Jib`.  If it is a large concern, perhaps you could use "java image builder" or "J-I-B", when talking about this product.

**Comment by pig4cloud** [comment]
挺会挑刺，晚上来我这吃鱼吧。
真的是丢中国开发者的人！

**Comment by yqc126** [comment]
你这个...怕不是杠精....丢人到国外来了..... -_-|| spring boot 还简写成sb呢...
