### ISSUE TITLE
Improve examples.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#540]
- Improve the documentation for [helloworld](https://github.com/GoogleContainerTools/jib/tree/master/examples/helloworld)
- Add examples for other registries besides GCR (like **Docker Hub**, ECR, ACR, Nexus)
- Provide examples for multi-module projects (DONE - #736)
  - Multi-module example with one module as common library (low priority)
- Move the [Micronaut example](https://github.com/coollog/micronaut-jib) here (DONE - #893)

Please comment with any examples you would like to us to provide.

**Comment by giskarda** [comment]
Fairly interested in the multi-module example!

**Comment by wilder** [comment]
@coollog, do you think adding an example using Gradle and [Docker Hub](https://hub.docker.com/) as registry would be a good idea? I'm interested in setting up a project using this configuration.

**Comment by coollog** [comment]
@wilder thanks for the suggestion - added to the list of registries!

**Comment by coollog** [comment]
Hi @giskarda , we have added a simple multi-module example at https://github.com/GoogleContainerTools/jib/tree/master/examples/multi-module :)

**Comment by coollog** [comment]
Will close this and file separate issues for example requests as needed.
