### ISSUE TITLE
Improve the contributor experience.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#548]
Contributors may be having issues when working on the code. We should try to make the contributing getting-started experience as smooth as possible (with setup guides, troubleshooting, etc.).

Examples:
- https://github.com/GoogleContainerTools/jib/issues/539#issuecomment-404063543

Please comment with other issues you experienced.

**Comment by briandealwis** [comment]
- How to build
- How to debug
- Instructions for importing into different environments (e.g., IntelliJ and Eclipse)

**Comment by coollog** [comment]
I think this is mostly good now with #655 . Closing.
