### ISSUE TITLE
What is the eccn classification code of jib? thanks！

### ISSUE THREAD

**Issue by reloadcarrot** [GoogleContainerTools/jib#570]
**Description of the issue**: 
What is the ecln classification code of jib? thanks！

**Expected behavior**:

**Steps to reproduce**: 

**Environment**: 

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**:

**Comment by patflynn** [comment]
This publicly available code is not subject to the Export Administration Regulation (EAR) and has no Export Control Classification Number (ECCN).

**Comment by patflynn** [comment]
@reloadcarrot will get back to you as soon as we have confirmation.

**Comment by patflynn** [comment]
Final answer:
This publicly available code is not subject to the Export Administration Regulation (EAR) and has no Export Control Classification Number (ECCN).
