### ISSUE TITLE
 Cannot run program "docker-credential-mvaen"

### ISSUE THREAD

**Issue by tanoak10** [GoogleContainerTools/jib#571]
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.2:build (default-cli) on project jib-demo: Build image failed: java.io.IOException: Cannot run program "docker-credential-mvaen": CreateProcess error=2, 系统找不到指定的文件。 -> [Help 1]

that is maven log

**Comment by tanoak10** [comment]
<from>
                        <image>hub.c.163.com/housan993/centos7_jdk8:latest</image>
                        <credHelper>maven docker</credHelper>
                    </from>
                    <to>
                        <image>localhost:5000/my-image:built-with-jib</image>
                        <credHelper>osxkeychain</credHelper>
                    </to>

**Comment by tanoak10** [comment]
`<from>
                        <image>hub.c.163.com/housan993/centos7_jdk8:latest</image>
                        <credHelper>maven docker</credHelper>
                    </from>
                    <to>
                        <image>localhost:5000/my-image:built-with-jib</image>
                        <credHelper>osxkeychain</credHelper>
                    </to>`

that is maven Configuration

**Comment by coollog** [comment]
Hi @tanoak10 , `credHelper` should be configured with the name of the Docker credential helper that stores the credentials for the corresponding image registry. I see you used `maven docker`. This doesn't seem like a valid credential helper name. Do you have a credential helper for your `hub.c.163.com` registry? If not, we'd recommend [using Maven settings](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#using-maven-settings).

**Comment by coollog** [comment]
@tanoak10 Closing this issue for now - feel free to reopen you are having any additional problems.
