### ISSUE TITLE
Allow to merge images

### ISSUE THREAD

**Issue by rmannibucau** [GoogleContainerTools/jib#580]
**Description of the issue**:

Jib - in particular core lib - handles layers perfectly, it would be very neat to be able to merge layers of different images (merge the filesystems) to create a new image.

**Expected behavior**:

The plugins (maven/gradle) support a new configuration entry "aggregateImages" which takes a list of images to include in the image being built.

I'm not sure if it must be done at layer level or if layers must be extracted then merged but the final feature of aggregating images through a simple build is very powerful and replaces the docker multi stage build in OCI land.

**Comment by rmannibucau** [comment]
@coollog with docker multi-stage you can consider each image as a delivery and you can very easily and with very few layers aggregate multiple of these deliveries in a single one. Since jib impl OCI module it is easy to do the same. High level the need is to be able to grab the filesystem of multiple image to build a new filesystem. This is a very common workaround for cloud providers like AWS which are not supporting mounting points.

**Comment by rmannibucau** [comment]
@briandealwis not sure I got you so let me give an example:

1. image1 creates a "/opt/repository"
2. image2 creates a "/opt/server"
3. image3 creates a "/opt/monitoring"
4. image4 creates a "/opt/tools"

Now i want to deploy image5 = /opt/*. The workaround would be to do composition 2 by 2 but it leads to a combination very hard to manage very quickly compared to docker multistage.

**Comment by coollog** [comment]
This might be better handled by a separate tool for merging images, since the other images don't actually relate to the Java application image that Jib builds.

**Comment by rmannibucau** [comment]
Maybe but reality is that jib is an image java framework and has all the primitives to do it so building it on top of jib makes sense cause it is very easy and a few lines. Better than redoing all the code IMHO or creating a project with nothing and no owning of the layer code

**Comment by coollog** [comment]
Hi @rmannibucau , we added the `src/main/jib` feature so that you can place additional files you wish to add to the container inside that directory (such as `src/main/jib/opt/repository` or `src/main/jib/opt/server`). The instructions can be found here: https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#adding-arbitrary-files-to-the-image

**Comment by rmannibucau** [comment]
Hello @coollog

It doesnt fully match (but is a great other feature btw) since here the hypothesis is that i already have images on a registry and i just want to merge them in one or rephrased, concatenate layers of N images.

**Comment by briandealwis** [comment]
I think this could be done via a mechanism as described in #1568.  Closing in favour of that issue.
