### ISSUE TITLE
Gradle plugin: support for Kotlin

### ISSUE THREAD

**Issue by juergenzimmermann** [GoogleContainerTools/jib#581]
It would be nice if the Gradle plugin would also look for the main class inside `build\classes\java\main`.

**Comment by coollog** [comment]
Hi @juergenzimmermann , thanks for filing this issue. I'm assuming you had to define the Kotlin main class explicitly with JIb's `mainClass` parameter?

**Comment by juergenzimmermann** [comment]
Yes

**Comment by tobad357** [comment]
Would this also fix that jib doesn't check ``` build/classes/kotlin```?

**Comment by chanseokoh** [comment]
@tobad357 that's good to know, thanks. We should check `build/classes/kotlin` too.

**Comment by coollog** [comment]
I believe this issue is already resolved. Using Jib with a Kotlin project should just work now. @tobad357 @juergenzimmermann try with version `0.9.6` - let me know if there's any issues.

**Comment by tobad357** [comment]
@coollog works fine but still gives warning about java classes not found even if kotlin classes found
Not something major, just a nit

**Comment by coollog** [comment]
@tobad357 thanks for the suggestion! Would you mind filing an issue for that? I'll close this in favor of that one.

**Comment by tobad357** [comment]
No problem, See #677

**Comment by coollog** [comment]
@tobad357 great, thanks!
