### ISSUE TITLE
Jib should handle the absence of source files gracefully

### ISSUE THREAD

**Issue by gintautassulskus** [GoogleContainerTools/jib#583]
The behaviour of `Jib` and `java` plugins differs if a project does not have any source files. Cosnider the following difference.

Java plugin handles the absence of source files gracefully by skipping the `compileJava` task:
```
> Task :root-project:sub-project:compileJava NO-SOURCE
file or directory '<project_path>/src/main/java', not found
Skipping task ':root-project:sub-project:compileJava' as it has no source files and no previous output files.
```

Jib, on the other hand, terminates gradle execution:

```
warning: Could not find build output <project_path>/build/classes/java/main'
warning: No classes files were found - did you compile your project?

> Task :jibDockerBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jibDockerBuild'.
> Main class was not found, perhaps you should add a `mainClass` configuration to jib

Caused by: com.google.cloud.tools.jib.frontend.MainClassInferenceException: Main class was not found, perhaps you should add a `mainClass` configuration to jib
        at com.google.cloud.tools.jib.frontend.MainClassFinder.resolveMainClass(MainClassFinder.java:96)
```

It would be convenient to be able to acheive the same no-source handling behaviour in both plugins for a simpler configuration.

I would suggest to either hardcode the improvement or add a configuration option such as `lenient=true/false`, where in case of `true` the plugin would skip the task with no source files and in case of `false` Jib would terminate as it does now.

**Comment by briandealwis** [comment]
Hi @gintautassulskus. Are you seeing this with a real project?  The risk otherwise is that Jib produces a broken image.

**Comment by gintautassulskus** [comment]
Hi @briandealwis, thanks for the response. Yes, I would like to use this in a real project. The project structure is as follows:

```
rootProject:
-no-surce-subproject
-jib-subproject
```
I place all configuration in the `rootProject` project. This is where I add 'java' and jib plugins as well.
The `no-surce-subproject` project does contain any source code and is not meant to be compiled or packaged with Jib.
The `jib-subproject` is a spring boot project that is meant to be packaged in a container image.

All tasks are run the root project level, e.g.: `gradle clean` cleans all projects, `gradle compileJava` processes all sub-projects whenever they are applicable. I have hoped to achieve the same with `gradle jibDockerBuild` and `gradle jib`.

> The risk otherwise is that Jib produces a broken image.
Jib could check for the presence of mainClass. If not found - skip. Would that suffice?

I am not a guru of gradle therefore I am not entirely sure what is the convention of running multi-project build tasks. However, it feels to me that it should be possible to trigger all tasks at the root level and they should behave somewhat similarly.

**Comment by coollog** [comment]
Hi @gintautassulskus , you can actually disable a task in a subproject with the `enabled` field like:

`build.gradle`
```
tasks.jib.enabled = false
```

**Comment by patflynn** [comment]
@gintautassulskus out of curiosity, why are you organizing your project that way?  Is it to get the spring boot uberjar packaging included in the container?

**Comment by gintautassulskus** [comment]
@coollog, I have added these lines at the bottom of `jib/examples/helloworld/build.gradle`:
```
tasks.jib.enabled = false
//jib.to.image = 'gcr.io/REPLACE-WITH-YOUR-GCP-PROJECT/image-built-with-jib'

task foo {
  doLast {
    println "bar"
  }
}
tasks.foo.enabled = false
```

The `gradle jibDockerBuild` still executes.  The `foo` task as expected - does not. Am I missing something obvious?

PS. Jib-created images have timestamps of something like `CREATED: 48 years ago` or `292 years ago`.

@patflynn, the multi-project build is a collection of libraries and microservices. Some of them need to be packaged and deployed, some of them need not. I tried top keep details to a minimum; our project structure actually looks something like the following:
```
project-platform:
-gateways
  -gateway1
  -...
-services
  -service1
  -...
-commons
  -library1
  -...
```
We would like to have the ability to deploy the whole platform either partially or at once.

**Comment by coollog** [comment]
@gintautassulskus Ah, didn't see you were using `jibDockerBuild` - do `jibDockerBuild.enabled = false` instead.

**Comment by patflynn** [comment]
@gintautassulskus I would expect that kind of project to configure jib in the module that needs to be containerized rather than the project root.  @coollog WDYT?

**Comment by coollog** [comment]
I think it is convenient to have a common base configuration for Jib, but it might be better organized as having the subprojects that should be containerized use a common configuration that is different from ones that shouldn't be containerized. @loosebazooka could probably give a better suggestion here.

**Comment by gintautassulskus** [comment]
@coollog, thanks! My apologies, should have spotted this myself. Time for a coffee break.

Now I can achieve the desired behaviour by setting `jibDockerBuild.enabled = false` in the root project and then setting it to `true` in relevant sub-projects that need to be containerised. 

@patflynn, I will consult the 'Gradle guys' on this and get back to you.

**Comment by chanseokoh** [comment]
> PS. Jib-created images have timestamps of something like CREATED: 48 years ago or 292 years ago.

This is intended. Please see #578 and #413.

**Comment by coollog** [comment]
Closing unless there are further issues. @gintautassulskus Feel free to post additional comments, though.

**Comment by gintautassulskus** [comment]
@patflynn, in the root project I declare common jib configuration and then each sub-project overrides/extends the configuration accordingly. Basically I'm am doing as you have suggested.

The approach taken in Gradle seems to be mostly [subject to situation](https://discuss.gradle.org/t/best-practices-for-plugin-declaration-and-task-visibility/27714).

**Comment by KTannenberg** [comment]
@coollog, is there similar option for Maven? I would like to place common configuration of Jib to project's parent pom and enable on modules that actually needs to be packaged (currently Job will attempt to package parent as well, failing due to lack of `target/` folder)

**Comment by coollog** [comment]
Hi @KTannenberg , is your parent POM just a `pom` packaging? If so, #735 will automatically not `jib:build` the parent POM.

**Comment by KTannenberg** [comment]
@loosebazooka yes, common configuration is stored in `pluginManagement` of parent pom. But calling `clean compile jib:build` still attempts to package parent pom (and modules where jib is not declared as plugin) into docker image.

**Comment by loosebazooka** [comment]
Yeah, since maven is assuming we're calling the goal on all modules, to avoid this you can use one of two options:

1. `-pl` which will only execute on a specific module. 
```
$ mvn clean compile && mvn jib:build -pl <my-module-name>
```

2. Attaching goals to lifecycle phases is profile. Assuming we're using both `<modules>` and the *parent pom* patterns. And lets assume we want the jib goal to execute in the *package* phase our lifecycle.
pom.xml (in our jib module)
```
     <profiles>
      <profile>
        <id>jib</id>
        <build>
          <plugins>
            <plugin>
              <groupId>com.google.cloud.tools</groupId>
              <artifactId>jib-maven-plugin</artifactId>
              <executions>
                <execution>
                  <phase>package</phase>
                  <goals>
                    <goal>build</goal>
                  </goals>
                </execution>
              </executions>
            </plugin>
          </plugins>
        </build>
      </profile>
    </profiles>
```

to execute this with almost the same results as `mvn clean compile jib:build`
```
$ mvn clean package -DskipTests -Pjib
```
We're skipping tests, because previously `compile jib:build` didn't even activate the `test` phase.

I must also say that the pattern of the plugin enabling/disabling itself appears in the maven ecosystem. And while it may be strange, I can't deny that people seem to want to use it. Let me know how this works for you, and if it doesn't we can work on another solution that fits within the standard maven model.
