### ISSUE TITLE
Reduce duplicate code in image building tasks/mojos

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#594]
- [x] Maven/gradle specific code
- [x] Auth configuration
- [x] `ProjectProperties`

**Comment by coollog** [comment]
We could probably organize this in the framework style like how the registry requests work.

**Comment by coollog** [comment]
Related to https://github.com/GoogleContainerTools/jib/issues/478 as well

**Comment by TadCordle** [comment]
I think this is done for the most part. Feel free to reopen if you think there's more that should be done.
