### ISSUE TITLE
Question: Support for opencontainers/custom labels?

### ISSUE THREAD

**Issue by bjornmagnusson** [GoogleContainerTools/jib#598]
Is there any support for org.opencontainers labels or applying custom labels to the generated image?

**Comment by coollog** [comment]
Hi @bjornmagnusson thanks for the suggestion! We've been thinking about this too and consider adding a way to configure labels.

**Comment by coollog** [comment]
Hi @bjornmagnusson label support was added in #751 and will be available in the next release (version `0.9.10`).

**Comment by coollog** [comment]
@bjornmagnusson Version `0.9.10` has been released with label support. Labels can be configured via `<container><labels>`.
