### ISSUE TITLE
Incorrect year of image creation

### ISSUE THREAD

**Issue by t-buss** [GoogleContainerTools/jib#600]
**Description of the issue**:
After building the image and inspecting it, the `Created` property shows 1970-01-01T00:00:00.
Appearently, the timestamp was not set correctly.
**Expected behavior**:
I expected the `Created` property to show the actual build time
**Steps to reproduce**: 
Use a simple Hello World Spring Application https://github.com/t-buss/sample-spring-app and added jib to the `build.gradle` file, then run  `./gradlew jibDockerBuild`
**Environment**: 
Windows 10, Gradle

**`jib-gradle-plugin` Configuration**: 
```groovy
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:2.0.3.RELEASE")
    }
}

plugins {
    id 'java'
    id 'com.google.cloud.tools.jib' version '0.9.2'
}

apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group 'Sample Spring App'
version '1.0-SNAPSHOT'

bootJar {
    baseName = 'sample-spring-app'
    version =  '0.1.0'
}

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile("org.springframework.boot:spring-boot-starter-web")
    testCompile group: 'junit', name: 'junit', version: '4.12'
}

```

**Log output**: 
`$ docker images`
`REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE`
`sample-spring-app          1.0-SNAPSHOT        564791ee361a        48 years ago        134MB`
**Additional Information**:

**Comment by coollog** [comment]
Hi @t-buss , this is to ensure reproducibility of the image, and was reported in #578 as well. Do you happen to need the creation timestamp for something?

**Comment by t-buss** [comment]
@coollog no, this is just a FYI

**Comment by chanseokoh** [comment]
@t-buss thanks. We have #413 open for this, so I'll close this. Feel free to update #413 if needs arise.
