### ISSUE TITLE
Handle Docker V2.1 image format or provide better error message.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#601]
Original comment by @jorgemoralespou https://github.com/GoogleContainerTools/jib/issues/534#issuecomment-404801072:

> I would think that nowadays there are very few (close to none) users with older versions of docker cli, but it would be good to support both schema1 and schema2 in the plugin, defaulting to schema2 but with the ability to override the value, and obviously a nicer error message explaining to the user what to do in case he get's a response from the registry that schema2 is not supported.

**Comment by briandealwis** [comment]
[`skopeo`](https://github.com/projectatomic/skopeo), a command-line tool for inspecting and copy container images, can read our tarballs and push the image to registries that only support v2-1 schemas.
```sh
$ mvn jib:buildTar
[…]
$ skopeo copy -dcreds user:pass tarball:target/jib-image.tar docker://quay.io/briandealwis/foo 
Getting image source signatures
Copying blob sha256:ca6b4ac8b25124deb3789851b58f94a1d31cab13af7d2ef9d64e3541d27e0973
 46.99 MB / 46.99 MB [======================================================] 8s
Copying config sha256:8d224412a288d1f8dcd66c74d263de411cf4a4f2753f03fe51700646d69ebabc
 420 B / 420 B [============================================================] 1s
Writing manifest to image destination
Copying config sha256:8d224412a288d1f8dcd66c74d263de411cf4a4f2753f03fe51700646d69ebabc
 0 B / 420 B [--------------------------------------------------------------] 0s
Writing manifest to image destination
Writing manifest to image destination
Storing signatures
```

Unfortunately there are no pre-built binaries of skopeo and installation is a bit… tricky (if you're a Go newbie like myself).

**Comment by jorgemoralespou** [comment]
@briandealwis, skopeo does not require any install. It uses go libraries internally and is a go binary, not sure how you can leverage it in jib, but I'm any case, if you need any type of help from Red Hat, you can reach out directly to @runcom, author of the tool for questions.

**Comment by briandealwis** [comment]
@jorgemoralespou: I was investigating whether skopeo as a workaround to save us from having to implement support for the v2-2 schema format, until registries like OpenShift and Quay.io support v2-2.  One possibility people could build to a tarball and then call out (somehow) to skopeo to push the build result to a v2-1 registry.

Skopeo does have some installation requirements: it requires installing a policy file to `/etc/containers/policy.conf`, and it requires gpgme to be installed somewhere.
