### ISSUE TITLE
can not push to harbor

### ISSUE THREAD

**Issue by qiankunli** [GoogleContainerTools/jib#625]
`mvn compile jib:build` is success, but there is no image existed in harbor.

environment 
1. os = mac
2. ide = idea

plugin config

```xml
                <plugin>
                    <groupId>com.google.cloud.tools</groupId>
                    <artifactId>jib-maven-plugin</artifactId>
                    <version>0.9.6</version>
                    <configuration>
                        <allowInsecureRegistries>true</allowInsecureRegistries>
                        <from>
                            <image>harbor.test.ximalaya.com/test/jdk8-tomcat8</image>
                        </from>
                        <to>
                            <image>harbor.test.ximalaya.com/test/jib-demo</image>
                        </to>
                        <container>
                            <mainClass>org.apache.catalina.startup.Bootstrap</mainClass>
                            <args>
                                <arg>start</arg>
                            </args>
                        </container>

                    </configuration>
                </plugin>
```

maven settings

```xml
      <server>
        <id>harbor.test.ximalaya.com</id>
        <username>admin</username>
        <password>mypassword</password>
      </server>
```

`mvn compile jib:build` output

```
[INFO] Retrieving registry credentials for harbor.test.ximalaya.com...
[INFO] Getting base image harbor.test.ximalaya.com/test/jdk8-tomcat8...
[INFO] Building dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO] Retrieving registry credentials for harbor.test.ximalaya.com...
[INFO] Finalizing...
[INFO] 
[INFO] Container entrypoint set to [java, -cp, /app/libs/*:/app/resources/:/app/classes/, org.apache.catalina.startup.Bootstrap]
[INFO] 
[INFO] Built and pushed image as harbor.test.ximalaya.com/test/jib-demo
```

**Comment by cai0329** [comment]
![image](https://user-images.githubusercontent.com/16819395/42757514-f3f1dc42-8932-11e8-9f42-c0368d1f5c12.png)
same as your maven config, I receive this error. did you meet this?

**Comment by qiankunli** [comment]
@cai0329 I meet this, but the reason for that is the error password

**Comment by coollog** [comment]
@cai0329 do you happen to be storing your password in encrypted form in your Maven settings? If so, we're patching a fix for that: #592 

@qiankunli Thanks for reporting this issue! We'll take a look at investigating this. @GoogleContainerTools/java-tools

**Comment by chanseokoh** [comment]
@cai0329 looking at the logs and your configuration, I believe you are pushing to a private repo, serving at port 5000. We currently have a few relevant issues:

1. If the repo at 5000 uses HTTPS, the current design of Jin requires the repo have a valid, trusted certificate. If you are using a self-signed certificate, you need a workaround: #543 
1. If the repo uses HTTP and requires authenthication, there is no way to make it work. By the current design, Jib does not send the password over HTTP, where other parties in the network can see.

We are discussing what would be the ideal ways to handle these sceanarios.

**Comment by qiankunli** [comment]
@chanseokoh but  i can not find image `harbor.test.ximalaya.com/test/jib-demo` in harbor, and there is not enough log to debug

**Comment by chanseokoh** [comment]
@qiankunli oh, sorry, looks like I got it wrong. Now I see you encountered your original issue after you provided a correct password. Please disregard my comments above.

**Comment by cai0329** [comment]
@chanseokoh You are right, when I use https it works correctly. But the same scene I met as @qiankunli.
, harbor registory can not find the image:
![image](https://user-images.githubusercontent.com/16819395/42863305-3b30379e-8a95-11e8-9c38-80d386516935.png)
![image](https://user-images.githubusercontent.com/16819395/42863341-54c44f4c-8a95-11e8-998d-aec202be2935.png)

**Comment by chanseokoh** [comment]
@cai0329 I saw you edited your comment. Is it all working now? What was the cause of the problem that you didn't see the image in the harbor repo?

**Comment by cai0329** [comment]
@chanseokoh The harbor ui delayed show the image. I think it is the problem of harbor. Thank you again!

**Comment by coollog** [comment]
@cai0329 Glad your issue was solved!
@qiankunli Is your issue still occurring?

**Comment by qiankunli** [comment]
@coollog it works in 0.9.7 thank you！
