### ISSUE TITLE
resource deduplication (strategies)

### ISSUE THREAD

**Issue by schmitch** [GoogleContainerTools/jib#634]
currently if a project is a multi project in maven/gradle (or even my implementation in [sbt](https://github.com/schmitch/sbt-jib)) resource would "break" the build. i.e. all layers would be correctly build, however a layer might be broken, if actually two resource files with different content would exist on the classpath. 
consider somebody adds a `lang.properties` file with different content, jib would break. most often the content of these files should just be merged together.

**Comment by coollog** [comment]
Hi @schmitch , first off, thanks for making the sbt plugin! Regarding this issue, what do you mean by "break" - ie. does Jib give an error, or does is the built container not what is expected?

**Comment by schmitch** [comment]
well if I have multiple `reference.conf` files in my subprojects (i tested that on gradle, too).
then **only one** is added to the docker image.
and the layer will raise an error:

```
[error] java.lang.Exception: Build to Docker daemon failed
[error]         at de.gccc.jib.SbtDockerBuild$.task(SbtDockerBuild.scala:61)
[error]         at de.gccc.jib.JibPlugin$.$anonfun$projectSettings$20(JibPlugin.scala:104)
[error]         at de.gccc.jib.JibPlugin$.$anonfun$projectSettings$20$adapted(JibPlugin.scala:99)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:39)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:66)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:263)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:272)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:263)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:174)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] Caused by: java.io.IOException: entry 'app/classes//hello.txt' closed at '5' before the '33' bytes specified in the header were written
[error]         at org.apache.commons.compress.archivers.tar.TarArchiveOutputStream.closeArchiveEntry(TarArchiveOutputStream.java:419)
[error]         at com.google.cloud.tools.jib.tar.TarStreamBuilder.writeEntriesAsTarArchive(TarStreamBuilder.java:63)
[error]         at com.google.cloud.tools.jib.blob.WriterBlob.writeTo(WriterBlob.java:36)
[error]         at com.google.cloud.tools.jib.cache.CacheWriter.writeLayer(CacheWriter.java:75)
[error]         at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:123)
[error]         at com.google.cloud.tools.jib.builder.steps.BuildAndCacheApplicationLayerStep.call(BuildAndCacheApplicationLayerStep.java:38)
[error]         at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:127)
[error]         at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
[error]         at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:80)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (jibDockerBuild) java.lang.Exception: Build to Docker daemon failed
```
(tried to include two hello.txt files)

The problem is also how "jib" is designed. I actually need to give paths instead of Path, String tuples for files that are included inside the image, thus it's basically impossible without further copying to fix it on the build system level.

**Comment by chanseokoh** [comment]
Seems like the overarching project is set up with, for example, multiple "modules" and some resources in some of the modules have the same name and path (e.g., property files such as `lang.properties`), so they end up overwriting each other?

I wonder how exactly the project is set up. Briefly describing the overall config and hierarchy of the project would be helpful, at least to me.

**Comment by chanseokoh** [comment]
> (tried to include two hello.txt files)

You can drap-and-drop a file in the GitHub comment input box.

**Comment by schmitch** [comment]
https://github.com/schmitch/jib-bug

Actually only the first `hello.txt` is included. (Currently in the gradle project the error is omitted, which is even worse since if a resource file (images, whatever) needs to be there it would fail at runtime)

**Comment by schmitch** [comment]
hm, ok, somehow I think I missed how it worked on gradle, gradle actually **always** adds all library files as a *.jar, however that is not the case in sbt.

**Comment by schmitch** [comment]
i.e. most of my problems will also be fixed via `https://github.com/GoogleContainerTools/jib/pull/516`. I guess.

**Comment by coollog** [comment]
@schmitch Also when we turn `jib-core` into a usable library #337 :)
