### ISSUE TITLE
support image tag

### ISSUE THREAD

**Issue by qiankunli** [GoogleContainerTools/jib#636]
it is necessary to support setting image tag automaticlly,  such as `<image>harbor.test.ximalaya.com/test/jib-demo:${build.time}</image>` , so that we can check the version of code easily

```
<plugin>
    <groupId>com.google.cloud.tools</groupId>
    <artifactId>jib-maven-plugin</artifactId>
    <version>0.9.6</version>
    <configuration>
        <allowInsecureRegistries>true</allowInsecureRegistries>
        <from>
            <image>harbor.test.ximalaya.com/test/jdk8-tomcat8</image>
        </from>
        <to>
            <image>harbor.test.ximalaya.com/test/jib-demo:${build.time}</image>
        </to>
        <container>
            <mainClass>org.apache.catalina.startup.Bootstrap</mainClass>
            <args>
                <arg>start</arg>
            </args>
        </container>

    </configuration>
</plugin>
```

**Comment by coollog** [comment]
Hi @qiankunli , we have [instructions for how to do that here](https://github.com/GoogleContainerTools/jib/wiki/Frequently-Asked-Questions-(FAQ)#how-can-i-tag-my-image-with-a-timestamp) :)

**Comment by chanseokoh** [comment]
@qiankunli I believe you will have no problem following the instructions, so I'm going to close this. If you still think Jib should should support something futher, feel free to re-open.

**Comment by chanseokoh** [comment]
FTR, you can now use `<container><useCurrentTimestamp>true<<useCurrentTimestamp></container>` too.

For more details about extended usage: https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage
