### ISSUE TITLE
Spring Boot Application containerizes but Tomcat Server doesn't start

### ISSUE THREAD

**Issue by saturnism** [GoogleContainerTools/jib#640]
**Description of the issue**:
1. Create a Rest service w/ Spring Boot, and add Jib to Maven `pom.xml`.
1. Validate that local run, default port 8080 is exposed.
1. Run `jib:build
1. Run the created container image
1. Notice the port isn't opened. Tomcat didn't start.

**Expected behavior**:
Created image should behave like the JAR.

**Steps to reproduce**: 
1. Build application here: https://github.com/saturnism/spring-cloud-gcp-guestbook/tree/master/11-kubernetes/guestbook-frontend
1. Build container w/ Jib.
1. Notice the port isn't opened.

**Environment**: 
MacOS, Maven

**`jib-maven-plugin` Configuration**: 
```xml
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <version>0.9.6</version>
  <configuration>
    <to>
      <image>gcr.io/.../guestbook-frontend</image>
    </to>
  </configuration>
</plugin>
```

**Log output**: 
Normal Startup w/o Jib
```
2018-07-17 14:09:02.191  INFO [-,,,] 60312 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started _org.springframework.integration.errorLogger
2018-07-17 14:09:02.485  INFO [-,,,] 60312 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
2018-07-17 14:09:02.488  INFO [-,,,] 60312 --- [           main] c.example.frontend.FrontendApplication   : Started FrontendApplication in 9.774 seconds (JVM running for 10.318)
```
Failed startup w/ Jib
```
springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2018-07-17 18:05:09.937  INFO [-,,,] 1 --- [           main] o.s.i.channel.PublishSubscribeChannel    : Channel 'application-1.errorChannel' has 1 subscriber(s).
2018-07-17 18:05:09.937  INFO [-,,,] 1 --- [           main] o.s.i.endpoint.EventDrivenConsumer       : started _org.springframework.integration.errorLogger
2018-07-17 18:05:09.967  INFO [-,,,] 1 --- [           main] c.example.frontend.FrontendApplication   : Started FrontendApplication in 9.085 seconds (JVM running for 9.892)
```

**Additional Information**:

**Comment by chanseokoh** [comment]
So, this use case is currently not supported in Jib. An application requires Google ADC, and the container which must be self-contained to run the application should be able to get the ADC from somewhere somehow. But I think this can be solved once we have features to add arbitrary files and define environment variables.

**Comment by chanseokoh** [comment]
Oh, BTW, I first had to add the `spring-milesontes` Maven artifact repository to my `~/.m2/settings.xml` for the `org.springframework.cloud:spring-cloud-gcp-dependencies`

```xml
  <profiles>
    <profile>
      <id>spring-milestones</id>
      <repositories>
        <repository>
          <id>spring-milestones</id>
          <name>Spring Milestones</name>
          <url>https://repo.spring.io/milestone</url>
        </repository>
      </repositories>
    </profile>
  </profiles>
  <activeProfiles>
    <activeProfile>spring-milestones</activeProfile>
  </activeProfiles>
```

and also had to downgrade the version of `org.springframework.cloud:spring-cloud-gcp-dependencies`:

```diff
                        <dependency>
                                <groupId>org.springframework.cloud</groupId>
                                <artifactId>spring-cloud-gcp-dependencies</artifactId>
-                               <version>1.1.0.BUILD-SNAPSHOT</version>
+                               <version>1.0.0.M4</version>
                                <type>pom</type>
                                <scope>import</scope>
                        </dependency>
```

**Comment by coollog** [comment]
> So, this use case is currently not supported in Jib.

@chanseokoh So we do have the `src/main/jib` extra files feature which could probably be used for this.
@saturnism I'll look more into this as well.

**Comment by chanseokoh** [comment]
Oh, is `src/main/jib` already usable? But I guess we don't have the feature to define arbitrary env variables yet (but will soon)?

**Comment by coollog** [comment]
@chanseokoh Yes it is usable, but in an incubating state (hence why there is no documentation).

**Comment by saturnism** [comment]
oops, is that default credential causing your start up issue?

the root issue is unrelated to adc. i.e., even w/ credential in place, the tomcat server didn't start.

**Comment by saturnism** [comment]
Easier to test w/ [1-bootstrap/guestbook-frontend](https://github.com/saturnism/spring-cloud-gcp-guestbook/tree/master/1-bootstrap) and add Jib to it.

1. `./mvnw spring-boot:run` <-- server starts and listens to port 8080
2. `./mvnw jib:build` then, run the container <-- tomcat server does not start, container exists

**Comment by chanseokoh** [comment]
> the root issue is unrelated to adc. i.e., even w/ credential in place, the tomcat server didn't start.

Oops... ADC was causing a problem, but yeah, you're right, the tomcat does not start with Jib, and I think I know why. If I look at the `META-INF/MANIFEST.MF`, this main class of this Spring-Boot-crafted excutable WAR (and probably JAR too?) that does some kind of black magic is supposed to be `org.springframework.boot.loader.WarLauncher`.

```
Main-Class: org.springframework.boot.loader.WarLauncher
Start-Class: com.example.frontend.FrontendApplication
...
```

What we instead have in `Dockerfile` is

```
ENTRYPOINT ["java","-cp","/app/libs/*:/app/resources/:/app/classes/","com.example.frontend.FrontendApplication"]
```

**Comment by coollog** [comment]
So, adding Jib to https://github.com/spring-projects/spring-petclinic and doing `./mvnw compile jib:build` generates a container that starts Tomcat fine. I'm looking at what difference there could be in this case.

**Comment by chanseokoh** [comment]
FYI, in the case of Spring-Boot-craft executable JAR (i.e., `<packaing>jar</packaing>` instead of `<packaing>war</packaing>`), the main class is set to the JAR launcher:

```
Main-Class: org.springframework.boot.loader.JarLauncher
Start-Class: com.example.frontend.FrontendApplication
```

Explicitly setting `org.springframework.boot.loader.WarLauncher` (or `JarLauncher`) as the main class in Jib's configuration won't work, because these launchers require additional classes and library that Spring Boot injects at the time of packaging a WAR or a JAR.

**Comment by saturnism** [comment]
I have been able to create a Jar archive w/ custom manifest w/ the app as the main class. See https://github.com/saturnism/spring-petclinic-gcp/blob/master/pom.xml#L146

**Comment by chanseokoh** [comment]
> whereas @saturnism's application basically retains the WAR structure from which Spring Boot has the ability to create either an (executable) WAR or a JAR with some black magic.

I might be wrong with the "WAR structure" terminology... but I am still thinking it is this `ServletInitializer` that makes the different, which enables Spring Boot to create a magical executable WAR.

> I have been able to create a Jar archive w/ custom manifest w/ the app as the main class. See https://github.com/saturnism/spring-petclinic-gcp/blob/master/pom.xml#L146

@saturnism FYI, Jib does not take a JAR from somewhere or even attempt to package a JAR. It doesn't use a JAR at all, but puts individual class files into the container; there is no JAR packaging at all. That could explain why we have problems with Spring Boot here.

**Comment by saturnism** [comment]
Removing servlet initializer doesn't nor should change anything. The ServletInitializer is for initialization inside of an application server, like Jetty.

Spring Petclinic also packages the Manfiest w/ JarLauncher.

**Comment by coollog** [comment]
So I've found that the `tomcat-embed-core` JARs (like `tomcat-embed-core-8.5.31.jar`) are not being added to the guestbook image, which I believe are necessary for the embedded tomcat startup. They do appear in the petclinic image, which is why that starts.

**Comment by coollog** [comment]
Adding

```xml
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-core</artifactId>
		</dependency>
```

Made it work for me.

**Comment by coollog** [comment]
Not sure why it wasn't being added since `spring-boot-starter-web` includes `spring-boot-starter-tomcat`, which includes `tomcat-embed-core`.

**Comment by coollog** [comment]
Ah I found it: @saturnism 

```xml
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
```

The scope is set to `provided`, but should be none/`compile`.

**Comment by malithsumuditha** [comment]
> Ah I found it: @saturnism
> 
> ```
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-tomcat</artifactId>
> 			<scope>provided</scope>
> 		</dependency>
> ```
> 
> The scope is set to `provided`, but should be none/`compile`.

Thank you very much for this clarification
