### ISSUE TITLE
Change "-Djib.dockerDir" in maven plugin for consistency

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#662]
In gradle, the configuration option is `targetDir`, and the parameter is `--targetDir`.

In maven, the configuration option is `targetDir`, and the parameter is `-Djib.dockerDir`. We should make it more consistent (something like `-Djib.targetDir`, or maybe even just `-DtargetDir`).

**Comment by chanseokoh** [comment]
Personally I vote for `jib.targetDir`. `-DtargetDir` sounds too general that may easily conflict with others.

**Comment by coollog** [comment]
I believe the issue with Gradle is that it doesn't allow for `.` in the property name. It might have to be `jibTargetDir`

**Comment by TadCordle** [comment]
Change it to jibTargetDir for both?

**Comment by coollog** [comment]
Sounds good!
