### ISSUE TITLE
Document sendCredentialsOverHttp and jib.httpTimeout system properties

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#668]
Should be merged after releasing 0.9.7.

Note that `sendCredentialsOverHttp` is effective only when `allowInsecureRegistries` is set and the HTTPS-to-HTTP fallback happens.

**Comment by chanseokoh** [comment]
These items are being handled by https://github.com/GoogleContainerTools/jib/pull/664#issue-202624367, so closing.

**Comment by yanhongwang** [comment]
Hello @chanseokoh 

Where can I set 'sendCredentialsOverHttp' for Jib?
I couldn't find that in document...
https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin

Thanks much.

**Comment by chanseokoh** [comment]
It's in the FAQ: https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-can-i-diagnose-problems-pulling-or-pushing-from-remote-registries

To discourage its usage, we've not documented it in an prominent way. It is the system property, so for Maven, you can set it by `-DsendCredentialsOverHttp=true` on the command line.
