### ISSUE TITLE
Consider detecting embedded servlet engines marked as "provided" scope.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#675]
From https://github.com/GoogleContainerTools/jib/issues/658#issuecomment-406263039
And https://github.com/GoogleContainerTools/jib/issues/640#issuecomment-405729035

And either providing the user with useful feedback or automatically adding the dependency.

**Comment by chanseokoh** [comment]
Now with the WAR support, people can do WAR packaging. Alternatively, this can be resolved with JAR packaging we are going to implement. (#530)
