### ISSUE TITLE
Extreme long parsing time for long repository values in the <to> field

### ISSUE THREAD

**Issue by hubermi** [GoogleContainerTools/jib#678]
**Description of the issue**:

When defining long docker repository names the parsing process takes extremely long, causing the mvn build job (gradle build job should be affected, too as the root cause is in jib-core) to run with 100% CPU.

**Expected behavior**:
String length should not have a big impact on parsing time.

**Additional Information**:
The root cause is the class com.google.cloud.tools.jib.image.ImageReference;
If calling the parse(String reference) method with a repository value that has 27 characters, it takes about 10 seconds to complete. With 28 characters (like in the example above) it takes about 20 seconds, with 29 characters about 40 seconds ...

**Comment by coollog** [comment]
Hi @hubermi , thanks for reporting the issue! This is related to #323. Labeling this will high priority.

**Comment by coollog** [comment]
The fix will be available in the next release (version `0.9.8`).

**Comment by coollog** [comment]
@hubermi we've released version `0.9.8` and this issue should be fixed in that version.
