### ISSUE TITLE
Setting auth credentials from command line or environment variable

### ISSUE THREAD

**Issue by victornoel** [GoogleContainerTools/jib#693]
In the case jib-maven-plugin is used in a CI environment, it can be useful to pass the authentication credentials directly via the command line or via environment variable.

For example with Gitlab CI, it is the case that CI jobs have environment variables with temporary tokens to push images to the Gitlab Registry.

Currently, it seems to me that the only way to take advantage of these is either via `docker login` (which means I need docker installed now) or via some hack by generating a custom `settings.xml`.

It would be great either to have jib-maven-plugin accept credentials via command line or to document what is the preferred way to achieve the requirement.

**Comment by victornoel** [comment]
> Just FYI, copying a working .docker/config into your CI env will also work. Jib doesn't use docker but just reads the file to get credentials.

That's what I had understood, maybe as a workaround there are "simpler" ways to generate the content of this file without using docker… but I suppose the information is not there in its raw form.

**Comment by briandealwis** [comment]
Could you write a simple [docker credential helper script](https://github.com/docker/docker-credential-helpers#development) that returns the appropriate environment values?  You'd configure that helper with your [`<to><credHelper>`](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#extended-usage) / (`to.credHelper`](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin#extended-usage).

**Comment by coollog** [comment]
We could also consider adding `auth` to the image configurations for `jib-maven-plugin` as well, so people could do:

```xml
<configuration>
    <to>
        <image>imagename</image>
        <auth>
            <username>${env.REGISTRY_USERNAME}</username>
            <password>${env.REGISTRY_PASSWORD}</password>
        </auth>
    </to>
</configuration>
```

and be able to use `REGISTRY_USERNAME` and `REGISTRY_PASSWORD` environment variables as the credentials.

**Comment by victornoel** [comment]
@coollog I had something like that in mind when I opened the issue yes. Also there should be an expression (in maven lingo) associated to each of those so that one can pass it via `-Djib.to.auth.username=XXX` (or something like that) too.

**Comment by victornoel** [comment]
Thanks @TadCordle :)

**Comment by TadCordle** [comment]
No problem! Will be available when 0.9.8 releases.

**Comment by coollog** [comment]
@victornoel version 0.9.8 is released with these features :)

**Comment by victornoel** [comment]
@coollog @TadCordle thanks, it works well, I just tested it.

For the record, the README wasn't updated with the new options.

**Comment by TadCordle** [comment]
Just updated it. Thanks again for your suggestions!
