### ISSUE TITLE
Update credential retrieval order

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#724]
Current order has explicit username/password checked before cred helpers in build config, but the new order should be
1. Username/password system properties
2. Username/password in build config
3. Cred helper in build config
4. Maven settings
5. Common cred helpers
6. Docker config

**Comment by coollog** [comment]
Hmm, looks like we should probably have credentials be refactored to be provided in via a common interface like how the layers were - perhaps via a list of RegistryCredentialProvider.
