### ISSUE TITLE
Wrong error message when auth failed on target registry

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#758]
From https://github.com/GoogleContainerTools/jib/issues/712#issuecomment-409403379

The log clearly shows that it's failing on the target registry, but the same log says at the end

`> Build image failed, perhaps you should set a credential helper name with the configuration 'from.credHelper' or from.auth`

It should say 'to.credHelper' or to.auth. Bonus for being consistent with single quotes.

**Comment by chanseokoh** [comment]
This actually confused the user to take a wrong action:

https://github.com/GoogleContainerTools/jib/issues/712#issuecomment-408647611
> albeit I had to put my username/password to pull a public image from docker hub.

https://github.com/GoogleContainerTools/jib/issues/712#issuecomment-409403379
> I did not have an auth field originally and got this error so I assumed I needed one and added it.

**Comment by briandealwis** [comment]
Oh jeepers, I meant to file this from #620.

**Comment by TadCordle** [comment]
Ah I think I found the issue.

```
      boolean isRegistryForBase =
          registryUnauthorizedException
              .getRegistry()
              .equals(buildConfiguration.getBaseImageConfiguration().getImageRegistry());
      boolean isRegistryForTarget =
          registryUnauthorizedException
              .getRegistry()
              .equals(buildConfiguration.getTargetImageConfiguration().getImageRegistry());
      boolean areBaseImageCredentialsConfigured =
          buildConfiguration.getBaseImageConfiguration().getCredentialHelper() != null
              || buildConfiguration.getBaseImageConfiguration().getKnownRegistryCredentials()
                  != null;
      boolean areTargetImageCredentialsConfigured =
          buildConfiguration.getTargetImageConfiguration().getCredentialHelper() != null
              || buildConfiguration.getTargetImageConfiguration().getKnownRegistryCredentials()
                  != null;

      if (isRegistryForBase && !areBaseImageCredentialsConfigured) {
        throw new BuildStepsExecutionException(
            helpfulSuggestions.forNoCredentialHelpersDefinedForBaseImage(
                registryUnauthorizedException.getRegistry()),
            registryUnauthorizedException);
      }
      if (isRegistryForTarget && !areTargetImageCredentialsConfigured) {
        throw new BuildStepsExecutionException(
            helpfulSuggestions.forNoCredentialHelpersDefinedForTargetImage(
                registryUnauthorizedException.getRegistry()),
            registryUnauthorizedException);
      }
```

If the base image registry and target image registry are the same, we assume the problem is with the base image credentials.
