### ISSUE TITLE
Add integration test for various project configurations.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#76]
- [x] Simple project
- [x] Empty project (no dependencies/no resources/an empty main class)
- [x] Blank project (no dependencies/no resources/no classes)
- [ ] Multi-module project with single root build script (Gradle)
- [ ] Multi-module project with Maven
- [x] Complex project (using every parameter)
- [ ] Build as OCI image format (requires a bit more setup on our end)
- [ ] Other languages (Groovy, Kotlin)

**Comment by wilder** [comment]
@coollog, I would like to add integration tests for Kotlin, but I'm not sure where to start.

**Comment by coollog** [comment]
Hi @wilder , thanks for offering to contribute! Here's some tips for how to get started:

1. Read the [CONTRIBUTING](https://github.com/GoogleContainerTools/jib/blob/master/CONTRIBUTING.md) guide - you probably want to make sure you can run your integration tests since this is explicitly adding integration tests (if this is not possible feel free to skip those and we can run them from our side)
1. I'm assuming this would be only for Gradle since it seems to the build tool of choice for Kotlin developers, and the integration-test projects for `jib-gradle-plugin` are under [the integration-test resources](https://github.com/GoogleContainerTools/jib/tree/master/jib-gradle-plugin/src/integration-test/resources/projects)
1. Check out the other integration-test projects as examples.
1. Create a new integration-test project for Kotlin.
1. Add the corresponding test code in [JibPluginIntegrationTest.java](https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/src/integration-test/java/com/google/cloud/tools/jib/gradle/JibPluginIntegrationTest.java)
1. File a pull request and get approved :)

Thanks! Let us know if you run into any issues!

**Comment by coollog** [comment]
@wilder Also, I'd recommend making a new issue and referencing this issue so that we can better organize any discussions we have.

**Comment by coollog** [comment]
Closing as we have added many integration tests.
