### ISSUE TITLE
Update CHANGELOG for 0.9.8 release.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#765]
Set unreleased to 0.9.8 and set up new unreleased section.

**Comment by TadCordle** [comment]
Should also replace all instances of `0.9.7` -> `0.9.8`, and `0.9.8-SNAPSHOT` -> `0.9.9-SNAPSHOT` (when should we do this?)

**Comment by coollog** [comment]
Yep I think it could all be a part of a single PR.
