### ISSUE TITLE
Reverse order of classpath to allow patching

### ISSUE THREAD

**Issue by tobad357** [GoogleContainerTools/jib#777]
**Description of the issue**:
Overriding dependency classes is impossible due to classpath order when generating
startup command.

Sometimes it is necessary to patch a class in the dependencies.
To get this to work the classpath would need to load application classes first and then 
lib classpath

Current Entrypoint 
``` ENTRYPOINT ["java","-Xms512m","-Xdebug","--spring.config.name","${APP_NAME}","--spring.config.location","${CONFIG_FILES}","-cp","/app/libs/*:/app/resources/:/app/classes/","com.app.AppStart"]```

**Expected behavior**:
The app classes dir would be first in the classpath
``` ENTRYPOINT ["java","-Xms512m","-Xdebug","--spring.config.name","${APP_NAME}","--spring.config.location","${CONFIG_FILES}","-cp","/app/resources/:/app/classes/:/app/libs/*","com.app.AppStart"]```

**Steps to reproduce**: 
1. Build any project with gradle jibExportDockerContext
2. View the generated Dockerfile

**Environment**: gradle

**Comment by coollog** [comment]
Hi @tobad357 , thanks for the suggestion! This definitely sounds like a useful feature and we will have this patched for the next version release (`0.9.9`).

**Comment by coollog** [comment]
Hi @tobad357 , we have reversed the classpath order in version `0.9.9` - let us know if this works for you.

**Comment by coollog** [comment]
Hi @anuraaga thanks for the tip! We were thinking to keep `resources` before classes in case one wished to replace some class file in `classes` with a file in `resources`, whereas the reverse does not seem to be of any use (replacing resource file with file in `classes`). However, mimicking the behavior of the `run` task may be the right way to go @GoogleContainerTools/java-tools

**Comment by briandealwis** [comment]
I think your reasoning makes sense @coollog.

**Comment by TadCordle** [comment]
Agreed, I think we gain more here the way we currently have it vs following convention.

**Comment by coollog** [comment]
Closing unless any objections to keeping it the way it is.

**Comment by anuraaga** [comment]
Feel free to keep this closed :) Just want to ask for one more thought though. Currently, this means that users could see different behavior when using gradle's `run` (which is commonly used from normal IntelliJ running with the Gradle runner) and `docker run` of a jib image. It's also different than gradle's `distribution` plugin which runs a jar - the jar packages classes before resources so the JRE will prefer classes. Basically, any Gradle user is highly likely to currently to rely on behavior that prioritizes classes over resources regardless of their running / deployment strategy.

I think it can be very surprising to users to see different behavior for `run` and `docker run` and might reduce trust in the plugin. I'd recommend giving one more look from a user's perspective - if this Gradle plugin decides not to match Gradle's behavior, I would at least think that should be mentioned in the `README`.

**Comment by briandealwis** [comment]
Although the Maven `exec:java` [doesn't add resources to the classpath by default](https://www.mojohaus.org/exec-maven-plugin/java-mojo.html#addResourcesToClasspath), when configured to do so (`addResourcesToClasspath=true`) then it adds [resources](
https://github.com/mojohaus/exec-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/exec/AbstractExecMojo.java#L154), then [classes](
https://github.com/mojohaus/exec-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/exec/AbstractExecMojo.java#L167), then [dependencies](
https://github.com/mojohaus/exec-maven-plugin/blob/2dfcf2c552c3033f444a71fdc69633f8d8d462a9/src/main/java/org/codehaus/mojo/exec/ExecJavaMojo.java#L600).
