### ISSUE TITLE
Cannot find default setter in class com.google.cloud.tools.jib.maven.JibPluginConfiguration$FromConfiguration

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#791]
@DidierSchonne

From https://github.com/GoogleContainerTools/jib/issues/746#issuecomment-410205942:

Besides that I tried to add a `<from>openjdk:10-jre</from>` or `<from>openjdk:10</from>` tag into `<configuration>` like in the doc and Jib crashes :

`Unable to parse configuration of mojo com.google.cloud.tools:jib-maven-plugin:0.9.8:build for parameter from: Cannot find default setter in class com.google.cloud.tools.jib.maven.JibPluginConfiguration$FromConfiguration`

**Comment by chanseokoh** [comment]
Ah, it should be

```xml
<from><image>openjdk:10-jre</image></from>
```

**Comment by chanseokoh** [comment]
@DidierSchonne put `<image>` inside `<from>`. I don't find a doc without `<image>`. I'll close this issue, but if you find a doc in error, please re-open.

**Comment by DidierSchonne** [comment]
@chanseokoh, my apologies, I dig out a very old doc through Google, shame on me.
