### ISSUE TITLE
how do i copy customer files to the image.

### ISSUE THREAD

**Issue by vijaypothireddy** [GoogleContainerTools/jib#798]
i want to copy some custom config files to the docker image and also run postgres as part of the docker image, is there a way i can do it  ?

vijay

**Comment by coollog** [comment]
Hi @vijaypothireddy , you can use `src/main/resources` to copy custom config files into the Docker image. However, for running Postgres, we would not recommend running that in the same Docker image - each container should be a single process and take care of a single concern. Closing, but feel free to comment further if there are any further questions.
