### ISSUE TITLE
 mvn compile jib:build freezing after Finalizing 

### ISSUE THREAD

**Issue by mushtaqck** [GoogleContainerTools/jib#806]
**Description of the issue**: mvn compile jib:build freezing after Finalizing 58mb container takes 11 min to upload to ECS.

**Expected behavior**: Some message is excepted while upload is in progress. 

**Steps to reproduce**: 
mvn clean
mvn compile jib:build

**Environment**: maven

**`jib-maven-plugin` Configuration**:<plugin>
				<groupId>com.google.cloud.tools</groupId>
				<artifactId>jib-maven-plugin</artifactId>
				<version>0.9.7</version>
				<configuration>
			               <to>
						<image>XXXXXXX.dkr.ecr.eu-west-1.amazonaws.com/name-jib</image>
						<credHelper>ecr-login</credHelper>
					</to>
					<mainClass>com.aws.transformation.Main</mainClass>
				</configuration>
			</plugin>

**Log output**: 
[INFO] Finalizing...
[DEBUG] TIMING  Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@fa0bad6
[DEBUG] TIMING  Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@64a82d82
[DEBUG] TIMING  Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@a44292c0
[DEBUG] RUNNING Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@64a82d82
[DEBUG] RUNNING Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@fa0bad6
[DEBUG] TIMING  Pushing container configuration
[DEBUG] RUNNING Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@a44292c0
[DEBUG] RUNNING Pushing container configuration
[DEBUG] TIMED   Pushing container configuration : 31.345 ms
[DEBUG] TIMING  Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@c2d7a77f
[DEBUG] RUNNING Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@c2d7a77f
[DEBUG] Pushing container configuration : 31.345 ms
[DEBUG] BLOB : com.google.cloud.tools.jib.blob.BlobDescriptor@fa0bad6 already exists on registry
[DEBUG] TIMED   Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@fa0bad6 : 1081.532 ms
[DEBUG] Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@fa0bad6 : 1081.532 ms
[DEBUG]         TIMING  pushBlob
[DEBUG] BLOB : com.google.cloud.tools.jib.blob.BlobDescriptor@c2d7a77f already exists on registry
[DEBUG]                 TIMING  pushBlob POST sha256:e55f91cfcc4c37eae015b13ca9634aa854a6370232eb6188586e6434d3305774
[DEBUG] TIMED   Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@c2d7a77f : 1052.243 ms
[DEBUG] Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@c2d7a77f : 1052.243 ms
[DEBUG] BLOB : com.google.cloud.tools.jib.blob.BlobDescriptor@64a82d82 already exists on registry
[DEBUG] TIMED   Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@64a82d82 : 1124.42 ms
[DEBUG] Pushing BLOB com.google.cloud.tools.jib.blob.BlobDescriptor@64a82d82 : 1124.42 ms
[DEBUG]                 TIMED   pushBlob POST sha256:e55f91cfcc4c37eae015b13ca9634aa854a6370232eb6188586e6434d3305774 : 1105.674 ms

**Additional Information**: 
It took 11 minutes to build and upload 58mb container. Some progress message will help in this case.

[DEBUG] TIMED   Pushing BLOB digest: sha256:e55f91cfcc4c37eae015b13ca9634aa854a6370232eb6188586e6434d3305774, size: 38708287 : 658524.746 ms
[DEBUG] Pushing BLOB digest: sha256:e55f91cfcc4c37eae015b13ca9634aa854a6370232eb6188586e6434d3305774, size: 38708287 : 658524.746 ms
[DEBUG] TIMING  Pushing new image
[DEBUG] RUNNING Pushing new image
[DEBUG] TIMED   Pushing new image : 1868.794 ms
[DEBUG] Pushing new image : 1868.794 ms
[DEBUG] TIMED   Building and pushing image : 664238.621 ms
[DEBUG] Building and pushing image : 664238.621 ms
[INFO]
[INFO] Container entrypoint set to [java, -cp, /app/libs/*:/app/resources/:/app/classes/, com.aws.transformation.Main]
[INFO]
[INFO] Built and pushed image as xxxxxxxx
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11:07 min
[INFO] Finished at: 2018-08-01T19:33:50+05:30
[INFO] ------------------------------------------------------------------------

**Comment by chanseokoh** [comment]
Hi @mushtaqck

Are you suggesting that it is a bug that Jib takes 11 minutes to push to ECS, or it's normal that ECS is slow and Jib should just print out helpful messages or a progression bar if pushing or pulling takes long?

**Comment by mushtaqck** [comment]
Hi,

This is a suggestion to add some message to indicate the progress of upload.
I am not sure if it is normal to take 11 minutes for first push of 58mb to ECS that might depend on  connection speed (but my connection is fast) .
