### ISSUE TITLE
Consider making javassist an optional dependency or move to separate module.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#841]
javassist is only used for `MainClassFinder`, so it should either be:
- made optional so that the dependency is only required if the user of Jib Core uses `MainClassFinder` (and other Java-specific code), or
- moved along with other Java-specific code to a separate module like `jib-core-extensions`

**Comment by TadCordle** [comment]
Adjusted the milestone for this one since we decided yesterday that it's low priority.

**Comment by briandealwis** [comment]
I thought we were using javassist as it had a psvm-finder built in.  Since it doesn't — and it weighs in at 700k — another candidate to consider is [ASM 6.x](https://asm.ow2.io)(110k).
