### ISSUE TITLE
Allow setting an entry point to an explicit pathed binary

### ISSUE THREAD

**Issue by jrivard** [GoogleContainerTools/jib#850]
**Description of the issue**:
I'm trying to use an image where the entry point is not the java binary, and the java binary is in a different path than the default distroless image.  (Specifically, adoptopenjdk/openjdk10)

**Expected behavior**:
I should be able to specify the image's java execution path

**Comment by coollog** [comment]
Hi @jrivard , thanks for suggesting this feature. We are considering allowing a custom entrypoint to be defined in #579.

**Comment by coollog** [comment]
@jrivard We have added support for defining a custom entrypoint via `<container><entrypoint>`. It is available in version `0.9.10`.
