### ISSUE TITLE
Templating for Docker-Compose-, Docker Stack-Files

### ISSUE THREAD

**Issue by silasmahler** [GoogleContainerTools/jib#855]
Is there an option to template Docker-Compose or Stack files?

My Issue: 

I'm using a gradle plugin for project-versioning with the Git-Commit-Hash.
This hash is passed to the dockerimage as a tag to produce a reproducable imagebuild for the commit.
Works well with jib and i like the layerd imagebuild so it saves a lot of time .

In my docker-compose and docker-stack file i dont want to adjust the version manually, so im looking for a way of templating a Docker-Swarm conform docker-compose file with the generated git-hash as a tag, so i can run it immediately. 

My goal is to create a local pipeline that generates a new version when i commit and build my project and have it deployed to a minimal local docker-swarm automatically for testing.

Is there a feature im missing or would this be something jib isnt possible to do atm.

Thanks for feedback

**Comment by patflynn** [comment]
@silasmahler this sounds like something you could configure yourself with resource filtering in your build system.  Are you using Maven or Gradle?

**Comment by silasmahler** [comment]
@patflynn Im using gradle

**Comment by patflynn** [comment]
@loosebazooka is the expert, but we've had success using a strategy like this one: https://stackoverflow.com/questions/25328132/is-resource-filtering-in-gradle-possible-without-using-tokens

Here's how we used it in the IntelliJ plugin:
https://github.com/GoogleCloudPlatform/google-cloud-intellij/blob/2bfe84354116b7eb15a436086ec4db5233c014c0/google-cloud-core/build.gradle#L69

Seems like you could use a similar template parameter in your docker compose file assuming you can assign your git-commit-hash value from gradle.

**Comment by silasmahler** [comment]
@patflynn Thanks for your help! - it worked :)

My initial gradlefile looks something like this, it needs to be made generic for multi-module-projects and respect other variables in the .env-file , but serves the inital propose.
Maybe i'll rewrite it to parse docker-compose-files later and hand it down as a plugin.

```
project.version = versionDetails().gitHash 

...

task buildDockerComposeEnv {
    doLast {
        new File("./../.env").setText("VERSION={$project.version}")
    }
}
tasks.build.dependsOn buildDockerComposeEnv
```

Turns out its really good if you know your buildtool, i'll definetely learn more about it.

Greetings from Germany :)

**Comment by patflynn** [comment]
@silasmahler happy it worked! 👍
