### ISSUE TITLE
jib push image to harbor success but not image in harbor web.

### ISSUE THREAD

**Issue by dragontree101** [GoogleContainerTools/jib#876]
**Description of the issue**:
jib push image to harbor success but not image in harbor web.

**Expected behavior**:
in harbor i can see i pushed image

**Steps to reproduce**: 
mvn clean package

**Environment**: 
macos
maven
jib-maven-plugin 0.9.9

**`jib-maven-plugin` Configuration**: 
```xml
PASTE YOUR pom.xml CONFIGURATION HERE
<plugin>
          <groupId>com.google.cloud.tools</groupId>
          <artifactId>jib-maven-plugin</artifactId>
          <version>0.9.9</version>
          <configuration>
            <from>
              <image>openjdk:8u111-jre-alpine</image>
            </from>
            <to>
              <image>10.10.30.38/library/test-spring-boot:1.0.0-SNAPSHOT</image>
              <auth>
                <username>admin</username>
                <password>Harbor12345</password>
              </auth>
            </to>
            <container>
              <ports>
                <port>8080</port>
              </ports>
            </container>
            <allowInsecureRegistries>true</allowInsecureRegistries>
          </configuration>
          <executions>
            <execution>
              <phase>install</phase>
              <goals>
                <goal>build</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
```

**`jib-gradle-plugin` Configuration**: 
```groovy
PASTE YOUR build.gradle CONFIGURATION HERE
```

**Log output**: 

**Additional Information**: 

```
[INFO] Finalizing...
[WARNING] Failed to connect to https://10.10.30.38/v2/library/svc1/blobs/sha256:cd134db5e982d5650745e9479866c856f24b892a92c4bfad3f3de6fd1bb7cc6d over HTTPS. Attempting again with HTTP: http://10.10.30.38/v2/library/svc1/blobs/sha256:cd134db5e982d5650745e9479866c856f24b892a92c4bfad3f3de6fd1bb7cc6d
[WARNING] Failed to connect to https://10.10.30.38/v2/library/svc1/blobs/sha256:fc4b8626a0a82a7a49e910bac186669d936c2185db7fe16d007d75832203d4b2 over HTTPS. Attempting again with HTTP: http://10.10.30.38/v2/library/svc1/blobs/sha256:fc4b8626a0a82a7a49e910bac186669d936c2185db7fe16d007d75832203d4b2
[WARNING] Failed to connect to https://10.10.30.38/v2/library/svc1/blobs/uploads/ over HTTPS. Attempting again with HTTP: http://10.10.30.38/v2/library/svc1/blobs/uploads/
[WARNING] Failed to connect to https://10.10.30.38/v2/library/svc1/manifests/1.0.0-SNAPSHOT over HTTPS. Attempting again with HTTP: http://10.10.30.38/v2/library/svc1/manifests/1.0.0-SNAPSHOT
[INFO]
[INFO] Container entrypoint set to [java, -Xms712m -Xmx712m, -cp, /app/resources/:/app/classes/:/app/libs/*, com.k8s.test.Svc1Application]
[INFO]
[INFO] Built and pushed image as 10.10.30.38/library/svc1:1.0.0-SNAPSHOT
```

but in harbor i can't see this image in library project

![image](https://user-images.githubusercontent.com/1763935/44567050-4c839600-a7a3-11e8-82dc-b4359c1b9dc2.png)

**Comment by dragontree101** [comment]
i found in harbor's web can not find image, but i can pull image from harbor and i found data in harbor's machine filesystem, i guess this is jib bug or harbor web bug?

**Comment by coollog** [comment]
@dragontree101 Did the image eventually show up? If not feel free to reopen this issue.

**Comment by dragontree101** [comment]
https://github.com/goharbor/harbor/issues/5729 
i open new issue in harbor, seems jib change ua's head

**Comment by chanseokoh** [comment]
Jib uses its own User-Agent value, just like any clients would do, including Docker. It is not that Jib delegates to Docker for pushing an image; Jib pushes an image directly, identifying itself as Jib through the UA header. It will make no sense for Jib to disguise itself as if it is a Docker client. Obviously, looks like it is the policy of Harbor that it accepts requests only from Docker, so it is really the Harbor that should be fixed if it wants to accept requests from other clients than Docker.
