### ISSUE TITLE
jib push harbor connection refused

### ISSUE THREAD

**Issue by JoeToffler** [GoogleContainerTools/jib#885]
plugin config
![pom1](https://user-images.githubusercontent.com/31876954/44701057-3e918600-aabf-11e8-974d-045cfb55016a.PNG)

error
![error](https://user-images.githubusercontent.com/31876954/44700827-e73ee600-aabd-11e8-9bf4-d7ba53315aae.PNG)

and I try to set allowInsecureRegistries=true,but it error too
![error2](https://user-images.githubusercontent.com/31876954/44700918-6b916900-aabe-11e8-997b-303d185b346b.PNG)

Please help me to solve this question,thank you very much!

**Comment by chanseokoh** [comment]
Hi @JoeToffler,

`sendCredentialsOverHttp` is not a configuration parameter but a system property. Try `mvn -DsendCredentialsOverHttp=true jib:build`. (You should know what it means by sending a password over HTTP.)

**Comment by Hernaldo** [comment]
how set this value in a Settings.xml or Config.json?

**Comment by chanseokoh** [comment]
@Hernaldo unfortunately, if you're on Maven, it's not possible to set `sendCredentialsOverHttp` in any build or config file. For the time being, you must pass `-DsendCredentialsOverHttp` on the command line. (OTOH, Gradle won't be a problem, as you can do anything in `build.gradle`.) We may lift this restriction when we fix #1923.
