### ISSUE TITLE
Consider using ContainerConfigurationHistory instead of a HistoryEntry list in Image

### ISSUE THREAD

**Issue by TadCordle** [GoogleContainerTools/jib#889]
Original comment: https://github.com/GoogleContainerTools/jib/pull/877#discussion_r213356053

>I think this might better belong under the image.json package, next to ContainerConfigurationTemplate.
>
>I'm thinking it might make more sense to call this ContainerConfigurationHistory and have it manage the actual JSON templates. Then, Image will have a ContainerConfigurationHistory and not have to directly manage HistoryEntry JSON templates.

**Comment by TadCordle** [comment]
I've been looking at this/experimenting with some refactoring for the past couple days, and I'm not really seeing much improvement. Just using lists and directly building the `HistoryEntry`s seems simpler than trying to abstract away the JSON handling. `Image` doesn't really do any processing on the `HistoryEntry`s in the first place, just stores them; most of the processing happens in `BuildImageStep`, but even there I'm not sure I like the idea of separating the `HistoryEntry` building logic from the layer processing, since they're so closely tied together. Adding another layer between `Image` and `HistoryEntry` just seems to add more complexity than it's worth.

I'm going to close this, but if you feel strongly about it we can reopen.

**Comment by coollog** [comment]
Closing again, because, as mentioned, the change was not worth it.
