### ISSUE TITLE
Add `chown` configuration parameter to set groupId and userId for files.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#892]
**NOT READY**

Regards #727

Add a configuration to `jib-maven-plugin`/`jib-gradle-plugin` that can define the userid/groupid to set for the files we build into the container, similar to how Dockerfile's `COPY --chown` works. The container configuration `User` field should also be set accordingly.

`chown` can either be a single uid or a string of the form `uid:gid`.

So, for example, in your case, the configuration could look something like:

Maven:
```
<configuration>
  ...
  <container>
    <chown>10:11</chown>
  </container>
</configuration>
```

Gradle:
```
jib.container.chown = 10000
```

Tasks:

- [ ] Add `OwnerGroup` to represent a pair of user id and group id (group id defaults to user id if not given).
- [ ] Add `User` field to `ContainerConfigurationTemplate`.
- [ ] Add `OwnerGroup` to `BuildConfiguration`.
- [ ] Use `OwnerGroup` to build the layer files.
- [ ] Add `jib-maven-plugin` `chown` parameter.
- [ ] Add `jib-gradle-plugin` `chown` parameter.

**Comment by coollog** [comment]
Closing unless found necessary again.

**Comment by chanseokoh** [comment]
Just FTR: files are already readable and possibly executable for any, so it doesn't seem necessary to set user and group IDs. At least we don't see a use case for it for now.
