### ISSUE TITLE
Add Support for use CMD to start container

### ISSUE THREAD

**Issue by swift1911** [GoogleContainerTools/jib#924]
I use supervise like s6-overlay to handle PID 1 for container, jib plugin use entrypoint to start container and overwrite my baseimage entrypoint, so i want to use CMD to start jib generated container 

like this:
```
<container>
            <jvmFlags>
                  <jvmFlag>-javaagent:/data0/java/deploy/pinpoint.agent/pinpoint-bootstrap.jar</jvmFlag>
                  <jvmFlag>-Dpinpoint.agentId=docker</jvmFlag>
                  <jvmFlag>-Dpinpoint.applicationName=docker-test</jvmFlag>
            </jvmFlags>
      <mainClass>com.fangdd.bwfs.server.container.Application</mainClass>
      <exec>CMD</exec>
</container>
```

**Comment by chanseokoh** [comment]
Hi @swift1911,

Let me check if I understood you correctly: you don't want Jib to overwrite the entrypoint and CMD, and you just Jib to just inherit and use the entrypoint of CMD that whatever base image has, right?

**Comment by swift1911** [comment]
@chanseokoh Yes, this is the meaning

**Comment by chanseokoh** [comment]
Now the question is, where/how to indicate Jib to not overwrite the entrypoint and CMD, e.g., a new configuration parameter or a system property?

**Comment by swift1911** [comment]
@chanseokoh i think that a a new configuration parameter is better

**Comment by swift1911** [comment]
@coollog this is my Dockerile, i want to use s6-overlay to init and handle pid 1
```
FROM alpine
RUN apk add busybox-extras bash vim lsof strace pstree git curl tzdata
ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.4.0/s6-overlay-amd64.tar.gz /tmp/
RUN gunzip -c /tmp/s6-overlay-amd64.tar.gz | tar -xf - -C /
ENV TZ Asia/Shanghai
ENTRYPOINT ["/init"]
```

**Comment by loosebazooka** [comment]
@swift1911 so you're expected execution is something like?

```
/init java -cp <some-classpath> <some-main-class> ...
```

**Comment by swift1911** [comment]
@loosebazooka yes

**Comment by coollog** [comment]
Hi @swift1911, have you tried using the `<entrypoint>` configuration?

```xml
<container>
  <entrypoint>/init</entrypoint>
</container>
```

**Comment by swift1911** [comment]
@coollog in some condition, /init command might be replace by other, hard code /init in jib may cause tech debt
