### ISSUE TITLE
[Gradle] Ability to specify absolute path of credential helper

### ISSUE THREAD

**Issue by anuraaga** [GoogleContainerTools/jib#925]
**Description of the issue**:

Currently it is only possible to specify the credential helper suffix (e.g., gcr). This requires an executable `docker-credential-gcr` to be on the `PATH`. This manipulation of the `PATH` may not be ideal, i.e., to allow builds to be reproducible on multiple environments.

**Expected behavior**:
It is possible to specify the absolute path to a credential helper. I believe`jib-core` already supports passing a `java.nio.Path` and it just needs to be exposed.

**Comment by chanseokoh** [comment]
Hi @anuraaga,

Can you elaborate on what is your exact use case? Also, do you want this to be a configurable parameter in `pom.xml` or `build.gradle` that you want to check in in a VCS? Or is it OK if you can specify that in a command line? Do you just want to fix a location where `docker-credential-gcr` is located, or do you also need to be able to specify an arbitrary command name (i.e., not starting with `docker-credential` prefix)?

**Comment by anuraaga** [comment]
Hey - my use case is that a Gradle task automatically downloads the `gcloud` sdk and extracts it into a location under `gradle.userHomeDir`. This way users don't have to worry about downloading SDKs, etc, the build takes care of everything and a task like `:gcloudLoginToCluster` can execute the downloaded SDK's `gcloud` to generate kubeconfig, for example and jib should "just work". But in this case, the `gcloud` SDK, which includes`docker-credential-gcr` is not on the system `PATH`, it is managed by Gradle.

Being able to specify the exact path to the credential helper on a Gradle script would be great. From what I could tell, this might be trivial since this method in core exists that takes a `Path`.

https://github.com/GoogleContainerTools/jib/blob/master/jib-core/src/main/java/com/google/cloud/tools/jib/frontend/CredentialRetrieverFactory.java#L117

**Comment by coollog** [comment]
I believe we can allow `credHelper` to be specified with a path to a credential helper executable (along with the credential helper suffix as we have now). The value specified would first check for existence as a file and then try to be used as a credential helper suffix.

**Comment by coollog** [comment]
Hi @anuraaga , we've released version `0.10.0` with the ability to set a full path as the `credHelper`!

**Comment by anuraaga** [comment]
Thanks! Verified it works great.
