### ISSUE TITLE
<to><image></image></to> is ignored

### ISSUE THREAD

**Issue by sergeygalkin** [GoogleContainerTools/jib#927]
**Description of the issue**:
Then I try set <to><image></image></to> this setting is ignored

**Expected behavior**:
Containerizing application to gcr.io/project-1111/something_not_web:namespace

**Steps to reproduce**: 
Try to build module with
export PROJECT_ID=project-1111
export JAVA_IMAGE='gcr.io/distroless/java'
export NAMESPACE_NAME=namespace
export JIB_VERSION='0.9.10' 
mvn compile -pl web jib:build

**Environment**: 
Gentoo, Ubuntu, Apache Maven 3.3.9

**`jib-maven-plugin` Configuration**: 
```xml
            <plugin>
                <groupId>com.google.cloud.tools</groupId>
                <artifactId>jib-maven-plugin</artifactId>
                <version>${env.JIB_VERSION}</version>
                <configuration>
                  <to>
                    <image>gcr.io/${env.PROJECT_ID}/something_not_web:${env.NAMESPACE_NAME}</image>
                  </to>
                  <from>
                      <image>${env.JAVA_IMAGE}</image>
                  </from>
                  <container>
                    <useCurrentTimestamp>true</useCurrentTimestamp>
                  </container>
                </configuration>
            </plugin>
```

**Log output**: 

╰─➤ mvn compile -pl web   jib:build           
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=lcd_hrgb
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building project-web 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ web ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ web ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- jib-maven-plugin:0.9.10:build (default-cli) @ web ---
[WARNING] Setting image creation time to current time; your image may not be reproducible.
[WARNING] Base image 'gcr.io/distroless/java' does not use a specific image digest - build may not be reproducible
[INFO] 
[INFO] Containerizing application to gcr.io/project-1111/web:null...
[INFO] 
[INFO] Retrieving registry credentials for gcr.io...
[INFO] Getting base image gcr.io/distroless/java...
[INFO] Building dependencies layer...
[INFO] Building snapshot dependencies layer...
[INFO] Building resources layer...
[INFO] Building classes layer...
[INFO] Finalizing...
INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 32.923 s
[INFO] Finished at: 2018-09-04T20:06:43+04:00
[INFO] Final Memory: 66M/562M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build (default-cli) on project web: Build image failed: Read timed out -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Additional information**
Read timed out is not jib issue it seems what this is the  https://status.cloud.google.com//incident/cloud-dev-tools/18003 but
_[INFO] Containerizing application to gcr.io/project-1111/web:null.._ is incorrect

in this time 
```xml
<from><image>${env.JAVA_IMAGE}</image></from>
```
and 
```xml
<version>${env.JIB_VERSION}</version>
```
 is working fine

**Workaround**
```
mvn compile -pl web -Dimage=gcr.io/project-1111/something_not_web:namespace  jib:build
``` 
Is working as expected

**Comment by coollog** [comment]
Hi @sergeygalkin , I see you have `export PROJECT_ID=`. That should be `export PROJECT_ID=project-1111` in your case right?

**Comment by sergeygalkin** [comment]
@coollog yes, sorry for inaccuracy

**Comment by chanseokoh** [comment]
Looks like your project is a multi-module project. Can you share all the `pom.xml` files (excluding some sensitive info, if any)?

**Comment by sergeygalkin** [comment]
It was my bad, sorry guys.
I have added <images> in main <properties> and forgot about it
