### ISSUE TITLE
Give access to Image ID

### ISSUE THREAD

**Issue by remmeier** [GoogleContainerTools/jib#933]
Docker v1.10 introduced a content/digest-based image ID to uniquely identify docker images. It would be great if this image ID would be available from the gradle (and maybe maven) plugin after the image has been built or is deemed being already up-to-date. 

Having the image ID would, for example, let the subsequent deployment processes skip containers that do not change (without having to resolve tags to image ids or workaround with manual mechanisms). This is of particular importance for larger multi-project gradle setups / single repository approaches where a single build manages multiple images.

**Comment by coollog** [comment]
Hi @remmeier , after some discussions over how to provide the user with the digest output, we are planning to have the Jib tasks/goals output a `jib-image.digest` into the build output directory (`build/jib-image.digest` for Gradle/`target/jib-image.digest` for Maven). This file will contain the container image digest. Will this be adequate for your use case?

**Comment by remmeier** [comment]
yes thx, that would be a great help.

**Comment by briandealwis** [comment]
Just so I'm clear @coollog, you are proposing we write out the manifest digest (type `application/vnd.docker.distribution.manifest.v2+json`, not the container configuration digest (type `application/vnd.docker.container.image.v1+json`)?

(`docker images --digests` reports the container configuration digests as the _Image ID_, and the manifest digest as _Digest_. The manifest references the container configuration as _config.digest_.)

**Comment by coollog** [comment]
Yes, the manifest digest, which is the digest portion of the image reference if it's qualified with a digest (ie. `gcr.io/distroless/java@sha256:bb1c9179c2263733f235291998cb849d52fb730743125420cf4f97a362d6a6dd` where `sha256:bb1c9179c2263733f235291998cb849d52fb730743125420cf4f97a362d6a6dd` is the image digest.

**Comment by coollog** [comment]
Hmm, maybe we should write out `jib-image.id` as well. @remmeier Do you happen to need the Docker Image ID (config digest) or is the image digest enough?

**Comment by remmeier** [comment]
thx a lot! I'm ok with either. i could imagine that some people may expect the docker image id as it is well establusged

**Comment by coollog** [comment]
Filed #1204 for that!

**Comment by coollog** [comment]
Hi @remmeier , @sdavids, @novotnyr, @keykey7, @Tanmayshetty, version `0.10.0` has been released with the image digest written out to a `jib-image.digest` file in the build output directory.
