### ISSUE TITLE
Consider making JibContainerBuilder interface more fluent.

### ISSUE THREAD

**Issue by coollog** [GoogleContainerTools/jib#953]
Continuing from #881...

Considering that we are modeling `JibContainerBuilder`'s interface off of the `Stream` API, and that `JibContainerBuilder` begins with `Jib.from`, we should probably make the rest of the API more fluent as well.

`addLayer(List<Path>, String)` -> `layer(List<Path>, String)`
`addLayer(LayerConfiguration)` -> `layer(LayerConfiguration)`
`setLayers(List<LayerConfiguration>)` -> `layer(List<LayerConfiguration>)`
`setEntrypoint(List<String>/String...)` -> `entrypoint(List<String>/String...)`
`setProgramArguments(List<String>/String...)` -> `programArguments(List<String>/String...)`
`setEnvironment(Map<String, String>)` -> `environment(Map<String, String>)`
`setEnvironmentVariable(String, String)` -> `environmentVariable(String, String)`
`setExposedPorts(List<Port>/Port...)` -> `expose(List<Port>/Port...)`
`addExposedPort(Port)` -> `expose(Port)`
`setLabels(Map<String, String>)` -> `label(Map<String, String>)`
`addLabel(String, String)` -> `label(String, String)`

Also, currently, the collection setters (like `setExposedPorts`) replace previously-set ports. If converting to use this more fluent API, these collection setters should append, not replace. We could add methods like `exposeOnly(Map)` that behaves like the original setters.

**Comment by briandealwis** [comment]
We could provide `exposeOnly(Map<>)` variants that take a `Map`?

**Comment by TadCordle** [comment]
Should we close this? Haven't had any discussions about it in a while (personally I like the explicit API over the fluent one).

**Comment by briandealwis** [comment]
@loosebazooka recently turned appengine-plugins-core to the more fluent approach.  I think it looks better, but I don't feel strongly.

**Comment by loosebazooka** [comment]
I just made everything a builder: ¯\_(ツ)_/¯

**Comment by briandealwis** [comment]
You also did `setX()` &rarr; `x()`

**Comment by coollog** [comment]
Closing and sticking with current design since it is clearer in the functions' intentions, especially for methods like `addExposedPort` vs `setExposedPort` (`expose` vs `exposeOnly` is less clear and still involves extra `Only` portion).
