### ISSUE TITLE
How to package Spring Boot Executable Jar to Docker image?

### ISSUE THREAD

**Issue by AlekseyChudov** [GoogleContainerTools/jib#954]
Spring Boot Gradle and Maven plugins produce single Executable Jar file as described in reference docs
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#getting-started-first-application-executable-jar
https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#executable-jar

It would be nice if jib supports this, pack just a single file into the image and use `-jar, /app/libs/app.jar` option instead of `-cp, /app/resources/:/app/classes/:/app/libs/*, app.Main`.

How to package Spring Boot Executable Jar to Docker image? Maybe it can be possible to achieve the same effect through some jib settings?

**Comment by loosebazooka** [comment]
Unless you have some special configuration, this should work out of the box? What issues are you running into?

**Comment by AlekseyChudov** [comment]
Do you mean jib supports Spring boot jar out of the box?

I have just tested my simple IDEA project configuration

```
mkdir -p gradle-project/src/main/java/com/example
cd gradle-project
gradle init

cat << EOF > build.gradle
plugins {
    id 'com.google.cloud.tools.jib' version '0.9.10'
    id 'org.springframework.boot' version '2.0.4.RELEASE'
}

apply plugin: 'idea'
apply plugin: 'java'
apply plugin: 'io.spring.dependency-management'

version = '1.0'

sourceCompatibility = 1.8

jib {
    from {
        image = 'gcr.io/distroless/java'
    }
    to {
        image = rootProject.name + ':' + version
    }
}

idea {
    module {
        inheritOutputDirs = false
        outputDir = file 'build/classes/java/main'
        testOutputDir = file 'build/classes/test/main'
    }
}

repositories {
    mavenCentral()
}

dependencies {
    compile 'org.springframework.boot:spring-boot-starter'

    testCompile 'org.springframework.boot:spring-boot-starter-test'
}
EOF

cat << EOF > src/main/java/com/example/App.java
package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(App.class, args);
    }
}
EOF
```

Spring boot jar created as expected
```
./gradlew bootJar
java -jar build/libs/gradle-project-1.0.jar
```

But jib uses multiple files instead of single boot jar.
```
$ ./gradlew jibDockerBuild
warning: Base image 'gcr.io/distroless/java' does not use a specific image digest - build may not be reproducible

Containerizing application to Docker daemon as gradle-project:1.0...

Getting base image gcr.io/distroless/java...
Building dependencies layer...
Building classes layer...
Finalizing...
Loading to Docker daemon...

Container entrypoint set to [java, -cp, /app/resources/:/app/classes/:/app/libs/*, com.example.App]

Built image to Docker daemon as gradle-project:1.0
```

**Comment by coollog** [comment]
Hi @AlekseyChudov , is there a reason you need to use the JAR over the normal Jib container?

**Comment by AlekseyChudov** [comment]
The only reason is my personal interest in how to get application running using the same jar file and the same command-line options, both on the bare server and in the container.

**Comment by coollog** [comment]
@AlekseyChudov You can configure command line options via the `jib.container.jvmFlags` parameter.

To use the JAR itself, you can set some configuration options to have Jib copy the JAR into the container:

`build.gradle`:
```groovy
jib {
    extraDirectory = bootJar.destinationDir
    container.entrypoint = ['java', '-jar', bootJar.archiveName]
}
```

**Comment by AlekseyChudov** [comment]
It's too easy. I should have guessed :)

Also dependencies should be added to make tasks work
```
jibBuildTar.dependsOn bootJar
jibDockerBuild.dependsOn bootJar
jibExportDockerContext.dependsOn bootJar
```

**Comment by AlekseyChudov** [comment]
Do you consider using Spring boot jar in a container as a bad practice?

Just for clarification. I like the Jib plugin because it allows me to store the entire configuration in a single project build file and not use Dockerfile and command executable calls. For this to work absolutely perfect, the /app directory should be excluded from image, since it is not used in this case.

**Comment by chanseokoh** [comment]
@AlekseyChudov a single executable JAR is one of the main points of Spring Boot, so putting a Spring Boot JAR in a container is not a bad practice for sure. In fact, I think this is the usual way and probaly the only sane way to containerize a Spring Boot app, *until you use Jib*. So, in some sense, one difference is that the Spring JAR includes everything it needs to run the app, and with Jib, you can easily create a container that includes everything at the container level without the need of a single fat JAR.

Lastly, currently there is no way to exclude /app, so you probably don't want the workaround to add the Spring Boot JAR, as you said. You are just dropping in one additional file into the current image that Jib builds, so you are actually duplicating everything, including dependency JARs, .class files, etc.

**Comment by AlekseyChudov** [comment]
Thank you very much for the detailed explanations.
