### ISSUE TITLE
Limitation of `LayerConfiguration.addEntry()`

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#957]
We've been OK, but I think this will matter more when we release jib-core as a library.

Let's say I have
```
/usr/home/user/extra-files/file1
/usr/home/user/extra-files/file2
/usr/home/user/extra-files/sub/file3
/usr/home/user/extra-files/sub/file4
/usr/home/user/extra-files/sub/directory/file5
/usr/home/user/extra-files/sub/directory/file6
```

Some observations (abusing Java syntax):
- Adding the root directory: `addEntry([/usr/home/user/extra-files/], /dest/in/image)` results in
   ```
   /dest/in/image/extra-files/file1
   /dest/in/image/extra-files/file2
   /dest/in/image/extra-files/sub/file3
   /dest/in/image/extra-files/sub/file4
   /dest/in/image/extra-files/sub/directory/file5
   /dest/in/image/extra-files/sub/directory/file6
   ```
- Adding files: `addEntry([/usr/home/user/extra-files/file1], /dest/in/image)` results in
   ```
   /dest/in/image/file1
   ```

Now, suppose that I want to put only some of the files from `/usr/home/user/extra-files/` into `/dest/in/image/extra-files/` so that the image will look like
   ```
   /dest/in/image/extra-files/file1
   /dest/in/image/extra-files/sub/file3
   /dest/in/image/extra-files/sub/directory/file5
   ```
Currently, the only way I can see to achieve this is to create three separate layers with different destination paths like below. There seems no way to create a single layer that contains the three files.
```
addEntry([/usr/home/user/extra-files/file1],
         /dest/in/image/extra-files)
addEntry([/usr/home/extra-files/sub/file3],
         /dest/in/image/extra-files/sub)
addEntry([/usr/home/extra-files/sub/directory/file5],
         /dest/in/image/extra-files/sub/directory)
```

Lastly, I think the following Javadoc of `addLayer()` is not correct:
```
     * @param sourceFiles the source files to build from. Source files that are directories will
     *     have all subfiles in the directory added (but not the directory itself)
```
As can be seen from the example above, if the source path is a directory, the directory itself is added too. (`extra-files/` in the above example)

**Comment by coollog** [comment]
Yep! I'm actually fixing this currently via #956.

**Comment by coollog** [comment]
Yes, this is no longer an issue.
