### ISSUE TITLE
Add skaffold helpers to jib-maven-plugin

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#958]
Add helpers so any integration with skaffold can extract the necessary information.

~~1. See if multimodule or not~~ (this can be done directly with `mvn help:evaluate -Dexpression=project.modules`)
2. Get all source files to watch (`jib:_skaffold-files`)
3. Get jib goals on package phase (more useful for multimodule builds - might be ignore for single module) (`jib:_skaffold-package-goals`)

**Comment by TadCordle** [comment]
Is this the same as https://github.com/GoogleContainerTools/jib/issues/864?

**Comment by loosebazooka** [comment]
well I guess it's the maven specific part of #864
