### ISSUE TITLE
extra directory should resolve smarter for non-absolute paths

### ISSUE THREAD

**Issue by loosebazooka** [GoogleContainerTools/jib#962]
Currently extra directory is resolved to the execution directory, not the project path. This is fine unless you're in a multi module situation, in which case you want it to resolve to the project.baseDir.

For example a user may configure it one of two ways
```xml
<extraDirectory>src/main/custom-jib</extraDirectory>
<!-- OR -->
<extraDirectory>${project.baseDir}/src/main/custom-jib</extraDirectory>
```

solution is to do something like this:
```java
    Path extraDirectoryPath = Paths.get(extraDirectory);
    if (extraDirectoryPath.isAbsolute()) {
      return extraDirectoryPath;
    }
    else {
      return project.getBasedir().toPath().resolve(extraDirectory);
    }
```

This is how maven-resources appear to be resolved.

**Comment by loosebazooka** [comment]
Actually I think it should just be resolved to "File" directly, not string.

**Comment by coollog** [comment]
We should probably add a CHANGELOG entry for this fix.
