### ISSUE TITLE
Add "container.appRoot" config parameter

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#964]
The default will be `/app`, so when not explicitly given, the normal non-WAR Jib builds will work as before.

Knowing that users can already configure `ENTRYPOINT`, this new config parameter will help people use an arbitrary Servlet engine as a base image for building a WAR image (#431). In the WAR case, the default value will be `/jetty/webapps/ROOT`. (The default base image will be `gcr.io/distroless/java/jetty`.)

Don't forget to add docs after releasing it.

**Comment by coollog** [comment]
Alternative naming suggestion: `container.app.root` or `container.appRoot`

**Comment by chanseokoh** [comment]
`container.appRoot` sounds good. `.app.root` looks like two levels.

**Comment by loosebazooka** [comment]
I like appRoot as the param name. Can you show how it will look in gradle/maven config?

**Comment by chanseokoh** [comment]
I image this is under `<container>`, specifying a single directory as a string type.

```groovy
  jib.container.appRoot = '/app'
```

```xml
  <configuration>
    <container>
      <appRoot>/app</appRoot>
    </container>
  </configuration>
```

**Comment by chanseokoh** [comment]
Should add a doc.

**Comment by TadCordle** [comment]
Added this to the README (reopen if you meant something else)
