### ISSUE TITLE
Make possible to read JVM opts from ENV

### ISSUE THREAD

**Issue by velo** [GoogleContainerTools/jib#990]
**Description of the issue**:

Currently, JVM OPTS are hardcode during the image build.
What I would like to do is to override it at runtime by setting environment variables with different/extra JVM opts

**Comment by loosebazooka** [comment]
Instructions available here: https://github.com/GoogleContainerTools/jib/blob/master/docs/faq.md#how-do-i-set-parameters-for-my-image-at-runtime

Does this work for you?

**Comment by velo** [comment]
RTFM, sorry for that and thank you for the link
