### ISSUE TITLE
UnixPath class for strictly accepting Unix-style path

### ISSUE THREAD

**Issue by chanseokoh** [GoogleContainerTools/jib#992]
From https://github.com/GoogleContainerTools/jib/pull/984#issuecomment-422042180

We don't build Windows images, so some image-building components work on the assumption that given paths are in Unix-style. We could introduce `UnixPath` to replace `Path`, and a class like `LayerType` or `LayerEntry` could accept `UnixPath`. If implementing `UnixPath` as a replacement for `Path` may look like an over-engineering, at least we could make `UnixPath` as a convenient util class for conversion to and from Unix paths and checking if a path is a Unix one.

**Comment by coollog** [comment]
Possible `UnixPath` API:

`static UnixPath fromPath(Path path)`
`static UnixPath fromPathString(String path)`
`UnixPath resolve(UnixPath/String/Path)`
`boolean isAbsolute()`
`String toString()`

**Comment by coollog** [comment]
I'll take a stab at this and see how useful it is.

**Comment by TadCordle** [comment]
Looks like this was already finished.
