### ISSUE TITLE
Failure to connect to Nexus proxy repository via HTTP in Maven build.

### ISSUE THREAD

**Issue by brianrodecap** [GoogleContainerTools/jib#993]
**Description of the issue**:  Attempting to proxy Docker Hub using Sonatype Nexus as "docker-hub" and push image to hosted "docker-private" repo.  Request to Nexus results in 404.  Why is jib adding "v2" to the connection string?  Any feedback would be appreciated.

**Expected behavior**:  Built and pushed image.

**Steps to reproduce**: mvn jib:build

**Environment**: Windows 7, Maven 3.5.0, Java 1.8.0_131

**`jib-maven-plugin` Configuration**:
```xml
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>jib-maven-plugin</artifactId>
	<version>0.9.10</version>
	<configuration>
	    <allowInsecureRegistries>true</allowInsecureRegistries>
		<from>
			<image>my-nexus:8081/repository/docker-hub/openjdk:8-jre-alpine</image>
		</from>
		<to>
			<image>my-nexus:8081/repository/docker-private/${project.groupId}/${project.artifactId}:${project.version}</image>
		</to>
	</configuration>
</plugin>
```

**Log output**:
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building my-app 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- jib-maven-plugin:0.9.10:build (default-cli) @ my-app---
[INFO]
[INFO] Containerizing application to my-nexus:8081/repository/docker-private/com.chicosfas/my-app:1.0.0-SNAPSHOT...
[INFO]
[INFO] Retrieving registry credentials for my-nexus:8081...
[INFO] Getting base image my-nexus:8081/repository/docker-hub/openjdk:8-jre-alpine...
[INFO] Building dependencies layer...
[INFO] Building classes layer...
[INFO] Building resources layer...
[WARNING] Cannot verify server at https://my-nexus:8081/v2/repository/docker-hub/openjdk/manifests/8-jre-alpine. Attempting again with no TLS verification.
[WARNING] Cannot verify server at https://my-nexus:8081/v2/. Attempting again with no TLS verification.
[WARNING] Failed to connect to https://my-nexus:8081/v2/ over HTTPS. Attempting again with HTTP: http://my-nexus:8081/v2/
[WARNING] Failed to connect to https://my-nexus:8081/v2/repository/docker-hub/openjdk/manifests/8-jre-alpine over HTTPS. Attempting again with HTTP: http://my-nexus:8081/v2/repository/docker-hub/openjdk/manifests/8-jre-alpine
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.135 s
[INFO] Finished at: 2018-09-17T12:48:04-04:00
[INFO] Final Memory: 34M/392M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:0.9.10:build (default-cli) on project my-app: Build image failed: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
[ERROR]  at [Source: (String)"
[ERROR] <!DOCTYPE html>
[ERROR] <html>
[ERROR] <head>
[ERROR]   <title>404 - Nexus Repository Manager</title>
[ERROR]   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
[ERROR]
[ERROR]
[ERROR]   
[ERROR]   <link rel="icon" type="image/png" href="http://my-nexus:8081/favicon-32x32.png?3.12.1-01" sizes="32x32">
[ERROR]   <link rel="mask-icon" href="http://my-nexus:8081/safari-pinned-tab.svg?3.12.1-01" color="#5bbad5">
[ERROR]   <link rel=""[truncated 1324 chars]; line: 2, column: 2]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Additional Information**: Nexus credentials are provided in settings.xml.

**Comment by brianrodecap** [comment]
The root cause of my connectivity issues was mis-configuration of Repository Connectors:

https://support.sonatype.com/hc/en-us/articles/115013153887-Docker-Repository-Configuration-and-Client-Connection

```xml
<plugin>
	<groupId>com.google.cloud.tools</groupId>
	<artifactId>jib-maven-plugin</artifactId>
	<version>0.9.10</version>
	<configuration>
	    <allowInsecureRegistries>true</allowInsecureRegistries>
		<from>
			<image>my-nexus:8082/openjdk:8-jre-alpine</image>
		</from>
		<to>
			<image>my-nexus:8083/${project.artifactId}:${project.version}</image>
		</to>
	</configuration>
</plugin>
```

**Comment by chanseokoh** [comment]
Thanks for the update @brianrodecap
